### ISSUE TITLE
SAP TechEd Barcelona 2017, November 14 to 16

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1003]
Hi All,
I'll be in Barcelona for #SAPTechEd, is anybody else going? Should we meet up and say hi?

I dont think there is any abapGit related stuff on the official agenda.

**Comment by gopalnair** [comment]
There was session regarding ABAPGit in SAP Teched LasVegas - 2017 from Mr Graham. Would have loved to meet you there. Oh well... there is always TechEd 2018 :)

**Comment by christian102094** [comment]
Hope to meet in TechEd 2018 :)

**Comment by Sdfraga** [comment]
Hello Lars, I will be at Barcelona.
Will you animate any session this year?

**Comment by larshp** [comment]
Currently there is nothing planned

**Comment by larshp** [comment]
Hi All,
I have booked a networking session, Wednesday 15th, from 12:00 to 12:30

**Comment by Sdfraga** [comment]
Hi @larshp ,

Your session is not showing on the Agenda builder in the TechEd site.

**Comment by larshp** [comment]
the networking sessions are not in the agenda yet, wait a week or so

**Comment by larshp** [comment]
https://sessioncatalog.sapevents.com/go/agendabuilder.sessions/?l=159&sid=53819_475466&locale=en_US

**Comment by larshp** [comment]
Best slide for #SAPTechEd Barcelona,
![image](https://user-images.githubusercontent.com/5888506/32413183-34f7b246-c20c-11e7-84c9-ae492cc55abf.png)

@insidy @apex8 @mkaesemann I can add your real names if you like, add a comment here or update your github profile 😄

**Comment by apex8** [comment]
Cool! 
Yes, please put my name there; its Alexander Petrenz
Thanks :)

**Comment by larshp** [comment]
thanks, updated 😄 
![image](https://user-images.githubusercontent.com/5888506/32414580-8bb67f18-c22a-11e7-8e82-64bfc0edb41d.png)

**Comment by apex8** [comment]
Great :)

**Comment by mkaesemann** [comment]
Of course you can replace the nickname with my real name as well: Michael Käsemann.
Though I'm not sure that one minor pull request actually qualifies me to actually be on any slides ;-)

**Comment by larshp** [comment]
all contributors are important 😄

**Comment by grahamrobbo** [comment]
In my abapGit presentations I always quote something @larshp said to me once - "Even logging issues is contributing" :)

**Comment by larshp** [comment]
presentation here: https://larshp.github.io/Presentations/teched-2017-emea/

**Comment by larshp** [comment]
From my session,
![do17es5wsaai1x5](https://user-images.githubusercontent.com/5888506/32977714-2950a6c4-cc33-11e7-838c-92b0b65bedd9.jpg)

Björn Goerke's laptop:
![doqoibxxkamn5xw](https://user-images.githubusercontent.com/5888506/32977716-3695682e-cc33-11e7-9d4c-dad50142ea9a.jpg)
