### ISSUE TITLE
SCP1 Business configuration set

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#1004]
Rather than supporting complete customizing transport request serializing it might be easier to support business configuration sets (object type SCP1). Seems to be bundled customizing content in a workbench object type.
https://wiki.scn.sap.com/wiki/display/Basis/Business+Configuration+Sets+%28BC+Sets%29+and+their+use

Transaction SCPR3. In SAP (partner) addon development there is a similar issue of not being able to deliver customizing tasks, so the recommended approach there is to use these.

Haven't checked if this object type is in abapGit-plugins but it's not mentioned at all in [this](http://docs.abapgit.org/ref-supported.html) list.

![image](https://user-images.githubusercontent.com/5270359/31585256-33c0af0c-b1bf-11e7-8c70-071586cbc267.png)

reference: #800

**Comment by larshp** [comment]
this looks really good, solving the issue with relating the customizing rows to a package 👍

**Comment by flaiker** [comment]
Table SCPRVALS and others
Funtion groups SCPRTM, SCPRPS
Function modules SCPR_TEMPL_MN_TEMPLATE_SAVE, SCPR_PRSET_MN_BCSET_SAVE
Package SCPR

**Comment by larshp** [comment]
wonder if this can be used for roles too, https://github.com/larshp/abapGit/issues/827, @EduardoCopat

**Comment by flaiker** [comment]
I am currently quite busy unfortunately, so if anyone wants to implement this sooner, feel free to do so.

**Comment by larshp** [comment]
function module SCPR_MN_BCSET_DOWNLOAD can download the BC set to a text file

function module SCPR_MN_BCSET_UPLOAD uploads

![image](https://user-images.githubusercontent.com/5888506/41048030-2a0ed1d0-69ae-11e8-8fb5-a444e61bfd15.png)

**Comment by larshp** [comment]
todo: Hierarchical/Sets of sets are not supported

**Comment by rjbhayani** [comment]
> function module SCPR_MN_BCSET_DOWNLOAD can download the BC set to a text file
> 
> function module SCPR_MN_BCSET_UPLOAD uploads
> 
> looks like the right function modules are there
> 
> ![image](https://user-images.githubusercontent.com/5888506/41048030-2a0ed1d0-69ae-11e8-8fb5-a444e61bfd15.png)

is it possible to export bc set/Tables from one system to another using github ?
