### ISSUE TITLE
Different include naming when deserializing function group

### ISSUE THREAD

**Issue by thomas-erdoesi** [larshp/abapGit#1005]
When deserializing functions, the corresponding include name is generated by SAP coding and may not match the include name from the original system. This difference is then considered as a local modification. Excluding the include name of the function from the serialized information would solve the issue.

**Comment by thomas-erdoesi** [comment]
Pull request: #1006

**Comment by larshp** [comment]
@thomas-erdoesi can this issue be closed?

**Comment by thomas-erdoesi** [comment]
Sorry! Yes, this can be closed.
