### ISSUE TITLE
Program abort when trying to select a branch in Clone Action

### ISSUE THREAD

**Issue by mkaesemann** [larshp/abapGit#1010]
When a Clone action is triggered and the user selects an action in the popup that requires authentication, abapGit aborts processing with an error message:
![2017-10-17_15h01_03](https://user-images.githubusercontent.com/32765685/31672126-f883e62c-b35b-11e7-9adc-4126582cbf8a.png)

The reason is that abapGit tries to bring up the popup for the user authentication (user/password) in lcl_password_dialog=>popup with a selection screen, while in a modal dialog box (the POPUP_GET_VALUES_USER_BUTTONS function module with the repository request). This is not allowed.

Normally I would probably just move the user dialog to a separate function module to get a second modal dialog to be called from the first, but that would not be compatible with the "easy installation" target of abapGit. So before I do a pull request that is going to be rejected anyhow, I am just reporting it for now.

**Comment by larshp** [comment]
yeah, also see https://github.com/larshp/abapGit/issues/658

**Comment by mkaesemann** [comment]
Any reason why you don't simply replace the password dialog with a modal dialog?
Example:
```abap
    DATA: st_sval    TYPE sval,
          lt_sval    TYPE STANDARD TABLE OF sval
                       WITH DEFAULT KEY,
          returncode TYPE c LENGTH 1.

    CLEAR: st_sval.
    st_sval-tabname    = 'ETS_HTTP_DEST_INFO'.
    st_sval-fieldname  = 'SERVER'.
    st_sval-field_attr = '03'.
    st_sval-fieldtext  = s_url.
    st_sval-value      = iv_repo_url.
    INSERT st_sval INTO TABLE lt_sval.
    CLEAR: st_sval.
    st_sval-tabname   = 'ETS_HTTP_DEST_INFO'.
    st_sval-fieldname = 'PROXY_USER'.
    st_sval-field_obl = 'X'.
    st_sval-fieldtext = s_user.
    st_sval-value     = cv_user.
    INSERT st_sval INTO TABLE lt_sval.
    CLEAR: st_sval.
    st_sval-tabname   = 'ETS_HTTP_DEST_INFO'.
    st_sval-fieldname = 'PASSWORD'.
    st_sval-field_obl = 'X'.
    st_sval-fieldtext = s_pass.
    INSERT st_sval INTO TABLE lt_sval.

    CALL FUNCTION 'POPUP_GET_VALUES'
      EXPORTING
        no_value_check = 'X'
        popup_title    = s_title
      IMPORTING
        returncode     = returncode
      TABLES
        fields         = lt_sval
      EXCEPTIONS
        OTHERS         = 1.

    IF sy-subrc <> 0 OR returncode = 'A'.
      CLEAR: cv_user, cv_pass.
    ELSE.

      LOOP AT lt_sval INTO st_sval.
        CASE st_sval-fieldname.
          WHEN 'PROXY_USER'.
            cv_user = st_sval-value.
          WHEN 'PASSWORD'.
            cv_pass = st_sval-value.
        ENDCASE.
      ENDLOOP.

    ENDIF.```

I've added it to my local ZABAPGIT and it works fine. 
I even used a coding style and a structure that works at least down to ECC 6.0 EhP4 (Can't check lower versions at the moment since our test systems with EhP 0 and 2 are currently down).

I can issue a pull request if needed.

**Comment by larshp** [comment]
Does the above also hide the password?

**Comment by mkaesemann** [comment]
Good point. It does not.
Next alternative would be to call the selection screen in a separate roll area. 
Not as elegant as a function module call, but with the same effect.
I've implemented it on my end and works as well. And this time its hiding the password.
Basically it calls ZABAPGIT again with a `SUBMIT` and adds some code to detect the special "call mode" (i.e. that it should do nothing more than call the dialog and export the values to memory).
If you want I can stage the changes for a pull request.

**Comment by larshp** [comment]
hmm

abapGit uses HTML pages for most of the GUI, so ideally I would suggest making a HTML page instead of the popup, however it requires some effort in the way pages(`lcl_gui_page`) are handled in abapGit

**Comment by mkaesemann** [comment]
Sound logical. But that would also mean that you have to replace the POPUP_GET_VALUES_USER_BUTTONS
function module, because that probably won't allow you to bring up any kind of screen that is not another mode window (i.e. modal dialog).
I've only started to look at abapGit and my HTML is a little rusty, so I don't think I would be able to redo the whole page handling at this point.
So for now I will stick with the popup workaround solution, which avoids the program abort for the tie being. Sometime a workaround is good enough until there is time to do it right :-)
Just let me know if at any point I should create a pull request for the workaround. Otherwise I'll just keep it local, so it doesn't clutter the repository.
