### ISSUE TITLE
Question regarding abapgit.xml

### ISSUE THREAD

**Issue by mkaesemann** [larshp/abapGit#1011]
I have an existing add-on that I want to manage with git and for this purpose I have created a new git repository (in bitbucket, but that should not be relevant for the problem; I hope) in which there is currently nothing but the readme.md a .gitignore and an abapgit.xml I have created manually to set the FOLDER LOGIC to FULL - because the existing add-on has subpackages that do not adhere to the PREFIX rules.
When I did the CLONE in abapGit it came back with an error "PREFIX: Unexpected package naming(/LOT/GC)" (Main Package is /LOT/OS).
Did I misinterpret something when I assumed that putting the abapgit.xml in the repository with the FULL setting that the CLONE should use the setting in the abapgit.xml and allow subpackages with different names than the PREFIX rules?

**Comment by larshp** [comment]
Hmm, this should work, are you running the latest version? I did some changes this Saturday that might fix the issue

**Comment by larshp** [comment]
might be related to https://github.com/larshp/abapGit/issues/992

**Comment by mkaesemann** [comment]
Once you confirmed that it should work this way, I went back to the file and discovered a small spelling error. So this one was my mistake :-(
