### ISSUE TITLE
Question regarding Staging

### ISSUE THREAD

**Issue by mkaesemann** [larshp/abapGit#1014]
Is it possible to filter by "Changed by" when staging changes?
Since the SAP system is a shared system where many developers work at the same time it would be useful to be able to only stage files the developer currently using abapGit has worked on.
One option would be to filter on the "Changed by" column, but using the "filter objects" field does not seem to parse it.

**Comment by sbcgua** [comment]
Currently just name column is matched vs filter. Though it is not very difficult to improve - maybe I'll check it during the weekend.

**Comment by sbcgua** [comment]
![2017-10-21_18h39_56](https://user-images.githubusercontent.com/15635498/31853363-cb16fcce-b68f-11e7-8c42-9f0bc641b939.png)

**Comment by larshp** [comment]
@mkaesemann try again, latest version

**Comment by mkaesemann** [comment]
Works nicely.
Thanks for the fast adoption.
