### ISSUE TITLE
Got shortdump while exporting offline repo into ZIP

### ISSUE THREAD

**Issue by pacroy** [larshp/abapGit#1016]
This happens to 2 packages but not for others.

[Here](https://s3-ap-southeast-1.amazonaws.com/pacroy/XML_CONVERSION_NO_NUMBER.htm) is the short dump.

**Comment by larshp** [comment]
A numeric or packed field contains the invalid value " ", so the XML serialization dumps. Can you try taking a look at the data in the debugger, to see which field it is? Perhaps we can CLEAR the field in abapGit, alternatively you have to fix the invalid values in the database manually

**Comment by larshp** [comment]
there are similar workarounds in DOMA serialization, https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_doma.prog.abap#L161

**Comment by pacroy** [comment]
Thanks for heads-up. It'd take a while to find the problematic object as there are quite a lot in this package.

**Comment by larshp** [comment]
Note that the above issue uses the abapGit-plugins

**Comment by pacroy** [comment]
This seems to be a SCAT object. Here is what I captured from the debugger:

#### LT_STAB
 
```
NAME	VALUE
CAT_VARS	->Standard Table[4x11(806)]
```

#### LT_STAB[1]-VALUE
```
ABLNR	COMMID	SUBID	CALLNO	VARNO	ELEMENT	TAB_INDEX	ELEMLENGTH	TYPE	VALUE	CB_INDEX
ZTMUS_MASS_UPLOAD_IT_2001	&TCD0002	&DYN0001	0000000001	0000000001		000000	000	O	2-	
ZTMUS_MASS_UPLOAD_IT_2001	&TCD0002	&DYN0001	0000000001	0000000002						
ZTMUS_MASS_UPLOAD_IT_2001	&TCD0002	&DYN0001	0000000001	0000000003						
ZTMUS_MASS_UPLOAD_IT_2001	&TCD0002	&DYN0001	0000000001	0000000004	_RESULT	000000	000	O	9	
```

**Comment by larshp** [comment]
Fields TAB_INDEX and ELEMLENGTH are NUMC, they are only allowed to contain 0123456789 characters, guess some of the lines contain spaces

![image](https://user-images.githubusercontent.com/5888506/32141495-44b2d56a-bc82-11e7-8f1e-edfeab2a0142.png)

**Comment by pacroy** [comment]
I've decided to fix data in DB table. But it still fails with the same error. Here is from my debugging. Any advices?

#### SELECT in my own program

```
ABLNR	COMMID	SUBID	CALLNO	VARNO	ELEMENT	TAB_INDEX	ELEMLENGTH	TYPE	VALUE	CB_INDEX
ZTMUS_MASS_UPLOAD_IT_2001	&TCD0002	&DYN0001	0000000001	0000000001		000000	000	O	2-	
ZTMUS_MASS_UPLOAD_IT_2001	&TCD0002	&DYN0001	0000000001	0000000002		000000	000			
ZTMUS_MASS_UPLOAD_IT_2001	&TCD0002	&DYN0001	0000000001	0000000003		000000	000			
ZTMUS_MASS_UPLOAD_IT_2001	&TCD0002	&DYN0001	0000000001	0000000004	_RESULT	000000	000	O	9	
```

#### SELECT into <LT_DATA> at ZCL_ABAPGIT_OBJECT_BY_SOBJ/LCL_TLOGO_BRIDGE/GET_CURRENT_TABLES_CONTENT

```
ABLNR	COMMID	SUBID	CALLNO	VARNO	ELEMENT	TAB_INDEX	ELEMLENGTH	TYPE	VALUE	CB_INDEX
ZTMUS_MASS_UPLOAD_IT_2001_NEW	&TCD0002	&DYN0001	0000000001	0000000001		000000	000	O	2-	
ZTMUS_MASS_UPLOAD_IT_2001_NEW	&TCD0002	&DYN0001	0000000001	0000000002						
ZTMUS_MASS_UPLOAD_IT_2001_NEW	&TCD0002	&DYN0001	0000000001	0000000003						
ZTMUS_MASS_UPLOAD_IT_2001_NEW	&TCD0002	&DYN0001	0000000001	0000000004	_RESULT	000000	000	O	9	
```

**Comment by pacroy** [comment]
Ok, my bads. It's a different object. :P

**Comment by pacroy** [comment]
Fixing data in the DB tables does solve this problem. Thanks!
