### ISSUE TITLE
docs: repeating abapGit and meta tags

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#1018]
following some recent conversation in Slack. @larshp @flaiker 

I guess text occurrence of "abapGit" can be removed. It would be better to mention keywords and proper description in header meta tags.

So it might look like this:

![image](https://user-images.githubusercontent.com/15635498/31854243-3f7a8424-b69e-11e7-970e-7be549ef8fa5.png)

Or maybe like this (repeating the UI design, although not sure)

![image](https://user-images.githubusercontent.com/15635498/31854249-5d2799c6-b69e-11e7-8531-e77f995de0d6.png)

P.S. Some links on SEO topic
https://moz.com/blog/seo-meta-tags
https://www.hobo-web.co.uk/definitive-guide-to-using-important-meta-tags/

**Comment by larshp** [comment]
both looks good to me

**Comment by sbcgua** [comment]
closing then :)
