### ISSUE TITLE
Any support for installing a repository based on a specific branch?

### ISSUE THREAD

**Issue by esjewett** [larshp/abapGit#103]
Specifically, I'm thinking about a workflow with multiple development systems, managing branching/merging from outside SAP/ABAPGit. Currently the fork/pull-request workflow can simulate the branch/merge workflow, but that requires separate Github accounts. Would be nice to be able to support the branch/merge workflow directly by allowing the selection of a branch when installing a repository.

**Comment by larshp** [comment]
no, is currently not implemented, but is a feature that should be added.

The branch name is hardcoded in line ~10830
```abap
    ls_repo-url = <ls_field>-value.
* todo, select branch or tag
    ls_repo-branch_name = 'refs/heads/master'.              "#EC NOTEXT
    lcl_url=>name( ls_repo-url ).         " validate
```
and all branches for the repository is in memory in method ref_discovery, it will probably require a bit of refactoring to make the branches available for the GUI

**Comment by larshp** [comment]
Hi Ethan,
I've implemented the "select branch" feature, there is now a "select branch" button in the clone popup,
![image](https://cloud.githubusercontent.com/assets/5888506/9154173/b0ccff3e-3e83-11e5-9ce1-55771e578978.png)
which will retrieve the branch list and allow the user to choose,
![image](https://cloud.githubusercontent.com/assets/5888506/9154175/bccaf55c-3e83-11e5-8dd9-0ab6256fb678.png)
update to the latest version to try it out

**Comment by esjewett** [comment]
Awesome! Thanks so much! I will give it a shot as soon as possible. Unfortunately no current projects using ABAPGit, but I plan to blog on the general topic soon, so this will get a mention/demo.

**Comment by larshp** [comment]
:thumbsup: just open new issues if you find bugs or have suggestions.

I'm not sure how branching will work for ABAP systems, it would probably require multiple systems. Though might be useful for something if doing retrofitting(http://help.sap.com/saphelp_smehp1/helpdata/en/a3/0aae435a1342e8a56998d83a797161/content.htm).

I also have an evil plan to implement https://github.com/larshp/abapGitServer so clients can keep all code local, without having to send it into the cloud or add extra servers to the current landscape. The server part will also open for some possibilities, however it will take quite some time to implement.

**Comment by esjewett** [comment]
Yes, I think it would require multiple systems. But at least it would allow for development outside of the critical path. It's pretty easy to spin up throw-away systems these days, so it would probably be worth it in a lot of situations. IMO, best practice for ABAP development should be for each dev to have their own dev system and share updates via ABAPGit. Some sort of package and dependency management system would probably be helpful in that scenario as well.

Regarding abapGitServer - makes sense I think. If it supports branches it would kind of allow a way to work around the fact that the built in ABAP VCS doesn't do branches (which makes me sad). ABAPGit should also work fine with a Git server on the private network, no?

**Comment by larshp** [comment]
private network, yes, if it supports git via http as transport protocol.

Gitlab has a free community edition(https://about.gitlab.com/downloads/) that works with abapGit(tested half a year ago)
