### ISSUE TITLE
Performance Issue in Object System

### ISSUE THREAD

**Issue by mkaesemann** [larshp/abapGit#1032]
When performing actions that require a methods of the different object type handlers (`LCL_OBJECT_*` classes), method `lcl_objects->create_object` is processed, which includes a check for the experimental features flag
```abap
    IF lcl_app=>settings( )->read( )->get_experimental_features( ) = abap_true
        AND is_item-obj_type = 'CLAS'.
      lv_class_name = 'LCL_OBJECT_CLAS_NEW'.
    ENDIF.
```
This leads to select on the ZABAPGIT table to read the settings and deserialize them each time a class creation happens, which is basically at least twice per object in the repository (for is_supported check as well as to acquire the handler instance). For repositories with lots of objects this has a huge impact on performance.
By buffering the settings in a fork I did I measured a performance gain of 600-800% for a the read of objects and 150-200% for the serialization for a repository with roughly 11000 objects.
For smaller repositories, like ABAPGIT, the savings similar, although the savings on the serialization side when not as high.

Since settings are not changing frequently I could imagine buffering them would be a valid option.
Unfortuantely I haven't had time to look into the unit testing for abapGit, so I can't verify if buffering in `lcl_persist_settings`, like I did for the test, would in break the unit tests and therefore I did not create a pull request.
Any pointers on what needs to be considered to not break the unit tests? Or is that irrelevant?

**Comment by larshp** [comment]
Cool, thanks, buffering seems like a good idea
