### ISSUE TITLE
WEBI: Endpoints cluster data shown as diff

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1033]
In Service Definitions (WEBI) cluster data is shown always as diff. It seems that it's generated while cloning.
![image](https://user-images.githubusercontent.com/17437789/32043587-7315cd34-ba3b-11e7-91ab-7142fff42816.png)

I'd suggest to clear it while serializing.

**Comment by larshp** [comment]
any idea what the cluster field contains, data wise?

**Comment by christianguenter2** [comment]
hm, it contains the name of the service definition...
![image](https://user-images.githubusercontent.com/17437789/32092733-059c7928-bafa-11e7-9492-4d00aabbb9d4.png)

Here is a little test report to investigate the data cluster.

```
REPORT ztest_import.

PARAMETERS: vepname TYPE vependpoint-vepname OBLIGATORY DEFAULT 'ZTEST_WS'.

DATA: data     TYPE xstring,
      veprefto TYPE veprefto,
      key      TYPE vependpointkey.

SELECT SINGLE * FROM vependpoint
       INTO @DATA(ls_vependpoint)
       WHERE vepname = @vepname.

IF sy-subrc = 0.
  MOVE-CORRESPONDING ls_vependpoint TO key.
  IMPORT ep = data FROM DATABASE vependpoint(vi) ID key.

  IMPORT any = veprefto FROM DATA BUFFER data.
  cl_demo_output=>display( veprefto ).
ENDIF.
```

and the content is always the same data.
![image](https://user-images.githubusercontent.com/17437789/32092874-8976e29c-bafa-11e7-80f9-d3b944479c0e.png)

So currently I don't have a clue where the diff comes from.

**Comment by christianguenter2** [comment]
I also analysed the cluster data with report RSINDX00 and couldn't see any difference. The binary data seems always the same.

![image](https://user-images.githubusercontent.com/17437789/32093277-000c3f14-bafc-11e7-9e98-97ea671267d2.png)


![image](https://user-images.githubusercontent.com/17437789/32093263-fdb1cc0c-bafb-11e7-8049-26e7df6e67a0.png)


Before...
![image](https://user-images.githubusercontent.com/17437789/32093292-0bf4b09a-bafc-11e7-91c6-2da9b6d5a394.png)

...after uninstalling and installing with abapGit
![image](https://user-images.githubusercontent.com/17437789/32093250-f70d6992-bafb-11e7-929b-b050c1f2f21d.png)

**Comment by larshp** [comment]
cool, then I guess it is okay to clear it 😄
