### ISSUE TITLE
Manually Add Objects to Repository

### ISSUE THREAD

**Issue by pacroy** [larshp/abapGit#1038]
I like the concept of syncing 1:1 Package vs. Repository. However, most of existing objects are not well organized. One of package has 2,500+ objects. It would take quite a while to access this repo in abapGit. It'd be good to have a feature that allow user to selectively add object to the repo.

I've tried these but it not working as expected:
- Add and commit only objects we want. This does not solve the processing time problem
- Add objects to .gitignore in .abapgit. This works at some level but not a total solution.

This may related to #681

**Comment by larshp** [comment]
hmm, you can also create a subpackage, and move the objects to that package, and have the subpackage in git?

**Comment by pacroy** [comment]
That might be the one of the simplest solution now. Otherwise, I think about telling developers to manually updating the git (either by *Object to files* or *Ctrl-C + Ctrl-V*) if this is simpler for them.

**Comment by larshp** [comment]
if you are using Git for backup, you can also schedule abapGit to automatically push in background, this does not add any extra steps for the ABAP developers

**Comment by pacroy** [comment]
Ok, thanks. That's really another good idea.

**Comment by larshp** [comment]
setting this to low priority, I dont think this will be supported

**Comment by larshp** [comment]
This user exit can be used to simulate moving objects 1 by 1 to a different package than where it correctly resides, 

![image](https://user-images.githubusercontent.com/5888506/44190667-105b9000-a128-11e8-8c71-8de3fcee6bf2.png)

**Comment by pacroy** [comment]
Thank you for supporting this. I have no plan to use this exit soon but may be later.

**Comment by larshp** [comment]
cool, closing then
