### ISSUE TITLE
unpack not ok when committing multiple DEVC objects

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#1039]
Ref #288 

This just happened to me. Seems to be reproduceable when two `package.devc.xml` are to be committed at the same time. Though this did not happen on the initial DEVC introduction which is weird to me.

![image](https://user-images.githubusercontent.com/5270359/32133919-c06f7dc6-bbe1-11e7-88e5-0801a5b25f4f.png)
![image](https://user-images.githubusercontent.com/5270359/32133923-d03bdccc-bbe1-11e7-9971-e669d0d9ef3f.png)

**Comment by larshp** [comment]
are both packages empty? ie. no objects in the packages

**Comment by larshp** [comment]
issue reproduced,
![image](https://user-images.githubusercontent.com/5888506/32978810-a5c934a8-cc49-11e7-8700-62ad0e67ed15.png)

**Comment by larshp** [comment]
@flaiker try this, https://github.com/larshp/abapGit/pull/1063

**Comment by flaiker** [comment]
Thanks, I'll try and let you know the result.

**Comment by larshp** [comment]
merged, closing
