### ISSUE TITLE
Investigate parallel DD activation

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1055]
Function group SDMP have some interesting function modules, looks like they can be used for parallel activation of DD objects, eg function module DD_MASS_ACT_C3

We should sometime investigate if this can be used, in order to speed up the activation step

log can be shown via `SUBMIT rsputprt`

**Comment by christianguenter2** [comment]
I did some experiments on a bare netweaver 7.51 SP02 developer  edition with
a) current implementation
b) separate DDIC activation with RS_DD_WORKLIST_ACTIVATE
c) separate DDIC activation with DD_MASS_ACT_C3

![image](https://user-images.githubusercontent.com/17437789/35038117-04bd8efa-fb7a-11e7-9c0f-0fb7dd4da7aa.png)

I'd suggest to use separat DDIC activation with FM DD_MASS_ACT_C3 and make it available via the experimental feature flag?

**Comment by larshp** [comment]
yeah, sounds good, lets try out some code

**Comment by larshp** [comment]
We need to consider how to show errors, if activation of an object fails, the user should be notified with eg. the object name?

**Comment by christianguenter2** [comment]
Maybe we can use FM TR_READ_LOG to read the log and show the errors? I'll try it...

**Comment by larshp** [comment]
Thanks, lets keep this issue open so we remember activating the functionality sometime in the future

**Comment by christianguenter2** [comment]
#1466

**Comment by larshp** [comment]
For https://github.com/abapkochbuch/Sources abapGit tries to activate the DDIC objects, with the old logic no errors are shown.

With new parallel logic abapGit shows an error list:
![image](https://user-images.githubusercontent.com/5888506/42034976-00240102-7ae2-11e8-82d6-3ae12775419f.png)

**Comment by larshp** [comment]
above errors are probably just due to the fact that errors did not show up properly with the old logic

**Comment by larshp** [comment]
think we should try activating this by default sometime soon

**Comment by larshp** [comment]
activated in https://github.com/larshp/abapGit/pull/2437, closing
