### ISSUE TITLE
Missing TYPE seo_cs_cache on Installation

### ISSUE THREAD

**Issue by SMilesi** [larshp/abapGit#1057]
i'm on SAP NW 731 (SP6)  so i should be on higher level than the required 702.
When i try to activate the report, i got the error message 

> Type "SEO_CS_CACHE" is unknown

in  METHOD update_cs_number_of_methods.

**Comment by christianguenter2** [comment]
As a workaround, just comment out the affected lines.

**Comment by SMilesi** [comment]
Thanks! worked fine!
