### ISSUE TITLE
ZCL_ABAPGIT_OBJECT_BY_SOBJ - no downgrade for 740 statement

### ISSUE THREAD

**Issue by SMilesi** [larshp/abapGit#1059]
Method distribute_name_to_components contains the following statement available only from ABAP 740
`DATA(lv_remaining_length) = strlen( |{ substring( val = cs_objkey-value off = lv_objkey_sub_pos ) }| ).`

i downgraded it locally to 

```
 data: lv_remaining_length TYPE i.
         lv_remaining_length = strlen( |{ substring( val = cs_objkey-value off = lv_objkey_sub_pos ) }| ).
```

**Comment by larshp** [comment]
cool, feel free to submit a Pull Request for it 😄

**Comment by christianguenter2** [comment]
I think the issue belongs to [abapGit-Plugins](https://github.com/larshp/abapGit-Plugins)?

**Comment by larshp** [comment]
oh, yeah, the code is in https://github.com/larshp/abapGit-Plugins/blob/11cd7db128e57e1040765d530a934af9a55adf14/src/zcl_abapgit_object_by_sobj.clas.locals_imp.abap#L705

**Comment by SMilesi** [comment]
i'm having issues in pushing my commit due SSL error.
As the basis team solves it, i'll push it

**Comment by larshp** [comment]
as an alternative, you can edit the source code via the github web editor

https://help.github.com/articles/editing-files-in-your-repository/

**Comment by SMilesi** [comment]
Thanks :+1:

**Comment by larshp** [comment]
closing issue, feel free to open a new in case of more bugs/questions
