### ISSUE TITLE
abapGit and WEBGUI

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1060]
Has anybody experience with abapGit and WEBGUI? Just fiddled a bit around and got some errors. E.g. in chrome with NW 7.51 SP02 dev edtion the screen is rendered correct. But the links are not working and there are several errors in dev console.

![image](https://user-images.githubusercontent.com/17437789/32855077-083ced6a-ca41-11e7-9041-ab947013ef29.png)

![image](https://user-images.githubusercontent.com/17437789/32854701-c4d3d9ea-ca3f-11e7-8120-701f903c4fd5.png)

Similiar experience with latest version of firefox. Rendering is ok but if I click a link a error site appears saying that 'sapevent' isn't a registered protocol.

Is this due some setup missing in my backend system? Or is it just not yet supported? And if the latter is the case, is there something we can do about it?

**Comment by larshp** [comment]
suggest testing the SAP standard html control demos

**Comment by christianguenter2** [comment]
Report SAPHTML_EVENTS_DEMO works fine. Events are fired and handled correctly. I'll try to investigate what the difference to the abapGit approach is.

![image](https://user-images.githubusercontent.com/17437789/32907639-fdb19b96-cb00-11e7-89b5-97faa5d3600d.png)

**Comment by larshp** [comment]
can we close this one? the JavaGUI fix has been implemented

**Comment by larshp** [comment]
closing
