### ISSUE TITLE
Refactor utility classes to global

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1061]
Follow up on #773.

We have to do (local classes from ZABAPGIT_UTIL):
- [x] lcl_url
- [x] lcl_language
- [x] lcl_state
- [x] lcl_convert
- [x] lcl_hash
- [x] lcl_path
- [x] lcl_diff
- [x] lcl_login_manager
- [x] lcl_progress
- [x] lcl_log

**Comment by larshp** [comment]
cool, note that https://github.com/larshp/abapGit/issues/904 is still not closed, so dont put too much effort into this just yet

**Comment by larshp** [comment]
perhaps you can help testing the CLAS deserialization feature? Enable the experimental and try installing some projects which contains CLAS objects,

![image](https://user-images.githubusercontent.com/5888506/32979029-cd185a08-cc4d-11e7-89fd-96737503dd29.png)

**Comment by christianguenter2** [comment]
Sure, is there something special I have to consider?

**Comment by larshp** [comment]
nah, just try it out :o)

**Comment by larshp** [comment]
okay, sometime soon we will probably move to the new CLAS serialization, feel free to move some classes, but one at a time please, so it is easier to review the PRs

**Comment by larshp** [comment]
I'm starting refactoring lcl_hash

**Comment by larshp** [comment]
in total lets stay below ~50 global classes, after this we need the CLAS deserilization

**Comment by christianguenter2** [comment]
done
