### ISSUE TITLE
How to avoid error messages for not implemented lif_exit methods?

### ISSUE THREAD

**Issue by jfilak** [larshp/abapGit#1065]
I have implemented my own user exit class lcl_user_exit to allow versioning of SAP objects. During an upgrade of abapGit, I got an error message for not implementing some methods of the interface lif_exit.

I wanted to create a base class implementing lif_exit and avoid the need to implement the interface in lcl_user_exit. I would use the base class as the parent of lcl_user_exit and I would just overwrite (redefine in ABAP syntax) the methods I want to change.

However, my plan seems to be impossible because of the behavior of the statement INCLUDE - it cannot be included conditionally.

Why have you put lif_exit into an include?
Can I turn it into zif_abapgit_exit?
Can I add a new class zcl_abapgit_exit_default?

Ahg, I got it! I would not be possible to distribute abapGit in as a single program.

Do you see any possible solution for getting rid of the error messages?

**Comment by larshp** [comment]
just implement the missing method? Alternatively we can move the flag to a global setting

original issue: https://github.com/larshp/abapGit/issues/738

**Comment by jfilak** [comment]
Heh, you are hummorous and I still cannot write good issue descriptions.

I sure know how to fix the issue this time but I want to avoid the same kind of issues in the future.

To clarify the situatio a bit more, the error message is not for the allow_sap_objects method. This method is implemeted. Thank you very much for it!

The error messas is for the 3 methods for proxy configurations - those methods that were added in the commit a43519156430d11966af40f47240db5b0fd6b2cb

Why do I want to avoid the error? Because it is kinda stresfull to pull latest abapGit and cannot activate it due to not implemented methods of a "configuration" interface.

**Comment by larshp** [comment]
yeah, I cannot think of any good mechanisms on 7.02 to avoid the errors, we also need to be "agile" in abapGit which sometimes will cause things to break.

what do you think of moving the configuration to a global abapGit setting?

**Comment by larshp** [comment]
another thought: move it to a global setting, and default it to `IS_SAP_SYSTEM( )`

![image](https://user-images.githubusercontent.com/5888506/33169594-82ac5d6a-d045-11e7-86bf-aa109dd86eb4.png)

**Comment by larshp** [comment]
@jfilak any thoughts on above suggestion?

**Comment by jfilak** [comment]
Well, another idea is to stop using interface and call the methods via reflection. Or maybe we need only a table with key value pairs - then we can keep the interface which would have only a single method - get_configuration.

**Comment by larshp** [comment]
@jfilak see https://github.com/larshp/abapGit/pull/1091, this should remove the need for implementing ZABAPGIT_USER_EXIT

any thoughts?

**Comment by larshp** [comment]
closing
