### ISSUE TITLE
How to add screens of a package into the repo

### ISSUE THREAD

**Issue by lcdszl** [larshp/abapGit#1067]
Hi,
When I add a local package into the repo with the +Offline button, the screens within the package are not added into the repo. How can I add the screens into the repo as well, thanks!

![gitafter](https://user-images.githubusercontent.com/34284944/33630903-f3fbf9fe-d9d6-11e7-9a6e-fe87c30a41ff.png)
![gitbefore](https://user-images.githubusercontent.com/34284944/33630955-fff7a546-d9d6-11e7-9671-42e40bb47a52.png)

**Comment by larshp** [comment]
hi, the screens are part of the program, and exported automatically

try exporting to zip, it will contain a file ztestprogram.prog.xml this xml file will contain the screens

**Comment by lcdszl** [comment]
Thank you very much for the help, I see the screens now.
