### ISSUE TITLE
Documentation on required permissions/et cetera

### ISSUE THREAD

**Issue by przerull** [larshp/abapGit#1068]
This is a really neat tool and I'd really like to implement it in my system.

The issue is that I work in an environment that is *very* conscious about security.   The only way I'll be able to get approval to install this would be if we knew exactly what this tool's dependencies were and where it might perform http requests.   So I have a couple of questions.

1. Does the tool need to send any http requests for offline repositories?
2. Is the tool an implementation of git in abap or does it need to link against a git binary installation?
3. Searching the build code for ABAP4_CALL_TRANSACTION shows that the following transactions are used SE11, SE35, SE61, SE71, SNRO, SE43, SHMA, SICF, SMARTFORMS, SMARTSTYLES, SE72, SE54, SE93, and SMW0.  Do we know what roles/authorization groups are needed to be able to use this program?

Having read the documentation, I'm guessing that the answer to 1 is no and the answer to 2 is yes it's an implementation of git in abap, but I wanted to confirm.

Thanks so much for your time and efforts building and maintaining this tool.  I'm really excited to be able to try this out!

**Comment by larshp** [comment]
1: in offline mode there are no http requests out of the ABAP system. On the frontend PC it uses a few files from cdnjs(search the code for "cdnjs"), note that this is only frontend for the HTML

2: abapGit implements the raw git protocol in ABAP, no link against anything

3: I do not have the full overview of authorizations needed, but if the user have a "normal" developer role, allowing for development of classes + programs + forms + services it should work. Feel free to do a authorization trace, however there might be some places where the code skips authorization checks. Again, I do not see this as much of an issue as the tool is meant for developers

If you do not already have a git server in your landscape, and is conscious about security, you can consider looking into https://github.com/larshp/abapGitServer as it will keep the ABAP code in git on the  ABAP system

**Comment by larshp** [comment]
@przerull did the above help, can we close the issue?

**Comment by larshp** [comment]
closing
