### ISSUE TITLE
Cloning from a internally hosted git repo results in http error 407. SSL handshake with remote server failed. SSLERR_CONN_CLOSED Remote peer has closed the network connection

### ISSUE THREAD

**Issue by johnsmythe** [larshp/abapGit#1069]
Hi, Im just wondering what additional steps is needed to point abapgit client to an internally host git repo. So far i have already installed the certificate from the git repo into the certificate chain via STRUST. Im assuming the error results from the git repo not trusting the SAP netweaver server that issued the request. Is it necessary to generate my own public certificate through STRUST and install it on the git server, it seems that i only have the certificate-request from the System PSE, not the actual certificate. Any ideas on what additional steps i need to do to make the handshake successful?

Thanks in advance.

**Comment by larshp** [comment]
did you try with the SSL test program, http://docs.abapgit.org/other-test-ssl.html ?

from the error it looks like the SSL certificate is not installed properly in STRUST or there is no network connection between the systems

**Comment by johnsmythe** [comment]
right. i tested github and it ran success but the https url to the internally hosted git server and it returned:
SSSLERR_CONN_CLOSED (-10)#Remote Peer has closed the network connection##SapSSLSessionStartNB()==SSSLERR_CONN_CLOSED##

i was able to navigate to the url as well. I also checked the internal certificates and i could see the certificated installed under the SSL client SSL Client (Anonymous) tab.

**Comment by larshp** [comment]
hmm, it is difficult to debug remotely, perhaps you have some basis people that can take a look?

**Comment by johnsmythe** [comment]
oh ok. thanks for your help

**Comment by larshp** [comment]
leave the issue open for a few days, perhaps somebody else have some ideas on how to help. 

I do not think this is a bug in abapGit

**Comment by johnsmythe** [comment]
oh just one more thing. i saw this in the ICM logs during the error:

[Thr 140286176098048] SecuSSL_SessionStartNB: SSL_get_peer_certificates() failed  (536872200/0x20000508)
[Thr 140286176098048]    => "SSL_CONN/H_SSL object does not hold any certificates received from SSL/TLS peer."
[Thr 140286176098048] >> ---------- Begin of Secu-SSL Errorstack ---------- >>
[Thr 140286176098048] 0x20000508 | SAPCRYPTOLIB | SSL_get_peer_certificates
[Thr 140286176098048] SSL API error
[Thr 140286176098048] SSL_CONN/H_SSL object does not hold any certificates received from SSL/TLS peer.
[Thr 140286176098048] << ---------- End of Secu-SSL Errorstack ----------

It looks like there is no certificate from the git server right?

**Comment by larshp** [comment]
I'm not sure, sometimes certificates are black magic 😉

**Comment by johnsmythe** [comment]
Ah. thanks. Great tool though.

**Comment by larshp** [comment]
closing issue, sorry 😢 

I dont think there is a bug in abapGit, it is difficult to debug server setup remotely
