### ISSUE TITLE
Have multiple developer working on the same project 

### ISSUE THREAD

**Issue by lcdszl** [larshp/abapGit#1070]
Hi,
I have been trying to utilize abapGit to make it possible for multiple people to work on the same codebase concurrently and merge later. What I have tried is:
- Create mulitple subpackges within the same packge
- Clone the project into each of the individual subpackage
Doing so creates multiple copies within the SAP system thus allowing multiple people making edits. 
However it seems that the package name is also attached to the repo, as only the most recent clone is viewable, all the previous attempts complains that the package name (shows as the subpackage of the most recent try) is unexpected. 
Is there ways to get around this so I can sync the same project under different package names? Or alternatively is there other ways we could have multiple developer making edit to the same project, on one SAP server? 
Thank you.
![subpackageerror](https://user-images.githubusercontent.com/34284944/33732944-20ee2088-db56-11e7-91f4-46fe24f2a91e.png)
![subpackagedirectory](https://user-images.githubusercontent.com/34284944/33732948-24f23ea8-db56-11e7-89ec-eab615c533e3.png)

**Comment by larshp** [comment]
One program can only exist once in a ABAP system, this is a restriction in the kernel which abapGit does not solve.

In the 2nd screenshot program "ZDEV2TEST" occurs twice, however this should not be possible due to the structure in SAP. Try refreshing the package contents

**Comment by lcdszl** [comment]
I see, so the only way to have multiple developers working on the same program is to sync two copies on two different SAP servers?

**Comment by EduardoCopat** [comment]
> I see, so the only way to have multiple developers working on the same program is to sync two copies on two different SAP servers?

Yes, at least to my knowledge. You could try to use docker... See https://github.com/tobiashofmann/sap-nw-abap-docker . Then, each developer could have their own docker instance

**Comment by larshp** [comment]
yes, this is a restriction in the ABAP kernel

This guy have some ideas on a workaround, see https://people.sap.com/jrg.krause#content:blog_posts however it is a lot of work

**Comment by lcdszl** [comment]
I see, thank you for the information.
