### ISSUE TITLE
ASSERTION_FAILED - ASSERT NOT rv_user IS INITIAL

### ISSUE THREAD

**Issue by jaschaDEV** [larshp/abapGit#1071]
Hi,

when staging files I receive the following short dump (see attachment).
[assertion_failed.zip](https://github.com/larshp/abapGit/files/1541872/assertion_failed.zip)

Regards,
Jascha

**Comment by jaschaDEV** [comment]
Hi Lars,
sorry, wanted to attach the full dump anyway, but missed to include the variable contents. Added another archive containing the full dump information. Let me know if anything's missing. Cheers, Jascha
[assertion_failed.zip](https://github.com/larshp/abapGit/files/1547181/assertion_failed.zip)

**Comment by larshp** [comment]
object type = DOCV

we need to do a small change in https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_docv.prog.abap, method lif_object~changed_by

add

```abap
IF rv_user IS INITIAL.
  rv_user = c_user_unknown.
ENDIF.
```

Feel free to submit a PR, I'll submit it tonight if nobody beats me to it 😄

**Comment by larshp** [comment]
closing, fix merged
