### ISSUE TITLE
V 1.50.1 not backwards compatible

### ISSUE THREAD

**Issue by grahamrobbo** [larshp/abapGit#1075]
Version 1.50.1 won't activate on NW ABAP v7.31.

Method `cl_package_factory=>create_new_package` does not have exception `error_in_cts_checks`.

Method `cl_abap_unit_assert=>assert_true` does not exist.

Method `cl_abap_unit_assert=>assert_false` does not exist.

![image](https://user-images.githubusercontent.com/1305633/34133639-09d65eee-e4aa-11e7-822d-ba698ef38b9f.png)

![image](https://user-images.githubusercontent.com/1305633/34133605-ccfc8b92-e4a9-11e7-8fac-081359ce0760.png)

**Comment by larshp** [comment]
thanks, it should be possible to backport the above issues 😄

**Comment by larshp** [comment]
@grahamrobbo try again, latest version

**Comment by grahamrobbo** [comment]
All good. Thanks @larshp
