### ISSUE TITLE
Implement support for (lightweight) tags

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1081]
As discussed here #960 support for tags would be useful in some cases. I'd like to start with implementing basic tag support. E.g. display, create and delete tags.
For the sake of simplicity I'd start with [lightweight tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging).

**Comment by larshp** [comment]
I have not found much git protocol documentation about creating tags, but I think it works much like creating a branch.

Not sure, to be tested: instead of eg 'refs/heads/branch1' it is something like 'refs/tags/v1.1'

**Comment by christianguenter2** [comment]
yep, works quite similar to branches. So it was easy to implement. I assume annotated tags will be a bit more effort.

**Comment by christianguenter2** [comment]
Todo:
- [ ] add support for annotated tags
- [ ] display tags in branch overvivew

**Comment by larshp** [comment]
Few comments/ideas,

1: If the user calls Tag -> Delete, when there are no tags, it shows a misleading error

2: Tag creation, perhaps move the sha1 information to the popup? Set iv_field_attr = '05' when calling ADD_FIELD, for a display only field

**Comment by christianguenter2** [comment]
1: Fixed. Now a proper error message appeȧrs
![image](https://user-images.githubusercontent.com/17437789/34534768-bdd5e6fa-f0bf-11e7-9c9d-57a6758385e4.png)

2: I removed the first popup and added the SHA to the tag creation popup
![image](https://user-images.githubusercontent.com/17437789/34534785-cd2a2288-f0bf-11e7-953a-66d7166540e7.png)

3: I added the tags to the branch overview page
![image](https://user-images.githubusercontent.com/17437789/34534800-dd671660-f0bf-11e7-93db-dd8b433f94af.png)

**Comment by christianguenter2** [comment]
I get this CI error
![image](https://user-images.githubusercontent.com/17437789/34535270-c67670d4-f0c1-11e7-82af-0bb425c46adf.png)

https://github.com/christianguenter2/abapGit/blob/7b248280f7ef7f50b8e44a2d4bdff37e9e3c5bc0/src/zabapgit_page_branch_overview.prog.abap#L503-L509

But I'm not quite sure what the error is...

**Comment by larshp** [comment]
abaplint does not handle string templates very well, https://github.com/larshp/abaplint/issues/84  

workaround is to use CONCATENATE, and/or simplify the string template, you can test if it is okay in abaplint via https://larshp.github.io/abaplint/ -> enter code -> click "Issues"

**Comment by christianguenter2** [comment]
Unfoturnately there is a syntax error in releases lower 7.40. I did downport and add the commit to the recent pull request #1083.

Thanks to Fred Verheul for notifying.

**Comment by larshp** [comment]
merged, will increase the patch level sometime later

**Comment by christianguenter2** [comment]
another one...
#1084

**Comment by christianguenter2** [comment]
I'll close this one and create a new for annotated tags...
