### ISSUE TITLE
tags: implement functionality to install/switch tag

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1089]
it should be possible to install a specific tag, like it is possible to switch a branch.

however pushing to tags should be disabled

**Update**: or perhaps it is okay to push to a tag, as it would just create a branch?

**Comment by christianguenter2** [comment]
WIP

https://github.com/christianguenter2/abapGit/tree/feature-checkout-tag

It's possible to checkout tags
![image](https://user-images.githubusercontent.com/17437789/35153636-99e56cf6-fd27-11e7-991d-b297827081b4.png)

![image](https://user-images.githubusercontent.com/17437789/35153664-b742bb64-fd27-11e7-82c4-a32c25917088.png)

![image](https://user-images.githubusercontent.com/17437789/35153670-bf3b17f8-fd27-11e7-9e32-06259e429823.png)

Currently it's possible to push on a tag. The behaviour is the same as with branches, a commit is added and the tag points to the new commit.

Todo: change the push behaviour.

**Comment by christianguenter2** [comment]
Should we close this?

**Comment by larshp** [comment]
yeah
