### ISSUE TITLE
Display Readme

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1102]
AFAIK it's currently not possible to display the readme of a repository? Or maybe I'm missing the obvious?

That was one of the first things a coworker asked when I showed him abapGit.
Maybe that's something we should implement?

**Comment by larshp** [comment]
Its currently not possible inside abapGit, only the ABAP artifacts are deserialized to objects.

However, all other files are in memory, so they can be shown, but I'm afraid that showing eg. markdown with images rendered is a lot of work.

Is the git repo not stored on a web based git server, where the readme can be shown?

**Comment by christianguenter2** [comment]
Hm, the markdown would be a problem, yes.
I did a small protoype how a plain text view could look like.
https://github.com/christianguenter2/abapGit/tree/show_readme

![image](https://user-images.githubusercontent.com/17437789/34678646-0c689592-f494-11e7-8382-b2aa70bec6c7.png)

![image](https://user-images.githubusercontent.com/17437789/34678658-1645a6a4-f494-11e7-97a6-c30de47ccb50.png)

Regarding your question, the repository is stored on a web based git server. It's just a matter of convenience.

**Comment by larshp** [comment]
There is https://github.com/koemaeda/abap-markdown, but I'm not sure we should introduce it as an required dependency.

Also, I'm not sure if this is a needed feature, if there are other files, these can always be shown and edited outside of abapGit. Ideally it should be added sometime, but currently there is a lot of internals that needs changing.

I'm thinking that we could add an option "show ignored files" in the file dropdown. And then it would be possible to click the README.md file or other files.

![image](https://user-images.githubusercontent.com/5888506/34678841-948765fc-f494-11e7-9fa3-3ea85360315f.png)

**Comment by christianguenter2** [comment]
Another approach would be to leverage the github markdown api to render the markdown. 
http://api.github.com/markdown

This approach has of course many drawbacks. At least it seems possible...
![image](https://user-images.githubusercontent.com/17437789/34681567-933c4d7c-f49c-11e7-8ad8-bc900866cffc.png)

I agree that the option "show ignored files" would be the cleanest option.

**Comment by larshp** [comment]
Markdown api, cool, this would be an un-authenticated call, they are limited to 50(?) per hour per ip.

But hmm, how difficult would it be to write a custom markdown parser 😜

**Comment by Sirius-A** [comment]
The github api approach could also lead to difficulties behind proxies.

**Comment by christianguenter2** [comment]
closing
