### ISSUE TITLE
ENQU: clear fields

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1110]
Some of the fields in DD27P are inherited from the table/view, clear the fields SCRLEN1 + SCRLEN2 + SCRTEXT_S + SCRTEXT_M + more? Align with what is cleared in TABL?

**Comment by larshp** [comment]
can fields like DATATYPE + ROLLNAME + INTTYPE also be cleared?

**Comment by larshp** [comment]
plus following 2 test repositories might need updates,
![image](https://user-images.githubusercontent.com/5888506/44912932-0b076380-ad2c-11e8-812f-a957066fc613.png)

**Comment by bigld** [comment]
@larshp can this be closed?
