### ISSUE TITLE
Escaping file path in BSP uses wrong character 

### ISSUE THREAD

**Issue by 14r5** [larshp/abapGit#1111]
Hi,
on importing an BSP with sub directories I run into the following error:

File not found: <<path to file>>#<<file>>

Cause for this is an encoding of the file path by replacing '/' with '_-'. The decoding of the file paths searches for '#' as replacement for '/'.

To solve  this issue I changed line 478 in ZABAPGIT_OBJECTS from
REPLACE ALL OCCURRENCES OF '/' IN rv_filename WITH '#'.
to 
REPLACE ALL OCCURRENCES OF '/' IN rv_filename WITH '_-'.

I'm not sure, if this will cause other problems.

**Comment by larshp** [comment]
Thanks, the code
`REPLACE ALL OCCURRENCES OF '/' IN rv_filename WITH '#'.`
is for handling namespaces in object names, we cannot change this without breaking downward compatibility.

Can you add an example with the filenames, and what the object  looks like in SE80?

**Comment by christianguenter2** [comment]
Today I had the same issue with this from eclipse deployed UI5 application.
![image](https://user-images.githubusercontent.com/17437789/34772392-166e197a-f608-11e7-9a1e-c1941e001f68.png)

![image](https://user-images.githubusercontent.com/17437789/34772380-0ed44540-f608-11e7-9b52-b008754dda60.png)

This is a example repo. But with the current implementation it's not possible to clone it.
https://gitlab.com/christianguenter/test_ui5_mime2

![image](https://user-images.githubusercontent.com/17437789/34772541-8c028d1a-f608-11e7-955b-cda59916d2ed.png)

I think we need to adjust the replace logic here.
https://github.com/larshp/abapGit/blob/ac226754284ccfb555f0fc0b68f90a8278bf1e9a/src/zabapgit_object_wapa.prog.abap#L246

**Comment by christianguenter2** [comment]
Did some testing
https://github.com/christianguenter2/abapGit/tree/fix_wapa_subfolders
at least for my case it works...

**Comment by larshp** [comment]
is it possible to fix by only doing changes in zabapgit_object_wapa.prog.abap? I'm concerned about changing the global filename logic

**Comment by christianguenter2** [comment]
good point.
I changed the code so that only zabapgit_object_wapa.prog.abap is changed.

@14r5 Do you think you can test your scenarios?

**Comment by larshp** [comment]
@christianguenter2 looks like the branch is not updated?

**Comment by larshp** [comment]
yeah, it looks okay, just looked for 2 commits instead of 1

**Comment by christianguenter2** [comment]
ah, ok. My new years resolution is to provide better and more meaningful commits to keep the history clean and comprehensible. Therefore I do lots of squases and rebases recently ;-)

**Comment by christianguenter2** [comment]
@14r5 can you try the latest build?

**Comment by 14r5** [comment]
It is working. I also checked bsp's with a namespace.

Thank you!

**Comment by larshp** [comment]
cool, thanks, closing
