### ISSUE TITLE
ENHO	Enhancement Implementation

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#113]

**Comment by larshp** [comment]
BADIs work, other types not implemented

**Comment by gregorwolf** [comment]
You can check the SAPlink plugin implementation for ENHO. Feel free to move it over.

**Comment by larshp** [comment]
thanks, only needed the BAdI stuff for now, not sure how many other types exists. 

Also handling of composite enhancement implementations missing in this impelementation

**Comment by VishnAndr** [comment]
Pool request #145 adding support for implicit enhancements (ENHO object; Enhancement Technique: Source Code Plug-In; HOOK_IMPL tool type).

**Comment by larshp** [comment]
thanks :+1:

**Comment by christianguenter2** [comment]
I think we can close?

**Comment by christianguenter2** [comment]
Closing...
