### ISSUE TITLE
Problem in CHANGE_BY( ) logic

### ISSUE THREAD

**Issue by nomssi** [larshp/abapGit#1142]
LCL_GUI_PAGE_STAGE->READ_LAST_CHANGED_BY( ) should working if no user was found,
but the ASSERT in the called LCL_OBJECTS=>CHANGED_BY( ) will not allow it.

Example: 
I managed to delete (initialize) the remote repository :-o  but the file are available locally 
Now I when I try to stage from there is this ASSERTION_FAILED dump.

JNN

**Comment by larshp** [comment]
hi, typically it fails due to missing code in CHANGED_BY in one of the objects, can you check the debugger to find which object type it fails for?

**Comment by nomssi** [comment]
In think from classes LCL_OBJECT_SAMC and LCL_OBJECT_SAPC

**Comment by larshp** [comment]
@nomssi try again, latest version

**Comment by nomssi** [comment]
I recreated the test case (deleted file on the remote repo and stage) and it passed.

**Comment by larshp** [comment]
closing
