### ISSUE TITLE
DUMP UNCAUCGHT EXCEPTION while creating a new package

### ISSUE THREAD

**Issue by nomssi** [larshp/abapGit#1152]
To clone a repository I enter the name of a target package in the popup "Clone repository..." then select "Create package" . In the follow up popup "Create Package" I enter details about the new package and press continue.
A popup "Prompt for transportable Workbench request" appears.
If I cancel (F12) => the short dump is triggered.

**Comment by christianguenter2** [comment]
@nomssi please test latest build

**Comment by nomssi** [comment]
test passes (no short dump, the action can be cancelled)

**Comment by larshp** [comment]
thanks, closing issue
