### ISSUE TITLE
7.02 downport issues

### ISSUE THREAD

**Issue by nomssi** [larshp/abapGit#1153]
to activate on a 7.02 SP10 I have to make 2 minor changes:
1) METHOD zif_abapgit_object~serialize( ) of class lcl_object_ddlx
The chained statement get_persistence( )->get( ... ) is not allowed. The system complains about EXPORTING parameter. Simple workaround:
```
DATA lo_per TYPE REF TO if_wb_object_persist.
        lo_per = get_persistence( ).
        lo_per->get( ... ).

```
2) METHOD zif_abapgit_object~exists( ) in class lcl_object_devc:
Exception `package_hierarchy_error` is not defined for method cl_package_helper=>check_package_existence( ), comment out the line

**Comment by larshp** [comment]
thanks

**Comment by christianguenter2** [comment]
Fixed, @nomssi  can you please try latest build?

**Comment by tf-Lukas-Klausner** [comment]
To activate the latest build on a 7.02 Netweaver, I had to change
`action_tab TYPE dctablrestab,`
to
`action_tab TYPE STANDARD TABLE OF dctablres,`

**Comment by nomssi** [comment]
Hello Christian,

I could test today and found a new issue:
in method activate_ddic( ) of class lcl_objects_activation, the table type in the data definition
`  action_tab TYPE dctablrestab,`
does not exist, I did 
` action_tab TYPE STANDARD TABLE OF dctablres,`
and it worked.

**Comment by christianguenter2** [comment]
I fixed it already and submitted a pull request...

**Comment by larshp** [comment]
closing, see comment in https://github.com/larshp/abapGit/pull/1159

issue https://github.com/larshp/abapGit/issues/1167 opened for fixing warnings
