### ISSUE TITLE
Broken links on http://docs.abapgit.org

### ISSUE THREAD

**Issue by brehberg** [larshp/abapGit#1161]
Not sure this is the right place to report, but here goes.  I encountered a few broken links on the abapGit documentation site,

On [Installation](http://docs.abapgit.org/guide-install.html) :
The link in "Report [ZABAPGIT_TEST_SSL](https://github.com/larshp/abapGit/wiki) can be used to verify that the connection works." goes to an old wiki page.  Seems like http://docs.abapgit.org/other-test-ssl.html is the correct destination.

On [Upgrading](http://docs.abapgit.org/guide-upgrade.html) : 
The link in "Copy the code from [zabapgit.abap](https://raw.githubusercontent.com/larshp/abapGit/build/zabapgit.abap) into the ZABAPGIT report" returns a 404: Not Found. Seems like https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap is the correct destination.

**Comment by larshp** [comment]
thanks, now fixed 👍
