### ISSUE TITLE
Deserialize_dynpros "error from RPY_DYNPRO_INSERT"

### ISSUE THREAD

**Issue by Dave94** [larshp/abapGit#1174]
Hi, I tried to import zip (that I've exported from one system) to another system and I'm facing "error from RPY_DYNPRO_INSERT".

FM 'RS_SCRP_CHECK_FIELD_POSITIONS' Raises exception 'OVERLAPPED'. 

What could be the cause of this? 

I can give you more info but I don't know abapgit well, yet.

**Comment by larshp** [comment]
hmm

can you edit the dynpro manually in the source system without errors? 

what is the ABAP versions of the source and target system? 

any way the issue can be reproduced in a public repository?

**Comment by Dave94** [comment]
I can edit the dnypros but I'm not sure which dynpro produces the error. Could you give me some info how to manage that?
Source system 740
Target system 731

**Comment by Dave94** [comment]
Oh, is that the dynpro in the LS_DYNPRO-HEADER?
I have a Report name here, screen Language and some other information.

**Comment by larshp** [comment]
HEADER, yeah, the report name and dynpro number is in a variable somewhere in the call stack

**Comment by Dave94** [comment]
Ok. I checked this on my source system. When I try to open the screen that is in HEADER I receive the information message "Element XXX touches or overlaps other element". I will try to fix it and then check the import again.

**Comment by Dave94** [comment]
This is strange because report works perfectly fine and is active besides that message that I receive in SE80 when I try to open the Screen is an information, not an error or warning.

**Comment by larshp** [comment]
SAP works in mysterious ways

but try fixing the issue mentioned in the information message in the source system, then I guess the import will work in the target system

**Comment by Dave94** [comment]
@larshp SAP FMs Raise very specific errors why don't you just show them on the screen instead of the 'error from RPY_DYNPRO_INSERT'? Istead of this I would get the error: 'Table XXX is not activated in the Dictionary'

**Comment by larshp** [comment]
yeah, we should change the code to show the full error message

**Comment by Dave94** [comment]
OK. I think I can close this issue now :) I've managed to fix the screen and import it by git. Although I think now I have similiar problem to https://github.com/larshp/abapGit/issues/501
I have a table and get the error: 'Table XXX is not activated in the Dictionary'. Truly it is in dictionary with the state "new".
