### ISSUE TITLE
Namespace Refactoring

### ISSUE THREAD

**Issue by mnemotron** [larshp/abapGit#1178]
Hi,
first of all, abapGit is a great tool!

This is a request for a needed feature.
A lot of people I know need to change the namespace of the ABAP objects.
A manual refactoring takes a lot of time and effort.

i.e. Z... to /IPS/... or something.

A standardized way to refactor the namespace would be great.
For example:
Repository (default) Namespace (i.e. Z) -> import -> Specific SAP System with namespace /IPS/...
or
SAP System /IPS/ -> export -> Z -> Repository

Greetings

**Comment by larshp** [comment]
Yeah, this would be a nice feature, but difficult to implement 😄 

Several people have asked for this feature

**Comment by larshp** [comment]
added label crazy which means it is a lot of work, the idea is good

**Comment by flaiker** [comment]
I looked into this some time ago but couldn't find an approach that would cover the main use cases. Some things that help:
- The repository infosystem has an API (CL_RIS_*) for object usages and also the environment check/search thing.
- ADT has some refactoring APIs, i. e. for renaming classes. Theses do however not support namespace changes at all unfortunately (target package cannot be in a different namespace than the source one).

Doing it outside of the ABAP stack seems really risky (regex renaming), unless there if there's going to be a nicely featured ABAP parser in the future.

In SCN there's also a blog about gettting abap2xlsx ported into a reserved namespace somewhere.

(I also feel like I already typed this up at some point, but I cannot find it...)

**Comment by treisinger** [comment]
Can these 2 blogs maybe help?

[https://blogs.sap.com/2013/03/06/namespace-refactoring-in-abap/](url)

[https://blogs.sap.com/2011/05/17/chain-and-rename-your-saplink/](url)

**Comment by nathanss** [comment]
Hello, as a workaround, I've wrote this script: https://github.com/nathanss/search-and-replace with the main goal of using it in an abapgit project (after serialization). I've had success applying it to a project I work for.

As it is very manual, you need to be careful not to screw up the files before you import them again. Also, remember to run it two times, one with old and new namespace in uppercase and other with lower case.

**Comment by mnemotron** [comment]
abap2xlsx: https://github.com/ivanfemia/abap2xlsx/tree/master/build

**Comment by mnemotron** [comment]
Hi,

check out the [ABAPSpace](https://github.com/SAPAssets/ABAPSpace) application to refactor namespaces.

**Comment by larshp** [comment]
think this is outside the scope of abapGit, can be solved with projects like https://github.com/SAPAssets/ABAPSpace

**Comment by mkysoft** [comment]
@mnemotron we shared a solution for this: https://github.com/isisdanismanlik/NamespaceChanger

**Comment by gregorwolf** [comment]
Now you can also check out: [Automagic standalone renaming of ABAP objects](https://blogs.sap.com/2021/04/20/automagic-standalone-renaming-of-abap-objects/)
