### ISSUE TITLE
Online - Uninstall Repository - Issue

### ISSUE THREAD

**Issue by mnemotron** [larshp/abapGit#1188]
Hi,

the option: Advanced -> Uninstall does not work correctly.

My repository contains several classes and interfaces. Not more.
And if I use the uninstall option, the objects are removed from the view (SE80), but I cant remove the empty package. Several errors raises: Cannot delete package, because is already in use, because package contains interface x and class y.

Please check. Thanx.

**Comment by larshp** [comment]
Hi,
You can check which objects still exist by looking up the packages in database table TADIR.

Note the DELFLAG field, if objects are in a transported package, then the actual rows in TADIR are not deleted until the transport is released. Try releasing the transport(if applicable) and then deleting the package.

**Comment by mnemotron** [comment]
hi, I will try it.

**Comment by larshp** [comment]
@mnemotron did it work? If it was a transported package, then this behavior is as expected

**Comment by larshp** [comment]
closing
