### ISSUE TITLE
WDYN add to repo gives error-  TODO, Encoding Length

### ISSUE THREAD

**Issue by techaware** [larshp/abapGit#119]
Supported object types does mention that web dynpro components are supports (type WDYN). However, when I tried to push a WDYN component from my package to GIT repo - it gives error - todo, encoding error. 

I installed v0.74  - which should be latest - I assume.

**Comment by larshp** [comment]
hi, can you try setting a breakpoint in line 9721, and confirm if this is the error message it stops at? If so, paste the value of lv_bits here?

**Comment by larshp** [comment]
btw, looking at your repository, folder support is not quite working yet(see https://github.com/larshp/abapGit/issues/5).

I recommend keeping the abapGit files in the root of the repostitory for now, this will help a lot if you need to update the code. Nuggets can be added under "releases" in the github repsitory, they can be considered "compiled" versions of your application.


In the error above it looks like the web dynpro component is quite large, so abapGit needs a bit more code to handle large files, will probably try adding it tomorrow or during the weekend :)

**Comment by larshp** [comment]
Hi Rahul,
I've updated the code, can you try again?

**Comment by techaware** [comment]
Hi Lars,

Appreciate your quick fix. I got stuck with creation of new netweaver instance to host my code. Will try out abapgit fresh again.

Regards,
Rahul

**Comment by larshp** [comment]
:thumbsup:

**Comment by techaware** [comment]
I gave it a try and it worked fine. Thanks! Also, as suggested, I have kept the abapGit files at root.
