### ISSUE TITLE
Error trying to run the last version of Report ZABAPGIT

### ISSUE THREAD

**Issue by lnitcheu** [larshp/abapGit#1195]
Hi,
can you please help me with this problem?
Error message:
Program ZABAPGIT
Direct access to the components of the global interface
ZIF_ABAPGIT_DEFINITIONS is not possible. The INTERFACE
ZIF_ABAPGIT_DEFINITIONS LOAD statement is missing. missing).
Thanks

**Comment by larshp** [comment]
ouch, I probably broke something, will check

**Comment by larshp** [comment]
@lnitcheu try again, latest build

**Comment by lnitcheu** [comment]
No syntax error. It is working. Thanks.

**Comment by larshp** [comment]
thanks, closing

😄

**Comment by andreash1027** [comment]
I think this issue still persists. When trying to compile the current code, I got the same error as the original author, but for the class zcl_abapgit_persist_background.

I had an older copy of the report in another system that I tried out after that and it compiled immediately.

**Comment by larshp** [comment]
thanks, this is probably a side effect in https://github.com/larshp/abapGit/pull/1707, taking a look

**Comment by larshp** [comment]
opened #1716 for fixing the above issue
