### ISSUE TITLE
WAPA	BSP (Business Server Pages) Application

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#12]
BSP_EXPORT_CLASSES
BSP_SHOW_SOURCE

cl_o2_api_pages=>load_with_access_permission
class CL_O2_PAGE

**Comment by larshp** [comment]
class cl_bsp_api_generate?

**Comment by tiefox** [comment]
For BSP UI5 repositories there is the class /UI5/CL_UI5_REP_DT that is used by /UI5/UI5_REPOSITORY_LOAD report to upload and download the files from the BSP repository. Would be great to have ABAP GIT to support this so the UI5 html/js/css can be stored in git and synced to the abap system in a CI enviroment. I'm interested in helping with this implementation.

**Comment by larshp** [comment]
cool

abapGit is targeted for basis release 702, I guess the UI5 stuff was not created back then.

So there are 2 options as I see it:
1. Use CL_BSP_API_GENERATE to upload/download the sources. This is also the backend method used by the UI5 classes, see eg class /UI5/CL_UI5_REP_PERSISTENCE method /UI5/IF_UI5_REP_PERSISTENCE~WRITE_BSP_PAGE

2. Write a abapGit plugin using the UI5 classes, see https://github.com/larshp/abapGit-Plugins there are no version restrictions for these, as it doesnt matter if there are syntax errors in isolated classes.

I recommend going for 1, as this should work all the way back to 702(and before?)

**Comment by larshp** [comment]
On another note, you sould also check the following project https://github.com/Yelcho/sapui5-deployer it might work out for you. I think there is also another similar project, but dont remember the name of it.

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapGit/issues/711
