### ISSUE TITLE
Syntax Error: "ZCX_ABAPGIT_2FA_ERROR" is unknown

### ISSUE THREAD

**Issue by patvo** [larshp/abapGit#1200]
Hi there.
At installation: when I try to activate the ABAP code (copy&pasted from here: https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap) I’m getting a syntax error at line 99 saying:
> The type "ZCX_ABAPGIT_2FA_ERROR" is unknown, but there are the following types with similar names: "ZCX_ABAPGIT_2FA_UNSUPPORTED" and "ZCX_ABAPGIT_CANCEL".

But when pressing F2 I can jump to this class. Any ideas?

**Comment by larshp** [comment]
Thanks, I did a lot of changes in the weekend, probably broke it, will check

**Comment by larshp** [comment]
@patvo try again, latest version

**Comment by patvo** [comment]
@larshp Working fine for me now.
Thanks for the immediate assistance.
