### ISSUE TITLE
WDYN - Sorting in xml

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#121]
When deserializing

https://github.com/techaware/wdalv_config
it seems like some of the xml is not sorted the same way as in the serialization system

**Comment by larshp** [comment]
closed with commit
https://github.com/larshp/abapGit/commit/3481eaa8ff0944326d17ea1f9a5458863838aaeb

**Comment by techaware** [comment]
I am not able to add SICF objects to ABAPGIT. Following Steps carried out: 
1) Refreshed the repository in ZABAPGIT 
2) Clicked ADD against the SICF object entry
3) Error displayed: Object not found or in wrong package


![image](https://cloud.githubusercontent.com/assets/13560153/11251618/f09d6632-8de6-11e5-9a20-47a26cc557ad.png)

One more issue observed: SICF ZALV_COMP_CONFIG is shown as A4H00132
![image](https://cloud.githubusercontent.com/assets/13560153/11251681/402988fc-8de7-11e5-8017-433db95e51fd.png)

**Comment by larshp** [comment]
hmm, can you try looking up in table TRDIR to see if the SICF objects are included in the package corresponding to the repository in abapgit?

**Comment by larshp** [comment]
I've reproduced the issue

**Comment by larshp** [comment]
Hi Rahul,
Thanks, I've updated the code can you try again?

**Comment by techaware** [comment]
After updating to the latest ABAPGIT - I was able to add SICF nodes to the GIT repo. Thanks.

**Comment by larshp** [comment]
cool, thanks
