### ISSUE TITLE
XML_FORMAT_ERROR after a misplaced '#' in database util xml file

### ISSUE THREAD

**Issue by patvo** [larshp/abapGit#1214]
Hi.
I misplaced an extremely unwise ‘#’ (number sign, hash) in one of the repository's xml files. 
Getting a dump now ([XML_FORMAT_ERROR_dump_021918.txt](https://github.com/larshp/abapGit/files/1737754/XML_FORMAT_ERROR_dump_021918.txt)), when starting transaction ZABAPGIT.
Is there any way to edit the xml file manually? Otherwise, I would try to reinstall abapGit.

**Comment by larshp** [comment]
Hi,
try changing the XML in the debugger

there is currently no external tool, only the built-in

**Comment by patvo** [comment]
Worked!
I could have thought of this myself. Anyway: Many thanks!
