### ISSUE TITLE
Solutions and Add-ons after upgrade of abapgit

### ISSUE THREAD

**Issue by A141117** [larshp/abapGit#1220]
Hi, 
Do we have any document sort of stuff where we can actually see what is the add-on features or benefits of upgrading the ABAPGIT from previous version to new version or whats the benefits of adding code corrections released here. For example, SAP release notes have a document which explains about functionality and add-on comes up with that release note.

Thanks
Divya

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit/blob/master/changelog.txt 

if you are installing abapGit via an online repository, it will also show the changelog in the client

**Comment by larshp** [comment]
@A141117 did above help?

**Comment by A141117** [comment]
Yes. That was good. Thanks.
