### ISSUE TITLE
2FA - Supported Git Platforms

### ISSUE THREAD

**Issue by mnemotron** [larshp/abapGit#1223]
Hi,

I use the client within a separate company Github enterprise platform.
There is a supported platform check, with a constant "www.github.com".
I changed the hostname of this constant to the used Github enterprise hostname.
I now it works.

But is it possible to make adding new hostnames easier (using a table)?

Thanx.

**Comment by larshp** [comment]
Is this for 2FA auth?

Did you change the following https://github.com/larshp/abapGit/blob/master/src/http/zcl_abapgit_2fa_github_auth.clas.abap#L61 ?

**Comment by mnemotron** [comment]
Yes, I think it was the following lines:
- line 18: CONSTANTS c_github_api_url TYPE string VALUE `https://api.github.com/` ##NO_TEXT.
- line 61

I changed the hostname github.com to my specific github enterprise hostname.

**Comment by larshp** [comment]
thanks, we should fix this somehow

**Comment by mnemotron** [comment]
Thank you.

**Comment by larshp** [comment]
2 options:
* add this as a setting in global configuration
* add as "user exit" via ZIF_ABAPGIT_EXIT

currently the workaround is to change the abapGit code, but this is annoying as the code has to be adjusted after each upgrade of abapGit assuming all objects are overwritten

**Comment by mnemotron** [comment]
mmmm.... I think as a setting in global configuration sounds great, so its easier to changed it without further effort.

**Comment by mnemotron** [comment]
other question, do you have a slack channel or something else?

**Comment by larshp** [comment]
yep 😄  invite link is in the readme/repo front page, https://abapgit-slackinviter.herokuapp.com/

**Comment by mnemotron** [comment]
or 3 option:
add this as a setting in global configuration (a default setting)
and it would be nice, if you can maintain a separate host for each repository

**Comment by larshp** [comment]
I dont think it is needed for each repo, the regex will match the git url which then can be used to determine the api url

**Comment by larshp** [comment]
Another plan:
Change
https://github.com/larshp/abapGit/blob/master/src/http/zcl_abapgit_2fa_auth_registry.clas.abap#L54
to find all global classes implementing `zif_abapgit_2fa_authenticator`

Then to implement your scenario, create a class with https://github.com/larshp/abapGit/blob/master/src/http/zcl_abapgit_2fa_github_auth.clas.abap as superclass, and redefine constant `c_github_api_url` plus `constructor`. Make sure the new class is outside the main abapGit package

This has the advantage that multiple sites can be supported

**Comment by mnemotron** [comment]
Hi, I'll do it like this. Thanks.

**Comment by larshp** [comment]
I'm making some changes for this right now, will submit a PR soon(today)

**Comment by larshp** [comment]
Pull request https://github.com/larshp/abapGit/pull/1236 opened, can you try this out if you have time? Also feel free to jump onto the Slack channel, I'll be available for the next ~3 hours.

With the code in the PR it is possible to implement custom handlers for 2FA, something like the below code, put this code outside of the package you have the abapGit code in, this will allow for easy upgrade of abapGit. Plus you can store your custom abapGit "exits" in a private repo.

```abap
CLASS zcl_abapgit_2fa_mycompany DEFINITION PUBLIC INHERITING FROM zcl_abapgit_2fa_github_auth FINAL CREATE PUBLIC .
  PUBLIC SECTION.
    METHODS constructor .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS ZCL_ABAPGIT_2FA_MYCOMPANY IMPLEMENTATION.
  METHOD constructor.
    super->constructor( '^https?://(www\.)?github.mycompany.com.*$' ).
    mv_github_api_url = `https://api.github.mycompany.com/`.
  ENDMETHOD.
ENDCLASS.
```

**Comment by mnemotron** [comment]
Hi,
can you compile the version for me (zabapgit.abap), because I can't access the Internet in the system to download the abapgit version.

**Comment by larshp** [comment]
Hi,
I have merged the PR, however you need to install the development version of abapGit in order to be able to inherit from the `zcl_abapgit_2fa_github_auth` class

See http://docs.abapgit.org/guide-import-zip.html on how to import the objects via zip file

**Comment by larshp** [comment]
@mnemotron did it work?

**Comment by larshp** [comment]
I'll close this issue, if you have any questions feel free to post, or open new issues

**Comment by gepparta** [comment]
Seems not to work for me with a non DEV Version of abapGit, as the local class  ZCL_ABAPGIT_2FA_AUTH_BASE cant be found via cl_oo_class=>get_instance 
so always the fix catch alternative is getting called 
![image](https://user-images.githubusercontent.com/3863263/38037399-137abd3a-32a9-11e8-835c-933e590e806b.png)

**Comment by larshp** [comment]
dev version required for this feature

**Comment by gepparta** [comment]
ok. thanks. I thought I've missed something here. 
I think it would already be a problem inheriting fro ma local class ^^
I will try this with DEV Version for our bitbucket repository.

**Comment by larshp** [comment]
are you running Bitbucket Enterprise? I suggest first contributing a 2FA solution for bitbucket.com, which then can be inherited for making local Bitbucket Enterprise installations work

**Comment by mnemotron** [comment]
Sorry, I haven't had time to try it yet. If there are any problems with the adapted version I will let you know. Thanks for the update.
