### ISSUE TITLE
Tags created not corret

### ISSUE THREAD

**Issue by treisinger** [larshp/abapGit#1224]
I wanted to save some state of my repository and created a tag. I've got the message "Tag xxxx created". The project is connected to Abap GitServer. But when I want to show the tag overview I've got the message "There are no tags for this repository". But when I select the Branch overview the Tags which I created are displayed as branches, but first character is truncated from tag name.

![image](https://user-images.githubusercontent.com/9279781/36524860-f2d1a718-17a7-11e8-87fc-4dd031d27c7c.png)

I've tried the same with a repository connected to GitHub and here it seems working ok.

![image](https://user-images.githubusercontent.com/9279781/36524981-6926a224-17a8-11e8-95cf-25a574732987.png)

Are tags not supported for Abap GitServer?

**Comment by larshp** [comment]
it will work sometime

However, I have not tested it, see https://github.com/larshp/abapGitServer/issues/97

Can we close this issue in abapGit and open it in abapGitServer? as it seems like it is an issue in the server not the client

**Comment by treisinger** [comment]
Sure, can I move the issue to abapGitServer or do I have to create a new one?
