### ISSUE TITLE
Settings flags always on in SAP GUI for Java

### ISSUE THREAD

**Issue by nathanss** [larshp/abapGit#1229]
Hello,

I'm currently using abapGit in SAP GUI for Java environment and whenever I make a change to settings, I noticed that the 'Proxy authentication' flag is always persisted as true, regardless of what I selected. Other flags, like 'Enable jump to ADT first', etc, all behave similar to Proxy authentication.

Steps to reproduce:

1. Execute ZABAPGIT.
2. Go to 'Advanced' and 'Settings'.
3. Try to set 'Proxy Authentication' to false.
4. Save.
5. Open the Settings page again.
6. Proxy authentication will be set to 'true'.

abapGit version: v1.50.1
SAP GUI for Javaversion: tested in 7.50 rev 0.3 and 7.40 rev 9
Operating system: Red Hat 7.4 

I don't know if it's a Red Hat specific issue. Perhaps someone could test it on Mac or even Windows.

**Comment by larshp** [comment]
Workaround is to manually edit the settings under Advanced -> Database util, but take care, if the XML is malformed it will crash abapGit on startup.

Can someone help out here? It is difficult for me to reproduce, however can try installing SAPGUI Java on windows to see if it is also affected.
