### ISSUE TITLE
Dump when exporting web dynpro component

### ISSUE THREAD

**Issue by kovboyjder** [larshp/abapGit#123]
Hi, 

First of all excellent contribution. I want to use this to export a web dynpro component. But it gives me a dump. I have attached it.

[abapgit.txt](https://github.com/larshp/abapGit/files/38719/abapgit.txt)

**Comment by larshp** [comment]
fixed, try again


Rahul have some trouble adding the SICF services, see #121 , let me know if you have the same problem
