### ISSUE TITLE
Connectivity issue after SAP note 510007 implementation

### ISSUE THREAD

**Issue by A141117** [larshp/abapGit#1230]
Hi Team,

I implemented the suggested sap note 510007 released on 22-Feb-2018. Now when I enter into ZABAPGIT transaction then it does not ask for my credentials and thus could not connect to abapgit repositories. Its giving error as shown below:
![image](https://user-images.githubusercontent.com/36180668/36712513-475729dc-1bdd-11e8-98d9-6a3bbd111460.png)

I tested the connectivity using program ZABAPGIT_TEST_SSL and it says 'Success, it works'.
![image](https://user-images.githubusercontent.com/36180668/36712477-16c67ebc-1bdd-11e8-81df-ed6936753d71.png)

Can you please help. 
Regards
Divya

**Comment by larshp** [comment]
hmm, try setting some breakpoints and see what goes wrong

also check log in transaction SMICM -> Goto -> Trace File -> Display End

**Comment by A141117** [comment]
below is the exact message coming up when I try to execute abapgit.

![image](https://user-images.githubusercontent.com/36180668/36760964-00150b2c-1c71-11e8-9674-db32f7e877b5.png)

**Comment by larshp** [comment]
is your SAP system behind a proxy? if so, setup proxy auth, see http://docs.abapgit.org/guide-install.html

**Comment by esjewett** [comment]
It's also possible that the proxy doesn't support TLS 1.2, in which case you're sort of out of luck and should engage your network infrastructure folks to get that sorted out.

**Comment by A141117** [comment]
When I tick the 'Proxy authentication required' checkbox in Settings (refer screenshot below), then its asking for proxy credentials, github credentials and then working. 
![image](https://user-images.githubusercontent.com/36180668/36817878-e2d04240-1d36-11e8-9e26-7c022df44323.png)

However, its not working when I try to create new branch and giving below error message:
![image](https://user-images.githubusercontent.com/36180668/36817855-cc6ccb36-1d36-11e8-9562-0300d3636ffa.png)

**Comment by A141117** [comment]
When we have the error then why that connection test program is not showing up. Its showing that "Success".
![image](https://user-images.githubusercontent.com/36180668/36818163-f7b31cc2-1d37-11e8-8eb0-08859cd07b68.png)

**Comment by esjewett** [comment]
@larshp Does zcl_abapgit_git_transport not initialize the proxy information into the HTTP client?

**Comment by larshp** [comment]
abapgit sets up the proxy according to the settings(or at least that is the idea, I have not tested the proxy functionallity as I do not have access to such a setup)

@A141117 have you setup the proxy as mentioned in the code inhttp://docs.abapgit.org/other-test-ssl.html

```abap
* enter username and password for proxy authentication if needed
*  li_client->authenticate(
*    proxy_authentication = abap_true
*    username             = ''
*    password             = '' ).
```

**Comment by esjewett** [comment]
I'm probably wrong but my read is that https://github.com/larshp/abapGit/blob/master/src/zcl_abapgit_http_client.clas.abap never applies the proxy information to the client (it should probably happen in the constructor).

Contrast with `zcl_abapgit_http=>create_by_url`.

**Comment by larshp** [comment]
@A141117 can you confirm if the http access via the proxy worked before feburary 22nd?

**Comment by pokrakam** [comment]
Something is fishy. After fixing the 510007 issue, I can no longer connect to my private repositories. But the symptoms seem closely related to what's going on here. 
I get the following popup: 
<img width="419" alt="screen shot 2018-03-04 at 07 58 06" src="https://user-images.githubusercontent.com/25539927/36943475-fe2ff09c-1f81-11e8-9af8-a1f55d047952.png">
which is where I used to enter my GitHub user/pw (no proxy here). 
But now I can't access my repo at all. I can enter what I like in here, there is no complaint. Debugging I see the info is just added to the http client, which first access the publicly accessible abapGit repo. 
If I try to clone my repo from scratch, it won't access it. In fact when I select a branch, abapGit suddenly crashes without error. 
Have been debugging this for a few hours but running out of time today. Will see if I can find out more later.

**Comment by pokrakam** [comment]
OK had another go. Made my repo public -> No difference. 
I deleted the repo from abapGit using DB tools and cloned it again. Now it works as before. It still keeps asking for proxy and repo passwords, so the two dialogs are a bit of a niggle - it used to be only one. 
I'd try to fix but am a bit short of time, it's not a biggie.

**Comment by A141117** [comment]
Does this proxy authorization dependent on the server? I mean if a server is changed for a sap system then is it possible that this proxy error could come?

**Comment by A141117** [comment]
@larshp - Any progress on this. I can see multiple issues discussed in same issue no. Basically my issues are as below: 
1. previously it did not ask for proxy pop-up but after program upgrade and SSL connection upgrade it asks for proxy credentials even if the server is same.
2. After entering the proxy credentials everything else works fine but I am not able to create the new branch.
Please look into this urgently. 
Thanks

**Comment by larshp** [comment]
Hi,
I have not had any luck reproducing the issue, none of the systems I have access to are behind a proxy.

The proxy popup only shows up if you have configured proxy authentication:
https://github.com/larshp/abapGit/blob/59c1f277ab623f18808f1c1f4d852ef6a439baea/src/http/zcl_abapgit_http.clas.abap#L154

Can you check the log in SMICM -> Goto -> Trace File -> Display End to see if it tells anything interesting?

**Comment by larshp** [comment]
@pokrakam have you had any luck/time?

**Comment by larshp** [comment]
closing
