### ISSUE TITLE
Will ZABAPGIT program work with https://github.mit.edu?

### ISSUE THREAD

**Issue by qiankangMIT** [larshp/abapGit#1233]
Hello,

As a discovery project at MIT, we have copied ZABAPGIT program and ran it from SE38. The project is to evaluate the feasibility of abapGit with MIT's own enterprise github "https://github.mit.edu" as github project repositories (not github.com). 

The main question is "can this be done?" In another word, can we use github.mit.edu instead of github.com?

Upon examining the code within ZABAPGIT, it refers to certain objects that are github.com specific, for example, api.github.com or github.com/larshp/XXX. Would you recommend to replace the code from "github.com" to "github.mit.edu" and copy all publicly available abapGit related objects to "github.mit.edu"? Or is this an approach that could lead to disaster of future SAP updates and support? Are there any other ways to make abapGit work with github.mit.edu?

Would you comment on these questions and give some guidance?

Thanks for your help!

Regards,
Qian Kang
qiankang@mit.edu

**Comment by larshp** [comment]
yes, it should/will work 😄 

the api.github.com only needs to be replaced if using 2FA, see https://github.com/larshp/abapGit/issues/1223 for more information, and possible solutions

abapGit is a community project, there is no support from SAP, and abapGit itself is only Z objects, so it will not interfere with future upgrades

**Comment by larshp** [comment]
@qiankangMIT see status in https://github.com/larshp/abapGit/issues/1223

**Comment by larshp** [comment]
@qiankangMIT did it work out?

**Comment by qiankangMIT** [comment]
yes,  I believe so. However, we are facing a different issue related to authentication from abapgit to "https://github.mit.edu" . Since it is a different subject, I will open a new issue and hope you can give us some guidance.

**Comment by larshp** [comment]
closing
