### ISSUE TITLE
Local objects when switching from offline to online repository

### ISSUE THREAD

**Issue by treisinger** [larshp/abapGit#1234]
I had problems with SSL connection, so I made abapGit repo an offline repository. SSL connetion is solved, so I changed abapGit back to Online repository. But now I have a lot of objects, which seems to exist only in my local system. Is this normal behavior?

![image](https://user-images.githubusercontent.com/9279781/36839215-af6ca0f0-1d41-11e8-8cfe-03bb2b50b142.png)

**Comment by larshp** [comment]
hmm, no

try Advanced -> Reset local

**Comment by treisinger** [comment]
Ok, Advanced -> Reset local solved it.

**Comment by larshp** [comment]
there might be a bug here, did you use the Advanced -> convert to online functionality, can this issue be reproduced?
