### ISSUE TITLE
Export to ZIP with online repository

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1235]
I'm currently in a situation where I have to regularly export an online repository to a zip. Therefore I make it offline, export the zip and make it online again. Is there any reason why we don't have the export to zip option for online repos? At least I think that the option isn't there.
I know I can also create download a zip of the repository in the git hosting e.g. github. But in this particular case that's not a viable option.

**Comment by larshp** [comment]
I use Advanced -> Package to zip,
![image](https://user-images.githubusercontent.com/5888506/36897221-f5f31a20-1e15-11e8-8476-d6d4b6c61e2d.png)

**Comment by christianguenter2** [comment]
great, wasn't aware of that. That's sufficient for me.
