### ISSUE TITLE
HTTP Communication Failure error

### ISSUE THREAD

**Issue by XHKOSE** [larshp/abapGit#124]
Greetings Larshp,

I wanted to give it a try and tried installing abapGit in our SAP CRM.

- I succesfully set up program ZABAP_GIT in SE38
- I succesfully imported those two certificates in [your Wiki](https://github.com/larshp/abapGit/wiki/Installing-abapGit)

When I run ZABAP_GIT from SE38 and want to clone my repository, it gives an error that reads "HTTP Communication Failure" error.

![image](https://cloud.githubusercontent.com/assets/16058009/11453296/0c303e40-960e-11e5-800c-6e16dd3576af.png)

What can I do to overcome this error?

Thanks in advance!

**Comment by XHKOSE** [comment]
I tried once more and it succesfully loaded my ABAP repository.

Issue closed

**Comment by XHKOSE** [comment]
The problem persists, hence reopened the issue

**Comment by larshp** [comment]
Hi,
can you try
a: double check STRUST steup
b: is the SAP server behind a firewall?

Also try testing the connection to https://github.com (or replace address with the server you are using) via report RSWF_TEST_HTTP

**Comment by XHKOSE** [comment]
Hi Lars,

Thank you for your reply. I'll check it when I have the time.

By the way, forgive my ignorance, how I can check if my SAP server is behind a firewall?

**Comment by larshp** [comment]
try using RSWF_TEST_HTTP to read a webpage that is not using SSL, this will show if the SAP server can contact the internet. The SAP server might also be behind a proxy.

If you have a SAP basis group you can also try asking them, they will know if the SAP server can contact the internet or behind firewall or using proxy.

**Comment by larshp** [comment]
if nothing works, consider making an offline project

The steps to move files to github is:
a: download files as zip from abapgit
b: unzip to folder, use your favorite git client to commit files, make sure not to change the file names or the folder locations

**Comment by larshp** [comment]
any luck?

**Comment by XHKOSE** [comment]
Greetings Lars,

Thanks for the tips.

* I double check the STRUST setup. Screenshot below

![STRUST Setup](https://cloud.githubusercontent.com/assets/16058009/11758875/4acd74cc-a079-11e5-8f64-852def472e40.png)

* I also tried testing github.com with the program you suggested. Results below

![SS01](https://cloud.githubusercontent.com/assets/16058009/11758886/7492a034-a079-11e5-9715-1a672cc350ba.png)

![SS02](https://cloud.githubusercontent.com/assets/16058009/11758894/8f099d32-a079-11e5-917a-939a164c1a27.png)

I don't know any BASIS team to ask about this server. Even if I somehow find out it's behind a firewall, I cannot change settings because I do not own the this client I'm working on...

**Comment by XHKOSE** [comment]
By the way, I think this is getting time-consuming.

Recently, I've been thinking of transferring my work to "Bitbucket" and will use your program to upload my ABAP codes to a folder in my windows. And then I can deploy the codes to Bitbucket manually via another application named "SourceTree". This is pretty similar, even the same principles that you define as "offline project"

Again, thanks for everything. I'm sorry I couldn't make it work and have to leave it here...

**Comment by larshp** [comment]
yes, consider using an "offline project". Online projects are a bit easier if you do a lot of updates, but offline works as well

**Comment by kalem123** [comment]
Greetings Larshp,

I am getting this error message E**rror: HTTP Communication Failure** as well when I am triying 
to clone https://github.com/larshp/FORMfactor.

First we are getting the message "Fetch Remote Files" and later it ends with the message
Error: HTTP Communication Failure.

I have proceeded all steps as described below:
https://github.com/larshp/abapGit/wiki/Installing-abapGit

Testing the connection via Report RSWF_TEST_HTTP to https://github.com ends with
Test HTTP Connection
HTTP-Receive: RC=411  Connect to github.com:443 failed: NIEC
ONN_REFUSED(-10)

Please assist, thx in andvance.

Br,
kalem123

**Comment by larshp** [comment]
can you try testing the connection with https://github.com/larshp/abapGit/wiki/ZABAPGIT_TEST_SSL ?

**Comment by kalem123** [comment]
Thank you very much for your quick feedback.

ZABAPGIT_TEST_SSL returns 
Error     1

install the projects via zip files, do you mean manually, if so

this would take a very long time because for FORMfactor project is abapOpenChecks project needed
where consists of more than 100 Files. Can you send me a sap transport.

Br,
kalem123

**Comment by larshp** [comment]
for via zip see: https://github.com/larshp/abapGit/wiki/Installing-a-repository-offline

**Comment by kalem123** [comment]
Hi,

I thank you very much. It works. I didn't know this option with "Import Zip".

Best Regards
kalem123

**Comment by Rachanasuresh1994** [comment]
I have the same problem.

But the problem is i can clone from Github, but i am using gitstack to clone as i wanted a free private repository. When i clone it through Gitstack repository( which is actually in localhost i.e a system folder), i get HTTP communication failure error.

can you please tell me how to resolve this issue

**Comment by larshp** [comment]
@Rachanasuresh1994 please open a new separate issue, make sure to set a breakpoint in the code to find the full error message and add in the description

**Comment by AiolosYang** [comment]
> Greetings Larshp,
> 
> I am getting this error message E**rror: HTTP Communication Failure** as well when I am triying
> to clone https://github.com/larshp/FORMfactor.
> 
> First we are getting the message "Fetch Remote Files" and later it ends with the message
> Error: HTTP Communication Failure.
> 
> I have proceeded all steps as described below:
> https://github.com/larshp/abapGit/wiki/Installing-abapGit
> 
> Testing the connection via Report RSWF_TEST_HTTP to https://github.com returns with
> Test HTTP Connection
> HTTP-Receive: RC=411 Connect to github.com:443 failed: NIEC
> ONN_REFUSED(-10)
> 
> Please assist, thx in andvance.
> 
> Br,
> kalem123

Hi, could you please let know how you fix this issue:

![image](https://user-images.githubusercontent.com/32993851/98882114-88ab8a00-24c6-11eb-953d-7a9242625858.png)

**Comment by Sjena99** [comment]
Greeting Larshp,
 I am getting this error when i tried testing the server with  https://github.com but i am getting the following error that error creating http client , does that mean SAP server is under firewall ? Please help !

 
<img width="939" alt="image" src="https://user-images.githubusercontent.com/120162357/212839145-0d7c94b8-1ab7-4498-b0d0-c3f8af07367e.png">

**Comment by larshp** [comment]
@Sjena99 please open a new separate issue
