### ISSUE TITLE
7.02 downport issues

### ISSUE THREAD

**Issue by nomssi** [larshp/abapGit#1243]
I had to make to following changes to compile version 1.60.1 on Netweaver 7.02 

CLASS zcx_abapgit_exception 
      Method raise_t100 
Both in definition an implementation replace TYPE 

- syst_msgid => SYMSGID
- syst_msgno => SYMSGNO
- syst_msgv => SYMSGV
- syst_subrc => sysubrc

Use a helper variable for lx_exception->get_text( ) in two cases

1) in CLASS ZCL_ABAPGIT_MIGRATIONS, method local_dot_abapgit( ).
              CALL FUNCTION 'POPUP_TO_INFORM'
                EXPORTING
                  titel = 'Migration has failed'
                  txt1  = lx_exception->get_text( )  <-- not allowed

2) In CLASS zcl_abapgit_gui  METHOD handle_action
      CATCH zcx_abapgit_exception INTO lx_exception.
        ROLLBACK WORK.
        MESSAGE lx_exception->get_text( ) TYPE 'S' DISPLAY LIKE 'E'.   <-- not allowed

To avoid a dump at runtime, further changes are needed in class ZCL_ABAPGIT_OO_CLASS_NEW:
1)Method update_meta( ) 
comment out two parameters (issue #933).
*        source                        = it_source
*        suppress_constrctr_generation = seox_true

2) Method UPDATE_CS_NUMBER_OF_METHODS 
add a guard clause
TRY.
  method content
CATCH CX_SY_CREATE_DATA_ERROR.
ENDTRY.

best regards,

JNN

**Comment by treisinger** [comment]
I will check this.

**Comment by larshp** [comment]
@nomssi can you try again, latest version

**Comment by nomssi** [comment]
I can confirm it works without changes
