### ISSUE TITLE
the class zcl_abapgit_user_exit is not found in the class zcl_abapgit_exit

### ISSUE THREAD

**Issue by jfilak** [larshp/abapGit#1245]
My exit implementation is ignored - https://github.com/filak-sap/abapgit_user_exit

When I add this code to zabapgit program:
```abap
START-OF-SELECTION.
  data: li_user_exit type ref to zif_abapgit_exit.
  create object li_user_exit type ('ZCL_ABAPGIT_USER_EXIT').
  data(li_abapgit_exit) = zcl_abapgit_exit=>get_instance( ).
  PERFORM run.
```

The variable `li_user_exit` is bound to an instance of my class.
The variable `li_abapgit_exit` is bound to an instance of  `zcl_abapgit_exit`.
I am sorry but I have no idea how program includes work or should work.

Could this be caused by NW release?

**Comment by larshp** [comment]
What is your setup, are you using the long ZABAPGIT report or the development version with global classes?

If using the long report, your class must be placed in the include, if using the global classes the exit should be placed as a global class.

See also
https://github.com/larshp/abapGit/blob/master/src/zabapgit.prog.abap#L40

**Comment by jfilak** [comment]
Yeah, I am an idiot, I didn't notice the 2nd and 3rd line of the comment. I need to create the global class.
