### ISSUE TITLE
Question: Should ZABAPGIT_TEST_SSL be in package $ABAPGIT

### ISSUE THREAD

**Issue by martin-english** [larshp/abapGit#1246]
I installed ZABAPGIT and ZABAPGIT_TEST_SSL into package $ABAPGIT  by saving the contents of https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap and http://docs.abapgit.org/other-test-ssl.html and uploading the code via SE38

I then used ZABAPGIT to make the package online, and I ended up with the following: 
![capture](https://user-images.githubusercontent.com/4261565/37551050-9bcdaa64-29ec-11e8-9eef-8db176261a24.PNG)

Should ZABAPGIT_TEST_SSL be in the master package, or should I change the package it is using on my system ?

thanks,

**Comment by larshp** [comment]
it should not

its a test program, just put it in $TMP

**Comment by martin-english** [comment]
thanks for the quick response

**Comment by larshp** [comment]
I've updated the documentation, https://github.com/larshp/abapGit/commit/11ab0190c15868376add639f8e99dc63197b9cdd
