### ISSUE TITLE
ZCL_ABAPGIT_2FA_AUTH_BASE diffs

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1247]
I've had some issues with diffs for class ZCL_ABAPGIT_2FA_AUTH_BASE when upgrading abapGit, the class does not match remote after reset/pull.

Not looked into the issue yet, we should look into reproducing the issue. Might have something to do with method ordering and/or deleting methods.

**Comment by flaiker** [comment]
I had that too. Reset local didn't work either.

**Comment by larshp** [comment]
manual workaround is to change the method manually

**Comment by larshp** [comment]
think this can be closed, we've been changing a lot of classes without similar issues
