### ISSUE TITLE
Git at AWS CodeCommit

### ISSUE THREAD

**Issue by p-dmitrij** [larshp/abapGit#1254]
Hi, I'm trying to setup connection to a Git repository at [Amazon Web Services](https://aws.amazon.com/codecommit/). Unfortunately I've faced the problem that the action "upload-pack-request" always returns an empty result. The SSL connection works fine. I can see even my branches by pressing the button "Select branch". But still can't see/synchronise the repo because of the problem. Technically it is possible to see the empty result by setting of a break point at the line 46358 (lo_client->send_receive_close). Later on at the line 46365 the exception "empty pack" is raised. Could you suggest please, how it is possible to deal with this problem.
PS Thank you guys, the idea of such a program is just brilliant!

**Comment by larshp** [comment]
Thanks,
It's difficult to say what is wrong, many of the git servers have their own teaks,

First guesses:
* something with authentication, however being able to see the branches talks against this
* git capabilites, https://github.com/git/git/blob/master/Documentation/technical/protocol-capabilities.txt abapGit assumes the git server supports some specific capabilities, and does not listen/negotiate these properly with the server

I'll take a look sometime, currently my weekdays are quite busy with real work, so first chance might be in the coming weekend.

**Comment by p-dmitrij** [comment]
Ok, got it. I can share my AWS account for reproducing of the problem or assist you in any other way. So if you have any ideas, what I could I try to do, I'll do it till the week end for your saving time.

**Comment by larshp** [comment]
It looks like AWS CodeCommit has a free tier, so it should not be an issue to try reproducing this issue.

ideas, not yet, will have to dig into it

**Comment by p-dmitrij** [comment]
Thank you, now it works!
