### ISSUE TITLE
Setup ABAP GIT 

### ISSUE THREAD

**Issue by srikanthGajula1** [larshp/abapGit#1258]
Hello All,
My organization wants to implement ABAP GIT but i am not able to find the below , can someone help me with the exact answers , thanks in advance 

training for the developers
security issues,
version management

**Comment by larshp** [comment]
Training: see http://docs.abapgit.org it describes the features of abapGit, but it is up to you how you want to use it. Also see http://docs.abapgit.org/other-articles-and-presentations.html for different scenarios

Security: feel free to review the code, as all other open source projects there might be issues. Strength in open source comes in numbers, right now there are 75 people from different organizations watching all code changes.

Version Management: The code for abapGit is stored in this repository, where you can always fetch the latest version. Every now and then I increase the version number and update https://github.com/larshp/abapGit/blob/master/changelog.txt 
You decide when/how/if you want to upgrade your local versoin.

**Comment by srikanthGajula1** [comment]
Hello Lars ,
Thanks for the quick response , Do you have any slides which you take for customer demos on how , why 
If you can share the details it would be of great help please .
Thanks in advance .

Regards
Sri

**Comment by larshp** [comment]
abapGit is not a commercial product, so there are no customers, only users and community 😄 

All my stuff is shared at http://docs.abapgit.org/other-articles-and-presentations.html

My slides are usually only images, and not very much text. But also see
https://blogs.sap.com/2017/05/07/abap-using-git-for-safety-and-transparency/
and
https://blogs.sap.com/2017/11/19/getting-started-open-sourcing-abap-code/

which describes the most important parts of abapGit from my point of view.

**Comment by srikanthGajula1** [comment]
Thanks Lars Appreciate your quick response :)

Regards
Sri

**Comment by larshp** [comment]
feel free to jump onto the slack channel, https://abapgit-slackinviter.herokuapp.com/ if you like to discuss approaches/processes

**Comment by larshp** [comment]
guess this can be closed
