### ISSUE TITLE
More precised title for password popup

### ISSUE THREAD

**Issue by gepparta** [larshp/abapGit#1261]
related to #783
While showing password-popups for git servers, 
it would be nice to have a more precised title for this popup.
Currently just "<current SID etc.> Login" is displayed.
It would be nice to have something like "<current SID etc.> Login at github.com"

The benefit would be, one could use tools like Keepass to enter user and password automagically.
For this feature to work, a current window (LogIn Popup) need to have something unique, for example at least the domain name of corresponding server where we try to login. 
Then tools like Keepass are able to automatically find the right user and pass for it.
For more information about Keepass autotype see: https://keepass.info/help/base/autotype.html

I have already a working forked solution at https://github.com/gepparta/abapGit  for this.
This is how it looks like:
![image](https://user-images.githubusercontent.com/3863263/37670005-805f890e-2c68-11e8-80f8-4b98a6ce8be4.png)

**Comment by christianguenter2** [comment]
Sounds like a very good idea to me. Today I copy and paste a lot from KeePass to abapGit...

**Comment by larshp** [comment]
Looks good to me, feel free to submit a PR

**Comment by gepparta** [comment]
Cool, PR is on the way.
This autotype is working for me:
![image](https://user-images.githubusercontent.com/3863263/37674306-dbc55f12-2c72-11e8-94d5-7c7ffa30f6b8.png)

**Comment by gepparta** [comment]
see PR #1262

**Comment by larshp** [comment]
closing, PR merged
