### ISSUE TITLE
Error: PREFIX: Unexpected package naming(ZNEXT_GENERATION_ABAP_V2) 

### ISSUE THREAD

**Issue by arcanist123** [larshp/abapGit#1267]
Basically I am getting this error when I am trying to include a main package that is containing ZNEXT_GENERATION_ABAP_V2 package into the offline git repository

**Comment by flaiker** [comment]
What does the package hierarchy of your project look like?

**Comment by arcanist123** [comment]
Like this
https://i.imgur.com/VURJYTD.png

**Comment by larshp** [comment]
set the package/folder logic to FULL, under Advanced -> Repo settings

see http://docs.abapgit.org/ref-dot-abapgit.html for a description of package logic

**Comment by arcanist123** [comment]
Setting the logic to full resolved issue. Thank you so much.
It might be more user friendly to somehow wrap the exception into more informative message. Generally I consider exception that is reaching me to be a bug.
Thanks again. Perhaps I will try to wrap it into message myself :)

**Comment by larshp** [comment]
good idea, we should do that

**Comment by EduardoCopat** [comment]
Closing, as the message seems to be more clear:

https://github.com/larshp/abapGit/blob/72f89f74f544a257eb81df22eb55b5e3ce80e6c7/src/zcl_abapgit_folder_logic.clas.abap#L60-L64

Issue can be reopened, if not.

**Comment by nomssi** [comment]
**PREFIX: Unexpected package naming (YRAP_TRAVEL_U_EYJFC)you might switch to FULL folder logic.**
while working with abapGit plugin for SAP Cloud Platform ABAP Environment.

How to set the folder logic to FULL?

**Comment by larshp** [comment]
this issue is closed, for new issues, not answered by existing issues, please a new issue
