### ISSUE TITLE
Error: SYNTAX_ERROR in ZCL_ABAPGIT_2FA_AUTH_BASE when pushing

### ISSUE THREAD

**Issue by pacroy** [larshp/abapGit#1274]
> In include "ZCL_ABAPGIT_2FA_AUTH_BASE=====CM006     ", in line 1 of program
 "ZCL_ABAPGIT_2FA_AUTH_BASE=====CP        ", the following syntax errors
have occurred:
Method "GET_SERVICE_ID_FROM_URL" is not declared or inherited in class
 "ZCL_ABAPGIT_2FA_AUTH_BASE". -

This happens when commit changes and push to remote repository. Start seeing this error from v1.61.0

Short dump: [syntax_error.zip](https://github.com/larshp/abapGit/files/1850296/syntax_error.zip)

**Comment by pacroy** [comment]
Tested and found the same dump in v.1.60.0. Reverted back to v.1.59.0 and found no more dump.

**Comment by larshp** [comment]
yeah, copy paste the source manually to the class from https://github.com/larshp/abapGit/blob/master/src/http/zcl_abapgit_2fa_auth_base.clas.abap

also see https://github.com/larshp/abapGit/issues/1247

**Comment by larshp** [comment]
workaround is described above

we dont have an easy way of reproducing this, closing
