### ISSUE TITLE
Dump ITAB_DUPLICATE_KEY in method CALCULATE_STATUS (ZCL_ABAPGIT_FILE_STATUS)

### ISSUE THREAD

**Issue by nomssi** [larshp/abapGit#1275]
While trying to update the code for the course _Writing Testable Code for ABAP_ I get a short dump

       SORT lt_items. " Default key - type, name, pkg
       DELETE ADJACENT DUPLICATES FROM lt_items.
       lt_items_idx = lt_items. " Self protection + UNIQUE records assertion  <<<<<<<<< DUMP here

I think it might be due to this entry:
![abapgit_error_sort](https://user-images.githubusercontent.com/18452507/37976321-8ba27fdc-31e1-11e8-87d6-52b7dc9355e5.png)

my current workaround

        DELETE ADJACENT DUPLICATES FROM lt_items COMPARING obj_type obj_name. " devclass

**Comment by larshp** [comment]
hmm, I imported the new zip without problems

guess your main package is "$WTC_EXERCISES"? which does not leave room for "REF_REBATE_ENGINE"

From my system, using "$WTC1" as main package,
![image](https://user-images.githubusercontent.com/5888506/37979153-252df572-31e8-11e8-9946-683fb951f71a.png)

**Comment by nomssi** [comment]
Hi Lars,
your guess is correct.

**Comment by larshp** [comment]
Change to be implemented in abapGit:
Error message if the package name gets too long

**Comment by hardyp** [comment]
This problem (short dump) can be caused by various means. For example if I try to download a large set of objects using ZABAPGIT and whilst that is in progress open another session and then try to open ZABAPGIT again then both sessions dump and thereafter you cannot call transaction ZABAPGIT without getting a short dump.
I know how to fix this and will tyr to create a pull request.

**Comment by gregorwolf** [comment]
Today I run also into this issue when cloning the [ABAP SDK for Azure](https://github.com/Microsoft/ABAP-SDK-for-Azure) repository into a fresh system. For the moment I've fixed it by using the fix by @hardyp.

**Comment by larshp** [comment]
@gregorwolf are you running the latest abapGit version? What is the package name you are cloning into?

**Comment by gregorwolf** [comment]
Just updated abapGit from GitHub. I've used $ZADF as the package to clone into.

**Comment by larshp** [comment]
Okay,

Original issue: error message to be implemented if the package name gets too long

New issue found by Gregor, when installing the Azure SDK into $ZADF abapGit dumps. As $ZADF is part of the folder structure, https://github.com/Microsoft/ABAP-SDK-for-Azure/tree/master/src/zadf (FULL folder logic is used) some unexpected stuff happens. We need to implement logic which does not allow the root package to be named identical to one of the subpackages in the repo.
