### ISSUE TITLE
TRAN: corrupted parameter transaction after cloning 

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1276]
The parameters of a parameter transaction are corrupted after cloning.
Example repo: https://gitlab.com/christianguenter/test_tcode.git 

Initial state of the transaction.
![image](https://user-images.githubusercontent.com/17437789/37979687-865f7ec8-31e9-11e8-8618-d3aa9bddb4fb.png)

Then I commited the transaction, uninstalled the repo and cloned it. Then I get this diff.

![image](https://user-images.githubusercontent.com/17437789/37979738-a6eb5158-31e9-11e8-9d88-07fa14ef4d83.png)

The viewname was corrupted.
![image](https://user-images.githubusercontent.com/17437789/37979750-b16152a4-31e9-11e8-9769-b795cc1d9e21.png)

It seems that's something wrong here. 
https://github.com/larshp/abapGit/blob/d49ac90a3b737e21de82808bfb1f8b7248441b7a/src/objects/zcl_abapgit_object_tran.clas.abap#L95-L222

**Comment by larshp** [comment]
cool, perhaps add some unit tests for METHOD split_parameters

**Comment by christianguenter2** [comment]
yep, that's what I'm doing right now :-)
