### ISSUE TITLE
Dump when importing from ZIP

### ISSUE THREAD

**Issue by Sdfraga** [larshp/abapGit#1288]
Hi,

I have launched abapGit today and a new version was suggested to pull from git server. I started the installation process as usual but it ended with a dump.
After that, I have launched abapGit again and I can see the following message:

<img width="1551" alt="screen shot 2018-03-31 at 16 12 07" src="https://user-images.githubusercontent.com/16186872/38164027-4fb67a8a-34fe-11e8-961c-d641251a3f42.png">

I tried to do a Pull again, but I more dumps.
Classes: zcl_abapgit_services_repo and zcl_abapgit_services_abapgit were not the same than the ones from the online abapGit repo so I manually changed them.

Noe the pull doesn't dump anymore, but nothing is done. I have 2 popups during the Pull process with the following:

<img width="551" alt="screen shot 2018-03-31 at 16 14 59" src="https://user-images.githubusercontent.com/16186872/38164071-c68c46c6-34fe-11e8-8cd8-a20b155344c3.png">

<img width="364" alt="screen shot 2018-03-31 at 16 15 56" src="https://user-images.githubusercontent.com/16186872/38164072-d36aa0ea-34fe-11e8-8807-2d4ac58c49fb.png">

I press OK for both of them, the process goes until the end, but no popup appears asking for the activation of some objects as it is normal.

Now when I try to upload an offline repo, I have a LOAD_PROGRAM_CLASS_MISMATCH dump.
You can find the dump in the attachment.

Anyone had the same issue?
[abapGitImportZIPDump.txt](https://github.com/larshp/abapGit/files/1865543/abapGitImportZIPDump.txt)

Thanks
Sérgio Fraga

**Comment by Sdfraga** [comment]
I have found out that if I go directly to the offline repo and import the ZIP, without previously run the Pull process on abapGit repo no dump happens and the import of the offline objects runs smoothly.

**Comment by larshp** [comment]
LOAD_PROGRAM_CLASS_MISMATCH = try again, program source has changed in the meanwhile

**Comment by larshp** [comment]
I also get diffs in `zcl_abapgit_services_repo` and `zcl_abapgit_services_abapgit` after pulling latest version, however is is difficult to debug as these are central classes. Adjusting code manually

**Comment by larshp** [comment]
Tried reproducing in repo https://github.com/larshp/test, master branch contains old code, "new" branch contains new code. Switch from master -> new works, hmm

**Comment by R875482** [comment]
Tried updating this morning, and experienced the same issue as OP.

**Comment by DerGuteWolf** [comment]
I also have the same problems as the OP (I already did one pull). What is the recommended procedure to get rid of the dumps?

**Comment by larshp** [comment]
workaround: 
1: copy the source code from https://github.com/larshp/abapGit/blob/master/src/ui/zcl_abapgit_services_repo.clas.abap manually into the system
2: delete all abapGit objects,  and reinstall via normal procedure

**Comment by DerGuteWolf** [comment]
Thanks. I updated the report ZABAPGIT from https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap, deleted the classes ZCL_ABAPGIT_SERVICES_REPO, ZCL_ABAPGIT_SERVICES_GIT and ZCL_ABAPGIT_SERVICES_ABAPGIT (the classes from the errors in the screenshot above), started ZABAPGIT and did a pull, then updated the report ZABAPGIT a second time. Currently no dumps and no strange displays anymore. Only ZABAPGIT  and ZCL_ABAPGIT_2FA_AUTH_BASE are now marked as having a difference.

**Comment by larshp** [comment]
try clicking "diff" to see the differences, and Advanced -> Reset local, if that does not work you can try manually adjusting the code

**Comment by DerGuteWolf** [comment]
Apparantly in ZCL_ABAPGIT_2FA_AUTH_BASE I have the method implementation get_service_id_from_url which is not in the git master.
ZABAPGIT in git master is only 72 lines while https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap is 50195 lines long.
I have now done a reset local, everything is fine now.

**Comment by larshp** [comment]
sorry about the trouble, but its sometime difficult to keep everything working and in sync 😄

**Comment by R875482** [comment]
Can confirm work around works. Thanks for the great work lars 👍

**Comment by DerGuteWolf** [comment]
Hi Lars,

no poblem, with the workaround I got everything working.

Thanks for the great work!

Regards,
  DerGuteWolf

**Comment by Sdfraga** [comment]
Hi Lars,

I have done the workaround and everything is fine now for me too.

Should we close the issue?

Thanks a lot
Sérgio Fraga

**Comment by larshp** [comment]
I'm not confident that the original problem is fixed, however I have not found any way of reproducing the issue, so lets close
