### ISSUE TITLE
New XML configuration/persistency

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#129]
change to xml, its easier to extend than the current setup

LCL_PERSISTENCY
LCL_USER

**Comment by grahamrobbo** [comment]
I am wondering if using the server-side cookie functionality might be a good solution for persistence? It means you can have separate persistence objects for each user, and even for each package and/or repo. Also it will persist ABAP structures (including deep structures) without having to convert them to XML.

**Comment by larshp** [comment]
hmm, havent tried using server-side cookies, so not sure how it works

Since programs are installed globally on the server it talks for sharing persistence across users, but in some cases, eg. for private repositories it might be that only a few users on the system have access to downloading the repository, this talks for per-user persistence.

The current approach is very low-tech, but this makes it very easy to manually change settings in SO10, I do this a lot when testing, or when something breaks its easy just to start over.

**Comment by grahamrobbo** [comment]
You make a good point about being able to easily change texts in SO10. Check out CL_BSP_SERVER_SIDE_COOKIE and see what you think? The data actually gets stored in table SSCOOKIE.

**Comment by larshp** [comment]
thanks will take a look, but I dont really like not being able to easily modify and see the data, perhaps there are some standard tools for it?

Looking at XML it is already used extensively in the serialization part of abapGit, so it should be very easy to move to an XML using SO10 for storage

**Comment by mrsimpson** [comment]
Why no use a traditional db-table (or multiple ones)?
The table(s) could be easily created during program execution with DDIF_TABL_PUT.
Alternatively, it was easy to create the table during installation (by serializing it to the ABAPGit repo). Downside of this approach was that you'd need a redundant persistency for the non-installers (just like the current one). This might result in a reduced feature-set for non-installers.

**Comment by larshp** [comment]
hmm, guess this falls under the design goal "small system footprint"

I'm worried if using tables, that it will be difficult to keep track of adding columns after the tables have been created. Eg. if there is a need for a master language column per project, then the table would need to be updated. The XML solution would be commonly known and have the field for the new "column" as blank.

the SO10 solution is kind of a hack, but it makes it very easy to change the configuration or delete the configuration if something messes up. With tables we would have to generate a table maintenance or build tools to manually edit or reset the configuration.

I have a plan to store the SHA1 hashes for all objects this would add another table. So we are up to at least 3 database tables: repositories, repository content and user settings. XML and SO10 can store everything in one place making it easy to add or remove stuff, plus have a small system footprint.

**Comment by mrsimpson** [comment]
Agree to all you wrote. However, it might get a bit messy particularly with editing the xml in SO10 as information is being added. 
Two things I don't like at all about so10:
* Language dependency
* Formatting option for each line

If it shall be text, I'd propose to put the xml-file in the mime-rep. 
However, both solutions have the disadvantage of not being able to manage concurrent writes. Of course, this might be a bit far stretched, but in larger systems not that unlikely.
What about a DB table for the repos with a link to a repo-specific xml-source in the mime-rep? This would render the repo the lockable entity which I consider ok.

**Comment by larshp** [comment]
Yea, the mime-rep is a good idea. I'm a bit worried about exceeding the line length of 72(?) characters in SO10(without using extended lines).

Now is a very good time to consider solving the concurrency issues. 

With a database table do you imagine a lock object, and doing optimistic locking for each repository? This would be a 100% bulletproof solution, however it would require another object.

Another idea could be to have a last-saved timestamp, and only allow saves if the values in memory matches the stored data. This would most likely work 99% of the time, theoretically it can fail due to not using semaphores.

**Comment by mrsimpson** [comment]
As an ABAPer, I indeed thought about a lock-object and pessimistic locking - d'oh! 
Of course, optimistic locking is more fancy ;-)
I don't have the long history like you and my focus actually never is in the single-source-file-shipment. I consider it more valuable to have a maintainable and powerful product. With the installation option at hand, I am also not that afraid of increasing the number of artifacts. However, I do think that a last-saved-time stamp is a good idea anyway and implementing "very optimistic-locking" on that basis should do fine for the next months. Plus it is compatible to be extended by a lock-object later on.

**Comment by larshp** [comment]
yeah, hmm

Going back to the requirements:
a: need something that can be extended with new fields when/if needed
b: it should be possible for 2 users to commit to 2 different repositories at the same time without messing stuff up or errors
c: try reducing number of artifacts(design goal: small system footprint)
d: allow for easy upgrades of abapGit(design goal: easy upgrade)

**Comment by larshp** [comment]
new approach(how many different are we up to now?): 

as in the normal ABAP world I've been thinking of normalized database tables. What if we make the sacrifice and don't normalize, and do it the wrong way?

1 new database table ZABAPGIT, consisting of 3 fields:
TYPE (key), CHAR 10
VALUE (key). CHAR 10
XML, STRING
the xml would contain the values needed, plus it could contain "subtables". And have a proper lock-object for the table. The 2 artifacts would be created when running zabapgit in package $TMP. The table would likely never need to be changed.

I would like to have a way to edit the XML manually, but it can be added to the ZABAPGIT report, it is just hard work.

For the non-database table approaches, I'm afraid that it needs quite a lot of code to fix the concurrency. And it might require multiple SO10/mime repository objects. So just having the above 2 objects might be better and easier to develop.

hmm

**Comment by mrsimpson** [comment]
If you go for that wrong approach of a name-value-table, you could at least provide a parent-field and serialize the entire DOM into that structure. I don't like it a lot, but if it shall be untyped, this at least was better for manipulation purposes compared to having XML-fragments in the "value". 

Personally, I consider the repo precisely branch the prime entity. Thus, I'd be fine with a table for that entity. Having a link to a mime-path containing the subordinate entities in an attribute of the repo/branch table had the benefit of having an easy opportunity to manipulate (up/download) the xml. 
What do you dislike about that compared to name/value?

**Comment by larshp** [comment]
parent-field: not sure I understand, can you elaborate?

I'm mainly concerned with number of artifacts, storing the XML in the table will get rid of 1 mime per repository?


2 example rows with data in above approach would look something like the following:

TYPE: "REPO"
VALUE: "000000000001"
XML: <repo><sha1>38cd6d615e2108112f42e1301dcef09efc3add54</sha1><branch>refs/head/master</branch></repo>

TYPE: "USER"
VALUE: "DEVELOPER"
XML: <user><username>larshp</username><email>larshp@emailll.com</email></user>

**Comment by mrsimpson** [comment]
Thanks for the samples, this is what I thought of as well except for storing the xml in the mime-rep.
TYPE: "REPO"
VALUE: "000000000001"
MIME: /sap/abapgit/repo-000000000001.xml

> I'm mainly concerned with number of artifacts, storing the XML in the table will get rid of 1 mime per repository?
Ack. Didn't understand your concern about number of artifacts at runtime, only thought of designtime. Why are you targeting this aim? Consistency? Honestly, I can understand that as I don't know how mime-rep e. g. handles concurrency.

My second thought was to have a "classical" name-value-table. This would basically resolve the XML DOM to separate name-value-pairs:

TYPE | NAME | VALUE | GUID | PARENT_GUID
--------|--------|---------|-------|----
REPO | ID | 000000000001 | 1 |
ATTR | sha1 | 38cd6d615e2108112f42e1301dcef09efc3add54 | 2 | 1
ATTR | branch | refs/head/master | 3 | 1
ATTR | url | https://github.com/larshp/abapGit.git | 4 | 1
| USER | username | lasrshp | 5 | 
| ATTR | email | lars@emailllllllll.com | 6 | 5

Of course reals samples would look not as clean due to real GUIDs ;)

**Comment by sbcgua** [comment]
Hi All, If I may join this conversation... :)

Why XML at all ? Or table ?! Both are not really readable, nor really editable.
SO10 approach looks rather nice and indeed enjoys small footprint. Editor is a part of the system. I'd say that it is just format which consider revising.

Ok, maybe add a small editor tool (imho separate from the main program) with a singular entry window to avoid limitation of 72 chars and introduce some usability features.

For the format I'd propose following standard git config format e.g.:

**ZABAPGIT_REPOS**
```
[repo "MyRepo1"]
  devc   = ZPACKAGE
  url    = https://github.com/sbcgua/somerepo.git
  branch = refs/heads/master
  sha1   = shad66a67e3f4b3c37256782f5f088c741668031884
  ignore = PROG:ZTEST*;DOCU:*   << would be nice feature but needs some effort to design, e.g. ignoring client side AND SERVER side separately, because not all objects are imported (e.g. readme ...) ... just thoughts ...

[repo "MyRepo2"]
  ...

[params]  << some global params if needed
  whateverparam = value

```
**ZABAPGIT_USERX**
```
[user]
  name  = atsy     << for commits
  email = someemail@some.domain
  user  = sbcgua   << for login, btw always empty now - inconvenient

[user "MyRepo1"] << higher priority settings for specific repo
  email = someemail@another.domain

[core]
  ???
```

**Comment by mrsimpson** [comment]
Why XML? It's easily consumable in ABAP. 
Till we reach the persistency, we can operate on (deep) ABAP structures. 
Before the write, simple call the id-transformation and everything is set. 
DB tables have the advantage of a clear transaction concept including locking. 
Thus, combining the both seems to give the best comfort und extensibility. 
For XML, there are so many supporting text-editors in the front end that U don't consider it "unreadable". JSON is of course fancier, but afaik the ABAP2JSON transformation exists only in 740++, not 7.02 which is targeted by Lars. 
The editor finally is the sole aspect which favors so10. When saving XML in a DB table, using a fronted-editor and executing copy-paste is not an option due to length limitation in se16 (afaik). 
Therefore, I proposed to put it in the mime-rep. If the effort to implement an in-place-editing is limited, I'd be fine with the table attribute as well.

**Comment by larshp** [comment]
sbcgua: sure, feel free to share your thoughts :smile:

I agree with mrsimpson's commens above. Going to XML will enable deep/table structures, which are difficult to build logic for in the SO10 approach

PARENT_GUID: ahh, now I understand. It could also be extended to support complex table structures, however wouldn't it just be another way of serializing data? We already have the XML stuff built which can handle de/-serialization of complex structures. I imagine the data in memory being stored in a (deep)-structure for eg. repositories,


types: begin of ty_object,
  sha1 type something,
  filename type something,
end of ty_object,

types: begin of ty_repo,
  sha1 type something,
  branch type something,
  url type something,
  master_language type something
  objects type table of ty_object,
end of ty_repo

**Comment by mrsimpson** [comment]
> It could also be extended to support complex table structures, however wouldn't it just be another way of serializing data? We already have the XML stuff built which can handle de/-serialization of complex structures. 
Yup, right. Transforming XML to that structure would be quite simple though

**Comment by sbcgua** [comment]
It seems I'm alone in my opinion :) Still another try:

> Why XML? It's easily consumable in ABAP. 

But it is not easily consumable by user. Programs are for users. ... ;) Look at webdev - it has been moving to simplification (from XML and SOAP to json and yaml e.g.)

> we can operate on (deep) ABAP structures

Mmm. Here I don't quite understand what you mean. If we are talking about **config** - I'm not sure there is a need for deep structures. In my approach it is 3 levels (textname-group-parameter). If more deeper needed ... well then we come to JSON indeed.

> but afaik the ABAP2JSON transformation exists only in 740++

JSON would for sure be better. **It is backported** by the way. I confirm it works in 7.31. And accroding to [this](https://scn.sap.com/community/abap/blog/2013/07/04/abap-news-for-release-740--abap-and-json) should work in 7.02 too.

**Comment by larshp** [comment]
If everything works, then nobody will get to see or have a need to modify the stored data. Core development or debugging is currently the only use case requiring to modify the data manually. Everything will be hidden behind a nice user interface like today, currently no users need to modify texts in SO10 manually, the program logic manages the updates.

We need deep structures for some of the future enhancements planned, the stored structure might look something like the following

```abap
types: begin of ty_object,
  sha1 type something,
  filename type something,
end of ty_object,

types: begin of ty_repo,
  sha1 type something,
  branch type something,
  url type something,
  offline type abap_bool,
  master_language type spras,
  objects type table of ty_object,
end of ty_repo.
```

I like JSON but also like to make sure abapGit can be used by as many people as possible without installing additional notes or support packages(notes in above link mentions kernel patches). abapGit is a big hack, and we need to make some sacrifices to make sure it works for everyone and it might not have a perfect architecture to make it easily accessible.

The XML serialization is already implemented and used for object serialization, I think the project will benefit by reusing this instead of building a new serialization method from scratch.

**Comment by larshp** [comment]
I've done some prototyping, see
https://github.com/larshp/abapGit-per-test/blob/master/zper_stuff.prog.abap

**Comment by mrsimpson** [comment]
yup, that's what I expected.

In the ancient-times, `EDITOR-CALL` opened an editor. NOwadays, `CL_GUI_TEXTEDIT` should do the job.
Just got no time to sample it.

**Comment by mrsimpson** [comment]
alright, really depressed now: Didn't get the textedit-control to appear. I despise DYNPRO. 
`parent = cl_gui_container=>screen0` neither worked on the textedit itself nor on the docking container.
`EDITOR-CALL` might not be such a bad idea

**Comment by larshp** [comment]
I think the html container blocks for new custom containers to appear. Been thinking of doing a solution inside the html container using <textarea> to edit the XML

**Comment by mrsimpson** [comment]
Didn't even get to display it within a separate report without a Dynpro. 
But this is not my front end anyway. 
A textedit will require some small JS. Honestly, as this is not intended to be a real User interaction UI, I'd be happy with an upload form as well.

**Comment by larshp** [comment]
I created a small test program, see https://github.com/larshp/abapGit-per-test/blob/master/zxml_edit.abap there is no JS required. Note that most of the code is copied from ZABAPGIT, just method RENDER is special

**Comment by larshp** [comment]
mostly done, should be able to move it to main repository quite soon
