### ISSUE TITLE
ECTD syntax error

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1295]
Only tested the recent PR on 751, seems that it does not work on 750,

![image](https://user-images.githubusercontent.com/5888506/38255769-febceb9e-375c-11e8-8f9a-8e5119e8b7d7.png)

perhaps use UPLOAD_DATA_FROM_STREAM instead,

![image](https://user-images.githubusercontent.com/5888506/38255785-05304778-375d-11e8-95d3-8d823dd32ce8.png)

**Comment by christianguenter2** [comment]
Hm, damn. That seems like a big problem. UPLOAD_DATA_FROM_STREAM operates on frontend files. So we need to examine other solutions.
