### ISSUE TITLE
Install abapGit repo - wrong errorhandling

### ISSUE THREAD

**Issue by xamafe** [larshp/abapGit#1297]
Hello,

I searched, but found no similar issue... If Im wrong, please tell me :)

Error:
if you start "install abapGit repo" and it fails, then it is marked as "installed".

I had errors while:
* edited the Code of ZABAPGIT while running the program
* logged in DE, which caused the $ABAPGIT package to fail

Maybe we could implement a "Redo installation" or dont write the changes to ZABAPGIT table.

CU

xamafe

**Comment by xamafe** [comment]
OK, this can be closed... I didnt recognize Advanced --> Database Util as a solution to delete tableentries ...

**Comment by larshp** [comment]
😄 

There is also an uninstall and remove option under repo settings
