### ISSUE TITLE
GitHub 2FA implementation - Doesn't authenticate with HTTP Proxy

### ISSUE THREAD

**Issue by chrismills** [larshp/abapGit#1298]
When connecting to a private GitHub repo via a corporate proxy server which requires authentication the following error will be returned:

Error: 2FA error: Communication error: SSL client SSL Client (Anonymous).

Class ZCL_ABAPGIT_2FA_GITHUB_AUTH is creating its own HTTP client via CL_HTTP_CLIENT in methods is_2fa_required and authenticate, however, its not setting the proxy auth where required, thus getting a HTTP 407 Proxy auth required but returning the above ambiguous message

Happy to help resolve if this isn't something already being worked on? Think we just need to add code similar to below when the client is being established in both methods previously mentioned

IF lo_proxy->get_proxy_authentication( mv_github_api_url ) = abap_true.
        zcl_abapgit_proxy_auth=>run( li_client ).
ENDIF.

But also add some appropriate exception handling.

**Comment by larshp** [comment]
cool, feel free to submit a PR, I dont think anybody is currently looking into this

**Comment by chrismills** [comment]
Closing, resolved via pull request #1300
