### ISSUE TITLE
explore page

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#130]
automagically update with stars, watchers, last update etc

via Travis? as the control runs in quirks mode it is not possible to update it on client side via javascript

**Comment by larshp** [comment]
request sent to travis ci to enable cron jobs for this repository

**Comment by larshp** [comment]
and it is enabled

to do: code stuff to build html/json pages

**Comment by EduardoCopat** [comment]
To add the star/watchers/forks, we could use a [Github buttons](https://buttons.github.io/).

See example at:

https://jsfiddle.net/utsgtqvr/

What do you think?

**Comment by larshp** [comment]
sure, lets try it

I tested some stuff a while ago, https://github.com/larshp/abapGit/commit/8812dfbca2fbd1a3caa9d89a51ddda666b25399a#diff-e457100bba8242ef0935984e0c21a4ff but it did not work when running inside SAP GUI, worked ok in a browser

**Comment by sbcgua** [comment]
> ... it did not work when running inside SAP GUI ...

potentially similar issue as with inetrnal pages - can you try to add DOCTYPE and METAs to the header ?

```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=11,10,9,8" />
```

**Comment by EduardoCopat** [comment]
w.i.p: https://eduardocopat.github.io/abapGit/explore.html

**Comment by larshp** [comment]
cool, currently the projects are sorted randomly, so that everyone gets the same exposure

but I was thinking to add some buttons for sorting, eg: alphabetically, last updated, by stars, if possible

**Comment by larshp** [comment]
following seems to work, this would allow integrating the explore page closer into abapGit, and not having to call the external `explore.html` page

```abap
    ro_html->add( '<script type="text/javascript">' ).
    ro_html->add( 'alert("jello");' ).
    ro_html->add( 'function foo(evt) {' ).
    ro_html->add( 'alert(evt.target.responseText);' ).
    ro_html->add( '}' ).
    ro_html->add( 'let oReq = new XMLHttpRequest();' ).
    ro_html->add( 'oReq.addEventListener("load", foo);' ).
    ro_html->add( 'oReq.open("GET", "https://raw.githubusercontent.com/larshp/abapGit/master/docs/repos.json");' ).
    ro_html->add( 'oReq.send();' ).
    ro_html->add( '</script>' ).
```

**Comment by larshp** [comment]
Hi All,
I'd like to move the explore page and https://github.com/larshp/abapGit/blob/master/docs/repos.json into a separate repo, any cool ideas for naming?

* the-abap-list
* the-abapgit-list
* abap-open-source-list

**Comment by sbcgua** [comment]
abaphub
abapopen
abapbook
openabap
abapnotdead :))
abaper (or abapr)
apm (abap package manager)
abapcentral

With my own preference for the first two and probably apm if it evolves in package manager (although the domain it taken ;) ).

P.S. sorry for long silence, still busy with some other things ...

**Comment by pokrakam** [comment]
ABAPtools

**Comment by flaiker** [comment]
abap-saint
abap-spam
abap-se03
abap-stms
...
I have nothing :P

**Comment by larshp** [comment]
https://github.com/dotabap organization and domain dotabap.org registered

**Comment by larshp** [comment]
All stuff regarding the repo list and explore page will be handled in https://github.com/orgs/dotabap/

To be done in a month or so:
* delete https://github.com/larshp/abapGit/blob/master/docs/repos.json
* delete https://github.com/larshp/abapGit/blob/master/docs/explore.html
* adjust https://github.com/larshp/abapGit/blob/master/docs/_config.yml

after the stuff is deleted this issue can be closed

**Comment by larshp** [comment]
closing, everything regarding explore page moved to https://github.com/dotabap
