### ISSUE TITLE
Type "ZCL_AAB_ID" is unknown

### ISSUE THREAD

**Issue by GioDel** [larshp/abapGit#1304]
Hi, 

I just tried to create a local report and pasted in the given code. The syntax check says: 
Type "ZCL_AAB_ID" is unknown

I this something that has to be created additionally somewhere?

Thanks!
Giovanni

**Comment by christianguenter2** [comment]
Interestingly there's no such thing as "ZCL_AAB_ID˙" in the [latest build](https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap). Can you post a screenshot of the source code position and the syntax error?

**Comment by GioDel** [comment]
![cl_aab_id](https://user-images.githubusercontent.com/25393300/38664054-d0307fb0-3e38-11e8-9e1d-eedc01afe24d.png)

Hi Günter, heres the screenshot. In the latest build it's called CL_AAB_ID. Thanks! Giovanni

**Comment by christianguenter2** [comment]
What's your netweaver release? My guess is that you are below 7.02.

**Comment by GioDel** [comment]
The system is on an old netweaver version called NGAP. I assume its software component SAP_BASIS release 804. Maybe I can replace this type by a local one.

**Comment by GioDel** [comment]
Yes I think that's our old stack. And thanks a lot for your help and feedback!

**Comment by christianguenter2** [comment]
closing...
