### ISSUE TITLE
Prefill committer name and email with user's email & full name if emtpy

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1309]
I'm not quite sure whether this was already discussed. Wouldn't it make sense to prefill the committer name and email with the user's email and full name if no other information is available?

![image](https://user-images.githubusercontent.com/17437789/38731323-1f073930-3f1a-11e8-8184-f72ec1a21689.png)

Here we to prefill the fields with default information from the repo and the git default user. I'd like to add a third case. When both are empty considering the user master data.
https://github.com/larshp/abapGit/blob/68d057151651fcccdb23f58e8b7711eecb8d2384/src/ui/zcl_abapgit_gui_page_commit.clas.abap#L93-L103

We do it already for background mode.
https://github.com/larshp/abapGit/pull/1219

**Comment by larshp** [comment]
seems good to me
