### ISSUE TITLE
New userexit methods to influence background mode

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1315]
We are currently in a situation where we'd like to have more control over background mode. E.g. we have multiple repos with background mode enabled, but we don't want to schedule the background job. Instead we want to submit the job on demand for a particular repository. And in addition want to change the commit message. 
Therefore it would make sense for us to have two new userexits.

 - filter the list of relevant repos here
https://github.com/larshp/abapGit/blob/7152b4281a37b0e9a7cbf152fd6581a5ba708d32/src/zcl_abapgit_background.clas.abap#L288

and

- change the background commit message here
https://github.com/larshp/abapGit/blob/7152b4281a37b0e9a7cbf152fd6581a5ba708d32/src/zcl_abapgit_background.clas.abap#L61

Any opinions on this? Does this make sense? If yes, I'll make a PR.

**Comment by larshp** [comment]
Submit job: cool, I guess this can be done somehow by calling the global classes, perhaps add a description on how to do this in the documentation.

Exits: good, but do consider if this is something that might be of benefit to others, or something client/customer specific. If re-useable consider adding it as a feature in abapGit master

**Comment by larshp** [comment]
Perhaps it can be made more generic in some way

**Comment by christianguenter2** [comment]
I think it would be better to leverage the global classes for our use case. 
I'll close.
