### ISSUE TITLE
User specific abapGit settings

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1316]
The abapGit settings dialog is global and afaik there are no user specific settings at the moment. For us it would make sense to make at least these two properties user specific (Yes, there are colleagues who don't prefer ADT ;-) ). 

![image](https://user-images.githubusercontent.com/17437789/38871803-198e6452-4252-11e8-8059-21a90873af94.png)

Maybe we can split the settings page into two sections with global and personal settings? Of course we need a user specific settings persistency first.

Any opinions on this? Or am I missing the obvious and this is already possible?

**Comment by larshp** [comment]
sounds good to me

There is already a user-specific object which most likely can be used for storing values, check Advanced -> Database Util

class `zcl_abapgit_persist_migrate` can be used for migration of values
