### ISSUE TITLE
SAP GUI for JAVA - Missing Icons

### ISSUE THREAD

**Issue by Sdfraga** [larshp/abapGit#1319]
Hello,

When I run abapGit with SAP GUI for JAVA I don't see any icons in the UI.
The functionality for each icon is there, just the icons are missing.

<img width="1326" alt="screen shot 2018-04-20 at 17 11 32" src="https://user-images.githubusercontent.com/16186872/39059119-f8e565de-44bd-11e8-940e-ca4b876c277d.png">

Anyone else has the same issue?

Thanks
Sérgio Fraga

**Comment by jfilak** [comment]
The same on Fedora 27.

**Comment by jfilak** [comment]
I sometimes see only the top frame "abapGit" - I plan to debug it and fix it - though, I am busy with my day job :-/

**Comment by larshp** [comment]
Under Advanced -> Debug info, abapGit shows the user agent,

![image](https://user-images.githubusercontent.com/5888506/39083671-6ae7895a-4568-11e8-90c6-ab6b5f9ec893.png)

**Comment by larshp** [comment]
Okay, this is quite difficult, it looks like SAP GUI for Java uses the JavaFX WebView component, which is difficult to debug, and I'm not sure which features to expect from it.

hmm 😕

**Comment by larshp** [comment]
closing, will be solved by #1479 (sometime)
