### ISSUE TITLE
ZCL_ABAPGIT_SERVICES_GIT syntax check error

### ISSUE THREAD

**Issue by rayatus** [larshp/abapGit#1327]
DUMP while trying to update a repo.

I have downloaded  manually ABAPGit from "https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap" today (23/04/2018), after that I've updated with the latest repository objects and when checking syntax some errors appears.

1. Pull after copying manually ZABAPGit.
![image](https://user-images.githubusercontent.com/12736990/39154384-46f28ada-474e-11e8-8fc4-485a2d619beb.png)

2. During upgrade ZABAPGIT has to be updated
![image](https://user-images.githubusercontent.com/12736990/39154410-51062fb8-474e-11e8-8f70-5c35e4c39206.png)

3. Executing syntax check
![image](https://user-images.githubusercontent.com/12736990/39154418-5a442f8a-474e-11e8-9043-fc33d186316a.png)

ZCL_ABAP_GIT_SERVICES_GIT seems has some kind of problems.

The problem is that, after upgrading, I can't perform commits nor pulls.

**Comment by rayatus** [comment]
sorry, I just found #1302 . I'll check if solution works also for me.

**Comment by rayatus** [comment]
Done, I have to do some manual things.

1. Move to package ZABAPGIT_UI following ABAP Classes 
zcl_abapgit_services_abapgit
zcl_abapgit_services_git
zcl_abapgit_services_repo

2. Replaced ABAP Class with the content from "https://github.com/larshp/abapGit/blob/master/src/ui/zcl_abapgit_services_git.clas.abap"

After that I was able to do a Pull request from GitRepo.


Thanks

**Comment by larshp** [comment]
sorry about the trouble, hope we will find the bug
