### ISSUE TITLE
Create tags and commits via API

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1329]
We have a custom release mechanism for our product and want to automatically tag the latest commit with the appropriate version number after the release. And optionally commit the latest changes if there are any.

Therefore we want leverage the global classes of abapGit. As we don't want any user interaction during the process we should be able to provide all necessary information (username, password, commit message, tag name, etc.) via the  API inferface. It seems that this is currently not possible.  Or am I mistaken?

I designed a small [prototype](https://github.com/christianguenter2/abapGit/blob/eb4cdaa5f7755a33e49842af50a99932985d47e6/src/zcl_abapgit_facade.clas.abap) with a simplified API to do that. In the end what we want is an API like this.

Create tag:
https://gitlab.com/christianguenter/test_tag_api/blob/master/z_test_tag_api.prog.abap#L8-24
```
PARAMETERS: repo_key TYPE  zif_abapgit_persistence=>ty_value OBLIGATORY,
            user     TYPE string OBLIGATORY LOWER CASE,
            password TYPE string OBLIGATORY LOWER CASE,
            tag      TYPE string OBLIGATORY LOWER CASE.

TRY.
    DATA(lo_abapgit_facade) = NEW zcl_abapgit_facade( iv_key      = repo_key
                                                      iv_user     = user
                                                      iv_password = password  ).

    DATA(message) = lo_abapgit_facade->create_tag( iv_tag_name = tag ).

    MESSAGE message TYPE 'I'.

  CATCH zcx_abapgit_exception INTO DATA(error).
    MESSAGE error TYPE 'S' DISPLAY LIKE 'E'.
ENDTRY.

```

Create commit:
https://gitlab.com/christianguenter/test_tag_api/blob/master/z_test_commit_api.prog.abap#L8-27

```
PARAMETERS: repo_key TYPE zif_abapgit_persistence=>ty_value OBLIGATORY,
            user     TYPE string OBLIGATORY LOWER CASE,
            password TYPE string OBLIGATORY LOWER CASE,
            comment  TYPE string OBLIGATORY LOWER CASE.

TRY.
    DATA(lo_abapgit_facade) = NEW zcl_abapgit_facade( iv_key      = repo_key
                                                      iv_user     = user
                                                      iv_password = password ).

    DATA(lt_staged) = lo_abapgit_facade->create_commit( iv_committer_name  = 'Christian Guenter'
                                                        iv_committer_email = 'christianguenter@googlemail.com'
                                                        iv_comment         = comment ).

  CATCH zcx_abapgit_exception INTO DATA(error).
    MESSAGE error TYPE 'S' DISPLAY LIKE 'E'.
    RETURN.
ENDTRY.

cl_demo_output=>display( lt_staged ).
```

The biggest problem is to cut the dependencies (i.e. password dialog, popups, etc.). I've choosen a lightweight (backdoor) dependency injection mechanism (you can also call it a factory) to solve that. 

A small example how it works. Method ACQUIRE_LOGIN_DETAILS of ZCL_ABAPGIT_HTTP directly calls the password dialog. 
https://github.com/larshp/abapGit/blob/be0b9d0df454cd67f9f7f68d202a0713bc7f1603/src/http/zcl_abapgit_http.clas.abap#L53-L62

We cut it out like this.
https://github.com/christianguenter2/abapGit/blob/eb4cdaa5f7755a33e49842af50a99932985d47e6/src/http/zcl_abapgit_http.clas.abap#L54-L61

```
    li_password_request ?= zcl_abapgit_di_container=>get_instance( |ZIF_ABAPGIT_PASSWORD_REQUEST| ).


    li_password_request->get(
      EXPORTING
        iv_repo_url = iv_url
      CHANGING
        cv_user     = lv_user
        cv_pass     = lv_pass ).
```

With this mechanism we are able to incject the credentials in the facade.
https://github.com/christianguenter2/abapGit/blob/eb4cdaa5f7755a33e49842af50a99932985d47e6/src/zcl_abapgit_facade.clas.abap#L151-L163

```

    DATA: lo_password_provider TYPE REF TO zcl_abapgit_password_provider.


    CREATE OBJECT lo_password_provider.


    lo_password_provider->set_user( iv_user ).
    lo_password_provider->set_password( iv_password ).


    zcl_abapgit_di_container=>set_instance( iv_name   = |ZIF_ABAPGIT_PASSWORD_REQUEST|
                                            io_object = lo_password_provider ).


```
In the we same way we cut the other dependencies and can perform the actions without user interaction.
It works quite well with our test cases. 

Does it make sense? Am I missing the obvious? Was dependency injection already discussed? Other ideas? Any Feedback is highly appreciated.

For the records here are some good resources about dependency injection in ABAP.
https://blogs.sap.com/?p=104505
https://blogs.sap.com/2014/01/06/successful-abap-dependency-injection/
https://blogs.sap.com/2013/08/28/dependency-injection-for-abap/

**Comment by larshp** [comment]
https://github.com/larshp/abapGit/blob/master/src/zcl_abapgit_background.clas.abap#L283-L286

**Comment by christianguenter2** [comment]
wasn't aware of zcl_abapgit_login_manager. I'll try it.

**Comment by larshp** [comment]
anyhow, we should get rid of the password popup in the backend, considering if it should throw an exception back to the GUI, and then the GUI will supply username+password. This opens some questions regarding state/stateless and performance

**Comment by christianguenter2** [comment]
Yes, I'll close. 
We are currently working with with zcl_abapgit_facade from my branch [exp_tag_api](https://github.com/christianguenter2/abapGit/tree/exp_tag_api). It works quite well in our szenario. Don't know how to incorporate this well to abapGit.
