### ISSUE TITLE
GUI Seperation: password popups

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1331]
As touched upon in https://github.com/larshp/abapGit/issues/1329, there are login popups when performing a git operation on a protected repository.

These are:
* Normal Password popup
* 2FA password popup
* Proxy authentication popup

Ideally these popups should be separated from the API, and somehow exposed via the signature.

**Comment by larshp** [comment]
### Normal Passwords
Okay, currently it is possible to set the normal http username and password via

```abap
zcl_abapgit_login_manager=>set(
  iv_uri      = lo_repo->get_url( )
  iv_username = <ls_list>-username
  iv_password = <ls_list>-password ).
```

However, this assumes that the code knows if the repo is password protected. If the repo is password protected, a GUI popup will be shown to the user(ZCL_ABAPGIT_HTTP->AQUIRE_LOGIN_DETAILS).

Suggest throwing an exception if the repo is password protected and no login set in login manager, or username and password wrong. Then the GUI can ask user for login details. There might be some downsides to performance, if data is to be calculated/refreshed

### 2FA
Currently only Github 2FA is supported, this anyhow ends up creating a token via api.github.com which is used for the git authentication. Also throw exception, and let the UI create the token using popus
ZCL_ABAPGIT_HTTP->AQUIRE_LOGIN_DETAILS
ZCL_ABAPGIT_2FA_*

### Proxy
abapGit is configured to use proxy or not, throw exception if proxy user and pw is not set.
See ZCL_ABAPGIT_PROXY_AUTH

## Generic
Decide if the login manager is the right approach for supplying username and passwords, a lot of the online functionallity require these, so if moving it to signatures there will be many changes. If using the login manager, extend it to handle proxy username and pws + 2fa tokens?

**Comment by marcellourbani** [comment]
I think tokens are the way to go, is what most applications use for similar scenarios.
We probably need to store them encrypted with some repo independent secret though, at least optionally.

Would like to enable that for the main UI too

**Comment by larshp** [comment]
hmm, storing the values is dangerous, if its not single user systems. If its single user systems I sometimes just paste the secret as ABAP into the authentication exit

**Comment by marcellourbani** [comment]
I didn't realise there was an authentication exit!
Good point about

**Comment by larshp** [comment]
duplicate, moving to https://github.com/larshp/abapGit/issues/783
