### ISSUE TITLE
GUI seperation: transport popup

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1333]
The transport popup is called from the backend API
![image](https://user-images.githubusercontent.com/5888506/39462466-23965e9e-4d12-11e8-863b-4b063e6e7896.png)
Instead it should be called by the GUI, and the transport be part of the API signature somehow.

**Comment by larshp** [comment]
Hi,
I finally took some time to start writing a bit about the current API, see https://docs.abapgit.org/other-api.html under "Pulling".

The idea started a while ago is that the GUI/client must call lo_repo->deserialize_checks which returns a structure with stuff where the user must decide what should happen.

We can use the same approach for this refactoring. Add another structure inside the `checks`, with 2 fields, eg.
```abap
IF ls_checks-transport-required = 'Y'.
* Ask user for transport and put in 
  ls_checks-transport-transport = 'SOMETHING'.
ENDIF.
```

then the ls_checks are passed to `deserialize`, which again ensures that everything is filled as expected

**Comment by christianguenter2** [comment]
Sounds like a good strategy. I adjusted my refactorings accordingly.

**Comment by larshp** [comment]
https://github.com/larshp/abapGit/pull/1340 merged
