### ISSUE TITLE
global settings, HTML rendering

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1345]
Looks like some of the HTML is broken, there is a gap corresponding to the button size,

![image](https://user-images.githubusercontent.com/5888506/39697608-c0532b2a-51f1-11e8-9ccb-217f31f2d442.png)

**Comment by christianguenter2** [comment]
This was done by purpose. :-) Feel free to change.
https://github.com/larshp/abapGit/blob/9ba92f319b3b9af8bac350a3857632ab829a0ab1/src/zabapgit_css_common.w3mi.data.css#L351-L353

**Comment by larshp** [comment]
ok, closing
