### ISSUE TITLE
gui: "show changes only" shows all files

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1355]
the feature "show changes only" shows all files in case there are no changed files, I guess it should display an empty list instead?

**Comment by christianguenter2** [comment]
https://github.com/larshp/abapGit/blob/59c1f277ab623f18808f1c1f4d852ef6a439baea/src/zcl_abapgit_repo_content_list.clas.abap#L195-L197

**Comment by larshp** [comment]
yes, looks good to me
