### ISSUE TITLE
Syntax error in NW 7.30 SP18

### ISSUE THREAD

**Issue by testitorleaveit** [larshp/abapGit#1358]
https://github.com/larshp/abapGit/blob/046b6fddefb7f3a4960d41b9cbb6850e68ba0025/src/objects/zcl_abapgit_object_ecatt_super.clas.abap#L248

Parameter not available in 7.30 SP18 system.

**Comment by christianguenter2** [comment]
can you comment out the parameter and check whether there are further syntax errors?

**Comment by testitorleaveit** [comment]
https://github.com/larshp/abapGit/blob/046b6fddefb7f3a4960d41b9cbb6850e68ba0025/src/objects/zcl_abapgit_object_devc.clas.abap#L92

	Formal parameter "I_SUPPRESS_DIALOG" does not exist. exist.		

https://github.com/larshp/abapGit/blob/046b6fddefb7f3a4960d41b9cbb6850e68ba0025/src/objects/zcl_abapgit_object_devc.clas.abap#L190

	Exception "DELETION_NOT_ALLOWED" does not exist		

https://github.com/larshp/abapGit/blob/046b6fddefb7f3a4960d41b9cbb6850e68ba0025/src/objects/zcl_abapgit_object_devc.clas.abap#L301

	Exception "WRONG_MAINPACK_VALUE" does not exist		

https://github.com/larshp/abapGit/blob/046b6fddefb7f3a4960d41b9cbb6850e68ba0025/src/objects/zcl_abapgit_object_devc.clas.abap#L302

	Exception "SUPERPACKAGE_INVALID" does not exist		

https://github.com/larshp/abapGit/blob/046b6fddefb7f3a4960d41b9cbb6850e68ba0025/src/objects/zcl_abapgit_object_devc.clas.abap#L339

	Exception "INVALID_TRANSLATION_DEPTH" does not exist		

https://github.com/larshp/abapGit/blob/046b6fddefb7f3a4960d41b9cbb6850e68ba0025/src/objects/zcl_abapgit_object_devc.clas.abap#L340

	Exception "WRONG_MAINPACK_VALUE" does not exist		

https://github.com/larshp/abapGit/blob/046b6fddefb7f3a4960d41b9cbb6850e68ba0025/src/objects/zcl_abapgit_object_devc.clas.abap#L341

	Exception "SUPERPACKAGE_INVALID" does not exist		

https://github.com/larshp/abapGit/blob/046b6fddefb7f3a4960d41b9cbb6850e68ba0025/src/objects/zcl_abapgit_object_devc.clas.abap#L473
https://github.com/larshp/abapGit/blob/046b6fddefb7f3a4960d41b9cbb6850e68ba0025/src/objects/zcl_abapgit_object_devc.clas.abap#L489

	The data object "LS_PACKAGE_DATA" does not have a component called		
	"TRANSLATION_DEPTH_TEXT".		

https://github.com/larshp/abapGit/blob/046b6fddefb7f3a4960d41b9cbb6850e68ba0025/src/objects/ecatt/zcl_abapgit_ecatt_val_obj_upl.clas.abap#L245
	Field "I_USE_CTS_API_2" is unknown. It is not one of the specified		
	tables and is not defined by a "DATA" statement. "DATA" statement.		

... there might be more, but I am running out of time

**Comment by christianguenter2** [comment]
hm, most of the code is used since some time. And used to run at least on 7.31 SP05 afaik. Which is your exact netweaver version?

**Comment by testitorleaveit** [comment]
7.30 SP18, updated my first comment with the exact versiuon number.

**Comment by larshp** [comment]
@testitorleaveit try again, latest version

**Comment by testitorleaveit** [comment]
The errors I listed above are gone. Here is another one. After that only warnings.

https://github.com/larshp/abapGit/blob/87f1d913fbd3b2ee4401573fce83a128092fe747/src/objects/ecatt/zcl_abapgit_ecatt_sp_upload.clas.abap#L108
	Field "I_USE_CTS_API_2" is unknown. It is not one of the specified		
	tables and is not defined by a "DATA" statement. "DATA" statement.

**Comment by larshp** [comment]
another fix by @christianguenter2 merged, @testitorleaveit try again

**Comment by testitorleaveit** [comment]
The syntax errors are gone, but now the runtime fails with `Function module PB_POPUP_PACKAGE_CREATE does not exist`.
Reproduction:
Press `+Offline`
Enter `name` and `package`
Press `Create Package`

**Comment by testitorleaveit** [comment]
When I create the package by hand, I get a little further until I hit issue #1273. So I suggest to close this issue here. I created the issue #1365 to follow up on the `Function module PB_POPUP_PACKAGE_CREATE does not exist`.

**Comment by larshp** [comment]
thanks
