### ISSUE TITLE
Push declined due to email privacy restrictions

### ISSUE THREAD

**Issue by rayatus** [larshp/abapGit#1363]
When performing a commit no error is shown if wrong email is used and "GitHub email privacy restrictions" are applied.
A fix must be done in ZCL_ABAPGIT_TRANSPORT=>RECEIVE_PACK in order to at least show some message

![image](https://user-images.githubusercontent.com/12736990/39776645-b8066746-5301-11e8-9b17-571ed3b6403e.png)

**Comment by larshp** [comment]
More info:
https://blog.github.com/2017-04-11-private-emails-now-more-private/
https://stackoverflow.com/questions/43378060/meaning-of-the-github-message-push-declined-due-to-email-privacy-restrictions

**Comment by larshp** [comment]
added a quick and dirty error message, see https://github.com/larshp/abapGit/pull/1369

**Comment by larshp** [comment]
@rayatus try again, latest version

**Comment by larshp** [comment]
closing

**Comment by sebbes333** [comment]
The documentation page:
https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address
