### ISSUE TITLE
Function module PB_POPUP_PACKAGE_CREATE does not exist (7.30 SP18)

### ISSUE THREAD

**Issue by testitorleaveit** [larshp/abapGit#1365]
The runtime fails with `Function module PB_POPUP_PACKAGE_CREATE does not exist`.

Reproduction:
- Press +Offline
- Enter name and package
- Press Create Package

Release: 7.30 SP18

**Comment by christianguenter2** [comment]
What makes we wonder is that just before the function module is called there's a check whether that function actually exists. Can you set a breakpoint there and check what function FUNCTION_EXISTS returns?

https://github.com/larshp/abapGit/blob/f72682aa8a82751b5206ff2e55f3bd0cad0d778b/src/ui/zcl_abapgit_popups.clas.abap#L877-L900

**Comment by testitorleaveit** [comment]
Well, it does behave like the code says, but what does that help me. I worked around the problem by creating the package before I started the reproduction above. This helped around this issue here - and led to another which is in another issue. Maybe the solution here would be not to show only an error, but give a hint how to work around the missing function module e.g. by creating the package before using abapGit.

**Comment by larshp** [comment]
@christianguenter2 I guess `zcx_abapgit_exception=>raise( 'Function module PB_POPUP_PACKAGE_CREATE does not exist' ). ` is triggering the error

@testitorleaveit good idea

**Comment by christianguenter2** [comment]
Oh I see. I assumend that 'runtime fails' = shortdump

**Comment by larshp** [comment]
@testitorleaveit something like this https://github.com/larshp/abapGit/pull/1367/files ?

**Comment by larshp** [comment]
@testitorleaveit try again, latest version

**Comment by larshp** [comment]
closing
