### ISSUE TITLE
Downport issue: CL_OO_CLASS_SECTION_SOURCE - short dump on creation due to unknown parameter

### ISSUE THREAD

**Issue by testitorleaveit** [larshp/abapGit#1366]
The class CL_OO_CLASS_SECTION_SOURCE is used with parameters which are not present in 7.30 SP18.

In 7.30 SP18 the constructor has the parameters:
- SLSKEY
- EXPOSURE
- STATE

Abapgit uses also 
- source
- suppress_constrctr_generation

Found here: https://github.com/larshp/abapGit/blob/de40ef670295078dc37766293fdb7e811f83b099/src/objects/zcl_abapgit_oo_class_new.clas.abap#L237

**Comment by larshp** [comment]
hmm, perhaps the easiest solution is to fall back to the old approach for if SAP_BASIS < 740

**Comment by larshp** [comment]
guess this is fixed with https://github.com/larshp/abapGit/commit/00f94d3f2e47a64c30e6b2ccded3cc044b59be81

@testitorleaveit try again

**Comment by goot1** [comment]
Hi,
same issue on SAP_BASIS 702 SP 20 with version 1.74.0

**Comment by goot1** [comment]
Retest with version 1.77.0 works fine.

**Comment by larshp** [comment]
thanks, closing
