### ISSUE TITLE
Moving an object or subpackage out of project should be a deletion

### ISSUE THREAD

**Issue by pokrakam** [larshp/abapGit#1378]
If an object is moved to a package external to the top-level package, it should be deleted from the project. 
Currently it only raises  "Error: error, expected parent package, $TEST2" ($TEST2 is my new top level package I moved the object to).
To reproduce, move any object or sub package from a repo to somewhere else. 

It looks like zcl_abapgit_file_status and zcl_abapgit_folder_logic are the modification points. If top level folder ends up as initial, make it a deletion. Or catch the exception and treat it as deletion (need to spend more time with it). 
I could probably do it, but won't have time for the next two weeks. However would like to get opinions whether this is the way it should behave?

**Comment by larshp** [comment]
Hi Mike,
Can you try this: https://github.com/larshp/abapGit/pull/1388

**Comment by larshp** [comment]
closing
