### ISSUE TITLE
dump, branch overview, author regex: Authors name separate with comma (Lastname, Firstname)

### ISSUE THREAD

**Issue by JohannesKonings** [larshp/abapGit#1379]
branch overview will produce a short dump if the authors name is separated with a comme: Lastname, Firstname.

class ZCL_ABAPGIT_BRANCH_OVERVIEW mehtod parse_commits

![image](https://user-images.githubusercontent.com/14806640/39957522-a3afff1e-55f4-11e8-86ad-86482a852b7b.png)

a change of the regex from ^([\\\w\s\.@\-_1-9\(\) ]+) <(.*)> (\d{10})\s?.\d{4}$ to ^([\\\w\s\.\,@\-_1-9\(\) ]+) <(.*)> (\d{10})\s?.\d{4}$ will solve the problem

zif_abapgit_definitions=>gc_author_regex
![image](https://user-images.githubusercontent.com/14806640/39957533-d083a220-55f4-11e8-9f65-96030dcbd95e.png)

https://regex101.com/
![image](https://user-images.githubusercontent.com/14806640/39957550-19ec2c52-55f5-11e8-959d-81ceef44b1e4.png)

I can fix this issue this afternoon.

Are there any unit test for this part?

**Comment by JohannesKonings** [comment]
Can this issue be closed? It should be done by PR https://github.com/larshp/abapGit/pull/1386.
Or should this problem remain open to create unit tests for it?
The same for https://github.com/larshp/abapGit/issues/1381

**Comment by larshp** [comment]
just close it

**Comment by JohannesKonings** [comment]
Fixed with https://github.com/larshp/abapGit/pull/1386
