### ISSUE TITLE
Unsupported Object types

### ISSUE THREAD

**Issue by jani80k** [larshp/abapGit#138]
Hi,

maybe this is not an issue and I am just too new to this.

I just installed ABAPGIT on our NW 7.40 machine.

I linked one of my big workflow projects including lots of objects of different kinds as an offline project. When I try to export it I get the error message "Object type AUTH not supported, serialize". I suppose authorization objects are not supported because they are not ABAP code. Am I correct in assuming that Workflows and standard tasks are also not supported?

Is there any fix for that or do I need to restructure my project into sub-projects so that all ABAP code is in one sub-project and only this sub-project is linked to ABAPGIT.

Could you provide a list of objects which are allowed and serializeable by ABAPGIT? Maybe it already exists out there and I just missed it :/

Keep up the good work and thanks a lot!

Cheers,
Jani

**Comment by larshp** [comment]
hi, list of object types is located here:
https://github.com/larshp/abapGit/wiki/Supported-object-types
I've added "AUTH" to the list and opened an issue for the object type, https://github.com/larshp/abapGit/issues/139

Also no serialization for workflow objects have been implemented. If you have the time feel free to implement support for the objects you need and submit a pull request :smile: see examples in LCL_OBJECT_* classes

If you just need some of the objects exported, just comment out the error in ZABAPGIT(or make a copy of it) and have it ignore the non-supported object types.

**Comment by larshp** [comment]
AUTH support added, 
https://github.com/larshp/abapGit/commit/edce760c8c080a1ff9c72d75e9abfa1c1f985fa3

**Comment by jani80k** [comment]
Hi,

thanks for adding AUTH support. 

I was able to export my package now, but I had to comment out the following object types:
 'CMOD', 'DOCV', 'PDTS', 'PDWS', 'SRFC', 'SXCI'

One hint for PDWS, there is an existing functionality by SAP to export Workflows.
LSWDDF70 Form xml_export.

For PDTS, I don't know.

Unfortunately, I do not have time because of work and personal life constraints, even though I would love to participate in your great project. 

Thanks for everything!

**Comment by larshp** [comment]
hi, I've added the objects to the list, and created separate issues #151 #152 #153 #154 #155 #156 for each of the types, perhaps someday someone will implement support :smile: 

I'll close the issue, each object type can be tracked in the above issues. Feel free to create a new issue if you run into problems or have questions
