### ISSUE TITLE
dump, branch overview, author regex: Authors name with special character (Lastname F#rstname)

### ISSUE THREAD

**Issue by JohannesKonings** [larshp/abapGit#1381]
The branch overview from abapGit leads to a short dump because of this commit:
https://github.com/larshp/abapGit/commit/3bacb05837a4b13d87da7ec11491acf55e7c7511

![image](https://user-images.githubusercontent.com/14806640/39959453-0f548164-5612-11e8-8115-a8e6622e2628.png)

![image](https://user-images.githubusercontent.com/14806640/39959456-17c686bc-5612-11e8-836e-0b036d5ec8cb.png)

Should the # be included in the regex?

https://regex101.com/
![image](https://user-images.githubusercontent.com/14806640/39959462-3d9c9c64-5612-11e8-9a50-3e8a4bda847d.png)

**Comment by larshp** [comment]
yeah, can we add this fix is the open PR?

**Comment by JohannesKonings** [comment]
Can you edit this directly in the open PR or should I create a new commit?

**Comment by JohannesKonings** [comment]
I'll create a new PR for the issue https://github.com/larshp/abapGit/issues/1379, where I can do also this correction.

**Comment by JohannesKonings** [comment]
Works after fix:
![image](https://user-images.githubusercontent.com/14806640/39965646-5d6033ea-569d-11e8-9ffc-ee75baad51fa.png)

**Comment by JohannesKonings** [comment]
Fixed with https://github.com/larshp/abapGit/pull/1386
