### ISSUE TITLE
Automatic integration tests

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1385]
Hi All,
Suggest moving the dangerous unit tests to a separate repository, so they are not delivered to customer systems. If an abapGit developer wants to run the dangerous tests/integration tests he/she installs a separate repository(eg https://github.com/abapGit/Integration-Tests).

Assumptions for unit tests in main abapGit repo:
* No internet connectivity
* No changes to data in the system
* No access to git server

However, for automatic integration tests:
* Access to internet, not behind proxy
* Some specific SSL certificates installed
* abapGitServer installed on localhost
* Changes to system data allowed

Any thoughts? This should not replace unit testing, see https://github.com/larshp/abapGit/issues/838, which also could use an overhaul

**Comment by flaiker** [comment]
Seems like a good idea to me. Some thoughts that come to mind:
The integration test repo will "depend" on a specific version of abapGit itself. This might be difficult to keep in sync, i. e. if you would change something in abapGit that requires a change in the integration tests you need to do 2 separate PRs. Any idea how other projects with separate test suite repositories handle this?
The alternative I guess would be to get the integration tests in the main repo but isolate them in some way so they are not deployed to customer systems (even with the full installation). I cannot think of way to do that at the moment (submodules / subtrees come to mind but are not supported; can't whole packages be hidden from activation with business functions switches? Or add a list of hidden packages to abapGit.xml which will only be pulled if they are activated in some repository user configuration). Not sure if it's worth pursuing this direction, splitting thinks up might make it easier anyways, as the main repo is already quite big.
Note though that friendship doesn't cross repository borders (hah), but that should not be needed for integration tests.

**Comment by EduardoCopat** [comment]
I also think separating to other repository makes things complicated. 

I liked the idea of hidden packages. What if abapmerge could ignore some packages?

**Comment by gepparta** [comment]
I would not separate them.

So here are my suggestions:

When those integration tests are written in abapUnit,
one could use RISK LEVEL DANGEROUS to avoid execution in systems where this is not explicitly allowed.
If this is not enough one could use an user parameter which has to be explicitly set for running those "dangerous" tests and check this parameter in class_setup for its value. If not set correctly one could call cl_abap-unit_assert=>fail method to skip this test.

**Comment by larshp** [comment]
👍 https://github.com/abapGit/Integration-Tests deleted

**Comment by larshp** [comment]
closing
