### ISSUE TITLE
Unit tests: Dependency injection/lookup

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1390]
Hi All,
In order to write more and better unit tests we need a common approach for dependency injection and/or lookup.

Code like ZCL_ABAPGIT_TADIR would be a good place to start introducing injection for. There is already some code in ZCL_ABAPGIT_SAP_PACKAGE for injection, but I'm not sure this is the best approach.

Any thoughts? Note that PARTIALLY IMPLEMENTED is not supported on 702

**Comment by treisinger** [comment]
IMHO I think dependency lookup is the easier and more convenient way to go if everything is already in place. Otherwise I would say constructor injection.

**Comment by flaiker** [comment]
Is there a dependency graph? Might make the decision for one approach or another easier. I thought I saw some notes in a PR some time ago but cannot find it again.

**Comment by larshp** [comment]
dependency graph, describing the dependencies between classes? no, I dont think so

**Comment by EduardoCopat** [comment]
I often use a factory pattern to work-out dependencies in ABAP. A simple pseudo-code example below:

```abap
INTERFACE lif_employee.
	methods:
		pay.
ENDINTERFACE.

CLASS lcl_employee.
	INTERFACES: lif_employee.
ENDCLASS.

CLASS ltd_stub_employee.
	INTERFACES: lif_employee.
ENDCLASS.

CLASS lcl_employee_factory DEFINITION.
PUBLIC SECTION.
	CLASS-DATA:
		employee type lif_employee.
	CLASS-METHODS:
		make_employee
			returning value(return) type ref to lif_employee.
ENDCLASS.

CLASS lcl_employee_factory IMPLEMENTATION.
	METHOD make_employee.
		IF employee IS BOUD.
			return = employee.
		ELSE.
			return = new lcl_employee( ).
	ENDMETHOD.
ENDCLASS.
```

Then you can use this factory to use your test doubles

```abap
CLASS lcl_testing FOR TESTING.
....

METHOD test.
	lcl_employee_factory=>employee = new ltd_stub_employee( ).
	"etc...
ENDMETHOD.
ENDCLASS.
```

I can provide more comments if needed, but I think the example above suffices.

**Comment by gepparta** [comment]
I would definitely go for a dependency lookup,
like it is described in openSAP course Writing Testable Code for ABAP Week_5.

I'm using it now in our project with out known side effects. 
One big benefit of it would be, that you can set up also integration tests very easy without blowing up all constructors with unnecessarily parameter mapping.

here is the overview picture of it from openSAP:
![dependency lookup in abap](https://user-images.githubusercontent.com/3863263/40226807-fcfb21e2-5a8c-11e8-9b65-f936dcadda6f.png)

It is similar to what Eduardo has written above but has also _create private_ and _global friends_ attributes in class definition.
If we go for injection/lookup we will need to switch to instance methods in ZCL_ABAPGIT_TADIR
and we would need an interface for it.

Switching to interface should be easy using aliases and eclipse :-)

Note:
If we **don't** set cl_injector "_for testing_" we could use it not only to set up our test cases but also for switching implementations on the fly. This is a standard use case in java like described here: http://xunitpatterns.com/Dependency%20Lookup.html

**Comment by larshp** [comment]
So, for the TADIR class,

new interface ZIF_ABAPGIT_TADIR with the public methods for ZCL_ABAPGIT_TADIR

new class ZCL_ABAPGIT_FACTORY with method GET_TADIR which makes sure it is a singleton, plus it has a public static attribute where the mock/stub/fake can be injected

**Comment by larshp** [comment]
see pull request https://github.com/larshp/abapGit/pull/1484

To be tested: FRIENDS and abapmerge

**Comment by larshp** [comment]
added a short description in http://docs.abapgit.org/development/tests.html, pull requests welcome

closing
