### ISSUE TITLE
Package to zip: It's possible to export non existing packages

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1391]
Advanced > Package to zip

It is possible to export non existing packages.
![image](https://user-images.githubusercontent.com/17437789/39966252-d851836e-56a8-11e8-86f5-0bfa70297bec.png)

![image](https://user-images.githubusercontent.com/17437789/39966260-06f544c6-56a9-11e8-982d-c19db35ed937.png)

Shouldn't we show an error instead?

**Comment by larshp** [comment]
yup
