### ISSUE TITLE
Package to zip: Assertion failed

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1392]
Advanced > Package to zip

![image](https://user-images.githubusercontent.com/17437789/39966329-4ced3352-56aa-11e8-9e17-59febc8a9461.png)

![image](https://user-images.githubusercontent.com/17437789/39966327-483200cc-56aa-11e8-957e-f22de739ffc0.png)

Todo: validate folder logic

**Comment by larshp** [comment]
change to exception instead of ASSERT ?
