### ISSUE TITLE
Two R3TR objects for one actual object

### ISSUE THREAD

**Issue by VishnAndr** [larshp/abapGit#140]
Hello Lars,

How should we handle situation when there are two objects in R3TR for one actual object? For example, SFBF and SFB2 are for business function. Another pair is SFBS and SFB1 for business function set. I am ready to submit a pull request with implementation for these objects (SFBF, SFBS and also SFSW), but need a clarification about SFB1 and SFB2 from your side please.

Best regards,
Andrei

**Comment by larshp** [comment]
cool!

Tried creating business function via transaction SFW2, and it created objects SFBF and SFB2 at the same time, without letting the user know about the SFB2 object. Just gotta love all the special cases in a standard system :smile: 

I think we should try filtering out the second object types(SFB2 + SFB1), this can be done in class LCL_TADIR, method BUILD(line 9459). This should make it skip SFB2 + SFB1 everywhere in the GUI and serialization.

Do you think this will work out?

**Comment by VishnAndr** [comment]
Thanks, Lars.

Seems to work. Need some more time (and some additional objects ;) ) to test completely.
