### ISSUE TITLE
docs: contributing to abapGit

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1402]
Move the part with building/submitting a PR out of https://github.com/larshp/abapGit/blob/master/CONTRIBUTING.md#buildingcreating-a-pr and to docs.abapgit.org

Perhaps make a video with the steps

**Comment by JohannesKonings** [comment]
About like that?

![image](https://user-images.githubusercontent.com/14806640/40586191-2b35709c-61bf-11e8-9fdb-8776be0557c8.png)

With a link from the contributing guideline to docs.abapgit.org

**Comment by larshp** [comment]
There is already https://docs.abapgit.org/guide-contributing.html, which is quite limited

The part from the contribution guidelines can be used, but it is currently abapGit centered

**Comment by JohannesKonings** [comment]
I would prefer that.

**Comment by larshp** [comment]
yeah, its easier to find via docs.abapgit.org

**Comment by larshp** [comment]
I guess this can be closed, all development related information moved to http://docs.abapgit.org/development/
