### ISSUE TITLE
Background mode dump when serializing badi implementations

### ISSUE THREAD

**Issue by Steve192** [larshp/abapGit#1403]
ABAPGit dumps when trying to serialize badi implementations in background mode.
This is because SXO_IMPL_FOR_BADI_READ is used which is somehow trying to use gui elements:

"  Exception condition "CNTL_ERROR" triggered"

![image](https://user-images.githubusercontent.com/6454983/40099264-985cc3a2-58df-11e8-85d2-bb668953d39c.png)

**Comment by larshp** [comment]
Also see https://github.com/larshp/abapGit/issues/1086

What SAP version is the system?

**Comment by Steve192** [comment]
We are on 7.50

**Comment by Steve192** [comment]
... We weren't on the latest abapgit version. Sorry for the inconvenience
