### ISSUE TITLE
User Exit: consider ABAP object types

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#1405]
Hi all,

We have several use cases in which a predefined set of ABAP object types should be imported to ABAP system out of a GIT repository. Therefore it would be desireable to have an exit in place in which a to be defined list of abap object types can be considered.

Best regards,
Thomas

**Comment by ThomasPloski** [comment]
Thanks for your answer. 

I would prefer to have this option as a kind of system setting, so that the admin can populate this whitelist. In addition a user can spefify more this whitelist.

What do u mean?

**Comment by ThomasPloski** [comment]
I just add some more background around this feature request. 

The SAP Cloud Plattform is currently working on supporting ABAP environment for partners and customers. In this context, ABAPGit will be used to migrate existing customer or partner code out of an on premise system to this SAP Cloud Platform environment. Therefore not all existing ABAP object types will be supported due to several reasons (e.g. no SAPGui support). We would like to integrate all whitelisted ABAP object types as global settings.    

More information you can find here:
https://blogs.sap.com/2017/09/26/overview-of-abap-in-sap-cloud-platform/
https://blogs.sap.com/2017/10/02/abap-in-sap-cloud-platform-why/
https://blogs.sap.com/2017/09/26/abap-in-sap-cloud-platform-frequently-asked-questions/
https://blogs.sap.com/2017/10/04/abap-in-the-cloud-is-this-a-good-thing/

**Comment by larshp** [comment]
I guess the cloud version will have to be a subset of the objects in the "full" abapGit repository. As there is no SAPGui support, all the UI classes can be excluded. Similarly a subset of the serialization classes(in /src/objects/) can be installed in order to support only a subset of the objects

**Comment by ThomasPloski** [comment]
Lars, your recommendation would be to extract all ABAPGit classes of the corresponding ABAP object types  which are not supported by SAP Cloud Platform ABAP environment? e.g. class cl_ABAPGIT_OBJECT_FUGR to not support function modules?

**Comment by larshp** [comment]
yes, exclude the `cl_ABAPGIT_OBJECT_*` classes which are not to be used in ABAPinSAPCP.

One approach could be to build this as a feature in https://github.com/abapGit/online_installer (rough draft) and also have a option for it to exclude the UI related classes

**Comment by christianguenter2** [comment]
I'd like to revive the idea of an userexit to filter objects or object types. My scenario is that we have several packages with corrupted ICF services. They causes exceptions during serialization. The services are working and nobody knows what's wrong with them and so nobody want to touch them. But they prevent that we can serialize the whole package. Current workaround is to jump over the objects in debugger.

Blacklisting them in .abapgit.xml is also not an option, as it requires proper serialization. 
I'd suggest introducing an userexit here where we can filter the corrupted objects.

https://github.com/larshp/abapGit/blob/46579651170dcc55e04916e82c8ad09147bedb2b/src/zcl_abapgit_tadir.clas.abap#L251

Something like this.
```
    zcl_abapgit_exit=>get_instance( )->change_tadir(
      EXPORTING
        iv_package = iv_package
      CHANGING
        ct_tadir   = rt_tadir ).

```

What do you think?

**Comment by christianguenter2** [comment]
@ThomasPloski is the new exit of any use for you?

**Comment by jfilak** [comment]
@ThomasPloski  You need to install a modified abapGit. In this case, software vendors distributing Open Source projects often fork the open source projects internally, modify it and install it from the modified repository. In your case, you just need to do `git rm src/objects/zcl_abapgit_object{FUGR,...}* && git commit -m "remote unsupported objects" && git push`. It is possible to do it in a Jenkins job that would be triggered upon a new commit in abapGit upstream (original) repository.

@larshp In comparison to your oneline_installer, what about to introduce `exclude` options in `abapmerge`. Or do they need to install abapgit in the non-compiled form?

**Comment by larshp** [comment]
I assume non-compiled form, it makes it easier to contribute back in case of any errors are found

**Comment by larshp** [comment]
Also see https://github.com/larshp/abapGit/issues/960 how/if to fork depends on the release/maintenance approach

**Comment by jfilak** [comment]
IMHO, in production systems, you should never install Open Source projects from their master branch of their original repositories.

**Comment by larshp** [comment]
closing, just leave out the serializers which are not to be supported
