### ISSUE TITLE
Merge function to use ABAPGit in a defined namespace 

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#1406]
Hi all,
Currently ABAPGit can be used as Z objects in a ABAP system. Would it be possible to merge/extract the ABAPGit sources in a defined namespace like /blabla/CL_ABAPGIT...., so that it can be transported to other systems by SAP transportation management tools? 

Best regards,
Thomas

**Comment by EduardoCopat** [comment]
I think that's a good idea.

Maybe duplicate of #1178 ? There are some workarounds listed there.

**Comment by mnemotron** [comment]
Try out my tool for ABAP namespace refactoring: [ABAPSpace](https://github.com/SAPAssets/ABAPSpace)

**Comment by larshp** [comment]
Also take note of 
ZCL_ABAPGIT_PERSIST_MIGRATE->TABLE_CREATE and LOCK_CREATE which creates a DDIC object and enqueue object when ZABAPGIT starts the first time

**Comment by larshp** [comment]
think this is outside the scope of abapGit, can be solved with projects like https://github.com/SAPAssets/ABAPSpace
