### ISSUE TITLE
ZABAPGIT - ITAB_DUPLICATE_KEY  on NW AS ABAP 7.51 INNOVATION PKG

### ISSUE THREAD

**Issue by lucodealethea** [larshp/abapGit#1412]
New Pull from master/zabapgit.abap results in dump.

https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap 

14786	                                                                            
14787	    SORT lt_items. " Default key - type, name, pkg                          
14788	    DELETE ADJACENT DUPLICATES FROM lt_items.                               
>>>>>	    lt_items_idx = lt_items. " Self protection + UNIQUE records assertion   
14790	                                                                            
14791	    " Process new remote files (marked above with empty SHA1)               
14792	    LOOP AT lt_remote ASSIGNING <ls_remote> WHERE sha1 IS NOT INITIAL.      
14793	      APPEND INITIAL LINE TO rt_results ASSIGNING <ls_result>.              
14794	      <ls_result> = build_new_remote( iv_devclass = iv_devclass             
14795	                                      io_dot      = io_dot                  
14796	                                      is_remote   = <ls_remote>             
14797	                                      it_items    = lt_items_idx            
14798	                                      it_state    = lt_state_idx ).         
14799	    ENDLOOP.                                                                
14800	                                                                            
14801	    SORT rt_results BY                                                      
14802	      obj_type ASCENDING

**Comment by christianguenter2** [comment]
What do you mean with pull from master/zabapgit.abap? This is the copy and paste report. 
Can please give more information about the steps you did?

**Comment by lucodealethea** [comment]
Hi Chris

1. /se38 > F8 > ZABAPGIT > Did a PULL from repo that has overwritten $ABAPGIT package
2./se38 run > dumps  with 
Syntax error in program "ZCL_ABAPGIT_GUI_ROUTER========CP        ".  
3. Went back to https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap
and copied it back overwritting ZABAPGIT program
4. Run it and it dumped with  ITAB_DUPLICATE_KEY  ZABAPGIT

**Comment by christianguenter2** [comment]
There are sometimes problems when abapGit modifies itself.
Therefore I'd suggest to copy and paste the abapGit report to an other report e.g. ZABAPGIT_INSTALLER and put it into $TMP. Run the report and then install the abapGit repo into package $ABAPGIT.

**Comment by christianguenter2** [comment]
Hm, are there any objects in package $ABAPGIT? If yes clean up and try again. Can you also delete database table ZABAPGIT?

**Comment by lucodealethea** [comment]
Ok thx Chris, that solved the issue, everything back on track. Cheers
