### ISSUE TITLE
error when changing starting folder

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1425]
error 'unexpected folder structure'

see https://github.com/Microsoft/ABAP-SDK-for-Azure/issues/1

**Comment by larshp** [comment]
issue reproduced:
1: install https://github.com/larshp/DOMA
2: change starting folder to "/src/"

hmm, not sure how to fix this

**Comment by mbtools** [comment]
Since https://github.com/larshp/abapGit/pull/3529, changing the starting folder is recognized as a "Change of Package Assignment" with the corresponding warning message (i.e. files are identical but in different local and remote folders).
