### ISSUE TITLE
Feature request - folding in list of changed files

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#1429]
Some object types produce a very large list of files. Changing a single include in a function group makes it list everything inside. I have to scroll down two screens to find the "view diff" button.

![image](https://user-images.githubusercontent.com/5097067/40781736-4b97ce7c-64dd-11e8-9f89-185287513265.png)

I would like to be able to fold this list. It would also be nice if large lists were folded automatically.

**Comment by larshp** [comment]
Hi,
Try deselecting "Show files" in the following dropdown,
![image](https://user-images.githubusercontent.com/5888506/40884311-5cb2845a-6711-11e8-85f1-93b14a25386f.png)

**Comment by FreHu** [comment]
Thanks, this is good enough. What would be ideal is to combine the first two - "show files with changes only", so one could still see the list of filenames without being overwhelmed.

Could I take a look at implementing this if I ever get any spare time?

**Comment by larshp** [comment]
sure, pull requests welcome
