### ISSUE TITLE
Dump when viewing XSLT file diff

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#1431]
A dump occurs when I try to view the diff on an XSLT file. Reproducable using version 1.68.

Longtext of the dump:
[dump.txt](https://github.com/larshp/abapGit/files/2061453/dump.txt)

Files causing the issue (zipped, as github does not allow the extensions):
[xslt_files.zip](https://github.com/larshp/abapGit/files/2061468/xslt_files.zip)

Changes in the file can be viewed here:
[xslt_comparison.zip](https://github.com/larshp/abapGit/files/2062190/xslt_comparison.zip)

Additionally, the author of the file was shown as "unknown". Unfortunately, I don't have any more info on this as I have already commited the file to prevent a dump when viewing all diffs at once.

**Comment by christianguenter2** [comment]
I can reproduce the error. It occurs for closing xml tags.
![image](https://user-images.githubusercontent.com/17437789/40871713-143761c6-6641-11e8-9a69-253ba05ef8cb.png)

**Comment by larshp** [comment]
@FreHu try again, latest version

**Comment by FreHu** [comment]
Tested using the included files, the diff is now working. Thank you for the fix.
