### ISSUE TITLE
abapGit Version scheme is different from any other git client

### ISSUE THREAD

**Issue by IngoS11** [larshp/abapGit#1432]
Hi guys,
we are operating GitHub Enterprise @ SAP and we are using Hubble https://github.com/Autodesk/hubble for analysis purposes. One of the Hubble reports is showing the git client versions used https://autodesk.github.io/hubble/users-git-versions. Unfortunately abapGit gets logged with versions like: 

abapGit-v1.68.0-sap-1
abapGit-v1.66.0-sap-1
abapGit-v1.50.2`

whereas any other client uses a scheme where the version goes first and any additional information after that like:

2.13.6 (Apple Git-96)
2.13.5 (Apple Git-94)
2.13.1.windows.1
2.13.1.2143.gb1f2c4b
2.12.2.windows.2
2.12.2.windows.1
2.12.2 (Microsoft Windows NT 10.0.16299.0; Win

is there any way I can get you to consider having the version to go first and anything else after that because the text in front completely messes up the report?

We also logged an issue in the Hubble Project https://github.com/Autodesk/hubble/issues/160 

Best

Ingo

**Comment by larshp** [comment]
I think we can change it, no problem

Will something like "v1.68.0-abapGit" work? Or should it be "1.68.0-abapGit"?

https://github.com/larshp/abapGit/blob/be0b9d0df454cd67f9f7f68d202a0713bc7f1603/src/http/zcl_abapgit_http.clas.abap#L208

**Comment by larsxschneider** [comment]
Thanks @larshp and @IngoS11 ! However, I feel `git/1.68.0-abapGit` could be misleading. It would basically say you are using the original Git client code version 1.68.0 with a few abap fixes. That's how Git for Windows does the versioning. But you are not using the code of the original Git client. As far as I understand it, the abap Git client is a reimplementation like libgit2 or JGit. Please correct me if am wrong!

libgit2 and JGit use the following version schemes:
```
git/2.0 (libgit2 0.26.0)
git/2.0 (libgit2 0.27.0)
JGit/2.1.0-SNAPSHOT
JGit/3.7.0.201502260915-r
```

That means your versioning should look more like this:
```
abapGit/1.6.8
```
or
```
git/2.0 (abap 1.68.0)
```

**Comment by larshp** [comment]
correct, abapGit is a custom implementation of git

I think I had "abapGit/1.6.8" in some early implementations but changed it. Since some sites(like bitbucket.org) returns an error if it is not a known git client

**Comment by larsxschneider** [comment]
I see. Would `git/2.0 (abapGit 1.68.0)` be an option? I think that expresses that you are somewhat compatible with git 2.x and your implementation is abap 1.68.0.

**Comment by larshp** [comment]
`git/2.0 (abapGit 1.68.0)` looks good to me

@IngoS11 any thoughts?

**Comment by larsxschneider** [comment]
@pks-t @ethomson did I capture the intention of the libgit2 version string correctly? (see two messages 👆)

**Comment by ethomson** [comment]
Yeah, I encourage you to do exactly that (`git/2.0 (your version)`).  Some hosting providers pattern match and expect `git/\d` in order to ensure that you're a real Git client.

**Comment by IngoS11** [comment]
(git/2.0 (your version)) would perfectly work for me. That way we could keep the original Hubble git-versions report and build ourselves another report showing the various Flavors like (Windows, Apple, Linux, ABAP etc.) or something along that line.

**Comment by larshp** [comment]
closing, change merged
