### ISSUE TITLE
Cannot COMMIT due to 2FA error

### ISSUE THREAD

**Issue by hardyp** [larshp/abapGit#1443]
As discussed, when tyring to COMMIT changes to GitHub from abapGit an error message arises from one of the Z 2FA classes
This can be solved in a dirty way by hacking the Z class in question, The point is that the connection between SAP and GitHub is working, yet the Z class is returning a fatal error whilst trying to contact api.github.com
Cheersy Cheers
Paul

**Comment by larshp** [comment]
Hi,
I've changed the code so 2FA implementations are evaluated alphabetically

Implement the following class in your system under package $TMP and abapGit will ignore 2FA on github.com

Note that I still recommend fixing the SSL setup to api.github.com, this is just a temporary workaround, 2FA will save the world 😄 

```abap
CLASS zcl_abapgit_2fa_a DEFINITION
  PUBLIC
  INHERITING FROM zcl_abapgit_2fa_auth_base
  CREATE PUBLIC .

  PUBLIC SECTION.

    METHODS constructor
      IMPORTING
        !iv_override TYPE string OPTIONAL .

    METHODS zif_abapgit_2fa_authenticator~authenticate
        REDEFINITION .
    METHODS zif_abapgit_2fa_authenticator~delete_access_tokens
        REDEFINITION .
    METHODS zif_abapgit_2fa_authenticator~end
        REDEFINITION .
    METHODS zif_abapgit_2fa_authenticator~is_2fa_required
        REDEFINITION .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_ABAPGIT_2FA_A IMPLEMENTATION.


  METHOD constructor.

    DATA: lv_match TYPE string.

    IF iv_override IS SUPPLIED.
      lv_match = iv_override.
    ELSE.
      lv_match = '^https?://(www\.)?github.com.*$'.
    ENDIF.

    super->constructor( lv_match ).

  ENDMETHOD.


  METHOD zif_abapgit_2fa_authenticator~authenticate.
    RETURN.
  ENDMETHOD.


  METHOD zif_abapgit_2fa_authenticator~delete_access_tokens.
    RETURN.
  ENDMETHOD.


  METHOD zif_abapgit_2fa_authenticator~end.
    super->end( ).
  ENDMETHOD.


  METHOD zif_abapgit_2fa_authenticator~is_2fa_required.
    rv_required = abap_false.
  ENDMETHOD.
ENDCLASS.
```

**Comment by hardyp** [comment]
Yes that works fine!

I am still chasing my BASIS people to find out why my system cannot contact api.github.com

**Comment by larshp** [comment]
closing, proxy problem in customer landscape
