### ISSUE TITLE
Repair transport needed while Development/Correction created

### ISSUE THREAD

**Issue by jfilak** [larshp/abapGit#1446]
I need to pull changes to a class. When I click the Pull link, the popup with transport appears. If I select a transport without task (or task of unspecified category) a new task of "Development/Correction" is created (or the unspecified task is set to "Development/Correction"). However, in that system, I have to track changes in "Repair" tasks.

**Version**:
abapGit v1.66.0
SAP_BASIS 753

**Actual behavior**:
When I submit the task selection, I get the following error:
`No suitable task exists under request`

The same happens when I manually change the type of the created task which is "Development/Correction" to "Repair" and re-try pulling with the same transport.

**Expected behavior**:
- The task is created as Repair (not sure how can abapGit figure out what type to use).
- Or I can specify type of the created task.
- Or it is possible to use a task of the "Repair" type.

**Comment by christianguenter2** [comment]
In FM TRINT_OBJECTS_CHECK_AND_INSERT the task type is determined via FM TRINT_GET_REQUEST_TYPE. Maybe you can use this somehow. 
It seems if tadir-srcsystem <> sy-sysid then a repair is needed

**Comment by jfilak** [comment]
The method popup_transport_request knows no nothing about the objects abapGit is going to pull. Fortunately, we do not need to check every object. It should be enough to check DEVC. However, that means I need to add the DEVC to the parameters of the method popup_transport_request.

**Comment by christianguenter2** [comment]
Yes, I think it would be sufficient to check DEVC. Or you can add the request type as a parameter to POPUP_TRANSPORT_REQUEST? It's a matter of taste.
The logic to determine the request type for a package would be well suited in zcl_abapgit_sap_package.
