### ISSUE TITLE
Multi User problem

### ISSUE THREAD

**Issue by jenssp** [larshp/abapGit#1447]
Hi,

we tried to work with multiple user on the same Git repository.

- When the first developer clones the dev package to the git repository in ABAP Git everything works fine
- When the second developer clones the same package to the same git repository we get the error "package in use" 

Do you have any ideas how to support multi user development on the same objects in ABAP Git?

Best regards

**Comment by jfilak** [comment]
<trolling>
It is not going to work - it is just not technically possible. The git files are deserialized into objects and you cannot have multiple versions of object in your system.
You need private system for all users. 
You can put your development system into a docker image and let the developers run it as a container anywhere.

Have a look at:
https://github.com/filak-sap/sap-nw-abap-docker
or 
https://github.com/nzamani/sap-nw-abap-trial-docker

</trolling>

**Comment by larshp** [comment]
In the SAP kernel it is only possible to have one active version of a program/class at a time.

**Comment by jenssp** [comment]
It is not my intention to work with multiple user on one one object at a time. 

My developers work on different classes within one dev package at a time and i tried to organize this in one git repository.

**Comment by larshp** [comment]
okay, as code is global in SAP, one user installing the repository is enough.

Other users can find the code under the burger icon, and click the star icon to make it a favorite,
![image](https://user-images.githubusercontent.com/5888506/40920991-7c663e4c-680e-11e8-866e-c3580d445fd4.png)

**Comment by jfilak** [comment]
Yes, that's possible but they are going to commit/push to the same remote repository and branch which is sub-optimal and causes a lot of confusion, especially when you are git beginner.

**Comment by larshp** [comment]
you can also setup abapGit to push automatically without developer involvement, see https://blogs.sap.com/2017/05/07/abap-using-git-for-safety-and-transparency/

but it depends on you use-case/scenario
