### ISSUE TITLE
tutorial: plugins

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1449]
Hi,
I'm considering removing the "install abapGit Plugins" from the tutorial, in the future I suggest everything to be supported from the main repo.

Any thoughts?

Also see https://github.com/larshp/abapGit/pull/823

**Comment by jfilak** [comment]
Good idea! However, there are plenty of objects we version by abapGit-plugins - IWPR, AOBJ, ...

**Comment by jfilak** [comment]
Yep. Will do ASAP.

**Comment by jfilak** [comment]
Here is the list. I will create the issues later on.

```
 AOBJ                                                                                                                                                                     
 ASFC                                                                                                                                                                     
 ASIS                                                                                                                                                                     
 AVAS                                                                                                                                                                     
 IWMO                                                                                                                                                                     
 IWPR                                                                                                                                                                     
 IWSV                                                                                                                                                                     
 IWVB                                                                                                                                                                     
 OCAO                                                                                                                                                                     
 SAJC                                                                                                                                                                     
 SAJT                                                                                                                                                                     
 SUSH
```

**Comment by abapkochbuch** [comment]
CHDO Change Documents

**Comment by larshp** [comment]
AOBJ                                                                                                                                                         
ASFC                                                                                                                                                           
ASIS                                                                                                                                                     
AVAS                                                                                                                                                 
IWMO
IWPR                                                                                                                                                                     
IWSV                                                                                                                                                                     
IWVB                                                                                                                                                                     
OCAO                                                                                                                                                                     
SAJC                                                                                                                                                                     
SAJT                                                                                                                                                                     
SUSH
CHDO

**Comment by larshp** [comment]
@jfilak do you still use the plugins? I'd like to delete the bridge code
