### ISSUE TITLE
Cannot create branch after switching remote

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1464]
I forked the [ABAP-SDK-for-AZURE](https://github.com/Microsoft/ABAP-SDK-for-Azure) to [my-fork](https://github.com/christianguenter2/ABAP-SDK-for-Azure.git).
I initially cloned the original repo into abapGit then changed the remote to my fork.

Now I can't create a new branch in abapGit. I get the error: New branch, "from" SHA1 empty.

![image](https://user-images.githubusercontent.com/17437789/41047240-665ba656-69ac-11e8-99c6-fcf94aa82c16.png)

![image](https://user-images.githubusercontent.com/17437789/41047215-5442c8be-69ac-11e8-9738-636444ddd205.png)

![image](https://user-images.githubusercontent.com/17437789/41047245-6939fc24-69ac-11e8-8405-1b6538934656.png)

![image](https://user-images.githubusercontent.com/17437789/41047292-8bea09e4-69ac-11e8-81d2-67ce57eeec57.png)

The local SHA1 is empty.
![image](https://user-images.githubusercontent.com/17437789/41047438-e1ee0796-69ac-11e8-82ec-269cc5d3ca19.png)

Uninstalling the repo and installing the fork directly works as a workaround.

**Comment by christianguenter2** [comment]
SHA1 is set here. Maybe we should set it to get_sha1_remote( )?
https://github.com/larshp/abapGit/blob/e738322783317534afac5269fe59cdaf116ec216/src/zcl_abapgit_repo_online.clas.abap#L449-L452

**Comment by larshp** [comment]
does it work? is it the correct sha1?

In the PR I guess it sets the SHA1 of the old remote?

**Comment by christianguenter2** [comment]
Your right, it's the SHA1 of the old remote. In my scenario this works accidentally, but I think there are other cases where this isn't a good solution. I updated the PR so the SHA1 is updated after the new url is set.

**Comment by larshp** [comment]
we should look into if the remote sha1 is actually needed, I guess it can be removed altogether

**Comment by larshp** [comment]
remote sha1: https://github.com/larshp/abapGit/issues/1485
