### ISSUE TITLE
DDLS: not added to transport

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1466]
DDLS: not added to transport during deserialization

@jfilak

**Comment by christianguenter2** [comment]
Just tested this and DDLS is added to transport.
![image](https://user-images.githubusercontent.com/17437789/41091526-0814c4d8-6a47-11e8-825c-29d69abf66f8.png)

**Comment by jfilak** [comment]
Interesting, not in our systems :)

**Comment by jfilak** [comment]
:D experimental features strike back again:
```abap
    IF use_new_activation_logic( ) = abap_true.
      activate_new( iv_ddic ).
    ELSE.
      activate_old( iv_ddic ).
    ENDIF.
```

**Comment by christianguenter2** [comment]
Well, at least we know that the new activation logic isn't that good :-)

**Comment by jfilak** [comment]
Therefore, I propose to fix the method ZCL_ABAPGIT_OBJECTS_ACTIVATION~activate_ddic where we need to make sure the activated object is locked in a transport.
Do you agree? 
Or should I added the transport check-in in the deserialization of DDLS?

**Comment by christianguenter2** [comment]
I'd suggest to add it in ACTIVATE_DDIC. I guess there are other objects with the same issue.

**Comment by jfilak** [comment]
```abap
    LOOP AT gt_objects ASSIGNING <ls_object>.

      ls_gentab-name = <ls_object>-obj_name.
      ls_gentab-type = <ls_object>-object.
      INSERT ls_gentab INTO TABLE lt_gentab.

      APPEND value #( pgmid = 'R3TR' object = <ls_object>-object obj_name = <ls_object>-obj_name ) TO lt_obj_entries.
    ENDLOOP.

    " INCLUDE LCTS_WBO_API_IMPLF06 FORM call_objects_check_and_insert
    CALL FUNCTION 'TRINT_OBJECTS_CHECK_AND_INSERT'
      EXPORTING
        iv_with_dialog = space
        it_obj_entries = lt_obj_entries
      EXCEPTIONS
        OTHERS = 1.
```

The function TRINT_OBJECTS_CHECK_AND_INSERT finishes correctly but the objects do no appear in the transport :(

**Comment by christianguenter2** [comment]
try

```
    CALL FUNCTION 'TRINT_OBJECTS_CHECK_AND_INSERT'
      EXPORTING
        iv_with_dialog    = abap_true
        it_obj_entries    = lt_obj_entries
      EXCEPTIONS
        OTHERS            = 1.

```

**Comment by jfilak** [comment]
Thanks! Please, have a look at #1468.
