### ISSUE TITLE
Proxy Authentication - 

### ISSUE THREAD

**Issue by MichiFr** [larshp/abapGit#1467]
Hi,

in our company landscape it is necessary to use a proxy to access the internet, with authentication. When providing thoses information within the settings, I get a error when the report tries to display the popup asking for user credentials. The error is similar to : CALL SCREEN( not modal)... Sorry for not providing the full message text, because it is in German language.

This happens in method lcl_password_dialog->popup() when CALL SELECTION-SCREEN ... gets executed.

I should have mentioned that this happens, when I try to clone a repository and choose the button to select a specific branch.

Any chance for a quick fix?
Michael

**Comment by larshp** [comment]
also see https://github.com/larshp/abapGit/issues/658 and https://github.com/larshp/abapGit/issues/1010

Workaround is to create the online repository, and then use "Branch" -> "Change" to switch branches.

**Comment by MichiFr** [comment]
Maybe you schould show the proxy authentication popup right after saving the settings, presumbly the appropriate checkbox is active?

This way you can avoid poping the window up in background.

**Comment by larshp** [comment]
There is a refactoring task open for the password popups, https://github.com/larshp/abapGit/issues/1331

**Comment by larshp** [comment]
duplicate issue and workaround, closing
