### ISSUE TITLE
current login language does not match master language

### ISSUE THREAD

**Issue by ffischer1984** [larshp/abapGit#1478]
Hi,
I want to clone abapOpenChecks and get this message:"current login lannguage does not match master language". I don't think it's an repo-issue because this repo should be opensource and so a login should not be neccessary.

**Comment by christianguenter2** [comment]
The repo language is english. The message means that you logged on with another language in SAPGUI. You have to switch to EN if you want to install it.

**Comment by larshp** [comment]
@ffischer1984 did above help? can we close the issue?

**Comment by larshp** [comment]
closing
