### ISSUE TITLE
Poor performance and missing icons when client has no internet access

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1479]
We have a scenario where client which runs SAPGUI and abapGit has no internet access. Therefore the external libraries mentioned [here](http://docs.abapgit.org/other-external-libraries.html) cannot be loaded. 

Every action in the ui causes rendering times between one and two minutes. This is mainly caused by the load of octicons here.
https://github.com/larshp/abapGit/blob/803148fa0fafc321c4fcba1cbe13a9d1ae5a3851/src/ui/zcl_abapgit_gui_asset_manager.clas.abap#L268-L271

As they cannot be loaded there are some things missing in the ui, e.g. the burger menus.
![image](https://user-images.githubusercontent.com/17437789/41190671-d0687248-6be3-11e8-80df-f75e0353d02b.png)

Besides that there are no further limitations at first sight. Maybe we can cut the dependency to cdnjs and supply octicons via mime repo as we already do for common.css and commons.js?

Btw. is there still a dependency to jQuery as documentation says? Couldn't find one.

**Comment by christianguenter2** [comment]
Maybe I'm missing the obvious but any idee where I can get the colored svgs?

**Comment by larshp** [comment]
Suggest first making an overview of which icons we need/use. Then we need to consider licensing if we copy something into the code, alternatively design new SVGs from scratch.

**Comment by sbcgua** [comment]
Hi All :) It has been some time ... :)  
Octicons are loaded as a font, so just monocolor (color controlled by CSS however). The licence seems to be [MIT](https://github.com/primer/octicons#license). Technically possible to use just needed icons but that would increase effort for new pages/designs - it is more convenient to get the whole package at once. Originally I had an idea to cache them dynamically as a MIME object (with asset manager) but then didn't get my hands on it. Also that would introduce versioning issues.

P.S. sadly I'm a bit further from ABAP at the moment. so don't have enough time to participate ... just following the news :)

**Comment by larshp** [comment]
Currently the following icons are used from Octicons:

- alert
- arrow-up (abapGit news/changelog)
- check
- cloud-upload (online project)
- dir
- file
- file-binary
- file-code
- file-directory
- git-branch
- lock
- package
- plug (offline project)
- settings
- star
- three-bars (burger icon)

Suggest drawing interpretations of these in custom SVG(use inkscape?) so that the icons can be used without extra copyright notices, and reused in ADT_Frontend

**Comment by larshp** [comment]
Started some stuff here: https://github.com/abapGit/icons/tree/master/src but I'm so bad 😄

**Comment by sbcgua** [comment]
let's discuss it a bit. Why not to use existing library and just add it to mime ?
Drawing own icon would be an ordeal:
- first to draw something nice (not easy at all) ... e.g. in inkscape
- then convert to font (IE does not support SVG well, I tried, this was my first failed approach with icons). Convert to font itself maybe not that difficult. But it should be a flow. So icons should be stored somewhere (another repo?) and then somehow integrate into AG (preferably automatically)
- if new icon is need it should be drawn ... so more difficult UI experiments

This all can be solved of course. But the alternative is to use existing well-looking MIT or CC licensed set and honor it in readme and/or in a comment somewhere in code.

P.S. Own icons might not solve all issues with java - seems like it's browser doesn't understand font. At least from what I remember from my experiments on macos.

**Comment by larshp** [comment]
existing: yeah, we can do that

would just like to take the chance to optimize, typically the existing fonts contains a lot more than whats needed in abapGit
