### ISSUE TITLE
table_add and table_read accept only STANDARD TABLE

### ISSUE THREAD

**Issue by VishnAndr** [larshp/abapGit#148]
Hello Lars,

Implementing switches and business functions/business function sets objects I found an issue with table_add and table_read methods in lcl_xml class. They accept only standard table. If we add a structure to xml with nested table as sorted one for instance, there will be a dump. Faced it with structure SFW_BFBS_OUTTAB_LINE component CELLTAB. I changed it locally in a way that it_table/ct_table is an index table. And in table_read method instead of 
APPEND INITIAL LINE TO ct_table ASSIGNING <lg_line>.
used:
```
DATA: lrs_line TYPE REF TO data.
CREATE DATA lrs_line LIKE LINE OF ct_table.
ASSIGN lrs_line->* TO <lg_line>.
CASE lv_kind.
.....
ENDCASE.
INSERT <lg_line> INTO TABLE ct_table.
```

What do you think? Should it be changed to ANY TABLE or INDEX TABLE is enough?

**Comment by larshp** [comment]
Yeah, I also ran into that problem once, used a workaround instead of a real fix, I'm lazy :smile: 

I think we should change the method signature to ANY TABLE and add above code. Not sure if it will work with everything, but we will find out in the future, perhaps add some unit tests.

**Comment by larshp** [comment]
this should be fixed now with next-gen-xml
