### ISSUE TITLE
DDLS: dump

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1488]
in following code it tries to clear fields ACTFLAG and CHGFLAG, however these fields do not exist in all system releases,

```abap
    APPEND 'AS4USER' TO lt_clr_comps.
    APPEND 'AS4DATE' TO lt_clr_comps.
    APPEND 'AS4TIME' TO lt_clr_comps.
    APPEND 'ACTFLAG' TO lt_clr_comps.
    APPEND 'CHGFLAG' TO lt_clr_comps.

    LOOP AT lt_clr_comps ASSIGNING <lv_comp>.
      ASSIGN COMPONENT <lv_comp> OF STRUCTURE <lg_data> TO <lg_field>.
      ASSERT sy-subrc = 0.
      CLEAR <lg_field>.
    ENDLOOP.
```

![image](https://user-images.githubusercontent.com/5888506/41222019-2b75494e-6d66-11e8-8a33-d3eedb60a203.png)

**Comment by jfilak** [comment]
So, just change `assert` to `check`?

**Comment by larshp** [comment]
there is always another bug, this one is especially difficult because we do not have all the details on all SAP releases

I've opened a PR, feel free to review
