### ISSUE TITLE
"2FA error: Communication error: SSL-Client SSL-Client (Anonym)" occures at git-commit

### ISSUE THREAD

**Issue by ffischer1984** [larshp/abapGit#1491]
Hi 
i get this error: "2FA error: Communication error: SSL-Client SSL-Client (Anonym)" by creating a git-commit. Abap-git asks me about username/password so I'm a little bit astonished that I get an SSL-Error.
My password is 99% correct because i use a password-manager so what I'm doing wrong?

Any ideas what i'm doing wrong will be appreciated.
Thanks for the help.

**Comment by larshp** [comment]
try running the program described in: https://docs.abapgit.org/other-test-ssl.html and paste output here

you might need to import additional certificates for https://api.github.com

**Comment by ffischer1984** [comment]
Cloning a repo is sucessfully I just can't commit something (I created my own repo with an readme.md file)
Here is the result from ssl test for git:
"11.06.2018                                                                                                                    ssl test für git                                                                                                                           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
https://github.com : ok

----

Error Number     1

ICM_HTTP_SSL_PEER_CERT_UNTRUSTED
Also check transaction SMICM -> Goto -> Trace File -> Display End"

**Comment by ffischer1984** [comment]
the api.github.com certificate solved the problem

**Comment by hardyp** [comment]
I have the same issue. What does your STRUST screen look like after you added the api.github.com certificate?

**Comment by ffischer1984** [comment]
i've three certificates:

- digicert / github
- github.com
- api.github.com

https://www.dropbox.com/s/oder81vnwhfw7sz/strust2.PNG?dl=0

**Comment by hardyp** [comment]
Thanks for that. I have all three as well but the SSL test program still faisl. Therefore the problem is on my side, and I will keep pressing my BASIS people.

**Comment by ffischer1984** [comment]
Have you set the ssl parameters in rz10?

Paul Hardy <notifications@github.com> schrieb am Mi., 13. Juni 2018, 08:01:

**Comment by hardyp** [comment]
Yes that works fine. On the SSL test program the first URL works OK i.e. I can "pull" from GitHub to SAP.
I just get the error on the SSL test program when trying to connect to |api.github/.com| which you need to do to do a "commit" when it checks the 2FA.
I think the problem is something to do with a proxy setting on my side.

**Comment by ffischer1984** [comment]
Hmn have you restarted your sap-instance after you have set the ssl params?

Paul Hardy <notifications@github.com> schrieb am Mi., 13. Juni 2018, 08:37:

**Comment by hardyp** [comment]
Oh yes, they were set a few weeks back. Before they were set I could not pull anything from GitHub and the SSL program failed on both URLs.

On the error message it says
Certificate : api.github.com etc etc
Issuer : some sort of proxy from my company

Hence I suspect the problem is with the latter. It is possible the SAP system does not trust one of our own proxies, If so maybe I need to get the certificate from the proxy and install that into STRUST as well.

**Comment by hf-kklein** [comment]
Checking out public repositories from GitHub worked just fine but when I tried to clone a private repository I got the error message:
> 2FA error: Communication error: SSL-Client SSL-Client (Anonym)

after entering the Github credentials.

Installing the certificates for **api**.github.com as described above solved it.
> you might need to import additional certificates for https://api.github.com

**Comment by flaiker** [comment]
> egin : Sun Jul 7 19:00:00 2019 (190708000000Z)
> nd : Thu Jul 16 07:00:00 2020 (200716120000Z)
> urrent : Fri Apr 26 10:56:33 2019 (20190426155633Z)

@salamancacm77  Are you from the past?

**Comment by salamancacm77** [comment]
@flaiker I don't understand

**Comment by flaiker** [comment]
You seem to have forgotten to adjust your watch after travelling 4 months into the future.

> Peer certificate __not yet valid__:
> Validity not before: __Sun Jul 7 19:00:00 2019__ (190708000000Z)
> Validity not after: Thu Jul 16 07:00:00 2020 (200716120000Z)
> Begin : Sun Jul 7 19:00:00 2019 (190708000000Z)
> End : Thu Jul 16 07:00:00 2020 (200716120000Z)
> Current : __Fri Apr 26 10:56:33 2019__ (20190426155633Z)

**Comment by shanvelc** [comment]
do we need to import certificate from https://api.github.com/ in case if we are connecting enterprise GITLAB?

**Comment by larshp** [comment]
no
