### ISSUE TITLE
Log objects which are removed in user exit

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1493]
Follow up on #1405 
Theres'a new user exit to filter tadir entries. 

https://github.com/larshp/abapGit/blob/fbadb3537bc1bf85ed1efa854020bcfd1cacc47a/src/zcl_abapgit_tadir.clas.abap#L239-L258

It might be a good idea to log the ignored entries similar to the not supported objects. This would make the process more transparent to the user.

![image](https://user-images.githubusercontent.com/17437789/41314049-d7cd5210-6e8b-11e8-8cd9-efe5562c7722.png)

Two possible approaches:
1) Pass the log object to the user exit. So the user can log whatever he wants
2) Let abapGit calculate the delta and log the removed objects

**Comment by larshp** [comment]
1. pass the log object, and let the user decide
