### ISSUE TITLE
SSFO: Dump when smartforms is locked

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1494]
If a smartforms can't be enqueued during deserialization a dump occurs.

![image](https://user-images.githubusercontent.com/17437789/41351871-00fa7d20-6f18-11e8-9253-0241ab774577.png)
![image](https://user-images.githubusercontent.com/17437789/41351874-02234b1e-6f18-11e8-9f7f-a3762c99a80e.png)

Suggest to catch CX_SSF_FB.
https://github.com/larshp/abapGit/blob/f14ac831bacd969082ac4cf7451ff581949ca808/src/objects/zcl_abapgit_object_ssfo.clas.abap#L255-L269

**Comment by larshp** [comment]
also see https://github.com/larshp/abapGit/issues/437
