### ISSUE TITLE
package name /ZZZ/YYY with subpackage error

### ISSUE THREAD

**Issue by zlob2k** [larshp/abapGit#150]
Hello all, 
we use package name e.g. /ZZZ/YYY and after testing new offline project with such name we can't start AbapGit again. Our package has subpackage and AbapGit generates exception 'Unexpected package naming' here:
`
method BUILD
* look for subpackages

    SELECT * FROM tdevc INTO TABLE lt_tdevc
      WHERE parentcl = iv_package
      ORDER BY PRIMARY KEY.               "#EC CI_SUBRC "#EC CI_GENBUFF
    LOOP AT lt_tdevc ASSIGNING <ls_tdevc>.
      lv_len = strlen( iv_package ).
      IF <ls_tdevc>-devclass(lv_len) <> iv_package.
        _raise 'Unexpected package naming'.
      ENDIF.
`
Is it possible to use subpackages?
Somebody had the same? Help, please..

**Comment by larshp** [comment]
so the following are the steps to reproduce:
1: import offline project into package /ZZZ/YYY
2: restart abapGit, it shows error?

**Comment by larshp** [comment]
Hi, I've updated the code so abapGit will be able to start again and shows an information popup instead. Also added a small explanation in the code before issuing the MESSAGE.

**Comment by zlob2k** [comment]
>  if installing into package /ZZZ/YYY the subpackages should be named like /ZZZ/YYY_something

I suppose it is the answer...  Thanks a lot. We will test it

**Comment by zlob2k** [comment]
So thanks for your quick answer, Lars. After downloading new version, it starts.  It doesn't show subpackage because of naming inconsistency, of couse. But it starts

**Comment by larshp** [comment]
great :smile: depending on your setup you might want to rename the subpackage, if it is to be handled by abapGit. Otherwise you might just want to leave it as is

**Comment by zlob2k** [comment]
I removed all subpackage's progs to another package and just deleted subpackage for this time, because i couldn't rename subpackage.

**Comment by larshp** [comment]
thanks, I'll close the issue. Feel free to open a new issue if you run into more problems

**Comment by zlob2k** [comment]
Thanks
