### ISSUE TITLE
CDS: Not Getting locked in a TR and also not active

### ISSUE THREAD

**Issue by JerinJK** [larshp/abapGit#1500]
Hi  ,

We are currently using 1.68.2 version . While pulling CDS views , the views are not locked under a Transport .  Also it is not active in the system.

We need to manually activate the views .

Regards,
Jerin

**Comment by christianguenter2** [comment]
Maybe the same root cause as here #1466?

**Comment by filak-sap** [comment]
I am on it! Perhaps, we better switch off the experimental features.

**Comment by larshp** [comment]
experimental: I've not tested the parallel activation, but if you have been running it for a while lets just try 😄
