### ISSUE TITLE
Block commit/push if code inspection has erros

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1524]
I'd like to suggest a new feature. Sometimes we have the situation that we mistakenly break something (syntax error or failing unit tests) and don't realize it. In this scenario we want to block commit/push. 

The idea is that we do the checks with the code inspector like the 'Advanced -> Syntax Check' and if there are errors in the inspection show them and block the commit. 
To be flexible one should can maintain a check variant in the settings of the repo and enable the blocking if the check fails.

**Comment by larshp** [comment]
yeah

it is moving a bit outside the scope of a git client, but it is also important that the tools are integrated

**Comment by hardyp** [comment]
In my recent reading about GitHub and it's competitors it is often mentioned that when a "merge" is about to happen various automated checks are done e.g. run all the unit tests and if one fails reverse the merge. That way the code in the main branch is always production ready. This is a reality fo various other languages as I understand it, although they talk about unit tests rather than the code inspector type concept we have in ABAP.
So having both in abapGit brings the "continious integration" concept into the ABAP world.

**Comment by larshp** [comment]
except that this "continious integration" will be configured and run on the client, but it is the best we can do

**Comment by christianguenter2** [comment]
WIP
https://github.com/christianguenter2/abapGit/tree/issue_1524

1) new repo settings
![image](https://user-images.githubusercontent.com/17437789/41676906-26d1c59e-74c7-11e8-9de0-1dd818594a76.png)

2) run code inspector on demand
![image](https://user-images.githubusercontent.com/17437789/41676670-8b0bfd5a-74c6-11e8-87e0-55d5c233fbbc.png)

3) code Inspector page
![image](https://user-images.githubusercontent.com/17437789/41676700-9b87323a-74c6-11e8-81b3-d6cadd69ffa2.png)

4) code inspector runs before commit, if error occurs popup is shown
![image](https://user-images.githubusercontent.com/17437789/41676748-bb82617c-74c6-11e8-9931-943228fa4851.png)

5) show code inspector results
![image](https://user-images.githubusercontent.com/17437789/41676774-c8fb9616-74c6-11e8-83f5-4a0572833e38.png)

6) commit anyway, if block commit is set error occurs otherwise commit is possible
![image](https://user-images.githubusercontent.com/17437789/41676790-d4922c9c-74c6-11e8-8070-571478e46346.png)

**Comment by larshp** [comment]
a: suggest showing the errors before the commit page
b: I'm not sure if these settings should go into .abapgit.xml, or they should be local? Variants vary across systems

on another note I created https://github.com/larshp/upDOWNci/issues/12 a few days ago, not sure if/how to integrate with abapGit

**Comment by christianguenter2** [comment]
b: I'm not sure either. You can set the variat as transportable which results in a pseudo report include which can be added to the repo.

![image](https://user-images.githubusercontent.com/17437789/41677801-b00d394a-74c9-11e8-97ec-c7367946865d.png)

![image](https://user-images.githubusercontent.com/17437789/41677815-b6d18754-74c9-11e8-8cd0-4fa59fdc864b.png)

**Comment by larshp** [comment]
pseudo report include: yeah, its a mess IMHO, so I created the XML stuff, see https://blogs.sap.com/2015/08/02/upload-and-download-code-inspector-variants-via-xml/

**Comment by christianguenter2** [comment]
yeah agree, they are a real mess and code inspector shows a syntax error for them
![image](https://user-images.githubusercontent.com/17437789/41678354-27d22db8-74cb-11e8-8f95-30765503bf41.png)

I have to look into your stuff looks promising. Otherwise we put it in the local settings.

**Comment by christianguenter2** [comment]
a: before or after staging?

**Comment by larshp** [comment]
a: also before staging IMHO, fixing errors might change multiple files

**Comment by christianguenter2** [comment]
a: moved code inspector checks before staging. It's not possible to stage when there are errors and the setting to prevent commit is set. Re runs also possible.
![image](https://user-images.githubusercontent.com/17437789/41733215-7f495c20-7583-11e8-8fd3-79efb015921f.png)

![image](https://user-images.githubusercontent.com/17437789/41733219-81c2180c-7583-11e8-925e-d485a9b8f883.png)

**Comment by hardyp** [comment]
I would like to congratulate you on this. I feel this is a wonderful step forward.

**Comment by larshp** [comment]
@christianguenter2 there were a bug when merging branches?
