### ISSUE TITLE
Support for SPRX object types

### ISSUE THREAD

**Issue by Srinu3366** [larshp/abapGit#1525]
We use SAP PI for integration with ECC and use ABAP Proxies for this. Currently when trying to use ABAP Git, it is not supporting SPRX object types. Is it possible to add this object type to git?

 Object type ignored, not supported: SPRX-INTFZZCLII_SI_PURCHASEORDERPROCESS

![image](https://user-images.githubusercontent.com/25985494/41732558-f3bea85e-7546-11e8-9936-678c27afe7f2.png)

Thanks,
Srini

**Comment by christianguenter2** [comment]
Duplicate #87

**Comment by larshp** [comment]
duplicate, closing
