### ISSUE TITLE
DEVC: Delete empty packages

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1533]
Follow up on #927

Package deletion is not trivial as stated here:
https://github.com/larshp/abapGit/blob/307c1395d2f64ddb5b191363fc674afa94f71d8f/src/objects/zcl_abapgit_object_devc.clas.abap#L211-L218

I think it should at least be possible to delete empty packages.

**Comment by larshp** [comment]
guess this can be closed
