### ISSUE TITLE
FUGR locking error

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1535]
see https://github.com/abapkochbuch/Sources/issues/1

![image](https://user-images.githubusercontent.com/5888506/42033597-a6e3b76c-7add-11e8-8aab-979274944096.png)

**Comment by larshp** [comment]
yep, fixing

**Comment by larshp** [comment]
@bizhuka try again, latest version

**Comment by bizhuka** [comment]
checked in
![image](https://user-images.githubusercontent.com/36256417/42035000-9f3c2c62-7b03-11e8-86e4-98da466a47d6.png)
and
![image](https://user-images.githubusercontent.com/36256417/42035009-a9a842c6-7b03-11e8-86ef-5ccf2b1d47df.png)

everithing seems to be ok
thanks!
