### ISSUE TITLE
repository organization

### ISSUE THREAD

**Issue by abapkochbuch** [larshp/abapGit#1543]
The more I use this genious tool abapGit the more I get into problems because I don't find repositories anymore... ;)

![abapgit_overview](https://user-images.githubusercontent.com/40034905/42089372-17d181f6-7b9d-11e8-9a22-dcd0a8154dc1.png)

Are there any ideas of hoe to group or organize repositories?

Regards
Enno

**Comment by christianguenter2** [comment]
Same here ;-) One thing that helps me is to hover over the burger menu. There you have all repositories not only your favorities and it's easier to scan.
![image](https://user-images.githubusercontent.com/17437789/42091639-6d5e30fc-7ba6-11e8-9319-862cb4021ae5.png)

**Comment by christianguenter2** [comment]
And maybe reduce your favorites?

**Comment by christianguenter2** [comment]
The SAP user who created the repo would also be helpful. Maybe we can start with a list like the database util ('Advanced' -> 'Database Util')?

![image](https://user-images.githubusercontent.com/17437789/42092957-0d39fd46-7bab-11e8-88df-ea478e8bff4d.png)

**Comment by christianguenter2** [comment]
Did a quick prototype. Seems that this is all currently available information without connecting to the remote repository.

![image](https://user-images.githubusercontent.com/17437789/42103644-f4f1b3cc-7bc9-11e8-9497-2c111a291b43.png)

https://github.com/christianguenter2/abapGit/tree/issue_1543

**Comment by christianguenter2** [comment]
@tricktresor @abapkochbuch 
You can check the latest version

**Comment by tricktresor** [comment]
Great!
thanks a lot! That brings some clarity into the _names_ ;)

**Comment by christianguenter2** [comment]
Feel free to close the issue.

**Comment by christianguenter2** [comment]
closing...
