### ISSUE TITLE
Reset local popup shows W3MI objects twice

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#1552]
![image](https://user-images.githubusercontent.com/5270359/42136270-98743fda-7d58-11e8-98ef-c2d8b2cdf995.png)

I assume it's because of the data.js file. If you just reset one of the two both will disappear / get reset.

**Comment by larshp** [comment]
@flaiker try again, latest version

**Comment by flaiker** [comment]
I was unable to reproduce the issue.
