### ISSUE TITLE
Reset local should also set transport request

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1554]
Reset local should also set transport request when deleting unnecessary objects. Currently the transport is set in the deserialization step afterwards. Otherwise e.g. DEVC can't be reseted.

![image](https://user-images.githubusercontent.com/17437789/42136544-d2124a84-7d5d-11e8-95bd-0a2c2075ecd7.png)

![image](https://user-images.githubusercontent.com/17437789/42136557-19b33178-7d5e-11e8-8d9d-e85c64a642ff.png)

**Comment by larshp** [comment]
cool, I also stumbled into this problem earlier today

**Comment by larshp** [comment]
does delete also call is_locked for the objects?

**Comment by christianguenter2** [comment]
hm, not yet I think. I'll check.
