### ISSUE TITLE
New start screen: do not automatically deserialize last seen repository

### ISSUE THREAD

**Issue by filak-sap** [larshp/abapGit#1558]
As discussed in #1550 we should consider changing the screen that is displayed after abapgit opens.
It sometimes happens to me that I create a repo for a big package or a package including object causing abapGit to die and then I have hard times convincing abpaGit to stop trying display the repository after restart.

**Actual results**:
abapGit tries to deserialize contents of the repository I visited last time.

**Expected results**:
abapGit allows me select a repository I want to work with this time.

**Comment by larshp** [comment]
Instead of adding more IFs, I think we should just change the default behavior to not show a repo by default?

**Comment by christianguenter2** [comment]
@larshp can you elaborate a bit further what you mean by that? I think my PR does exactly that?

**Comment by christianguenter2** [comment]
@filak-sap can check the latest build?

**Comment by larshp** [comment]
closing
