### ISSUE TITLE
Overwrite objects when pulling - file extensions should be taken into account

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#1561]
[Reproduced in version 1.70]

I am talking about this popup:
![image](https://user-images.githubusercontent.com/5097067/42219229-82db4d84-7ecb-11e8-8f5a-13b7d55540b1.png)

Having the some object appear seemingly multiple times is slightly confusing already, however, I can also reproduce a dump because of this:

Minimal steps to reproduce:

Publish package with a single class.
Make changes to the class in git, commit.
Make changes to the class in SAP, also change class description (to change the xml file), activate.

Now you should the option to pull in abapgit. You will be asked which files to overwrite. Select nothing, submit.

Abapgit does not distinguish between file extensions in this case and shows two identically named files (one clas.abap, one .xml) to choose from. 

This causes an assert to fail in this method:

```abap
" excerpt from ZCL_ABAPGIT_OBJECTS->warning_overwrite_adjust
  METHOD warning_overwrite_adjust.
....
    LOOP AT lt_overwrite ASSIGNING <ls_overwrite>.
      READ TABLE it_overwrite INTO ls_overwrite WITH KEY
        obj_type = <ls_overwrite>-obj_type
        obj_name = <ls_overwrite>-obj_name.
      IF sy-subrc <> 0 OR ls_overwrite-decision IS INITIAL.
        zcx_abapgit_exception=>raise( |Overwrite { <ls_overwrite>-obj_type } {
          <ls_overwrite>-obj_name } undecided| ).
      ENDIF.

      IF ls_overwrite-decision = 'N'.
        DELETE ct_results WHERE
          obj_type = <ls_overwrite>-obj_type AND
          obj_name = <ls_overwrite>-obj_name.
        ASSERT sy-subrc = 0.
      ENDIF.

    ENDLOOP.

  ENDMETHOD.
```

since the file is attempted to be deleted twice.

**Comment by larshp** [comment]
looks like https://github.com/larshp/abapGit/issues/1552 is a similar issue

**Comment by larshp** [comment]
@FreHu try again, latest version

**Comment by larshp** [comment]
closing
