### ISSUE TITLE
VCLS  CUS0, and CUS1 

### ISSUE THREAD

**Issue by attilaberencsi** [larshp/abapGit#1565]
Hello,

I exported VCLS, CUS0 and CUS1 objects to a zip file with version 1.70. I am tring to import it in another system with version 1.70, but that objects are not listed on the object list (only in the system where I do the export). After doing activation of the whole object list in teh target system, the mentioned objects(VCLS,CUS0,CUS1) were not in TADIR. If I go to SE54 to check the View Cluster, system immediately asks witha  popup to select transport request. After that I saw the VCLS in  TADIR, but CUS0 and CUS1 is still not in TADIR. After that I went back to ABAPGit in target system, refreshed the view and the VCLS appeared. I checked the zip file, and the CUSo,CUS1 and VCLS objects can be found inside.
Thank you
Attila

**Comment by larshp** [comment]
Hi,
Can you help reproducing the error in a public repository? Are you loading into a transported package or local?

**Comment by attilaberencsi** [comment]
Hi,
I operate with Offline projects behind corporate firewall. I created the Offline project using an existing transportable ABAP package. I have created the same package in the target system (which has a different transport layer assigned), after I created an offline project using the apckage created in the target system, then  I did the import ZIP, and skipped to overwrite the package only. 
Due inetllectual properties, I can't make the sources public, or put into a protected repo, but I can provide with the zip file per email.

**Comment by attilaberencsi** [comment]
Hi,
another thing I noticed,when doing the import second time.
Object list in original system:
![obj_list_orig](https://user-images.githubusercontent.com/20442467/42380837-83feef70-812f-11e8-8b2e-4acf932aa280.png)
When asking to overwrite in target system, I saw that the FUGR is 6 times on the list, but teh other objects with same name but of other object type are missing in the overwrite dialog.
![obj_list_ovw](https://user-images.githubusercontent.com/20442467/42380887-b150d362-812f-11e8-892a-b3d5dd113c80.png)
If I choose nothing to overwrite, I get teh following dump (rename to HTM):
[zabapgit_dump.txt](https://github.com/larshp/abapGit/files/2170621/zabapgit_dump.txt)
It might help.

**Comment by attilaberencsi** [comment]
As requested: https://github.com/attilaberencsi/zbc_job_scheduler.git

**Comment by larshp** [comment]
cool, I'm at customer site most of the week, so I do not have access to my real test systems, so I'll probably try it sometime during the weekend

**Comment by larshp** [comment]
Issue reproduced, 
![image](https://user-images.githubusercontent.com/5888506/42683038-81195086-868c-11e8-8bd2-388b60f363dd.png)

**Comment by larshp** [comment]
@attilaberencsi can you try testing #1633 and #1636 ? these should fix VCLS and CUS0

Probably a similar fix is needed for CUS1

**Comment by attilaberencsi** [comment]
I receive the following error message (TK/103) when importing a zip at the moment. 
![tk103](https://user-images.githubusercontent.com/20442467/42871395-8c457cc2-8a7a-11e8-910b-46ba8d119111.PNG)

**Comment by christianguenter2** [comment]
The same error  appears when I try to pull your example repo.
![image](https://user-images.githubusercontent.com/17437789/42876284-76856a62-8a86-11e8-8244-476898b3a082.png)

**Comment by christianguenter2** [comment]
Problem is in corr_insert. Object type LIMU VCLD isn't correct.
https://github.com/larshp/abapGit/blob/3a5b2b73fb48a5e9af4474501252edb5676742e0/src/objects/zcl_abapgit_object_vcls.clas.abap#L73

I think corr_insert of zcl_abapgit_objects_super is only valid for DDIC/DICT?
https://github.com/larshp/abapGit/blob/3a5b2b73fb48a5e9af4474501252edb5676742e0/src/objects/zcl_abapgit_objects_super.clas.abap#L103-L119

**Comment by christianguenter2** [comment]
@attilaberencsi can you try again with the latest build?

**Comment by attilaberencsi** [comment]
Hi Guys,
thanks for your support. It works great!
Attila
