### ISSUE TITLE
Import of function module/function groups - consideration of abap version

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#1566]
Issue Description:
During import of function modules / function groups the assigned abap version information in the xml file (field UCCHECK) is not considered. Instead the function module for creation "RS_FUNCTION_POOL_INSERT" will be called w/o any information. This means 'X' will used as default value.

**Comment by larshp** [comment]
so if UCCHECK is empty in the xml, and imported into a system, it becomes "X"?

**Comment by ThomasPloski** [comment]
You are right. This should be the default logic in case of XML does not have any information of UCCHECK.
