### ISSUE TITLE
PARA: popup when uninstalling

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1575]
PARA: popup when uninstalling

steps to reproduce:
1: install https://github.com/abapGit-tests/PARA
2: click Advanced -> Uninstall
3: following popup shows, expected result: no popups
![image](https://user-images.githubusercontent.com/5888506/42408151-389703b2-81c8-11e8-8ab5-9e2c78da2685.png)

Some changes required in https://github.com/larshp/abapGit/blob/master/src/objects/zcl_abapgit_object_para.clas.abap

**Comment by JohannesKonings** [comment]
Done with https://github.com/larshp/abapGit/pull/1784
