### ISSUE TITLE
TABL: error "This syntax cannot be used for an object name" when deserializing

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1584]
Install repo https://github.com/abapGit-tests/TABL_with_index, it gives the following error

Only happens when experimental features are enabled

related to https://github.com/larshp/abapGit/issues/1466 and https://github.com/larshp/abapGit/commit/17b808c8a54c046b002ec8be71bc899773b0d689

![image](https://user-images.githubusercontent.com/5888506/42409507-76a6e7fe-81db-11e8-9c32-adc34bf24fe2.png)

![image](https://user-images.githubusercontent.com/5888506/42409511-8f312df2-81db-11e8-8f4c-751f760f5fb7.png)

**Comment by larshp** [comment]
@jfilak looks like we have to move the logic for adding to transport inside the DDLS serialization class, any thoughts?

**Comment by jfilak** [comment]
Do we have many objects for which the action of adding to transport works but we have the INDX obejct that cannot be added to transport?

So we can generalize it to "we have 3 groups of DDIC objects: 1 - must be manually added to a transport, 2 - added automatically to a transport, 3 - cannot be added to a transport". Am I right?

**Comment by larshp** [comment]
some objects signal to core that it should insert in tadir, eg:

```abap
  METHOD zif_abapgit_object~get_metadata.

    rs_metadata = get_metadata( ).
    rs_metadata-delete_tadir = abap_true.

  ENDMETHOD.
```

perhaps add a flag to signal that RS_INSERT_CORR(?) should be called by the surrounding framework?

**Comment by jfilak** [comment]
I am not sure I understand your comment. Can you, please, clarify it for me? I cannot see the answers to my questions.

**Comment by larshp** [comment]
I would like to move the responsibility of adding to transport to the serialization classes and have reuseable functionality in ZCL_ABAPGIT_OBJECTS_SUPER. Much like the ZCL_ABAPGIT_OBJECTS_SUPER->CORR_INSERT method, however it cannot be reused as it only works for DDIC.

Also see https://github.com/larshp/abapGit/issues/1635

**Comment by larshp** [comment]
works now
