### ISSUE TITLE
syntax error in NW 7.31 caused by PARTIALLY IMPLEMENTED

### ISSUE THREAD

**Issue by JohannesKonings** [larshp/abapGit#1585]
The testclass of zcl_abapgit_repo_online uses PARTIALLY IMPLEMENTED. This is only available since 7.40.
Should we use the solution described here:

![image](https://user-images.githubusercontent.com/14806640/42412028-e24b31e8-8205-11e8-8ccc-5954a1236442.png)
https://blogs.sap.com/2013/06/20/abap-news-for-release-740-abap-objects/

https://github.com/larshp/abapGit/blob/361a4b067a98635012c5eea146623d1dd78d39b2/src/zcl_abapgit_repo_online.clas.testclasses.abap#L6

**Comment by larshp** [comment]
related: https://github.com/larshp/abaplint/issues/215

**Comment by JohannesKonings** [comment]
Two more classes affected: 
https://github.com/larshp/abapGit/blob/016e66244dc981eeb48298f0c7d2a39addc81761/src/zcl_abapgit_objects.clas.testclasses.abap#L363
https://github.com/larshp/abapGit/blob/0fa0c3bfe90f5a315b3719273e1669acbf876a8c/src/zcl_abapgit_dependencies.clas.testclasses.abap#L18

**Comment by larshp** [comment]
abaplint@0.29.26 will now give an error for `PARTIALLY IMPLEMENTED` when checking for version 702

**Comment by JohannesKonings** [comment]
Done with https://github.com/larshp/abapGit/pull/1588
