### ISSUE TITLE
Organizing serialization classes

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1589]
ZCL_ABAPGIT_OBJECT_ECATT_SUPER

It would be nice to only have the ZCL_ABAPGIT_OBJECT_xxx classes in the objects package, hmm, or perhaps not?

also affected:
ZCL_ABAPGIT_OBJECTS_SAXX_SUPER
ZCL_ABAPGIT_OBJECT_CLAS_*
ZCL_ABAPGIT_OBJECT_ENHO_*
ZCL_ABAPGIT_OBJECT_ENHS_*
ZCL_ABAPGIT_OO_*

**Comment by larshp** [comment]
@christianguenter2 any thoughts?

**Comment by christianguenter2** [comment]
Hm, not quite sure. My understanding was that we put everything which implements zif_abapgit_object or inherits from a class which implements that interface into the objects package.

But I also like the idea to have all pure ZCL_ABAPGIT_OBJECT_xxx serializers in a separate package. Maybe we should introduce another package we put the base/super classes?

**Comment by EduardoCopat** [comment]
What if we break into `ABAPGIT_OBJECTS_DDIC` and `ABAPGIT_OBJECTS_OO`:

- **ABAPGIT_OBJECTS**
	- ZCL_ABAPGIT_COMPARISON_NULL
	- ZCL_ABAPGIT_OBJECTS_ACTIVATION
	- ZCL_ABAPGIT_OBJECTS_FILES
	- ZCL_ABAPGIT_OBJECTS_GENERIC
	- ZCL_ABAPGIT_OBJECTS_PROGRAM
	- ZCL_ABAPGIT_OBJECTS_SAXX_SUPER
	- ZCL_ABAPGIT_OBJECTS_SUPER
	- **ABAPGIT_OBJECTS_ECATT**
		- ZCL_ABAPGIT_ECATT_CONFIG_DOWNL
		- ZCL_ABAPGIT_ECATT_CONFIG_UPL
		- ZCL_ABAPGIT_ECATT_DATA_DOWNL
		- ZCL_ABAPGIT_ECATT_DATA_UPLOAD
		- ZCL_ABAPGIT_ECATT_HELPER
		- ZCL_ABAPGIT_ECATT_SCRIPT_DOWNL
		- ZCL_ABAPGIT_ECATT_SCRIPT_UPL
		- ZCL_ABAPGIT_ECATT_SP_DOWNLOAD
		- ZCL_ABAPGIT_ECATT_SP_UPLOAD
		- ZCL_ABAPGIT_ECATT_SYSTEM_DOWNL
		- ZCL_ABAPGIT_ECATT_SYSTEM_UPL
		- ZCL_ABAPGIT_ECATT_VAL_OBJ_DOWN
		- ZCL_ABAPGIT_ECATT_VAL_OBJ_UPL
	- **ABAPGIT_OBJECTS_OO**	
		- ZCL_ABAPGIT_OBJECT_CLAS
		- ZCL_ABAPGIT_OBJECT_CLAS_NEW
		- ZCL_ABAPGIT_OBJECT_INTF
		- ZCL_ABAPGIT_OO_BASE
		- ZCL_ABAPGIT_OO_CLASS
		- ZCL_ABAPGIT_OO_CLASS_NEW
		- ZCL_ABAPGIT_OO_FACTORY
		- ZCL_ABAPGIT_OO_INTERFACE
		- ZCL_ABAPGIT_OO_SERIALIZER
	- **ABAPGIT_OBJECTS_DDIC**
		- ZCL_ABAPGIT_OBJECT_ACID
		- ZCL_ABAPGIT_OBJECT_ASFC
		- ZCL_ABAPGIT_OBJECT_AUTH
		- ZCL_ABAPGIT_OBJECT_AVAS
		- ZCL_ABAPGIT_OBJECT_CHAR
		- ZCL_ABAPGIT_OBJECT_CMPT
		- ZCL_ABAPGIT_OBJECT_CUS0
		- ZCL_ABAPGIT_OBJECT_CUS1
		- ZCL_ABAPGIT_OBJECT_CUS2
		- ZCL_ABAPGIT_OBJECT_DCLS
		- ZCL_ABAPGIT_OBJECT_DDLS
		- ZCL_ABAPGIT_OBJECT_DDLX
		- ZCL_ABAPGIT_OBJECT_DEVC
		- ZCL_ABAPGIT_OBJECT_DIAL
		- ZCL_ABAPGIT_OBJECT_DOCT
		- ZCL_ABAPGIT_OBJECT_DOCV
		- ZCL_ABAPGIT_OBJECT_DOMA
		- ZCL_ABAPGIT_OBJECT_DSYS
		- ZCL_ABAPGIT_OBJECT_DTEL
		- ZCL_ABAPGIT_OBJECT_ECAT
		- ZCL_ABAPGIT_OBJECT_ECATT_SUPER
		- ZCL_ABAPGIT_OBJECT_ECSD
		- ZCL_ABAPGIT_OBJECT_ECSP
		- ZCL_ABAPGIT_OBJECT_ECTC
		- ZCL_ABAPGIT_OBJECT_ECTD
		- ZCL_ABAPGIT_OBJECT_ECVO
		- ZCL_ABAPGIT_OBJECT_ENHO
		- ZCL_ABAPGIT_OBJECT_ENHO_BADI
		- ZCL_ABAPGIT_OBJECT_ENHO_CLASS
		- ZCL_ABAPGIT_OBJECT_ENHO_CLIF
		- ZCL_ABAPGIT_OBJECT_ENHO_FUGR
		- ZCL_ABAPGIT_OBJECT_ENHO_HOOK
		- ZCL_ABAPGIT_OBJECT_ENHO_INTF
		- ZCL_ABAPGIT_OBJECT_ENHO_WDYC
		- ZCL_ABAPGIT_OBJECT_ENHO_WDYN
		- ZCL_ABAPGIT_OBJECT_ENHS
		- ZCL_ABAPGIT_OBJECT_ENHS_BADI_D
		- ZCL_ABAPGIT_OBJECT_ENHS_HOOK_D
		- ZCL_ABAPGIT_OBJECT_ENQU
		- ZCL_ABAPGIT_OBJECT_ENSC
		- ZCL_ABAPGIT_OBJECT_FORM
		- ZCL_ABAPGIT_OBJECT_FUGR
		- ZCL_ABAPGIT_OBJECT_IAMU
		- ZCL_ABAPGIT_OBJECT_IARP
		- ZCL_ABAPGIT_OBJECT_IASP
		- ZCL_ABAPGIT_OBJECT_IATU
		- ZCL_ABAPGIT_OBJECT_IDOC
		- ZCL_ABAPGIT_OBJECT_IEXT
		- ZCL_ABAPGIT_OBJECT_JOBD
		- ZCL_ABAPGIT_OBJECT_MSAG
		- ZCL_ABAPGIT_OBJECT_NROB
		- ZCL_ABAPGIT_OBJECT_PARA
		- ZCL_ABAPGIT_OBJECT_PINF
		- ZCL_ABAPGIT_OBJECT_PRAG
		- ZCL_ABAPGIT_OBJECT_PROG
		- ZCL_ABAPGIT_OBJECT_SAMC
		- ZCL_ABAPGIT_OBJECT_SAPC
		- ZCL_ABAPGIT_OBJECT_SCP1
		- ZCL_ABAPGIT_OBJECT_SFBF
		- ZCL_ABAPGIT_OBJECT_SFBS
		- ZCL_ABAPGIT_OBJECT_SFPF
		- ZCL_ABAPGIT_OBJECT_SFPI
		- ZCL_ABAPGIT_OBJECT_SFSW
		- ZCL_ABAPGIT_OBJECT_SHI3
		- ZCL_ABAPGIT_OBJECT_SHI5
		- ZCL_ABAPGIT_OBJECT_SHI8
		- ZCL_ABAPGIT_OBJECT_SHLP
		- ZCL_ABAPGIT_OBJECT_SHMA
		- ZCL_ABAPGIT_OBJECT_SICF
		- ZCL_ABAPGIT_OBJECT_SMIM
		- ZCL_ABAPGIT_OBJECT_SPLO
		- ZCL_ABAPGIT_OBJECT_SRFC
		- ZCL_ABAPGIT_OBJECT_SSFO
		- ZCL_ABAPGIT_OBJECT_SSST
		- ZCL_ABAPGIT_OBJECT_STYL
		- ZCL_ABAPGIT_OBJECT_SUCU
		- ZCL_ABAPGIT_OBJECT_SUSC
		- ZCL_ABAPGIT_OBJECT_SUSO
		- ZCL_ABAPGIT_OBJECT_SXCI
		- ZCL_ABAPGIT_OBJECT_TABL
		- ZCL_ABAPGIT_OBJECT_TABL_DIALOG
		- ZCL_ABAPGIT_OBJECT_TABL_VALID
		- ZCL_ABAPGIT_OBJECT_TOBJ
		- ZCL_ABAPGIT_OBJECT_TRAN
		- ZCL_ABAPGIT_OBJECT_TTYP
		- ZCL_ABAPGIT_OBJECT_TYPE
		- ZCL_ABAPGIT_OBJECT_UCSA
		- ZCL_ABAPGIT_OBJECT_UDMO
		- ZCL_ABAPGIT_OBJECT_VCLS
		- ZCL_ABAPGIT_OBJECT_VIEW
		- ZCL_ABAPGIT_OBJECT_W3HT
		- ZCL_ABAPGIT_OBJECT_W3MI
		- ZCL_ABAPGIT_OBJECT_W3SUPER
		- ZCL_ABAPGIT_OBJECT_WAPA
		- ZCL_ABAPGIT_OBJECT_WDYA
		- ZCL_ABAPGIT_OBJECT_WDYN
		- ZCL_ABAPGIT_OBJECT_WEBI
		- ZCL_ABAPGIT_OBJECT_XINX
		- ZCL_ABAPGIT_OBJECT_XSLT

**Comment by larshp** [comment]
Question is then, what is DDIC and what is not? something like ACID + SSFO + WDYN I dont see as ddic

**Comment by EduardoCopat** [comment]
Yep. Not everything is DDIC. We can build on existing ABAP repository list by ADT:

![image](https://user-images.githubusercontent.com/2248490/49444059-32e7e680-f7b5-11e8-817a-36eed3551839.png)

**Comment by larshp** [comment]
the entry point is the object type(TADIR-OBJECT), so this is what I see as important. Suggest one package with one class per object type, if more classes are needed(like OO and ENHO) put it in a subpackage

**Comment by larshp** [comment]
not super high priority, nice to have, closing
