### ISSUE TITLE
Question regarding usable ABAP features(secondary indices)

### ISSUE THREAD

**Issue by mkaesemann** [larshp/abapGit#1606]
In my local abapGit branch I have done some optimizations to the way abapGit handles objects in the Git communication (encode/decode), which have proven to bring a performance boost for large repositories.
However, the optimization makes use of secondary indices on the `zif_abapgit_definitions=>ty_objects_tt` table type.
If I remember correctly, secondary indices have been allowed since 7.02, so they should be compatible with the requirements for abapGit. But I would like to confirm this with you prior to creating any pull requests, since you probably had a good reason for not using sorted tables and secondary indicies in abapGit.

**Comment by larshp** [comment]
Hi, 
Can you add some example code here(something that can be checked if it compiles), then hopefully someone with a 702 system can help.

**Comment by mkaesemann** [comment]
Sorry. That was a misunderstand.
Here's the declaration as it could be checked in any standard SAP system w/o abapGit in it:
```
  TYPES:
    ty_table_w_sec_key TYPE STANDARD TABLE OF usr02 WITH DEFAULT KEY
      WITH UNIQUE SORTED KEY name COMPONENTS bname
      WITH NON-UNIQUE SORTED KEY type COMPONENTS ustyp.
```

**Comment by christianguenter2** [comment]
Not tested in a system, but documentation says that secondary indices for interal tables were introduced in 702.

https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-US/abennews-71-itab.htm#!ABAP_MODIFICATION_2@2@

**Comment by mkaesemann** [comment]
PR #1734 has been created so this issue can be closed. Any further discussion can be done in the PR.
