### ISSUE TITLE
'Transport to zip': Error finding super package

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1615]
When we do 'Transport to zip' with a transport containing objects from different packages we get this error
![image](https://user-images.githubusercontent.com/17437789/42557558-235f0006-84ef-11e8-80e2-3028f9868aa0.png)
from here
![image](https://user-images.githubusercontent.com/17437789/42557563-26f6be3e-84ef-11e8-8512-7fd87d7a3ab5.png)
https://github.com/larshp/abapGit/blob/145a82e9eff61961a00f836c7ccd06b0e55dd981/src/zcl_abapgit_transport.clas.abap#L166-L169

I our scenario it would help a lot if we could choose a package and export all objects into one zip.

**Comment by larshp** [comment]
as far as I remember, the error is given when objects belong to 2 different package hierarchies, in this case we cannot export this to single zip, as the folder structure cannot be determined

**Comment by christianguenter2** [comment]
hm ok, I see. I'll check this sometime.
