### ISSUE TITLE
Code Inspector Performance Check: Fields of the Primary key not Fully Specified (3251)

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#1617]
There is a prio 2 issue for class ZCL_ABAPGIT_OBJECT_SICF/method READ_TADIR_SICF:

![sicf_issue](https://user-images.githubusercontent.com/39330834/42577494-c00ea4d0-8524-11e8-82b2-85afec3b72f5.PNG)

**Comment by larshp** [comment]
Pragma or pseudo comment to be added, if possible
