### ISSUE TITLE
Potential SQL injection (WHERE condition) in different methods of class ZCL_ABAPGIT_OBJECTS_GENERIC 

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#1621]
- There is a Prio1-ATC-issue in method SERIALIZE_DATA of class ZCL_ABAPGIT_OBJECTS_GENERIC in line 19 

<pre>SELECT * FROM (<ls_object_table>-tobj_name) INTO TABLE <lt_data> WHERE (lv_where).</pre>

- There is a Prio1-ATC-issue in method VALIDATE of class ZCL_ABAPGIT_OBJECTS_GENERIC in line 32

<pre>SELECT` COUNT(*) FROM (lv_primary) WHERE (lv_where).</pre>

- There is a Prio1-ATC-issue in method EXISTS of class ZCL_ABAPGIT_OBJECTS_GENERIC in line 17

<pre>SELECT SINGLE * FROM (lv_primary) INTO <lg_table_line> WHERE (lv_where_clause).</pre>

- There is a Prio1-ATC-issue in method DELETE of class ZCL_ABAPGIT_OBJECTS_GENERIC in line 15

<pre>DELETE FROM (<ls_table>-tobj_name) WHERE (lv_where).</pre>

**Comment by larshp** [comment]
Guess this was found using the CVA? 

Out of curiosity, does it say where the user input is coming from?

**Comment by ThomasPloski** [comment]
Yes, there is a data flow for each finding

**Comment by ThomasPloski** [comment]
I am currently working on these issues to fix it.
