### ISSUE TITLE
Potential SQL injection (WHERE condition) in line 17 of method EXISTS in class ZCL_ABAPGIT_OBJECTS_GENERIC

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#1623]
There is a Prio1-ATC-issue in method EXISTS of class ZCL_ABAPGIT_OBJECTS_GENERIC in line 17

`    SELECT SINGLE * FROM (lv_primary) INTO <lg_table_line> WHERE (lv_where_clause).`

**Comment by larshp** [comment]
hi, can we merge these 3 issues into one? as it is the same class, and regarding similar a problem

**Comment by ThomasPloski** [comment]
No problem. Shall I close the last 2 issues and put the detailed information to the first one?

**Comment by larshp** [comment]
yes please 😄

**Comment by ThomasPloski** [comment]
merged to #1621
