### ISSUE TITLE
Potential ABAP command injection in method DESERIALIZE_PROGRAM of class ZCL_ABAPGIT_OBJECTS_PROGRAM

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#1626]
- There is a Prio1-ATC-issue in method DESERIALIZE_PROGRAM of class ZCL_ABAPGIT_OBJECTS_PROGRAM in line 88

<pre>      INSERT REPORT is_progdir-name
       FROM it_source
       STATE 'I'
       EXTENSION TYPE is_progdir-name+30.</pre>
- There are a Prio1-ATC-issue in method DESERIALIZE_PROGRAM of class ZCL_ABAPGIT_OBJECTS_PROGRAM in line 96

<pre>      INSERT REPORT is_progdir-name
        FROM it_source
        STATE 'I'
        PROGRAM TYPE is_progdir-subc.</pre>

**Comment by larshp** [comment]
I'm not sure how this one can be avoided? The purpose of the abapGit client is to take code from a remote repo and add it into the system

**Comment by ThomasPloski** [comment]
I suppose it would require to mitigate the INSERT REPORT statement by an API to avoid ATC findings. 

Will check it with colleagues.
