### ISSUE TITLE
ABAP Unit for ZCL_ABAPGIT_BRANCH_OVERVIEW 

### ISSUE THREAD

**Issue by JohannesKonings** [larshp/abapGit#1647]
I would try to add ABAP Unit tests for https://github.com/larshp/abapGit/blob/master/src/zcl_abapgit_branch_overview.clas.abap like described here: http://docs.abapgit.org/development/tests.html
so that this issues are covered:
https://github.com/larshp/abapGit/issues/1381
https://github.com/larshp/abapGit/issues/1379

**Comment by larshp** [comment]
simple unit test for method PARSE_COMMITS added in https://github.com/larshp/abapGit/pull/1698

**Comment by larshp** [comment]
its an ongoing task to do unit tests, don't think we should keep this open, closing
