### ISSUE TITLE
Installation to non-empty package

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#166]
When cloning a repository, contents of the local package is getting overwritten.
This might be not desirable in every case.

**Comment by larshp** [comment]
I guess this is on the initial clone?

We could add a warning message if the target package is not empty?

**Comment by mrsimpson** [comment]
yup, on initial clone.
It might be a good idea to allow the user to chose a resolution strategy: Keep object from Git repo, keep object from local system and create a new branch.

**Comment by larshp** [comment]
yes, its just a lot of work

**Comment by mrsimpson** [comment]
After I disconnected the repo and re-cloned, zabapgit warned me about overwriting.
What's different compared to cloning initially?

**Comment by larshp** [comment]
depends on the packages, if there is an object in a different package than the repository package it will warn

https://github.com/larshp/abapGit/blob/master/zabapgit.abap#L10881

**Comment by larshp** [comment]
closing this one, feel free to reopen, or create new issue
