### ISSUE TITLE
Handle errors during new online

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1678]
In case the user enters a malformed url or something else bad happens during repo creation, the repo is created but not added as a favorite.

Perhaps split this into 2 steps, one saving the repo, and next doing the HTTP communication

ZCL_ABAPGIT_SERVICES_REPO=>NEW_ONLINE

![image](https://user-images.githubusercontent.com/5888506/43044009-4711cc60-8d9e-11e8-8181-01ff6bd8c6e7.png)

![image](https://user-images.githubusercontent.com/5888506/43044019-6c4b78be-8d9e-11e8-8257-b9c7e5442e88.png)

**Comment by JohannesKonings** [comment]
I deleted ro_repo->refresh( ) in new_online( ). Thereby the repo will created as a favorite.
The refresh will be called later again. 
Could that be a solution?
 
https://github.com/larshp/abapGit/compare/master...JohannesKonings:issue_1678?expand=1

![image](https://user-images.githubusercontent.com/14806640/43771551-e2341d8a-9a3f-11e8-8d09-12297a0dc739.png)


![image](https://user-images.githubusercontent.com/14806640/43771437-8ac30408-9a3f-11e8-89aa-186f0b8d32a7.png)

**Comment by larshp** [comment]
yeah, think so, nice solution if it works 👍

**Comment by JohannesKonings** [comment]
Another approach:
Analogues to the validation of a malformed url I added a ping to the url. If it fails no repo is created.

![image](https://user-images.githubusercontent.com/14806640/43780138-2dfafdf0-9a5a-11e8-92ec-ed016187a700.png)

![image](https://user-images.githubusercontent.com/14806640/43780003-ea04d7e2-9a59-11e8-8050-d91f0af4cba9.png)

![image](https://user-images.githubusercontent.com/14806640/43780076-1180f710-9a5a-11e8-973d-74281ae05e38.png)

![image](https://user-images.githubusercontent.com/14806640/43780089-16bcdd5c-9a5a-11e8-91f0-4ed2b16336c2.png)

Maybe that could work?

**Comment by larshp** [comment]
In my opinion the above is just a partial fix, the server might return an error even though the url is okay

**Comment by mbtools** [comment]
We have a new form design (https://github.com/larshp/abapGit/pull/3582). Closing this one
