### ISSUE TITLE
Optimize Refresh: ZCL_ABAPGIT_GIT_TRANSPORT=>BRANCH_LIST is called twice

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1679]
When refreshing an online repository ZCL_ABAPGIT_GIT_TRANSPORT=>BRANCH_LIST is called twice and therefore two identical HTTP requests are made. I guess we can optimize this somehow so that only one request is sufficient.

first
![image](https://user-images.githubusercontent.com/17437789/43044724-4f5b898e-8dac-11e8-9a40-9a61b353d871.png)

second
![image](https://user-images.githubusercontent.com/17437789/43044727-5bc9dcca-8dac-11e8-9162-3086bac122eb.png)

Maybe we can export the branch_list somehow from pull so we don't need 386
https://github.com/larshp/abapGit/blob/640839ad0e36ec593a2b6551fb5ad2d47fb24460/src/zcl_abapgit_repo_online.clas.abap#L378-L386

**Comment by larshp** [comment]
Also looks like `MO_BRANCHES` can be removed, it is only used in method ACTUALIZE_HEAD_BRANCH, and ACTUALIZE_HEAD_BRANCH is only called in one place,

```abap
    mo_branches = zcl_abapgit_git_transport=>branches( get_url( ) ).
    actualize_head_branch( ).
```
