### ISSUE TITLE
How to handle local deletions?

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#168]
Once a file is not serialized anymore locally, should not a  delete be commit-able?
Different usecases:
* Object deleted locally
* Part of an existing object which was serialized as file not needed anymore (e. g. locals of a class deleted)
* Object moved to another package. In this case, a text appears below the package-listing, but there's no option to commit the deletion.

**Comment by larshp** [comment]
yes, it is not implemented yet, workaround is to manually delete it using another git tool or github web

**Comment by larshp** [comment]
rm implemented in https://github.com/larshp/abapGit/commit/b51962eb66ca9097be266390f9f31f67ca7ed900
feel free to reopen issue, or create new issue if it does not work

in the staging screen the file appears under remote, click "rm"
![image](https://cloud.githubusercontent.com/assets/5888506/15274506/d2aab24c-1ab3-11e6-94b0-e852b97fc70f.png)

click "commit"

![image](https://cloud.githubusercontent.com/assets/5888506/15274507/d8c37da8-1ab3-11e6-8bb3-62dfd892f7ea.png)

and push the deletion to the repository,

![image](https://cloud.githubusercontent.com/assets/5888506/15274509/e3590968-1ab3-11e6-90b8-e541670a6096.png)

**Comment by mrsimpson** [comment]
:thumbsup:

**Comment by larshp** [comment]
lots of changes this weekend, so expect a few problems :smile:
