### ISSUE TITLE
Support for SAP Basis 700

### ISSUE THREAD

**Issue by TomLAX** [larshp/abapGit#1681]
Hi, 

i would like to use this tool in my SAP System, but we only have the release SAP Basis 7.00. What can i do?

Regards
Thom

**Comment by larshp** [comment]
See https://github.com/larshp/abapGit/issues/635, main problem is the source based class editor which does not exist in 700. I doubt abapGit will support 700 in the future, but pull requests are welcome 😄

**Comment by larshp** [comment]
Duplicate, use #635, closing
