### ISSUE TITLE
BOPF/ISWG Plugins

### ISSUE THREAD

**Issue by germ4nhunter** [larshp/abapGit#1682]
Hey,

I´ve installed abapGit and created my first repo, however it shows that BOPF Objects are ignored. I´ve read that these objects were serialized using abapgit-plugins, but I cant find any info on this as the tutorial was removed from the docs. Am I missing something?

Thanks in advance

**Comment by germ4nhunter** [comment]
Just to get this right - I need to install SAPLink, clone both abapGit-plugins and SAPLink-Plugins and it should be working?

**Comment by larshp** [comment]
just install https://github.com/larshp/abapGit-Plugins via abapGit

**Comment by germ4nhunter** [comment]
Thanks!
