### ISSUE TITLE
CHAR: 'reset local' leads to DBSQL_DUPLICATE_KEY_ERROR

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1694]
![image](https://user-images.githubusercontent.com/17437789/43220443-53da07ba-904a-11e8-813a-98d462b35e91.png)

![image](https://user-images.githubusercontent.com/17437789/43220465-6059e1fe-904a-11e8-8175-1cb2cd9f8354.png)

![image](https://user-images.githubusercontent.com/17437789/43220474-69eabfd6-904a-11e8-999f-22caf4cc4a8f.png)

![image](https://user-images.githubusercontent.com/17437789/43220488-717f1ae4-904a-11e8-83a7-9bfe9ba5dc7b.png)

**Comment by larshp** [comment]
guess this can be closed
