### ISSUE TITLE
Background mode: Remove deleted files

### ISSUE THREAD

**Issue by germ4nhunter** [larshp/abapGit#1696]
Would be a useful feature for the background mode. I´m not too sure how to do this as I just started coding ABAP a couple weeks ago, but given the size of some repositories checking if every file still exists in the repo sounds horrible. Maybe theres some Event fired when a file is deleted which we could intercept?

**Comment by larshp** [comment]
Hi,
abapGit always checks all files, as there is no events to catch(assuming the SAP standard code is not changed)

**Comment by larshp** [comment]
merged, closing
