### ISSUE TITLE
Improve keyboard navigation with link hints

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1706]
I like to do everything with the keyboard and try to avoid the mouse as much as possible. Currently the abapGit interface is mainly desinged for mouse usage. I'd suggest to introduce a concept called [link hints](https://github.com/philc/vimium/wiki/Using-Link-Hints) which is also available in browser plugins like [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb). You can activate the hints with a keystroke (e.g. pressing f) then every hyperlink gets a number or string assigned and if you type that the link is clicked.

E.g. I did it for sap.com, now I can open my profile by typing ah.
![image](https://user-images.githubusercontent.com/17437789/43344198-3a4a1268-91e9-11e8-8d3a-ae28375cc652.png)

Goal is to improve the productivity by providing a seamless keyboard interface.

**Comment by larshp** [comment]
do you run chrome inside the SAP gui? Thought it was only possible to use IE?

**Comment by christianguenter2** [comment]
No, nothing special. Just plain css and javascript.

**Comment by christianguenter2** [comment]
![image](https://user-images.githubusercontent.com/17437789/43356390-5eb0a54a-9270-11e8-9789-e28eff4b8236.png)

**Comment by christianguenter2** [comment]
https://www.youtube.com/watch?v=rGxsQZuWDis

**Comment by larshp** [comment]
Suggest defaulting the settings, so users just have to enable it, its difficult to know which values work,

![image](https://user-images.githubusercontent.com/5888506/43672914-044eae32-97b9-11e8-8637-573b9b4534a0.png)
