### ISSUE TITLE
Parallel object serialization

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1714]
Improve performance by serializing objects in parallel. This will require a function group, suggest not including this feature in the compiled report, but only in the full development installation.

Prerequsite: https://github.com/larshp/abapmerge/issues/56

Performance can be measured using https://github.com/abapGit/api_examples/blob/master/src/zabapgit_api_local_files.prog.abap

**Comment by larshp** [comment]
Notes:

test code in https://github.com/larshp/parallel_test

* refactor logic in get_files to new class?

* refactor cache handling into new method(s)

* delete HAS_CHANGED_SINCE ? https://github.com/larshp/abapGit/issues/1021

* move responsibility for setting path and SHA1 into SERIALIZE,
```abap
      lt_files = zcl_abapgit_objects=>serialize(
        is_item     = ls_item
        iv_language = get_dot_abapgit( )->get_master_language( )
        io_log      = io_log ).
      LOOP AT lt_files ASSIGNING <ls_file>.
        <ls_file>-path = <ls_tadir>-path.
        <ls_file>-sha1 = zcl_abapgit_hash=>sha1(
          iv_type = zif_abapgit_definitions=>gc_type-blob
          iv_data = <ls_file>-data ).
```

**Comment by larshp** [comment]
@mkaesemann / @christianguenter2 try running the code in https://github.com/larshp/parallel_test, i have only ~1100 objects across my installed repos, plus only 4 CPUs allocated to my docker container.

Speedup is around 2x,
![image](https://user-images.githubusercontent.com/5888506/43365545-c118bd30-932e-11e8-9bf5-3a5476f32f73.png)

**Comment by christianguenter2** [comment]
7.51 SP02 dev edition inside VM and docker container with one CPU

![image](https://user-images.githubusercontent.com/17437789/43366546-dec9e05a-933f-11e8-9df4-0602f89f3048.png)

![image](https://user-images.githubusercontent.com/17437789/43366547-e063645e-933f-11e8-9791-7f5e29425d4a.png)

**Comment by mkaesemann** [comment]
I will try to do so as soon as possible.
The parallelization code I am currently using brings our repositrory down from 10 minutes to 1 minute, but that is in conjunction with other optimizations (many already submitted via PR) and with 27 usable work processes in the system.

**Comment by larshp** [comment]
there is a few things that needs to be reorganized in order to implement parallel serialization properly, the example is in order to determine if its worth the effort

**Comment by larshp** [comment]
Suggest deleting the time based cache after/if parallel serialization is implemented

`mv_last_serialization`

**Comment by larshp** [comment]
Some numbers, reproduce with https://github.com/larshp/parallel_test, runnin on a big box

@joymike

4 threads:
![image](https://user-images.githubusercontent.com/5888506/48765101-bed81980-ecb1-11e8-9713-b339c21d4513.png)

10 threads:
![image](https://user-images.githubusercontent.com/5888506/48765271-170f1b80-ecb2-11e8-9168-c5bb3bdd6312.png)

30 threads:

**Comment by larshp** [comment]
plus follow progress here: https://github.com/larshp/parallel_test

plan is to add new class ZCL_ABAPGIT_SERIALIZE which takes care of the parallel

**Comment by larshp** [comment]
okay, more or less done

https://github.com/larshp/abapGit/pull/2122 to be merged

then retrofit the code from https://github.com/larshp/parallel_test into abapGit core, and we'll have parallel serialization

**Comment by joymike** [comment]
Awesome. Will try it out next week. Great stuff
