### ISSUE TITLE
CHAR: field HIDE_ICONS not updated at pull?

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1715]
I'm getting diffs on CHAR objects, all 3 due to HIDE_ICONS flag. Can someone try reproducing by pulling https://github.com/larshp/abapOpenChecks ?

![image](https://user-images.githubusercontent.com/5888506/43364355-f452a24e-9318-11e8-94ad-9d469c193a61.png)

![image](https://user-images.githubusercontent.com/5888506/43364356-f787fbe4-9318-11e8-9e42-9efbc633280f.png)

**Comment by christianguenter2** [comment]
I can reproduce the bug.

**Comment by larshp** [comment]
the field is not present in 751, must be introduced in a higher release, closing for now
