### ISSUE TITLE
Syntax error in compiled abapGit

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1716]
![image](https://user-images.githubusercontent.com/5888506/43366053-1bcabd8e-9337-11e8-9cb9-e24ca7beadf6.png)

@andreash1027

**Comment by larshp** [comment]
@andreash1027 try again, latest version, https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap

**Comment by andreash1027** [comment]
I was able to upgrade the code without any problems, thanks!

I admire how much code you make available to the public, so that's the least I can do to help :)

**Comment by larshp** [comment]
sharing is caring 😄 

closing issue
