### ISSUE TITLE
Only pull after remote change possible

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#173]
After having done local changes as well as a change to the branch vie gitHub Web-UI (readme.md), only a pull is possible. This overwrites local changes.
![2016-02-17 19_15_18-cortana](https://cloud.githubusercontent.com/assets/17176678/13119831/54f7fe42-d5ab-11e5-8cca-dd51efd5e96d.png)

**Comment by larshp** [comment]
yep, a dirty workaround is to change the SHA1 for the repository in SO10

as far as I remember then git command line will create a new branch for changes like this. Need the whole staging setup done then stuff like this can be solved

**Comment by larshp** [comment]
todo: there is a bug in 750 regarding local test classes after deserialize, this will probably mess it up
