### ISSUE TITLE
ecatt: Syntax errors in 702 in the long form program

### ISSUE THREAD

**Issue by kartefact** [larshp/abapGit#1737]
Trying to upgrade from v1.62 to the latest one, I get the following syntax error:

![image](https://user-images.githubusercontent.com/3407499/43569236-84a234d4-9654-11e8-86d2-d67cd0f5aaf0.png)

**Comment by kartefact** [comment]
Please label this as downport.

**Comment by christianguenter2** [comment]
Are the any other syntax errors related to ecatt?

**Comment by kartefact** [comment]
There's this one other for the local structure declared at two places as well:
![image](https://user-images.githubusercontent.com/3407499/43573666-e11adc88-965f-11e8-8c85-b5eed9e04bb9.png)

**Comment by kartefact** [comment]
When I comment out these two, I get the following syntax errors:

![image](https://user-images.githubusercontent.com/3407499/43573701-fabce37a-965f-11e8-89f7-13dca8094516.png)

**Comment by christianguenter2** [comment]
I fixed the ecatt stuff and created a pull request. Can you please create a new issue for the other errors?

**Comment by kartefact** [comment]
@christianguenter2 Do you want me to close this issue and create a new one? In that case, shall I rename this issue?

**Comment by christianguenter2** [comment]
Keep this issue open until the pull request is merged. Just open a new one for the other errors.

**Comment by christianguenter2** [comment]
@kartefact ecatt stuff should work now. Can you please check the latest build?

**Comment by kartefact** [comment]
Getting the following errors from the latest build (long form program copy+paste)

![image](https://user-images.githubusercontent.com/3407499/43709507-abc666f0-998a-11e8-8d5b-16078424ab97.png)

![image](https://user-images.githubusercontent.com/3407499/43709579-d7938f56-998a-11e8-9a2a-436e433c9ddf.png)

![image](https://user-images.githubusercontent.com/3407499/43709601-e42b72f6-998a-11e8-8581-525453b9ddc0.png)

![image](https://user-images.githubusercontent.com/3407499/43709633-f20e1d7e-998a-11e8-94e3-0fb64f372c71.png)

![image](https://user-images.githubusercontent.com/3407499/43709655-034a7c18-998b-11e8-888a-6fb083fb4745.png)

**Comment by christianguenter2** [comment]
I'll have a look

**Comment by christianguenter2** [comment]
@kartefact try again latest build

**Comment by kartefact** [comment]
@christianguenter2 No more ecatt related syntax errors :)

**Comment by larshp** [comment]
cool closing

one down, probably a lot more to go, but one step at a time in the right direction
