### ISSUE TITLE
Dump ASSERTION_FAILED when creating new online repo

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1738]
I cannot create new online repositories anymore.

Test [repo](https://gitlab.com/christianguenter/test_ecatt.git)

![image](https://user-images.githubusercontent.com/17437789/43570235-18794622-963a-11e8-9f41-566638b9271c.png)

![image](https://user-images.githubusercontent.com/17437789/43570254-2689801a-963a-11e8-901a-b1b19da19ec9.png)

![image](https://user-images.githubusercontent.com/17437789/43570266-2ee539e8-963a-11e8-9089-06629846c7d7.png)

[assertion_failed.txt](https://github.com/larshp/abapGit/files/2252614/assertion_failed.txt)

Maybe this is due the recent optimizations? @mkaesemann can you have a look?

**Comment by christianguenter2** [comment]
The error was cause by a orphaned abapGit repository. I deleted it with database utils and it's working again. Don't bother. I'll close.

**Comment by mkaesemann** [comment]
Good to hear. I try to test the optimizations prior to creating the PR and would have hated to have missed something.
