### ISSUE TITLE
Unsupported object type => Ignore repository, not all repositories

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#174]
Once an unsupported object type is contained in one of the synced packages, the complete ZABAPGIT is not functional anymore. Though the report does not terminate technically, the HTML-container appears empty.
Desired behavior: Provide an error message only for the affected package/fork. From this repository, no further action should be possible. Other repositories should be unaffected.

**Comment by larshp** [comment]
Tried to reproduce the error, in this example there are 2 repositories "IA" and "abapGit". The "IA" is not functional, but the abapGit repository seems to work:

![image](https://cloud.githubusercontent.com/assets/5888506/13389324/3ecad926-dec7-11e5-9ae3-139eac3b5490.png)

**Comment by larshp** [comment]
I figured out that this happens at eg. startup of abapgit, and not when adding like in the above example. Issue reproduced.

**Comment by larshp** [comment]
Hi Oliver,
Can you try again, I think it has been fixed in above commit. It will look something like the following:

![image](https://cloud.githubusercontent.com/assets/5888506/15071013/c9d7f5bc-1388-11e6-8c64-5f109ca8846e.png)

**Comment by larshp** [comment]
should have been fixed, closing issue, feel free to reopen in case of any issues

**Comment by mrsimpson** [comment]
Confirmed. Couldn't reproduce it. Thx
