### ISSUE TITLE
"To do, encoding length" Error in Pushing Whole Packages

### ISSUE THREAD

**Issue by pwguinto** [larshp/abapGit#1741]
We are currently attempting to use abapGit in committing a whole development package (which contains more than 5000 objects) to Github and we are getting this error.

![image](https://user-images.githubusercontent.com/39749918/43626578-0e47fe5a-9725-11e8-972b-49f322163725.png)

It is probably in the best interest to commit files in batches though we can't seem to find an easy way to do so. Would you guys be able to check and identify why this error is triggered?

Thanks!

**Comment by larshp** [comment]
Hi,
Can you try setting a break-point at https://github.com/larshp/abapGit/blob/3331a73b863226a5d7a38f67f6bf39f07ae727e7/src/git/zcl_abapgit_git_pack.clas.abap#L910 ?

and check the values of `iv_type` + `iv_length`, plus it should be possible to find the file/object name in the call hierarchy

It looks like you are committing more than 30 megabytes, after compression in a single blob/file?

**Comment by pwguinto** [comment]
Yup, we are definitely committing something more than 30MB but okay. I will place a breakpoint there and check which object triggers the exception.

**Comment by pwguinto** [comment]
Yup, looks like there's possibility that we'll be using abapGit to store such. Currently debugging to check the lengths of the variables that would trigger the exception. Will be putting what I'll find here.

**Comment by pwguinto** [comment]
I was able to trigger the error and have these values:

![image](https://user-images.githubusercontent.com/39749918/43628892-2248a63a-972e-11e8-9f5b-9c7c2aea8382.png)

![image](https://user-images.githubusercontent.com/39749918/43629009-8bc02da4-972e-11e8-8c47-61eda7f3ae86.png)

Not really sure if these make sense though let me know if you still need more info.

**Comment by larshp** [comment]
@pwguinto try the code in https://github.com/larshp/abapGit/pull/1745

**Comment by tantulus** [comment]
Is there a way to exclude large binary files?

**Comment by larshp** [comment]
@tantulus nope, not in abapGit. If you like to exclude them I suggest storing the large objects in a different package outside of the git repository/package hierarchy

**Comment by christianguenter2** [comment]
Or maybe the userexit change_tadir is of some help? There you can exclude specifc objects on tadir base. 
   
https://github.com/larshp/abapGit/blob/f9746cf19911a330736c7ecde91806c7ca109637/src/zcl_abapgit_tadir.clas.abap#L235-L240

**Comment by tantulus** [comment]
Thank you for input.

**Comment by pwguinto** [comment]
Hello,
I updated the abapGit code and attempted to do the same batch commit and while I'm not getting the "To do, encoding length" error, I am receiving a new one.

![image](https://user-images.githubusercontent.com/39749918/43693974-945969da-9963-11e8-8f39-20270dd4a1f7.png)

Which comes from this method:
![image](https://user-images.githubusercontent.com/39749918/43694000-b2fcbc0c-9963-11e8-92ec-882d8bac4064.png)

**Comment by larshp** [comment]
hmm, this one is much more difficult, the remote host declines the packfile, this usually means there is something wrong with the packfile generated by abapGit, it is difficult to debug remotely

**Comment by pwguinto** [comment]
When you say "remote host" is it the repo rejecting the packfile generated by abapGit?

**Comment by larshp** [comment]
yes

**Comment by larshp** [comment]
try pushing in smaller chunks, you can use to search function to get push all CLAS files in one commit

**Comment by pwguinto** [comment]
Yeah, about that -- I was trying to make filtering work according to object type but I can't seem to do so. I can do filtering by object or user name but not by object type.

![image](https://user-images.githubusercontent.com/39749918/43704679-0db5acc4-9993-11e8-815e-f25fa75a82bf.png)

![image](https://user-images.githubusercontent.com/39749918/43704715-220316f8-9993-11e8-8824-1ded647af481.png)

**Comment by larshp** [comment]
the search is case sensitive, and searches usernames and file names(as far as I remember) try "clas" instead of "CLAS"

**Comment by pwguinto** [comment]
The lower case filtering worked, we tried committing only type PROG objects and it eventually returned a short dump:

![image](https://user-images.githubusercontent.com/39749918/43750456-1b42bff6-9a2b-11e8-9bfa-d1f4be660061.png)

![image](https://user-images.githubusercontent.com/39749918/43750526-6c021ec8-9a2b-11e8-8792-e5257be3fe27.png)

The activation mode of the ASSERT statement in method PROCESS_STAGE_LIST is set to "abort". The SY-SUBRC value during that point is 4. Not really sure how to interpret those though.

**Comment by larshp** [comment]
Does the program `sds0_gbl_i_multi` exist in your system? Are you using namespaces?

**Comment by pwguinto** [comment]
Yup, it is an existing include, and we don't use namespaces.

![image](https://user-images.githubusercontent.com/39749918/43808269-e1735006-9ade-11e8-9696-e88fc01d8913.png)

**Comment by larshp** [comment]
note that the screenshot from the debugger says "sds0_gbl_i_multi" not "zsds0_gbl_i_multi", or did you move the cursor to the end of the field so it does not show the correct value?

**Comment by pwguinto** [comment]
Thanks. For now, committing in smaller batches work, though we do think there is a program that triggers the asset error. I'll post another update if we're able to narrow it down.

**Comment by pwguinto** [comment]
I think we found what's causing the ASSERT issue, the code is looking for a program named like this:
![image](https://user-images.githubusercontent.com/39749918/43823465-aba4028e-9b21-11e8-90fa-dbe2c758d427.png)

To which the only viable object with the same name is:
![image](https://user-images.githubusercontent.com/39749918/43823502-ca39556e-9b21-11e8-9b85-ca34af3e0818.png)

I have to check deeper on whether this is a mis-classification of an Enhancement to a Program or something similar.

**Comment by larshp** [comment]
As documented in https://launchpad.support.sap.com/#/notes/1025291 this is a bug in the standard code regarding the EIMP PROG in TADIR. 

Run report `DELETE_TADIR_FOR_EIMP_INCLUDE` to clean up the wrong TADIR entries

**Comment by larshp** [comment]
@pwguinto can this issue be closed, did it work out?

**Comment by pwguinto** [comment]
Yup, I'll close this issue, as the initial bug has been addressed. Thanks for the support!
