### ISSUE TITLE
First link in the repo page

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#1746]
The first link here goes straight back to the repo, which doesn't make much sense to me:
![image](https://user-images.githubusercontent.com/5097067/43673279-6de027a2-97c0-11e8-8b7f-482ed44bb7b4.png)

Wouldn't it be better if the link went to https://docs.abapgit.org instead?

**Comment by larshp** [comment]
¯\_(ツ)_/¯

**Comment by larshp** [comment]
closing, lets keep as is for now, thanks for the suggestion 👍

**Comment by FreHu** [comment]
@larshp please change this. It's impossible to PR as this is part of the repo description. If the first thing you see in the repo is completely pointless, it sets a bad example for the rest :)

**Comment by larshp** [comment]
updated

**Comment by FreHu** [comment]
thanks! this will no longer keep me up at night
