### ISSUE TITLE
Improve screen flow: stage and commit from diff screen

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1748]
If we stage and commit from the diff page, we get back to the diff page after the commit. I think this is a bit confusing, especially as you are able to press stage again. I suggest that we navigate back to the main repo page after a successful commit.

![image](https://user-images.githubusercontent.com/17437789/43673663-f28d4a92-97c6-11e8-9766-af24567a647e.png)
˙
![image](https://user-images.githubusercontent.com/17437789/43673664-f61b8f70-97c6-11e8-9e0d-15e8119b752a.png)

![image](https://user-images.githubusercontent.com/17437789/43673667-f8c852a8-97c6-11e8-8b7f-4f2afddcb5e9.png)

![image](https://user-images.githubusercontent.com/17437789/43673670-fb3c20c8-97c6-11e8-94e5-50c63ff28c40.png)

![image](https://user-images.githubusercontent.com/17437789/43673692-6d27acc0-97c7-11e8-8d52-a9022c3685ea.png)

![image](https://user-images.githubusercontent.com/17437789/43673676-0b469db8-97c7-11e8-8085-b9f0879ccd38.png)

**Comment by jfilak** [comment]
Yep, but I liked it because it helped me to follow my workflow:
```
hack
until everything is committed:
  until satisfied:
    git diff
    git add -p
  git commit
```

**Comment by larshp** [comment]
did you stage from the diff screen? note that the files on the staging screen link to the diff page

**Comment by jfilak** [comment]
Yes, I did. Because the stage screen contains many many many objects and there is no way how to easily see the delta I add from the stage screen.

**Comment by jfilak** [comment]
You can ignore me - I am a git nazi - I spend a lot of time polishing my commits.

**Comment by sbcgua** [comment]
> Yes, I did. Because the stage screen contains many many many objects and there is no way how to easily see the delta I add from the stage screen.

Yeap, I also had the same issue. To choose all diffs related to a particular object easily. This was probably the reason to add it if I remember well :) It was a convenient feature imho.

**Comment by larshp** [comment]
We can also add it back in, pull requests welcome. Just trying to remove some complexity
