### ISSUE TITLE
lcl_xml->add_table/structure/element: iv_name overridden

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#175]
If iv_name is supplied by the consumer , it should be the one used by the xml writer.
Else, different elements of the same type cannot be distinguished when reading the data again
![2016-02-21 12_30_56-info-center](https://cloud.githubusercontent.com/assets/17176678/13202321/ffc5f476-d896-11e5-9e1b-4587590f8b88.png)

**Comment by mrsimpson** [comment]
soon fixed in fork https://github.com/mrsimpson/abapGit

**Comment by larshp** [comment]
yep

**Comment by larshp** [comment]
some of the changes rolled back

Breaking already serialized objects. We are not ready for breaking stuff yet, need to prepare for it, things will be solved with "NextGen XML"

**Comment by larshp** [comment]
@mrsimpson ran the unit test LTCL_DANGEROURS in ZABAPGIT, this showed up with errors.

I agree on the final resulting XML, but we are not ready to break stuff yet. Would like to prepare the "NextGen XML", and then break **everything**, plus add user-guides on how to handle the new situation

**Comment by mrsimpson** [comment]
agreed. Did only run all the harmless ones, that looked fine.

**Comment by larshp** [comment]
this should be fixed now with next-gen-xml
