### ISSUE TITLE
New online popup, fix descriptions

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1752]
Should be "create online" instead of "clone", also suggest just having "package" instead of "target package"

![image](https://user-images.githubusercontent.com/5888506/43675123-46f45b80-97df-11e8-944a-a1536625f0b8.png)

**Comment by JohannesKonings** [comment]
I have adapted the description analogous to the offline project. Does it fit?

![image](https://user-images.githubusercontent.com/14806640/43731282-4de52296-99ae-11e8-8f48-e537418bc319.png)
![image](https://user-images.githubusercontent.com/14806640/43731303-5b4c6476-99ae-11e8-9686-65074874bd05.png)

Why is a new popup needed?

**Comment by larshp** [comment]
descriptions look good

no new popup is needed, just adjust the descriptions in the existing popup
