### ISSUE TITLE
SSST: package popup

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1755]
Steps to reproduce: install https://github.com/larshp/abapOpenReview

Add SSST repo under https://github.com/abapGit-tests

Shows following popup, no popup expected
![image](https://user-images.githubusercontent.com/5888506/43676436-9b4a4728-97f1-11e8-84e7-1b8e044d4d7f.png)

**Comment by JohannesKonings** [comment]
Test repo: https://github.com/abapGit-tests/SSST

**Comment by JohannesKonings** [comment]
Done with https://github.com/larshp/abapGit/pull/1783
