### ISSUE TITLE
Namespaced structures screw up XML

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#176]
when adding a table/structure via lcl_xml, the created element looks like 
`</NAMESPACE/TABLENAME><//NAMESPACE/TABLENAME>`
Escaping needed.

**Comment by mrsimpson** [comment]
soon fixed in https://github.com/mrsimpson/abapGit

**Comment by larshp** [comment]
yep, ran into the same problem while messing around with https://github.com/larshp/abapGit-Gateway

the escaping will be a quick fix

_long term_
actually been wondering to rewrite much of the XML stuff, currently it uses the data element names which might cause problems. The way it has been done in https://github.com/larshp/upDOWNci/blob/master/zupdownci.prog.abap is nicer, plus would like just to have one "add" method which itself figures out the type

**Comment by mrsimpson** [comment]
For simple serialization, I always tend to populare an ABAP-structure and the apply the ID-transformation. With respect to performance, this is the best solution, imho.
Have you had other experiences?

**Comment by larshp** [comment]
I haven't tried using the ID transformation before, should test to see how it works out.

Will create a new repository for testing if I start working on it

**Comment by larshp** [comment]
I did some testing in https://github.com/larshp/abapGit-NextGen-XML/blob/master/zxml.abap

Probably the namespaces will work with it

**Comment by mrsimpson** [comment]
Used namespaces in ID-Transformation today. You might want to check out the generic implementation and the st-based container

**Comment by larshp** [comment]
sure will

**Comment by larshp** [comment]
this should be fixed now with next-gen-xml
