### ISSUE TITLE
Method chaining syntax error in 702 (downport)

### ISSUE THREAD

**Issue by kartefact** [larshp/abapGit#1775]
Getting the following error when trying to activate the latest long form version of the program in 702:

![image](https://user-images.githubusercontent.com/3407499/43716967-96c50824-99a3-11e8-942e-b6a93f7f59c3.png)

This seems to be at multiple places in the code. The above is just one example.

**Comment by kartefact** [comment]
Please label this as "downport".

**Comment by larshp** [comment]
this one is probably a lot of work 😞 Pull requests welcome

I'll check if it is possible to implement a check for this in abaplint

**Comment by christianguenter2** [comment]
@kartefact next try with latest build

**Comment by kartefact** [comment]
More errors: 

![image](https://user-images.githubusercontent.com/3407499/43719100-5d047050-99aa-11e8-8238-1a6d91fc08c6.png)
![image](https://user-images.githubusercontent.com/3407499/43719113-6a8c1ad4-99aa-11e8-8967-f4b95795156e.png)
![image](https://user-images.githubusercontent.com/3407499/43719136-76bd3162-99aa-11e8-9150-64bd1a5ffc0b.png)

**Comment by christianguenter2** [comment]
D'oh, still some work to do.

@larshp how did that one pass the linter?
https://github.com/larshp/abapGit/blob/f0fb0f047052affb67caa64c592eb1ddd0420323/src/zcl_abapgit_tadir.clas.abap#L105

**Comment by larshp** [comment]
not sure, opened https://github.com/larshp/abaplint/issues/223

**Comment by christianguenter2** [comment]
@kartefact can you try latest build? A few erros should have gone. Can post the current error list?

**Comment by kartefact** [comment]
@christianguenter2 
Errors from the latest build:

![image](https://user-images.githubusercontent.com/3407499/43754650-8a99e138-9a29-11e8-8634-5c2392efd26e.png)

**Comment by christianguenter2** [comment]
@kartefact next round. There should be only some errors left. Can you check again the latest build and send the  errors list?

**Comment by kartefact** [comment]
Here are the errors from the latest build. Almost there! 💃 

![image](https://user-images.githubusercontent.com/3407499/43767086-c8d8dbf2-9a51-11e8-95ef-846b7c7a24f4.png)

**Comment by christianguenter2** [comment]
@kartefact try again latest build

**Comment by christianguenter2** [comment]
Btw. the ecatt stuff probably doesn't work on 702, but I think that's ok.

**Comment by kartefact** [comment]
Errors in the latest build:

![image](https://user-images.githubusercontent.com/3407499/43775923-f16e63ba-9a6b-11e8-9452-296529941887.png)

@christianguenter2 Yes, I understand that it may not work. That's okay.

**Comment by christianguenter2** [comment]
@kartefact next try

**Comment by kartefact** [comment]
@christianguenter2 Success! No errors. 💃 
However. on pulling the latest build from the repo, it leads the Issue #1273

**Comment by kartefact** [comment]
Yes, Used the latest compiled report. Please close this issue. This one seems to be fixed.
