### ISSUE TITLE
every package one repository

### ISSUE THREAD

**Issue by a-kuller** [larshp/abapGit#1779]
Hello,
I have a question, if I have the following structure:
Main
-> Sub1
-> Sub 2

how can i say abapgit that every package is a separate repository?

I have tried the following:
- create main and ignore subpackages = true, pull, then create sub1/2
- create sub1/sub2 and pull, then create main

Every time I get the following error message: repository ... already contains ...

how can I handle this?

thank you
best regards a-kuller

**Comment by larshp** [comment]
This looks like a bug, this should be possible in case ignore_subpackages is set.
Probably need to change the code for the validation

👍

**Comment by larshp** [comment]
@a-kuller try this, https://github.com/larshp/abapGit/pull/1785

**Comment by a-kuller** [comment]
it work's, great.

Thank you very much.

**Comment by larshp** [comment]
cool, merged to master, closing
