### ISSUE TITLE
Saving remote repo password

### ISSUE THREAD

**Issue by kartefact** [larshp/abapGit#1789]
Would love to have the remote repo password saved and not having to enter it every time.

**Comment by kartefact** [comment]
Please label this as "feature request"

**Comment by larshp** [comment]
SAP systems are typically multi user, thus saving the password in a database able is not preferred. And abapGit is used in developer systems, so the secure store is also accessible for everyone.

Suggest using a password tool on your PC, like Keepass, see https://github.com/larshp/abapGit/pull/1262

**Comment by kartefact** [comment]
@larshp/abapGit
<reply@reply.github.com>
I
do use lastpass with my browser. How do I get it to work with SAP GUI
screen on abapGit?

Regards,
Karthikeyan Ravikumar

**Comment by kartefact** [comment]
okay, Installed Lastpass for Desktop application on my windows laptop. When the password prompt comes up for the repo on abapGit, I had to press ctrl+alt+F, click train, then login normally to add the application to lastpass. Next time onward, I just have to hit Ctrl+Alt+F to autofill the password and login.
This can be documented somewhere may be.

This issue can be closed.

**Comment by larshp** [comment]
I think this is not abapGit specific, so it does not have to be documented as part of abapGit. But people can find this issue if they have similar questions/suggestions 👍 

closing
