### ISSUE TITLE
After a commit, repository still shows files as changed

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#1797]
After I commit, I am taken back to the repo homepage and I still see the same files that I committed as changed. Clicking on the diff reveals that there are no differences.

![sapguiserver_2018-08-07_15-41-51](https://user-images.githubusercontent.com/5097067/43779335-745538bc-9a58-11e8-9cac-41f55a0652c8.png)

![image](https://user-images.githubusercontent.com/5097067/43779326-6d1dc686-9a58-11e8-82c4-cb563d405c95.png)

Either a refresh should be done or maybe there is a way to exclude the files you just committed from being displayed as changed.

**Comment by larshp** [comment]
I've also seen this a few times today, afraid it is introduced by some of the recent refactoring.

However it does not happen every time for me, hmm 😕

**Comment by FreHu** [comment]
I was still using 1.72, so that should help narrow it down

**Comment by larshp** [comment]
okay, first step is updating to latest then 😄

**Comment by larshp** [comment]
found, this error occurs when clicking diff from the staging screen

**Comment by larshp** [comment]
@FreHu try this, https://github.com/larshp/abapGit/pull/1798

**Comment by FreHu** [comment]
already left work, I will get to it tomorrow

**Comment by FreHu** [comment]
Tested just now, it seems to be working. Thanks.
