### ISSUE TITLE
clean up ZCL_ABAPGIT_OBJECT_CLAS_OLD

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1801]
ZCL_ABAPGIT_OBJECT_CLAS_OLD has not been in use for a while, delete

note that _NEW inherits from _OLD, move everything to ZCL_ABAPGIT_OBJECT_CLAS

**Comment by marcellourbani** [comment]
I will give this a shot

**Comment by marcellourbani** [comment]
I have a problem.

in the constructors, 
ZCL_ABAPGIT_OBJECT_CLAS_OLD does this:
`mi_object_oriented_object_fct = zcl_abapgit_oo_factory=>make( ms_item-obj_type ).
which ends up instantiating zcl_abapgit_oo_class and ZCL_ABAPGIT_OBJECT_CLAS does this:
`create object mi_object_oriented_object_fct type zcl_abapgit_oo_class_new.

I won't copy that line from _old as seems pointless, but I wonder if we should decommission/replace zcl_abapgit_oo_class

**Comment by larshp** [comment]
merged, closing
