### ISSUE TITLE
error RS_CUA_INTERNAL_WRITE while pulling an old abapgit repository

### ISSUE THREAD

**Issue by sandraros** [larshp/abapGit#1807]
I have the same issue as #562 which is solved by correcting manually the XML of the CUA interfaces (fastidious), or by regenerating the XML (but unfortunately sometimes the abapGit repository is from someone else).

So, I would like to propose my correction which is about to add an option in the "repository settings" to auto correct the CUA interfaces : https://github.com/sandraros/abapGit/tree/pull-option-to-auto-correct-RS_CUA_INTERNAL_WRITE-errors

This way, it's up to the user to decide whether he wants to auto correct or not.

Sandra

**Comment by larshp** [comment]
Cool, pull requests welcome 😄 see https://help.github.com/articles/github-flow/

I guess it is okay just to add the code to fix this, and always run it. I.e. suggest not having this as a configuration option.

**Comment by sandraros** [comment]
No option then. That's done, please merge #1809.

**Comment by larshp** [comment]
merged, closing
