### ISSUE TITLE
CHECK_31 - Extended Program Check, Filterable

### ISSUE THREAD

**Issue by gajulahari69** [larshp/abapGit#1808]
When we are calling a function module for class method with more than 10 exceptions, "Insert a constant for the numeric literal" is displayed from exception 11.

**Comment by larshp** [comment]
Hi Hari, 👋 

Check 31 runs the SAP standard Extended Program check,

![image](https://user-images.githubusercontent.com/5888506/43947196-ba96576c-9c87-11e8-9418-27fa5ae34c86.png)

![image](https://user-images.githubusercontent.com/5888506/43947199-c29bbd8a-9c87-11e8-95e0-d29b2f2359a9.png)

gives

![image](https://user-images.githubusercontent.com/5888506/43947205-c6b8226e-9c87-11e8-8641-9446c233ae55.png)

Check 31 allows you to filter findings from the SAP standard check, eg ignoring error code 0504.
![image](https://user-images.githubusercontent.com/5888506/43947249-dc2c5962-9c87-11e8-87b2-a6c49d1d986b.png)

**Comment by larshp** [comment]
oh, and wrong repository? should be https://github.com/larshp/abapOpenChecks instead

**Comment by larshp** [comment]
closing, create issue under https://github.com/larshp/abapOpenChecks if you have more questions
