### ISSUE TITLE
Show commit message body in branch overview

### ISSUE THREAD

**Issue by patvo** [larshp/abapGit#1821]
Hi
I would like to suggest to show the commit message body (e.g. as a hoverbox) in the branch overview.

**Comment by bigld** [comment]
https://github.com/nicoespeon/gitgraph.js/issues/138

**Comment by christianguenter2** [comment]
@patvo Feature is implemented. You can try with the latest build.

**Comment by patvo** [comment]
> 
> 
> @patvo Feature is implemented. You can try with the latest build.

Thanks, works like a charm. This is a great improvement! 👍
