### ISSUE TITLE
Invalid branch overview after merged branches are deleted

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1823]
When branches are deleted after they are merged, the branch overview shows a linear history.
Test repo https://gitlab.com/christianguenter/test_branch_overview.git 

![image](https://user-images.githubusercontent.com/17437789/44168397-710bae00-a0d1-11e8-9ac3-f9bacbd3de17.png)

With graphical git client
![image](https://user-images.githubusercontent.com/17437789/44168409-7963e900-a0d1-11e8-9bc8-468b9c32f21b.png)

And local git client
![image](https://user-images.githubusercontent.com/17437789/44168415-7e289d00-a0d1-11e8-8dfe-7e205baa113a.png)

I'd expect that the branch overview also show the correct non-linear commit history.

**Comment by larshp** [comment]
guess only active branches are shown, and it does not take merge commits properly into account

**Comment by bigld** [comment]
@christianguenter2 can this be closed?
