### ISSUE TITLE
abapGit on pure BASIS system

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1826]
Currently the following objects are used:

* Table type RSO_T_OBJNM(define in ZIF something instead)

* Function module BANK_OBJ_WORKL_RELEASE_LOCKS(look for other dummy implementation which is part of BASIS)

Which does not exist in pure BASIS system?

**Comment by larshp** [comment]
fm CLVF_VB_RELEASE_LOCKS does not exist in 730

**Comment by flaiker** [comment]
`PERFORM dequeue ON COMMIT.` would be too early I guess? CLVF_VB_RELEASE_LOCKS doesn't exist on 740 either by the way.

**Comment by marcellourbani** [comment]
This looks trivial enough to start contributing.
I wrote a small program to look for alternative FMs (update with no code), it came up with this list:

/BOBF/TRA_DUMMY_UPDATE_TASK   
SRT_IDP_DBACCESS_ON_ROLLBACK  
CLMU_CHANGE_ALLOCATION_VALUES 
BANK_OBJ_WORKL_RELEASE_LOCKS  

The only good candidate imho is SRT_IDP_DBACCESS_ON_ROLLBACK, but in my 7.0 system it's not empty, does a perform running method cl_ws_idp_helper=>cleanup_on_rollback
I think this is harmless unless we are inside a SOAP call and method SOAP_IDP_HELPER=>IF_WS_IDP_HELPER~SAVE

I still would prefer to create our own FG, but I guess that would prevent packaging the whole thing.
Or we can create a get_function method which returns  BANK_OBJ_WORKL_RELEASE_LOCKS if found, using SRT_IDP_DBACCESS_ON_ROLLBACK as a fallback

**Comment by flaiker** [comment]
I wonder if you can use the generic update task of object services for this. I thought this might work but I wasn't able to get the OO transaction to inherit the lock (even with a dummy update between start and end).
```abap
METHOD lock.
  DATA: li_transaction_manager TYPE REF TO if_os_transaction_manager,
        li_transaction         TYPE REF TO if_os_transaction.

  CALL FUNCTION 'ENQUEUE_EZABAPGIT'
    EXPORTING
      mode_zabapgit  = iv_mode
      type           = iv_type
      value          = iv_value
    EXCEPTIONS
      foreign_lock   = 1
      system_failure = 2
      OTHERS         = 3.
  IF sy-subrc <> 0.
    zcx_abapgit_exception=>raise( |Could not aquire lock { iv_type } { iv_value }| ).
  ENDIF.

  li_transaction_manager = cl_os_system=>get_transaction_manager( ).
  li_transaction = li_transaction_manager->create_transaction( ).
  li_transaction->set_mode_update( oscon_dmode_update_task ).
  li_transaction->start( ).
  li_transaction->end( ).
ENDMETHOD.
```

**Comment by marcellourbani** [comment]
I don't know this framework, but doesn't seem like it would work.
At best this code will create a new transaction and commit it. 

If I understand it correctly this call is made to cleanup the locks after we're done:
The commit no the main transaction will trigger the update task which will run asynchronously and do nothing in our code, but I guess will trigger some system code closing  the pending enqueues of dead parent processes

**Comment by flaiker** [comment]
Well I thought it might work, because there is a OS transaction "compatibility mode", so the commit would only takes place at the `COMMIT WORK`.

Function module `STFC_PING_VB` seems like the perfect candidate to me. Should we use that one?

`BANK_OBJ_WORKL_RELEASE_LOCKS` does way more stuff than one might think by the way. There is a `LOAD-OF-PROGRAM` event in the function group that causes the same event to be called in SAPLAIEV, in which some classes get event handlers registered on cl_system_transaction_state=>transaction_finished ...

**Comment by marcellourbani** [comment]
Looks good! I wonder how I missed it.
Will update it and do a new pull request, but not now (I'm too busy at work)

**Comment by marcellourbani** [comment]
...although it has another potential issue: doesn't exist in 7.0, not sure what the minimal requirement is.

About the commit, I had a look at the code, in our case li_transaction->end( ). would do it straight away.Also, doesn't seem to run anything in update tasks

**Comment by jfilak** [comment]
FYI: abapGit worked OK even if the function module `BANK_OBJ_WORKL_RELEASE_LOCKS` was just an empty function doing nothing (it is a very latest system and I cannot tell you anything more specific :).

**Comment by marcellourbani** [comment]
I know, the whole point is to run an  update task to trigger some side
effect, not to do something in it.
But the function needs to exist or you'll get dumps/ exceptions

**Comment by marcellourbani** [comment]
CALL_V1_PING looks even better, will use that and remove the existence check

**Comment by larshp** [comment]
@jfilak is it possible for you to test this? possible fix merged

**Comment by jfilak** [comment]
Will try to get an account in that system :)

**Comment by larshp** [comment]
@jfilak any luck? Looking at the initial issue I think this can be closed?

**Comment by jfilak** [comment]
abapGit is woking on our basis system.
