### ISSUE TITLE
Syntax error in: ZCL_ABAPGIT_GUI_CHUNK_LIB

### ISSUE THREAD

**Issue by patvo** [larshp/abapGit#1832]
Just updated. Now I'm getting an syntax error in ZCL_ABAPGIT_GUI_CHUNK_LIB in method render_hotkey_overview: **Field "GC_ACTION_TYPE-ONCLICK" is unknown.**
(Line 127: iv_typ   = zif_abapgit_definitions=>gc_action_type-onclick)

**Comment by JohannesKonings** [comment]
This is caused by https://github.com/larshp/abapGit/pull/1827.
I'll correct it.

**Comment by christianguenter2** [comment]
fix is included in #1728

**Comment by JohannesKonings** [comment]
@patvo can you please update again? The syntax error should be fixed.

**Comment by patvo** [comment]
@JohannesKonings Fixed. Many thank! :)

**Comment by JohannesKonings** [comment]
Thanks to @christianguenter2 😄
