### ISSUE TITLE
Modified Few feature of ABAP Git

### ISSUE THREAD

**Issue by supriya42** [larshp/abapGit#1840]
Modified the feature of Advanced-> Object to files feature . earlier it was single single doc we can download but have modified it and made it as select option written logic for that and it's working as expected . Working On some other feature , which will helpful for end user.

![sel_abap_git](https://user-images.githubusercontent.com/13636811/44299008-5c1a5f00-a30b-11e8-8af4-a7a8fd53aed3.png)

**Comment by larshp** [comment]
Pull requests welcome

**Comment by larshp** [comment]
@supriya42 are you working on this?

**Comment by supriya42** [comment]
I have made this change and now i am using it as well

**Comment by larshp** [comment]
@supriya42

**Comment by larshp** [comment]
closing
