### ISSUE TITLE
Logon with RFC destination

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1841]
On my ABAP developer edition I'd like to use RFC destinations for the HTTP client (cl_http_client=>create_by_destination). This has the advantage that I don't need to provide my credentials anymore. I'd like to create a RFC destination for every git server I use.

Two possible ways to implement this.
1) provide a new option in repo settings to maintain a RFC destination
2) provide RFC destination somehow over the APIs
3) provide a new user exit override abapGit standard http client instantiation, somewhere here

https://github.com/larshp/abapGit/blob/d7e90aae6062388f8efacdad6d707356ba3c7b56/src/http/zcl_abapgit_http.clas.abap#L127-L139

possible implementation could look like this:
 
```
    DATA(lv_host) = zcl_abapgit_url=>host( iv_url ).

    DATA(lv_destination) = COND rfcdest( WHEN lv_host CS 'gitlab' THEN |GITLAB|
                                         WHEN lv_host CS 'github' THEN |GITHUB| ).

    IF lv_destination IS INITIAL.
      RETURN.
    ENDIF.

    cl_http_client=>create_by_destination(
      EXPORTING
        destination              = lv_destination
      IMPORTING
        client                   = ri_client
      EXCEPTIONS
        argument_not_found       = 1
        destination_not_found    = 2
        destination_no_authority = 3
        plugin_not_active        = 4
        internal_error           = 5
        OTHERS                   = 6 ).

    IF sy-subrc <> 0.
      zcx_abapgit_exception=>raise_t100(  ).
    ENDIF.

```

Any opinions? Was this already discussed?

**Comment by christianguenter2** [comment]
Maybe this is then also an option for background mode.

**Comment by christianguenter2** [comment]
I'd prefer option 3. I tested it already and it works like a charm.

With this RFC destination for GitHub I don't need to provide credentials for GitHub repos anymore.
![image](https://user-images.githubusercontent.com/17437789/44337321-96563e80-a47a-11e8-92dd-99dc3c797c65.png)

![image](https://user-images.githubusercontent.com/17437789/44337316-92c2b780-a47a-11e8-9c7e-87b21a34d56d.png)

**Comment by sandraros** [comment]
@christianguenter2 nice idea!
Here is a ready-to-use repository : https://github.com/sandraros/abapGit-user-exit-logon-by-rfc

**Comment by larshp** [comment]
@sandraros cool, we should include your example in the documentation, when it is written, see https://github.com/larshp/abapGit/issues/1853

**Comment by larshp** [comment]
exit method name = CREATE_HTTP_CLIENT
