### ISSUE TITLE
Impossible to save a dummy variant for background

### ISSUE THREAD

**Issue by sandraros** [larshp/abapGit#1843]
Ultimate goal: run ZABAPGIT in background, as explained in https://github.com/larshp/abapGit/blob/master/docs/guide-regular-backup.md

The issue is at step 9.

Symptom/to reproduce: run ZABAPGIT 
![image](https://user-images.githubusercontent.com/34005250/44311908-c60c3480-a3ef-11e8-9329-647159cf9231.png)

Click Save to create a variant:
![image](https://user-images.githubusercontent.com/34005250/44311810-69f4e080-a3ee-11e8-9116-79c8db8089bd.png)
In the screenshot above, is the beginning of the issue, as the variant screen is not displayed.

Anyway, try to Save the variant:
![image](https://user-images.githubusercontent.com/34005250/44311852-e982af80-a3ee-11e8-9b85-6248f64927ed.png)

Description must be entered, but it's impossible.

I also tried to create the variant with other standard possibilities, but no way.

**Comment by sandraros** [comment]
It must have worked one day, but with the latest version, impossible to make it work. Could somebody search the origin of the regression? Or maybe it's me, I don't know.

**Comment by sandraros** [comment]
I tried to find the origin but it seems to have worked this way (not worked) for years. So maybe it's not a bug but there's something obvious I didn't see.

**Comment by flaiker** [comment]
SE38 doesn't work for you? This screen?
![image](https://user-images.githubusercontent.com/5270359/44321860-b241ec00-a44a-11e8-93f1-fa68a9ffea1a.png)

It says to use SE38 to create the variant in step 9.
But if you can fix it so it is possible to just use the save button in the report I am all for it 👍

**Comment by larshp** [comment]
I also used SE38 previously

**Comment by sandraros** [comment]
Yes I have this screen, but then can you create it?
![image](https://user-images.githubusercontent.com/34005250/44328865-14a6e680-a463-11e8-9c3b-0a994fb97fa4.png)
Select all screens and Continue
![image](https://user-images.githubusercontent.com/34005250/44328919-4324c180-a463-11e8-8571-9257499a9082.png)
Back
![image](https://user-images.githubusercontent.com/34005250/44328943-59328200-a463-11e8-8805-b5797a0adaf3.png)
Yes
![image](https://user-images.githubusercontent.com/34005250/44328996-7cf5c800-a463-11e8-86d6-865a9d2e1fcf.png)
Save
![image](https://user-images.githubusercontent.com/34005250/44329004-84b56c80-a463-11e8-85d5-9a2e25fe040b.png)
Etc.

**Comment by christianguenter2** [comment]
Yeah it worked a while ago. I checkout out an old branch (roughly 3 months old) and there it works. So it seems that we broke this recently.

**Comment by flaiker** [comment]
Ah well, seems like I am not up to date then (sry @sandraros )
It still worked on 1.70.0, if that's any help.

**Comment by sandraros** [comment]
@flaiker I'm currious to see the screenshots at the time of 1.70.0 ? (i.e. what we should make it look like again)

**Comment by flaiker** [comment]
I updated my abapgit installer report to the latest build and did a comparison. The only things different is that there now is a horizontal scrollbar that is always visible and serves no purpose.

**Comment by christianguenter2** [comment]
I guess I found the root cause. If these lines are removed one can maintain the variant in SE38/SA38 again.
https://github.com/larshp/abapGit/blob/578640f84407bb420fef4eea4bba86dd8879b25b/src/zabapgit_forms.prog.abap#L129-L134

They were introduced with https://github.com/larshp/abapGit/commit/ff4d1268568f02e1d7ea5b9b46a4f0ad83517684

I think we can remove these lines and the focus method. I vaguely remember that the html control sometimes lost the focus, but I'm no longer able to reproduce it.

**Comment by larshp** [comment]
@sandraros try again, latest version

**Comment by sandraros** [comment]
@larshp It works as before now - not ideally though as it doesn't work from the SAVE button in ZABAPGIT main screen, only from SE38 + button Variants. Below is the way it works now, for future references.

Create the variant (here named "BACKGROUND"):

![image](https://user-images.githubusercontent.com/34005250/44509905-680f7380-a6b3-11e8-8e40-7816c64c4a62.png)
![image](https://user-images.githubusercontent.com/34005250/44509937-7e1d3400-a6b3-11e8-839d-48801db1bafd.png)
![image](https://user-images.githubusercontent.com/34005250/44509992-a7d65b00-a6b3-11e8-938b-13cca79d2161.png)
![image](https://user-images.githubusercontent.com/34005250/44510022-bfaddf00-a6b3-11e8-9534-2f32f65616ba.png)
![image](https://user-images.githubusercontent.com/34005250/44510055-d0f6eb80-a6b3-11e8-8c7c-0cf063bb6f37.png)
![image](https://user-images.githubusercontent.com/34005250/44510096-f126aa80-a6b3-11e8-8d80-3816d5d3f01d.png)
![image](https://user-images.githubusercontent.com/34005250/44510171-259a6680-a6b4-11e8-85da-efa87055e19a.png)

Then schedule the job periodically for program ZABAPGIT and variant BACKGROUND, with SE38 or SM36 as usually.
