### ISSUE TITLE
How to access the metadata-information on object creation

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#185]
with https://github.com/larshp/abapGit/commit/471901f9e4d8cd7fd7e123e95eed6c258bc9b63a, metadata-files are being created properly now (at least it seems).
What's missing is the interpretation of it.
Particularly interesting is the information about the serializer which created the file.
However, at the time of `lcl_objects=>create_object` there is no knowledge about the metadata.
While during `serialize`at least files are being injected, the information about the serializer cannot be retrieved at other point in time when it shall be instantiated (e. g. at `exists`).

My only idea is to propagate the files from the repo to `lcl_objects` at an early time and buffer it there. But that's not a brilliant solution.
@larshp you know your architecture better than myself, any suggestions?

**Comment by larshp** [comment]
yeah, one step at a time :smile: I haven't had much time lately, but I'll try to catch up tomorrow or Sunday. Need to get a better overview of the issues and what is important.

a: .abapgit files, so far I've envisioned this as one file per repository, much like https://github.com/larshp/abapGit/blob/master/.travis.yml or https://github.com/larshp/abaplint/blob/master/.npmignore or https://github.com/larshp/abaplint/blob/master/.gitignore files to keep top-level information about the repository. We need to get a proper issue created to make plans for what this file should contain. One thing which might be a good idea to place in this file is the MASTER_LANGUAGE. And before creating this file I'd like to add the "next generation XML"(issue to be created), so this file wont change format in the future.

b: we need somehow to distinguish if the object was serialized by a plugin or not. My idea so far have been to add an extra attribute in the XML files, the line
<abapGit version="v0.2-alpha">
could be
<abapGit version="v0.2-alpha" origin="plugin">
if it was serialized by a plugin, or better yet your approach by mentioning the class name
<abapGit version="v0.2-alpha" serializer="ZCL_SOMETHING_SERIALIZER">
I think this would be quite easy to access, as the XML file is the entry point for the object. It would also avoid having an extra file per object. I think we should just add the "serializer" tag for plugins, and leave the standard as is, that way most XML files wont change for already serialized objects.

I'll do some work tomorrow on getting the issues organized, and create a "Roadmap" issue for better overview.

**Comment by larshp** [comment]
closing this issue, moving to separate issues

a: see https://github.com/larshp/abapGit/issues/186

b: see https://github.com/larshp/abapGit/issues/187
