### ISSUE TITLE
Document Auth and User Exit

### ISSUE THREAD

**Issue by gregorwolf** [larshp/abapGit#1853]
Currently only the comments in [zabapgit.prog.abap#L35](https://github.com/larshp/abapGit/blob/52758028a7b08101e9c76d1cdab8639d776d3d2b/src/zabapgit.prog.abap#L35) document that abapGit has an exit to implement an authorization check and also one to adjust different behaviours like the creation of the HTTP Client (#1841). I think this functionality should be surfaced also in the documentation at http://docs.abapgit.org/.  A new topic "Auth and User Exit" below Reference could be the entry point.

**Comment by larshp** [comment]
started at http://docs.abapgit.org/ref-exits.html guess this issue can be closed, pull requests with further details welcome
