### ISSUE TITLE
Assertion failed blob data is initial

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#1857]
I am currently trying to commit ~4000 objects of a legacy code base, to keep track of the changes.

When pressing the commit button I get this shortdump:
![image](https://user-images.githubusercontent.com/5270359/44509787-f6372a00-a6b2-11e8-9244-76deb6845b2e.png)
ZCL_ABAPGIT_GIT_PORCELAIN->RECEIVE_PACK_PUSH

<ls_blob> referes to a mime object in the filename. The filename has a space in it ("file name.png"). Not sure if that's the issue.

**Comment by larshp** [comment]
try exporting the mime to files via "Advanced" -> "Object to files", perhaps the png file is empty

**Comment by flaiker** [comment]
Correct, it is empty.
Any idea how I can delete the object? I cannot find it in the mime repository or SMW0.

**Comment by larshp** [comment]
you can filter it out in the user exit

but I'd regard this as a bug in abapGit, it should be possible to have empty files

**Comment by flaiker** [comment]
Hmm, I cannot really reproduce it. It's only that one specific object. Maybe it was somehow not completely deleted so the object catalog entry is still there but the empty mime data is not.

**Comment by larshp** [comment]
closing
