### ISSUE TITLE
Horizontal scrollbar always visible

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#1858]
When I updated to the latest version, I noticed that now on the repository object list page there is horizontal scrollbar always visible. It lets you scroll to the right (where there is nothing of particular interest).
![image](https://user-images.githubusercontent.com/5270359/44510374-d43ea700-a6b4-11e8-950a-c1185d14a5e5.png)

Or is it just me?

**Comment by larshp** [comment]
heh, yeah, I also have it

**Comment by christianguenter2** [comment]
Root cause seems to be this: 

https://github.com/larshp/abapGit/blob/d28b0fdc978cf198fa21ec99cf73f2706b65a964/src/zabapgit_css_common.w3mi.data.css#L23-L25

Suggest to disable horizontal scrolling in body class. PR submitted.

**Comment by larshp** [comment]
with some long lines in ABAP, the horizontal scrollbar is needed on the diff page?

**Comment by christianguenter2** [comment]
AFAIS no. Long lines are wrapped.
![image](https://user-images.githubusercontent.com/17437789/44515705-8a10f200-a6c3-11e8-9bd9-58bd43bcb9a9.png)

**Comment by christianguenter2** [comment]
@flaiker can you try again with the latest build?

**Comment by flaiker** [comment]
It's fixed now. Thanks!
