### ISSUE TITLE
Merge mode layout not displaying correctly

### ISSUE THREAD

**Issue by patvo** [larshp/abapGit#1860]
In merge mode, the layout seems broken. Tested this in SAP GUI and Eclipse.

![2018-08-23 12_00_33-abapgit - merge mode](https://user-images.githubusercontent.com/35031904/44519630-d7925c80-a6cd-11e8-9526-f36b5dca728e.png)

**Comment by christianguenter2** [comment]
@patvo can you try again with the latest build?

**Comment by patvo** [comment]
@christianguenter2 

![merge_mode](https://user-images.githubusercontent.com/35031904/44720272-8ec01680-aac6-11e8-9451-0f598f10173f.png)

Works like a charm. Thanks. 😉
