### ISSUE TITLE
Abap 610 possible? 

### ISSUE THREAD

**Issue by Abapsocke** [larshp/abapGit#1861]
hi, is it possible to use abapGit on Release 610? 

I want to install Abap Git on a testing-playground of my company and i don't know if it's possible because i get some errors like "....long literals are not allowed..." and so on. 

i am not sure if i can get it to run properly but at least i want to try.

**Comment by larshp** [comment]
nope, version 702 required

**Comment by Abapsocke** [comment]
ok, thx maybe i can convince some People to upgrade the release ...:)

**Comment by larshp** [comment]
yeah, its quite difficult to downport it below 702

closing
