### ISSUE TITLE
Serialization of documentation longtexts

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1862]
We should also serialize the documentation longtexts of objects.
![image](https://user-images.githubusercontent.com/17437789/44591622-82824380-a7be-11e8-9978-484a8c41457c.png)

I think we should strive for a central logik as it seems that only the id is different for object types. Maybe we can add a new method GET_LONGTEXT_ID to interface ZIF_ABAPGIT_OBJECT or introduce an abstract method in ZCL_ABAPGIT_OBJECTS_SUPER which can be implemented on demand.

Or we can add some generic methods to ZCL_ABAPGIT_OBJECTS_SUPER which then can be called on demand by concrete object implementations.

FMs
DOCU_READ
DOCU_UPDATE
DOCU_DEL
similar to longtext handling in MSAG

**Comment by TobiasTroup** [comment]
Translation will not be considered.

**Comment by christianguenter2** [comment]
Yes, that's right. That is the next step we have to take. Does anybody have an idea how to access translations?

**Comment by TobiasTroup** [comment]
Christian,

There is a simple way to reveive installed languages.

Take a look at:

    cl_spfl_profile_parameter=>get_value(
      EXPORTING
        name        = |zcsa/installed_languages|
      IMPORTING
        value       = lv_param_value
    ).

    DATA(lv_len) = strlen( lv_param_value ).
    DO lv_len TIMES.
      lv_language_key = lv_param_value(1).
      SELECT SINGLE FROM t002t
        FIELDS *
      WHERE spras = @( cl_abap_syst=>get_language( ) )
        AND sprsl = @lv_language_key
          INTO @DATA(lw_t002t).
ENDDO.

Hosting variable needs to be replaced. You know. ;)

After receiving installed languages you need to take DOCU_UPDATED w/ founded languages.
That should it be.

**Comment by christianguenter2** [comment]
Thanks. Sounds reasonable. Didn't know that we can access the translations withs the same API.

**Comment by christianguenter2** [comment]
Seems to work. I submitted a pull request. 
@TobiasTroup feel free to test my PR.

**Comment by christianguenter2** [comment]
@TobiasTroup you can try latest build if you like.

**Comment by TobiasTroup** [comment]
I have already tested it. It is working.

**Comment by d023604** [comment]
Sorry its a little late - but the functions of the translation workbench SE63 are really useful here - because they also handle the object specific handling that takes place.  e,g 'LXE_OBJ_DOKU_GET_XSTRING'
