### ISSUE TITLE
Commiting a subset of changes fails in SAP GUI for Java

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#1866]
See screenshot below. Only one file is added to the commit stage area and an error message is raised.

Commiting all files (by just directly clicking on the commit button) is working.

Version: SAPGUI for Java 7.50rev4

![image](https://user-images.githubusercontent.com/2248490/44659115-7f16d400-a9d9-11e8-8838-f5213d66560b.png)

**Comment by jfilak** [comment]
It looks like that Java GUI does not pass POST data of generated form elements. I tried to create an empty auxiliary from:

```diff
--- a/src/ui/zcl_abapgit_gui_page_stage.clas.abap
+++ b/src/ui/zcl_abapgit_gui_page_stage.clas.abap
@@ -232,6 +232,10 @@ CLASS ZCL_ABAPGIT_GUI_PAGE_STAGE IMPLEMENTATION.
 
     ro_html->add( '</div>' ).
 
+    " auxiliary form for Java GUI
+    ro_html->add( '<form id="stage_form" method="post" class="repo" action="sapevent:stage_commit">' ).
+    ro_html->add( '</form>' ).
+
   ENDMETHOD.
```

and populated populated in the js code:

```diff
--- a/src/zabapgit_js_common.w3mi.data.js
+++ b/src/zabapgit_js_common.w3mi.data.js
@@ -61,10 +61,8 @@ function debugOutput(text, dstID) {
 
 // Create hidden form and submit with sapevent
 function submitSapeventForm(params, action, method) {
-  var form = document.createElement("form");
-  form.setAttribute("method", method || "post");
-  form.setAttribute("action", "sapevent:" + action);
-  
+  var form = document.getElementById("stage_form");
+
   for(var key in params) {
     var hiddenField = document.createElement("input");
     hiddenField.setAttribute("type", "hidden");
@@ -73,7 +71,6 @@ function submitSapeventForm(params, action, method) {
     form.appendChild(hiddenField);
   }
 
-  document.body.appendChild(form);
   form.submit();
 }
```

and it fixed the problem for me.

I need to create a patch which will not use the literal `stage_commit` in the function `submitSapeventForm`.

Any thoughts what is wrong with the generated form?

Any proposals how to create the auxiliary form? Should we change all pages to this pattern?

**Comment by jfilak** [comment]
Reported to SAP GUI for Java developers.

**Comment by marcellourbani** [comment]
I had a bit of a play.
the GET method does work fine.
And so does this horrible hack, at least on my arch linux box 
```
// Create hidden form and submit with sapevent
function submitSapeventForm(params, action, method) {

  var form = document.createElement("form");
  form.setAttribute("action", "sapevent:" + action);
  //hack for java sapgui. Perhaps we should quit and show a message when post explicitly asked?
  if (navigator.vendor.match('Apple'))
    form.setAttribute("method", "get");
  else
    form.setAttribute("method", method || "post");

  for (var key in params) {
    var hiddenField = document.createElement("input");
    hiddenField.setAttribute("type", "hidden");
    hiddenField.setAttribute("name", key);
    hiddenField.setAttribute("value", params[key]);
    form.appendChild(hiddenField);
  }

  document.body.appendChild(form);
  form.submit();

}
```

**Comment by marcellourbani** [comment]
not very good.

I tried this out here: https://github.com/marcellourbani/abapGit/tree/issue_%231866_%23790_hack_for_java_sapgui

but abapgit actually looks at postdata rather than a parsed query, so I needed a terrible hack in ABAP too. Which would also fail if the query is longer than 2048 char.

Later I will experiment with other ideas: this one kind of works but is a dead end

**Comment by marcellourbani** [comment]
Ok, I think I got it working reasonably well using @jfilak's method.
I did it in a more general way
Code is a mess and buggy though.

Would be nice if someone could confirm on a non linux client.

**Comment by larshp** [comment]
looking at the history I'm guessing this is solved?

**Comment by marcellourbani** [comment]
Yep, just retested to be sure
