### ISSUE TITLE
Serializer origin

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#187]
we need somehow to distinguish if the object was serialized by a plugin or not. My idea so far have been to add an extra attribute in the XML files, the line
``
 <abapGit version="v0.2-alpha"> 
``
could be
``
 <abapGit version="v0.2-alpha" origin="plugin"> 
``
if it was serialized by a plugin, or better yet your approach by mentioning the class name
``
 <abapGit version="v0.2-alpha" serializer="ZCL_SOMETHING_SERIALIZER"> 
``
I think this would be quite easy to access, as the XML file is the entry point for the object. It would also avoid having an extra file per object. I think we should just add the "serializer" tag for plugins, and leave the standard as is, that way most XML files wont change for already serialized objects.

**Comment by mrsimpson** [comment]
* I like the idea of adding it as attributes of the XML root. This way, it's file-specific and at the same time does not produce a separate file. I'd also allow the serializer to provide a version. There is some more meta-information which - in theory - might become relevant, such as minimum system requirements or similar. While a separate file provides more flexibility, it could also be represented as subnode of the XML.
* I'd also capture this information for local classes. Reasons:
** Common handling when instantiating the serializer (though the current derivation by class-name-concatenation has to be available as fallback anyway)
** I believe that when thinking of a productive use, it might happen that some local classes move to an external class. Having the serializer's name stored somewhere might be useful then
* The ideal place to add this information is during `add_xml`. Thus, it would also be closely related to #188 
* Still, I'd keep the `get_metadata` interface method. It could be consumed within the creation of the next gen xml

**Comment by larshp** [comment]
minimum system requirements: can go into the .abapgit file in the future, see https://github.com/larshp/abapGit/issues/125

serializer version: ideally yes, however I'm afraid that it will be difficult to explain the users and keep track of the versions. However I have thought about it, if going for semver(http://semver.org/) style versioning, the MAJOR version could be decided by abapGit, and the MINOR version by the serializer.

capture local clases: ok, common handling is good

add_xml: yes

get_metadata: I think we should remove it if its not needed at the moment, it can be added later if needed. I'm afraid to leave dead code which might not be removed in the future

**Comment by larshp** [comment]
serializer version: lets do it

it seems that getting #188 started is a good idea to get things moving, perhaps I'll start it up tomorrow in a new branch. It will not be merged into master until after 2 weeks, dont want to break too much up to #sitfra

Also there is a pull request approaching, https://twitter.com/VishnAndr/status/705078865094434817 but it should be quite straight forward to move to "next gen xml"

**Comment by mrsimpson** [comment]
> serializer version: ideally yes, however I'm afraid that it will be difficult to explain the users and keep track of the versions. 
I just bet that there will be usecases when the serializer version will be important. In a (quite far) future, you can imagine to have old versions of the serialized artifact but don't know which class in which version was needed in order to deserialize it.
This could be achieved by the infrastructure posting a serliazed version of the serializer's version in a central git-repo. When de-serializing, the same infrastructure could figure out that the installed version was not appropriate and find the proper one from the repo. Ok, this is quite far stretched, but I'm just dreaming...

I believe getting #188 done first is the right approach. Nevertheless, you might want to check the pro version in the branch I created due to the additional changes done, e. g. the non-binary-comparison which I believe to solve some other issues I had in the past. (https://github.com/larshp/abapGit/blob/metadata-files/zabapgit.prog.abap#L11105)

**Comment by larshp** [comment]
serializer versions: yes, lets do it

binary-comparision: I'm not sure that I understand the issue, if we run into it we can fix it. As far as I understand it is not directly related to the XML engine/setup. I think some of the later stuff will handle only-local/only-remote much better, as I've been thinking of saving the SHA1 hashes of the objects after a pull, this will give much better possibilities to figure out what has been changed.

**Comment by larshp** [comment]
fixed in latest release
