### ISSUE TITLE
MSAG: popup when deleting

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1878]
Steps to reproduce:
1: install https://github.com/abapGit-tests/MSAG_simple
2: uninstall

it shows following popup, expected: no popup
![image](https://user-images.githubusercontent.com/5888506/44783403-9943e400-ab8a-11e8-9654-86a93149aa64.png)

**Comment by marcellourbani** [comment]
I will pick this up

**Comment by larshp** [comment]
We cannot/should not do enhancements/changes to SAP standard code

**Comment by larshp** [comment]
can be closed, merged in above PR
