### ISSUE TITLE
Next generation XML

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#188]
In the current XML approach there are some issues see #176 #175, plus field names are not correct, would also like to provide just one method for adding data to an XML file.

Issues with current implementation:
- Top level names are not always correct
- Not possible to handle namespaces
- Multiple methods

### Suggested approach
See https://github.com/larshp/abapGit-NextGen-XML

2 classes, lcl_xml_input and lcl_xml_output, which both provide just a few methods to the serializers.

### Breaking everything
With commit https://github.com/larshp/abapGit/commit/93c8a7a0aebe8c72199e55c1696c6508743f3ade an error message will be shown if the XML version does not match the implementation. The user will be directed to https://github.com/larshp/abapGit/wiki/XML-Mismatch which will describe how to handle the situation.

**Comment by larshp** [comment]
An unforeseen improvement: values are externally formatted in the XML, eg timestamp is 22:10:10 instead of 221010 in the old approach

**Comment by mrsimpson** [comment]
There should be some more externally formatted data types. If I recall correctly, language is also transformed into ISO-format.

**Comment by larshp** [comment]
Okay, everything seems to be working now, see branch
https://github.com/larshp/abapGit/tree/next-gen-xml
a corresponding branch
https://github.com/larshp/abapGit-Unit-Test/tree/next-gen-xml
can be used for unit testing, and checking out the new format

I think the serializer origin and serializer version should be implemented before merging to master. No PRs or changes to master until this branch has been merged please.

### Format
discussed in https://github.com/larshp/abapGit/issues/187

though I dont like my previous suggestion to misuse the MINOR version for serializer versions, I think adding another version attribute is better, eg. something like

``
<abapGit version="v1.0.0" serializer="ZCL_SOMETHING_SERIALIZER" serializer_version="v1.0.0"> 
``

### Providing version
Add a method GET_VERSION in LIF_OBJECT which returns a string as version. Formatted as semver.org versions, default everything in zabapgit will start with "v1.0.0"

### Accessing/adding/checking attributes in XML files
I'm not sure how this can be handled the best way, will update this thread with ideas

**Comment by larshp** [comment]
### Scribblings

in LIF_OBJECT, add method GET_METADATA
	return structure with 2 string fields, serializer class name and serializer version

in lcl_objects_files add reference to lif_object as constructor parameter
	method add_xml pass the needed information to the xml render method
	method read_xml can similariy pass the information to check version

in LIF_OBJECT method DESERIALIZE
       new mandatory importing parameter lcl_xml_input
       this will allow for parsing the xml and checking the serializer version before it is passed to the serializer, in LCL_OBJECTS plus a lot of "lo_xml = mo_files->read_xml( )." can be omitted in the serializers

change method SERIALIZE to return a XML object? to make serialize and deserialize symmetric

**Comment by larshp** [comment]
and thats about it

note that it is possible to have both the old and new abapgit installed in a single system, eg ZABAPGIT and ZABAPGIT_OLD

still todo:
- [ ] more testing
- [ ] fix plugin bridge, I'm pretty sure I broke some of it but havent tested yet

before pushing to master:
- [ ] create git tag, so it is easy to fetch the old abapgit

**Comment by mrsimpson** [comment]
looks nice, though I still don't like the `create object lcl_xml...`

I can take care of the plugins.

**Comment by larshp** [comment]
create object lcl_xml..: which part, can you point to code line? perhaps we can do something else

**Comment by mrsimpson** [comment]
I just don't like to have each implementation instantiate it (from an architectural perspective).
E. g. unit testing would be easier if an instance of a factory for xml containers was injected into the serialize/deserialize

**Comment by larshp** [comment]
yes, something like:

https://github.com/larshp/abapGit/commit/bfca54b92bb9e6511b649bd9a9dee17a93aadd42
https://github.com/larshp/abapGit/commit/c77150739c510235c4acbfe551c5597dbeca3e0e

the xml object was added to both serialize and deserialize, so the interface is now:

``
INTERFACE lif_object.

  METHODS:
    serialize
      IMPORTING io_xml TYPE REF TO lcl_xml_output
      RAISING   lcx_exception,
    deserialize
      IMPORTING iv_package TYPE devclass
                io_xml     TYPE REF TO lcl_xml_input
      RAISING   lcx_exception,
``

**Comment by mrsimpson** [comment]
yup, looks nicer. Sorry, had a look at it earlier.
Though this assumes that there will be exactly one xml-file per plugin. But I guess that this is fair enough.
A bit tricky to encapsulate this nicely for the plugins though without having a typed interface though...

**Comment by larshp** [comment]
plugins: creating global classes for input and output, eg. ZCL_ABAPGIT_XML_INPUT will most likely work, but it is hard work

the old approach still works for adding multiple XML files, currently only FUGR adds multiple XML files, but I plan changing this so there is only one(task "FUGR serializer cleanup" in above checklist)

**Comment by mrsimpson** [comment]
anyway, multiple XMLs can easily be merged into one DOM tree, thus I said the assumption was fair
Give me some days to wrap that properly.

**Comment by larshp** [comment]
DOM tree: yes, I agree

**Comment by larshp** [comment]
I've fixed all the stuff on my todo list for next gen XML.

@mrsimpson is the plugins working okay? Anything else you'd like to add?

There are a lot of other things on the big todo list, but nothing IMHO that cannot be done after the PR is merged into master.

**Comment by mrsimpson** [comment]
Looks fine to me. Plugins are adapted. I'd like to see it merged soon. Might implement some of the other issues this evening, seems as if I've got some time then.

**Comment by larshp** [comment]
Been sick and busy at work. Will look into doing the merge as soon as possible(perhaps today or tomorrow)
