### ISSUE TITLE
OAuth2 for VSTS (visual studio team services)

### ISSUE THREAD

**Issue by sandraros** [larshp/abapGit#1882]
I'm trying to clone a Microsoft visualstudio.com Git repository, and I get a 401 Unauthorized HTTP status code. When I try with Chrome, no issue (not that it's for professional use, I'm entering my company email at Microsoft web site, so there's a temporary redirection to my company web site to enter my password).

Is it possible to use it from abapGit, or do you have tips so that I can implement it myself ?

It seems that Microsoft uses a OAuth2 connection. I knew absolutely nothing at all that auth stuff so bear with me. I have started to look at OAuth2 / Google Docs implementation by @ivanfemia (and converted his stuff to abapGit format in my own github https://github.com/sandraros/abap2oauth2 and https://github.com/sandraros/abap2gapps so you can easily download them at this place), but many things are to be changed so that to make it work.
I also saw that there are some standard OA2C* transactions to configure OAuth2 but I don't know how it works.

Thank you.

**Comment by larshp** [comment]
try using a personal access token, see https://docs.microsoft.com/en-us/vsts/repos/git/auth-overview?view=vsts

**Comment by sandraros** [comment]
Awesome, that works, thank you ! 👍 

So, it was not OAuth2 I guess.

1. Log in VSTS and add a Personal Access Token for my VSTS user. VSTS displays (once) a 52 characters "password" corresponding to this PAT.
2. Start ZABAPGIT and add the Git repository. At refresh it will display a popup with user + password. Enter the password of the PAT.

That's done.

If you use a private ABAP developer edition, you may automate the input of the password by adding this code in class ZCL_ABAP_USER_EXIT :

    CLASS zcl_abapgit_user_exit DEFINITION PUBLIC FINAL CREATE PUBLIC .
      PUBLIC SECTION.
        INTERFACES zif_abapgit_exit.
    ENDCLASS.
    CLASS zcl_abapgit_user_exit IMPLEMENTATION.
      METHOD zif_abapgit_exit~http_client.
        IF ii_client->request->get_header_field( name = '~request_uri' ) CP '*part-of-URI-query-string*'.
          ii_client->authenticate(
            EXPORTING
              username = 'your-VSTS-email'
              password = 'your-52-character-VSTS-PAT-password'
        ENDIF.
      ENDMETHOD.
    ENDCLASS.

One more question before I close the issue: do you think there is a way to store the password safely in SAP? (other than hardcoding it in the exit)

**Comment by larshp** [comment]
there is https://help.sap.com/viewer/280f016edb8049e998237fcbd80558e7/7.51.6/en-US/4eeb2dce10f2398de10000000a42189b.html

but note "For legal reasons, only SAP applications may use the secure storage. We therefore use technical measures to prevent the secure storage being used in customer developments"

**Comment by sandraros** [comment]
When SAP makes it so clear, I prefer not taking the risk !
Closing.
