### ISSUE TITLE
Code inspector results do not respect 'Jump to ADT first' setting

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#1892]
![sapguiserver_2018-09-05_13-17-35](https://user-images.githubusercontent.com/5097067/45089937-154fa600-b10e-11e8-936a-a7182cd5ae8f.png)

Clicking on an individual result should open the file in ADT if I have 'Jump to ADT first'  enabled.

**Comment by christianguenter2** [comment]
Yeah, code inspector jump code was adapted from SAP Standard. It has the advantage that it jumps to exact line of code. Our ADT jump just support object navigation afaik. That's why I didn't follow that path. But that's indeed something that we can improve. 

https://github.com/larshp/abapGit/blob/f0415a22fdeee6feda033dc539bad19c0cbac4e5/src/ui/zcl_abapgit_gui_page_code_insp.clas.abap#L155-L173

**Comment by FreHu** [comment]
AFAIK, this would make abapgit the only tool that can run a custom check variant and is properly integrated with ADT.

There's the "ABAP Test Cockpit With...", but it doesn't work on all systems:
![eclipse_2018-09-05_15-52-15](https://user-images.githubusercontent.com/5097067/45097802-f2c88780-b123-11e8-8ee2-ae7a496809be.png)

**Comment by christianguenter2** [comment]
@FreHu can you check the latest build? I think we can close then

**Comment by FreHu** [comment]
Is there any way to avoid having to go through this window each time?
![eclipse_2018-09-24_08-08-37](https://user-images.githubusercontent.com/5097067/45939229-3bf85280-bfd1-11e8-9e9e-e41b3f80ae0c.png)

Aside from that, the links now work correctly. Thanks!

**Comment by christianguenter2** [comment]
Hm, for me the window appears only the first time.

**Comment by bigld** [comment]
I don't even get this window!?

**Comment by FreHu** [comment]
I figured it out. The window only appears when jumping from a system not currently in your ADT project list. This is fine.

**Comment by larshp** [comment]
cool, can the issue be closed?

**Comment by FreHu** [comment]
Yep, closing. Thanks!
