### ISSUE TITLE
Question: How to deal with name clashes?

### ISSUE THREAD

**Issue by Safadurimo** [larshp/abapGit#1902]
Disclaimer: This is a question, if already answered, feel free to point me to the answer.

How do you deal with the issues, that names have to be unique within a system. If I understand it right, on pulling, abapgit checks if file will be overwritten and just asks if this is ok.
If I publish something, I don't want to clash with names the user might have already in their systems. How do I do that? Inventing a cyptic prefix like ZDQS for all development objects to minimize chances there is a name clash?

**Comment by larshp** [comment]
Yes, abapGit just asks if it is okay to overwrite if the object exists in an unexpected package

From an open source perspective, we do not know the names of the objects in the customer system. In the ABAP open source world, http://dotabap.org runs a check every night to see if there are name clashes in the open source projects listed, if found the build status turns red.

Typically at customers you also just choose a very specific naming to avoid clashes, so a prefix ZDQS will in most cases be okay

**Comment by larshp** [comment]
@Safadurimo did above help, can we close the issue?

**Comment by Safadurimo** [comment]
Yes, helped a lot, thank you.
