### ISSUE TITLE
Support for Object Type UDMO - Data model

### ISSUE THREAD

**Issue by d023604** [larshp/abapGit#1905]
Support for the serialisation and de-serialisation of the Data Modeller (Tx SD11) object types UMDO - Data Model,  UENO - Entity Type presently missing.  Whilst perhaps not the most commonly used objects, relatively simply objects to implement.

**Comment by d023604** [comment]
Happy to implement this by the way..

**Comment by larshp** [comment]
cool, never tried SD11 before 😄 

Perhaps open 2 issues, one for UMDO and one for UENO? Alternatively change the title of this issue

**Comment by larshp** [comment]
Name of the TADIR object type is UDMO instead of UMDO?

**Comment by d023604** [comment]
Correct - Object type is UDMO.

**Comment by d023604** [comment]
UDMO is undergoing testing. Support for the data model, language dependent descriptions and language dependent long texts. Shouldn't be too long now.

**Comment by larshp** [comment]
merged in https://github.com/larshp/abapGit/pull/1966 so I guess this can be closed
