### ISSUE TITLE
Support for Object Type UENO - Entity Type

### ISSUE THREAD

**Issue by d023604** [larshp/abapGit#1906]
Support for the serialisation and de-serialisation of the Data Modeller (Tx SD11) object types UMDO - Data Model, UENO - Entity Type presently missing. Whilst perhaps not the most commonly used objects, relatively simply objects to implement.

**Comment by d023604** [comment]
Happy also to implement - have started already.

**Comment by larshp** [comment]
@d023604 are you actively working on this? if not I will remove your assignment 😄

**Comment by d023604** [comment]
Hi Lars,

Thanks for the nudge. In short - maintain the assignment - and I will
complete it in the next week.

Regards
Andrew

**Comment by d023604** [comment]
Testing completed. Pull request shortly

**Comment by larshp** [comment]
merged in https://github.com/larshp/abapGit/pull/2911, closing
