### ISSUE TITLE
Dump in ZCL_ABAPGIT_BRANCH_OVERVIEW->DETERMINE_BRANCH (ASSERTIATION FAILED)

### ISSUE THREAD

**Issue by bigld** [larshp/abapGit#1909]
Some branch actions fail because off missing HEAD (using github)
![image](https://user-images.githubusercontent.com/4643389/45268300-2dab2200-b47a-11e8-87b4-8ff663e1e874.png)

Erro is in ZCL_ABAPGIT_GIT_BRANCH_LIST->PARSE_BRANCH_LIST

**Comment by bigld** [comment]
#1897

**Comment by bigld** [comment]
For bitbucket.org there is a different behaviour when changing repo (with LF) or refresh/branch action (w/o FL)!

**Comment by christianguenter2** [comment]
I can also reproduce it with my bitbucket repos

**Comment by bigld** [comment]
It' working for me now with branches and tags on github and bitbucket
@christianguenter2 is it working for you, too? I'll close the issue then.

**Comment by christianguenter2** [comment]
Yes, it's working.
