### ISSUE TITLE
Provide "installation"-option: Get recent ABAPGit and Plugins

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#191]
When ABAPGit has been copied to the system, a more recent version might be available.
Implement a feature to
* Clone the ABAPGit repository
* Clone the ABAPGit plugins repository
* Pull both of them

**Comment by larshp** [comment]
Also option to skip this step, as the system might not have direct access to the big internet

**Comment by mrsimpson** [comment]
I started implementing it as an option in the menu which can be triggered anytime. 
Might implement some hiding-logic

**Comment by larshp** [comment]
I think its okay just to have it as an option. Just wanted to make sure it is not a mandatory step

**Comment by mrsimpson** [comment]
added conditional hiding. Systems without internet-connection should not even be presented the installation option (not tested though)
