### ISSUE TITLE
Syntax error in ZCL_ABAPGIT_BRANCH_OVERVIEW (only < 7.40 SP02)

### ISSUE THREAD

**Issue by patvo** [larshp/abapGit#1914]
Getting a syntax error in ZCL_ABAPGIT_BRANCH_OVERVIEW ( Line 59:    METHODS _get_1st_child_commit ) only on our 731 SP7 machine. 
751 SP2 machine doesn't show any errors.

**Comment by patvo** [comment]
Error message:
> Method _GET_1ST_CHILD_COMMIT may not have a RETURNING parameter and an EXPORTING or CHANGING parameter at the same time. time.

Seems like 731 can't handle this. Maybe this is related:
https://help.sap.com/saphelp_nw70ehp2/helpdata/en/08/d27c03b81011d194f60000e8353423/content.htm?no_cache=true

> This is suitable for methods that return a single output value.

**Comment by larshp** [comment]
@patvo try again, latest version

**Comment by patvo** [comment]
Solved.
