### ISSUE TITLE
Syntax error ZCL_ABAPGIT_GUI_PAGE_BKG after doing pull

### ISSUE THREAD

**Issue by irodrigob** [larshp/abapGit#1919]
Hi,

Today after doing pull of project, i have the next DUMP:

" The current ABAP program "ZCL_ABAPGIT_HOTKEYS===========CP" had to be
  terminated because it found a
 statement that could not be executed.
 In include "ZCL_ABAPGIT_GUI_PAGE_BKG======CM007     ", in line 3 of program
  "ZCL_ABAPGIT_GUI_PAGE_BKG======CP        ", the following syntax errors
 have occurred:
 Type "TY_METHODS_TT" is unknown."

The dumps ocurrs when i execute the transaction ZABAPGIT. When i actived the object after pull there was no error.

How i can fix the problem? Because i can't the execute the transaction for another pull.

Thank you
Iván

**Comment by larshp** [comment]
cool, 👍 closing
