### ISSUE TITLE
ABAP Doc not in sync

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#1924]
752 has some new syntax checks 👍 

![image](https://user-images.githubusercontent.com/5270359/45584935-50a35f00-b8dc-11e8-8bd8-76fb4acedfd6.png)
![image](https://user-images.githubusercontent.com/5270359/45584939-5ac55d80-b8dc-11e8-8840-cc323462bd34.png)

**Comment by larshp** [comment]
yeah, implemented as custom check on lower versions via http://docs.abapopenchecks.org/checks/63/
