### ISSUE TITLE
FORM: No object not recorded in transport request

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1933]
When deserializing a SAPscript form (object type FORM)  the object isn't recorded to a transport request.
Demo repo
https://gitlab.com/christianguenter/test_sapscript.git

**Comment by larshp** [comment]
cool, please create a test repo for FORM undre https://github.com/abapGit-tests

**Comment by christianguenter2** [comment]
https://github.com/abapGit-tests/FORM
