### ISSUE TITLE
Short dump SAP CRM CX_SY_DYNAMIC_OSQL_SEMANTICS on ABAPGIT execution

### ISSUE THREAD

**Issue by frestegil** [larshp/abapGit#1937]
Hello,

I have installed ABAPGIT on a SAP CRM (SAP CRM 7.0 SP18, Netweaver 750 SP6), and on execution, I have the following dump issue: CX_SY_DYNAMIC_OSQL_SEMANTICS on execution of READ method of class:
zcl_abapgit_persistence_db
line 33491:     
` SELECT SINGLE data_str FROM (c_tabname) INTO rv_data       WHERE type = iv_type       AND value = iv_value.   `

I'm not having the error on my SAP TM (which is as well on Netweaver 750 SP6).

8 METHOD       ZABAPGIT                            ZABAPGIT                            33491 ZCL_ABAPGIT_PERSISTENCE_DB=>READ
7 METHOD       ZABAPGIT                            ZABAPGIT                            33804
  ZCL_ABAPGIT_PERSIST_MIGRATE=>READ_GLOBAL_SETTINGS_XML
6 METHOD       ZABAPGIT                            ZABAPGIT                            33647
  ZCL_ABAPGIT_PERSIST_MIGRATE=>GET_GLOBAL_SETTINGS_DOCUMENT
5 METHOD       ZABAPGIT                            ZABAPGIT                            33772
  ZCL_ABAPGIT_PERSIST_MIGRATE=>MIGRATE_SETTINGS
4 METHOD       ZABAPGIT                            ZABAPGIT                            33819
  ZCL_ABAPGIT_PERSIST_MIGRATE=>RUN
3 METHOD       ZABAPGIT                            ZABAPGIT                            16407
  ZCL_ABAPGIT_MIGRATIONS=>RUN
2 FORM         ZABAPGIT                            ZABAPGIT                            62667
  RUN
1 EVENT        ZABAPGIT                            ZABAPGIT                            62803
  START-OF-SELECTION

Category               ABAP programming error
Runtime Errors         SAPSQL_PARSE_ERROR
Except.                CX_SY_DYNAMIC_OSQL_SEMANTICS
ABAP Program           ZABAPGIT
Application Component  Not assigned
Date and Time          20.09.2018 10:29:34

Have you encountered the issue before?

Thanks & best regards,

Frederic Mounier

**Comment by christianguenter2** [comment]
Does DB table ZABAPGIT exists?

**Comment by frestegil** [comment]
Hello Christian, 
Table ZABAPGIT was created but not active. I activated and now it works fine.
Thanks a lot.

Best regards,
Frédéric
