### ISSUE TITLE
UI: 2 step ZIP import - to view diffs on import

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#1950]
Import ZIP is a black box now. Proposal: to make it 2 steps
1. Import and see diffs
2. Apply changes

Example after import:

![image](https://user-images.githubusercontent.com/15635498/45941135-6c49ec00-bfe5-11e8-9cf0-f00498dc60db.png)

**Comment by sbcgua** [comment]
yeap, this will close 816. One point: do you think that **file** view is needed ? I wasn't going to show files in offline initially. But indeed should not be difficult. I'll PR this week.

**Comment by sbcgua** [comment]
One more point. I added `has_remote`, `status` and `reset_remote` to base repo class - https://github.com/sbcgua/abapGit/commit/e0f88c71af48317ae8a2f982de38de8ea98d41e5#diff-86243fe7bed62c7e0c920cd3dc73ca08R369. Though having some doubts about proper semantics - any opinions about it? last 2 methods are then redefined in online implementation.

**Comment by sbcgua** [comment]
Closing then. Delivered

**Comment by larshp** [comment]
not merged yet, will merge later today/tomorrow, leaving a chance for more people to test it

**Comment by sbcgua** [comment]
ok, rushed a bit. let's leave it open then for the moment
