### ISSUE TITLE
Sequence definition of import for offline project

### ISSUE THREAD

**Issue by VishnAndr** [larshp/abapGit#196]
Any ideas how should it be handled?
For example dynpros should be created only after ddic objects. The same applies for TOBJ (relevant tables should already exist).

**Comment by larshp** [comment]
it can be added in METHOD prioritize_deser CLASS lcl_objects. 

Both offline and online projects should hit this method

**Comment by larshp** [comment]
@VishnAndr did it work out for you? can we close the issue?
