### ISSUE TITLE
Dump on assert rv_user is not initial in zcl_abapgit_objects->changed_by

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#1960]
sometimes there are objects without user who updated it. In this case `zcl_abapgit_objects->changed_by` dumps at assert.

Proposal: to override empty `rv_user` with 'unknown' instead of assert

**Comment by larshp** [comment]
Suggest identifying the objects which give the wrong changed_by, and fix the corresponding changed_by methods

**Comment by sbcgua** [comment]
it was not a problem of wrong identification. It was actually empty field in the DB (for a couple of classes). Not sure how it happened ... So I think the logic should be changed to "fallback" - if not found, then "unknown"
