### ISSUE TITLE
syntax error on in class zcl_abapgit_object_suso on SAP_BASIS 702.20 systems

### ISSUE THREAD

**Issue by goot1** [larshp/abapGit#1970]
class cl_suso_gen not available on  SAP_BASIS 702 SP 20  systems.

**Comment by christianguenter2** [comment]
Is the function module SUSR_DELETE_OBJECT available? If yes, can you post its content?

**Comment by christianguenter2** [comment]
@goot1 sytax error should be gone in the latest build, can you try? Please notice that SUSO objects currently will cause shortdumps in 702. 
Can you provide some information how SUSO objects are deleted in 702? E.g. examine above mentioned function module?

**Comment by goot1** [comment]
@christianguenter2:  year it compiles now on 702.

**Comment by goot1** [comment]
Hi,
this is the coding from SUSR_DELETE_OBJECT in a 702 System

FUNCTION SUSR_DELETE_OBJECT.
*"----------------------------------------------------------------------
*"*"Lokale Schnittstelle:
*"       IMPORTING
*"             VALUE(OBJECT) LIKE  TOBJ-OBJCT DEFAULT 'S_TEST'
*"             VALUE(EU_MODE) LIKE  SMENSAPNEW-CUSTOMIZED
*"                             DEFAULT SPACE
*"       EXPORTING
*"             VALUE(OBJECT) LIKE  TOBJ-OBJCT
*"----------------------------------------------------------------------
  DATA: ld_flag TYPE c.
*-----------------------------------------------------------------------

  IF eu_mode = abap_true.
    PERFORM check_object_name_and_popup CHANGING object
                                                ld_flag.
    IF ld_flag = abap_true.
      RETURN.
    ENDIF.
  ENDIF.
  PERFORM delete_object USING object.

ENDFUNCTION.

*&---------------------------------------------------------------------*
*&      Form  CHECK_OBJECT_NAME_AND_SEND_POP
*&---------------------------------------------------------------------*
FORM check_object_name_and_popup CHANGING pv_object TYPE xuobject
                                          pv_exit   TYPE tv_c1.
  DATA:
    lv_dummy TYPE xuobject.
*-----------------------------------------------------------------------
  pv_exit = space.

  IF pv_object = space.
    CALL FUNCTION 'PRGN_SELECT_ONE_AUTH_OBJECT'
      IMPORTING
        object           = pv_object
      EXCEPTIONS
        no_data_selected = 1
        OTHERS           = 2.
    IF sy-subrc <> 0.
      MESSAGE s319(s#).
      pv_exit = gc_cross.
    ENDIF.
  ENDIF.

  SELECT SINGLE objct FROM tobj
    INTO lv_dummy
    WHERE objct = pv_object.
  IF sy-subrc <> 0.
    MESSAGE i308(s#) WITH pv_object.
    pv_exit = gc_cross.
  ENDIF.

ENDFORM.                    "check_object_name_and_popup

FORM delete_object USING pv_object TYPE xuobject.
  DATA:
    lv_return     TYPE i,
    lv_sap_system TYPE c,
    lv_ret_tx     TYPE tv_c1.
*----------------------------------------------------------------------
  CALL FUNCTION 'PRGN_CHECK_SYSTEM_TYPE'
    EXCEPTIONS
      sap_system = 1
      OTHERS     = 2.
  IF sy-subrc = 0.
    CLEAR: gs_suso-sap_system.
  ELSE.
    gs_suso-sap_system  = gc_true.
  ENDIF.

  lv_sap_system = 'U'.
  gs_suso-navi_mode = gc_nav_del.         "activity: delete object

  PERFORM suso_check_authority USING pv_object
                                     gs_suso-navi_mode
                            CHANGING lv_return.
  IF lv_return <> 0.
    RETURN.
  ENDIF.

  PERFORM suso_check_system_swl USING pv_object
                                      gs_suso-navi_mode
                                      lv_return.
  IF gs_suso-navi_mode <> gc_nav_del OR lv_return <> 0.
    RETURN.
  ENDIF.

  PERFORM suso_check_name_space USING pv_object
                             CHANGING lv_sap_system
                                      lv_return.
  IF lv_return <> 0.
    RETURN.
  ENDIF.

  PERFORM suso_where_used USING pv_object
                                'D'    "deletion mode
                       CHANGING lv_return.
  IF lv_return <> 0.
    RETURN.
  ENDIF.

  PERFORM susa_popup_for_decision USING 'DELE'
                               CHANGING lv_ret_tx.
  IF lv_ret_tx <> space.
    RETURN.
  ENDIF.

* if all checks was succesfull we can do the update w/o
* further dialogs
  PERFORM suso_db_update USING pv_object
                               gs_suso-navi_mode
                      CHANGING lv_return.

  IF lv_return IS INITIAL.
    CALL FUNCTION 'RS_TREE_OBJECT_PLACEMENT'
      EXPORTING
        object    = pv_object
        type      = 'SUSO'
        operation = 'DELETE'.
  ELSE.
    CLEAR pv_object.
  ENDIF.

ENDFORM.                    "DELETE_OBJECT

Do you need more on the delete_object  form?

**Comment by christianguenter2** [comment]
@goot1 Thanks, form rountine suso_db_update would be helpfull. As it probably contains the main delete logic.

**Comment by goot1** [comment]
@christianguenter2  These forms also references other forms. - I attached the completed Include now. 

[Include_LSUSAF01.txt](https://github.com/larshp/abapGit/files/2445322/Include_LSUSAF01.txt)

**Comment by christianguenter2** [comment]
@goot1 thanks. I'd try another solution and created a PR. As soon as it is merged it would be great if you can test it in your 702 system.

**Comment by christianguenter2** [comment]
@goot1 can you try to install and uninstall the SUSO demo repo on 702 with the latest abapGit build?
https://github.com/abapGit-tests/SUSO.git

**Comment by larshp** [comment]
@goot1

**Comment by christianguenter2** [comment]
I assume it's working.
