### ISSUE TITLE
IDOC/IEXT Segment type definition missing

### ISSUE THREAD

**Issue by bigld** [larshp/abapGit#1989]
IDoc Segement Type definition is missing (Tx WE31).
Segment types are defined via this tables:
EDISDEF
EDISEGMENT
EDSAPPL

Customer namespace for segment types SHOULD be Z1* but Z/Y* is also possible!

there is also an structure with the same name (TADIR entry: R3TR/TABL/<TYPENAME> and GENFLAG = ABAP_FALSE and EDTFLAG = ABAP_TRUE)

Should we check one of the above tables for evere structure in an package?

FMs:
SEGMENT_DELETE
SEGMENT_CREATE_CHECK
SEGMENT_CREATE
SEGMENT_MODIFY
SEGMENTDEFINITION_DELETE
SEGMENTDEFINITION_MODIFY

**Comment by larshp** [comment]
@bigld

**Comment by bigld** [comment]
closing
