### ISSUE TITLE
W3MI, W3HT - Web Reporting/Internet MIME types support

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#199]
Hi Lars,
I would like to contribute with the subj objects support if you don't mind. I'm using them in my project and probably can be useful for someone else. Will send the (first) merge request in a moment.

In the meanwhile i've got 2 questions as I'm not familiar with the code enough:
1. W3 objects have params - it is a table so there may be any number of params (although I didn't see more than 5 standard in real life). How to serialize them better ? I didn't find a way to create deep xml in your XML class (like `<params><param name="abcde">value1</param1></params>` or similar)

![image](https://cloud.githubusercontent.com/assets/15635498/13964629/4789f0de-f073-11e5-88f3-d4debc2dbb79.png)

2. I'm a bit confused with TADIR handling. Is a `lcl_object*` class responsible for it's update ? In my current code I add a record there via `TR_TADIR_INTERFACE`. Not sure it is is correct, but WWW* FMs I use do not do that

Would appreciate comments on this.

**Comment by larshp** [comment]
PARAMS: the xml ADD and READ methods works on complex structures

TADIR: yes, the lcl_object_* classes are responsible for the updates. Your approach is correct. Problem is that some of the API calls for other objects manages the updates, so it cannot be handled generically.

**Comment by larshp** [comment]
closed via PR https://github.com/larshp/abapGit/pull/200
