### ISSUE TITLE
Improve error analysis with actions for zcx_abapgit_exception=>raise

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1998]
In the abapGit code base lots of exceptions are raised with `zcx_abapgit_exception=>raise`. The problem is that no further information than the error message is provided and error analysis always require debugging and fiddling around until you find the position where the error is raised. 
I'd like to improve this procedure and provide some additional actions to shorten root cause analysis.

I did a small [prototype](https://github.com/christianguenter2/abapGit/tree/more_exception_information) where I added a longtext which contains two actions.

When a message raised with `zcx_abapgit_exception=>raise` appears you can click on it and in the longtext view on the bottom you see actions 'Go to source' and 'Callstack'
![image](https://user-images.githubusercontent.com/17437789/46818756-47de6580-cd82-11e8-9994-1b12ecf1fc31.png)

![image](https://user-images.githubusercontent.com/17437789/46818877-8d029780-cd82-11e8-83f6-eae9c2973088.png)

'Go to source' jumps directly to the position where `raise` is called.
![image](https://user-images.githubusercontent.com/17437789/46819898-2af76180-cd85-11e8-9ea7-df983086e002.png)

'Callstack' shows a popup with the callstack when `raise` is called and you can navigate to the source of each entry.
![image](https://user-images.githubusercontent.com/17437789/46819029-f7b3d300-cd82-11e8-9485-6a927bf2c9da.png)

The whole thing is based on a custom message class and message and two new transactions. Which means that this feature will only be available in installed abapGit repositories. Also is the implementation quite hacky.

I work with this feature enabled since a few days and for me it's quite helpful. 
Any opinions? Should we consider this?

**Comment by flaiker** [comment]
Very interesting. The problem with static raise methods in exception classes is always that the goto raise location debugger function doesn't help anymore.
Replacing =>raise with RAISE EXCEPTION TYPE... would already help that. But of course your solution is more user friendly as it does not require debugging. 👍 

Another approach: At work we have an exception library that logs the import parameters and callstack in the constructor for any exception inheriting from /.../cx...internal_error to a trace db table using a secondary database connection. SYSTEM_CALLSTACK sometimes returns ??? in some fields by the way (mostly INCLUDE).

**Comment by mfsap** [comment]
My (initial) approach in #2759 was just the re-definition of default method GET_SOURCE_POSITION by providing the "correct" line of code where the raise is triggered. The topics discussed here are more sophisticated and I the approach of Christian. If there is any progress here? If yes, I'll not continue with #2759 ...

**Comment by FreHu** [comment]
@mfsap I would still be interested on what this redefinition looks like. I'd potentially use it in my own code.

**Comment by mfsap** [comment]
@FreHu My idea was: 
1. read the callstack in the constructor of `ZCX_ABAPGIT_EXCEPTION` and keep program/include/line from the "last call before `ZCX_ABAPGIT_EXCEPTION`"
2. re-define method `CX_ROOT->GET_SOURCE_POSITION()` and return the kept program/include/line

**Comment by christianguenter2** [comment]
Yeah, forgot about this. I think it would improve error handling analysis in abapGit tremendously. Submitted a PR. Let's see.

**Comment by christianguenter2** [comment]
Follow up issue #2811.
