### ISSUE TITLE
Repo link does not work from staging screen

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2005]
Reproduced on version 1.78.

The repo link works correctly from the home screen:
<img width="334" alt="sapguiserver_2018-10-16_14-11-27" src="https://user-images.githubusercontent.com/5097067/47015525-7b880980-d14d-11e8-9fc6-b95557a50bba.png">

For the staging and commit screens, an error message is shown:
<img width="443" alt="sapguiserver_2018-10-16_14-14-06" src="https://user-images.githubusercontent.com/5097067/47015616-c0ac3b80-d14d-11e8-8e33-c665beb614b1.png">
<img width="137" alt="sapguiserver_2018-10-16_14-13-15" src="https://user-images.githubusercontent.com/5097067/47015573-a1ada980-d14d-11e8-8e46-d0155f1c4f69.png">

I tried copying the urls and they all point to the same address. Tried with other repositories as well with the same result.

**Comment by FreHu** [comment]
This seems to be caused by a rejected PR which we have in our downstream version:
https://github.com/larshp/abapGit/pull/1932

Closing.

**Comment by filak-sap** [comment]
@FreHu  is right! I broke abapGit in our system because I deploy abapGit with a local patch enabling SAP GUI for JAVA:
https://github.com/filak-sap/abapGit/commit/5556c53d396deee1fbcaf4237fc37e9e7bb628ea

Notice the version 2 comment.

Sorry about the noise.
