### ISSUE TITLE
Design: icon suggestions

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#201]
Hi Lars,

I thought that abapgit maybe should have a customized icon so here are some suggestions (attached) :)
Icon is (obviously ;) based on original git logo.

License considerations: icon seems to be [published under CC](https://git-scm.com/downloads/logos) so looks ok to use.

> This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of the CC licenses offered. Recommended for maximum dissemination and use of licensed materials.

Personally I like:
- the first column, mostly 1 and 3 but 3 is rather tall (so might not fit the page layout well)
- abapgit version where abap is regular and git is bold (as in original) 
- colors ... not sure, for a logo probably red is nicer

P.S. Git logo at the bottom is for reference

![logoall](https://cloud.githubusercontent.com/assets/15635498/14233291/019b44a2-f9cd-11e5-9a52-433d0f9d106a.png)

**Comment by larshp** [comment]
Lets just try, guess column 3 row 3 will fit nicely into the top left part. Can you do one with transparent background and uppercase "G" in git?

![image](https://cloud.githubusercontent.com/assets/5888506/14821034/70d7989e-0bc9-11e6-863c-e00f2bc6345d.png)

**Comment by sbcgua** [comment]
![logo_abapgit_capital](https://cloud.githubusercontent.com/assets/15635498/14831786/d3821d08-0bff-11e6-9b6c-650ecb40d17d.png) - 40x163 (optimal imho)

Vector: [logo_abapgit_capital_opt_svg.zip](https://github.com/larshp/abapGit/files/237333/logo_abapgit_capital_opt_svg.zip)

P.S. I'll answer for 202 tomorrow (briefly: working on it)

**Comment by larshp** [comment]
cool, will probably look into it later today

just take your time

**Comment by larshp** [comment]
closed with https://github.com/larshp/abapGit/commit/5dc3b7722303eb01937039ff81e61754327f0762

**Comment by larshp** [comment]
@sbcgua do you remember which font was used? I would like to create a similar svg file, but with "abapGitServer" instead of "abapGit"

**Comment by sbcgua** [comment]
It called Adelle if I remember well

**Comment by larshp** [comment]
thanks, @sbcgua also see private message on LinkedIn
