### ISSUE TITLE
SSFO: ABAP source formatting is lost during deserialization

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2011]
![image](https://user-images.githubusercontent.com/17437789/47170976-d7968d80-d307-11e8-982c-030209505a3b.png)

This doesn't happen with the SMARTFORMS up- and download mechanism.
It seems that it's lost somewhere in abapGit xml handling.

ZCL_ABAPGIT_OBJECTS_FILES READ_XML
![image](https://user-images.githubusercontent.com/17437789/47171680-9c955980-d309-11e8-9672-2cb667cb1cc1.png)
![image](https://user-images.githubusercontent.com/17437789/47171708-b898fb00-d309-11e8-9d71-15d9fad6ae57.png)

**Comment by larshp** [comment]
the XML is normalized so the spaces are removed, in other places, the number of preceding spaces is moved to a different tag

**Comment by bigld** [comment]
we could set the number of leading spaces as attribute in the item node of coding and put them back during serialization?

   <item abapgit-leadig-spaces="7">       FROM t000</item>

**Comment by larshp** [comment]
yes

**Comment by christianguenter2** [comment]
Thanks @bigld . Closing.
