### ISSUE TITLE
[Suggestion] Show failing unit test message in code inspector results

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2013]
If your inspection variant includes running unit tests, a failing unit test just says 'Critical Alert':
<img width="585" alt="sapguiserver_2018-10-19_09-34-37" src="https://user-images.githubusercontent.com/5097067/47203933-3567bb80-d382-11e8-9af9-9df632aad414.png">

We can see in the result of `zcl_abapgit_repo->run_code_inspector` that in this case, a much better message exists in `scir_alvlist-param1`, which either states the failed assert or the assert's msg paramter.
<img width="401" alt="2018-10-19_09-32-40" src="https://user-images.githubusercontent.com/5097067/47204129-d6567680-d382-11e8-8926-67586becb2c9.png">

**Comment by christianguenter2** [comment]
Im my test case the right message is shown and  `test` and `param1` are the same.

![image](https://user-images.githubusercontent.com/17437789/47209041-acf01780-d38f-11e8-85e6-d0b89929c4ee.png)

![image](https://user-images.githubusercontent.com/17437789/47209161-f6d8fd80-d38f-11e8-96eb-f9b4eb2d9192.png)

![image](https://user-images.githubusercontent.com/17437789/47208999-921da300-d38f-11e8-8723-f91d94c41910.png)

How can we decide when to use `param1` instead of `test`? Always? How does your unit test look like?

**Comment by FreHu** [comment]
I also tried a simple assert_fail originally, strange. Could it be that my variant is set up differently from yours? I only know about this option:

<img width="515" alt="sapguiserver_2018-10-19_12-55-53" src="https://user-images.githubusercontent.com/5097067/47214473-54744680-d39e-11e8-82e0-f34b37c2cb75.png">

Looks like even my SCI results just show _critical alert_ :
<img width="917" alt="sapguiserver_2018-10-19_13-00-06" src="https://user-images.githubusercontent.com/5097067/47214651-eb410300-d39e-11e8-8214-579993db5029.png">

**Comment by christianguenter2** [comment]
Variant is the same. SCI results looks like this.
![image](https://user-images.githubusercontent.com/17437789/47223864-8abfbf00-d3ba-11e8-8f10-cd293c41b9be.png)

**Comment by FreHu** [comment]
It seems that since SCI is returning wrong results as well, this may be system-related. I'll investigate on monday.

**Comment by FreHu** [comment]
Indeed, on a different system I get the correct message in SCI, so this is not abapgit related.
<img width="869" alt="saplogon_2018-11-21_12-38-21" src="https://user-images.githubusercontent.com/5097067/48839027-717bab00-ed8a-11e8-8424-04b3d2a775cc.png">

**Comment by FreHu** [comment]
Apparently this was a year-old regression bug nobody has bothered to report since...
