### ISSUE TITLE
Design & usability

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#202]
Hi Lars,

I have some suggestion on improving design and usability. Probably they are subjects for several issues but I'll start from this one. I intended to make some draft code during the weekend but managed only html draft. Please find attached (clickable for more resolution). It would be great to hear you thought on that :)

![2016-04-03_18h36_47](https://cloud.githubusercontent.com/assets/15635498/14233305/61cd86aa-f9cd-11e5-8725-136b1db0868c.png)

I didn't go far for the design, it is highly ispired by github. Design is mostly build on CSS rather than inline styles. It works on IE10 (it is in the screenshot in fact)  Below are some comments/questions:

1. Refresh/Refresh All - this is more a usability issue (actually separate one) - if I have a private repo (or more than 1 !!!) it asks all the passwords at the beginning. Very inconvenient. I'd suggest skipping automatic repo update or skipping private repos update and initiating then after explicit "refresh" for a repo or global "Refresh all"

2. Link to ZABAPGIT repo is moved to the logo block

3. Top menu: I have some doubts about "Explore" link - it shows a bit limited list of packages (even not complete list of your packages) - what is it designed to do ? Also not quite got the logic of "Install" link - could you please clarify.

4. Each repo has it's div, icon before name differenciate online/offline projects. 

5. After, a set of attributes go. The link to brach in particular can be later converted to actually branch switcher.

6. Repo toolbar - all commands are here, may differ for on/offline, commit links will also be here.

7. Table header ... is it needed ? It seems all columns are quite obvious. I'd suggest removing.

8. Object list. different icons can be set for differents kind of objects (I'd say "code", "non-code", "binary" should be enough - see second repo in the screenshot). Irrelevant files are greyed out. "Path" is merged with file name, it may have different style to be more visible. btw do you plan to develop some path features? :) E.g. saving to another path than the root folder.

9. What does "e" at the bottom means ? =)

looking forward for your comment :)
kr, alex

P.S. Link to [octicons](http://fa2png.io/r/octicons/)

**Comment by larshp** [comment]
looks really cool! Very little effort has been put into making it look nice.

The html container runs in IE quirks mode, so we have to test that the stuff works there. Plus it has to be a single HTML file, without linking to external files. It would also be nice to have the icons/font embedded somehow, not sure how it works now. Perhaps you can upload the example to a github repository?

1. Can we move this to a separate issue? I like the idea, lets see how it can work out. Also see #45

9. Its a "secret" method to export a package to zip file, without having to create the offline project. I use it for testing. Its not documented anywhere, thats also why it currently has a color almost matching the background so its difficult to find :smile:

**Comment by sbcgua** [comment]
Everything is embeded :). The file can be found [here](https://github.com/sbcgua/TestRep1/blob/master/index_complete.html). But this is really a draft. There are much to improve, at least optimize css, and adjust right alignment of toolbars right to logo and repo-names. (link hrefs are dummy too just in case).

IE in SAP. I was sure it was using host IE. But ... it does restrict it somehow ... some stuff to fix indeed, layout broke (especially those right-aligned toolbars). :( Still most things work. (it is direct file upload, not code generated yet just in case).

![2016-04-04_22h13_09](https://cloud.githubusercontent.com/assets/15635498/14260466/51e5915a-fab4-11e5-8f7c-1be6e357f927.png)

1) Done -> 203
9) ok ... :)

Could you please also comment 3 and 7? 

P.S. thinking about cleaner implementation: does abap702 supports string definition like `teststr = |Line1\nLine2|.` ?

**Comment by mrsimpson** [comment]
ABAP supports string templates as of 7.0. 
However, some features like SWITCH are missing.

**Comment by sbcgua** [comment]
for history (IE limitations @sapgui): 
[1833037 - SAPGUI HTML Viewer: IE8 and above is not supported by WebBrowser embedded in HTML viewer](http://service.sap.com/sap/support/notes/1833037)
https://msdn.microsoft.com/en-us/library/ee330730(v=vs.85).aspx
refered as working, thought didn't work for me

**Comment by larshp** [comment]
3 - Its a feature to discover abapGit based projects without searching the web, think of it as some "featured" projects. It points the user to http://larshp.github.io/abapGit/explore.html, also see the gh-pages branch of this project https://github.com/larshp/abapGit/tree/gh-pages. The new design will have to be implemented separately for this html page, but it should be straight forward when the other stuff is done.

7 - I agree

**Comment by larshp** [comment]
hi, 
do you mind if I start moving the GUI to your proposed design? or would you like to do a pull request?

I think the broken layout can be fixed using some old-style HTML layout tricks(tables)

**Comment by sbcgua** [comment]
Hi Lars, Sorry for long silence, having tough schedule at my current project.

I started coding, I think I'll commit something soon (maybe this week). In the meanwhile I've finilized the main page layout and css. I must say that IE7+compat5 (the mode used in GUI) really sucks - not only it does not support very usual styles but also it has issues with padding and image data. 

![image](https://cloud.githubusercontent.com/assets/15635498/14842408/96d133bc-0c4f-11e6-917a-7e207988b4a1.png)

There are are some questions by the way:

1) IE target version. I've found that GUI 7.4 does not force IE down to 7 version. Do you have any concern on GUI version? Actually the difference is so big that when IE7 shows images IE10 does not and vice versa... I'm trying to solve it with JS now ... but honestly that looks like a crutch. Maybe target to newer IE? IE7 style will be inaccurate then - empty space where the images must be (except of logo) - kind of opposite the screenshot above. What do you think ? 

2) Back button. What if I remove Back link from child pages and assign this function to normal SAP back button. This assumes catching GUI event and passing it to the class (which must be non-static then). html_viewer seems to have go_back() method. This will make UX better - "Back" link is not intuitive in SAPGUI.

3) I've separated all html code to a separate class for clearer code. 

4) As I can see repos classes call gui to render themselves. This is kind of calling the view from the model ... I'd suggest detecting from it GUI. For this, repo class has to have an attribute showing its type (on/offline) set in constructor. Or using RTTI ... Would you mind ?

5) Just a comment. The code (whole abapgit) is really huge. Do you consider splitting it to includes? Separate for each "function area"? I guess the main reason for 1 file is simple installation. If so have a look at [the tool](https://github.com/sbcgua/abap_include_assembler) I've published recently - it is called include_assembler and kind of compiles all includes into one target file. The output can be saved as another program (build) or text file. Just as a suggestion.

**Comment by larshp** [comment]
1: would like to support as many versions as possible. If it is possible to put in some extra effort to have it work with a low version, I think we should go for it

2: if its possible to bind back without having a dynpro screen its okay, perhaps you can create a small example on github showing how to do it? I havent found a way, but also havent looked much, just assumed it was not possible/difficult

3: ok

4: agree, I fixed this a few days ago, https://github.com/larshp/abapGit/blob/18724d1554dc31af0009ad419f1fc0e3a53155fb/zabapgit.prog.abap#L17772

5: would prefer not to introduce a build step if possible. Having just one file makes it low effort to contribute code(not having to look into tools), but it also has the disadvantage of it being large, and the possibility to introduce conflicts when merging changes.

**Comment by mrsimpson** [comment]
That sounds like quite some effort and in fact a lot of additional code to be included into the product. Also, support of newer releases than Lars' targeted 7.02 is also a challenge here.
We've had similar discussions when I wanted to contribute a generic adapter. Thus, I'd propose to go for a similar approach now: Separate the undoubtly beautiful UI and ship it from the plugins-repository. That would also enable to chose a different runtime-environment: You could implement a webdynpro/BSP/Fiori/whatever component - or even simply create a restful ICF-node.
Particularly  the latter would allow integration into other tools.
Of course, there'd be some overhead (like adding proxies for the local classes), but it would also make ABAPGit more easy to consume.
At the same time, it would comply with the as-simple-as-possible-copy-paste-deployment-paradigm.

Just my two cents

**Comment by larshp** [comment]
Hi,
I reproduced the issue with missing icons in IE9. I've changed the "icon" style to
```css
display:          inline-block;
vertical-align:   bottom;
```
and it seems to work both in IE9(tested with http://larshp.github.io/test_html/) and when running via SAP GUI(tested with https://github.com/larshp/test_html/blob/gh-pages/zfoobar.abap).

It might not work in old SAP GUI versions, but I think its okay, most are running 7.40 nowadays.

---

Was also thinking of doing a workaround, the icons could be stored in ABAP variables instead of using CSS. Eg.

```abap
DATA lv_icon TYPE string.

lv_icon = '<img src="data:image/png;base64,iVBORw0KGgoAsomethingsomething>'.
rv_html = lv_icon && 'some text after the icon'.
```

It should work on all versions in all cases, plus it is easy, but is not very pretty.

**Comment by sbcgua** [comment]
1,2) ok
4) That's what I needed :)
5) "would prefer not to introduce a build step": it is a dev tool, so this step is on the vendor side - for consumer nothing changes. Just have a look to the description. But you decide anyway :)

inline-block: yes I know. Actually I've managed make it with js - if IE7 detected, style is replaced inline-block<->inline.

img-generation: I thought about it too. That splits style between css and code, and I actually wanted to clear html as much as possible ... but I'll play with it a bit, it solves the issue indeed

**Comment by larshp** [comment]
Cool, feel free to do many small commits/PRs, when you have something that is a step in the right direction just submit it. This will minimize the risk of merge conflicts, plus we'll be able to test it with a wider audience, and adjust the direction if needed, and it is easier to review.

---

5: I like the [include assembler](https://github.com/sbcgua/abap_include_assembler) it looks nice. The [steamroller](https://www.assembla.com/spaces/saplink/subversion/source/HEAD/trunk/installer/PROG_ZSAPLINK_STEAMROLLER.slnk) used in SAPlink has also been discussed.

A build step raises the question regarding how/when/who to do releases, in the current approach all changes are automatically released as soon as possible, this allows for introducing errors very quickly, but changes can also be tested and fixed very quickly. I believe that moving fast ahead benefits the project(ship early, ship often).

The ABAP code installed in "customer" systems is the same as the development branch, so if someone finds an error and fixes it, the code relates 100% to what/where it can be fixed in the git repository. I believe that this transparency will encourage more people to contribute, new contributors does not have to install extra ABAP tools or even install a git client as the github web interface can be used.

On the other hand, there are some potential problems with merge conflicts in the current approach. But there have been a total of 6 different contributors in the ~2 year lifespan of the project. I think we can get a long way by committing changes as soon as possible. Branches are cool, but I think its easier to attack the merge conflicts as soon as possible instead of postponing it via branches.
(I've added a note in https://github.com/larshp/abapGit/blob/master/CONTRIBUTING.md regarding committing often)

**Comment by larshp** [comment]
5: new idea: have Travis do the build and releases(like all the cool web-kids)

This would require implementing the include assembler or steamroller in some language that can run on travis(javascript/typescript/python/batch/C#/etc.). It would then do the build and automatically create and push the release to github.

**Comment by larshp** [comment]
created issue #210 for the include assembling.

Then this issue can get back to the original topic :smile:

**Comment by larshp** [comment]
hi,
I did some work on this today, see https://github.com/larshp/abapGit/commit/68faf59786cf6362e2d10e8c7495c6e69cc8d7eb

It is nowhere done yet, and some of the stuff is probably not done the right way. Feel free to do a pull request with fixes and changes. I'll probably continue the work tomorrow

**Comment by sbcgua** [comment]
Hi, sorry for delays, really under water now and in a trip :) I've done big part of the code already but it does not show repos yet. If it is not urgent I'll finish during the weekend.

**Comment by larshp** [comment]
no problem, dont worry :smile: 

I have done some of the stuff, and working on some more. Some of the next stuff in abapGit I'll look into will involve extra buttons in the gui and extra pages, so just need a bit of this CSS going to avoid double work.

**Comment by sbcgua** [comment]
The final css is [here](https://github.com/sbcgua/TestRep1/blob/master/styles.css) - although there are some commented styles - they can be removed

**Comment by sbcgua** [comment]
Also posted some code here - but it is really half way there https://github.com/sbcgua/abapGit/commit/39d9177029558dfb1d9727461f1c0151b2ef435a

**Comment by larshp** [comment]
hi, I've implemented some of the stuff, see screenshot below.

The front page looks consistent now, but there are probably a lot of extra tweaks that can be done, also there are no icons added yet. I'll start looking into some other stuff in abapGit, so feel free to submit PRs with additional updates, multiple small incremental PRs are okay.

![image](https://cloud.githubusercontent.com/assets/5888506/15267201/70a22268-19bb-11e6-9856-3011de1a6630.png)

**Comment by sbcgua** [comment]
Hi, coming back to this topic, sorry for long silence on this topic from my side :) I can take care about fine tuning and images - I'll be having a bit more time next few days. 

A few points I'd like to check (might be subjects for separate issues): 

1. Would you mind if I do some refactoring ? I'm going to create a page super class for example and put there header/footer and some other common code. GUI class is more a controller so I'd like to separate view code. 
1.1 Would you mind if I convert GUI to a singleton non-static class? It is quite typical pattern :) 
1.2 Potentially some page switching should be done in gui class instead of pages ... thinking on that currently.
2. Design: would you mind if I remove bottom logo ? From design perspective it would look better :)

**Comment by larshp** [comment]
1. no
  1.1 feel free
  1.2 try and see how it looks. If in doubt, split it into a separate PR so we have the changes isolated
2. no

:smile:

**Comment by larshp** [comment]
there are also 2 new pages introduced this weekend: staging and commit, that you might have some ideas to improve design wise :wink:

**Comment by sbcgua** [comment]
2) logo - :'(
ok, I'll think how to tune it in this way :)

new pages: yes I've seen, I'll come to them eventually too :)

offtopic: btw how abapmerge is going (great idea btw - far better than include assembler certainly) ? is it possible to split includes already ?

**Comment by larshp** [comment]
abapmerge:
I think it is basically done, added possibility to test it online: http://larshp.github.io/abapmerge/ and released to npmjs.org

next step would be to try splitting ZABAPGIT up to see if it will work with abapmerge. It is most likely possible, but there might be a few surprises

would like to implement the "starting folder" feature in ZABAPGIT before taking it in use, so the abapGit repository will have a /src/ folder with all the includes. Instead of messing up the root folder(see eg. https://github.com/larshp/abapOpenChecks which also needs cleanup)

**Comment by sbcgua** [comment]
![image](https://cloud.githubusercontent.com/assets/15635498/15665853/407994a0-2716-11e6-8f04-31f5cbd8816e.png)
For history :)

**Comment by sbcgua** [comment]
I guess this one also can be closed for now. @all: What do you think ?

**Comment by larshp** [comment]
yes, close it, we can always open a new if needed
