### ISSUE TITLE
Support of Behaviour Definition (BDEF) as RAP artefact

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#2021]
Object Handler to support Behaviour Definitions for RAP programing model

**Comment by anagarcigm** [comment]
Good Afternoon,

We are working with Rap and are interested in use this object in Abapgit.
This issue is open many time ago. Is there any date to include this object in the current version?
Best regards.

**Comment by christianguenter2** [comment]
@anagarcigm it's implemented now. Please check the latest version.

**Comment by anagarcigm** [comment]
Thanks. I have done.

Note: I have this warnings about other objects.

![Captura](https://user-images.githubusercontent.com/56394203/81043367-664f0900-8eb2-11ea-9f91-c52101419636.PNG)

**Comment by larshp** [comment]
the SCVI and STVI classes was moved to a different package, its easiest just to delete the 2 classes and then pull again

**Comment by anagarcigm** [comment]
Hi.
But the object appears twice in folder src and in folder src/objects
Thanks in advance.
Best regards.

**Comment by christianguenter2** [comment]
Yes, that's because it class has been moved to another package. Either follow Lars advice from above or manually reassign the package to objects package, e.g. $ABAPGIT_OBJECTS. Note that the actual package differ in your case.

**Comment by anagarcigm** [comment]
Ok. It works.

Thanks.

**Comment by anagarcigm** [comment]
Hi.
I have a question. How can i generate a file with extension srvd.assrvd?.
I see in my repository srvd.srvdsrv.

Thanks in advance.

**Comment by christianguenter2** [comment]
I don't know if I got your question right but SRVD is a service definition and you can edit it in ADT. No need to generate the file, it's generated by abapGit when there 's a service definition in your repo.

**Comment by anagarcigm** [comment]
Hi.
When i run abapgit i have this message.

Best regards.
![Captura1](https://user-images.githubusercontent.com/56394203/81185075-6e41a280-8fb1-11ea-865f-baf3bd88578f.PNG)

**Comment by christianguenter2** [comment]
@anagarcigm ok, can you please open a new issue with this and elaborate a bit more?
