### ISSUE TITLE
CALL_METHOD_NOT_IMPLEMENTED when importing ABAP SDK for Azure

### ISSUE THREAD

**Issue by gregorwolf** [larshp/abapGit#2023]
I'm using the current master of abapGit and try to import the [ABAP SDK for Azure](https://github.com/Microsoft/ABAP-SDK-for-Azure). Unfortunately that fails with this Dump:

Category               ABAP programming error
Runtime Errors         CALL_METHOD_NOT_IMPLEMENTED
Except.                CX_SY_DYN_CALL_ILLEGAL_METHOD
ABAP Program           ZCL_ABAPGIT_OBJECTS===========CP
Application Component  Not assigned

It occurs in:
ZCL_ABAPGIT_OBJECTS -> SERIALIZE
Line:
    rs_files_and_item-item-inactive = boolc( li_obj->is_active( ) = abap_false ).

**Comment by larshp** [comment]
what is the object type?

**Comment by gregorwolf** [comment]
As a first workaround I've implemented

```
  METHOD zif_abapgit_object~is_active.
    rv_active = abap_true.
  ENDMETHOD.
```

in ZCL_ABAPGIT_OBJECT_SUSC.

**Comment by larshp** [comment]
@gregorwolf did the fix by @christianguenter2 fix the problem?

**Comment by EduardoCopat** [comment]
I recently cloned the Azure SDK and it was successful. Closing.

If it happens again, we reopen it.
