### ISSUE TITLE
Usability: accessing private repos

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#203]
if I have a private repo (or more than 1 !!!) it asks all the passwords at the beginning. Very inconvenient. I'd suggest skipping automatic repo update or skipping private repos update and initiating then after explicit "refresh" for a repo or global "Refresh all".

Unchecked repos can be displayed as a placeholder block, mentioning something like "This is a private repo and requires login. Please press me to update". I can design this.

So:
1. user runs abapgit
2. it checks each repo, if repo requires pass, it falls back to the place holder
3. Placeholder can be also done clickable like a big button ("...press ME to update...")
4. the user can press "Refresh All" at the top to refresh all repos (the login dialog should show the repo name)

Relevant: #45, #202

**Comment by larshp** [comment]
also see https://github.com/larshp/abapGit/issues/207 it is mainly to avoid refreshing a lot of repositories.

If there are 5 repositories installed, typically a developer is working on one at a time. So the hiding allows for hiding 4 of them, and only have one being automatically refreshed.

Perhaps the private repo issue and hiding feature can be combined somehow.

**Comment by larshp** [comment]
hi,
errors have now been isolated to each repository in https://github.com/larshp/abapGit/commit/b8cbfbc0e2e106e91240a3980057f72d0b162ea2 and hide feature implemented in https://github.com/larshp/abapGit/commit/6575f9834f4830c740f7e19338acc629c56facb2

can you try again and see if it works better with the new features?

**Comment by sbcgua** [comment]
Show/Hide is good for sure. Adds a lot of convenience. :)
I would also store default email per repo per user. Kind of login manager. The lcl_login_manager is only for background for the moment. I'll look into it later in a separete ticket. So closing this one for now.

**Comment by larshp** [comment]
login manager, see #251
