### ISSUE TITLE
SHI3: Deletion calls UI

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2035]
Deletion of SHI3 (General structure storage: Definition of a structure) calls UI.

![image](https://user-images.githubusercontent.com/17437789/47925930-95507d00-debf-11e8-9c21-a73ea7378293.png)

Demo repo
https://github.com/abapGit-tests/CUS0.git

**Comment by larshp** [comment]
guess this one can be closed?

**Comment by christianguenter2** [comment]
done
