### ISSUE TITLE
IDOC and IEXT: abapgitCI indicates errors

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2044]
[abapGit CI](https://github.com/abapGit/CI) indicates errors for IDOC and IEXT.
Reproducable with test repos.
https://github.com/abapGit-tests/IEXT.git
https://github.com/abapGit-tests/IDOC.git

![image](https://user-images.githubusercontent.com/17437789/47968773-aee3f700-e06e-11e8-8eb7-2b894fb1bbd5.png)

**Comment by larshp** [comment]
customizing EDISGEMENT is not serialized,

![image](https://user-images.githubusercontent.com/5888506/48976782-bc006e80-f08d-11e8-985a-475dd73d5e9d.png)

**Comment by larshp** [comment]
one solution is adding the customizing in the TABL xml, but not sure its the best solution

**Comment by christianguenter2** [comment]
#1989

**Comment by larshp** [comment]
suggest closing this one as a duplicate
