### ISSUE TITLE
Icons missing in JavaGUI

### ISSUE THREAD

**Issue by pokrakam** [larshp/abapGit#2045]
When using abapGit on a JavaGUI, some icons disappear. 
Windows:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/25539927/47970549-e9559000-e07e-11e8-947a-6c185ed12fb6.png">
Mac / JavaGUI:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/25539927/47970547-dcd13780-e07e-11e8-9378-32a9ffca780a.png">
When hovering over the nonexistent icons with the mouse, the menu appears or the pointer changes (favourite-star) and everything still functions.

It's not a colour issue, as the alignment shows the icons are not rendered. Compare alignment of abap2xlsx on the following two screenshots:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/25539927/47970594-b1028180-e07f-11e8-9a1c-b81041efe7ab.png">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/25539927/47970597-bfe93400-e07f-11e8-8e31-428acfabd321.png">

It's not terribly important, as things do work. But it can confuse users.

**Comment by christianguenter2** [comment]
#1319

**Comment by pokrakam** [comment]
Sorry, missed that, can close this.
