### ISSUE TITLE
Syntax errors: 'Only the addition "GLOBAL FRIENDS" exists for PUBLIC classes, not the addition "FRIENDS" addition.' when installing zabapgit.abap

### ISSUE THREAD

**Issue by gregorwolf** [larshp/abapGit#2056]
I've just tried to install abapGit from the latest build at [zabapgit.abap](https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap) and get the following Syntax error:

Only the addition "GLOBAL FRIENDS" exists for PUBLIC classes, not the addition "FRIENDS" addition.

That is caused in this section:

```
CLASS zcl_abapgit_abap_unit_tests DEFINITION
  CREATE PRIVATE
  PUBLIC
  FRIENDS ZCL_ABAPGIT_factory.
```

by the additional PUBLIC statement. When I remove it the next error occurs in:

`CLASS zcl_abapgit_adhoc_code_insp DEFINITION`

**Comment by larshp** [comment]
abapmerge should remove the "PUBLIC" keyword, however it does not know all the possibilities in ABAP

**Comment by larshp** [comment]
thanks, will have a look sometime later

workaround is getting the old version from https://github.com/abapGit/build/blob/d0ce247d178966ba4815b8836cbda42529569296/zabapgit.abap

**Comment by larshp** [comment]
https://github.com/larshp/abaplint/issues/277

**Comment by christianguenter2** [comment]
I think we can close this one
