### ISSUE TITLE
Late deserialization for object TOBJ

### ISSUE THREAD

**Issue by VishnAndr** [larshp/abapGit#206]
There is an issue that TOBJ object can only be generated if active versions of related objects already exist in the system. It's even mentioned as ToDo in method lif_object~deserialize of lcl_object_tobj.
"* todo, TOBJ has to be saved/generated after the DDIC tables have been activated". It should be done if sy-subrc = 2 after OBJ_GENERATE call.

What would be nice to have is an option to store such TOBJs somewhere ( where? ) and call deserialize method for them after 
lcl_objects_activation=>activate( )
in method deserialize of lcl_objects class.

So the question is where to store such objects for "late deserialization"? What do you think?

Or different approach: what about skipping TOBJ deserialization and call it separately after other objects activation?

PS: in case of offline project - now I need to move tobj files to separate zip-file and import it as an additional step manually. That certainly works.

**Comment by larshp** [comment]
hmm, not sure :confused: 

It might be the best option to skip TOBJs until after the activation, but would like some generic way to define this so it can be reused if its needed for other types.

**Comment by VishnAndr** [comment]
May be some flag set during serialization in metada of an object and check during first run of deserialization?
Another thought was an exception from deserialize method which would be caught and such objects will be processed in second step of deserialization?

**Comment by larshp** [comment]
Exceptions are usually for error handling, not sure I would regard this scenario as an error.

@mrsimpson recently introduced method GET_METADATA in LIF_OBJECT which is metadata for the object serializer itself. If we add a new field in TY_METADATA eg. LATE_SERIALIZATION, the code controlling the serialization would know what to do.

Wondering if the new metadata field should be an integer so we can control the sequence of late deserialization, eg if a new object type should be deserialized after TOBJ. But on the other hand I'm not much of a design for the future guy, so a flag will also do for now.

**Comment by VishnAndr** [comment]
OK, will try to implement the flag on weekends

**Comment by larshp** [comment]
should be working now, closing issue, feel free to reopen if there are any issues
