### ISSUE TITLE
Explore doesn' work for me.

### ISSUE THREAD

**Issue by jmoutreux** [larshp/abapGit#2069]
Hello, 
I just copy zabapgit from http://www.abapgit.org and try the button Explore but i only see blank page. 

it's an issue of my install ? 

thanks for help.
![image](https://user-images.githubusercontent.com/44878745/48222403-d1d71980-e394-11e8-9cc5-fc77f8ae0d2e.png)

![image](https://user-images.githubusercontent.com/44878745/48222526-119e0100-e395-11e8-943c-2b446b697321.png)

could you please help ?

**Comment by flaiker** [comment]
Same issue here. (You can explore on https://dotabap.org/ for now.)

Seems to me like dotabap.org was recently changed to enforce https. The json-request gets redirected from http to https and fails with a CORS error.
![image](https://user-images.githubusercontent.com/5270359/48226128-31d2bd80-e39f-11e8-9fe6-4026f821e1aa.png)

**Comment by larshp** [comment]
yeah, I moved everything to HTTPS

@jmoutreux try again, latest version, fix by @flaiker merged

**Comment by jmoutreux** [comment]
Thanks it work now.

Best regards
Jérôme Moutreux
SAP Development consultant
Mobile: +33 6 43 47 92 09


[LOGO-TEAMWORK-SIGNATURE-version Outlook]

FRANCE : 1, Rue Jean Carmet - CS 80004 - 69808 Saint-Priest
Phone: +33 (0)4 78 63 63 25
www.teamwork.net<http://www.teamwork.net/>

Print this message only if this is essential.


De : Lars Hvam <notifications@github.com>
Envoyé : vendredi 9 novembre 2018 04:15
À : larshp/abapGit <abapGit@noreply.github.com>
Cc : MOUTREUX Jerome <Jerome.Moutreux@teamwork.net>; Mention <mention@noreply.github.com>
Objet : Re: [larshp/abapGit] Explore doesn' work for me. (#2069)


yeah, I moved everything to HTTPS

@jmoutreux<https://github.com/jmoutreux> try again, latest version, fix by @flaiker<https://github.com/flaiker> merged
