### ISSUE TITLE
CUS0: no TADIR delete if in CTS relevant Package

### ISSUE THREAD

**Issue by bigld** [larshp/abapGit#2093]
Object directory entry can't be deleted if CUS0 is locked in an Transport
![image](https://user-images.githubusercontent.com/4643389/48311229-e1c14a00-e59c-11e8-9ba0-9ad1c576ec1e.png)

zcl_abapgit_object_cus0->get_metadata 
rs_metadata-delete_tadir = abap_true.

#1636

**Comment by bigld** [comment]
can be reproduced with test repo https://github.com/abapGit-tests/CUS0.git

**Comment by larshp** [comment]
this might be a generic issue for objects using `rs_metadata-delete_tadir = abap_true.` ?

**Comment by mbtools** [comment]
Tested with the current version and uninstall works fine for local as well as transportable packages. 
Closed by https://github.com/larshp/abapGit/pull/2741

**Comment by JanisB-AT** [comment]
TADIR of transportable object has to be cleaned up, I believe, by CTS only, during/after the release of transport. 

At the moment, however, UNINSTALL of a PROG fails to write the requisite entry into transport request (the TR entry for green arrow PROG I produced  via debugger, by re-enabling deletion popup for RS_DELETE_PROGRAM call):
![image](https://user-images.githubusercontent.com/9512588/102698966-9f6d9b00-4241-11eb-8fb2-628ce6f6f116.png)

This RS_DELETE_PROGRAM behavior seems to be documented:
![image](https://user-images.githubusercontent.com/9512588/102699085-59650700-4242-11eb-80b2-0c465cdc102f.png)

Fixing of writing deletion entry for transportable PROG could be done then, on the first look, as easily as by passing ZCL_ABAPGIT_DEFAULT_TRANSPORT=>GET_INSTANCE( )->GET( ) to RS_DELETE_PROGRAM -> CORRNUMBER in ZCL_ABAPGIT_OBJECT_PROG->ZIF_ABAPGIT_OBJECT~DELETE( ).

I'll try it out...

**Comment by mbtools** [comment]
@JanisB-AT no need for that: just set `rs_metadata-delete_tadir = abap_true.` here:
https://github.com/abapGit/abapGit/blob/master/src/objects/zcl_abapgit_object_prog.clas.abap#L230

**Comment by JanisB-AT** [comment]
@mbtools One needs the TR entry anyway - if the deletion is to be transported onward to QA and PRD. What does that do - delete TADIR physically? If so, I'm 99.99% sure that there might be an issue upon releasing deletion TR, - if the DEV TADIR is already missing. 

I'd leave the deletion of TADIRs belonging to transportable packages to CTS, if at all feasible...

**Comment by mbtools** [comment]
sure. your approach or just call `corr_insert` in the `zif_abapgit_object_prog~delete`.
