### ISSUE TITLE
ECTC: Background deserialization shows diff

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2097]
abapGit CI indicates diff for ECTC. The error occurs only when [abapGit CI](https://github.com/abapGit/CI) runs in background.

![image](https://user-images.githubusercontent.com/17437789/48428639-b9d41100-e76b-11e8-901c-887f9d2c67e7.png)

https://github.com/abapGit-tests/ECATT.git

**Comment by larshp** [comment]
duplicate, use https://github.com/larshp/abapGit/issues/2722 instead?
