### ISSUE TITLE
steamrolling / include assembling abapGit code

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#210]
see https://github.com/larshp/abapGit/issues/202
see https://github.com/larshp/abapGit/issues/164

if anything I'm most hot for building a program that can run in [Travis](https://travis-ci.org/) and automatically do the build and upload the release to github automagically.
Think something much like https://github.com/sbcgua/abap_include_assembler will be easy to implement with node/javascript/typescript, and it will make sure the built code looks much like the development version of the code.

**Comment by mrsimpson** [comment]
I like the idea. Two remarks:

1. Assuming there were only a report and a set of global classes and interfaces (serialized from ABAPGit) in the src-folder: Would travis have to do more than adding a "definition deferred" in the beginning for all class-and interface-names and then concatenate all the sources (maybe including a substitution of the prefix)? I don't think so.
2. Problem is that the result of the build cannot be verified (due to a missing ABAP-runtime). Potential solution if you have an ABAP-system which is always online and connected to the internet: Use a webhook to trigger a clone of the ABAPGit-Repo and compile the package. A simple ICF-Node.Implementation should be sufficient.
The result could in turn be posted to GH. @gregorwolf did something similar in ZAKE. with SVN.

**Comment by larshp** [comment]
1. the "definition deferred" would probably already exist in the main include, as there are some dependencies between the classes. So it would just concatenate some files.

2. yes, however it requires an ABAP system that is connected to the internet and running at all times => problem with money and licenses

on the other hand I guess the risk for syntax errors in the "concatenated" build is quite limited

**Comment by larshp** [comment]
will be trying out some stuff in https://github.com/larshp/abapmerge

**Comment by larshp** [comment]
seems to work, see https://github.com/larshp/abapmerge_test
and
https://github.com/larshp/abapmerge_test/releases

Would really like to have a direct link directly to the latest built zabapgit.abap file, however it seems like that is not possible without some javascript, http://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo . So the users will have to go to the github releases page and find the correct file, hmm

**Comment by larshp** [comment]
another reason to look into this: it seems that github cuts of the files at a specifc point in time, eg. only the first 17047 lines is shown in https://github.com/larshp/abapGit/blob/master/zabapgit.prog.abap

**Comment by larshp** [comment]
now possible to test abapmerge online: http://larshp.github.io/abapmerge/

**Comment by sbcgua** [comment]
Idea by the way: plugins to integrate css or image data from ext files kind of:

```
METHOD styles.
  "##ABAPMERGE IMPORT_CSS(somefile.css)
ENDMETHOD.
```


P.S. really need include splitting ... editing/compiling 20k line on a slow connection (I'm in a business trip) is terrible.

**Comment by larshp** [comment]
I will look into this topic after sithh.de, ie. about a week from now

**Comment by sbcgua** [comment]
Hi @larshp, how did the sithh.de go ? =) Will there be any online materials ? There are some nice topic as I could see (including yours :)

**Comment by larshp** [comment]
all good, thanks :smile: you can check #sithh on twitter for pictures and comments

a few people have added links to slides at https://wiki.scn.sap.com/wiki/display/events/SAP+Inside+Track+Hamburg+2016+-+%23SITHH

my slides are at
https://larshp.github.io/sithh2016/

**Comment by larshp** [comment]
hi,
The pretty printer started to take 10 seconds to execute, so I've moved the code to src/ folder and setup abapmerge :smile: 

The builds are saved to the gh-pages branch eg:
http://larshp.github.io/abapGit/build/zabapgit.txt
it is named .txt to show the source in the browser instead of triggering a download of the file. Wondering if it should be renamed to .abap and then instead point users to https://raw.githubusercontent.com/larshp/abapGit/gh-pages/build/zabapgit.abap
