### ISSUE TITLE
Opening the repository takes a long time

### ISSUE THREAD

**Issue by joymike** [larshp/abapGit#2100]
Problem: Opening a large repo/package takes around 200,000 milliseconds.

We are looking at using abapGit to sync our ABAP main package to our internal github. 
We are toying with the idea of using this for code review, and we cannot restrict objects in one transport to all belong to one package/repo. Hence synching at the highest package is our only way.
It contains around 8000 objects in total and about 30 subpackages.

I see for closed issue #537 is related and solved by limiting the number of entries displayed in the settings but didn't help us.
Most of the time is spent on serialisation, and i understand from the comments it is hard to achieve this without the use of function groups.
My questions is:
1) Could we persist the serialisation based on change timestamp?
2) Is there a way to not serialise every time?

I'm new here, so I am happy to contribute to the project (including coding), but I just want to ask the obvious question before wasting my time and everyone's time.

**Comment by larshp** [comment]
200000 milliseconds = 200 seconds =~ 3 minutes

The plan is to do serialization in parallel, see https://github.com/larshp/abapGit/issues/1714

**Comment by flaiker** [comment]
#2061 might have also dropped performance by a bit for transportable packages. Can you check if `lv_render_transports = abap_false.` makes a significant difference?

https://github.com/larshp/abapGit/blob/e61108511dec241e9b24a9d61231303525ba6ac3/src/ui/zcl_abapgit_gui_view_repo.clas.abap#L631-L632

**Comment by joymike** [comment]
> 200000 milliseconds = 200 seconds =~ 3 minutes
> 
> The plan is to do serialization in parallel, see #1714
> 
> Function groups: idea is to only have parallel serialization supported in the full install, i.e. not in the 50k lines ABAP report

Thanks for the prompt response Lars.

Can you explain the rationale of serializing everytime, even for unchanged objects on either side? Is this a GIT restriction?

**Comment by joymike** [comment]
> #2061 might have also dropped performance by a bit for transportable packages. Can you check if `lv_render_transports = abap_false.` makes a significant difference?
> 
> [abapGit/src/ui/zcl_abapgit_gui_view_repo.clas.abap](https://github.com/larshp/abapGit/blob/e61108511dec241e9b24a9d61231303525ba6ac3/src/ui/zcl_abapgit_gui_view_repo.clas.abap#L631-L632)
> 
> Lines 631 to 632 in [e611085](/larshp/abapGit/commit/e61108511dec241e9b24a9d61231303525ba6ac3)
> 
>  lv_render_transports = zcl_abapgit_factory=>get_cts_api( 
>    )->is_chrec_possible_for_package( mo_repo->get_package( ) ).

Thanks for the suggestion.
Very similar ~200 seconds (3.5 mins).

**Comment by larshp** [comment]
rationale: this is just how it is currently implemented, not all objects have timestamps for latest update, and it is typically only down to the second. So the safe and easy approach is serializing everything every time

**Comment by larshp** [comment]
Saving timestamps opens for a lot of questions, eg. see https://github.com/larshp/abapGit/issues/1021 where the current non-persisted cache has some problems. Also, what if the serialization format changes, how will the timestamp know? Currently much of the git code works on full files, saved timestamps would probably require this to change.

Parallel serialization is on the other hand, more or less straight forward to implement, and will not need to change any design.

Contributing: get familiar with git and the github flow first, recommend making a small change first, there are lots of bugs 😄 Keep the pull requests as small as possible, this makes it easier to review, and if it is in a wrong direction not too much time is wasted. For larger/central changes recommend discussing the plan/approach first, but its free for all 🆓

**Comment by larshp** [comment]
@joymike also feel free to join the Slack channel, https://abapgit-slackinviter.herokuapp.com

I might have some time this week and start looking into Parallel Serialization, wont promise anything, just keep an eye on the pull requests, recommend [watching](https://help.github.com/articles/watching-and-unwatching-repositories/) the repo

**Comment by joymike** [comment]
Thanks Lars.
I fully agree parallel serialisation is a safe approach and inline with current design. 
However I think caching is also a necessity and don't really see a real issue with has_changed_since concept.

I am familiar with git, and will try with something small first to test the waters. 

I'll add further comments to #1021

**Comment by larshp** [comment]
Also, if your scenario is using git tools for code review, then I'm planning to sync the transports to a branch in background, so the developers does not have to change their workflow. And then performance does not matter too much

**Comment by joymike** [comment]
Wow... retested code with the latest new parallel feature. This has brought it down to 50-60 seconds (from about 4 mins for 8000 objects previously) using 21 threads which is a massive improvement and now much more acceptable to the end user. Many thanks @larshp . Awesome job!!

![image](https://user-images.githubusercontent.com/4646447/48990386-504bfd80-f182-11e8-8a48-802592351f41.png)
