### ISSUE TITLE
Cannot deserialize repo with unsupported object type

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2103]
Seem like a regression from https://github.com/larshp/abapGit/pull/2017

![image](https://user-images.githubusercontent.com/17437789/48546111-bf466e00-e8c7-11e8-8b3e-1bfd2e5a4e82.png)

![image](https://user-images.githubusercontent.com/17437789/48546136-d4230180-e8c7-11e8-8b49-6c526456c59e.png)

Suggest moving this block into surrounding try catch and catch zcx_abapgit_exception.
https://github.com/larshp/abapGit/blob/dc173ad9061c0f54e14301d0b83d1b0b6f6bfc50/src/zcl_abapgit_objects.clas.abap#L703-L704

**Comment by flaiker** [comment]
Hm, it still works for me. Might be specific to some object types? Or specific to offline repositories.
![image](https://user-images.githubusercontent.com/5270359/48603411-a052e500-e976-11e8-9edb-0d698d641fce.png)

**Comment by christianguenter2** [comment]
You are right, the error occurs only for offline repos.

CMOD with online repo:
![image](https://user-images.githubusercontent.com/17437789/48606395-d21c7980-e97f-11e8-93ff-c44406abce74.png)
