### ISSUE TITLE
Open abapGit in master language

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#2105]
In my case at work I am usually logged on with language = DE. The original language for development is always DE. Therefore all development that uses abapGit has a git repository with master language DE.

Now the issue is when I want to update an abapGit repository (like maybe abapGit itself) that has a different master language than my current logon language, because of course abapGit rejects pulling the updates. To continue I need log off (and close all gui windows that may have running processes) and login again with language EN (multi logon is disabled). After that I switch again to continue my work.
With eclipse this is not possible, I would need to create a separate project for each language...

I recently stumbled upon this blog by Horst Keller:
https://blogs.sap.com/2017/01/13/logon-language-sy-langu-and-rfc/

I suggest adding a small link in the repository page, that shows up when master language <> logon language. Clicking on it opens abapGit using ABAP4_CALL_TRANSACTION in a new task / GUI window with logon language = master language. That would make things quite a bit easier as it circumvents the multi logon issue.

(To take things further one could even call the abapGit-API over RFC with the different language and do the pull in there. I doubt that's possible yet (regarding the API) and you would also lose the progress indicator.)

**Comment by christianguenter2** [comment]
Quite interesting approach, I have the same problem on several systems, too.

**Comment by christianguenter2** [comment]
Or maybe something like this. 
To jump to any install language as the problem might occur for other repos too.
![grafik](https://user-images.githubusercontent.com/17437789/48632689-d49fc300-e9c1-11e8-901e-eff0bc5a748c.png)

![grafik](https://user-images.githubusercontent.com/17437789/48632735-f4cf8200-e9c1-11e8-8d53-7bc78255261c.png)

**Comment by christianguenter2** [comment]
Yes, indeed that would be better. What do you think about that?

Repo opened in DE instead of EN, then there's a new option 'Advanced > Open in master language'.

![grafik](https://user-images.githubusercontent.com/17437789/48647089-2f99e000-e9eb-11e8-9885-88df8947571b.png)

Which opens new mode with the repo opened in the master language.

![grafik](https://user-images.githubusercontent.com/17437789/48647106-40e2ec80-e9eb-11e8-98e5-baa32b2b2cb4.png)

**Comment by christianguenter2** [comment]
[WIP](https://github.com/christianguenter2/abapGit/tree/2105_b)

**Comment by flaiker** [comment]
Looks great!

**Comment by flaiker** [comment]
Merged in #2117
