### ISSUE TITLE
Cannot install repo with starting folder '/'

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2113]
[abapGit CI](https://ci.abapgit.org)
![grafik](https://user-images.githubusercontent.com/17437789/48659231-2db53880-ea4e-11e8-8c4e-d9f1f06739bc.png)

Cannot install ECATT demo repo anymore. Reproducable.
https://github.com/abapGit-tests/ECATT.git

A dump occurs
![grafik](https://user-images.githubusercontent.com/17437789/48659011-5f78d000-ea4b-11e8-9c6a-f5002c5bb911.png)

![grafik](https://user-images.githubusercontent.com/17437789/48659014-67387480-ea4b-11e8-9dac-abf11c2bc1bd.png)

![grafik](https://user-images.githubusercontent.com/17437789/48659108-7a980f80-ea4c-11e8-9e0d-164dd13b4347.png)

Seems like a regression from the recent changes.

**Comment by christianguenter2** [comment]
The problem occurs for every repository with starting folder `/`. Default value for newly created local repo is `src` and seems suddely to be a problem. Worked rougly 2-3 weeks ago.

![grafik](https://user-images.githubusercontent.com/17437789/48920550-c4905380-ee99-11e8-9567-7033ed086c74.png)

**Comment by larshp** [comment]
taking a look
