### ISSUE TITLE
staging screen, columns

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2120]
expect the "ignore remove reset" commands to be in the next column

![image](https://user-images.githubusercontent.com/5888506/48771539-f77fef00-ecc1-11e8-8acf-55c0d9ad3ac1.png)

**Comment by flaiker** [comment]
Probably caused by #2061

**Comment by larshp** [comment]
yeah, plus its probably an easy fix, just add "<td></td>" somewhere, pull requests welcome
