### ISSUE TITLE
External changing of starting folder creates a package with "_SRC"

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2125]
Observed a strange bug.
- I had a repo with the source in the root
- moved all (*.abap, *.xml) to the `src` subfolder and changed `.abapgit.xml` appropriately - externally, not via abapgit !
- Pulled the change into the system
- AG created a subpackage with `_SRC` suffix. An empty one.

![image](https://user-images.githubusercontent.com/15635498/48867333-86822980-edde-11e8-84d9-bf54272518e0.png)

.abapgit content just in case
```xml
  <DATA>
   <MASTER_LANGUAGE>E</MASTER_LANGUAGE>
   <STARTING_FOLDER>/src/</STARTING_FOLDER>
   <FOLDER_LOGIC>PREFIX</FOLDER_LOGIC>
   <IGNORE>
    <item>/.gitignore</item>
    <item>/LICENSE</item>
    <item>/.travis.yml</item>
    <item>/changelog.txt</item>
    <item>/abaplint.json</item>
    <item>/README.md</item>
    <item>/CONTRIBUTING.md</item>
   </IGNORE>
  </DATA>
```

**Comment by larshp** [comment]
might be related to #2113

**Comment by sbcgua** [comment]
Tried to re-create. No extra packages created. So seems to work now. Closing.
