### ISSUE TITLE
Regressions after 'Open in master language'

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2132]
to #2105 

- `cl_abap_syst=>get_logon_language( )` dumps on 7.31 (several places)
- `MESSAGE |Repository opened in a new window| TYPE 'S'` too

**Comment by christianguenter2** [comment]
@flaiker first one is your turn ;-)

**Comment by flaiker** [comment]
:/ I guess not having access to the logon language is why the RFC language switching "feature" works in the first place.
What's the dump though? Does the method already exist?

**Comment by larshp** [comment]
`MESSAGE |Repository opened in a new window| TYPE 'S'.`

 what ABAP version are you running, plus what is the syntax error?

**Comment by sbcgua** [comment]
`cl_abap_syst=>get_logon_language` - yeap, the method does not exist in 7.31

`MESSAGE |Repository opened in a new window| TYPE 'S'.` - syntax error, 7.31 does not accept string templates as an input (changing to '' worked)

**Comment by flaiker** [comment]
Should be fixed now. Can you check @sbcgua ?

**Comment by sbcgua** [comment]
@flaiker yeap, work now. Thanks ! :+1: 
Closing then.
