### ISSUE TITLE
Parallel serialization follow up

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2137]
- ~~error handling via log?~~
- ~~user information~~
- ~~parallel_generators to exit~~

**Comment by sbcgua** [comment]
- imho parallel_generators should be better in settings (or both settings and exit). Most will just need the simplest option.
- idea: request remote in a subtask too. When local serialization finish, remote will be received already.

**Comment by larshp** [comment]
dont remember what I meant with the first 2 tasks. Subtask and remotes, this is a different issue.

Scope for this issue:
instead of hardcoding `parallel_generators`, allow the user to specify this, either in user exit(see ZIF_ABAPGIT_EXIT) or in global settings.
https://github.com/larshp/abapGit/blob/cb341e778fe3ced8c15ff2b8a317228556cc9d52/src/zcl_abapgit_serialize.clas.abap#L91

**Comment by sbcgua** [comment]
by the way, on this subject. What about integrating [this](https://github.com/sbcgua/abap-threads) into AG ?

Final expectation:
1. just one task is awaited in the main thread -> opens a possibility to do something in the mean while e.g. fetching remote
2. possibility to auto create FM with parallelization (like ZABAPGIT table) - the code will be unified, not much need to keep it in the repo - as a consequence parallel serialization in single-file AG version

**Comment by larshp** [comment]
having dependencies in abapGit is difficult, as there is nothing to bootstrap it

the design goals are
* Easy installation
* Easy upgrade
* Small system footprint

for any other kind of project, yea sure

**Comment by sbcgua** [comment]
I actually mean integrating it inside, no deps.

**Comment by sbcgua** [comment]
and change the namespace too

**Comment by larshp** [comment]
good first issue, scope described in https://github.com/larshp/abapGit/issues/2137#issuecomment-538889746

@sbcgua please move other tasks to new issues

**Comment by sbcgua** [comment]
hmmm, do you mean parallel serialization ? The remote parallel fetch is indirectly related to #3008 and #2664 . Not sure it would be possible without them. So I consider them as followups.

**Comment by larshp** [comment]
I've moved the scope from this task to a https://github.com/larshp/abapGit/issues/3280

@sbcgua anything outstanding that is not covered in #3008 / #2644 ?

**Comment by sbcgua** [comment]
> anything outstanding in this issue that is not covered in #3008 / #2644 ?

From my perspective no. So i guess this one can be closed
