### ISSUE TITLE
Reset local kills whole class (while have to kill just local test include)

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2139]
1) Created unit test class (here: for `ZCL_ABAPGIT_REPO`), commited it **to a new branch**
2) switched back to **master**, pulled
3) The test include remained (as a new file to commit, although se80 does not see it) - this might be a bug by itself (maybe a separate issue?)
4) Go to advanced -> Reset local -> note the text in the screenshot - it mentions **the whole class**

![2018-11-23_22h43_55](https://user-images.githubusercontent.com/15635498/48960013-4d7abe00-ef72-11e8-8686-8d6ae6a5245e.png)

5) Tick it and press OK...
6) ... And yes, the class is deleted, AG dies in dump ...

P.S. to restore: created a one-file ag and made another Reset local there - it re-created the class from remote master.

**Comment by larshp** [comment]
duplicate of https://github.com/larshp/abapGit/issues/1066 ?

**Comment by sbcgua** [comment]
yes, looks like. Closing then.
