### ISSUE TITLE
Offline: add "reset local" function

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2150]
with the new 2 step zip import, it would be nice to have the same "reset local" functionality as for online repos.

This can be used to clean up(delete) old objects, and move objects between packages

Example, the following diffs are caused by removed or moved objects,
![image](https://user-images.githubusercontent.com/5888506/49005619-744e1580-f167-11e8-8bc7-284d898bfb49.png)

**Comment by sbcgua** [comment]
I can have a look.
I would also add here another fix - on new repo checksums are not created which makes first status a bit strange (at least for offline projects). Should be a simple fix

**Comment by sbcgua** [comment]
Regarding "checksums for initial repo"

Added rebuild_checksums to `SERVICE_REPO->NEW_OFFLINE`. But this is a temporary solution. Final should be done within #2086. The problem: online should also calculate localchecksums at the beginning. But only based on local files. However `rebuild_local_checksums` is redefined in online and requests remote. This will make initial checksums not exectly initial. So after refactoring of `rebuild_local_checksums` the idea is to add a flag forcing local only rebuild and move the call somewhere to a more core place closer to repo or repo svr.

**Comment by sbcgua** [comment]
can be closed ?
