### ISSUE TITLE
UI: transport icon change, minor

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2153]
Propose to change transport icon. From lock to something else, e.g. suitcase (other suggestions welcomed too - https://octicons.github.com/)

![image](https://user-images.githubusercontent.com/15635498/49046348-81f1b280-f1dc-11e8-9056-030424e9b1d9.png)

![image](https://user-images.githubusercontent.com/15635498/49046353-8918c080-f1dc-11e8-99e8-33413bfeb298.png)

Reasons:
- lock is used to denote that repo blocked from changes. So it is confusing to see it in lines
- intuitive reaction of unbiased users (some of my colleagues) on this icon is that the object is somehow blocked and has issues, it does not occur to them that this is related to transport

**Comment by sbcgua** [comment]
![2018-11-27_10h50_48](https://user-images.githubusercontent.com/15635498/49069604-5699b280-f232-11e8-9dc0-1b7c404dcab5.png)

**Comment by flaiker** [comment]
The idea behind the lock icon was that it is recognizable from SE01 (at least for me it's very common to see it there next to the objects):
![image](https://user-images.githubusercontent.com/5270359/49090961-21578980-f25f-11e8-8353-e55039fd1404.png)

Also the icon only shows up if the object _is locked_ in a transport and not for non-locking transports, like transport of copies.

But that might be just me. If another icon is better suited for it or it leads to confusion feel free to change it :)

**Comment by sbcgua** [comment]
Yeah that makes sense. I guess all options will be subjective depending on a person ... in my understanding the briefcase icon represents "in transport".
My own "hard" argument is the first one - the same icon represent different meaning which is bad - but this one can also be solved changing the "write protected repo" instead ... also an option.
The second argument is more an observation of colleagues' reaction (which is, on the other hand, unbiased).
So not sure how to decide :) We need a third opinion I think.

**Comment by flaiker** [comment]
If only there was the iconic transport truck icon available...

**Comment by sbcgua** [comment]
:) Had the same idea but only found the briefcase

**Comment by sbcgua** [comment]
Let's close probably. Can be reopened if needed
