### ISSUE TITLE
Start abapGit with package

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2160]
To improve the eclipse integration with [abap CI](https://github.com/andau/abapCI) we need the possibility to set a parameter before starting abapGit so the repo according to that package is opened automatically.

**Comment by christianguenter2** [comment]
https://github.com/andau/abapCI/issues/17

**Comment by larshp** [comment]
Any thoughts on how to implement this?

**Comment by christianguenter2** [comment]
Yes :-) Submitted PR

**Comment by larshp** [comment]
closing
