### ISSUE TITLE
Switch for offline work

### ISSUE THREAD

**Issue by Dave94** [larshp/abapGit#2161]
Is there any "switch" to turn off all http requests? Some systems doesn't have connection to outside world and gui is loading very slowly (probably because of waiting for http requests to have timeouts).

**Comment by larshp** [comment]
Systems, are you referring to backend or frontend?

The frontend(client PC) does some http calls to fetch [external libraries](https://docs.abapgit.org/other-external-libraries.html), also see https://github.com/larshp/abapGit/issues/1479

**Comment by Dave94** [comment]
Hmmm... the client PC doesn't have and internet access and the SAP system. Every refresh of the main page takes sooo long. 

![image](https://user-images.githubusercontent.com/9119187/49142838-fb32f780-f2f9-11e8-9438-9a2b03fd7894.png)

**Comment by Dave94** [comment]
This is the example. If I run abapgit from SE38 It shows the code for some time even the session is responsible (blinking cursor in the transaction field).
![image](https://user-images.githubusercontent.com/9119187/49142983-4cdb8200-f2fa-11e8-905a-380178251d86.png)

**Comment by larshp** [comment]
try commenting the following line to see if it helps, https://github.com/larshp/abapGit/blob/master/src/ui/zcl_abapgit_gui_asset_manager.clas.abap#L268

**Comment by Dave94** [comment]
Yup! that solved the issue 👍

**Comment by larshp** [comment]
problem is just that the icons are not shown, I would like to have custom abapGit icons, so the dependency to https://github.com/larshp/abapGit/issues/1479 can be removed

**Comment by Dave94** [comment]
Thank you for immediate response and for help to resolve this frustrating problem 👍
