### ISSUE TITLE
abapgit program for 701 or 702

### ISSUE THREAD

**Issue by thilak1** [larshp/abapGit#2162]
Hi All,

I am trying to implement abapgit in our SAP system(ABAP 701). I came to know that the minimum version required is 702.
If anyone have abapgit program for ABAP 701, please let me know. or at least share the program developed for 702 so that I will try to fix the syntax errors and implement it.

Thank you.

**Comment by larshp** [comment]
also see https://github.com/larshp/abapGit/issues/789 + https://github.com/larshp/abapGit/issues/46

**Comment by thilak1** [comment]
Hi, 
Yes. Thanks for the quick suggestion.
I'm exploring different possibilities.
