### ISSUE TITLE
Translation of abapGit itself

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2167]
Currently all abapGit development and messages is done in English. It is currently the only way it will work, as the code is merged to the [build](https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap).

Suggest adding the possibility to have real text elements for texts, this will require changes to the `abapmerge` tool

**Comment by flaiker** [comment]
Is this worth the effort? Afaik lots of developer tools are english only nowadays and continuously keeping translations up to date is a pain.

**Comment by larshp** [comment]
worth the effort: no

**Comment by larshp** [comment]
move to #2368
