### ISSUE TITLE
Dump: After Save Repo Settings - Folder Logic Full

### ISSUE THREAD

**Issue by mnemotron** [larshp/abapGit#2171]
ABAPGIT Version: 1.80.0

I got a dump after saving the repository settings folder logic full.

Some screenshots from the dump:
![2018-11-29_20-56](https://user-images.githubusercontent.com/25267138/49248099-3b3ccc00-f419-11e8-83cc-1927f2613c25.png)
![2018-11-29_20-48](https://user-images.githubusercontent.com/25267138/49247816-81456000-f418-11e8-96ec-efbaf4e08e21.png)
![2018-11-29_20-49](https://user-images.githubusercontent.com/25267138/49247817-82768d00-f418-11e8-9ab3-5ff8ac0594eb.png)
![2018-11-29_20-49_1](https://user-images.githubusercontent.com/25267138/49247819-83a7ba00-f418-11e8-8ef2-56b417a80056.png)

**Comment by mnemotron** [comment]
Hi, I use the SAP JAVA GUI 7.50 on Linux.

**Comment by larshp** [comment]
yeah, there is quite some trouble with the JAVA GUI, see other open issues

**Comment by mnemotron** [comment]
Hi,

I think the problem is, that the field symbol <ls_requirement> is only assigned for the first time in case 'com', but case 'pat' is processed first.

![grafik](https://user-images.githubusercontent.com/25267138/50078242-c0302f80-01e6-11e9-973e-da3b6a927d07.png)

**Comment by larshp** [comment]
yeah, the code assumes that the UI sends the fields in a specific order

**Comment by larshp** [comment]
@mnemotron try again, latest version

**Comment by mnemotron** [comment]
Hi, its working. Thanx.

**Comment by mnemotron** [comment]
But I get another dump after saving the repository settings.
This occurs only sporadically.

Some screenshots from the dump:

![grafik](https://user-images.githubusercontent.com/25267138/50571936-2c4d8e80-0db6-11e9-964a-6061c7f8f6cc.png)

![grafik](https://user-images.githubusercontent.com/25267138/50571939-3c656e00-0db6-11e9-9934-0e75fe3e7d45.png)

![grafik](https://user-images.githubusercontent.com/25267138/50571943-53a45b80-0db6-11e9-849b-ce697d8f4675.png)
