### ISSUE TITLE
Class not available in local nor remote repository

### ISSUE THREAD

**Issue by matt1as** [larshp/abapGit#2184]
After playing with branching and trying to find a good Pull Request strategy, suddenly one of my classes (the one used for testing this) has disappeared from both the local and remote repository. It's still available in the object directory and I can transport it as normal.

It seems the abapgit local repository is out of sync with the object directory.

I don't have any steps to reproduce this, as I'm not sure when it disappeared.

Running CRM 7.5 sp 11 and using Eclipse for development.

**Comment by larshp** [comment]
So the class exists but does not show up in the list in ZABAPGIT? Is it in the right package? Can you add a few screenshots?

**Comment by matt1as** [comment]
Now I feel stupid, but this class is in the wrong package ( outside of my repository ) .... Closing the issue
