### ISSUE TITLE
After Update to 1.80.0: Maximum number of GUI sessions reached (S/4 1809, ABAP 7.53)

### ISSUE THREAD

**Issue by MDJoerg** [larshp/abapGit#2187]
Hi,

after updating to the new version 1.80.0 there are errors after refreshing a repository. I think this comes from the new parallelization feature? In this system the refresh action opens 14 threads (info in status line). In another system with the same abap stack release 753SP0 only 1 thread is opened. The difference is 20 to 9 dialogue processes?!

If there a way to influence this feature? For example switch off or set a maximum of threads?

Thx Joerg

![grafik](https://user-images.githubusercontent.com/41207683/49550004-a4758100-f8ea-11e8-8453-f7ec757c5cf4.png)

![grafik](https://user-images.githubusercontent.com/41207683/49549881-552f5080-f8ea-11e8-9c01-5c0fc4433fc7.png)

![grafik](https://user-images.githubusercontent.com/41207683/49549915-6ed09800-f8ea-11e8-8e3f-6b0ef38570d3.png)

![grafik](https://user-images.githubusercontent.com/41207683/49549941-7ee87780-f8ea-11e8-8daf-507a78da840c.png)

**Comment by MDJoerg** [comment]
the call of function SPBT_INITIALIZE returns 14 and will be set to 13. But it seems to be to much for other system restrictions like max number of SAPGUI sessions? 
If I set it to 1 all is fine. If I set 6 and have other open GUI Sessions open I run in this error too.

![grafik](https://user-images.githubusercontent.com/41207683/49584373-695f6600-f95b-11e8-8f05-2cce165e24c7.png)

**Comment by MDJoerg** [comment]
Hi Lars,

in my systems I have 12 parallel SAPGUI sessions (RZ10 parameter rdisp/max_alt_modes). The function module SPBT_INITIALIZE returns 14 free processes. I think checking the available user sessions with TH_USER_INFO is a better way to detect free ressources?

The following code works for me:

  METHOD determine_max_threads.

    IF iv_force_sequential = abap_true.
      rv_threads = 1.
      RETURN.
    ENDIF.

    IF gv_max >= 1.
* SPBT_INITIALIZE gives error PBT_ENV_ALREADY_INITIALIZED if called
* multiple times in same session
      rv_threads = gv_max.
      RETURN.
    ENDIF.

    CALL FUNCTION 'FUNCTION_EXISTS'
      EXPORTING
        funcname           = 'Z_ABAPGIT_SERIALIZE_PARALLEL'
      EXCEPTIONS
        function_not_exist = 1
        OTHERS             = 2.
    IF sy-subrc <> 0.
      gv_max = 1.
    ELSE.
* todo, add possibility to set group name in user exit
      CALL FUNCTION 'SPBT_INITIALIZE'
        EXPORTING
          group_name                     = 'parallel_generators'
        IMPORTING
          free_pbt_wps                   = gv_max
        EXCEPTIONS
          invalid_group_name             = 1
          internal_error                 = 2
          pbt_env_already_initialized    = 3
          currently_no_resources_avail   = 4
          no_pbt_resources_found         = 5
          cant_init_different_pbt_groups = 6
          OTHERS                         = 7.
      IF sy-subrc <> 0.
*   fallback to running sequentially. If SPBT_INITIALIZE fails, check transactions
*   RZ12, SM50, SM21, SARFC
        gv_max = 1.
      ENDIF.
    ENDIF.

    IF gv_max > 1.
      gv_max = gv_max - 1.
    ENDIF.

* begin workaround max sapgui sessions reached
    DATA: lv_act_user TYPE i.
    DATA: lv_max_user TYPE i.
    DATA: lv_available_user TYPE i.

    CALL FUNCTION 'TH_USER_INFO'
      IMPORTING
        act_sessions = lv_act_user
        max_sessions = lv_max_user.

    lv_available_user = lv_max_user - lv_act_user - 1.

    gv_max = COND #( WHEN lv_available_user < 0
                     THEN 1
                     ELSE lv_available_user ).
* end workaround max sapgui sessions reached



    ASSERT gv_max >= 1.

    rv_threads = gv_max.

  ENDMETHOD.

Best Regards
Joerg

**Comment by larshp** [comment]
I dont think there is anything wrong with the parallel execution or determining threads. 

Usually this kind of error is due to some of the code triggering UI, which it is not supposed to do when serializing, suggest trying to identify where/if UI is triggered.

Try setting number of threads to 1, and add a breakpoint for ABAP statement `CALL SCREEN`

**Comment by MDJoerg** [comment]
The problem still exists with abapGit 1.84.0 (same system) and the workaround works fine. 
one small change required: gv_max -> gv_max_threads.

**Comment by larshp** [comment]
Jakub did some testing a few days ago, see #2397, again, this looks like a bug in SAP standard

**Comment by jfilak** [comment]
Yep, I had to turn of parallel serialization off. However, I am 99% sure the problem is caused by OO stuff because DDIC parallel serialization didn't suffer from the GUI maximum sessions issue.

https://github.com/larshp/abapGit/issues/2397#issuecomment-463750745

**Comment by SebastianWolf-SAP** [comment]
I found the root cause. The class serialization process (and as well probably all other source code-based objects) checks the pretty printer settings during processing. The call to function module RS_WORKBENCH_CUSTOMIZING invokes cl_gui_sourceedit=>is_control_supported( ) (LOAD-OF-PROGRAM in Top-Include of WB_CUSTOMIZING) which internally creates a new GUI session per call. Once you comment this check, everything works fine.

However, as it's deep within standard code, any solution might take some time. I'll follow up internally.

**Comment by SebastianWolf-SAP** [comment]
SAP Note 2759002 should fix the issue. Please report back in case there are additional issues with it!

**Comment by MDJoerg** [comment]
Confirmed: SAP Note 2759002 solved the issue and is released for ABAP753 now.
