### ISSUE TITLE
Sapscript : sequence of Windows in tdlines files

### ISSUE THREAD

**Issue by CCapa** [larshp/abapGit#2188]
Hello,
I have tested the export function to export a Sapscript in a file to do code review.
I have the following issue :
- I export the sapscript in a file.
- I do a modifciation the sapscript in a specific language (suppose it is EN).
- Then I export the new version of the sapscript in a file. But the sequence of the windows in the file (xxxxxxxxxxgit.form.tdlines_eb.xml) is not the same than before.
So it is not possible to compare the two files in Github due to the difference of sequence (a lot of lines are not at the same position).
The sequence is modified after each sapscript modification.

I have done a modification in the code in **method _read_form** of class **zcl_abapgit_object_form** and the issue is fixed (see in following screen shots). The code is added just after the call to FM 'READ_FORM'.
If it looks fine for you I will do a pull request.

![image](https://user-images.githubusercontent.com/22550208/49616333-bae61000-f9b0-11e8-8c15-bf4857f7d14c.png)
![image](https://user-images.githubusercontent.com/22550208/49617925-d9e7a080-f9b6-11e8-844b-0ad6219abd98.png)

Thanks

**Comment by larshp** [comment]
seems okay, feel free to open a PR

I have a few comments but I'll add those in the PR

**Comment by larshp** [comment]
merged, guess this can be closed
