### ISSUE TITLE
offline: everything matches after import zip

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2189]
in case everything matches after importing a zip to offline repo, it is difficult to tell if something went wrong or everything is okay, suggest showing a text "loaded"/"everything matches"/something

**Comment by sbcgua** [comment]
Makes sense. Might have a look on the weekend.

**Comment by sbcgua** [comment]
![image](https://user-images.githubusercontent.com/15635498/49689070-619eed80-fb24-11e8-8add-e2a1c2da2c2c.png)
