### ISSUE TITLE
When sy-cprog = ZABAPGIT_FULL, disable parallel

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2208]
sometimes when upgrading ZABAPGIT it gives syntax errors due to dumps, so I keep a full ZABAPGIT_FULL single report as backup, however it will run in parallel triggering the syntax error

**Comment by sbcgua** [comment]
imho, "When sy-cprog <> ZABAPGIT". Others may use different names (e.g. ZABAPGIT_TEMP in my case)

**Comment by larshp** [comment]
yeah, good idea, agree

**Comment by larshp** [comment]
hmm, however when called via API it should also use parallel, eg https://github.com/abapGit/ADT_Backend

**Comment by sbcgua** [comment]
ok, maybe ... create a variable of ZIF_ABAPGIT_???? type and check the full type name with typedescr  classes ? In case of one-file-install this will be a local name if I understand well (my guess) and a global interface in other cases

**Comment by pokrakam** [comment]
First thought would be to scan for the abapmerge footer, but perhaps a more convenient marker could be added to abapmerge. 
```
CLASS lcl_abapmerge_marker DEFINITION. 
  PUBLIC SECTION. 
ENDCLASS.
```

 and in abapgit: 
```
TRY. 
CREATE OBJECT TYPE ('LCL_ABAPMERGE_MARKER').
  <disable parallel>
  CATCH... 
ENDTRY.
...
```

**Comment by larshp** [comment]
should work now

**Comment by larshp** [comment]
closing
