### ISSUE TITLE
create OTR concept should check if it already exist or not

### ISSUE THREAD

**Issue by i317513** [larshp/abapGit#2209]
Dear colleagues:
    When I try to use ABAPGIT to sync exception class code I got an error "Error from SOTR_CREATE_CONCEPT". I debug a little bit and found there is a message "The alias name XXXalready exists" from FM "BTFR_CHECK". It means the OTR alias already exists in the local system. I think ABAPGIT should check if the current OTR concept exists: if yes delete it and create it again, or just ignore the "existing" message continues to sync code.

**Comment by larshp** [comment]
sounds right, can the issue be reproduced? Suggest creating a public repo with dummy code to demonstrate the issue

**Comment by i317513** [comment]
HI:
    I have an SAP GitHub to reproduce this issue, but if the target system does not contain related OTR concept/Alias, there will be no error.
   Please check sap github: https://github.wdf.sap.corp/i317513/Z_CX_OT_GENERIC

**Comment by i317513** [comment]
Hi:
    Since my internal SAP system cannot link to GitHub public. I manually copy all dummy code file into one public Github repo: https://github.com/i317513/ABAPGIT_SOTR
   Before you sync this code to your local, open t-code: SOTR_EDIT, create a new OTR:
>  Language: English
>    Text: anything
>     Alias: $TMP/FENGLEI-> same as the file in GitHub "zcx_test_fl.clas.xml" alias
    Save this OTR.
    Then try to sync the code from above GitHub, you should get an error "ERROR from 
    SOTR_CREATE_CONECPT", then the whole process will be canceled.

BRs
FengLei

**Comment by larshp** [comment]
Thanks

one tip, you can use the menu Advanced -> Package to zip to export all files to zip, which then can be uploaded to github from local pc using normal git tools

**Comment by filak-sap** [comment]
There is no need to do neither manual copy nor export to zip. You have git, the best source code management tool.

```bash
git clone https://github.wdf.sap.corp/i317513/Z_CX_OT_GENERIC
cd Z_CX_OT_GENERIC
git remote add public https://github.com/i317513/ABAPGIT_SOTR
git push public HEAD:master
```

**Comment by i317513** [comment]
Thanks for your advice, that's convenient~ 👍

**Comment by larshp** [comment]
basic example with CLAS and SOTR added in https://github.com/abapGit-tests/CLAS_with_SOTR

**Comment by larshp** [comment]
related issue: https://github.com/larshp/abapGit/issues/2320

**Comment by larshp** [comment]
@i317513 PR #2435 opened

it should now skip the creation if it already exists, its dangerous just deleting it, it might belong to something else

**Comment by larshp** [comment]
@i317513 try again, latest version
