### ISSUE TITLE
GUI: Refactor page logic

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#221]
following #202 

- [x] gui_page super class
- [x] fix bottom logo style (css)
- [x] common title logic concept
- [ ] implement title logic in all pages
- [x] refactor title design (alignment)

### New page logic
- each page must inherit from `lcl_gui_page_super` and redefine IF methods
- page super implements:
  - `header` (html header) - may import additional style (specific for page), see page_diff
  - `footer` (html footer) - may import scripts (preparation for image rendering, etc ...)
  - `title` (page title) - logo, page name, may import menu to be displayed on the right side, see page_main
  - to be continued ... 

### lcl_html_toolbar
Some updates here also. Changed interface a bit. Now able to render down lists if `iv_as_droplist_with_label` is specified and also include dropdown items to menubars.
In particular *DB Persistency moved to special beta menu item*, built in `page_main->build_menu()`

### History:
- (cancelled) lcl_gui -> singleton - I thought that maybe for this case it is not so important. Currently no benefits from singleton although it is more proper way. Maybe later
- (cancelled) refactor event handling - initially thought to move some of logic to GUI (in particular page routing) but after some analysis I think that it would be clearer just to split main_page logic ... will think yet.

**Comment by sbcgua** [comment]
@larshp could you please keep gui staff unmodified for a while ... I'm adjusting all pages definitions - it will be a hell to integrate changes :) I'll try to finish today.

**Comment by larshp** [comment]
yes, sure. I have real-world stuff to do this weekend, so I'll not be doing very much open-source work.

**Comment by sbcgua** [comment]
I'm currently working from laptop with win10, IE11 and GUI7.4 ... might overlook some legacy issues for GUI7.3 and IE7 emul

**Comment by sbcgua** [comment]
**IMPORTANT !**
DB link moved to dropdown menuitem "Beta" at the end of main menu. In code it is now controlled by `page_main->build_menu()`

**Comment by larshp** [comment]
tested it a bit more, the dropdown does not work in IE9, works okay in IE11. Tested outside of SAP GUI

However example http://www.w3schools.com/css/tryit.asp?filename=trycss_dropdown_button works in IE9

**Comment by sbcgua** [comment]
Dropdown: that's the example I took the inspiration from :) Hmm, I cannot check now - I have just IE11 and when I switch the IE7 emulation in IE11 it works as well ... I think I'll be able to check only when I return home on weekend.

This is GUI7.3+IE11:
![image](https://cloud.githubusercontent.com/assets/15635498/15475004/e9d21df2-2107-11e6-8a91-330a149f9af1.png)

> The db link is not important for end user functionality, I would like to hide the link to db, but dont have any good idea as to where (from merge request)

Well, if this functionality exists then someone needs it, and so it should be clearly accessible :) That's why I though of dropdown to hide it a bit deeper. (I hope I make it work in IE7 too - another option is a separate page with secondary features but it would look ugly imho)

**Comment by sbcgua** [comment]
Dropdown: that's the example I took the inspiration from :) Hmm, I cannot check now - I have just IE11 and when I switch the IE7 emulation in IE11 it works as well ... I think I'll be able to check only when I return home on weekend.

This is GUI7.3+IE11:
![image](https://cloud.githubusercontent.com/assets/15635498/15475004/e9d21df2-2107-11e6-8a91-330a149f9af1.png)

> The db link is not important for end user functionality, I would like to hide the link to db, but dont have any good idea as to where (from merge request)

Well, if this functionality exists then someone needs it, and so it should be clearly accessible :) That's why I though of dropdown to hide it a bit deeper. (I hope I make it work in IE7 too - another option is a separate page with secondary features but it would look ugly imho)

**Comment by larshp** [comment]
I fixed it in https://github.com/larshp/abapGit/commit/f51ad48015d486cb92030ea5e2f76375aafc6ec7 :smile:

**Comment by sbcgua** [comment]
Magic trick 8() - ways of IE are strange :)
BTW will add a commit in a moment to skip DOCTYPE for html indentation. 

P.S. I suggest closing this issue. There is yet a subtask to implement title in all other pages but I think I'll come to that eventually but later.

**Comment by larshp** [comment]
closing as suggested above
