### ISSUE TITLE
Cleanup classes package assignment

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2217]
Seems like some classes can be moved around ?

- ZCL_ABAPGIT_HTTP_CLIENT -> $ABAPGIT_HTTP
- ZCL_ABAPGIT_LONGTEXTS -> $ABAPGIT_OBJECTS
- ZCL_ABAPGIT_OBJECT_ENHC -> $ABAPGIT_OBJECTS
- ZCL_ABAPGIT_STRING_UTILS -> $ABAPGIT_UTILS

P.S. maybe create a subpackage for repo, stage, transports related classes ? And maybe another one for CI related ?

**Comment by larshp** [comment]
yea
