### ISSUE TITLE
Design: main page polish, images, refactoring

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#223]
Follows from #202 

- [x] fine tune design & code
- [x] implement images
- [MOVED] ?? split the class (it is too heavy already)

**Comment by sbcgua** [comment]
OK, the design looks fine for me now :) Main and diff pages I mean of course :)

**Comment by sbcgua** [comment]
![image](https://cloud.githubusercontent.com/assets/15635498/15633024/a377e2d0-25ab-11e6-9951-fbd7d8acf5b3.png)

**Comment by sbcgua** [comment]
Comments for history:
- full size table should have width="100%" attribute
- I changed font-size to explicit number for more consistency and control
- there are modifier-classes
  - grey - makes text grey
  - emphasis - makes it bold (maybe overdoing with naming a bit ... ;)
  - attention - red (for errors and cancel buttons)
  - paddings - to add explicit padding to a div or area (e.g. for Empty package message)
- both emphasis and attention can be set to menu items in abap code

**Comment by larshp** [comment]
cool, it looks really nice now :smile:

**Comment by sbcgua** [comment]
Closing this one. 
I yet plan to make some events refactoring but I'll do it in separate task
