### ISSUE TITLE
Separate GUI core classes as a separate subpackage/repo

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2230]
@larshp the GUI has quite nice and reusable structure. What do you think about separation it into a separate project. At the first step it can be a separate subpackage with minor refactoring (mainly to move GUI constants from zif_definitions and some minor tweaks). And later maybe a submodule. Abapmerge should be adjusted as well, I have some ideas how to do it.

**Comment by larshp** [comment]
What is the problem we are trying to solve?

It must be separated properly, and ideally contained in the `/ui/` folder. Separating makes it more difficult to do eg. syntax check.

Depending on what we are solving, enabling package checks might help.

**Comment by sbcgua** [comment]
It is not a problem of AG certainly. Just an idea to make a part of code reusable for other projects. e.g. [this](https://github.com/sbcgua/abap_gui_boilerplate). The "separate repo" probably sounds too revolutionary, of course such a change should not create any complexities for ag. I think moving classes like gui, assetman, html and a couple of interfaces together with related constants to a subpackage of UI (e.g. UI_CORE) should be fine. Well maybe some changes to assetman too because it is not abstract enough. Of course if you agree.

**Comment by sbcgua** [comment]
I'm actually looking into abapmerge too :smiley:

**Comment by larshp** [comment]
yea, abapmerge might need a few changes too, but guessing its low effort

**Comment by sbcgua** [comment]
If you have time have a look - https://github.com/sbcgua/abap_gui_boilerplate
And here: https://github.com/sbcgua/abapGit/compare/before_gui_unification...sbcgua:gui_unification?expand=1

The last one is the code proposal. I can PR if looks OK.

**Comment by larshp** [comment]
I think there is some stuff we can use from it, but one step at a time.

Definitely a good idea to move `zif_abapgit_definitions=>c_action` to a new place.

**Comment by sbcgua** [comment]
Guess can be closed, done in #2525
