### ISSUE TITLE
One GIT in 2 packages

### ISSUE THREAD

**Issue by mfallen** [larshp/abapGit#2234]
I want to install abap2xlsx.

Was already installed with old nugget program, now I want to switch to GIT.

When installed first time, I moved the demo programs into my $TMP pacakge, while the "real" classes, data elements, ... are stored in package Z_EXCEL.

Now I get an error when trying to PULL:
"error from SEO_CLASS_CREATE_COMPLETE
OTR-Based Exception of Class: ZCX_ABAPGIT_EXCEPTION"

Seems to be an error with more than one package?

Any ideas?

**Comment by christianguenter2** [comment]
Can you set a breakpoint at FM SEO_CLASS_CREATE_COMPLETE and check what sy-subrc is and for which class the error occurs?

**Comment by mfallen** [comment]
Sure!
It's class ZCL_EXCEL, sy-subrc = 5

Error comes from FM SEO_CLIF_SAVE_ALL, sy-subrc = 2

**Comment by larshp** [comment]
this might be related to https://github.com/larshp/abapGit/issues/2209

**Comment by larshp** [comment]
its quite difficult when you had some of the application in non-transported package and some in transported package, suggest deleting it all and reinstalling, or alternatively move everything to a common package

**Comment by larshp** [comment]
@mfallen any luck?

**Comment by mfallen** [comment]
> @mfallen any luck?

Yes, working now. Need to delete all programs etc. out of &TMP and start again :-)

**Comment by larshp** [comment]
yeah, its a bit of a mess when its not split up

closing

**Comment by schealex** [comment]
sorry to open this again but as referenced by andkopp i've got the same issue but i am not able to resolve it. As i'm also quite new to ABAP i may need further assistance if you guys would be so kind to provide it :)

**Comment by mfallen** [comment]
> sorry to open this again but as referenced by andkopp i've got the same issue but i am not able to resolve it. As i'm also quite new to ABAP i may need further assistance if you guys would be so kind to provide it :)

Just delete programs/classes/... from second package and try again

**Comment by schealex** [comment]
How do I know what the second package is and where I need to delete those?

mfallen <notifications@github.com> schrieb am Mi., 20. Nov. 2019, 09:18:
