### ISSUE TITLE
Reset local, table maintenance function group, "PROG, error updating"

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#2235]
RPY_PROGRAM_UPDATE raises PERMISSION_ERROR (subrc 2)
Seems like the *T00 includes in a function group cannot be edited by a normal user? There's also the flag editor-lock set in the program attributes.

![image](https://user-images.githubusercontent.com/5270359/50510830-7fa89f80-0a8b-11e9-884c-3ee4986ea511.png)

![image](https://user-images.githubusercontent.com/5270359/50510801-643d9480-0a8b-11e9-9f15-9d18069b261c.png)

![image](https://user-images.githubusercontent.com/5270359/50510993-1aa17980-0a8c-11e9-9344-d01a2d41d883.png)

![image](https://user-images.githubusercontent.com/5270359/50511137-b3d09000-0a8c-11e9-9dfb-60eadb959999.png)

![image](https://user-images.githubusercontent.com/5270359/50511243-22155280-0a8d-11e9-8835-40707a491ccf.png)

**Comment by flaiker** [comment]
Hmmm, things I did not want to know about the table maintenance generator:
- The T00 include seems to be entirely generated by TOBJ objects.
- The editor lock cannot be removed using ABAP SQL (and I was unable to do it using Native SQL).
- SAP* cannot remove the editor lock either, because the user is not allowed to edit any programs. SAP* can also not reset the object in abapGit for the same reason.
- Function module `OBJ_GENERATE` might do the generation (based on a maintenance view or a view cluster)

So I guess the possibilities are to either change the way T00-includes are created / updated in abapGit, by finding a parameter or a function module that allows ignoring the editor lock and possibly additional checks based on the include name suffix and user - or ignore the T00-include entirely in abapGit and add some activation step to TOBJ objects that generates the include. The generation process however might create / overwrite other objects that do not have the editor lock and can be modified. So the first approach should be the one to go for.

The editor lock flag and SAP* user are cleared on serialization. Cloning abapGit-tests/FUGR_maintenance_view will result in an editable T00-include without editor-lock and by user sy-uname. When regenerating the maintenance dialogs it's SAP* and editor-lock = X again.

By the way: refreshing the repository in abapGit to see the changes after a regenerating the maintenance views is sometimes not enough. You have to actually leave and reenter abapGit (flaiker/ci-lib@75e1c5a75a2540ca059642268c80ae0aabdf943f and flaiker/ci-lib@5de9213799b8ce14f22ffdeae9ce7e5ce7ed3f91 were part of the same generation).

**Comment by flaiker** [comment]
Not sure how I failed to do it before but you can actually change EDTX (editor lock) in SE16 with table PROGDIR. Surprisingly that table has "Maintenance allowed".

**Comment by flaiker** [comment]
Removing the editor lock using `UPDATE_PROGDIR` before calling `RPY_PROGRAM_UPDATE` seems to work. Is that an acceptable solution?

**Comment by flaiker** [comment]
I am also not sure where these diffs come from: https://github.com/flaiker/ci-lib/commit/fa4635bbeb147e0723841dcd6378b7d9cfdaf9f3

**Comment by larshp** [comment]
yea, there are some issues with function groups

**Comment by larshp** [comment]
How can this issue be reproduced? A lot of the issue talks about the T00 include, however there is no diff in the screenshot, so I would expect it not to be updated?

**Comment by flaiker** [comment]
### Steps to reproduce
- Clone [FUGR_maintenance_view](https://github.com/abapGit-tests/FUGR_maintenance_view)
- Open table ZABAPGIT_UNIT_TE in SE54
- "Create / change" generated objects
- Change
- Expert mode
- Select everything, continue
- Refresh abapGit

/src/zabapgit_unit_te.fugr.lzabapgit_unit_tet00.xml shows this diff (which probably shouldn't even be there):
```diff
 ﻿<?xml version="1.0" encoding="utf-8"?> 
  <abapGit version="v1.0.0"> 
   <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0"> 
    <asx:values> 
     <PROGDIR> 
      <NAME>LZABAPGIT_UNIT_TET00</NAME> 
      <STATE>A</STATE> 
-     <VARCL>X</VARCL> 
      <SUBC>I</SUBC> 
      <RLOAD>E</RLOAD> 
-     <UCCHECK>X</UCCHECK> 
    </PROGDIR> 
   </asx:values> 
  </asx:abap> 
 </abapGit> 
```
(and all others includes also have diffs, mostly because of the generation timestamp comment)

- Reset local
- Select FUGR ZABAPGIT_UNIT_TE

### Expected behavior:
I expect all objects in the repo to be reset to the state on the remote.

### Actual behavior:
I get this error message and a half reset function group.
![image](https://user-images.githubusercontent.com/5270359/51340308-d7389a80-1a8e-11e9-96f2-e3ea0faf1352.png)

I am also surprised my initial screenshot doesn't show the diff. I might have clicked refresh at some other point in the steps.

**Comment by larshp** [comment]
Hi,
Looked through it, I guess with the solution in the pull request, the user will then be able to edit the T00 program in SE38 after deserialization? Which seems bad.

Suggest adding logic to skip updating PROGDIR for T00 includes, and instead focus on why VARCL + UCCHECK is set during deserialization

**Comment by larshp** [comment]
test repo: https://github.com/larshp/FUGR2

![image](https://user-images.githubusercontent.com/5888506/51436695-47633e00-1c92-11e9-9020-386fe97b0f00.png)
![image](https://user-images.githubusercontent.com/5888506/51436696-4a5e2e80-1c92-11e9-8352-f2197d02f107.png)

**Comment by larshp** [comment]
Okay, how about something like this, https://github.com/larshp/abapGit/compare/fugr?expand=1

SQLX: is now updated
VARCL: is cleared for everything, it seems like there is some magic which determines this, eg. after a SE54 regeneration, editing the include manually will set VARCL
UCCHECK: I'll argue that the blank values from SE54 are wrong, this value should be taken from the main function module program(not implemented in branch)

**Comment by flaiker** [comment]
👍 
These fixes definitely help.

It might not fix this specific issue though. Instead of just regenerating in SE54 you could change things like the dynpro numbers. Then not only the t00.xml will change (hopefully not anymore after these fixes) but also the t00.abap.

> Looked through it, I guess with the solution in the pull request, the user will then be able to edit the T00 program in SE38 after deserialization? Which seems bad.

Then maybe we should set EDTX again after deserialization? Currently it is already possible for everyone to edit the T00 program who cloned the repository (and did not regenerate in SE54) since EDTX is not serialized. So in theory, if you wanted to get around the editor lock using abapGit for this include you could uninstall the repo and install it again.

I also wonder if other object types use this kind of editor lock mechanism for their generated code.

**Comment by larshp** [comment]
yeah, also noticed it about EDTX, perhaps we should not clear EDTX?

**Comment by larshp** [comment]
Yeah, its just difficult as SAP is inconsistent. When generating the function group VARCL is set to blank, manually editing the file will set VARCL to 'X', I would not expect flags to change if just code is edited. So for VARCL I suggest not putting the field into the XML, as I guess it mostly does not matter in 702+

**Comment by flaiker** [comment]
Should I update #2289 then to include EDTX (+ UNAM if EDTX=X) serialization but keep the "workaround" in that clears the flag briefly on deserialization?

**Comment by larshp** [comment]
Suggest starting without the workaround, it seems quite evil

**Comment by flaiker** [comment]
Sure, I'll create a new PR then.

**Comment by flaiker** [comment]
Hmm, so I added EDTX and UNAM. https://github.com/flaiker/abapGit/commit/9906da0483b99d62cddd263f3ae83491d391efc6
I tried getting EDTX to work in normal programs for now, see https://github.com/abapGit-tests/PROG_EDTX

However, it seems like this UPDATE to the inactive progdir entry does not get copied to the active version, causing UNAM to not be changed.

https://github.com/flaiker/abapGit/blob/9906da0483b99d62cddd263f3ae83491d391efc6/src/objects/zcl_abapgit_objects_program.clas.abap#L557-L560

Does it work for VARCL? Seems like the object activation also just uses UPDATE_PROGDIR to copy the inactive entry over to active, therefore missing some fields.
![image](https://user-images.githubusercontent.com/5270359/54074136-39439e00-428f-11e9-9320-b639f895ffa0.png)

**Comment by larshp** [comment]
VARCL, idea is to exclude the field in the XML file, and let the system decide what it is. SAP standard seems to work in strange/inconsistent ways
