### ISSUE TITLE
AbapGit releases/tag

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2237]
IMHO I guess each release of AG and AG-related-tools should be accompanied with corresponding git tag (and probably release, which changelog abstract) :)
Would be helpful for this in particular #2236 and as a good practice in general

**Comment by larshp** [comment]
yes, see https://github.com/larshp/abapGit/issues/960

suggest closing this issue as duplicate

**Comment by sbcgua** [comment]
agree :) closing
