### ISSUE TITLE
Popup "New Offline Project" and Fiori theme, missing OK button

### ISSUE THREAD

**Issue by sambarza** [larshp/abapGit#2243]
In the popup for the creation of a new offline project the OK button is missing or better is there but without a text it's a quite difficult to find it ;-)

![image](https://user-images.githubusercontent.com/3630051/50543102-8a6b4d80-0bcd-11e9-92c1-f163fd65908c.png)

![image](https://user-images.githubusercontent.com/3630051/50543140-087c2400-0bcf-11e9-88fe-d0fb5b8f121a.png)

Thank you

**Comment by larshp** [comment]
thanks, do you want to make a pull request for it?

the file to edit is https://github.com/larshp/abapGit/blob/master/src/ui/zcl_abapgit_popups.clas.abap#L906
