### ISSUE TITLE
unknown syst_subrc type for 7.31

### ISSUE THREAD

**Issue by mem1b** [larshp/abapGit#2258]
![image](https://user-images.githubusercontent.com/1336470/50689364-c10bf280-1029-11e9-8ec3-40537ca05b3e.png)

syntax error occured on 7.31

https://github.com/larshp/abapGit/blob/1de94565677abd0be1a1ba441f8c629199948477/src/objects/zcl_abapgit_object_tabl.clas.abap#L621
https://github.com/larshp/abapGit/blob/1de94565677abd0be1a1ba441f8c629199948477/src/objects/zcl_abapgit_object_tabl.clas.abap#L705
https://github.com/larshp/abapGit/blob/1de94565677abd0be1a1ba441f8c629199948477/src/objects/zcl_abapgit_object_tabl.clas.abap#L799

**Comment by larshp** [comment]
thanks, fixing

**Comment by larshp** [comment]
@mem1b try again, latest version
