### ISSUE TITLE
Design: implement icons

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#226]
Following from #202

**Comment by sbcgua** [comment]
First approach to image loading: I've put it to page_super `class_constructor` so that it is called automatically and once. This, however, require that gui already initialized so I made `startup` public. But probably I'll make startup a class_constructor too for gui + singlton (if you don't mind).

Naming convention: images should be saved as `img/...`.

For history: js approach was also considered (below + example attached). But I decided to go abap because actually it makes cleaner html, cleaner references to imgs and less potential issues with browser version.

```js
var cssImages = {}; 
var reImage   = /^\.img_\w+$/;
var reImgData = /^(?:url\(")(.+)(?:"\))$/;

for (var i = 0; i < document.styleSheets.length; i++) {
  var rules = document.styleSheets[i].rules;
  for (var j = 0; j < rules.length; j++) {
    var styleName = rules[j].selectorText;
    var imgData   = rules[j].style.backgroundImage;
    if (!reImage.test(styleName)) continue;
    if (!imgData) continue;
    if (!reImgData.test(imgData)) continue;
    styleName = styleName.substring(1);
    cssImages[styleName] = reImgData.exec(imgData)[1];
  }
}

var images = document.images;

for (var i = 0; i < images.length; i++) {
  if (cssImages.hasOwnProperty(images[i].className)) {
      images[i].src = cssImages[images[i].className];
      images[i].className = '';
  }
}
```
[index.zip](https://github.com/larshp/abapGit/files/281038/index.zip)

**Comment by larshp** [comment]
ok :smile:

**Comment by sbcgua** [comment]
@larshp working now on icons and page_main optimization. I'm confused with repo online logic - is it certain than "unsupported" files are always at the beginning of the table ?

**Comment by larshp** [comment]
Yes, they will be at the top

Date: Thu, 26 May 2016 08:57:19 -0700

**Comment by sbcgua** [comment]
Another question: opinion needed. I'm moving all commands to repo menu area. However there are quite a lot of them. I guess how to emphasize "most relevant" commands. Options for the moment:

1) Dont care about such tuning

![2016-05-26_19h46_20](https://cloud.githubusercontent.com/assets/15635498/15584458/f4eabe2c-237a-11e6-8159-55ab32644f6d.png)

2) Color
![2016-05-26_19h47_26](https://cloud.githubusercontent.com/assets/15635498/15584472/001f6bee-237b-11e6-948c-6ad16f3e7144.png)

3) font style

![2016-05-26_19h46_34](https://cloud.githubusercontent.com/assets/15635498/15584467/fce8187c-237a-11e6-9617-2ad4979c527a.png)

4) ???

**Comment by larshp** [comment]
I like number 3, font style bold

Date: Thu, 26 May 2016 10:50:12 -0700

**Comment by mrsimpson** [comment]
+1: bold

**Comment by sbcgua** [comment]
Summary for history:
- images are loaded in `pages_super->load_images` which is called from it's `class_constructor`
- actual load routine located in `lcl_gui=>cache_image` which uses `html_viewer->load_data` for that. **Images are supposed to be PNG for now** - hardcode (but of course can be adjusted if required)
- images should start from `img/` prefix (just for "namespacing" and code readability) and consequently addressed like `<img src="img/...">`
- nice [site](https://www.base64-image.de/) to convert to base64
