### ISSUE TITLE
Replace 'Overwrite object' popup with list

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2279]
Currently we get a popup for each object. I'd suggest to replace it with a list.

![image](https://user-images.githubusercontent.com/17437789/51038598-ee214d80-15b3-11e9-9530-489e6742054e.png)

https://github.com/larshp/abapGit/blob/e809df8384d7d3c1b0321eae52b887e0cd2a4e38/src/ui/zcl_abapgit_services_repo.clas.abap#L243-L279

**Comment by larshp** [comment]
2 warnings,
![image](https://user-images.githubusercontent.com/5888506/51082331-41ef7c00-1705-11e9-94f7-a9b3cf5305b8.png)
