### ISSUE TITLE
How to influence on the displayed project name?

### ISSUE THREAD

**Issue by tricktresor** [larshp/abapGit#2296]
Hi!
Is it possible to influence on the project name that is displayed in the GUI?

![image](https://user-images.githubusercontent.com/29763439/51256214-21455180-19a5-11e9-99b9-9ae4f7428d72.png)

It becomes quite confusing if there many projects...

Thanks
Enno

**Comment by tricktresor** [comment]
Maybe it could help to include or group by the owner of the repository...?

**Comment by flaiker** [comment]
Clicking on the hamburger menu icon 
![image](https://user-images.githubusercontent.com/5270359/51257934-14c2f800-19a9-11e9-96c7-687c89a7ffa9.png) 
brings you to the repository overview where you can filter / search and remove favorites.
I think for online projects the name is just the repository name on the remote.

Does that help?

**Comment by tricktresor** [comment]
Thanks! I know that, but it does not really solves the problem.
If I create a project on github with a common or meaningless name (demo, testAB, CheckOk), it might be helpful to have a better description.

In my special case I have several projects which are identified by a 4-character id (abcd, A123, chk4, ...) which is confusing when displayed in the overview.

Cheers
Enno

**Comment by sbcgua** [comment]
+1 to separate display name from url. url does not allow spaces for example. Analogy: in normal git i can choose dir name as I like, it is not connected to url anyhow

**Comment by christianguenter2** [comment]
@larshp do you think that's something we should implement?

**Comment by larshp** [comment]
yea probably, just dont make it too complicated

**Comment by tricktresor** [comment]
maybe a simple additional file for additional information
<project id= "github-project-name">
<name>project name displayed in abapGit</name>
<abstract>here might be some more information about what the project does and what it is for.</abstract>
</project>
?

I haven't seen any "github standards" for this.

**Comment by larshp** [comment]
I would imagine this being a local setting

**Comment by sbcgua** [comment]
imho, just add `ty_repo_xml-local_name` or `display_name` and split the logic a bit. From the top of my head: add field to online repo dialog, maybe add rename command (or maybe leave for DB util)

**Comment by christianguenter2** [comment]
@tricktresor can you try the latest build?

**Comment by tricktresor** [comment]
Works great! Thanks a lot!
