### ISSUE TITLE
objects are missing in repository

### ISSUE THREAD

**Issue by tricktresor** [larshp/abapGit#2297]
I have an issue with my repository https://github.com/tricktresor/guidrasil

The two objects mentioned here were missing in the repository:
https://github.com/tricktresor/guidrasil/issues/12

They are not displayed in the abapGit repo in my SAP system.
After "force stage" they have been found and I could stage them to github.

But still they do not appear in my local repository.
I tried "reset local" and "refresh". No effect. the objects are still missing.

How can I match the repositories again??

Thanks
Enno

**Comment by larshp** [comment]
Try Advanced -> Remove, and then create the online repo again

**Comment by tricktresor** [comment]
If there are more objects missing then they're gone afterwards... 😭

**Comment by larshp** [comment]
Remove does not delete any objects, as it explains in the popup

**Comment by larshp** [comment]
Are you running the latest abapGit version?

**Comment by tricktresor** [comment]
good point! 

still updating... ☕️ 😄

**Comment by tricktresor** [comment]
> Remove does not delete any objects, as it explains in the popup

Sorry. mixed up with "uninstall"... 😕

**Comment by tricktresor** [comment]
still missing the two objects...

They somehow were added to ignore list.
manually corrected .abapgit.xml.
Now it works.
