### ISSUE TITLE
Dynpro Generation - Flag SET-/GET_PARAM

### ISSUE THREAD

**Issue by GoWale** [larshp/abapGit#2300]
When generating a Dynpro in some cases the Flags SET_PARAM and GET_PAAM are active by default.
The soulution is to set the parameters to "/". I think this must happen when seralizing the object.

![grafik](https://user-images.githubusercontent.com/9630039/51292002-803cb200-1a09-11e9-8f03-723f8564b2ad.png)

I thinkt this cahnge is also only requered ift the DDIC Element on the Dynpro has a default PARAMETER_ID.
See als the SAP solution in the table maintain generator.
![grafik](https://user-images.githubusercontent.com/9630039/51293269-6ea9d900-1a0e-11e9-88da-a09ea02321d2.png)

**Comment by larshp** [comment]
okay, can you explain a bit more about the error, how can it be reproduced?

**Comment by GoWale** [comment]
Create a dynpro using a data element that:
1.)	Have a predefined parameter id (DD04L-MEMORYID => example FIELDNAME or INDEXID).
2.)	create with DDIC reference

**Before**
Fields (without DDIC reference):
![grafik](https://user-images.githubusercontent.com/9630039/51304284-040d9300-1a38-11e9-9004-00d327a42fe1.png)
![grafik](https://user-images.githubusercontent.com/9630039/51304288-05d75680-1a38-11e9-9c64-73293db71701.png)

Fields (with DDIC reference):
![grafik](https://user-images.githubusercontent.com/9630039/51303940-2357f080-1a37-11e9-81a4-f9553b4a38fd.png)
![grafik](https://user-images.githubusercontent.com/9630039/51303946-27840e00-1a37-11e9-8ec7-48fee4bee825.png)

•	Export to ZIP
•	Delete Report in System
•	Rebuild local checksums (forget about existing report)
•	Import from ZIP

**After**
Fields (without DDIC reference):
![grafik](https://user-images.githubusercontent.com/9630039/51304263-f2c48680-1a37-11e9-853c-ed2a7f5cb70e.png)
![grafik](https://user-images.githubusercontent.com/9630039/51304268-f5bf7700-1a37-11e9-8b30-a0736367a9c6.png)

Fields (with DDIC reference):
![grafik](https://user-images.githubusercontent.com/9630039/51304059-703bc700-1a37-11e9-9f10-078cb08afb41.png)
![grafik](https://user-images.githubusercontent.com/9630039/51304073-75007b00-1a37-11e9-9eeb-494766f78865.png)
As you can see the checkboxes for set/get parameters are now active.

Example ZIP file:
[$ISSUE_20190117_083629.zip](https://github.com/larshp/abapGit/files/2767615/ISSUE_20190117_083629.zip)

**Comment by christianguenter2** [comment]
Confirmed. 

Public repo: https://github.com/christianguenter2/test_2300.git

![image](https://user-images.githubusercontent.com/17437789/51316468-10541900-1a55-11e9-90db-7caf03f8bc92.png)

**Comment by larshp** [comment]
related: https://github.com/GoWale/abapGit/commit/b96f2d554a20d929329244d2da1d34a5ca20028c

**Comment by larshp** [comment]
I think we need to reopen this, I did not notice it changed the file format, just assumed the changes were for deserialization, not serialization.

I will roll back the change.

**Comment by larshp** [comment]
Sorry about the delay, been busy

Fields SET_PARAM and GET_PARAM are flag fields, ie. values '' and 'X' are permitted, the serialized XML should contain the permitted values if possible.
Suggest trying to move the code into method ZCL_ABAPGIT_OBJECTS_PROGRAM->DESERIALIZE_DYNPROS, so that blanks from the XML will be saved properly.

https://github.com/larshp/abapGit/commit/4b3d2334ccf5b57b96fd1e595667f8ff95530f68

**Comment by larshp** [comment]
@GoWale does it work now? can we close the issue?

**Comment by GoWale** [comment]
Yes the current version fixes the issues I had.
