### ISSUE TITLE
Object type SUCU not supported using latest build

### ISSUE THREAD

**Issue by matt1as** [larshp/abapGit#2333]
I'm trying to pull @gregorwolf s fork of ABAP-SDK-for-Azure (https://github.com/gregorwolf/ABAP-SDK-for-Azure) using the latest abapgit (did a pull just nu with updates from 2019-01-24) and get this. 

    Object type SUCU not supported, serialize

According to #2141 this should be merged into master, but for me it still seems to be an issue

**Comment by larshp** [comment]
They have not adopted the core abapGit format, see https://github.com/Microsoft/ABAP-SDK-for-Azure/issues/30

so you have to install https://github.com/larshp/abapGit-Plugins

**Comment by matt1as** [comment]
It's working, thank you. I had seen that comment but not understood it
