### ISSUE TITLE
Error creating offline repository

### ISSUE THREAD

**Issue by treisinger** [larshp/abapGit#2334]
When trying to create a new offline repository, I get the error below

![image](https://user-images.githubusercontent.com/9279781/51730547-24f96800-2078-11e9-9e97-0d44644e998d.png)

As the repository is not created, I cannot change anything.

When trying to create same repository again, I get the following error message.

![image](https://user-images.githubusercontent.com/9279781/51730605-6f7ae480-2078-11e9-9f66-87098d2ca574.png)

This will go away, when I leave abapGit transaction, but than again first error message.

I already created an offline repo (same namespace) in the system few weeks ago and it worked without any problem?

**Comment by larshp** [comment]
Is the project present under the burger icon?

**Comment by treisinger** [comment]
What is the burger icon? If you mean the COGS-Split project. Yes it is present.

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/51731116-3c395500-207a-11e9-8425-9ffc3fb46f67.png)

is "COGS-Split" the project you are creating? What happens if you select it?

**Comment by christianguenter2** [comment]
A last resort would be to change it via 'Database util'
![image](https://user-images.githubusercontent.com/17437789/51731896-a81cbd00-207c-11e9-86bc-d2bbf4cc19f0.png)
![image](https://user-images.githubusercontent.com/17437789/51731912-ba96f680-207c-11e9-9610-9962a83dc267.png)

**Comment by treisinger** [comment]
No, it is not present there. I guess the error message will be issued before it will create it in the database.

**Comment by christianguenter2** [comment]
I can reproduce it too.

**Comment by christianguenter2** [comment]
Offline repo with default dot_abapgit is created here.

https://github.com/larshp/abapGit/blob/d63686c4424bc740ad8d8271a80341f03ab92748/src/zcl_abapgit_repo_srv.clas.abap#L302-L307

https://github.com/larshp/abapGit/blob/d63686c4424bc740ad8d8271a80341f03ab92748/src/zcl_abapgit_dot_abapgit.clas.abap#L113-L132

**Comment by christianguenter2** [comment]
@treisinger you can set a breakpoint here
https://github.com/larshp/abapGit/blob/d63686c4424bc740ad8d8271a80341f03ab92748/src/zcl_abapgit_dot_abapgit.clas.abap#L120
and switch manually to 'FULL'.

**Comment by treisinger** [comment]
@christianguenter2 Ok, this worked. I could create the repo.

**Comment by christianguenter2** [comment]
As a fix I'd suggest that we ask the user for folder logic, mayb we can add it here:
![image](https://user-images.githubusercontent.com/17437789/51733274-1cf1f600-2081-11e9-8bda-bb00680e7921.png)

**Comment by christianguenter2** [comment]
@treisinger can you try again with the latest build?
![image](https://user-images.githubusercontent.com/17437789/51838914-f5f92580-2307-11e9-8690-cf945967c8af.png)

**Comment by treisinger** [comment]
@christianguenter2 yes, it works now.

**Comment by larshp** [comment]
closing
