### ISSUE TITLE
Local files marked as modified after local reset

### ISSUE THREAD

**Issue by matt1as** [larshp/abapGit#2336]
I'm trying to install ABAP SDK for Azure from Gregor Wolf's fork, but even after a local reset it marks some of my files as locally modified. From the diff it does look like it's something with the new AbapGit format?

I tried installing first from Microsofts official repo, and then updated the remote to point to Gregor's fork, not sure if that messed something up. Also I cannot uninstall it due to authorization objects that are already tracked in a transport and cannot be installed.

At the moment I'm having problems with the SDK, but am not sure if it's my local repo thas is out of sync or not.

````

<abapGit version="v1.0.0" serializer="LCL_OBJECT_CLAS" serializer_version="v1.0.0">
--
  |   | <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  |   | <asx:values>
  |   | <VSEOCLASS>
  |   | <CLSNAME>ZCL_ADF_SERVICE</CLSNAME>
  |   | <VERSION>1</VERSION>
  |   | <LANGU>E</LANGU>
  |   | <DESCRIPT>SAP-Azure Data Framework Service</DESCRIPT>
  |   | -    <EXPOSURE>2</EXPOSURE>
  |   | <STATE>1</STATE>
  |   | -    <CLSABSTRCT>X</CLSABSTRCT>
  |   | <CLSCCINCL>X</CLSCCINCL>
  |   | <FIXPT>X</FIXPT>
  |   | <UNICODE>X</UNICODE>
  |   | </VSEOCLASS>
  |   | <DESCRIPTIONS>


````

![image](https://user-images.githubusercontent.com/2552736/51786073-96601600-215f-11e9-9a76-cec88b6ecb8b.png)

**Comment by matt1as** [comment]
Just realised this is because I use the abapgit plugin

**Comment by larshp** [comment]
fiels EXPOSURE and CLSABSTRCT were cleared in https://github.com/larshp/abapGit/blob/master/changelog.txt#L34, the above code is not update to the latest format yet, hence the diffs

suggest opening a PR to the Azure SDK if you have the time
