### ISSUE TITLE
dependency ddic and abap objects

### ISSUE THREAD

**Issue by GoWale** [larshp/abapGit#2338]
If you import a DDIC Object that needs an abap object:
•	search help with an exit function module
•	table type the has reference to a class
The activation of the DDIC will fail.
Examples: https://github.com/GoWale/abapGit-issue_2338

But without the DDIC the abap objects cannot be activate or
the import will fail at all if the DDIC is used in a dynpro.

Also I think these issues going in a simular direction
#379
#2169
The problem is how to solve the issue?
The ways I think are:
1.	Replace all possible dependent places at the DDIC import with an always existing one and then after the abap import switch it back
2.	Import the DDIC leave it inactive Import the abap and force activation with errors then try ddic again and then the abap again
3.	(maybe) Import the dependent abap objects first or create empty dummy objects and then start the regular import

**Comment by larshp** [comment]
yeah, its an issue, I think there are other open issues for this

Anyhow, can you help submitting the exampels as PR to:
https://github.com/abapGit-tests/TTYP_with_CLAS_reference
and
https://github.com/abapGit-tests/SHLP_with_exit

then we have it somewhere central for later, plus it will hopefully show up on https://ci.abapgit.org when/if it gets working

**Comment by christianguenter2** [comment]
Another test repo with similar issues
https://github.com/christianguenter2/test_TABL_SHLP.git

#2422 

What's also confusing is that abapGit doesn't give activation errors and show the objects as non existing. But they are actually created but not activated.

**Comment by larshp** [comment]
activation error: try activating experimental features, #2169

**Comment by christianguenter2** [comment]
Yes, with experimental features on an error is shown.
![image](https://user-images.githubusercontent.com/17437789/52946065-675e4e00-3373-11e9-8264-6962ce8a4ae0.png)

**Comment by larshp** [comment]
as noted in some issue yesterday, I think we should try enabling the new ddic activation logic by default

**Comment by GoWale** [comment]
My approach to this error would need some changes to the current flow of the current deserialize process.
At the moment there are 3 fixed steps:
* ddic
* "rest"
* late

My idea was that there are more defined steps and each plugin object (PROG/CLAS/DOMA/etc.) can register to multiple steps.
So an object can import some details at the ddic step and late import some other details.

I have tested this a little bit and I think this is possible.

The main concern I have is that I have to change quite a bit on this central places.
And to be clean also interface and registration of the object plugins for the activation have to get a little more detailed.
(For example the flag DDIC from get_meta( ) is needed to now witch function is needed for activation but we need additional the information on witch steps the plugin should be executed).

**Comment by larshp** [comment]
yeah, something like above, just wonder how it will look(code and interface wise), currently there is just one `deserialize` method, either more methods or information is needed.

alternatively, look into forcing the objects active

**Comment by GoWale** [comment]
Ok I think I have a solution for this. At least for the issues I had.
My test with the abapGit-tests repo also looked ok for the first try (As far as I can read the result 2 more errors then with the public result).

I would create a PR for the issue (only active with experimental features)?
I think this changes can help for #2302

**Comment by larshp** [comment]
yes, please open PR

**Comment by mbtools** [comment]
https://github.com/larshp/abapGit/pull/3545 should fix this. Please test

**Comment by mbtools** [comment]
if there's still a problem, pls create a new issue.
