### ISSUE TITLE
ui main - cmds not aligned?

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#234]
it looks like the diff links are not in the same row as the files they correspond to. Below, the "diff" is for the clas.xml file, there should also be a diff linke for the clas.abap file. (diffs are done per file)

![image](https://cloud.githubusercontent.com/assets/5888506/15644559/11e5ae66-2654-11e6-8190-8005c69f4a15.png)

**Comment by sbcgua** [comment]
I'll have a look

**Comment by sbcgua** [comment]
Seems to work now. Have a look at commits (the first one). 
However: I've adjusted en/decode_file method - the link actually uses just path and filename - no need to create so huge link (from my perspective :). The old code is commented for the moment. If the change is OK, I'll remove the comments and create pull request. 

![image](https://cloud.githubusercontent.com/assets/15635498/15657486/f3243d10-26b9-11e6-98a9-e78c85248655.png)

**Comment by larshp** [comment]
looks good, let's ship it :ship:

**Comment by larshp** [comment]
solved with https://github.com/larshp/abapGit/issues/235
