### ISSUE TITLE
Skipped: generated by SADL  but still ni the staging when doing Transport-to-Branch

### ISSUE THREAD

**Issue by matt1as** [larshp/abapGit#2343]
Hi,

We're trying to use Transport-to-Branch, but are having problems with some generated objects. There's a warning saying they are ignored, but when we try to create our transport-to-branch it still tries to stage the files, which is not working. I assume it tries to stage all objects that are in the transport, and ignores that it's been ignored earlier. 

I'd love to help but don't feel comfortable enough in the abapgit code to add a check for this

![image](https://user-images.githubusercontent.com/2552736/52040183-edd2fd00-2536-11e9-81e4-5c1916e9546b.png)

**Comment by matt1as** [comment]
Too bad. We're (trying to) keep each user story we work on in a separate transport, and transport-to-branch is a great way to do code reviews and syntax checking. 

I will look and see if I can fix it somehow, would it be a plausible solution to add the sadl files to .gitignore?

**Comment by matt1as** [comment]
Or maybe basically compare all objects in the transport with those in the local repo and skip the ones not in the repo?

**Comment by larshp** [comment]
I basically want to do the same thing with code reviews, just not use the transport-to-branch feature, instead use a new background mode, https://github.com/abapGit/background_modes (work in progress) which (sometime) will do it all automatically

**Comment by matt1as** [comment]
Our flow right now is

1. Put all objects from user story in one transport ( here we of course have challenges with people locking each other, but we're fighting that with slicing our stories smaller and smaller, and people chipping in to help each other finish / release)
2. Before releasing transport request we commit the transport into a new branch in Azure Devops (Git repo)
3. Create a pull request in Azure Devops
4. Another dev approves the pull req and also checks for lint errors in Sonarcloud & ATC
5. Branch is merged in Azure Devops, but we never pull anything back into CRM

But if there's a new feature helping us with this it would be awsome, the current setup is not optimal.  

Also somewhere in there Devops runs Abap Unit tests nightly and publishes the results together with our .Net test-results

**Comment by larshp** [comment]
I'd like step 2 and 3 in above to be automated.
The background mode can run every hour and push changes automatically to a branch with name = transport, this will make it transparent what is in the transport, changes over time, backup, and status.
Plus when the branch is created, do an API call to Azure Devops/or similar, to create the PR.

Then it would also be possible to implement a check on transport release, to check if the PR is approved in Azure Devops. Errors from ATC can be automatically posted/updated in the PR, or use abaplint 😄

**Comment by matt1as** [comment]
Seems like wer're trying to accomplish mostly the same thing, please see PR #2344 . Will try to create a fix for my current issue and then play with the background branch in our sandbox

**Comment by larshp** [comment]
there is a lot of work left in the background-modes project, but I think its worth it, as there will be less actions required by the developers 😄

**Comment by matt1as** [comment]
I've created a fork that basically ignores files not in the local repo, I'll test it some more and create a PR

**Comment by matt1as** [comment]
created PR #2404

**Comment by larshp** [comment]
guess this issue can be closed?
