### ISSUE TITLE
no use access to package interface _ABA_Default

### ISSUE THREAD

**Issue by DennstedtB** [larshp/abapGit#2346]
Hi, 

I just wanted to import ABAP2XLSX via ABAPGIT. I've created a package where every repository should be stored in. This is ZGIT_REPOSITORIES. Then I wanted to import ABAP2XLSX, created via ABAPGIT a package which is called ZGIT_ABAP2XLSX. After this I pressed "Pull". 

After a few seconds, and after a few classes which got imported, ABAPGIT raises the error "ZGIT_REPOSITORIES has no use access to package interface _ABA_DEFAULT". What is exactly the reason for this and how can I solve this? 

Thank ya.

**Comment by flaiker** [comment]
ABAP2XLSX seems to have package interface usages defined in their top level package. For these to be correct the whole package hierarchy (directed upwards) needs to also have these usages defined.
You could try adding these in ZGIT_REPOSITORIES or clone into a package that is top level.

https://raw.githubusercontent.com/ivanfemia/abap2xlsx/master/src/package.devc.xml
_ABA_DEFAULT
_ABA_VIRTUAL_DEFAULT
_BASIS_DEFAULT
_BASIS_VIRTUAL_DEFAULT

Either way seems like the handling in abapGit is not optimal.

**Comment by DennstedtB** [comment]
Thank you very very much!!! Now it works and the issue can be closed. 

And yes, it is not optimal, maybe it would be good if it collects every message and then shows a popup .. with a possible solution. But okay, as long as we have this amazing community, we can ask here and we get help. 

Thank ya again!

**Comment by larshp** [comment]
perhaps we should submit a pull request to abap2xlsx to remove the interface usages?

**Comment by flaiker** [comment]
> perhaps we should submit a pull request to abap2xlsx to remove the interface usages?

Maybe, do these even do anything? Aren't these interfaces only for structure package checks (PAKPARAM-GLOBAL_SWITCH=R3ENTERPRISE)?

Having a superpackage for all open source projects managed by abapGit isn't that uncommon though.
