### ISSUE TITLE
SFPF: Error by pulling of an existing object (SIFbA print form)

### ISSUE THREAD

**Issue by p-dmitrij** [larshp/abapGit#2352]
By pulling of an updated version of a SIFbA print form which already exists in the system, the program throws the error "SFPF error, deserialize". I've noticed that the method ZCL_ABAPGIT_OBJECT_SFPF->ZIF_ABAPGIT_OBJECT~DESERIALIZE() always tries to create a new print form without to check if it already exists, which leads to raising of the exception cx_fp_api. I'm not sure how it should work properly according to the abapGit architecture, but this small adjustment allows to solve the issue:

`  METHOD zif_abapgit_object~deserialize.

    DATA: lv_xstr      TYPE xstring,
          lv_name      TYPE fpname,
          li_wb_object TYPE REF TO if_fp_wb_form,
          li_form      TYPE REF TO if_fp_form.

    lv_name = ms_item-obj_name.
    lv_xstr = cl_ixml_80_20=>render_to_xstring( io_xml->get_raw( ) ).

    TRY.
        li_form = cl_fp_helper=>convert_xstring_to_form( lv_xstr ).

"       >>> DP 03.02.2019 Update existing SFPF object
        IF zif_abapgit_object~exists( ) = abap_true.
           cl_fp_wb_form=>delete( lv_name ).
        ENDIF.
"       <<< DP 03.02.2019 

        tadir_insert( iv_package ).
        li_wb_object = cl_fp_wb_form=>create( i_name = lv_name
                                              i_form = li_form ).
        li_wb_object->save( ).
        li_wb_object->free( ).
      CATCH cx_fp_api zcx_abapgit_exception.
        zcx_abapgit_exception=>raise( 'SFPF error, deserialize' ).
    ENDTRY.

    zcl_abapgit_objects_activation=>add_item( ms_item ).

  ENDMETHOD.`

**Comment by christianguenter2** [comment]
Fix seems about right, as there isn't an API for setting the form at first sight. Feel free to create a pull request.

**Comment by larshp** [comment]
pull request opened containing above fix

**Comment by p-dmitrij** [comment]
Ok, I'll try to do it. It will be my 1st experience with a git-based open source project :)

**Comment by larshp** [comment]
I have opened https://github.com/larshp/abapGit/pull/2362 for this issue

**Comment by larshp** [comment]
merged, try latest version

**Comment by p-dmitrij** [comment]
Thanks, now it works
