### ISSUE TITLE
SFPF, SFPI: Error by import of big SIFbA forms

### ISSUE THREAD

**Issue by p-dmitrij** [larshp/abapGit#2353]
By serialisation of a SFPF/SFPI object the attributes like "id=o*" and reference attributes like "href=#o*" are renumbered. This logic is implemented in the method `ZCL_ABAPGIT_OBJECT_SFPF=>FIX_OREF()`. The problem is, that the renumbering has the upper limit of 100 for the total number of nodes:
![image](https://user-images.githubusercontent.com/37515520/52170970-5e5f6100-2765-11e9-9721-512fc2380c05.png)
But big forms can have much more nodes. This is a screenshot from the serialised xml of a productive SIFbA form with search results of the substring "o11045":
![image](https://user-images.githubusercontent.com/37515520/52171040-ab900280-2766-11e9-86d7-52897a9d66b2.png)
As you can see here there is only one node with id="o11045" in the xml document.
After executing of the method `FIX_OREF()` there are a lot of nodes with the same id="o104":
![image](https://user-images.githubusercontent.com/37515520/52171028-49cf9880-2766-11e9-8896-b8fdeeecead2.png)
What is the reason for such a renumbering? I've just deleted the calls of the method and now big forms work just fine.

**Comment by christianguenter2** [comment]
fd468a2

**Comment by larshp** [comment]
reason: when the standard code exports the form, it gives numbers, however these are not deterministic, so each time a form is serialized it gives new numbers => in abapGit the form will always show up as changed

suggest changing the code so it uses "1000000" instead of "100", this should fix the issue? While still being backwards compatible

**Comment by p-dmitrij** [comment]
Ok, I've got your point.  I'll try to implement the renumbering in a slight a different way in a separate branch.

**Comment by p-dmitrij** [comment]
I've tested the correction with couple of really big print forms:
1) backward compatibility -> ok
2) performance -> ok
3) pull, stage -> ok
4) stage, pull -> ok
So from my point of view, the issue can be closed.

Btw, the method IF_IXML_NODE_ITERATOR->GET_NEXT() works *really* slowly! It is much better firstly to store all relevant nodes in an internal table and then work with the table instead of the iterator.

**Comment by larshp** [comment]
closing issue

GET_NEXT: feel free to submit a PR with a fix

**Comment by p-dmitrij** [comment]
I've found this problem during development, so the correction is already implemented using internal tables. No additional changes are needed.
