### ISSUE TITLE
Files are not placed in same Folder

### ISSUE THREAD

**Issue by schallera** [larshp/abapGit#2354]
Hi,

I got those errors :

Files for object CLAS ZCL_ABAPGIT_HTTP_CLIENT are not placed in the same folder
Files for object CLAS ZCL_ABAPGIT_HTTP_CLIENT are not placed in the same folder
Files for object CLAS ZCL_ABAPGIT_LONGTEXTS are not placed in the same folder
Files for object CLAS ZCL_ABAPGIT_LONGTEXTS are not placed in the same folder
Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHC are not placed in the same folder 
Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHC are not placed in the same folder
Package and path does not match for object, CLAS ZCL_ABAPGIT_HTTP_CLIENT
Package and path does not match for object, CLAS ZCL_ABAPGIT_HTTP_CLIENT
Package and path does not match for object, CLAS ZCL_ABAPGIT_LONGTEXTS
Package and path does not match for object, CLAS ZCL_ABAPGIT_LONGTEXTS 
Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHC
Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHC
Multiple files with same filename, zcl_abapgit_http_client.clas.abap 
Multiple files with same filename, zcl_abapgit_http_client.clas.xml 
Multiple files with same filename, zcl_abapgit_longtexts.clas.abap 
Multiple files with same filename, zcl_abapgit_longtexts.clas.xml
Multiple files with same filename, zcl_abapgit_object_enhc.clas.abap
Multiple files with same filename, zcl_abapgit_object_enhc.clas.xml

Any idea how to solve it?

Greetings
Andreas

**Comment by larshp** [comment]
click Advanced -> Reset Local

**Comment by schallera** [comment]
Hi Lars,

thanks for the quick response.  At first I had some errors while reseting to local (I avoided deleting table ZABAPGIT) but after reload the initial ZABAPGIT Report it's fixed.

Greetings
Andreas
