### ISSUE TITLE
Method "LOAD_BY_ABAP_NAME_INT" is unknown or PROTECTED or PRIVATE

### ISSUE THREAD

**Issue by bmaciag** [larshp/abapGit#2365]
Error while activating the latest version:

Method "LOAD_BY_ABAP_NAME_INT" is unknown or PROTECTED or PRIVATE.	
ZABAPGIT line 48514

**Comment by larshp** [comment]
What SAP version are you running?

LOAD_BY_ABAP_NAME_INT is called by new SPRX code

workaround is deleting local class ZCL_ABAPGIT_OBJECT_SPRX in the copied code

**Comment by bmaciag** [comment]
SAP_BASIS	731

**Comment by larshp** [comment]
So method LOAD_BY_ABAP_NAME_INT does not exist in CL_PXN_FACTORY on 731, can you help checking if method LOAD exists in CL_PXN_FACTORY, and paste the input parameters here?

**Comment by bmaciag** [comment]
There is a method LOAD_BY_ABAP_NAME
    importing
      !OBJECT type PRX_R3OBJ optional
      !OBJ_NAME type PRX_R3NAME
    returning
      value(MAIN) type ref to IF_PX_MAIN
    raising
      CX_PXN_UNQUALIFIED
      CX_PXN_LOCK_FAILED
      CX_PXN_FAULT .

**Comment by bmaciag** [comment]
methods LOAD
    importing
      !NAME type QNAME
      !TYPE type PRX_TYPE
      !IS_TABLE type PRX_BOOLEAN optional
      !GEN_NSPACE type CSEQUENCE optional
      !MAIN_LOAD type PRX_BOOLEAN default SPRX_TRUE
      !GEN_APPL type PRXGENAPPL default 'BACKENDMDR'
      !PACKAGE type DEVCLASS optional
    returning
      value(MAIN) type ref to CL_PXN_MAIN
    raising
      CX_PXN_FAULT .

**Comment by larshp** [comment]
The LOAD_BY_ABAP_NAME is part of interface IF_PXN_FACTORY ?

**Comment by bmaciag** [comment]
Yes, its part of.
methods LOAD_BY_ABAP_NAME
    importing
      !OBJECT type PRX_R3OBJ optional
      !OBJ_NAME type PRX_R3NAME
    returning
      value(MAIN) type ref to IF_PX_MAIN
    raising
      CX_PXN_UNQUALIFIED
      CX_PXN_LOCK_FAILED
      CX_PXN_FAULT .

**Comment by larshp** [comment]
can you help trying the code in https://github.com/larshp/abapGit/pull/2366 to see if it syntax checks

**Comment by bmaciag** [comment]
Done, but there is a error in the class definition:
You can only define a PUBLIC class within a global CLASSPOOL. 
ZABAPGIT	line 5936	

CLASS zcl_abapgit_object_sprx DEFINITION PUBLIC INHERITING FROM zcl_abapgit_objects_super FINAL.

After removing the PUBLIC I got one step further:
Exception "LOGICAL_PACKAGE_TYPES_DIFFER" does not exist	
ZABAPGIT	line 52750	

mi_interface->set_all_attributes(
      EXPORTING
        i_package_interface_data     = is_package_interface_data
        i_data_sign                  = is_data_sign
      EXCEPTIONS
        object_deleted               = 1
        object_not_changeable        = 2
        interface_not_empty          = 3
        acl_not_empty                = 4
        author_not_existing          = 5
        object_type_mismatch         = 6
        logical_package_types_differ = 7
        object_invalid               = 8
        OTHERS                       = 9 ).

**Comment by larshp** [comment]
are you using the latest version, https://github.com/larshp/abapGit/commit/2c8a3f3b171c72675fab657d7947fede4d183c53 should have fixed the PUBLIC definition 3 days ago, plus I just copied the full source without the PUBLIC error

**Comment by larshp** [comment]
I assume also OBJECT_INVALID does not exist?

**Comment by larshp** [comment]
https://github.com/larshp/abapGit/pull/2367 opened for the PINF downport

**Comment by bmaciag** [comment]
Got it from https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap
And then Copy/Past the abapGit/src/objects/zcl_abapgit_object_sprx.clas.abap from #2366
the zcl_abapgit_object_sprx DEFINITION and IMPLEMENTATION

**Comment by bmaciag** [comment]
> I assume also OBJECT_INVALID does not exist?

This exists
  methods SET_ALL_ATTRIBUTES
    importing
      !I_PACKAGE_INTERFACE_DATA type SCOMPIDTLN
      !I_DATA_SIGN type SCOMPISIGN
    exceptions
      OBJECT_DELETED
      OBJECT_NOT_CHANGEABLE
      INTERFACE_NOT_EMPTY
      ACL_NOT_EMPTY
      AUTHOR_NOT_EXISTING
      OBJECT_TYPE_MISMATCH
      OBJECT_INVALID .

**Comment by larshp** [comment]
updated, https://github.com/larshp/abapGit/pull/2367

**Comment by bmaciag** [comment]
Perfect, working now. Thank you
