### ISSUE TITLE
Replace report name ZABAPGIT with ZABAPGIT_FULL 

### ISSUE THREAD

**Issue by gregorwolf** [larshp/abapGit#2370]
I would like to suggest to replace:

```REPORT zabapgit LINE-SIZE 100.```

with

```REPORT zabapgit_full LINE-SIZE 100.```

in the abapGit build that is used for copy&paste.

**Comment by larshp** [comment]
agree, good idea

**Comment by flaiker** [comment]
Does the identifier after the report statement have any effect at all? Syntax check does not complain if it's different than the program name  and according to the documentation it is even optional.
`REPORT LINE-SIZE 100.`

**Comment by larshp** [comment]
it works without and with other names, but above suggestion will help showing the intent as described in https://docs.abapgit.org/guide-install.html

**Comment by larshp** [comment]
done in https://github.com/larshp/abapGit/pull/3154, closing
