### ISSUE TITLE
Method doesn't exist in class

### ISSUE THREAD

**Issue by rjmonteiro** [larshp/abapGit#2374]
I was trying to install abapGit yesterday following the install guide.
Created the program saved, but when trying to activate, I got the error in the image.
As it seems, the Method LOAD_BY_ABAP_NAME_INT doesn't exist in the class.

My system has SAP_BASIS 731 with sp-level 0022.

![abapgit error](https://user-images.githubusercontent.com/5887399/52410165-7883a100-2acf-11e9-9ad6-f646cbf739a5.jpg)

Thank you,
Ricardo Monteiro

**Comment by christianguenter2** [comment]
fixed with #2366 can you try the latest build?

**Comment by rjmonteiro** [comment]
Works like a charm ;)
