### ISSUE TITLE
Transport Object for MSAG

### ISSUE THREAD

**Issue by mfsap** [larshp/abapGit#2378]
Hi,

when messages classes are de-serialized, object type "LIMU MSAD <msgclass>" is added to the transport request (object_class = 'T100' in combination with global_lock='X' -> LIMU MSAD):
   CALL FUNCTION 'RS_CORR_INSERT'
      EXPORTING
        global_lock         = abap_true
        devclass            = iv_package
        object              = ls_t100a-arbgb
        object_class        = 'T100'
        mode                = 'INSERT'
When the message class is deleted, "R3TR MSAG <msgclass>" is used.

Why is "LIMU MSAD <msgclass>" used for de-seriialization instead of "R3TR MSAG <msgclass>"?

Regards,
Martin

**Comment by larshp** [comment]
yeah, this seems strange, how can the issue be reproduced? Pull https://github.com/abapGit-tests/MSAG_simple to a transported package?

**Comment by mfsap** [comment]
Hi Lars,

I used https://github.com/abapGit-tests/MSAG.git with a transportable package for testing...

Best Regards,
Martin

Am 11.02.2019 um 18:02 schrieb Lars Hvam <notifications@github.com<mailto:notifications@github.com>>:


yeah, this seems strange, how can the issue be reproduced? Pull https://github.com/abapGit-tests/MSAG_simple to a transported package?

**Comment by larshp** [comment]
Reproduced, yeah, seems like a bug,
![image](https://user-images.githubusercontent.com/5888506/52582266-1b6c5000-2e2d-11e9-957f-edb1800c59e2.png)

**Comment by larshp** [comment]
@mfsap will you be working on a fix for this? Note that the superclass have methods CORR_INSERT AND TADIR_INSERT which might be helpful

**Comment by mfsap** [comment]
Hi Lars, I fixed it using method corr_insert() method. But the current version of corr_insert() could only handle objects with object class 'DICT'. Object type MSAG does not belong to 'DICT'. In my version I moved the object_class to the signature (import parameter) to handle other object types as well. I'll prepare pull request soon...
