### ISSUE TITLE
UI, refactoring: split page logic to view and controller

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#238]
Idea is reducing page class size, more flexible command routing (in particular a command may be called from more than 1 place) and concentrate processing logic in one place separating it from visualization.

Current action study:

![page actions](https://cloud.githubusercontent.com/assets/15635498/15718024/27a18aec-2832-11e6-8ff4-30f359f81142.png)

P.S. Follows from #202, mentioned before as event handling refactoring

**Comment by larshp** [comment]
I like the idea with separating logic from visualization, but again the visualization must correspond to the logic/actions.

How will the page actions look in this case? One class for each action or one page actions class for all pages, in case it is for all pages I guess it will be a quite big class?

**Comment by sbcgua** [comment]
My initial idea was to call page event handler which should then return if it "managed" the event. and if not then the controller proceed with "global" actions. However from what I see above **all** existing commands look "global" to me - they are all related to models: repo, db, commit (well here I'm not sure didn't study that piece of code yet :), navigation to pages (which is external to page by definition).

 > one page actions class for all pages, in case it is for all pages I guess it will be a quite big class?

Yes that's what I was planning for the moment. I see the issue but don't see how to resolve for the moment. I hope it will be more visible when done :) Maybe the controller will stay with navigation (diff, jump, explore, nav to beta features, aghome, stage, db_display/edit, ???) and the rest (e.g. repo actions and commit actions) will stay in pages. But actually that's what I'd like to change :)

**Comment by larshp** [comment]
hmm, yea, its difficult to see if it makes things easier, again perhaps make small example outside of the abapgit code

**Comment by sbcgua** [comment]
See below some plans.

Comments:
1) Gui knows about if_page and router, router knows about if_page but does not know about gui, page does not know about gui and router. 
2) Currently router is doing all controller staff but maybe it will also split - currently not visible. 
3) page on_event() in fact not reallly needed. Maybe will stay for some on page events like refresh + re-render (also not 100% visible for the moment)
4) globally: why gui is the main class ? why not to introduce some lcl_app which will handle gui and also create single instances of persistence, gui and other context stuff ? (just a question, if yes, should go to another task)
5) globally 2: explore: For me this page does not fit the concept like it is now. External page with unpredictable behavior (like tracker link at the bottom). As I understand this is kind of placeholder for future package marketplace ? :) Good idea, no problem, but I guess it should receive content and render it in abap as lcl_gui_page_xxx. Consequently able to handle installation links in-code, check what is already installed and etc.
6) question: What is the logic behind lcl_gui=>set_page (not call_page) in page_stage->call_commit() ? Avoiding history ? Why ?
7) above commit: Redirect pages: added redirect method to page_super. Now external pages follow same logic as internal, no need handling URLs (unification needed for routting).

If OK, I'll be implementing it these days :) then please don't adjust pages and gui for a while :)

![abapgit-gui](https://cloud.githubusercontent.com/assets/15635498/15799049/6e1a81ea-2a58-11e6-8a32-7afaa7e0b842.png)
![abapgit-guiflow](https://cloud.githubusercontent.com/assets/15635498/15799050/6e1c0178-2a58-11e6-9f14-23a44a2fe180.png)

**Comment by sbcgua** [comment]
Some half-way code in commits above ([branch](https://github.com/sbcgua/abapGit/tree/t238))

**Comment by sbcgua** [comment]
in progress. Can be checked in commits above and [here](https://github.com/sbcgua/abapGit/tree/t238)

pls, don't adjust gui and pages code - merging would be a hell! :))

notes by the way: moved `is_repo_installed` to `lcl_repo_srv`. Looks like a model call. However there is  exception checking target package mentioning "installation". I wonder what to do with it. Either changing text (and potentially method name) or moving package check to another method.

**Comment by sbcgua** [comment]
That's all for now. Still actions from other pages to be integrated (db, stage). But I'll do it later.
Question about `lcl_gui=>set_page` from above is still actual - I'd like to reorder lcl_gui a bit hiding/merging unnecesary methods.

Current user instance migrated to `lcl_gui`. But in fact that should be a part of some kind of `lcl_app` mentioned above (Q4).

If all OK, I'll do PR.

**Comment by larshp** [comment]
Overall I think it looks good, feel free to create the PR, then we can discuss details.

Replies to questions above:

4: we can do it. However I would like some way to ensure that the app class is used. Typically if I need a persistence object I will go look in the persistence class and call the constructor if possible.
Perhaps the context classes can be changed to "CREATE PRIVATE", and be friends with the app class, this will force the developer to use the app class.

5: yes, a "package maketplace" thing. It makes it easy to install stuff, avoiding to find the github page and copy the .git file link

6: to avoid history. On the commit page when cancelling I guess the user would like to cancel everything, and end up back at the main page. I dont have an opinion on this, we can change it so it goes back to the staging screen.
Think of CALL SCREEN and SET_SCREEN in ABAP, I guess we will need both. This can also be compared with GET and POST methods in the web world.

Few minor issues found in the code:

a: type char40_t is unknown on 731

b: class lif_gui_page, method get_assets, RETURNING can be used instead of EXPORTING

c: in the explore page, clicking clone, then cancel, F3(back) does not work the first time pressed

**Comment by sbcgua** [comment]
OK, I'll create the PR in the evening today, including the fixed below.

4) lcl_app: I'll create a separate issue for discussion. `create private` - yeah, that's what I was also thinking about.

5) explore_page: ok. I meant that the page itself has a jquery for content. And that should be potentially done from abapgit itself. But anyway it is not critical, more about approach - I'll open a separate issue for that. 

6) set_page for commit: mmm, ok. I think I'll make it in regular way for now, and then think about some better way

minor issues:

a) type char40_t. Ha, indeed! It had so typical name that I even didn't check the package (it appeared to be some "DI: Work Packaging and Sequencing" package). I'll fix. =)

b) lif_gui_page~get_assets, RETURNING. That was a care about performance. But ... why not. A table with a couple of strings? performance?! I'll fix. :)

c) F3 from explore: yes I know, I even added a comment in the code to fix in future :) This is because I wrapped it in redirect page class so it is both in stack and has "http" in url. I think I'll just remove the workaround with http. This will mean that F3 will not work for history, generated by external page links, but I think it is OK. I'll fix.

**Comment by larshp** [comment]
5: I have a plan to change the explore page so it is static html pages(#130) automatically generated via Travis. But the page will still be different from the rest of the UI

b: I dont think there is much difference in performance for EXPORTING and RETURNING with methods. However, using returning makes the code look so pretty :wink:

**Comment by sbcgua** [comment]
4) branched to #241

**Comment by sbcgua** [comment]
finetuned db pages. Not the most brilliant design but at least in line with main and diff pages.

@larshp I'd PR but there is a bug. When I enter edit page and just press update (without any changes) it then dumps at next start claiming about incorrect XML format. That might be me who broke it but I didn't touch the logic actually so I think it was there already. Could you please have a look ?

**Comment by larshp** [comment]
yes, I'll have a look

**Comment by larshp** [comment]
try changing the textarea so that the content begins immediately after the tag, 
`ro_html->add( '<textarea rows="20" cols="100" name="xmldata">' && lv_data ).`

looks like the statement in 'db_save' action
`ls_content-data_str = <ls_field>-value+1. " hmm`
causes the problem problem, on 750 it removes a strange character created by
`cl_http_utility=>if_http_utility~string_to_fields( lv_string ).`
however the character is not present on 731, suggest changing to

```abap
IF <ls_field>-value(1) <> '<'.
  ls_content-data_str = <ls_field>-value+1. " hmm
ENDIF.
```

**Comment by sbcgua** [comment]
Seems to work now ... PRing ...

**Comment by sbcgua** [comment]
@larshp thinking about moving stage/commit pages logic to router. There is a problem - stage state- it is passed explicitly between classes. So I'm thinking how to solve it better. The best idea I see is:

1) refer repo from stage (then the commit logic can be also handled from stage)
2) make some kind of stage_srv (static or singleton) which creates/finds appropriate stage object by repo key

Another option is actually opposite - integrating stage to repo (or repo_srv) so that certain repo know about stage created for it. This looks better if stages will ever become persistent (and not in-memory like now)  but seems to be more complicated in term of state management.

**Comment by larshp** [comment]
1: have repo as input to the constructor in lcl_stage, yes it makes sense
2: ok, there will only be one active stage at a time. Problem with static or singleton objects with state is that it has to be cleared somewhere, would it be possible to have pages return a value/object to the router?

I think it will be difficult to have persistent stages, there are a lot of moving parts that can change.

**Comment by sbcgua** [comment]
@larshp have a look at the last commit. stages are created via `repo_srv`. destruction is not done explicitly but actually it is not needed. what I don't like is increased cross-referencing: repo knows about stage, stage about repo, stage friends repo_srv ... but maybe it is ok ... works at least :)

If above is OK, i'll move handling to router and then it can be closed.

**Comment by larshp** [comment]
it looks okay

**Comment by sbcgua** [comment]
@larshp have a look at the last commit. I was moving stage event handling to the router. It appeared to be tricky because page_stage held a lot of state. So:
- I moved workarea (combination of local & remote files) to stage - that's logical because stage should work with specific state of repo. Consequently `add`, `rm`, etc actually copies `mt_workarea` record to `mt_stage` internally
- consequently `lcl_stage` can also validate proper filename and not rely on external input which is more consistent then before
- `add`, `rm` ... changed interface and now accept path+filename instead of ty_file doing all checks and appends internally

However. There is a code in `repo_online->handle_stage_ignore` and `lcl_background->push` which I'm not familiar with which uses "old" interface. `lcl_background->push` seems to just list files and I can easily rewrite. But `repo_online->handle_stage_ignore` calls `add()` passing `ls_file-data  = _dot_abapgit->serialize( )`. So it has to update workarea... probably can be some method in `lcl_stage` ... also that means modifying repo files without repo knowing it ... (or maybe it is ok ?) ... and what if commit fails ? stage will contain workdata different from repos - and the user will be still on the same page with the same actions to activate ... so here I stucked a bit. What do you think ?

P.S. commit_post event currently just invokes a message instead of actual commit. (`rounter->on_event()`)

P.P.S. types are messy - many of them defined in classes and so refering to them assume also proper definition sequence which is sometime difficult. Maybe worth moving some key types to the beginning.

**Comment by sbcgua** [comment]
OK, here is an option of fix having that only `.abapgit` is updated on the fly.
Should be complete now. If OK, I'll PR.

**Comment by larshp** [comment]
looks okay

**Comment by sbcgua** [comment]
Well ... good enough to close I guess :)
