### ISSUE TITLE
INTF not refreshed at refresh

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2382]
Steps to reproduce:
1: open abapGit
2: change interface code in other session
3: click refresh in abapGit

The diff does not show the changed code. Expected to see changed code

**Comment by larshp** [comment]
method `has_changed_since` returns false

**Comment by larshp** [comment]
looks like this is a local problem on my local application server, something wrong with the time and date settings

**Comment by larshp** [comment]
closing, moving to https://github.com/larshp/abapGit/issues/1021

**Comment by sbcgua** [comment]
> looks like this is a local problem on my local application server

Had same issue recently, indeed unobvious, took an hour of debugging before insight to run `ntpdate`
