### ISSUE TITLE
DOMA not all fixed values translated -> diff

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2385]
Install https://github.com/abapGit-tests/DOMA_fixed_values_single_translated, this results in a diff

**Comment by larshp** [comment]
example restored

**Comment by larshp** [comment]
the translations are:
![image](https://user-images.githubusercontent.com/5888506/52898290-2aac1e80-31dc-11e9-8233-51bd0d90b994.png)

and this is also what is stored in the current XML, just pulling the object messes up the local object

**Comment by larshp** [comment]
okay, dont think there is an easy way to get it working with function module DDIF_DOMA_PUT

This might be a good opportunity to start looking into the LXE translation environment, related: #1886 + #2202

Function modules LXE_OBJ_TEXT_PAIR_WRITE and LXE_OBJ_TEXT_WRITE_VALU looks relevant for fixing this issue, but suggest increasing the scope a bit and prepare for generic object translation serialization and deserialization, I dont have the time for it right now

**Comment by sandraros** [comment]
Just commenting to show what it looks like after pulling:

**the DIFF:**

![image](https://user-images.githubusercontent.com/34005250/55288067-6e38a180-53b2-11e9-8bbc-017bd162bf60.png)

**the table DD07T:**

![image](https://user-images.githubusercontent.com/34005250/55288098-ee5f0700-53b2-11e9-8ce7-9c8c165535b8.png)

**Comment by larshp** [comment]
also see #2424
