### ISSUE TITLE
Installer not backwards compatible

### ISSUE THREAD

**Issue by grahamrobbo** [larshp/abapGit#2389]
Tried latest installer on a NW 7.31 system and it would not compile because data element `SEU_OBJID` is not available. 

V 1.76.0 works.

**Comment by larshp** [comment]
taking a look

**Comment by larshp** [comment]
@grahamrobbo try again, latest version

**Comment by grahamrobbo** [comment]
This syntax also doesn't work on my 7.31 system.
`READ TABLE is_diff-o_diff->get_beacons( ) INTO lv_beacon INDEX is_diff_line-beacon.`

It appears in the two `RENDER_BEACON` methods.

Had to replace with something like this.
```
      DATA: lt_beacons TYPE TABLE OF zif_abapgit_definitions=>ty_string_tt.
      lt_beacons = is_diff-o_diff->get_beacons( ).
      READ TABLE lt_beacons INTO lv_beacon INDEX is_diff_line-beacon.
```

**Comment by sbcgua** [comment]
strange ... works in my 731 ... I can PR a fix on the weekend just in case

**Comment by larshp** [comment]
try again, latest version

**Comment by larshp** [comment]
@grahamrobbo
