### ISSUE TITLE
modifiable configuration of new repositories

### ISSUE THREAD

**Issue by filak-sap** [larshp/abapGit#2395]
**Description**
- The default PREFIX folder logic sometimes prevents me from cloning a repository.
- The default version of sub-packages prevents me from adding repository of a package whose sub-package is already being versioned.

**Proposal**
I would like to extend the new repository popup with these two options and change the implementation of the method zcl_abapgit_repo_srv=>validate_sub_super_packages to not black list super packages of versioned packages when the new repository ignores sub-packages.

**Comment by larshp** [comment]
Folder logic field was recently added in the offline create project popup, so I guess its similarily needed for online.

For the versioned sub-package, we have a few issues open already, guess its okay to add an option to ignore the check, just make it visible for users that they should leave it default in most cases
