### ISSUE TITLE
Missing constants in ZIF_ABAPGIT_VERSION after upgrade abapGit (1.80.0 - 1.84.0)

### ISSUE THREAD

**Issue by MDJoerg** [larshp/abapGit#2406]
Hi Lars,

fyi. I have fixed this issue for me.

The Upgrade from 1.80.0 to current 1.84.0 failed with an "class changed during runtime" error. After that some objects are inactive. This was fixed manually. 

After activating the objects I got an syntax error for missing constants in interface  ZIF_ABAPGIT_VERSION. 
If I go to the source and use "check" than the same error occurs. But if I doubleclick the source at zif_abapgit_version=>gc_abap_version the constants are visible in the se24 view and the interface itself was activated. 

I found the solution then: the contants definition in the source view was missing but in the form view the constants was there. See the screenshots. Very strange...
I changed the source view of this interface with the current code from github and it works.

The abap stack is 7.53 SP0.

Best Regards 
Joerg

![grafik](https://user-images.githubusercontent.com/41207683/52897117-f2eba980-31d0-11e9-8656-94af5b3ae8b9.png)

![grafik](https://user-images.githubusercontent.com/41207683/52897122-0139c580-31d1-11e9-8c3d-dff3b5be355a.png)

![grafik](https://user-images.githubusercontent.com/41207683/52897126-0c8cf100-31d1-11e9-8ce0-b2176936bb5f.png)

![grafik](https://user-images.githubusercontent.com/41207683/52897130-144c9580-31d1-11e9-9de7-30683561ef25.png)

![grafik](https://user-images.githubusercontent.com/41207683/52897133-19a9e000-31d1-11e9-9642-20b307dbf4c1.png)

**Comment by larshp** [comment]
yea, sometimes it messes up when changing the code that is running

see https://docs.abapgit.org/guide-install.html, install the compiled report as ZABAPGIT_FULL in $TMP, and then use it to upgrade abapGit in $ABAPGIT, its the easiest way to fix issues like this, I dont think there is any workaround to avoid the dumps

**Comment by MDJoerg** [comment]
Thx!

**Comment by sandraros** [comment]
I had the same issue while upgrading from 1.86.1 to 1.86.2

I simply edited ZIF_ABAPGIT_VERSION via SE24, used the menu Utilities -> Regenerate sections, and activated it.

Then activated ZCL_ABAPGIT_GUI_PAGE.

**Comment by larshp** [comment]
Recommend keeping the full report in ZABAPGIT_FULL and update using it, as noted in https://docs.abapgit.org/guide-install.html
