### ISSUE TITLE
Refactoring: lcl_app

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#241]
ok, here are some thoughts.

lcl_app. probably a static class. manages app-wise resources. Methods:

- `run()` - branches between gui and background, creates resourses (user, gui ...)
- `gui()` - gets singleton instance of lcl_gui. lcl_gui is created privatly. lcl_gui will not have get() anymore
- `user()` - gets a singleton instance of current user. or creates instance for another user. In fact = lcl_user->constructor. lcl_user becomes privately created.
- `repo_srv()` - gets singleton instance of repo server (which so becomes non-static)
- `db()` - db persistence class instance
- `pw_man()` - password cache manager
- ??? anything else ?

**Comment by larshp** [comment]
looks good, there is probably something we have missed, but it will show up over time

**Comment by sbcgua** [comment]
Some doubts. Currently `FORM run` runs either `lcl_background` or `lcl_app`. But then lcl_background_persistence asks `lcl_app=>db()`. That works but does not look clean. I can move this to `app=>run()` but then call screen will be inside class - is it ok ?

```abap
      IF sy-batch = abap_true.
        lcl_background=>run( ).
      ELSE.
        lcl_app=>run( ).
        CALL SELECTION-SCREEN 1001. " trigger screen
      ENDIF.
```

**Comment by larshp** [comment]
ok :+1:

**Comment by sbcgua** [comment]
Then I guess this task can be closed. password/login manager - will move it later, maybe I'll adjust it a bit to keep also email for refresh.
