### ISSUE TITLE
Uninstalling https://github.com/abapinho/abaK.git gives error

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2410]
1: Install https://github.com/abapinho/abaK.git
2: click uninstall, it shows error "Error deleting ENHO"

triggering uinstall multiple times and it works

![image](https://user-images.githubusercontent.com/5888506/52911059-58a66700-329f-11e9-829f-21d1a45cc015.png)

**Comment by christianguenter2** [comment]
ZABAK_CX_ABAK enhances class ZCX_ABAK. When ZCX_ABAK is deleted the enhancement is deleted implicitly (quite suprisingly). 

![image](https://user-images.githubusercontent.com/17437789/52914490-44775f80-32c9-11e9-9e4e-9df513553dda.png)

![image](https://user-images.githubusercontent.com/17437789/52914544-fc0c7180-32c9-11e9-8906-901307b0f091.png)

Simple fix is to check existence before deleting.
