### ISSUE TITLE
abapGit UI hangs sometimes

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2415]
Occassionaly I encouter annoying delays in abapGit UI. They occur either at startup or when the page is switched or rerenderd. Nothing I can reproduce consistently. Usually it takes between 5 and 30 seconds until the UI is usable again. It appears on various systems. Colleagues working on the same systems at the same time didn't face any issues. In the next second it could be that abapGit works normal again. So quite strange and hard to analyze.

Maybe somebody noticed similiar phenomens?

E.g. at startup it looks like this. The report is started but the HTML control hangs.
![image](https://user-images.githubusercontent.com/17437789/52913935-ff502f00-32c2-11e9-9ca4-5f65c6745a2c.png)

**Comment by larshp** [comment]
try disabling the octicons

**Comment by christianguenter2** [comment]
Well, I thought about that, but I'd like to understand why it works in the exactly same setup and in the next second it doesn't work. 
Doesn't make sense to me.

**Comment by larshp** [comment]
yea, its difficult but octicons is an external factor

no problems here

**Comment by christianguenter2** [comment]
Agreed, I'd like to leave the issue open so others can log similiar problems and maybe we get better insight.

**Comment by larshp** [comment]
offline icons implemented via https://github.com/larshp/abapGit/pull/2454
