### ISSUE TITLE
Repo with circular dependencies is uninstalled but objects remain in the system

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2422]
I have a [repo](https://github.com/christianguenter2/test_TABL_SHLP.git) with circular dependencies (search help refers DB table and DB table refers search help). When I uninstall the repo the repo is removed and I don't get errors. But actually none of the objects is deleted.

![image](https://user-images.githubusercontent.com/17437789/52940885-e3529900-3367-11e9-8eb8-b10d089133ce.png)

Advanced > Uninstall
![image](https://user-images.githubusercontent.com/17437789/52940929-f6fdff80-3367-11e9-8005-bdf60a90db24.png)

No errors, but this message and the repo is removed from abapGit.

![image](https://user-images.githubusercontent.com/17437789/52940889-e5b4f300-3367-11e9-9e36-f1f9b98e8975.png)

All objects are still in the system.

![image](https://user-images.githubusercontent.com/17437789/52940992-2280ea00-3368-11e9-9a0d-4818af9daca5.png)

I'd expect some kind of error and that the repo isn't removed.

**Comment by larshp** [comment]
related: #379

**Comment by GoWale** [comment]
Hi, I think have fixed this issue and #379 in my local repo.
I will wait for my current open PR before mixing 2 issues with one PR.
