### ISSUE TITLE
 SPRX, No proxy exists for object Something (namespacehttp://www.foobar.com/something.xsd) 

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2430]
Getting error "SPRX, No proxy exists for object Buyer (namespacehttp://www.foobar.dk/file.xsd) " for multiple objects, 2 different systems.

The proxy objects seems okay, but are not serialized.

I do not know how to reproduce.

I've run some SAP standard SPRX consistency checks which are all okay(see package SAI_PROXY_TEST)

**Comment by larshp** [comment]
loading via

```abap
  DATA(lo_proxy) = cl_proxy_fact=>load_by_abap_name(
    object   = 'TABL'
    obj_name = 'ZSDFSDFSDF' ).

  DATA(lt_delta) = lo_proxy->get_delta_all( ).

  DATA(ls_sprx_db_data) = cl_proxy_db=>serialize(
    proxy     = lo_proxy
    inactive  = abap_false
    delta     = lt_delta ).
```

gives error

however showing object via SAP standard report SPRX_SHOW everything is okay

**Comment by larshp** [comment]
looks like there is some hierarchy in SPRX objects, the objects I get errors for are included in other SPRX files.

eg.
https://github.com/abapGit-tests/SPRX/blob/master/src/tablzblzget_bank.sprx.xml
contains 2 PROXY_HEADER lines, which seems wrong from a git perspective?

**Comment by flaiker** [comment]
I have the same issue. For me there's an additional error message in there:
![image](https://user-images.githubusercontent.com/5270359/53017020-57b43780-344f-11e9-9bc1-5f38a9fd3481.png)
It worked fine though a while back when I tested it with an offline repository.

**Comment by larshp** [comment]
phew, I'm not the only one 😅 

something like

```abap
  DATA(data) = cl_proxy_db=>load_by_abap_name(
    object   = 'TABL'
    obj_name = 'ZOBJECT' ).
```

works, and loads the same data as current serialization, however note the call to `cl_pxn_db=>db->select_hdr_by_hashid(` in `CL_PROXY_DATA`, so if ZOBJECT is part of a hierarcy, the full hierarchy is in `data`, in my case 24 different SPROXHDR headers
