### ISSUE TITLE
cl_proxy_db=>load_by_abap_name is unknown or PROTECTED or PRIVATE

### ISSUE THREAD

**Issue by mfallen** [larshp/abapGit#2440]
Actual version 1.84.0 can't be activated due to missing method in line 48060

**Comment by larshp** [comment]
which SAP_BASIS version are you on?

related: https://github.com/larshp/abapGit/issues/2365

**Comment by mfallen** [comment]
731	0023

**Comment by larshp** [comment]
does methods `cl_proxy_query=>get_hdr_by_abap_name` and `cl_proxy_db=>load` exist in your system?

**Comment by mfallen** [comment]
Both yes

**Comment by larshp** [comment]
@mfallen try this, https://github.com/larshp/abapGit/pull/2466

**Comment by mfallen** [comment]
@larshp  - updated coding with your new version. Can confirm all is working as expected, no errors anymore! Thanks

**Comment by larshp** [comment]
thanks, merging changes, closing issue
