### ISSUE TITLE
user setting: disable octicons - missing alternativ for favorit icon

### ISSUE THREAD

**Issue by GoWale** [larshp/abapGit#2445]
2419
With the new parameter (thx btw!) I have one issue.
On the repository overview I can not see if the repo is an active favorit and it is hard to "click" the missing icon.

Can we replace the missing icon with some Basic text dummy?
And for example change the color if it is active?

**Comment by larshp** [comment]
Related https://github.com/larshp/abapGit/issues/1479

Suggest that we make some custom icons and include in abapGit instead, it will solve the issue altogether, without adding extra logic in the code

**Comment by larshp** [comment]
but I think it will take less time to implement above, just adds complexity

**Comment by GoWale** [comment]
I don't think we have to stress this issue.
Most people have internet nowadays and the parameter helps me a lot to work with abapgit when I'm on the train.
An the isssue #1479 describes exactly the same issue so I'm fine with closing this one.
