### ISSUE TITLE
Refactor icons, make them offline

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2450]
Following #1479
There were a couple of issues and suggestions to move icons into the AG. As before I propose not to invent own icon set but reuse existing. There are icon sets with licence which allow using them even commercially. (anyway mentioning at the AG README would be the proper way of course).

General idea (by @larshp #1479) to create limited icon set and include it as MIME repo object.

I played a bit with octicons source and unexpectedly found that the build process is rather unclear and even buggy imho (!?). So I propose to keep it simple, change the icon set and use this service: http://fontello.com/

Very briefly: it provides several widely used icon sets with open licenses, allows to select them and build custom font with CSS map - so everything that is needed for AG. Along with the font - the config is saved (list of icons included).

Idea 1: create a separate repo with the config, on commit it starts CI script which recreates the font at fontello (there is an API for this) and create a PR to AG with the new font version. Looks cool but one issue: in order to use a new icon in UI one would need to go through this PR procedure first.

Idea 2: Same but push to master (mmmm ... don't like)

Idea 3: Keep both config and font as MIME objects. So the procedure to add an icon is: get config with SMW0, upload it to fontello, mark an icon to add (in their web page), download new font AND config. Commit both to MIME objects. Seems flexible. But manual.

What do you think ?

P.S. I checked, all the icons currently used in AG have an alternative in one or more icon sets available at fontello

**Comment by christianguenter2** [comment]
I vote for idea 3. Seems the most straight forward to me. But others would also be fine.

**Comment by larshp** [comment]
We dont add new icons very often, so IMHO its okay its manual, just need to keep a description under https://docs.abapgit.org/development/

Overall I would like to not be dependent on external licenses or services, but it will probably not happen anytime soon. With above suggestions we can have something running for users in quite short time

Still need to consider licensing, https://github.com/fontello/fontello/wiki/What-about-license%3F

**Comment by sbcgua** [comment]
WIP

![image](https://user-images.githubusercontent.com/15635498/53304842-c5fb5e80-3882-11e9-9cc3-34785966f6d2.png)

Seem like some CSS fixes needed ... but in general looks almost similar.

**Question**: where the font licenses should be mentioned ?
- option 1: add it as a MIME object too (fontello deliverable contains convenient file listing the fonts and sources). Advantage: can be included in `abapgit_full`, so distrib will contain the licenses - kind of nice ...
- option 2: at the bottom of readme

P.S. potentially useful links, for history
http://artplustech.com/generating-font-icon-files-from-the-command-line/
https://github.com/primer/octicons/issues/294
https://github.com/fontello/fontello

**Comment by larshp** [comment]
suggest restricting usage to 1 icon pack instead of 4, this way we have to mention only 1 license somewhere, and only figure out how to do it for one type

**Comment by sbcgua** [comment]
yes, sorry, heavy workload these days ...
So I support the 1 only icon pack conceptually. But some icons are missing in the fontello set ... e.g. branch which is quite difficult to replace ...
I'm looking into possibility to use latest font awesome which have more icons and branch in particular. But there is no web tool :( So probably will need come python or node programs to install. Will write about the findings soon, probably closer to the weekend.

**Comment by larshp** [comment]
something like https://github.com/jeerbl/webfonts-loader can take custom SVGs and make a font, just need someone artistic to do a few SVGs

**Comment by sbcgua** [comment]
some progress: https://github.com/sbcgua/abapgit-icon-font
@larshp shell I move it to abapGit namespace by the way ?

**Comment by larshp** [comment]
created https://github.com/abapGit/icon-font

**Comment by sbcgua** [comment]
I'd better transfer ownership for the existing one. But I need auth to create repos (currently got a mistake because of it).

**Comment by sbcgua** [comment]
@larshp cannot push to your repo, could you add auth pls ?

**Comment by larshp** [comment]
hmm, you should have write access to https://github.com/abapGit/icon-font, you also accepted the collaborator invitation?

**Comment by sbcgua** [comment]
I haven't got collaboration invite ... though there was email that I automatically subscribes as watcher ... and git says "Access denied" on push

**Comment by larshp** [comment]
hmm,
![image](https://user-images.githubusercontent.com/5888506/53901664-c7294a00-403f-11e9-9bb4-ac7630e19eef.png)

**Comment by sbcgua** [comment]
just managed to update readme directly in repo, strange. will try another way

**Comment by sbcgua** [comment]
guess can be closed unless there are bugs found ...

**Comment by sbcgua** [comment]
Link to final docs: https://docs.abapgit.org/development/adding-icons.html

**Comment by larshp** [comment]
works for me, thanks, closing
