### ISSUE TITLE
Adding Horizontal scrollbar to Branch Overview

### ISSUE THREAD

**Issue by Sdfraga** [larshp/abapGit#2481]
Hello,

When you have a lot of commit's in one repo and you want to see the branch overview I have to zoom out the page in order to have a clear view of the history of my repo.

![image](https://user-images.githubusercontent.com/16186872/53720274-98a14880-3e60-11e9-8799-5e6eec223ad5.png)

Since I am having more and more commits, the zoom out stragegy is no longer OK since I am not able to read the commit messages.

![image](https://user-images.githubusercontent.com/16186872/53720313-bc648e80-3e60-11e9-8941-317930510c15.png)

If someone can point me where to play with the css/html I can give it a try by my own to see If I can add the Hor. scrollbar.

Thanks
Sérgio

**Comment by larshp** [comment]
heh, cool

this looks like a bug, but it in most of these cases it does not have to add horizontal width? http://gitgraphjs.com might be doing some tricks

alternatively consider the merge strategy, rebase/squash to master instead of adding a merge commit

**Comment by Sdfraga** [comment]
Well I am using Branch Feature strategy for my project, so every time I have a new feature I keep adding new branches, implement what is asked, and when tested, commit to master.

I am still learning git workflows so I will have a look to your suggestion of rebase/squash.

Regarding the branch overview page, I think the problem is that each commit done to master is taking the wrong space in the screen, going more and more to the right. 
When a merge is done and the branch is deleted, a newer branch should take the place on the screen used by the deleted one.

**Comment by larshp** [comment]
Suggest making a public repo with some dummy code, just a few branches is needed to illustrate the problem

**Comment by Sdfraga** [comment]
You should get the same behavior from the Branch Overview of the abapGit repository no?
What is strange is that if I launch the Branch Overview on abapGit repo I don't get any graph..

![image](https://user-images.githubusercontent.com/16186872/53723082-3730a800-3e67-11e9-907a-d566858465ef.png)

Nevertheless I will create a public repo to reproduce the wrong behavior.

**Comment by christianguenter2** [comment]
I guess for abapGit the graph is to already too large. It also takes ages for abapGit to calculate the graph. Maybe we can do some optimizations there. I vaguely remember that I had a look on this, but it was quite difficult.

**Comment by larshp** [comment]
yeah, the graph for abapGit is too big, perhaps add option to only look at latest 200 commits

**Comment by Sdfraga** [comment]
Hello,

I have created repo https://github.com/Sdfraga/BranchOverviewBug to do a simple test and it seems that this "growing behaviour on each merge" is just how gitgraphs works.

![image](https://user-images.githubusercontent.com/16186872/53802186-7af7e000-3f41-11e9-8af8-8ba9574b0ca0.png)

Not sure why @larshp mention that this is a bug but I did some investigation and the HTML looks like is beeing well created. Can you give me some more hints?

Regarding the rebase/squash strategy, is abapGit ready for them?

**Comment by flaiker** [comment]
Just for clarification: Do you delete the branches after they are merged into master?

**Comment by Sdfraga** [comment]
Yes I do.

My workflow is:

1 - Create new branch for new feature
2 - Implement the new feature in branch
3 - Merge branch to master
4 - Delete branch

**Comment by larshp** [comment]
looking at http://gitgraphjs.com/examples/index.html it also does not reuse the space

**Comment by Sdfraga** [comment]
That’s what I found out also.

Maybe a horizontal scroll in this case could be sufficient.

**Comment by Sdfraga** [comment]
Just playing around with the HTML...
If we enclosure the CANVAS element used for gitGraph in a DIV with the css property overflow-x: scroll

![image](https://user-images.githubusercontent.com/16186872/53807178-31ae8d00-3f4f-11e9-88b5-5f6593ffd073.png)

It will generate the Horizontal scroll

![image](https://user-images.githubusercontent.com/16186872/53806997-bfd64380-3f4e-11e9-84cb-1f7f5fe43244.png)

This was just quick and dirty to see if it works.

Now the scrollbar should be on the top of the canvas but for this some JS must be added.
Do you agree with this strategy?

**Comment by Sdfraga** [comment]
Hi,

So I decided to give it a try and get my hands dirty (finally) in this amazing project.

My goal was to **create a horizontal  scroll bar on top of the gitGraph element** that is showing this nice visual history of the project commits when the number of commits is exceeding the space on the screen

After touching on the common.js, common.css and in zcl_abapgit_gui_page_boverview class I manage to implement it:

![image](https://user-images.githubusercontent.com/16186872/54130505-cb26e480-4410-11e9-9745-a40de39c69b5.png)

**zcl_abapgit_gui_page_boverview**

- Created some DIV Elements to wrap gitGraph Element to manage the  Horizonal Scroll bar on top the element
- Added setGitGraphScroller() js function to initialize the width of the scroll bar with the same width of gitGraph element

**common.css**

- Added some CSS to manage the created Wrappers

**common.js**

- setGitGraphScroller() - Initialize Scroll bar width dynamically
- GitGraphScroller() - Event Handler for onScroll Event

To test this please pull branch _gitGraph-horizontal-top-scroll_ on my fork [https://github.com/Sdfraga/abapGit]()

**Comment by larshp** [comment]
feel free to open a pull request with the fixes 😄

**Comment by larshp** [comment]
guess this issue can be closed?

**Comment by Sdfraga** [comment]
I think we can close it since the functionality is there and working.
There are some issues regarding performance like @christianguenter2 pointed out and I found issues on the ordering of the branches but I will create new issues for that.
