### ISSUE TITLE
After abapGit updates, execution of program ZABAPGIT runs into errors

### ISSUE THREAD

**Issue by NaveenKurmadas** [larshp/abapGit#2489]
After abapGit updates, execution of program ZABAPGIT runs into errors.

![image](https://user-images.githubusercontent.com/35898274/54042692-c257c800-41f0-11e9-9abc-dad1c2547ae7.png)

**Comment by jfilak** [comment]
Do you use the compiled (single source) abapgit or do you install abapgit from this git repository?

**Comment by jfilak** [comment]
By the way, not reproducible on my ABAP Trial 752 with the single source abapgit nor development abapgit.

If you use compiled abapgit, please, try to reinstall.
If you use developement abapgit, please, consult `tcode SMW0 -> Binary data forWebRFC applicaitons -> Object name = zabapgit_icon_font_css`.

**Comment by sbcgua** [comment]
Just re-updated both dev and full versions of AG on 731 - also cannot reproduce. +1 for reinstall. Should work fine.

**Comment by larshp** [comment]
@NaveenKurmadas can you provide additional information?

**Comment by NaveenKurmadas** [comment]
reinstall fixed the issue. Thanks
