### ISSUE TITLE
Big icons issue

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2490]
Run into this
![image](https://user-images.githubusercontent.com/15635498/54061509-da881100-4209-11e9-8e74-d76bea7e62ef.png)

@bigld could you pls share some info about your screen config ? The code you've proposed in #2275 certainly makes sense. But I have `cl_gui_cfw=>compute_pixel_from_metric( x_or_y = 'X' in = 1 )` returning 2, so the icons become large but the font does not. So I'm a bit confused about proper condition for the large icon. Do you have some specific windows scaling params ?

my params: win10, 3440x1440, 125% "change size of text" in display settings (hmm, why pixel has 2x ? It is not Hi DPI from what I understand).

**Comment by sbcgua** [comment]
BTW any one has the same issue ?

**Comment by sbcgua** [comment]
![image](https://user-images.githubusercontent.com/15635498/55292089-13716b00-53ef-11e9-9379-9e296053a6c5.png)
Guess we need some switch to force big icons on or off ...

**Comment by sbcgua** [comment]
... you know, big icons are not that bad, I event like them :) Just will need some CSS fixes ...
... and one more crazy idea - what about Dark Theme ? :)))

**Comment by larshp** [comment]
+1 for dark theme

**Comment by sbcgua** [comment]
Guess can be closed
