### ISSUE TITLE
Deserialize, return object log

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2495]
Return log of actions/objects deserialized when performing deserialize, related to #2169

**Comment by larshp** [comment]
1: Method ZCL_ABAPGIT_REPO->DESERIALIZE should return/append an instance of a log object
and pass to ZCL_ABAPGIT_OBJECTS->deserialize / ZCL_ABAPGIT_OBJECTS->DESERIALIZE_OBJECTS

2: Extend ZCL_ABAPGIT_LOG so it is possible to specify an object that the message relates to

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit/issues/2821

**Comment by mbtools** [comment]
Looks like these changes have been implemented https://github.com/larshp/abapGit/pull/2729
