### ISSUE TITLE
2 unit tests in ZCL_ABAPGIT_GUI_PAGE_DIFF failing

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2498]
2 unit tests failing in ZCL_ABAPGIT_GUI_PAGE_DIFF

Something regarding patches, @christianguenter2 

![image](https://user-images.githubusercontent.com/5888506/54207041-beba8e80-44d9-11e9-8093-c438b6e45f04.png)

**Comment by sandraros** [comment]
Note: this issue dates from commit 389512f690344ab6438e6d117fdc0b79fc271560 on Feb 26, 2019
