### ISSUE TITLE
Refactoring: centralize db commits, move it to models

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#250]
Follows #219 

> @mrsimpson Commit after each DB-Interaction... Personally, I had thought of coding the COMMIT WORKs ins the Data access class.
> 
> @sbcgua pushing commits to model is not that bad idea here - all db updates seems atomic: repo synced - update and commit, create package - commit, etc ...
> 
> @larshp good arguments, lets do it, push it down :smile: it should be possible to limit COMMIT WORK to some of the methods in LCL_PERSISTENCE_DB. Guess ROLLBACK WORK will not be needed anywhere.

**Comment by larshp** [comment]
Note that it has to be `COMMIT WORK AND WAIT` when moving the commits down. To make sure the update task releases the lock before next code in abapGit is executed, it sometimes needs the lock for the same object right away.

**Comment by bigld** [comment]
how should we deal with implicit commits? HTTP communication will do this!

**Comment by larshp** [comment]
implement small framework for buffering changes in memory, much like BOPF

**Comment by flaiker** [comment]
Maybe object services transactions could also help? (IF_OS_TRANSACTION, CL_OS_SYSTEM=>GET_TRANSACTION_MANAGER, ...)

**Comment by larshp** [comment]
never tried it, looks like it is used in connection with persistent classes? We just need something that works on 702

**Comment by flaiker** [comment]
The object services transaction concept was made for persistent classes but I just use it without them (works fine with opensql). The main advantages are you can rollback parts of a LUW, you can use update tasks without creating update function modules and you have an OO transaction API (which is nice for dependency injection).
I do not know about the implicit commits though. In non compatibility mode it might just throw a runtime error (external commit not allowed).

An internal table with outstanding changes that can be persisted at any time will probably be easier (which I assume is your idea of a buffer).

**Comment by larshp** [comment]
interesting, is there any documentation somewhere on how to use it? Perhaps you can write a blog post about it?

**Comment by flaiker** [comment]
Documentation is [here](https://help.sap.com/http.svc/rc/abapdocu_751_index_htm/7.51/en-US/index.htm?file=abenabap_object_services_transact.htm). I might write a blog about it when I have some time (focusing on usage without persistent classes).

**Comment by larshp** [comment]
lets close this? doesnt seem like its been a topic since 2017
