### ISSUE TITLE
F2A error while trying to clone github Repository in ABAP server

### ISSUE THREAD

**Issue by shaniniza** [larshp/abapGit#2523]
I am getting the below error while executing test SSL program.
Certificate:
 Certificate:
  Subject:                              CN=github.com, O="GitHub, Inc.", L=San Francisco, SP=California, C=US, SN=5157550, OID.1.3.6.1.4.1.311.60.2.1.2=Delaware, OID.1.3.6.1.4.1.311.60.2.
  Issuer:                               CN=DigiCert SHA2 Extended Validation Server CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Serial Number:                        0A:06:30:42:7F:5B:BC:ED:69:57:39:65:93:B6:45:1F
 Verification result:
  Status:                              Not successful
  SignerStatus:                        Not successful
  SignerVerificationResult:
   Status:                              Not successful
   Validity:                            Successful
   BasicConstraints:                    Successful
   KeyUsage:                            Successful
   ObjectStatus:                        Not successful
   SignerCert:
    Certificate:
     Subject:                              CN=DigiCert SHA2 Extended Validation Server CA, OU=www.digicert.com, O=DigiCert Inc, C=US
     Issuer:                               CN=DigiCert High Assurance EV Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
     Serial Number:                        0C:79:A9:44:B0:8C:11:95:20:92:61:5F:E2:6B:1D:83
    Verification result:
     Status:
Any details regarding the correct certificate to be installed?

**Comment by larshp** [comment]
see https://docs.abapgit.org/guide-ssl-setup.html

**Comment by shaniniza** [comment]
Followed the above and from the given site, which certificate to be installed?
https://www.digicert.com/digicert-root-certificates.htm

**Comment by larshp** [comment]
can you help posting a screenshot of the result of the ssl check program? https://docs.abapgit.org/other-test-ssl.html

**Comment by shaniniza** [comment]
Hi, certificate installed successfully. Thanks for the support. AbapGit is working now.
