### ISSUE TITLE
Unification of UI Core

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2525]
Goal: clean the code, make UI more reusable

Steps / proposed changes

- [x] Move GUI related constants from `zif_abapgit_definitions` to GUI classes/interfaces, create interface for `zcl_html`
- [x] separate processing of UI exceptions from `ZCL...GUI`
- [x] make `assetman` more abstract and universal
- [x] Split `ZIF_GUI_PAGE` into `zif_abapgit_gui_renderable` and `zif_abapgit_gui_event_handler`
- [x] Remove `ZIF_GUI_PAGE`
- [x] Make `zcx_abapgit_cancel` a subclass of `zcx_abapgit_exception`
- [x] Move `zcx_abapgit_cancel` to /ui/, ~~potentially rename to `zcx_abapgit_ui_cancel`~~
- [x] Graceful free of GUI, go_page
- [x] Move assetman, gui, html, interfaces to `/ui/core/` (new subpackage)
- [x] Add some dev docs

Draft of working code can be found [here](https://github.com/sbcgua/abap_gui_boilerplate/blob/master/src/zguibp_html_contrib.prog.abap)

**Comment by sbcgua** [comment]
Do you think it makes sense to rename zcx_abapgit_cancel to zcx_abapgit_ui_cancel (or zcx_abapgit_gui_cancel) ? (step 6). On the one hand it kind of shows that it is UI only exception. On the other ... who cares ? The belonging to ui package should be enough ?

**Comment by larshp** [comment]
belonging to the UI package should be enough

**Comment by sbcgua** [comment]
Reconsidering this point "Make zcx_abapgit_cancel a subclass of zcx_abapgit_exception". The idea is to be able to catch just `zcx_abapgit_exception` in GUI classes. Does this make sense ? Or better to keep them apart ?

**Comment by mfallen** [comment]
With this "change", on SAP_ABA 731 0023, error "Before the "INTERFACES 
 IF_ABAPGIT_GUI_RENDERABLE" statement, the interface in question must be fully defined." is raised when trying to active (error in line 1045)

**Comment by sbcgua** [comment]
Are you using one-file version ?
Quick fix: move `zif_abapgit_gui_renderable` (line 1071) above `zif_abapgit_gui_page`

Seems to be an issue of abapmerge (opened https://github.com/larshp/abapmerge/issues/80)
Also: the issue should go after all pages are transfered to if_renderable instead of page (which I will PR soon, maybe today)

**Comment by larshp** [comment]
just to clarify, does this happen right now in master, or in the open pull request?

**Comment by sbcgua** [comment]
master. In a built one-file

**Comment by mfallen** [comment]
> Are you using one-file version ?
> Quick fix: move `zif_abapgit_gui_renderable` (line 1071) above `zif_abapgit_gui_page`
> 
> Seems to be an issue of abapmerge (opened [larshp/abapmerge#80](https://github.com/larshp/abapmerge/issues/80))
> Also: the issue should go after all pages are transfered to if_renderable instead of page (which I will PR soon, maybe today)

Correct, quick fix is working

**Comment by larshp** [comment]
try again, latest version

**Comment by mfallen** [comment]
> try again, latest version

Working again, thx for checking

**Comment by sbcgua** [comment]
OK, with the docs PR it is almost done.
A couple of doubtful points left, @larshp what do you think ?

1. Remove `ZIF_GUI_PAGE`? Now it is a combination of `ZIF_RENDERABLE` and `ZIF_EVENT_HANDLER`. Which is imho confusing. On the other hand it works well. 
2. Make `zcx_abapgit_cancel` a subclass of `zcx_abapgit_exception`, which will enable to catch just `zcx_abapgit_exception` e.g. in `on_event`. On the other hand `cancel` is a user action versus error
3. Your comment from #2557, event vs interface, I can redo as interface if required. No big preference from my side.

**Comment by larshp** [comment]
1: yes
2: yes
3: yes, but not super important. Events are nice, but I dont think this is the use case, since we have tight coupling 1 to 1. I consider tight coupling a nice thing for doing where-used

**Comment by sbcgua** [comment]
I think this one can be closed now.
Maybe will try to play with the event middleware a bit later to avoid calling super->on_event every time. But not sure about the approach. Currently I have an idea to pass some `gui_context` instance as an optional parameter to `render` ... or in `constructor`. The context would have a) `register_handler` to insert an event handler into the stack b) probably access to gui instance, to call `go_to_page` directly if needed or ... c) access to asset manager for the case of loading additional non-cacheable assets specific for the page. The problem is that this context must be passed some how. Via render or via construction. I don't see the way to make it automatic.
