### ISSUE TITLE
Other Namespace

### ISSUE THREAD

**Issue by wjlindner** [larshp/abapGit#2527]
Hi all,
Is it possible to use abapGit also for other namespaces like /cust/ ?
Regards
Wolfgang

**Comment by larshp** [comment]
depends a bit on the scenario, pushing is no problem, for pulling see https://docs.abapgit.org/ref-namespaces.html

**Comment by larshp** [comment]
@wjlindner did above help?

**Comment by larshp** [comment]
closing, no reply
