### ISSUE TITLE
New icons in Java UI?

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2529]
Can someone help testing if the new icons works on Java UI?

**Comment by jfilak** [comment]
Which icons should I check?

**Comment by jfilak** [comment]
I am afraid that my JavaGUI on linux does not display any icons except the ones on the changed files:
![image](https://user-images.githubusercontent.com/1902249/54425013-8ce13c00-4714-11e9-8381-544e3e839c53.png)

**Comment by larshp** [comment]
@sbcgua any thoughts?

**Comment by jfilak** [comment]
I am afraid that I didn't see any icons even before the upgrade. zabapgit looks completely different in SAP GUI for Windows.

**Comment by sbcgua** [comment]
From what I remember when I tried to make it work on Mac: I didn't manage to display fonts at all. And it is very unclear which browser is used to render pages in JGUI. On the one hand it understands reasonably modern (IE10+ ...) CSS for a completely custom implementation. On the other there are issues with JS if I remember well too. So looks more like some custom limited Java based implementation.
And no errors ... no logs ... afaik.
The only solution idea is to detect java env and output some icon replacements. E.g. squares/circles and first letter of icon name inside. Kind of better than nothing ...

**Comment by jfilak** [comment]
From my point of view, do not waste time on eye candy things like Icons, I don't need them (you know, I am a console guy). I would rather appreciate a powerful abapGit ADT HTTP API, which I can integrate into `sapcli` and which already exists ;)
