### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by filak-sap** [larshp/abapGit#2544]
The following is the content of zabapgit:

```
No leaf found: zif_abapgit_gui_page, 
zif_abapgit_gui_page->faces zif_abapgit_gui_event_handler, zif_abapgit_gui_page->faces zif_abapgit_gui_renderable, 
```

**Comment by filak-sap** [comment]
abapmerge's `npm test` failing

**Comment by larshp** [comment]
yeah, see https://github.com/larshp/abapGit/issues/2525

**Comment by larshp** [comment]
and https://github.com/larshp/abapmerge/issues/80

**Comment by filak-sap** [comment]
Nice, thank you very much for the information. Please, consider merging this PR for abapmerge:
https://github.com/larshp/abapmerge/pull/81

**Comment by larshp** [comment]
try again, latest version, build should be fixed now

**Comment by filak-sap** [comment]
Indeed, the current version of zabapgit is OK. Thank you very much. Even abapmerge works on my machine. Well done!
