### ISSUE TITLE
SFPF: would it make sense to store layouts in separate files?

### ISSUE THREAD

**Issue by filak-sap** [larshp/abapGit#2554]
I would appreciate, if I could edit XDP forms in Adobe LiveCycle Designer, commit & push them to a git repo and pul them to my system using abapGit. It would also be possible to easily spot changes to the layout done by someone else.

I am not sure if it is a problem or not but we have a variant of the layout for every supported language but it is possible to get only the layout of Form's language. I am not sure how it works.

**Comment by larshp** [comment]
lets try 😄
