### ISSUE TITLE
Branch Overview Hierarchy Order

### ISSUE THREAD

**Issue by Sdfraga** [larshp/abapGit#2556]
Seems that Overview Page is managing wrongly the branches hierarchy due to alphabetic order.
I created a [repo](https://github.com/Sdfraga/BranchOverviewBugNOK) with the following branche structure:

master => branch2 => branch1 => branch0

The output of the abapGit page Overview:

![image](https://user-images.githubusercontent.com/16186872/54592972-bf997600-4a2d-11e9-862a-d18c64b96939.png)

Or we manage the sorting of MT_BRANCHES somehow or we have to review the algorithm implemented on **zcl_abapgit_branch_overview->determine_branch**.

I believe we could implement some kind of recursion to manage the branch manipulation on this method but as I said, maybe is as simple as sorting the internal tables at some point..

**Comment by Sdfraga** [comment]
Hello @larshp 

I am trying to understand who is defining the order of the branches when the request is done.

Seems like in class ZCL_ABAPGIT_GIT_TRANSPORT we have method BRANCH_LIST where the request to git server is done.
In this method I can see that the value of LV_DATA comes with the branches ordered alphabetically :

![image](https://user-images.githubusercontent.com/16186872/55167847-fed46f00-5171-11e9-8998-bf51cd209133.png)

Do you have any hint why this happening?

**Comment by larshp** [comment]
above is the reply from the git server, it decides the sequence, I dont think the protocol sets requirements for the sorting. Anyhow, we can just add code in the branch overview to sort it differently

**Comment by Sdfraga** [comment]
Fixed by PR #2594
