### ISSUE TITLE
ENHO Clas/Intf TYPES enhancements not handled

### ISSUE THREAD

**Issue by sandraros** [larshp/abapGit#2568]
I have enhanced a class pool, I added types, methods and attributes using these types.
I saw that the types are not handled at all.
Consequently, committing the object does not record the type(s) in the xml file of the enhancement object (ENHO). When pulling the enhancement in a fresh environment, it doesn't compile because the type is missing.
Same issue with interface pools.

**Comment by larshp** [comment]
can this be closed?

**Comment by sandraros** [comment]
Yes, thank you. Closed.

**Comment by sandraros** [comment]
Sorry, my code was buggy, <ls_attr> used instead of <ls_type> in the block to avoid differences (CLEAR author and so on).

May I also propose more code for enhancements: I saw that the method implementations for new methods were not deserialized at all, that the events were not created too, and a few fields not cleared to avoid differences (descript_id for the OTR texts which are recreated so the GUID doesn't matter + ext & extid for the Hook enhancement numbers which are also renumbered). If you're okay, then I will complete the main description of the issue too.

**Comment by larshp** [comment]
yeah, just open additional issues and pull requests
