### ISSUE TITLE
After Updating where-used list: "Error from RPY_DYNPRO_INSERT: 6"

### ISSUE THREAD

**Issue by GiantCrocodile** [larshp/abapGit#2575]
Hello,

we are using abapGit 1.86.0 and we are facing an error on importing a package which we exported with abapGit. After importing the package from the online repository by pressing 'PULL', we are getting this error message `Error from RPY_DYNPRO_INSERT: 6` after the step where abapGit updates the where-used list of the objects. Import and export were done on the same system.

We are running on NW 731 SP 15. The export has been created with folder logic `PREFIX` in the repository settings and it's imported with folder logic `FULL`. No other options set in the repository settings. Our package contains a registered customer namespace like `/EXAMPLE/<package_name>`.

Thanks for your support!

Best Regards

**Comment by larshp** [comment]
try setting a breakpoint at https://github.com/larshp/abapGit/blob/06097f96142e655b46729b1e32339b24ff33020f/src/objects/zcl_abapgit_objects_program.clas.abap#L372 and check SY messages

**Comment by larshp** [comment]
https://github.com/larshp/abapGit/issues/1174 might be relevant, check if function module RS_SCRP_CHECK_FIELD_POSITIONS gives an error

**Comment by GiantCrocodile** [comment]
I've forwarded this to my colleague and I will get back to you quickly with more information. Thanks for your support!

**Comment by GiantCrocodile** [comment]
According to the sy message variables we found out that there is an error thrown:
`The field <field_name> doesn't exist in active version of table <our table>.`

The missing field is a field of one of our own tables. We have to find out if this field is called in the source code or on the dynpro somewhere.

Function module RS_SCRP_CHECK_FIELD_POSITIONS seems fine but some call after it seem to set the sy-subrc to 6. SAP Logon is crashing with C parser thread fail popup during debugging so we are not able to analyse it right now.

Our developer will analyse this in detail next days. So far, I can't provide more details.

**Comment by larshp** [comment]
there might be some issues in the deserialization sequence, so `<our table>` does not exist or is not active when the dynpro is inserted. It should have been imported, check the status in SE11 and try activating manually, then retry the import

**Comment by larshp** [comment]
If you are using the long report, it might help with the "C parser" error if you install the many classes instead.

RS_SCRP_CHECK_FIELD_POSITIONS: added https://github.com/larshp/abapOpenChecks/pull/682 to check for this in the future

**Comment by GiantCrocodile** [comment]
I checked see11/se16: The table does exist and it is active. The mentioned field is missing.

**Comment by larshp** [comment]
@GiantCrocodile any news?

**Comment by GiantCrocodile** [comment]
I've contacted our developer regarding this and asked for news. I'm sorry for the late reply @larshp - seems like I missed the notification e-mail.

**Comment by GiantCrocodile** [comment]
It looks like an issue in the exported objects. I will close this issue now due to the fact that it's most likely a mistake on our side. Thanks for your support @larshp!
