### ISSUE TITLE
shortdump or diff always shown after pull of ENHO Clas/Intf TYPES enhancements

### ISSUE THREAD

**Issue by sandraros** [larshp/abapGit#2577]
I have added types to standard classes via enhancement and pushed them (possible since #2568), the pull works fine but there's still a DIFF shown because of author, date and time.

Here is the error in the method SERIALIZE of ZCL_ABAPGIT_OBJECT_ENHO_CLIF, the use of `<ls_attr>` is incorrect (origin: #2568), instead `<ls_type>` should be used:

    LOOP AT lt_tab_types ASSIGNING <ls_type>.
      CLEAR: <ls_attr>-author,
             <ls_attr>-createdon,
             <ls_attr>-changedby,
             <ls_attr>-changedon.
    ENDLOOP.

This code error also generates a **short dump GETWA_NOT_ASSIGNED** (cf #2584) at the line <ls_attr>-author if the enhancement contains a new type, but doesn't contain any attribute.

Reproducing steps:
- Run ZABAPGIT
- Click an abapGit project which contains such an ENHO object
- Short dump occurs immediately before even displaying the objects of the project (during the serialization phase of local objects)

**Comment by larshp** [comment]
@sandraros is this still a problem?

**Comment by sandraros** [comment]
> @sandraros is this still a problem?

No, it has been corrected by https://github.com/larshp/abapGit/commit/f603147bd10e870a9d207b95d70a1a2600766d72, I cannot reproduce the error. I close the issue. Thanks!
