### ISSUE TITLE
diff always shown after pull of ENHO hooks (implicit enhancements)

### ISSUE THREAD

**Issue by sandraros** [larshp/abapGit#2579]
After pulling implicit enhancements (ENHO hooks), abapGit may show a difference, it will then always remain:

![image](https://user-images.githubusercontent.com/34005250/55018889-138af880-4ff4-11e9-8baa-d74fedff7627.png)

Reason: if the author has created and deleted implicit enhancements in the original system, the numbering doesn't start from 1 (this is the numbering we can see for the statement ENHANCEMENT, for instance `ENHANCEMENT 1. ... ENDENHANCEMENT.`)

Solution: don't push the enhancement number, so that it is not compared.

**Comment by larshp** [comment]
guess this can be closed?

**Comment by sandraros** [comment]
yes
