### ISSUE TITLE
enhancement events and pulling of NEW enhancement methods

### ISSUE THREAD

**Issue by sandraros** [larshp/abapGit#2580]
Enhancement events are not serialized at all (missing feature).

![image](https://user-images.githubusercontent.com/34005250/55021227-ad54a480-4ff8-11e9-8aa0-e6a7b5a41a0b.png)

The code of new enhancement methods (not the implicit enhancements of existing methods, the code for methods added) are serialized but not deserialized (incomplete feature).

![image](https://user-images.githubusercontent.com/34005250/55021321-d4ab7180-4ff8-11e9-8402-9e0dbcdb77fe.png)

There is also an issue for the DIFF. It may still appear after pulling ENHO objects, concerning attributes (OTR text ID) and method parameters (author, date, etc.)

**Comment by sandraros** [comment]
By the way, beside the correction, I have also refactored by moving the method `SERIALIZE_INCLUDES` from the class `ZCL_ABAPGIT_OBJECT_ENHO_CLIF` to `ZCL_ABAPGIT_OBJECT_ENHO_CLAS` and created `DESERIALIZE_INCLUDES` in the latter class because method implementations exist only for classes, not for interfaces.

**Comment by larshp** [comment]
@sandraros can this issue be closed?

https://github.com/larshp/abapGit/pull/2601 was merged

**Comment by sandraros** [comment]
Yes!
