### ISSUE TITLE
Shortdump in zcl_abapgit_object_enho_clif - field-symbol not assigned

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2584]
Seems like a copy paste error
https://github.com/larshp/abapGit/blob/c7f21c2a5bdde972a76775ef87fe710e2819646c/src/objects/zcl_abapgit_object_enho_clif.clas.abap#L94-L99

**Comment by flaiker** [comment]
Duplicate of #2577, f5d1f3d213d446185b8a3fffa837b2107990a625, #2578 ?

**Comment by christianguenter2** [comment]
Yes, seems so. Thanks for notifying. Closing.
