### ISSUE TITLE
Is it possible to use VSTS protected repo?

### ISSUE THREAD

**Issue by JayKidd81** [larshp/abapGit#2587]
Hi,

More of a question, is it possible to connect with an online repo hosted in visual studio team services (VSTS)?

Currently getting: HTTP error 421 occured: Unknown error

VSTS Authentication options: https://docs.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=azure-devops

I believe these might be related?
https://github.com/larshp/abapGit/issues/1331
https://github.com/larshp/abapGit/issues/1257

Thanks,
Jay :)

**Comment by larshp** [comment]
I think it worked last I tested it, suggest first trying with a public repo.

**Comment by JayKidd81** [comment]
Have performed some additional testing, github repos seem fine, it's just vsts repos that we're are having difficulty connecting with.

Have setup and shared below some test vsts repos, just in case the issue is limited to our SAP environment, but test http connections work as expected (SA38 -> RSWF_TEST_HTTP).

public:
git ls-remote https://dev.azure.com/abapGitTestJK/public/_git/public

private:
git ls-remote https://dev.azure.com/abapGitTestJK/private/_git/private
_(can message me with your email address to be added as a user to this private repo)_

Any guidance or suggestions much appreciated... :)

**Comment by larshp** [comment]
did you try using tokens https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops ?

**Comment by JayKidd81** [comment]
I have not yet as was unsure how to enter the credential (token) into abapGit. I assume it would go into Database util ->  user/repo but am unsure how to apply. Any guidance available? :)

**Comment by larshp** [comment]
in the password popup, enter your username, and then the token as password

**Comment by JayKidd81** [comment]
Unfortunately, it doesn't popup a user/pass, if I click branches, it just shows the HTTP error 421 occured: unknown error, and if I click ok, it closes the window without creating a repo. :(
![image](https://user-images.githubusercontent.com/28907929/55140266-ea738080-5137-11e9-85c5-4a1542486413.png)

**Comment by Sdfraga** [comment]
Hello,

I am also using Azure DevOps as a git server and everything works fine for me.
My setup is:

1 - Since I have a company proxy I entered the credentials in the abapGit Setup page:

![image](https://user-images.githubusercontent.com/16186872/55141181-1bed4b80-513a-11e9-9bf3-95b9b8c5bd1f.png)

2 - I have created a personal token as @larshp suggests:

![image](https://user-images.githubusercontent.com/16186872/55141262-50610780-513a-11e9-98a4-0f75088c3aef.png)

3 - When connecting to a Azure Repo I have to enter my credentials (popup is launched):

**Comment by sandraros** [comment]
I confirm. It works for me, with the Personal Access Token too.
HTTP 421 = Misdirected Request (proxy?)
PS: Microsoft has renamed VSTS into Azure DevOps a few months ago.

**Comment by JayKidd81** [comment]
Boom, got it. Thanks for all the help larshp, sdfraga & sandraros!
The HTTP 421 error was due to a missing certificate in STRUST. Have added and it asks for the login details! 
Cheers :)
