### ISSUE TITLE
commit page, press enter

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#259]
on the new commit page, the cursor is focused in the commit text field so the text can be entered without using the mouse.

However it is not possible anymore to press enter to submit the commit, instead the mouse has to be used to point and click to the commit link.

@sbcgua can we change this so there is a submit button in the form?

**Comment by sbcgua** [comment]
indeed. I'll have look

**Comment by sbcgua** [comment]
Fixed as described [here](http://stackoverflow.com/questions/29943/how-to-submit-a-form-when-the-return-key-is-pressed)
But maybe it would be cleaner to get back the submit button, just restyle it. I'll think on it.

The issue can be closed.

**Comment by larshp** [comment]
thanks, tested ok
