### ISSUE TITLE
DISPLAY_NAME not refreshed on abapGit main page when edited via Database Util

### ISSUE THREAD

**Issue by Sdfraga** [larshp/abapGit#2603]
When using the feature Database Util to edit the Repo metadata, namely the DISPLAY_NAME field, the change is saved in the database but it's not refreshed in the main abapGit page favorites toolbar.

To see the correct name abapGit must be reloaded.

**Comment by larshp** [comment]
yeah, a lot of the things does not reload when using the database util. I dont think this is a problem, using the db tool is not a typical use case

**Comment by Sdfraga** [comment]
Just something I noticed. 
If its agreed that this is just like Database Util behavior works it's OK for me. There's no reference to the repo object on the Database Util so it would not be a trivial change I guess.

What about when you use the Change Remote feature on the Repo?

The Change repo remote is not coming with the values for Display Name, Folder logic and Ignore Subpackages fields.
When the Display Name is updated via this feature is also not refreshed on the main page..

**Comment by larshp** [comment]
it should be possible to change the display name via repo settings, if not we should add this feature

**Comment by Sdfraga** [comment]
Just for clarification, in the Advanced options for a repo we have:

- Change remote - Display Name is changed in DB and **is not updated** in the Favorites toolbar
- Repo Settings - Display Name is changed in DB and **is updated** in the Favorites toolbar

**Comment by sbcgua** [comment]
@Sdfraga could you pls check the latest version ?

**Comment by Sdfraga** [comment]
Consistent now!
Thanks  @sbcgua
