### ISSUE TITLE
SHI3, User menu serialization

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#261]

**Comment by sbcgua** [comment]
@larshp small question: serialization strips "change" markers (user, date, time) - it's clear why. Should it also strip "creation" data ? I checked some basic objects (dtel, tabl) but there are views without creation markes at all (???). So what is the approach for creation markers ?

**Comment by larshp** [comment]
I think all usernames and timestamps should be stripped in the serialized data.

Git will keep track of who created the object and when.

Usernames might also disclose which system/SAP customer the code is originally created on, which might raise concerns about doing open source ABAP.

**Comment by larshp** [comment]
added in PR #262
