### ISSUE TITLE
UI Dark Theme

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2610]
Kind'a trendy ?

P.S. A lot of work honestly. This means:
- refactoring CSS (in terms of color usage unification)
- splitting CSS into layout and color parts
- and finally finding good colors for dark mode.

P.P.S. following #2490

**Comment by flaiker** [comment]
I think it would already be an improvement if the background color of abapGit (the gray) adjusts to the GUI theme. For example with the new Belize theme the gray kind of looks out of place in my opinion.

**Comment by sbcgua** [comment]
good idea. should be quite easy after the bullet are done.

**Comment by flaiker** [comment]
![image](https://user-images.githubusercontent.com/5270359/57877628-91ab9480-7818-11e9-9761-4f28b055221a.png)
Just hardcoded some different colors in after upgrading to GUI 7.60 again. Looks quite good in my opinion.
No idea how to find out which theme the frontend uses though. I guess you'd have to read some registry keys or just add a user setting.

**Comment by sbcgua** [comment]
nice colors, really cool.
imho no need for automatic theme selection, it should be a user preference from my understanding.

P.S. not sure when I'll be able to dig into themes myself, a bit underwater with work these days :(

**Comment by flaiker** [comment]
Yes, it's the custom "72" font SAP added with 7.60. I can post the CSS changes I made later.

As far as I know CSS does not natively support variables, right? So no idea how to implement theming in a good way. Years ago I used sass / less to compile CSS with variables but I would not feel confident in adding such a build step to abapGit. (Also I assume the web development world has moved away from these _ancient_ technologies by now ;) )

**Comment by flaiker** [comment]
Just the search and replace I did for reference:
<details><summary>Diff</summary>
<p>

```diff
@@ -5,9 +5,9 @@
 /* GLOBALS */
 
 body {
-  font-family: Arial,Helvetica,sans-serif;
+  font-family: "72",Arial,Helvetica,sans-serif;
   font-size:   12pt;
-  background:  #E8E8E8;
+  background:  #eff4f9;
   overflow-x:  hidden;
 }
 
@@ -101,7 +101,7 @@ div#header span.page_title {
 
 div#toc {
   padding:          0.5em 1em;
-  background-color: #f2f2f2;
+  background-color: #fcfdfe;
 }
 div#toc .favorites a { opacity: 0.5; }
 div#toc .favorites:hover a { opacity: 1; }
@@ -126,7 +126,7 @@ div#footer span.version {
 }
 
 div.dummydiv {
-  background-color: #f2f2f2;
+  background-color: #fcfdfe;
   padding:          0.5em 1em;
   text-align:       center;
 }
@@ -146,7 +146,7 @@ div.log .icon { padding-right: 6px; }
 /* REPOSITORY */
 div.repo {
   margin-top:       3px;
-  background-color: #f2f2f2;
+  background-color: #fcfdfe;
   padding: 0.5em 1em 0.5em 1em;
   position: relative;
 }
@@ -441,7 +441,7 @@ div.settings_container {
   padding: 0.5em;
   font-size: 10pt;
   color: #444;
-  background-color: #f2f2f2;
+  background-color: #fcfdfe;
 }
 
 div.settings_section {
@@ -450,7 +450,7 @@ div.settings_section {
 
 /* DIFF */
 div.diff {
-  background-color: #f2f2f2;
+  background-color: #fcfdfe;
   padding: 0.7em
 }
 div.diff_head {
@@ -673,7 +673,7 @@ table.db_tab tbody tr:hover, tr:active {
 
 /* DB ENTRY DISPLAY */
 div.db_entry {
-  background-color: #f2f2f2;
+  background-color: #fcfdfe;
   padding: 0.5em;
 }
 
@@ -721,7 +721,7 @@ table.tag td.label { background-color: #b3c1cc; }
 
 div.tutorial {
   margin-top:       3px;
-  background-color: #f2f2f2;
+  background-color: #fcfdfe;
   padding: 0.5em 1em 0.5em 1em;
 }
 
@@ -1073,7 +1073,7 @@ table.commit tr .title {
 
 /* code inspector */
 .ci-head {
-  background-color: #f2f2f2;
+  background-color: #fcfdfe;
   padding: 0.5em 1em;
 }
 .ci-head .package-name span {

```
</p>

**Comment by sbcgua** [comment]
![image](https://user-images.githubusercontent.com/15635498/58049999-714c4480-7b4e-11e9-99f5-e1f13bf7f2f0.png)

The solution is to split colors and layouts into separate CSS files (probably, this is what you meant in "Edit"). The CSS classes add up. So if I have same class in 2 css files - the attributes will merge.

I have idea how to implement it just don't have time now :) Technically `ZCL_ABAPGIT_GUI_PAGE->HTML_HEAD` should go to settings (or created with dedicated param) and find theme and add it as a `<link rel="stylesheet" type="text/css" href="css/theme_dark_or_whatever.css">`. The theme CSS files should be respectively added to `ZCL_ABAPGIT_UI_FACTORY->INIT_ASSET_MANAGER`. So should not be very difficult except diligent hardworking through existing CSS to strip the colors out :)

P.S. CSS variable and in-abap-css processor. Also had this idea ... but seem rather difficult and with few perspectives to reuse in future. Also the above CSS merge approach should totally work. I was actually thinking about pre-processor not for the variable but for nesting - there are quite many related styles now but they are in different places and hard to mind at once.

**Comment by sbcgua** [comment]
@flaiker have a look at #2700 
splitted the css, added the settings (with dummy dark and belize modes). So potentially your colors can be integrated (theme-belize.css).

**Comment by flaiker** [comment]
Looks good! Cannot test it until sunday unfortunately. For Belize one might need even more files, one for each color variant (Blue, Gold, Green, Purple, Red).

**Comment by sbcgua** [comment]
Blue, Gold, Green, Purple, Red ... hmmm, probably we also need some mechanism for external themes not to include too much in standard :) imho.

**Comment by flaiker** [comment]
A more flexible approach might be to just do a search and replace for CSS variables in the asset manager based on values in the user settings and to just provide different defaults there? Then you could also simply have a default "custom" where the user can enter everything himself.
Something like this: https://github.com/larshp/abapGit/compare/master...flaiker:themes

(I assume that also works with the compiled report but not sure)

Also apparently there are [polyfills](https://github.com/jhildenbiddle/css-vars-ponyfill) available for CSS variables (IE9+), if one wanted to go that route.

**Comment by flaiker** [comment]
I guess the downside of the variables approach is that you rely on having variables at the right places in the main css file while with theme specific css you can adjust everything.

**Comment by larshp** [comment]
first draft merged in https://github.com/larshp/abapGit/pull/2787

**Comment by larshp** [comment]
this was merged, can the issue be closed?

**Comment by larshp** [comment]
close, we can open another issue as "Polishing Dark Theme"
