### ISSUE TITLE
Running abapGit in production/QA environments

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2611]
currently its not possible to run abapGit in production, but it would be nice to be able to export files from production systems

**Comment by larshp** [comment]
T000 settings are checked, if changes to repository objects are not allowed, only allow pushing no pulling

**Comment by Srinu3366** [comment]
@larshp  I will give it a try.

**Comment by Srinu3366** [comment]
To start with I am thinking of removing Online and Offline repo creation options in the main screen if client is not a development client. 
Add text to the Tutorial to mention about only export option in case of non development clients. Remove Pull, Stage, Create branch and delete branch options in repo screen. This kind of locks down the options to trying to change anything. 
Any other ideas?

**Comment by larshp** [comment]
basically the `write_protected` feature should be forced on systems where its not allowed to update workbench objects

**Comment by larshp** [comment]
merged, closing
