### ISSUE TITLE
Diff filter does not work

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2613]
I noticed this some time ago, then forgot to report it and then I wanted to check if the new version didn't fix it somehow.

The filter doesn't respond to clicks at all (diff, patch page):
![image](https://user-images.githubusercontent.com/5097067/55311520-74d32180-5463-11e9-9271-fe47322e4e29.png)

Reproducible in 1.86 and 1.86.2. Very likely to be broken in 1.86.1 as well, I just haven't tried that version at all.

Possibly related: 
![image](https://user-images.githubusercontent.com/5097067/55318521-43fae880-5473-11e9-8842-567cc4657601.png)

I'm not able to track down the source of the error. Could be some weird character issue again, although I get it even on an fresh repository (on every page, even repo settings). 

I managed to find this line, which is missing quotes around the id:
https://github.com/larshp/abapGit/blob/604c68200ed6a038229756f179fb86b9ccc9cc39/src/ui/zcl_abapgit_gui_page_diff.clas.abap#L681

I can submit a PR for the quote fix, maybe it doesn't change anything, but it is incorrect.
I get the error even with the fixed quotes though.

**Comment by FreHu** [comment]
This is why it breaks:
https://github.com/larshp/abapGit/blob/3217ef234832feba2d34491ae456a34fc146b1ae/src/ui/zabapgit_js_common.w3mi.data.js#L496

Adding the class `octicon` here fixes it:
https://github.com/larshp/abapGit/blob/3217ef234832feba2d34491ae456a34fc146b1ae/src/ui/core/zcl_abapgit_html.clas.abap#L318

This is a completely naive fix, can someone familiar with how icons work review?
@sbcgua @larshp

**Comment by sbcgua** [comment]
good find. I can't remember why the octicon is checked there though it seem to be my code. Probably some extra assert that it is the item list. The quick fix would be to change to `contains("icon")`

Do you prefer to PR or I can do it ?
