### ISSUE TITLE
Ignore XTI includes in function groups

### ISSUE THREAD

**Issue by mfsap** [larshp/abapGit#2620]
When the includes for function groups are resolved for serialization, includes with extension XTI (simple transformations) are added if they are used in the function group. The corresponding .abap file is empty and during de-serialization, the RS_CORR_INSERT fails.
I would recommend to ignore XTI includes since transformations are always individual transport objects.
I will prepare a PR for this (in addition to commit https://github.com/larshp/abapGit/commit/6cc5e63dfd6787b5d464f5ca5fa1bb686afb523b).

**Comment by mfsap** [comment]
Further informations:
The includes are determined via RS_GET_ALL_INCLUDES. This performs a read on table D010INC. If you check for entries with MASTER = 'SAPL*' and INCLUDE = '*XTI' you'll find function groups with these kind of includes.

**Comment by larshp** [comment]
guess this can be closed
