### ISSUE TITLE
Code Inspector, Cannot install abapGit because of lo_type

### ISSUE THREAD

**Issue by bmd-benita** [larshp/abapGit#2624]
Hi,

I got error when activating abapGit script in SAP GUI 7.40 from this link: https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap. 

Here is the error message:
`The result type of the functional method cannot be converted into the type of LO_TEST.`

I also attached the screenshot when error occured.

![VirtualBox_win10-64_08_04_2019_16_16_54](https://user-images.githubusercontent.com/17718038/55713417-d292db00-5a1a-11e9-8aa0-ab3ff2cb6893.png)

Thanks in advance.

**Comment by christianguenter2** [comment]
What's your netweaver version? As a quick fix just comment out the line.

**Comment by christianguenter2** [comment]
@bmd-benita any news?

**Comment by bmd-benita** [comment]
Hi @christianguenter2,

sorry for late reply. I don't know exactly what the netweaver version. But, this is sap ides version and I want to try abapgit on sap ides. Can abapgit be integrated to sap ides?

Thanks.

**Comment by christianguenter2** [comment]
@bmd-benita 
It's quite easy to figure out the netweaver version.

![image](https://user-images.githubusercontent.com/17437789/56114458-293f6e00-5f61-11e9-8411-efe3fbf73b1d.png)

![image](https://user-images.githubusercontent.com/17437789/56114477-352b3000-5f61-11e9-9607-00b2028763a0.png)

![image](https://user-images.githubusercontent.com/17437789/56114457-26dd1400-5f61-11e9-9a2d-f132fb61c63c.png)

Anyway, did you try the above mentioned fixes?

**Comment by bmd-benita** [comment]
Hi @christianguenter2, it's release 731 with SP-Level 0002.

**Comment by christianguenter2** [comment]
Ok, this release is supported, but only a few people are using it. So you need to help us to fix the issue.

Can you change line33513 to this an try to activate
`lo_test ?= cl_ci_tests=>get_test_ref( <ls_result>-test ).`

If that fails comment the line and check whether further syntax erros occur.

**Comment by bmd-benita** [comment]
Thanks for your fast reply. I have tried it and it displays another error message.

![VirtualBox_win10-64_18_04_2019_14_39_18](https://user-images.githubusercontent.com/17718038/56344488-c4497980-61e7-11e9-8b47-718608128e6c.png)

**Comment by christianguenter2** [comment]
Ok, thanks. I'll fix it and let you know.

**Comment by christianguenter2** [comment]
@bmd-benita error is fixed. Can you try the latest build?

**Comment by bmd-benita** [comment]
I have tried it and it displays another error message.

<img width="1680" alt="Screen Shot 2019-04-22 at 08 52 02" src="https://user-images.githubusercontent.com/17718038/56478803-fe629600-64db-11e9-8666-bd2755269866.png">

**Comment by larshp** [comment]
@bmd-benita the code is continuously being updated, so it helps if you paste the code which the error is reported for

**Comment by christianguenter2** [comment]
@bmd-benita fixed. Can you try the latest build?

**Comment by bmd-benita** [comment]
I have tried it. It displays another error message.

<img width="1675" alt="Screen Shot 2019-04-23 at 11 31 05" src="https://user-images.githubusercontent.com/17718038/56554293-6805a180-65bb-11e9-9e81-d9be1a915718.png">

**Comment by larshp** [comment]
method ZCL_ABAPGIT_CONVERT=>XSTRING_TO_STRING_UTF8 can be used instead

**Comment by christianguenter2** [comment]
@bmd-benita fixed. Can you try the latest build?

**Comment by bmd-benita** [comment]
@christianguenter2 it works now. Thanks.

But, there is an error message when creating an offline repo. I have created a new issue for this problem (https://github.com/larshp/abapGit/issues/2649). Thank you.
