### ISSUE TITLE
Allow for private repositories (only visible to the user who created them)

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#2625]
Since I installed abapGit in my system some years ago I was the only one using it. So just now I looked at a repository I didn't recognize and removed it, thinking it was something old I no longer remembered. Only then I saw there were others clearly not created by me. That's when I realised abapGit is now being used by others too.

There should be user-specific repositories. A long time ago I posted issue #401 voicing this concern. At the time the solution was introducing favourites which is an amazing feature and really solved the problem back then.

Now, considering that abapGit is slowly becoming a central piece of any system which is used by many people, I think the current behavior should be questioned again. Because, the way it is built today any, anyone can mess with someone else's repositories, even if by accident.

I would like abapGit to allow for user/central repositories (much like an ATC variant does).

My proposal:
- When creating a repository I should be able to decide if it will be visible only to me (user) or to everyone (central);
- When listing the repositories I should be able to choose to list only mine, only central ones or both.

**Comment by larshp** [comment]
ABAP is a multi developer system, all code can be changed by all developers at all times(if edit lock is not used, and it should never be used)

Users can add and remove favorites via the star icon, just like adding favorite packages in ADT

Clicking the burger icon -> repository overview -> toggle detail, will show the user that created or last pulled the repo

**Comment by nununo** [comment]
Yes, I see what you mean and agree with you. I guess I just have to get used to it and be careful from now on.

Yet, I was wondering: what if, for some reason, there is the need to link the same package to two different repositories at the same time? Maybe this is far fetched.

Your arguments convinced me that my request isn't aligned with how the tool is supposed to be used. So I'll close this issue. Thanks Lars!

**Comment by larshp** [comment]
two different repositories at the same time: it will become very difficult for the developers, who pulls when, hence the current limitation that it can only be connected to one

real multi user would mean one system per developer
