### ISSUE TITLE
SAP Cloud Platform Git Repository

### ISSUE THREAD

**Issue by Sdfraga** [larshp/abapGit#2627]
Hi, 

For UI5 projects it's possible to integrate the WebIDE to a repository in the SAP Cloud Platform like this:

![image](https://user-images.githubusercontent.com/16186872/55886081-61cef880-5bab-11e9-8b20-d28dba9aa592.png)

I was wondering If someone already used this Git Server in the SCP to manage ABAP code via abapGit?

**Comment by larshp** [comment]
I tested it some years ago, it worked back then, but not currently using it

**Comment by bigld** [comment]
Hi @Sdfraga 

We use SCP Git Service for backups (background mode) without any problems!
For several reasons for development we use github.

**Comment by Sdfraga** [comment]
Thanks for the feedback @bigld and @larshp .

I am currently using Azure to manage my developments. Like github, the management of issues on those tools are quite good and SCP Git Service seems weeker for that purpose for example.

So for your development workflow process you use github and then you use SCP just to create backups of your repos is it? 
Can you explain me what is your main purpose with that setup?

Maybe it could be interesting to create a page in the documentation with _Scenarios_ where we could share how do we use the abapGit for the development process..?

What do you think?

**Comment by larshp** [comment]
see https://blogs.sap.com/2017/05/07/abap-using-git-for-safety-and-transparency/

**Comment by larshp** [comment]
also have https://github.com/larshp/abapGit/issues/2087 open

**Comment by Sdfraga** [comment]
Thank you @larshp 
In fact #2087 already takes care of the "Scenario" suggestion. Nice.
Regarding SCP Git Service, I will give it a run and check if I could use it.
