### ISSUE TITLE
Keyboard shortcuts do not work in on-file-version abapgit_full

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2629]
The reason seems to be that keyboard shortcuts are collected from all classes implementing the interface `zif_abapgit_gui_page_hotkey`. Global classes. This is also then needed for settings to redefine shortcuts on system basis. However in abapgit_full there are no global classes.

P.S. I'd suggest implementing shortcuts so that a page register own shortcuts on rendering (also do the same with on_event handlers, was discussed somewhere here ...). As for shortcuts redefinition - keep the existing approach but disable shortcut change in one-file version probably.

**Comment by christianguenter2** [comment]
@sbcgua should work now, can you try?

**Comment by sbcgua** [comment]
Yeap, I will on the weekend. Thanks!

**Comment by sbcgua** [comment]
Works perfectly, thanks ! closing
