### ISSUE TITLE
background mode, one branch per transport

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#263]
would perhaps make it possible to do automatic checks that transports can be imported individually?

**Comment by larshp** [comment]
#266 must be solved first

**Comment by EduardoCopat** [comment]
My thoughts on how could one develop this:

- A new sub-menu "Transport to Branch" in the repository's "Advanced" menu.
- Using a logic similar on lcl_transport, get the objects in the request.
- Create a new branch with the transport request code (SYS000002)
- Commit the objects using the transport request code (SYS000002) [Who should commit?]
- Push against new branch

Any ideas?

**Comment by larshp** [comment]
I use the background mode with a few work projects, where it runs in background every hour and pushes the changed objects to abapGitServer. It has the advantage that it does not change the developer workflow.

Similarily I have imagined this as also running in the background, just automatcially creating branches from transports, eg. every hour.

If you are heading towards reviewing ABAP code via eg. github, this could also work automatically? The committer is built from the username that last changed the object, but in this case it could be combined with the owner of the transport/task

**Comment by EduardoCopat** [comment]
Yeah, I believe this is the overall idea. 

A button with "Transport to Pull Request", which has also an underlying API.

Then, to automate it, my idea would be to implement the [CTS_BADI_REQUEST](https://www.sapdatasheet.org/abap/cus0/cts_request_check.html)~CHECK_BEFORE_RELEASE. 

When a task is released, the "Transport to Pull request" is triggered in abapGit. Of course, this BADI implementation is another project.

**Comment by EduardoCopat** [comment]
Work in progress: https://github.com/EduardoCopat/abapGit/tree/transport_to_pull_request

Core logic here: https://github.com/EduardoCopat/abapGit/blob/transport_to_pull_request/src/zabapgit_services_repo.prog.abap#L335

Still figuring out how to Stage new/removed files.

**Comment by larshp** [comment]
take a look at the code for background mode: https://github.com/larshp/abapGit/blob/master/src/zabapgit_background.prog.abap#L52

**Comment by EduardoCopat** [comment]
@larshp Thanks, that helped.

I'm first creating it as a button (interactive), later I would add the background functionalities.

I created a routine that get the transport objects, create a branch and push. Now, I'd need to create a Pull request. I start dwelling into the `lcl_git_transport=>receive_pack`, but that's really arcane knowledge. Do you know if it should be possible to create a **Pull Request** using this **Pack protocol**?

**Comment by larshp** [comment]
I think https://developer.github.com/v3/pulls/#create-a-pull-request has to be used for creating pull requests(the 2fa code already does some API calls to github). Pull requests are not part of the git protocol(AFAIK).

Perhaps make a new class that handles the calls to GitHub API

**Comment by EduardoCopat** [comment]
Another simple option would be to rename the functionality to "Transport to new branch". Then, later add this option to create a Pull request from a branch

**Comment by tiefox** [comment]
I'm planning on implementing the same functionality but for TFS, and yep, will need to call TFS api for that, so it would be good idea to have some hooks in abapgit to enable the pull request integration with the different repositories providers.

**Comment by larshp** [comment]
once you have the "transport to new branch" part working just submit a PR for that, then we can add the other stuff in a follow up PR

**Comment by larshp** [comment]
moving to https://github.com/abapGit/background_modes
