### ISSUE TITLE
GUI: make syntax page "no errors" more neat

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2636]
Looks a bit strange,

![image](https://user-images.githubusercontent.com/5888506/56265185-2bcccf80-60e9-11e9-8906-6b030af68b77.png)

**Comment by Srinu3366** [comment]
This looks like a change which can be fixed by a novice like me. Can I work on it?

**Comment by larshp** [comment]
yea, sure 👍 guess few html/css fixes are needed, I have not looked at the details

**Comment by sbcgua** [comment]
:+1: 
Please try to reuse existing css styles when possible. 
Have a look at code inspector page. As far as i remember it renders green “no errors” panel on success, which should be very similar.

**Comment by Srinu3366** [comment]
![image](https://user-images.githubusercontent.com/25985494/56480163-74381480-647e-11e9-97e4-4de5dca524a4.png)

This is how the current screen looks in my abapgit. Is something changed?

**Comment by Srinu3366** [comment]
![image](https://user-images.githubusercontent.com/25985494/56481312-0f7fb880-6484-11e9-9134-3efbb20c8e28.png)

I made a few changes by replicating the result of code inspector check to show a similar message if no syntax errors. I will create pull request if this looks fine.

**Comment by larshp** [comment]
looks good to me, much better than before

**Comment by larshp** [comment]
fixed by @Srinu3366, closing
