### ISSUE TITLE
Pull logic is unsafe (UX)

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#264]
Hi @larshp , there is one issue with which looks quite critical for me: If you have local changes and repo changes and press pull then local changes are overwritten (!) and without any notification (!!!!!).

I'm not saying about stashing but at least a warning would look minimally safe.

Thoughts:
As I understand this happens because actually there is no possibility to identify local changes. My first idea was to create kind of dynamic workdir class which would virtually serialize objects and calculate their hashes (maybe store it somewhere for performance reason or maybe not). So they can be checked versus git repo hashes. 

The object would also be useful for staging (it will take take over the workarea logic there). 
And also it will be very useful for branching (#265) - to make possible skipping unchanged object installation/activation.

However I cannot cope with that myself - current logic seems to be used too deep into internals and I don't know that part of code yet and also git protocol. So at least some assistance needed from your side :)

**Comment by larshp** [comment]
this should have been solved as part of https://github.com/larshp/abapGit/issues/173

can you add the steps to reproduce the issue? And make sure that the repository have been installed with the latest version.

In the current solution checksums for all objects are saved as part of the XML in the database. If the object is changed in the meanwhile it should show a warning.

![image](https://cloud.githubusercontent.com/assets/5888506/16116547/e82a36f0-33cd-11e6-8aee-17fb5a78987b.png)

**Comment by larshp** [comment]
Did a small test, seems to work for me:
![image](https://cloud.githubusercontent.com/assets/5888506/16116936/cdefe440-33cf-11e6-8718-84f2aa607f85.png)

**Comment by sbcgua** [comment]
Hmm, indeed, sorry. I was sure I saw this bug a couple of days ago. But maybe that was indeed a repo which was last pulled more than a month ago.

Still the UX is still confusing. Test case:

1. Even code
2. Adding a line to local prog + refresh = good, Stage bunnot appear
3. Repo is updated elsewhere
4. Refresh => **No stage button, just pull**
5. if I press Pull and decline the overwrite msg, then **Pull disappears, just Stage remains**

So
- the state of workdir (point 4) is not visible (some kind of dirty flag)
- point 5 - I cannot restart pull.
- Now if I stage - then repo is updated with local code, overwriting the repo (although the history is there in this case)

**Comment by larshp** [comment]
so,
4. does the "diff" link appear?

5. Earlier today I was thinking of adding a "Advanced" dropdown under the online repos, with options for "changing branch"(#265) and "force pull" which can always be used to overwrite the local objects

**Comment by sbcgua** [comment]
4) Yes, showed diff between local and **updated** repo
5) "Force pull", imho "Reset" would be better (and then pull on top of clean workdir) + making that warning about object replacement an error (so that it is not possible to pull partially).

**Comment by larshp** [comment]
5: yes, it would just pull with the normal logic(including warning checks). This will also add the possibility to reset local changes, in case the user would like to roll back the local changes. Looks like "reset" is correct terminology in the git world

**Comment by larshp** [comment]
advanced dropdown looks like this:

![image](https://cloud.githubusercontent.com/assets/5888506/16329195/2824bc44-39e1-11e6-812e-0811f2491bc5.png)
