### ISSUE TITLE
SSFO: Leading spaces are doubled after pull

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2640]
It seems that some leading space in Smartforms (SSFO) are doubled during deserialization.

Test repo
https://github.com/abapGit-tests/SSFO.git 

![image](https://user-images.githubusercontent.com/17437789/56442544-82a4f580-62f1-11e9-94f8-c7db69518d68.png)

**Comment by larshp** [comment]
side effect of https://github.com/larshp/abapGit/pull/2597, we should remove the SSFO specific workaround

**Comment by larshp** [comment]
and we need to take care of backwards compatibility

**Comment by larshp** [comment]
merged, closing
