### ISSUE TITLE
Error when create offline repo

### ISSUE THREAD

**Issue by bmd-benita** [larshp/abapGit#2649]
Hi, 

I cannot create offline repo from my abap package. Screenshots attached.

Thanks in advance. 

<img width="740" alt="Screen Shot 2019-04-23 at 17 28 14" src="https://user-images.githubusercontent.com/17718038/56574719-23dfc480-65ee-11e9-9963-abe5f937b7dd.png">
<img width="740" alt="Screen Shot 2019-04-23 at 17 29 27" src="https://user-images.githubusercontent.com/17718038/56574718-23dfc480-65ee-11e9-938c-4a395fcc5907.png">
<img width="740" alt="Screen Shot 2019-04-23 at 17 30 08" src="https://user-images.githubusercontent.com/17718038/56574717-23472e00-65ee-11e9-8a5f-98c6dd732620.png">

**Comment by larshp** [comment]
@bmd-benita thanks for the bug report

Sorry about the syntax errors and dumps, but only few of us have access to 73x systems

**Comment by larshp** [comment]
@bmd-benita try again, latest version, build will be automatically updated in a few minutes

**Comment by larshp** [comment]
closing, no reply, please reopen or create new issue if there are additional problems
