### ISSUE TITLE
Branch changing

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#265]
Branch switching feature (I guess the purpose should be obvious :)

**Thoughts**
Flow: reference to branch becomes a link. 

![branchlink](https://cloud.githubusercontent.com/assets/15635498/16116100/b9394ec0-33d3-11e6-849c-2385d54f4987.PNG)

Pressing on that calls `branch_popup` which also have "new" option (can be a separate feature in fact). User chooses a branch, the program checks local changes vs current branch and shows warning if changes unsaved (blocked by #264), if ok switches to another branch. Only unequal objects are replaced (also blocked by #264). DB is updated. 
In case of activation fails the process does not stop but retrieves all objects and shows list of activation issus.

**Comment by larshp** [comment]
yep, also see https://github.com/larshp/abapGit/issues/127

Overwriting should be handled separately from this issue.

I think this can be solved by updating the mv_branch field to the sha1 of the new branch. Update the persisted branch name, and then call lcl_repo_online->deserialize.

**Comment by larshp** [comment]
it should also be possible to change the url/repository along with the branch
