### ISSUE TITLE
Refactoring: Unify string utils

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2651]
following discussion in #2648

suggest to unify `ZCL_ABAPGIT_STRING_UTILS` and `ZCL_ABAPGIT_CONVERT`. Both contain helper methods, some of which related to string processing. Also there is a 'text/bin detection' routine in diff page which I would extract to util class.

Need an opinion on what to move where ? :)))

- convert class has some methods which are not string related so my first intention is to move some of methods to string utils and leave convert class with bin utils only. But ...
- why 2 classes ? And if yes why so different names ? (why not string utils and e.g. bin_utils). Unifying both into one definitely makes sense but with  a proper name imho.
- also: just perceptionally I'd say that `convert` is not a very intuitive name, I wouldn't look for utils in this class (and I didn't :)) But this is pure imho.

I'd just move some methods to string utils for now unless there is a better concept at the moment.

**Comment by larshp** [comment]
if we do not get rid of one of the classes we will have the same problem sometime again

**Comment by sbcgua** [comment]
Agree ... what if move all to convert and rename it to convert_utils ?

**Comment by larshp** [comment]
sounds good to me, none of the naming string_utils/convert/convert_utils are perfect

**Comment by sbcgua** [comment]
naming: yeah ... maybe just utils ? or conv_utils ? or data_utils ?

**Comment by larshp** [comment]
no opinion 🤷‍♂

**Comment by sbcgua** [comment]
probably let's leave as it is for now. I'll just move binary/text detection method there in a separate PR later
