### ISSUE TITLE
Duplicate key error in ZCL_ABAPGIT_OBJECTS_GENERIC->deserialize_data when importing IWPR object

### ISSUE THREAD

**Issue by oliver-goetz** [larshp/abapGit#2652]
abapGit dumps when importing an IWPR object because of a DBSQL_DUPLICATE_KEY_ERROR for DB tables **/IWBEP/I_SBD_SE** and **/IWBEP/I_SBD_SET** in **ZCL_ABAPGIT_OBJECTS_GENERIC->deserialize_data** 

**ZCL_ABAPGIT_OBJECTS_GENERIC->constructor** does not check for duplicate _tobj_name_ entries  when filling internal table **mt_object_table**
```
* object tables
    SELECT * FROM objsl INTO CORRESPONDING FIELDS OF TABLE mt_object_table
      WHERE objectname = is_item-obj_type
      AND objecttype = lc_logical_transport_object
      AND tobject = 'TABU'.
    IF mt_object_table IS INITIAL.
      zcx_abapgit_exception=>raise( |Obviously corrupted object-type {
        is_item-obj_type }: No tables defined| ).
    ENDIF.
```

In my S/4 HANA 1709 installation there are 2 entries with the same **tobj_name** for the tables I mentioned. They have the same data except the TRWCOUNT.
This leads to an DB duplicate key error on INSERT state in the quoted LOOP of **ZCL_ABAPGIT_OBJECTS_GENERIC->deserialize_data** 

```
    LOOP AT mt_object_table ASSIGNING <ls_table>.

      CREATE DATA lr_ref TYPE STANDARD TABLE OF (<ls_table>-tobj_name).
      ASSIGN lr_ref->* TO <lt_data>.

      io_xml->read(
        EXPORTING
          iv_name = <ls_table>-tobj_name
        CHANGING
          cg_data = <lt_data> ).

      INSERT (<ls_table>-tobj_name) FROM TABLE <lt_data>.
      IF sy-subrc <> 0.
        zcx_abapgit_exception=>raise( |Error inserting data, {
          <ls_table>-tobj_name }| ).
      ENDIF.

    ENDLOOP.
```

Removing the duplicates from **mt_object_table** in debugger helps to run the import successfully, but I'm not too familiar with abapGit to know about side effects filtering it in one of the methods I mentioned.

Excerpt of DB table **objsl**
 ```
OBJECTNAME                     OBJECTTYPE TRWCOUNT TPGMID TOBJECT TOBJ_NAME                                TOBJKEY                                                                                              MASKNLEN MASKKLEN PRIM_TABLE

IWPR                           L          24       R3TR   TABU    /IWBEP/I_SBD_SE                          /&/*                                                                                                   15        2
IWPR                           L          25       R3TR   TABU    /IWBEP/I_SBD_SET                         /L/&/*                                                                                                 16        3
IWPR                           L          40       R3TR   TABU    /IWBEP/I_SBD_SE                          /&/*                                                                                                   15        2
IWPR                           L          41       R3TR   TABU    /IWBEP/I_SBD_SET                         /L/&/*                                                                                                 16        3
```

**Comment by larshp** [comment]
thanks for the detailed bug report, this sure looks like a bug, we'll have to find out what OBJSL-TRWCOUNT means, but my guess is its safe to only take the unique tables

and also guess the workaround is okay, the GENERIC serializer just copies table rows from one system to another

**Comment by oliver-goetz** [comment]
ok, thanks for the quick response 👍

**Comment by larshp** [comment]
potentially same problem in 751 dev edition, 
![image](https://user-images.githubusercontent.com/5888506/56602350-91472180-65fd-11e9-9c57-ac127f674f2e.png)

**Comment by larshp** [comment]
pull request https://github.com/larshp/abapGit/pull/2653 opened

**Comment by larshp** [comment]
@oliver-goetz changes merged, try latest version

note that XML files will have to be serialized again from source system, or after the manual fix

**Comment by oliver-goetz** [comment]
@larshp my OData service was successfully imported and the first local test in SAP Gateway Client was successful. 
Thanks for fixing this so fast 😄
