### ISSUE TITLE
possibility to create new branch

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#266]
after #265 implement the possibility to create new branch from abapGit.

Guess this will require some changes in 'METHOD receive_pack'.

This also raises the question if it should be possible to merge branches from abapGit.

guess this will also require some visualization of branches, eg like https://twitter.com/gitkraken or https://github.com/larshp/abapGit/network

Possibly a lot of work

**Comment by larshp** [comment]
The following might be relevant:
https://github.com/git/git/blob/master/Documentation/technical/pack-protocol.txt#L459

**Comment by larshp** [comment]
the code

```abap
    lv_line = lv_branch &&
              ` ` &&
              iv_commit &&
              ` ` &&
              io_repo->get_branch_name( ) &&
              get_null( ) &&
              ` ` &&
              'report-status agent=' && gv_agent &&
              gc_newline.                                   "#EC NOTEXT
```

corresponds to the update in the protocol documentation

**Comment by tiefox** [comment]
For Branch visualzation, http://gitgraphjs.com/ seems pretty cool!

**Comment by larshp** [comment]
already implemented, click Branch -> Overview

Example:
https://larshp.github.io/dkom2017/#/14
