### ISSUE TITLE
How to investigate a possible bug?

### ISSUE THREAD

**Issue by patvo** [larshp/abapGit#2661]
Hi there
I am trying to investigate a possible bug on an NW 7.31 (SP0007) machine. 
So step one: reproduce it. :P

First, what happened?
(Don’t know how related the following is, but I think I should at least mention it.
A while ago, I updated abapGit from 1.76.0 to 1.85.0 what ended in a syntax error. The error was clearly on our end, so I just manually fixed it. Posted an issue at this time: [https://github.com/larshp/abapGit/issues/2462](https://github.com/larshp/abapGit/issues/2462) )

Finally having abapGit version 1.85.0 workin, I needed to switch branches from developer to master.
In the process of switching branches, I got a dump. I started the process again and got another dump.

The consequences were errors at serialization and deserialization. Objects which clearly existed could not be found. In addition, objects that did not exist anymore where still in TADIR. 

Our repo was a big bunch of inconsistencies...

Being under some pressure do give the devs a fully working environment back, I decided to just get the latest backup from the night bevor and all was good again. 

For later investigation, I requested a complete clone of this machine. Now I have a snapshot of this clone and am able to dig deeper into what happened.
However, lacking the knowledge, I am seeking some advice, how to document my procedures while trying to reproduce this possible bug.

Any help is appreciated. =)
Greetings

**Comment by larshp** [comment]
First suggest documenting the dumps or finding them in ST22 will help

**Comment by patvo** [comment]
Will close this for now. Can't investigate right now.
