### ISSUE TITLE
Activation fails on ABAP 7.02

### ISSUE THREAD

**Issue by hectormartinezn** [larshp/abapGit#2665]
Hi,

When trying to activate the latest build of the abapGit report on ABAP 7.02 (SP 14) one gets the following error message:

~~~~
Unexpected word "EXPORTING" in functional method call
~~~~

This does not occur with later versions (I tested with ABAP 7.4).  The error is triggered by the following call in the method `popup_package_overwrite` of the class `ZCL_ABAPGIT_SERVICES_REPO`:

~~~
    zcl_abapgit_ui_factory=>get_popups( )->popup_to_select_from_list(
      EXPORTING
        it_list               = ct_overwrite
        iv_header_text        = |The following objects have been created in other packages.|
                             && | Select the objects which should be overwritten.|
        iv_select_column_text = |Overwrite?|
        it_columns_to_display = lt_colums_to_display
      IMPORTING
        et_list               = lt_selected ).

~~~

In ABAP 7.02 a functional method cannot have an EXPORTING parameter. Apparently at compiling time the ABAP compiler erroneously identifies the EXPORTING keyword as part of the `zcl_abapgit_ui_factory=>get_poups()` functional method call.

I solved the problem as follows:

~~~

DATA: lr_popups TYPE REF TO zcl_abapgit_popups.
    lr_popups ?= zcl_abapgit_ui_factory=>get_popups( ).
    lr_popups->popup_to_select_from_list(
    EXPORTING
        it_list               = ct_overwrite
        iv_header_text        = |The following objects have been created in other packages.|
                             && | Select the objects which should be overwritten.|
        iv_select_column_text = |Overwrite?|
        it_columns_to_display = lt_colums_to_display
      IMPORTING
        et_list               = lt_selected ).

~~~

After the correction, the problem is solved and the report is compiled successfully. I'm submitting a patch with the solution.

Best,

Hector

**Comment by larshp** [comment]
thanks, hope to implement https://github.com/larshp/abaplint/issues/221 sometime, so we can more easily discover errors like this

**Comment by hectormartinezn** [comment]
You're welcome. BTW amazing work with abapGit overall 👍 👍

**Comment by larshp** [comment]
fix is merged, guess this can be closed, closing
