### ISSUE TITLE
Login data and patch saved don't know where ...

### ISSUE THREAD

**Issue by ABILUKI** [larshp/abapGit#267]
While testing ZABAPGIT has saved my username and password so now I cant change it as well as repository patch. When I execute I get the following error: no branches, create branch manually by adding file. No login popum appears neither the initial screen. Thanks.

**Comment by ABILUKI** [comment]
Well, it does .
I execute ZABAPGIT  from se80

![image](https://cloud.githubusercontent.com/assets/19999823/16196994/8da7330a-3700-11e6-968d-6865756d006a.png)

and this is what I get immediately:

![image](https://cloud.githubusercontent.com/assets/19999823/16197038/bb1d2c36-3700-11e6-9302-d0f35a0b6178.png)

I have no chance to click the "Remove" link cause I can't see it.
The initial screen of ZABAPGIT is beeing ommited.

**Comment by ABILUKI** [comment]
It helped. THX.

**Comment by larshp** [comment]
cool :smile: 

I'll close the issue, feel free to create new issues if you find bugs, have suggestions or questions
