### ISSUE TITLE
Some error on ABAP 7.02

### ISSUE THREAD

**Issue by Aleksoid1978** [larshp/abapGit#2671]
1 - **CALL FUNCTION 'SEO_INTERFACE_CREATE_COMPLETE'** (line 38282) don't have **suppress_dialog** parameter and dump when run.

2 - **INSERT REPORT iv_program FROM it_source EXTENSION TYPE iv_extension STATE iv_version PROGRAM TYPE iv_program_type.** (line 38358) - dump with error **INSERT_REPORT_NO_EXTTYPE**
![1](https://user-images.githubusercontent.com/11625603/57750296-01d8ee00-7725-11e9-9073-fae042e7aaae.jpg)
![2](https://user-images.githubusercontent.com/11625603/57750297-02718480-7725-11e9-97f2-9b10238ed791.jpg)

**Comment by larshp** [comment]
1: as a workaround, try commenting the line

2: not sure what this means, is `iv_extension` empty? or?
https://help.sap.com/doc/abapdocu_740_index_htm/7.40/en-US/abapinsert_report.htm

**Comment by Aleksoid1978** [comment]
1 - that's exactly what I did.
2 - iv_extension = 'CS' as describe here:
**CONSTANTS: lc_class_source_extension TYPE sychar02 VALUE 'CS',** (line 38482).
May be it's value is not supported in 702.

**Comment by Aleksoid1978** [comment]
Trying install abap_data_parser(https://github.com/sbcgua/abap_data_parser)
break before dump:
![error](https://user-images.githubusercontent.com/11625603/57752254-da395400-772b-11e9-893b-c0c893d163f5.png)

dump:
![error2](https://user-images.githubusercontent.com/11625603/57752260-dd344480-772b-11e9-84c4-e98ceb6dc713.png)

As i see code Saplink - it's don't use 'CS' ext type and all woking.

**Comment by Aleksoid1978** [comment]
Here is type-pool SREXT from my system:
```TYPE-POOL srext .

******************************************************
*  Konstanten fuer zulaessige Extensions             *
******************************************************
CONSTANTS:
  srext_ext_class_pool(2)           TYPE c VALUE 'CP',
  srext_ext_class_public(2)         TYPE c VALUE 'CU',
  srext_ext_class_protected(2)      TYPE c VALUE 'CO',
  srext_ext_class_private(2)        TYPE c VALUE 'CI',
  srext_ext_class_local(2)          TYPE c VALUE 'CL',
  srext_ext_class_class(2)          TYPE c VALUE 'CC',
  srext_ext_class_method(2)         TYPE c VALUE 'CM',
  srext_ext_class_typeref(2)        TYPE c VALUE 'CT',
  srext_ext_class_remote_stubs(2)   TYPE c VALUE 'CR',
  srext_ext_class_temporary(2)      TYPE c VALUE 'CX',
  srext_ext_funclib_testenv(2)      TYPE c VALUE 'FT',
  srext_ext_interface_pool(2)       TYPE c VALUE 'IP',
  srext_ext_interface_public(2)     TYPE c VALUE 'IU',
  srext_ext_interface_rem_stubs(2)  TYPE c VALUE 'IR',
  srext_ext_interface_def_impl(2)   TYPE c VALUE 'IM',
  srext_ext_interface_typeref(2)    TYPE c VALUE 'IT',
  srext_ext_typepool_ref(2)         TYPE c VALUE 'TT',
  srext_ext_xslt_source(2)          TYPE c VALUE 'XT',
  srext_ext_transformation(2)       TYPE c VALUE 'TR',
  srext_ext_aab_activation_id(2)    TYPE c VALUE 'AB',
  srext_ext_default(2)              TYPE c VALUE '  ',

  srext_app_small_control           TYPE c VALUE 'S'.

******************************************************
*  Konstanten fuer State-Handling                    *
******************************************************

CONSTANTS:
  srext_active   TYPE c VALUE 'A',
  srext_inactive TYPE c VALUE 'I'.

******************************************************
*  Konstanten fuer Programmtypen                     *
******************************************************

CONSTANTS:
  SREXT_REPORT          type c value '1',
  SREXT_MODUL_POOL      type c value 'M',
  SREXT_INTERFACE_POOL  type c value 'J',
  SREXT_CLASS_POOL      type c value 'K',
  SREXT_TYPE_POOL       type c value 'T',
  SREXT_INCLUDE         type c value 'I',
  SREXT_SUBROUTINE_POOL type c value 'S',
  SREXT_FUNCTION_GROUP  type c value 'F'.```

**Comment by Aleksoid1978** [comment]
Any idea about type-pool SREXT and missing "CS" value ?

**Comment by larshp** [comment]
what is the exact SAP_BASIS version of your system?

**Comment by Aleksoid1978** [comment]
![SAP_BASIS](https://user-images.githubusercontent.com/11625603/58530340-bdb81400-8221-11e9-9bb9-ad8107cde0d2.png)

**Comment by Aleksoid1978** [comment]
There are any changes ?

**Comment by bigld** [comment]
I only have access to a 700/0013 or a 702/0014
Typepool SREXT is the same but with 702/0014 the EXTENSION TYPE CS for INSERT REPORT is known,
so I don't see any possibility to check for existing extension type at the moment...

cl_oo_classname_service=>get_cs_name() is available with 702/0014

@Aleksoid1978: is the method also available with 702/0010? 
Can you please check if this is working for you on 702/0010?
https://github.com/bigld/abapGit/tree/issue_2671

**Comment by Aleksoid1978** [comment]
cl_oo_classname_service=>get_cs_name() is available.
About https://github.com/bigld/abapGit/tree/issue_2671 - what i need check ? Working METHOD is_min_702_sp14_check ?? Or full work of abapGit ?

As i see in code - create_report will be run only if is_min_702_sp14_check. If no - create_report not run.

**Comment by Aleksoid1978** [comment]
Can you create zabapgit.abap from https://github.com/bigld/abapGit/tree/issue_2671 and upload for test ?

**Comment by sandraros** [comment]
For information, CS needs a kernel patch as explained in note [1505127 - Extension type CS does not exist](https://launchpad.support.sap.com/#/notes/1505127/E)

**Comment by Aleksoid1978** [comment]
Sorry for later answer - it's working, good job !

**Comment by larshp** [comment]
cool, can we close the issue?

**Comment by Aleksoid1978** [comment]
When wait for changes in the main branch/here ?

**Comment by larshp** [comment]
oh, sorry, thought it was merged

@bigld can you help opening a PR with the changes?

**Comment by Aleksoid1978** [comment]
Any progress :) ??

**Comment by Aleksoid1978** [comment]
Any progress ?

**Comment by larshp** [comment]
pull requests welcome

**Comment by Aleksoid1978** [comment]
It's not my code but @bigld.

**Comment by stubbini** [comment]
Hi guys

I'm also getting the issue in a 7.02 system. What is the latest status?

Thanks

**Comment by larshp** [comment]
waiting for someone to make a pull request with the fix

**Comment by sandraros** [comment]
I can take it. I will re-implement the solution of @bigld.
But I cannot test it on system < 7.02 SP14. I can just test that there's no regression on 7.52 SP00.
Okay?

**Comment by larshp** [comment]
@sandraros yes, thanks

**Comment by Aleksoid1978** [comment]
When the code is added to the main repository ?

**Comment by larshp** [comment]
see comments in https://github.com/larshp/abapGit/pull/2987

**Comment by larshp** [comment]
dont think this will be solved, kernel patch required, closing
