### ISSUE TITLE
Performance issue when patching large files

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2673]
Try adding all lines of a file with >500 lines. This can easily freeze the UI for over 10 seconds.

**Comment by FreHu** [comment]
I'm attaching some profiling results. You can import them in the IE debugger (don't use the one within sapgui, this failed for me).

It seems like all it's doing is toggling classes, which adds up:
![image](https://user-images.githubusercontent.com/5097067/57834255-2e8c1480-77bc-11e9-9539-5b45e1014b85.png)

I also feel that the performance gets worse with the size of the diff page, no matter the size of individual files.

[patch.zip](https://github.com/larshp/abapGit/files/3185821/patch.zip)

**Comment by christianguenter2** [comment]
Patch UI relies heavily on CSS classes and the rendering engine of SAPGUI browser control is quite slow.
I'm not sure whether there's an easy way to improve the performance without reengineering the UI. 

An idea is mentioned here, but I'm not sure whether the suggested techniques are supported by our archaic rendering engine.
https://ultimatecourses.com/blog/stop-toggling-classes-with-js-use-behaviour-driven-dom-manipulation-with-data-states

**Comment by FreHu** [comment]
Looks like it's toggling two things - the add link and the remove link - for each line. The second link isn't necessary, you can just toggle one and style it differently based on whether the line is included.

I guess checkboxes could also be used, though I'm dubious about both the performance and looks of hundreds of checkboxes. It's probably not what they were intended for :)

**Comment by christianguenter2** [comment]
Just submitted a PR replacing links with cheboxes. I seems like a good idea from both performance and UX perspective.
