### ISSUE TITLE
FUGR includes with author SAP are skipped

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2674]
We noticed that some very old includes are not serialized in one of our repositories. I debugged why and came upon this:

https://github.com/larshp/abapGit/blob/d1c5e332d4d6fdeb78c68994d734c9ec59a3385b/src/objects/zcl_abapgit_object_fugr.clas.abap#L519-L524

This is something we would like to serialize, it just happens that the author is listed as SAP for historical reasons.
What is the purpose of this logic?
Would it possible to utilize a different field such as `last changed by` to do this exclusion?

**Comment by larshp** [comment]
try creating a table maintenance function group, perhpas this comment is related:
https://github.com/larshp/abapGit/issues/15#issuecomment-134636714

**Comment by FreHu** [comment]
The generated includes seem to start with `LSVIM`. Could this be good enough criteria for excluding them?

![image](https://user-images.githubusercontent.com/5097067/57845278-f4c60880-77d1-11e9-962c-4d1524c7b85e.png)

Looking at last changed by would work for our purposes, but would not correctly exclude all of the table maintentance includes:
![image](https://user-images.githubusercontent.com/5097067/57845387-3656b380-77d2-11e9-80f3-9ca62e6b1824.png)

**Comment by larshp** [comment]
LSVIM, yea, lets try

**Comment by FreHu** [comment]
![image](https://user-images.githubusercontent.com/5097067/57849491-b897a580-77db-11e9-94b7-17118a980abd.png)

This is what remains from the generated group:
https://github.com/FreHu/abapgit-fugr-test/tree/master/src

There are no changes in the repo when I run abapgit without the fix.

**Comment by larshp** [comment]
cool, suggest adding a comment in the code so we can remember what LSVIM is
