### ISSUE TITLE
Opening a repository does not count as a navigation step

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2680]
Steps to reproduce:

- Open abapgit (without `show last repo` enabled)
- Go to a repository
- Open diff
- Press back

This exits abapgit instead of going back to the repository.

**Comment by g-back** [comment]
Looks like this has been fixed? Can't reproduce it with the provided steps.

**Comment by FreHu** [comment]
Neither can I. Yay for random fixes!
