### ISSUE TITLE
How to pull PR code into abap system for checks and tests before merge to master

### ISSUE THREAD

**Issue by NaveenKurmadas** [larshp/abapGit#2692]
Hi, 
I want to run ATC checks and Abap Unit tests in my netweaver system for the code changes that are part of  Pull request in my CI pipeline. In abapgit, I only see normal branches but do not see Pull request braches (refs/pull/*/head) to pull the code into my system. I saw the code and found that refs/pull branches are ignored from displaying in the branch list.

How to fetch PR code into my abap system for running these static code checks and unit tests before taking a decision to merge to master.

Regards,
Naveen

**Comment by larshp** [comment]
I guess this is something that should happen automatically?
So methods from https://docs.abapgit.org/development/api.html can be called for this to happen automatically(eg triggered via a REST call), however we might have to add a few features

can you link the code that filters out the pull request branches?

**Comment by larshp** [comment]
would like to expose the api as REST via https://github.com/abapGit/REST but have not had time so far

**Comment by NaveenKurmadas** [comment]
> I guess this is something that should happen automatically?
> So methods from https://docs.abapgit.org/development/api.html can be called for this to happen automatically(eg triggered via a REST call), however we might have to add a few features
> 
> can you link the code that filters out the pull request branches?

This is where it is getting ignored
![image](https://user-images.githubusercontent.com/35898274/58123762-315a8f80-7c2a-11e9-93c5-f7632df9b61e.png)

**Comment by filak-sap** [comment]
Well, you can always go to PR, copy the requestor's remote URL, change the  remote in abapgit and pull the PR branch.

**Comment by larshp** [comment]
yea, but I guess this should happen automatically @NaveenKurmadas ?

for http://abaplint.org it also uses the pull request branch, as this is the information which is available at least on github

**Comment by NaveenKurmadas** [comment]
> Well, you can always go to PR, copy the requestor's remote URL, change the remote in abapgit and pull the PR branch.
> 
> That's what normal people do when they want to pull PR branch into their workstations.

Pulling a PR branch is different to pulling the actual branch. PR branch will have merged code of new changes in your branch as well as of new changes of master branch which your branch might not be in sync with. So ideally all the CI pipelines are run on PR brach. and I'm looking at doing this using abapgit and automatically as part of pipeline task

**Comment by NaveenKurmadas** [comment]
> yea, but I guess this should happen automatically @NaveenKurmadas ?
> 
> for http://abaplint.org the code uses the pull request branch, as this is the information which is available, at least on github

This is easily possible using git command >>git fetch origin pull/ID/head:BRANCHNAME. I'm looking for similar functionality in abapgit. is it possible as of  today?

**Comment by larshp** [comment]
I dont think it is possible to list these today with current functionality, suggest adding another method that returns the non-filtered list.

**Comment by NaveenKurmadas** [comment]
> I dont think it is possible to list these today with current functionality, suggest adding another method that returns the non-filtered list.

for now, I have enhanced the same method for my internal use. When I get time, i will refactor into a seperate function and create a PR
Is there a way not to assign TR during pull using API? modifying decisions seems not to work and giving RR_CORR_INSERT error. I am debugging currently. is this a known issue?

**Comment by larshp** [comment]
TRs has to be assigned to transported objects, or inconsistencies between systems might occur

if the objects are not to be transported, install into a local package `$SOMETHING`, the PREFIX folder logic might be required for this to work

**Comment by larshp** [comment]
fixing, code examples will be part of https://github.com/abapGit/ci_tools

**Comment by larshp** [comment]
@NaveenKurmadas see https://github.com/larshp/abapGit/pull/3031
