### ISSUE TITLE
ITAB_DUPLICATE_KEY

### ISSUE THREAD

**Issue by valuepeople** [larshp/abapGit#2696]
I installed the latest ABAPGit in the ABAP System. I tried to install an openSAP zip archive. The objects were not installed. After that I deleted the local DEV-class and starting over. But now I have a dump. Can I reset ABAPGit or is there a different solution for this mistake?

**Comment by christianguenter2** [comment]
What's the dump? Why weren't the objects installed properly?

To cleanup you mean the openSAP repo? Just remove it from abapGit and delete everything left over in the package and start again.

If you still have issues it would be great if you can supply more information.

**Comment by valuepeople** [comment]
Hallo Christian,
thank you for your answer. I have everything deleted and start again. See
the attachment for more Information.
many regards
Karsten

Am Do., 23. Mai 2019 um 22:41 Uhr schrieb Christian Günter <
notifications@github.com>:

**Comment by larshp** [comment]
@valuepeople please attach in this issue, https://github.com/larshp/abapGit/issues/2696

**Comment by valuepeople** [comment]
Sorry Lars,
at the moment I have no access to my data. I'll attach the files later.
many regards

Am Di., 28. Mai 2019 um 12:42 Uhr schrieb Lars Hvam <
notifications@github.com>:

**Comment by valuepeople** [comment]
Here are further information about the dump.
[Dump.pdf](https://github.com/larshp/abapGit/files/3257216/Dump.pdf)

**Comment by christianguenter2** [comment]
Confirmed.

Also package names look somehow corrupted and incomplete.
![image](https://user-images.githubusercontent.com/17437789/58959044-822ec400-87a4-11e9-9390-4f9be7885810.png)

![image](https://user-images.githubusercontent.com/17437789/58959075-92df3a00-87a4-11e9-96d6-a62c891b2e72.png)

**Comment by christianguenter2** [comment]
Reason seem to be the starting folder. 
abapGit default is "/src/" but in the OpenSAP it's "/".

As a workaround goto Advanced > Repo settings and change the folder logic to /.
![image](https://user-images.githubusercontent.com/17437789/58959542-9de69a00-87a5-11e9-85cc-a2f3f23e4717.png)

Then the import should work.

**Comment by christianguenter2** [comment]
As a fix I think we should throw an exception if local starting folder doesn't match the remote. With a hint how to fix it.

**Comment by valuepeople** [comment]
Cool! It works. I'm impressed.
Thank you Christian for your help.

**Comment by larshp** [comment]
we need something like: if there is a pull, and the local package is empty then always inherit the remote .abapgit.xml settings, or something similar

**Comment by larshp** [comment]
https://github.com/larshp/abapGit/pull/2736 is merged, so I think this can be closed
