### ISSUE TITLE
Fail (pragmas)

### ISSUE THREAD

**Issue by ilostt** [larshp/abapGit#2697]
So i have copied the code and try to run it in my system, but then this shows up:

Fehlerhafter arithmetischer oder Bitausdruck: Statt "##NO_TEXT" wurde		
ein Operator (+, -, *, /, ... bzw. BIT-AND, BIT-XOR, BIT-OR) erwartet.	

I have read that Pragmas are used to help to compile the code, but really more i didn´t know. Can you please explain me how to deal with it?

**Comment by christianguenter2** [comment]
On which line does the error occur? Can you post a screenshot?

**Comment by ilostt** [comment]
So first picture is where this pragma fail comes. Than i decided to delete all pragmas and the fail on the 2nd screenshot happen.

![image](https://user-images.githubusercontent.com/50966747/58306832-260b8d80-7dfd-11e9-8cad-a70ded47d30c.png)


![image](https://user-images.githubusercontent.com/50966747/58306729-c6ad7d80-7dfc-11e9-9cf8-d1e1c927c04b.png)

**Comment by flaiker** [comment]
Can you tell us your NetWeaver release? Seems to me like secondary table keys and pragmas are not supported yet (below 7.02?).

**Comment by ilostt** [comment]
Oh, i have a 7.0 version. Is there any possibility to install it to my system without updating?

**Comment by larshp** [comment]
no, abapGit will not work on 700, see https://github.com/larshp/abapGit/issues/635

also see documentation, https://docs.abapgit.org "abapGit is a git client for ABAP developed in ABAP. It requires SAP BASIS version 702 or higher."

closing issue
