### ISSUE TITLE
submodules

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#27]
make sure git submodules work/implment support for submodules

**Comment by larshp** [comment]
will probably be some years until this is relevant

**Comment by sbcgua** [comment]
... a couple of years after ...
I guess this can be a good idea to implement.

Briefly to refresh the concept:
- Submodule is a **link** to another **independent** repo
- moreover, it is a link to specific commit (which may be a problem !)
- e.g. in normal git `git clone` does not fetch submodules, one has to run `git submodule init && git submodule update`
- so I imagine how would it work in AG
  - `clone` must add the main repo and additional repos for each submodule
  - so they actually live own lives, BUT 
  - on push of submodule ag must ask if `link to specific commit` must be updated in the main module
  - on pull of the main module ag must check if remote `link to specific commit` has changed and suggest (or even force) to update submodule repos

**Comment by larshp** [comment]
link to specific commit is a problem, as it will break if there are multipe repos linking the same repo. Anyhow, if we take out link to specific commit, the push feature can be taken out. And we end up with the feature I've tried describing in https://github.com/larshp/abapGit/issues/217 (ignore everything about package managers).

Basically,
* .abapgit.xml contains a list of required git repositories(not specific commit)
* on clone/pull the required git repos are installed
* everything else works as is

**Comment by sbcgua** [comment]
yes maybe you're right. In terms of package management submodules will not be very flexible. Links via .abapgit are at least not worse and probably better (e.g. to keep semantic version and not commit).

**Comment by larshp** [comment]
will close this for now
