### ISSUE TITLE
Error from RPY_TRANSACTION_INSERT

### ISSUE THREAD

**Issue by rajeshmajeti** [larshp/abapGit#2703]
![Issue](https://user-images.githubusercontent.com/36046824/58353643-08f6af00-7e3d-11e9-9eee-f0aaa0df4c1b.PNG)
Hi,

 While Installing ABAPGIT REPO , i am getting the issue RPY_TRANSACTION_INSERT. Can you please help me on how to overcome it?

**Comment by larshp** [comment]
do you have a developer key for this system, plus enough authorizations? Suggest checking SU53 for authorization issues, alternatively set a breakpoint in the code

**Comment by rajeshmajeti** [comment]
Thank you. It worked. Issue is due to the authorizations. I was not able to create ZABAPGIt Tcode and it was solved after working with our security team
