### ISSUE TITLE
G4BA is not supported

### ISSUE THREAD

**Issue by arcanist123** [larshp/abapGit#2704]
As of now the G4BA and G4BS object type is not being supported, as per my understanding. Or should I install some other package/plugin?

**Comment by larshp** [comment]
according to https://help.sap.com/doc/saphelp_nw751abap/7.51.0/de-DE/c6/dd838722ce4b8d9cc4a0741d93d864/frameset.htm this is OData v4 objects

you can try installing https://github.com/larshp/abapGit-Plugins, however this plugin will become obsolete sometime

recommend implementing native support, the generic serializer might work, see example in https://github.com/larshp/abapGit/pull/2141

**Comment by larshp** [comment]
G4BA	SAP Gateway OData V4 Backend Service Group & Assigments
G4BS	SAP Gateway OData V4 Backend Service

**Comment by larshp** [comment]
G4BS objects are created in SEGW, not sure how to create the service groups

**Comment by larshp** [comment]
@arcanist123, try again, latest version
