### ISSUE TITLE
Object type ignored, not supported: TABT

### ISSUE THREAD

**Issue by guigashm** [larshp/abapGit#2709]
Hello,

First, like to say impressive work. 👍  :D 

I got , "Object type ignored, not supported: TABT". 

Can you help me, please?

Do you have any plans already to add TABT support ?  
Or this is already supported, by some kind of plugins ( I went to the plugins page, says "is obsolete" )  

Thank you so much,

**Comment by larshp** [comment]
you can try installing https://github.com/larshp/abapGit-Plugins, however this plugin will become obsolete sometime

recommend implementing native support, the generic serializer might work, see example in #2141

**Comment by larshp** [comment]
hmm, how can the issue be reproduced? TABT is not a top level object, R3TR but instead its a LIMU, which are not supposed to be processed in abapGit

**Comment by larshp** [comment]
closing, no reply
