### ISSUE TITLE
Dumping due to missing CONVERSION_EXIT_RSDAT_INPUT (no SAP_BW)

### ISSUE THREAD

**Issue by lvx-mikhail** [larshp/abapGit#2716]
abapGit uses FM CONVERSION_EXIT_RSDAT_INPUT from SAP_BW. I do not have it -> dump. Could you replace that the functionality does not depend on software components.

**Comment by larshp** [comment]
https://github.com/larshp/abapGit/blob/9f2db446b1469bbccae77977ce74fe2c2912db2c/src/objects/zcl_abapgit_object_ecatt_super.clas.abap#L271

**Comment by larshp** [comment]
test with https://github.com/abapGit-tests/ECATT

**Comment by larshp** [comment]
@lvx-mikhail try this: https://github.com/larshp/abapGit/pull/2717

**Comment by flaiker** [comment]
@larshp @christianguenter2 
/SDF/CD_CCA allows for a static usage analysis grouped by component. Maybe we could automatically check this in abapGit/CI ?
![image](https://user-images.githubusercontent.com/5270359/58687763-d55ade00-8382-11e9-83c0-b7098e9ade35.png)

**Comment by larshp** [comment]
we cannot trigger it automatically for a PR anyways, due to the minisap licensing

but this is something that I'll build into abaplint someday

**Comment by larshp** [comment]
@lvx-mikhail merged, try latest version

**Comment by lvx-mikhail** [comment]
@larshp , this part works fine but after execution got a new dump related to missing FM CONVERSION_EXIT_TIMLO_INPUT.  Could you please check it it can be replaced as well?

**Comment by lvx-mikhail** [comment]
It is working fine for me! Thank you for your quick support!
