### ISSUE TITLE
W3MI: abapGit CI failed - left over package

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2719]
Propably we need to delete tadir entry?
![image](https://user-images.githubusercontent.com/17437789/58690331-99774700-8389-11e9-9b08-84f21142490b.png)

Test repo
https://github.com/abapGit-tests/W3MI.git

#2639

**Comment by larshp** [comment]
yea, also noted in https://github.com/larshp/abapGit/issues/2639
