### ISSUE TITLE
TOBJ: abapGit CI failed - left over package

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2720]
Propably we need to delete tadir entry?

![image](https://user-images.githubusercontent.com/17437789/58690485-eb1fd180-8389-11e9-95a2-bf058bf093e9.png)

Demo repo
https://github.com/abapGit-tests/FUGR_maintenance_view_variant.git

![image](https://user-images.githubusercontent.com/17437789/58690628-4d78d200-838a-11e9-95e8-97341992b5e9.png)

**Comment by christianguenter2** [comment]
Fix #2735 seems to be contra productive.

More CI failures with TOBJ related repos

e.g. https://github.com/abapGit-tests/FUGR_maintenance_view.git
![image](https://user-images.githubusercontent.com/17437789/59461892-bfd5c180-8e22-11e9-9af2-b7954fb17884.png)

![image](https://user-images.githubusercontent.com/17437789/59461894-c106ee80-8e22-11e9-91b5-0984c89d2333.png)

**Comment by flaiker** [comment]
Maybe TADIR needs to only be deleted explicitly for certain view types? (dd25v-viewclass)

**Comment by christianguenter2** [comment]
As the issue is technically fixed I'll close. Todo comment for improvement is in the code.
