### ISSUE TITLE
Add customizable commit template

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2730]
In the repository settings, the user should be able to save a template commit message and body which will be prefilled on the commit page.

For example, I would use this custom body to prefill our JIRA project key so I only need to add the issue number to link the task to the commit. It could also be used to display some information the developer should be aware of before committing.

**Comment by larshp** [comment]
would this be a setting persisted in the `.abapgit.xml` file or locally on the server?

**Comment by FreHu** [comment]
Both make sense, but I'd just put it on the server - you generally only develop on one system. Also, it's debatable whether you want to preserve the same templates for people who fork your repo.

**Comment by larshp** [comment]
ok

**Comment by FreHu** [comment]
commit title template implemented in #3371, closing to unclutter issues.
