### ISSUE TITLE
Investigate and improve handling of pre-commit hooks

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2731]
A repository owner might want to require his developers to properly document their commits.

Add a repository setting which if enabled will make the commit body required.

**(this is the original issue, see comments for actual issue)**

**Comment by larshp** [comment]
hmm

I think this is something the git server should be responsible for checking, not the git client.

**Comment by FreHu** [comment]
Does the abapgit client know how to display a failed hook?

**Comment by larshp** [comment]
no, I dont think abapGit does a good job displaying failed hooks, this we should improve

**Comment by larshp** [comment]
I'll try closing this, this is something that can be enforced via CI outside of the git client
