### ISSUE TITLE
Lost in contribution

### ISSUE THREAD

**Issue by VishnAndr** [larshp/abapGit#274]
Hello Lars!

The guide 'how to contribute' should be updated :) I'm lost how to contribute to the project with latest updates to abapGit and abapmerge.

Currently I have an online repo $ABAPGIT connected to _your_ git repository. Pulled it into the system. Also I have forked abapGit into my own git repository. What should I do next after implementing some changes? Need your help :)

**Comment by larshp** [comment]
yeah, sorry, everything gets more complicated with a build step

I've updated https://github.com/larshp/abapGit/blob/master/CONTRIBUTING.md

Basically just implement the changes in the include programs and submit it. The build is handled automatically without any manual steps.

**Comment by VishnAndr** [comment]
Awesome! Thanks a lot!
