### ISSUE TITLE
Activation error for ZABAPGIT three-digit number XXX required in the Message

### ISSUE THREAD

**Issue by Seemanaths** [larshp/abapGit#2742]
Hi Team,
    I am getting an error while activating the program. Is there any way any one can please help me ?
Thanks in advance.

![image](https://user-images.githubusercontent.com/51808268/59479711-18a06b00-8eb2-11e9-8d48-912b5dd26bd3.png)

![image](https://user-images.githubusercontent.com/51808268/59480079-505be280-8eb3-11e9-8bea-ad204997fdd4.png)

**Comment by christianguenter2** [comment]
Quick fix: Comment the line

**Comment by larshp** [comment]
@Seemanaths what SAP_BASIS version are you running?

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapGit/pull/2743, closing

**Comment by Seemanaths** [comment]
@larshp we are in 702 .

**Comment by Seemanaths** [comment]
Thanks #2743 fixed my issue.
