### ISSUE TITLE
Inconsistent de-serialization of check fields from DDIC in Dynpros. 

### ISSUE THREAD

**Issue by hectormartinezn** [larshp/abapGit#2745]
Hi, 

[using the latest version of abapGit (v1.87) with ABAP 7.4]

I found an issue when de-serializing dynpros that have a check field for which a flag
type has been taken from the Dictionary. The procedure to reproduce the issue is the following:

-   Create a check field in the dynpro using a flag field from the Dictionary
-   Accept the prompt to import the properties of the the flag from the Dictionary 
-   There has to be enough space in the Dynpro so the field label is taken
-   Manually erase the generated text
-   Notice that the `Modify` setting in the properties of the field is kept blank. If other circumstances if a dictionary field is taken but the text is not taken (e.g. there is no enough space) this label is automatically set to `X`.
![issue1_source](https://user-images.githubusercontent.com/46260267/59666385-00cc2e00-91b5-11e9-9d75-e67eb40e68bf.PNG)
-   Save and activate the dynpro
-   Transport with abapgGit
-   After the de-serialization in the the target system the `Modify` setting has been set to `F` with the corresponding field label text taken from the Dictionary.

This last point can be a bigger issue since at design time other fields may have been added to the dynpro, potentially overlapping with the check field label. In this last case, the error `RPY_DYNPRO_INSERT: 6` is triggered during de-serialization stopping the whole process.

I have a patch for this. In the class `zcl_abapgit_objects_program,` method `deserialize_dynpros`, add the following block before calling the `RPY_DYNPRO_INSERT` function: 

```abap
if  <ls_field>-type = 'CHECK'
    and <ls_field>-from_dict = abap_true
    and <ls_field>-text is initial
    and <ls_field>-modific is initial.

        "If the previous conditions are
        "met the value 'F' will be taken over 
        "during de-serialization potentially
        "overlapping other fields in the screen,
        "we set the tag to the correct value 'X':

        <ls_field>-modific = 'X'.

endif.
```

This addition solves the issue. If you agree I can submit a pull request with the correction.

**Comment by larshp** [comment]
lets try it, please submit a PR with the test case to https://github.com/abapGit-tests/PROG_dynpro_modi/settings

**Comment by hectormartinezn** [comment]
done

**Comment by hectormartinezn** [comment]
now?

**Comment by larshp** [comment]
plus can you help submitting a PR to abapGit with the above fix?

**Comment by hectormartinezn** [comment]
Since the patch is already merged into master I think we can close this issue
