### ISSUE TITLE
Question regarding the <FOREIGNKEY> tag in the serialization of Dynpros

### ISSUE THREAD

**Issue by hectormartinezn** [larshp/abapGit#2746]
Hi,

I have a question regarding the `<FOREIGNKEY>` tag after serializing a dynpro with a field from the Dictionary. I noticed that it is always set to `X` even if in the screen painter the option for setting it is deactivated when the properties of the field are taken from the Dictionary.

![foreignkey_issue](https://user-images.githubusercontent.com/46260267/59672330-8e148000-91bf-11e9-8432-680d74e2cd44.PNG)

![foreignkey_issue_02](https://user-images.githubusercontent.com/46260267/59672351-95d42480-91bf-11e9-9cd6-19ac311f119e.PNG)

Most of the times this setting does not play a role because after de-serialization this tag is ignored also in the target system (apparently) due to the fact that the properties of the dictionary overwritte this option. 
However, this issue may be related to another bug (I'm submitting it as a separate issue later) in which the  `<FOREIGNKEY>` is set to `X` after de-serialization even if it is blank in the source system.

My question is, is this a SAP or abapGit issue? can the tag be left blank during the serialization of the dynpro even it is does not play a role in the de-serialization of the screen? 

Thanks in advance.

**Comment by larshp** [comment]
abapGit calls function module `RPY_DYNPRO_READ`, try setting a breakpoint to see what it returns

class ZCL_ABAPGIT_OBJECTS_PROGRAM, method SERIALIZE_DYNPROS

**Comment by hectormartinezn** [comment]
Ok. I will try it.

**Comment by hectormartinezn** [comment]
Hi,

I checked this. The the field ``FOREIGNKEY`` of the relevant entry of ``lt_fields_to_containers`` is set in the function ``RPY_DYNPRO_READ``. After analyzing this function I suspect that the problem lies either in the ``RPY_DYNPRO_READ_NATIVE`` or  in the ``RPY_DYNPRO_CVT_INTO_EXTFORMAT`` function. Don't know if there is much to do about it from the abapGit side.

**Comment by larshp** [comment]
We can add a bit of extra code after calling the function module, but suggest first to look for SAP notes

**Comment by hectormartinezn** [comment]
Hi,

I'm submitting a PR that fixes this issue so I want to explaing/document here the reasoning behind the patch.

First, the problem lies in that the logic used to set the foreign key field in `RPY_DYNPRO_CVT_INTO_EXTFORMAT`
appears to be wrong:

```abap

"(in the subroutine R_ASSIGN_FIELD_BIT_TO_FIELD)

IF   P_FIELD_INT-FLG1 O FLG1DDF          "E/A-Feld aus dem Dict:
  AND  P_FIELD_INT-FLG1 O FLG1EDT.
    IF P_FIELD_INT-FLG3 O FLG3FKU.           "Fremdschl.pr abgeschaltet
      P_DYNP_FIELD-FOREIGNKEY = RPYTY_OFF.
    ELSE.
      P_DYNP_FIELD-FOREIGNKEY = RPYTY_ON.
    ENDIF.
  ELSE.
    P_DYNP_FIELD-FOREIGNKEY = RPYTY_OFF.
  ENDIF.

```

Here `flg1` and `flg3` define the properties of the screen field `P_FIELD_INT` in internal format. The values of the flags (e.g. `FLG1DDF`) are defined in the include `MSEUSBIT`.

The proposed fix implements the logic used to show the Element list of a screen in the Screen Painter (program `SAPLWBSCREEN`). To my knowlegde that information is always correct:

```abap
IF f-flg1 O flg1ddf AND
         f-flg3 O flg3for AND
         f-flg3 Z flg3fdu AND
         f-flg3 Z flg3fku.
        
        feld-ffky = 'X'.
ENDIF.

```

In order to implement this logic in the method `serialize_dynpros` we have to read the properties of the dynpro field in internal format. This is done calling the function `RPY_DYNPRO_READ_NATIVE` for each dynpro field in the screen.

**Comment by hectormartinezn** [comment]
Great. I consider it solved so I will close it.
