### ISSUE TITLE
The Dynpro field attribute 'Foreign Key Check' is wrongly set during de-serialization

### ISSUE THREAD

**Issue by hectormartinezn** [larshp/abapGit#2747]
Hi again,

I found an issue related to the `Foreign Key Check` attribute of Dynpro fields. 

If the attribute is active, that is, it can be modified at design time because the dynpro field get the attributes from the Dictionary and the respective field has an assigned check table, abapGit wrongly sets the attribute as `X` during de-serialization.

![issue2_2](https://user-images.githubusercontent.com/46260267/59689865-afd22f00-91e0-11e9-9008-88ad350d33ae.PNG)

This can make input fields unusable after being imported with abapGit when SAP tries to enforce the check during runtime.

I solved the issue adding the following line to the method `deserialize_dynpros` of the class `zcl_abapgit_objects_program`:

```abap
if <ls_field>-foreignkey is initial.
     <ls_field>-foreignkey = lc_rpyty_force_off.
endif.
```

This forces the attribute to be kept unset after de-serialization. 

This issue may be related to #2746 where the field `foreignkey` appears to be set by default to `X` even if that setting is meaningless.  

I can submit a PR with my solution but I would like to get more feedback on issue #2746 first.

Thanks in advance

**Comment by hectormartinezn** [comment]
Hi,

I prepared a package to reproduce this issue. If you create a repository in  https://github.com/abapGit-tests/ I can create a PR with the package.

**Comment by larshp** [comment]
https://github.com/abapGit-tests/PROG_dynpro_foreign_key
