### ISSUE TITLE
Reset local takes hours

### ISSUE THREAD

**Issue by jani80k** [larshp/abapGit#2748]
Hi guys, 
I just updated to the latest version via copy&paste method.
I did a reset local on the abap2xlsx project and it is taking forever.
In SM50, I can see "Sequential Read of DB" on table TRDIR is causing the issue.
The reset local used to be much much quicker.
Has anything changed?
Cheers,
Jani

EDIT: I am completely aware that this might be a local issue. Please help in case you can.

**Comment by larshp** [comment]
Recent changes: https://github.com/larshp/abapGit/commits/master

Try doing a database trace, or trigger the debugger from SM50 to see which SQL statement takes the time

**Comment by jani80k** [comment]
![grafik](https://user-images.githubusercontent.com/16916879/59917452-3de92800-9422-11e9-9547-ef09d520beeb.png)
This is taking long... we are looking at some SAP notes which we can possibly apply.

**Comment by jani80k** [comment]
0002327896 solved the issue...

**Comment by larshp** [comment]
cool, closing this issue
