### ISSUE TITLE
Capital Case / Lower-Case

### ISSUE THREAD

**Issue by timostark** [larshp/abapGit#2755]
Hi All,

I want to utilize abapGit as deployment verification in our jenkins deployment pipeline. Simple Idea: In case abapGit can not recognize any open changes after a transport is done (pushed via commit), than the transport was correct "on byte level".

In comparison of Classes i have unexpected side effects with our pretty printer and the ABAP transport management system. On the left side you have the target system (e.g. production), on the right side you have the development system (or better git status).
![image](https://user-images.githubusercontent.com/19237828/60087521-74ce7f00-973d-11e9-9c79-58bc32da5666.png)

Unfortunately it seems that the capital/lower case settings done in eclipse (e.g. via formatting) are not applied during transport. Instead they are just overwritten by the transport management system. Even after transporting R3TR/CLAS the changes are not taken over to the target system.

"Workaround": Manually adjust the class name to be capital case in the target system. This workaround does not really work, as with the next eclipse pretty print the upper case is restored.

Do you have experienced this issue already and maybe even have a solution? If not: The only solution I could think of is serializing the class name as capital case in the IMPLEMENTATION line (sounds like an extremely ugly solution unfortunately :-(). What do you think of that?
We are using NW ABAP 750 / SP12.

Thanks,
Timo

**Comment by larshp** [comment]
I would regard this as a bug in the SAP deployment logic. However it will probably not be changed.

See the last exit described in https://docs.abapgit.org/ref-exits.html it can be used to change the serialization logic.

Additionally/another approach is to force the file in git to be upper case by triggering errors via linting.

**Comment by timostark** [comment]
Hmm ya.. I assume the same answer is valid for the problems:
- method order after deployment is different, in case it was changed manually in eclipse in development system
- spaces / line breaks added between methods are not deployed, and therefore differ

?

**Comment by timostark** [comment]
one additional question.. How are you handling auto-generated classes in customer namespace?

**Comment by flaiker** [comment]
I knew someone else would also run into this problem :)

The example implementation linked in the docs for the exit _should_ give you consistent serialization results, even if SAP randomly decides to reorder and reformat stuff. As far as I know the "old" class serializer which is used there has a fixed amount of lines between method implementations and always constructs the (END)METHOD statements in all uppercase. Everything else _should_ just be the source code of the separate includes (okcode SHOW_CLIF in SE24).

One thing to keep in mind is that if you enable it for existing repositories you will get one huge commit which changes the method order in all classes to be alphabetical and therefore complicates your git history quite a bit.

**Comment by timostark** [comment]
hmm - ok i just should have checked the provided link :-)
I will give the "old" de-serializer a try and close this one, in case it is working 👍

**Comment by timostark** [comment]
OK - works perfectly.. Thanks a lot.

**Comment by larshp** [comment]
disadvantage: the code made by the developer does not match what is moved to git
