### ISSUE TITLE
docs, add anchors

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2756]
will https://github.com/allejo/jekyll-anchor-headings work?

**Comment by larshp** [comment]
nah, not part of the approved plugins, https://help.github.com/en/articles/about-github-pages-and-jekyll#plugins

**Comment by allejo** [comment]
Hai there 👋 for what it's worth, my project isn't a Jekyll plug-in that needs to be whitelisted. It's something *crazy* you can drop in your `_includes` and use it via `{% include %}` in your site.

**Comment by larshp** [comment]
👋 thanks, I tried it out, but ended up just doing a javascript solution
