### ISSUE TITLE
ZCX_ABAPGIT_EXCEPTION source code position 

### ISSUE THREAD

**Issue by mfsap** [larshp/abapGit#2759]
Usually, when an exception is raised, method `CX_ROOT->GET_SOURCE_POSITION()` returns the source code of the calling program. When using methods `ZCX_ABAPGIT_EXCEPTION=>RAISE(_T100)`, the source code position within `ZCX_ABAPGIT_EXCEPTION` is returned and not where the method call happens.
I'll prepare a PR for this issue...

**Comment by flaiker** [comment]
Related: #1998

**Comment by christianguenter2** [comment]
#1998 is merged. @mfsap What do you think, can we close this?

**Comment by mfsap** [comment]
yes, this issue can be closed now. thanks
