### ISSUE TITLE
Jump to ADT for transport requests/tasks

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2761]
I discussed it internally and this is the proper way of building the url for transports:

```abap
data(transport_adt_uri) = cl_cts_adt_tm_uri_builder=>create_adt_uri( <transport request/task number> ).
data(adt_link) = |adt://{ sy-sysid }{ transport_adt_uri }|.
```

**Comment by larshp** [comment]
cool, make sure to make the call dynamic as ADT does not exist on 702

**Comment by christianguenter2** [comment]
As cl_cts_adt_tm_uri_builder only exists in NW >=753 I'd suggest to fallback to SAPGUI jump instead of raising this  exception.
https://github.com/larshp/abapGit/blob/f5d421e399937163f6718e6f1063dcdeff7a7a46/src/ui/zcl_abapgit_gui_router.clas.abap#L453
