### ISSUE TITLE
zcl_abapgit_environment=>is_merged doesn't work in exception classes

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2763]
As zcl_abapgit_environment=>is_merged calls the global class it doesn't work as expected.
![image](https://user-images.githubusercontent.com/17437789/60380411-9a150300-9a45-11e9-9fed-268a3d0e2b56.png)

**Comment by larshp** [comment]
hmm, the installer program should not hit the global class?

**Comment by christianguenter2** [comment]
Yeah, but it does.

**Comment by larshp** [comment]
hmm, perhaps try changing it to an instance method

**Comment by christianguenter2** [comment]
Ok, got it. I call zcl_abapgit_environment=>is_merged in zcx_abapgit_exception and those are defined and implemented before the deferred class definitions.

**Comment by larshp** [comment]
can this be closed? with the new solution I guess we do not need to call `is_merged` ?
