### ISSUE TITLE
Not supported object types: SAP Gateway IWMO / IWOM / IWSG / IWSV

### ISSUE THREAD

**Issue by mnemotron** [larshp/abapGit#2767]
Hi,
I want to deserialize gateway services and need the following object types:

Object type ignored, not supported: IWMO
Object type ignored, not supported: IWOM
Object type ignored, not supported: IWSG
Object type ignored, not supported: IWSV

Thank you very much!

**Comment by christianguenter2** [comment]
Did you try abapGit plugins?

**Comment by larshp** [comment]
we should just implement these in core

**Comment by larshp** [comment]
also see https://github.com/larshp/abapGit/issues/75

**Comment by larshp** [comment]
todo: update https://docs.abapgit.org/ref-supported.html when/in merge

**Comment by mnemotron** [comment]
Super thank you because gateway services and sapui5 is becoming more important.

**Comment by larshp** [comment]
@mnemotron can you help testing the pull request?

**Comment by mnemotron** [comment]
sure, I'll be glad to help

**Comment by mnemotron** [comment]
I'll test it on Monday. My SAP has no access to the internet I use the following link for an offline upgrade. https://github.com/larshp/abapGit/archive/gateway.zip

**Comment by mnemotron** [comment]
Hello, I tested it. There were no errors during serialization and deserialization. The objects are there. It looks good. I'll keep it under observation. If there's any complications, I'll get back to you.
Thank you very much for the quick implementation. Many greetings...

**Comment by larshp** [comment]
thanks, merging, closing issue, open new if errors are found
