### ISSUE TITLE
Unify ordering of diff with order in commit

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2777]
- The main page orders files alphabetically by `filename`.
- The abapgit diff and patch pages order files alphabetically by `filename`.
- The stage page orders aplhabetically by `folder + filename`.
- On github, the commit will have files ordered alphabetically by `folder + filename`.

When I look at what I committed on github, the files might be in a completely different order if the changes are across packages.

This can be fixed by adding 
```abap
      SORT lt_status BY path ASCENDING filename ASCENDING.
```
to the diff page.

and
```abap
    SORT lt_repo_items BY path ASCENDING obj_name ASCENDING.
```
to the main page.

I think the order should be consistent with github ordering. @sbcgua @larshp

**Comment by larshp** [comment]
sounds good to me
