### ISSUE TITLE
abapGit source: One include for each object type

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#278]
Where possible, add folder?, Will help keeping track of history

split
https://github.com/larshp/abapGit/blob/master/src/zabapgit_object.prog.abap
into multiple
zabapgit_object_++++.prog.abap includes

perhaps create a folder 
https://github.com/larshp/abapGit/blob/master/src/objects/ to store the new files

**Comment by sbcgua** [comment]
Also adding folder per object type for serialized data would be great (may be optional via some settings)

**Comment by larshp** [comment]
I meant to refer to the abapGit source code, I've updated the description and title, sorry about the confusion.

I guess the above refers to projects using abapGit. Currently subpackages will create extra folders, eg. in https://github.com/larshp/abapGitServer/tree/master/src/ddic there is an subpackage which contains the DDIC objects. It might be a good idea to automatically create directories for TADIR-OBJECT types. @sbcgua can you raise this as a separate issue?
