### ISSUE TITLE
Missing creation of the TADIR entry when importing badi

### ISSUE THREAD

**Issue by marcushoepfner** [larshp/abapGit#2781]
When importing a BAdI implementation the api for creating the tadir entry for enhancement should be called. otherwise creating the enhancement may fail.
API is cl_adt_corr_insert_dark->corr_insert()

**Comment by larshp** [comment]
what is the specific type? then I'll create a repo under https://github.com/abapGit-tests so we can add this to the tests

**Comment by marcushoepfner** [comment]
BADI_IMPL in this case. Maybe it is worth to have tests for other types as well.

**Comment by larshp** [comment]
see comment in https://github.com/larshp/abapGit/issues/2782

**Comment by marcushoepfner** [comment]
see comment in [#2782](https://github.com/larshp/abapGit/issues/2782)

**Comment by marcushoepfner** [comment]
Debugged while installing the git repo containing a badi.
Seems to be no error. 
Seems to be an error in the unit test so I guess the unit test is wrong.
I'm going to investigate this and close this bug.
