### ISSUE TITLE
No need to call save() when deleting an enhancement

### ISSUE THREAD

**Issue by marcushoepfner** [larshp/abapGit#2782]
Calling save raises an exception after delete() call.
Save shall be removed.

**Comment by larshp** [comment]
what is the specific type of enhancement?

I'll create a repo for it under https://github.com/abapGit-tests, then you can help adding the test case?

**Comment by marcushoepfner** [comment]
In my case it was BADI_IMPL. Also for HOOK_IMPL there is no need to call save()

**Comment by larshp** [comment]
ok, can you help opening a pull request to 
https://github.com/abapGit-tests/ENHO-HOOK_IMPL
and
https://github.com/abapGit-tests/ENHO-BADI_IMPL
with some simple examples of the ENHO, then it will be run as part of https://ci.abapgit.org

**Comment by marcushoepfner** [comment]
Done for BADI_IMPL. I'd like to check it for BADI_IMPL first, fix it and check CI then.
Afterwards I can also create a test object for HOOK_IMPL.
Ok for you?

Am I right that we are expecting red tests for HOOK_IMPL after the pull request is merged?

**Comment by larshp** [comment]
yea

@christianguenter2 can you help running/updating ci.abapgit.org when you have time?

**Comment by christianguenter2** [comment]
@marcushoepfner 
I can't install the demo repo https://github.com/abapGit-tests/ENHO-BADI_IMPL.git in my system.
![image](https://user-images.githubusercontent.com/17437789/61391666-7c58f200-a8bd-11e9-8088-72aa48cccb54.png)

Can you you add the missing objects to the repo?

**Comment by marcushoepfner** [comment]
You can just create them. You need a spot with the name ZMH_ENH_SPOT1. A badi definition in the spot ZMH_ENH_SPOT1_BADI1. A class and an interface and so on.

**Comment by marcushoepfner** [comment]
... as I thought a bit of it now I maybe got it.
Guess you want to have working examples with everything what is needed.
I'm going to create them tomorrow.

**Comment by marcushoepfner** [comment]
created a pull request. Could you please merge it and re-check

**Comment by christianguenter2** [comment]
Ok. I cannot reproduce the issue in my NW 752 SP01 system. Is the anything special in you setup?

**Comment by marcushoepfner** [comment]
Nothing special.

I wrote unit tests for zcl_abapgit_object_enho with a mocked database.
In testing the delete method the test aborted since the save() failed. save() threw exception cx_enh_canceled and afterwards unlock was not called.

Did you invoke the delete() method? Not sure how this can be done via UI. Only did it in unit tests.

**Comment by christianguenter2** [comment]
I don't get it. I just installed and deinstalled the demo repository as abapGit CI does. No errors there. Are we solving a real problem?

**Comment by marcushoepfner** [comment]
I also checked it and couldn't see an error. I installed and deinstalled the repo.
Also when debugging no error/exception can be seen. calling save() after delete() seems to be ok.
In my unit test this failed. So I guess the unit test has an error.
So we can close this bug.
