### ISSUE TITLE
test if abapGit follows HTTP redirects

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2786]
on github when a repo is renamed or ownership is transferred, it gives a http redirect,

test the behavior of abapGit in this case

suggest showing a message about the redirect so the user can manually change the repo to the new url

**Comment by flaiker** [comment]
Another use case is when you finally get a HTTPS certificate for your onpremise Git server and need to change the remotes of all repositories.

**Comment by FreHu** [comment]
I have a few repositories which I created myself and then transferred into an org. I had no problems committing with the old url still set.

**Comment by larshp** [comment]
no problems as noted above, closing
