### ISSUE TITLE
Parallel Development using abapGit

### ISSUE THREAD

**Issue by saranyaraghuram** [larshp/abapGit#2788]
Can we achieve parallel development for ABAP objects using abapGit? Two or more developers working on the same SAP object(Eg: Program/FM) and merge their code together when complete. 
Just like how fiori/ui5 application developers work on the local webIDE instance on the same application and merge their code using Git.

**Comment by gregorwolf** [comment]
In principle you can as you see on all the ABAP OpenSource Projects listed at https://dotabap.org/. But you need an ABAP system for each developer to be completely independent.

**Comment by saranyaraghuram** [comment]
Can we attain this without the independent ABAP systems? It will not be feasible to have multiple SAP servers for each developer. I understand for opensource languages we can attain this cause they don't have server dependency during development.

**Comment by larshp** [comment]
you can choose to avoid the server dependency during development and let the developers write unit tests, and then the server dependency can be tested in the integration system

another possibility is suggested in https://blogs.sap.com/2017/10/13/branching-in-abap-experiences/, but in my opinion this is too difficult

I recommend working on avoiding the problem altogether, if you have two or more developers working on the same object it is typically a sign that the object should be refactored

**Comment by saranyaraghuram** [comment]
But how do we avoid the server dependency? are there any tools to compile abap code and write unit tests without the server?
If not we'll have to work on the other options.

**Comment by larshp** [comment]
sorry, I assumed you meant server dependency, as in having dependencies between servers like integrations that make it more complex to do local development

**Comment by larshp** [comment]
@saranyaraghuram: did this help, can we close the issue?
