### ISSUE TITLE
Deleting all lines when patching should count as a deletion of the entire file, not just the lines

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2789]
@christianguenter2 
I noticed that using patch will not delete files correctly if all lines are marked for deletion. From the history it seems it was like this from the start.

https://github.com/larshp/abapGit/blob/2db46137fcf89f9c1e499822792308c22c1c6f40/src/ui/zcl_abapgit_gui_page_diff.clas.abap#L202-L205

## Patch
- Deleting by selecting all lines for deletion will only commit line deletions, but leave the file.
![SapGuiServer_JV3m4rh6Ue](https://user-images.githubusercontent.com/5097067/61213749-39085300-a706-11e9-944c-cd7a4e204de2.png)

You can see the stage flag is set to add:
![SapGuiServer_UmNDYcQjun](https://user-images.githubusercontent.com/5097067/61213908-c055c680-a706-11e9-91a2-ac1629faaf11.png)

- After committing, you are left with these differences:
![image](https://user-images.githubusercontent.com/5097067/61213787-56d5b800-a706-11e9-8735-d737a3863f07.png)

Trying to commit this diff through patch again will lead to an empty commit and the files will remain. They can be removed from the staging page.
https://github.com/FreHu/abapgit-patch-delete-test/commits/delete-patch

## Stage
- Deleting via stage assigns the remove flag to the staged file and correctly delete it
![SapGuiServer_guF1ANOgXf](https://user-images.githubusercontent.com/5097067/61213726-2857dd00-a706-11e9-819f-faef0b36536c.png)

**Comment by christianguenter2** [comment]
Yeah, noticed this also a while ago. I'll try to fix it soon.
