### ISSUE TITLE
Function Modules not imported

### ISSUE THREAD

**Issue by fidley** [larshp/abapGit#2794]
Hi @larshp , 

seems like there is an issue with importing FM. I was importing now 2 zips (abapgit & falv) to the S/4 system and although the files for FM are visible on the list, they are not created as an object later on. 
They are always visible as something new, but you cannot install them. 

Is this something known?

![image](https://user-images.githubusercontent.com/7912195/61289982-ff4d5000-a7ca-11e9-85c6-6be77a53d5ec.png)

![image](https://user-images.githubusercontent.com/7912195/61290008-13914d00-a7cb-11e9-97a4-64c7049bb63c.png)

Cheers
Łukasz

**Comment by larshp** [comment]
are you using the offline zip feature?

**Comment by fidley** [comment]
yes I do

**Comment by larshp** [comment]
I have a suspicion that offline imports does not show errors, see https://github.com/larshp/abapGit/issues/2793

**Comment by fidley** [comment]
could be, because there was no info at all, just comparison of the files once the pull was done

**Comment by fidley** [comment]
any clue which class should I debug?

**Comment by larshp** [comment]
PR https://github.com/larshp/abapGit/pull/2729 added the feature that the log is shown when importing online repos
^ still just a guess

**Comment by larshp** [comment]
class ZCL_ABAPGIT_SERVICES_REPO, method GUI_DESERIALIZE, try setting a breakpoint in the last statement and checking the log object

**Comment by fidley** [comment]
Ok, so the log is created and filled but not shown. The issues is my case are authorizations. But would be good that the log is shown or the menu appears also for the offline mode.

**Comment by larshp** [comment]
yea, offline and online should work similar in this case

**Comment by fidley** [comment]
If this will work I'll create PR
![image](https://user-images.githubusercontent.com/7912195/61294014-388abd80-a7d5-11e9-8fd9-b24e02c642d4.png)

**Comment by fidley** [comment]
ZCL_ABAPGIT_GUI_VIEW_REPO->BUILD_HEAD_MENU

**Comment by larshp** [comment]
above will show the "Log" button, but I guess we also need to issue a MESSAGE somewhere?

**Comment by larshp** [comment]
looks good to me

**Comment by fidley** [comment]
works but I have now #1491 and I cannot stage it..... Will try on other machine later.

**Comment by flaiker** [comment]
@fidley Did you update the *.github.com certificate lately? It expired last week and now there is a new one.

**Comment by fidley** [comment]
@flaiker yes, I've updated it but didn't worked for me.

**Comment by larshp** [comment]
guess this can be closed?

**Comment by fidley** [comment]
yes, sorry forgot about
