### ISSUE TITLE
Importing dictionary to existing package from ZIP

### ISSUE THREAD

**Issue by SMilesi** [larshp/abapGit#2797]
Hi all!
I have downloaded a zip with dictionary and function groups (the ones generated for SM30) from the my origin system and tried to upload it into a new one, attaching the objects to an existing package.
A TR has been required and provided, but, after the pull, just the Function groups were attached to the TR and the package and the dictionary wasn't imported.
Of course, the FG were not activated due the missing dictionary.

I deleted all the objects from the system and the references in TR and tried to upload the objects into a new local package and it worked perfectly.
I attach the zip file i used
[Base_dictionary.zip](https://github.com/larshp/abapGit/files/3400964/Base_dictionary.zip)

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit/issues/2794, currently errors are not shown when importing to zip, the issue also contains a fix, and @fidley will open a pull request with the fix

but in the meanwhile try applying the fix manually

**Comment by larshp** [comment]
@SMilesi has this issue been fixed with the latest version?

**Comment by SMilesi** [comment]
@larshp i'll try it next week into a fresh system and let you know asap

**Comment by SMilesi** [comment]
With the new version, it works smoothly
