### ISSUE TITLE
Separate files into folders by object type

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#280]
Would be a nice feature. Optional and controlled from some settings of a specific repo. 

E.g. I have one dev which I'd like to keep (mainly for traceability) in git - ~450 objects of 21 obj types. It just won't be usable as a plain list.

In fact it does not look well in abapgit interface too. I guess the same setting can be used to show folders in UI also. But probably it is a separate task.

**Comment by sbcgua** [comment]
#278 is in fact connected imho. If you make a lot of includes there will be the same issue as I mentioned here. Just as a thought: maybe it can go further then just splitting by objtype.

E.g. setting to split by type
```
<SPLIT>
  <METHOD>BY_TYPE</METHOD>
</SPLIT>
```

Or "manual" regex rules (assuming "default" is going to root folder):
```
<SPLIT>
  <METHOD>LISTS</METHOD>
  <RULES>
     <RULE>
         <DIR>UI</DIR>
         <MATCH>.*(page|gui).*</MATCH>
     </RULE>
     <RULE>
         <DIR>OBJECT</DIR>
         <MATCH>.*(object).*</MATCH>
     </RULE>
  </RULES>
</SPLIT>
```

**Comment by larshp** [comment]
for #278, I'm considering making moving zabapgit_object_* includes to a package eg. $abapgit_objects(subpackage of $abapgit). Then these includes will automatically be in a /objects/ folder. The developer can move objects between packages to decide the folder the objects goes into.

Example, for https://github.com/larshp/abapGitServer, I've split the development into the following packages:
![image](https://cloud.githubusercontent.com/assets/5888506/16649999/1d27d848-443c-11e6-8eef-0cc461d46968.png)
this automatically results in the following directory structure on github:
https://github.com/larshp/abapGitServer/tree/master/src

**Comment by sbcgua** [comment]
Looks like an option. Package is a high level object it is not always logical to structure code with those. In you case backend/frontend can be viewed as separated applications. Objects in abapgit can be announced an xml serialization library which can be used elsewhere. So it looks OK.
My case is a tool for VAT accounting - it does not split into small parts which may work separately. 

But anyway that's far fetching - splitting by objtype would be a nice start. :)

**Comment by larshp** [comment]
yes, I agree, if difficult to split up using packages, splitting by object type could be a nice feature.

eg. data elements all go into a /DTEL/ directory etc. the split by pakcages could be used in combination with this feature

**Comment by larshp** [comment]
@sbcgua are you on Twitter?

**Comment by sbcgua** [comment]
No :) I'm social-network-unfriendly :) Except Linkedin

**Comment by sbcgua** [comment]
Not so easy as I thought ...
I think to start from the existing feature - subpackages - and then do folding by type eventually. 
The structure presents both in local and remote. So if I understand correctly the "folding" should analyse both, select uniqe and create visual structure for the combination of local+remote. Right ?
How to show orphans ? On the upper level or in correspondent folder ?

Current thoughts: 
- there should be some class - some kind of folder browser - to generate portions of files for the selected dir. Or maybe an interface to implement it then in package-brower, type-browser, whatever-browser (custom folderring in some distant future). It is this class which should be accessed by page main. 
- main_page should be splitted to the page and repo content class which renders content div based on browser output. 

something like that.

**Comment by sbcgua** [comment]
btw: is it ok if I merge the above commit directly ? There are no changes, just rearrangemtn of methods. Not to mess with other stuff to do.

**Comment by larshp** [comment]
feel free to commit directly to master

**Comment by sbcgua** [comment]
Half way there 

![2016-10-05 23h15_44](https://cloud.githubusercontent.com/assets/15635498/19130053/54099416-8b52-11e6-9b55-b49dbb53ecc7.gif)

**Comment by larshp** [comment]
hmm, above does not look like "separate folders by object type"?

If displaying only the current folder content, then how will the user know which files have changed? I.e. `git status` only works for current folder?

**Comment by sbcgua** [comment]
> hmm, above does not look like "separate folders by object type"?

yes, that's a bit misleading. But actually, we've talked about subpackages as folder above (7 Jul) :)
Anyway, to write folders per type I needed folder mechanism itself. And it was simpler to write it for subpackages. So actually both features will be implemented at once. 

Yet planned:
- finish with online (does not work now)
- showing number of changes in subfolders (this answers your 2nd question) and potentially fixing diff so that it can show all changes at once
- actually grouping by type (see a question below)
- feature in table menu to disable all of this and show all files at once if someone needs
- some finetunings probably

Tricky questions:
- if the repo has starting dir (like src in abapGit) should the first render go to to that dir ? Tech files like `.abapgit` will be above and will not be seen immediately (need to press ..). How to show their changes (see also next question).
- Should we show changes in ".." ? Having the above question - probably yes. But is it "all other changes in the repo", "changes of top level non-object files" or "changes in all folders **above**" ? Doubts.
- Folders by type ... I think for now I'll make it as a dynamic feature - so you can group current view by type but that is not reflected in file structure. After we'll need to make some button to actually reorg files by type and commit it to the repo. These are actually 2 unrelated features, not sure how they should work together. What do you think ?

**Comment by sbcgua** [comment]
`status` works for all. Then filtered by `lcl_repo_content_browser` ebfore diplaying. `lcl_repo_content_browser` actually replaces former `extract_repo_items` in page_main

**Comment by larshp** [comment]
subpackages as folders is currently implemented in abapGit

when doing `git stauts` using command line git, it shows all the modified files in a list, it is the same approach currently in abapGit. I do not see any benefit of showing changed files per folder. Currently we have 2 different views on the main screen for files, having 3 different I think is a lot to maintain.

**Comment by larshp** [comment]
Folders by type:

I see it something like this:

https://github.com/larshp/abapGit/blob/master/src/zabapgit_repo_impl.prog.abap#L419

```abap
IF folders_by_type_is_enabled.
  <ls_file>-path = mo_dot_abapgit->get_starting_folder( ) && <ls_tadir>-path && '/' && <ls_tadir>-object.
ELSE.
  <ls_file>-path = mo_dot_abapgit->get_starting_folder( ) && <ls_tadir>-path.
ENDIF.
```
and some code to remove the extra folder when doing deserialization

A user can enable the feature by setting in .abapgit.xml file, after enabling the user does staging, where the old files can be removed and new files added. I dont think an extra button is needed, just reuse the existing functionality should be okay.

**Comment by sbcgua** [comment]
> subpackages as folders is currently implemented in abapGit

Yes, I'm not changing that, but it not displayed anyhow other then part of file path currently. 

> when doing git stauts using command line git, it shows all the modified files in a list, it is the same approach currently in abapGit. I do not see any benefit of showing changed files per folder. 

Sorry didn't understand what you mean.

> Currently we have 2 different views on the main screen for files, having 3 different I think is a lot to maintain.

Also not quite sure what you mean. Is it about hiding files ? But this is not related to grouping.

**Comment by larshp** [comment]
Lets open a new issue for changing the way files are shown in the overview page. And keep this issue for separating the objects into folders by object types.

https://github.com/larshp/abapGit/issues/371

**Comment by larshp** [comment]
Conversion, I have added 
```abap
<ls_file>-path = <ls_file>-path && <ls_tadir>-object && '/'.
```
from above in my local copy of abapGit. And click stage, thenn it shows all files.

If the user clicks "add" for all local files, and "remove" for all remote files. The files in the repository will have a folder for each object type

![image](https://cloud.githubusercontent.com/assets/5888506/19148877/286a5fb2-8bbf-11e6-8bb2-f11afa14f227.png)

**Comment by sbcgua** [comment]
an old issue ... :) Currently I'd close it. If we do some kind of filtering at header level this would have the same (even more flexible) effect

**Comment by larshp** [comment]
closing
