### ISSUE TITLE
7.31 system  - method "XSDBOOL" is unknown, PROTECTED or PRIVATE

### ISSUE THREAD

**Issue by stubbini** [larshp/abapGit#2802]
Just imported the latest build to a 7.31 system and have this error on line 34654.

![image](https://user-images.githubusercontent.com/32145310/61454587-36ea0280-a959-11e9-9d44-558e7dae9847.png)

![image](https://user-images.githubusercontent.com/32145310/61454617-48330f00-a959-11e9-8cec-81e535189311.png)

**Comment by larshp** [comment]
yea, should be changed to `boolc`

**Comment by larshp** [comment]
@stubbini thanks for the bug report, try again, latest version

**Comment by stubbini** [comment]
Thanks for the quick turnaround guys. Works on a different 731 system to that tested yesterday (original sandbox is down).
