### ISSUE TITLE
Stage page: Change link 'Add all and commit' to commit filtered files only

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2805]
TODO screenshot

People sometimes misinterpret this link and think this will commit the files they filtered. 

In a multi-developer environment, this is annoying because other people can't find their files and they have to figure out what happened and go to an external tool to undo the commit. Rewriting history also has the side effects of duplicating linked commits in JIRA, which you can't unlink. Or you have to do some intermediate commit where you remove the accidental changes back.

This would be solved if the button changed to `add filtered and commit` when you filter files.

**Comment by larshp** [comment]
or one button where the description changes if there is a filter applied?

**Comment by FreHu** [comment]
You lose the option to commit everything, but then again, you filtered so I guess you weren't going to do 
that anyway. It is actually simpler to have one button, I'll change the description.

**Comment by FreHu** [comment]
This was improved already.
