### ISSUE TITLE
zcl_abapgit_html->co_span_link_hint refactoring

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2807]
@larshp @christianguenter2 
A small suggestion to optimize html. Is the subj span needed ? It seems to be always empty and clutter html a bit e.g. 

```html
<td class="object"><a href="sapevent:jump?TYPE=FUGR&NAME=ZTHREADS">ZTHREADS<span class="tooltiptext hidden"></span></a> </td>
```

Also according to the code 
https://github.com/larshp/abapGit/blob/master/src/ui/core/zcl_abapgit_html.clas.abap#L124
https://github.com/larshp/abapGit/blob/master/src/ui/core/zcl_abapgit_html.clas.abap#L183

```abap
CONSTANTS: co_span_link_hint TYPE string VALUE `<span class="tooltiptext hidden"></span>`.
...
rv_str = |<a{ lv_id }{ lv_class }{ lv_href }{ lv_click }{ lv_style }>{ iv_txt }{ co_span_link_hint }</a>|.
...
    rv_html = |<input type="checkbox" id="{ iv_id }">|
           && |{ co_span_link_hint }|.
```

Would you mind if I remove it ?

**Comment by larshp** [comment]
try removing it 🚢

**Comment by sbcgua** [comment]
OK :+1:
Right after #2775 is merged then - it changes the same line in `add_a`

**Comment by christianguenter2** [comment]
The (pseudo-)span is needed for the link hint navigation. 

![image](https://user-images.githubusercontent.com/17437789/61773186-55864880-adf4-11e9-9dee-184936391f1d.png)

https://github.com/larshp/abapGit/blob/d10d922c067959ca425a687f124a317b8c5a751a/src/ui/zabapgit_js_common.w3mi.data.js#L733

Maybe there's a better way to do that? 
I'm most likely the only one using this feature, but I rely heavily on this ;-).

**Comment by larshp** [comment]
perhaps rename it to "hotkeytext" to better reflect what it is used for?

**Comment by sbcgua** [comment]
Ah, I see ... and I scanned the abap code, didn't find any good mentions and so wondered why it was needed :)
I'll try have a look on it.

**Comment by sbcgua** [comment]
... first guess - if it relays on JS anyway then it can be done completely dynamic
