### ISSUE TITLE
Empty name if repository URL has a trailing /

### ISSUE THREAD

**Issue by oliver-goetz** [larshp/abapGit#2808]
If the repository URL of an Online Repository ends with a **/** and no optional "Display name" is provided, it is created with an empty name.
In this case the repository appears in _Repository overview_, but not in the _Favorites bar_. Thus, it cannot be changed anymore.

![abapGit-favorites-emtpy-name](https://user-images.githubusercontent.com/47362717/61794166-d6f3d000-ae20-11e9-9256-c886f3854cb7.jpg)

![abapGit-empty-name](https://user-images.githubusercontent.com/47362717/61793931-664cb380-ae20-11e9-8dee-cfc4cbe08f91.jpg)

**Comment by larshp** [comment]
thanks

as a workaround, under Advanced -> Database Util, you can change the display name without the ui,
![image](https://user-images.githubusercontent.com/5888506/61795875-a6ae3080-ae24-11e9-971d-ab7365b341d7.png)

![image](https://user-images.githubusercontent.com/5888506/61795856-9c8c3200-ae24-11e9-89f9-cf82aae7dfff.png)

**Comment by larshp** [comment]
issue reproduced

**Comment by larshp** [comment]
@oliver-goetz try again, latest version
