### ISSUE TITLE
Refactoring of ZCL_ABAPGIT_ENVIRONMENT

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#2810]
Currently the class ZCL_ABAPGIT_ENVIRONMENT is defined as static class, which does not allow to mock this dependency in many unit tests. For that reason a refactoring is needed.

**Comment by ThomasPloski** [comment]
https://github.com/larshp/abapGit/pull/2809

**Comment by ThomasPloski** [comment]
#2826

**Comment by larshp** [comment]
merged in https://github.com/larshp/abapGit/pull/2826, closing
