### ISSUE TITLE
Improve object handler for CDS metadata extension (DDLX)

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#2815]
The existing object handler for CDS metadata extension (DDLX) has been reviewed by an expert.  
Doing this, the following feedback has been provided:
- enable existing logging capability
- include environment specific logic (e.g. import of an inactive version)
- improve exception handling so that the related object information can be displayed in log
- assign package information to handle abap language version in a proper way
- adapt lock object

**Comment by ThomasPloski** [comment]
fixed by #2816

**Comment by FreHu** [comment]
@ThomasPloski  small tip - if you write fixes/resolves #[issue_number] in your PR, it will close the issue automatically when the PR is merged.
