### ISSUE TITLE
UI usability: main screen, long file list

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#283]
With a lot of objects/files, the list is not very user friendly. 

Show folders? Skip the file list? Only show changed files? Something else?

see also https://github.com/larshp/abapGit/issues/280

**Comment by larshp** [comment]
Suggestion: only show one repo at a time and use the breadcrumb for switching

Currently the long file list is annoying when I need to go to a repo below to unhide, only showing one repo would get rid of the need for scrolling. Also the diff links are now also shown on the staging page

**Comment by sbcgua** [comment]
Good idea. toc-menu can indicate current repo with bold format.
Side question: when repo is syncronized ? At start or at display ? Imho at display should be better.
Folder can be also shown, potentially fold/unfold with JS not to re-render each time

**Comment by larshp** [comment]
synchronized = refreshed? at display/when switching repo is a good idea

Folders: we can add this later in separate issue

This approach will:
- Get rid of the "Refresh all" feature
- Get rid of the "hide/show" feature
- will move the error log up to before the files, so all important information is shown at the top of the page

**Comment by larshp** [comment]
starting implementation
