### ISSUE TITLE
Files for object CLAS ZCL_ABAPGIT_GUI_CSS_PROCESSOR are not placed in the same folder

### ISSUE THREAD

**Issue by petrhos** [larshp/abapGit#2830]
Hi, 

I got this message after a pull.
I have done a reset localy and then I had to build the two classes manualy (due to dumps on opening):
- ZCL_ABAPGIT_GUI_CSS_PROCESSOR
- ZCL_ABAPGIT_UI_FACTORY
 
Files for object CLAS ZCL_ABAPGIT_GUI_CSS_PROCESSOR are not placed in the same folder 
Files for object CLAS ZCL_ABAPGIT_GUI_CSS_PROCESSOR are not placed in the same folder 
Files for object CLAS ZCL_ABAPGIT_GUI_CSS_PROCESSOR are not placed in the same folder 
Package and path does not match for object, CLAS ZCL_ABAPGIT_GUI_CSS_PROCESSOR 
Package and path does not match for object, CLAS ZCL_ABAPGIT_GUI_CSS_PROCESSOR 
Package and path does not match for object, CLAS ZCL_ABAPGIT_GUI_CSS_PROCESSOR 
Multiple files with same filename, zcl_abapgit_gui_css_processor.clas.abap 
Multiple files with same filename, zcl_abapgit_gui_css_processor.clas.testclasses.abap 
Multiple files with same filename, zcl_abapgit_gui_css_processor.clas.xml 

Thanks

**Comment by larshp** [comment]
do Advanced -> Reset Local

if everything fails, delete the classes and reinstall

**Comment by petrhos** [comment]
If I delete the class(es) I get a dump opening ABAPGIT:

> Short Text
    Syntax error in program "ZABAPGIT".
What happened?
    Error in the ABAP application program.
    The current ABAP program "????????????????????????????????????????" had to be
     terminated because it found a
    statement that could not be executed.
    In include "ZABAPGIT_FORMS ", in line 29 of program
     "ZABAPGIT                                ", the following syntax errors
    have occurred:
    The type "ZCL_ABAPGIT_UI_FACTORY" is unknown.

**Comment by larshp** [comment]
install the report as ZABAPGIT_FULL and run it to update the classes, https://docs.abapgit.org/guide-install.html

**Comment by petrhos** [comment]
Solved.

1 - Opened the ZABAPGIT_FULL replaced the code with the one placed here: 
https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap 

2 - Opened the ZABAPGIT_FULL, during the pull I allowed to remove the class(es). 

3 - In the report ZABAPGIT_FULL, I made a new pull from the report and situation got solved.

Thanks for your help @larshp

**Comment by larshp** [comment]
cool, closing
