### ISSUE TITLE
$ABAPGIT error reading parent package

### ISSUE THREAD

**Issue by VishnAndr** [larshp/abapGit#284]
While trying to pull current version I'm getting following error:
"error reading parent package".

It comes after the call of cl_package_factory=>load_package because of sy-subrc = 1 which means object_not_existing. It's strange because it's trying to load $ABAPGIT.

I wondered what's wrong - check the package which is ZABAPGIT report should belong to. And has been surprised that it actually does not exist. Deleted during pull?

**Comment by VishnAndr** [comment]
Recreation of $ABAPGIT package fixed the issue.

**Comment by larshp** [comment]
I do not think there is any code implemented that can delete packages.

Though I have experienced a similar problem on a system that was recently upgraded to 750, so I concluded it was due to the upgrade. Have you recently upgraded the system? What SAP_BASIS version is it running?

**Comment by VishnAndr** [comment]
Exactly! After an upgrade to 750 it seems that all $* (except $TMP and some standard $*) packages are gone. Along with my developer key )))))) For example, the same happened to $AOC package :)
Now it's fixed. Closing the issue.

**Comment by larshp** [comment]
I think I created the deleted $ABAPGIT package manually before the upgrade, outside of abapGit. So this currently looks like a SAP standard issue, I tried searching for a note on it but without any luck.

**Comment by VishnAndr** [comment]
Let's live with that for now. Just another "under the hood" trick from SAP :)

**Comment by larshp** [comment]
another upgrade, this happened again

**Comment by flaiker** [comment]
Maybe T-packages work better (i. e. `TABAPGIT`)?

**Comment by larshp** [comment]
T packages?

**Comment by flaiker** [comment]
Can't find the documentation on them but if I remember correctly packages starting with the letter T automatically are not transported / not assigned a transport layer and LOCAL. So just like temp packages with $ as the prefix but semantically they are meant for development objects that are neither temporary nor designated for production, dev-system only objects.
I think they are mentioned in the DSAG guidelines.

**Comment by MDJoerg** [comment]
.... another upgrade and this happened again. S4HANA 1809 to 1909. OSS ticket opened.

**Comment by christianguenter2** [comment]
and another upgrade and this happend again. S4HANA 1709 to 1909...

@MDJoerg any news regarding your OSS ticket?

**Comment by larshp** [comment]
back when I experienced the issue, it also happend to not abapGit specific local packages.
