### ISSUE TITLE
Show warning when using non Windows SAPGUI

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2840]
#2769

**Comment by christianguenter2** [comment]
Maybe we can use `GUI_HAS_ACTIVEX` to detect Windows SAPGUI.

**Comment by larshp** [comment]
hmm, I would disable everything activeX if its possible

perhaps `CL_GUI_FRONTEND_SERVICES=>GET_PLATFORM` instead?

**Comment by christianguenter2** [comment]
Yeah `CL_GUI_FRONTEND_SERVICES=>GET_PLATFORM` looks more promising.

**Comment by flaiker** [comment]
You can also use Java GUI on Windows so get_platform probably does not help.

There's FM `GUI_HAS_JAVABEANS` to check for Java GUI and `GUI_IS_ITS` for Web GUI I think.

**Comment by flaiker** [comment]
Merged with #2841
