### ISSUE TITLE
AbapGit Export: Changing /FOOBAR/ namespace to Z

### ISSUE THREAD

**Issue by fecanin-ivan** [larshp/abapGit#2842]
Hallo.

I'd like to export(zip) my developed objects from SAP with special namespace /xxxx/ 
and import them to  SAP with Z. 
Objects should be accorgingly renamed.
Could you advise me, how to do it?

Ivan

**Comment by larshp** [comment]
not a feature in abapGit

you can try https://github.com/mnemotron/ABAPSpace, or alternatively do it manually
