### ISSUE TITLE
ASSERTION_FAILED ZIF_ABAPGIT_SAP_PACKAGE~READ_PARENT

### ISSUE THREAD

**Issue by bmaciag** [larshp/abapGit#2843]
Getting the following dump:
```
ASSERTION_FAILED
ZIF_ABAPGIT_SAP_PACKAGE~READ_PARENT
```

In this method:
```
  METHOD zif_abapgit_sap_package~read_parent.

    SELECT SINGLE parentcl FROM tdevc INTO rv_parentcl
      WHERE devclass = mv_package.        "#EC CI_SUBRC "#EC CI_GENBUFF
    ASSERT sy-subrc = 0.

  ENDMETHOD.
```

SAP_BASIS	740

**Comment by larshp** [comment]
what is the value of `mv_package`, and if it is not blank does it exist in the system?

**Comment by bmaciag** [comment]
It was not existing in the system, I created the package and now its fine.
But the issue here is rather for the general workflow of the report:
It should not dump and display a error instead maybe.

**Comment by larshp** [comment]
In my opinion this is a bug in the standard system, packages with a parent package that does not exist should not be possible.

I think its okay to dump for scenarios that should not exist

**Comment by bmaciag** [comment]
Okay. Will close the issue. Thx for the fast reply.

**Comment by larshp** [comment]
was this a local "$" package, and did you recently upgrade the system? I've previously experienced that upgrades removed some of the local packages

**Comment by bmaciag** [comment]
No, was not local. But the system was updated recently.
