### ISSUE TITLE
Reset local doesn't ask if it should restore deleted classes

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2845]
Steps to reproduce (1.88):

- make a new repo with two classes, commit all
- remove class 1 on system
- modify class 2 on system
- add class 3 on system
- Reset local

Result:
- I'm asked whether I want to delete the added class
- I'm asked whether I want to undo the modified class
- The deleted class gets recreated without asking

This means if there are uncommitted deletions, reset local will have unintended side effects.

**Comment by mbtools** [comment]
I tested this and it works properly asking if object 3 should be deleted (v1.95). Is this still a problem?

**Comment by FreHu** [comment]
Still reproducible - see how `zcl_turtle_math` gets recreated here without asking.

![](https://user-images.githubusercontent.com/5097067/82807030-44c8b800-9e87-11ea-90bf-8bdf9703052c.gif)

**Comment by mbtools** [comment]
You didn't select the checkbox in the delete popup. So the class remains. Or am I not understanding it right?

In my view, if you run "reset local" and then click "select all" on all popup, then you should get an exact copy of remote.

**Comment by FreHu** [comment]
The delete popup is about `zcl_turtle_test`, the newly added class. But I'm not given a chance to decide whant to do about `zcl_turtle_math`, it is just restored without asking.

**Comment by mbtools** [comment]
the clip was fast. ok, now I see that at the end zcl_turle_math appears at the bottom.

**Comment by mbtools** [comment]
I tracked it down. The following line needs to be removed
ZCL_ABAPGIT_OBJECTS->WARNING_OVERWRITE_FIND
*          AND <ls_result>-lstate <> zif_abapgit_definitions=>c_state-deleted

The deleted obj will be in the popup. We should adjust the text a bit:

"The following objects have been modified/deleted locally.  Select the objects which should be overwritten/recreated."

Give it a try

**Comment by FreHu** [comment]
Seems to work. Do you want to PR this or should I?
