### ISSUE TITLE
Add order by function to repo page

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2852]
Follow up #2778

I find the new sorting on the repo page a bit confusing. I'd suggest to add a order byfunction to sort by column and ascending or descending.
Maybe similar to the repo list?
![image](https://user-images.githubusercontent.com/17437789/62633220-1697dd00-b934-11e9-8c80-ed2b8e64d011.png)

**Comment by larshp** [comment]
hmm, what is your workflow? I rarely check what is in the list

**Comment by christianguenter2** [comment]
On some occasions I use abapGit as poor man's IDE. Which means that I do open my objects from there. Therefore order by object type would be more convenient to me.

**Comment by FreHu** [comment]
For that use case, searching would also be useful assuming you use SE80. For an Eclipse workflow, Ctr+Shift+A is still probably more convenient as you don't have to switch windows.
