### ISSUE TITLE
ABAPGit with private repository

### ISSUE THREAD

**Issue by DennstedtB** [larshp/abapGit#2879]
Hi, 

is it possible to use abapgit online projects with private Github repositories? unfortunately i am currently not able to test it. ( my current company does not want to install the needed certificate ). 

Want to set up github as our first place for code reviewing and versioning, therefor it would be perfect if we can use it directly with online projects.

**Comment by larshp** [comment]
yes, it works

**Comment by gregorwolf** [comment]
And I would suggest installing a ABAP developer edition so you can test such things on your own. Don't be dependent on others :-).

**Comment by christianguenter2** [comment]
It's quite unusual that companys allow to connect their SAP ABAP systems to public GitHub. So my guess is that the missing certificates aren't the only problem. 
Therefore maybe you can (re)use an internal git server? Or even set up your own? GitLab and abapGitServer are open source ;-)

**Comment by plato79** [comment]
What if the place to put the repos are not in **github.com** but in an **github enterprise server**? AFAIS the login methods are different ( enterprise server is redirects to company login page ) and **github.com** is hardcoded in ABAPGIT

**Comment by larshp** [comment]
@plato79 I assume you are thinking about 2FA?

In ZCL_ABAPGIT_2FA_GITHUB_AUTH note the IV_OVERRIDE parameter which you can use in custom subclasses.

just subclass the BASE 2FA class, and they are found dynamically
https://github.com/larshp/abapGit/blob/5018eae46cbc559ede07ba7ef6ce1569ca691a65/src/http/zcl_abapgit_2fa_auth_registry.clas.abap#L66

**Comment by larshp** [comment]
If you are thinking about SAML, the workaround is to add an outside collaborator with a token

And then its possible to set this user + token, which just grants everybody access,

```abap
  METHOD zif_abapgit_exit~http_client.

    IF iv_url CP 'https://enterprisegithub'.
      ii_client->request->set_header_field(
        name  = 'authorization'
        value = '' ).

      ii_client->authenticate(
        username = 'username'
        password = 'token' ).
    ENDIF.

  ENDMETHOD.
```

**Comment by EduardoCopat** [comment]
I used to have repos in the enterprise server and they worked OK. Maybe you will need a proxy.

**Comment by plato79** [comment]
You could see what I mean by visiting this address:  
https://git.daimler.com
It opens company's WhoIsWho enterprise login page, and if it authorizes you it goes back to the git.daimler.com.

**Comment by gregorwolf** [comment]
This is a classic SAML authentication which works fine when the client is a browser. Have you checked how the command line Git client handles this? Does it pop-up with a browser let you authenticate and then use this session? Because then you would have an option via exports from abapGit to a local directory.

**Comment by plato79** [comment]
Well it doesn't work like that it seems..

On an external computer it tries to connect but unable to do it:

```
Looking up git.daimler.com ... done.
Connecting to git.daimler.com (port 9418) ... fatal: unable to connect to git.daimler.com:
git.daimler.com[0: 141.113.0.105]: errno=Operation timed out
```

On a computer within the domain it pops up a basic authentication prompt, entering domain user/password doesn't work.. If you cancel it it asks the same information on command line, again domain user/password doesn't work.. If you try to login with domain user/password it gives this information:

```
remote: Password authentication is not available for Git operations.
remote: You must use a personal access token or SSH key.
remote: See https://git.daimler.com/settings/tokens or https://git.daimler.com/settings/ssh
fatal: unable to access 'https://git.daimler.com/#######/######/': The requested URL returned error: 403
```

With a generated token though git command line clones repo without problem **but only for a computer within the domain**. With a computer over internet it gives this error:

```
Looking up ####@git.daimler.com ... fatal: Unable to look up ###@git.daimler.com (port 9418) (nodename nor servname provided, or not known)
```

I want to access git.daimler.com via abapgit, but without a manual token authorization it doesn't seem likely.. Our SAP systems are within domain but I'm not sure if they'll be recognized like our computers, some servers are using SNC but again I'm not sure if that'll be enough, or even if it is then what will happen for servers not using SNC?

**Comment by gregorwolf** [comment]
I would suggest opening an internal support ticket for the git service and asking them.

**Comment by DennstedtB** [comment]
@plato79 no problem ;) 

Thanks everyone, I think I've got an idea how to solve this.

**Comment by DennstedtB** [comment]
If I have a solution which is applicable for everyone I'll create a PR for this.
