### ISSUE TITLE
abapGit update on Gateway system

### ISSUE THREAD

**Issue by Sdfraga** [larshp/abapGit#2888]
Hi,

I've just updated several systems with version 1.89.9 and I have some differences in files ABAPGIT an ABAPGIT_PARALLEL just in 2 my Gateway systems.

![image](https://user-images.githubusercontent.com/16186872/63465657-fef74300-c461-11e9-9745-435b16c73215.png)

![image](https://user-images.githubusercontent.com/16186872/63465791-4382de80-c462-11e9-9f15-35439f769132.png)

![image](https://user-images.githubusercontent.com/16186872/63465856-60b7ad00-c462-11e9-81f8-c884eb145f77.png)

The differences are both in the tag <I18N_TPOOL>. 
I18N are the files responsible for translations in Fiori Apps. Seems like abapGit is serializing the files locally with this extra metadata because it's running on a Gateway environment. 

In all other systems, and I have several, I don't have any difference in my staging area.

Does anyone has the same differences?

**Comment by larshp** [comment]
have not seen it, but guess its due to some system settings regarding translation, we have multiple open issues regarding translation, which will help moving this issue in the right direction

**Comment by christianguenter2** [comment]
Btw. 

`<LANGUAGE>3</LANGUAGE>`   

is korean. Does your gateway system has anything todo with korean?

![image](https://user-images.githubusercontent.com/17437789/63498400-19630800-c4c6-11e9-9019-fecfcdbf6831.png)

**Comment by Sdfraga** [comment]
Hum, yes!
We've recently installed Korean language in the Gateway for translations...

**Comment by sbcgua** [comment]
I've seen such an issue before, though without deep understanding of it. Seems like when you activate a new language the system tries to create translation for everything, if it is not available already it takes master language. At least this was the result I had.

The #2539 is addressing it in the long term. One of the ideas is to explicitly define list of serialized languages for a package.

As far as I know there is no workaround at the moment - I just ended up committing unnecessary languages (for my packages).

**Comment by Sdfraga** [comment]
Thank you for all the input.
Well if it is already being tracked let's close this one no?

**Comment by larshp** [comment]
yea, closing
