### ISSUE TITLE
Object type ignored, not supported: IAXU

### ISSUE THREAD

**Issue by mariusraht2** [larshp/abapGit#2889]
We have some ITS-related Subscreens with object type IAXU. The object type is not supported yet. The Subscreens are generated and can be modified by the developer. Due to one help document in the SAP Knowledge Base I found out that the object type belongs to ITS-related XML Tem­plates for HTML Templates ([https://help.sap.com/doc/207604dbeab848379211dc1b6d6ba525/LATEST/en-US/Deletable_Objects.pdf](https://help.sap.com/doc/207604dbeab848379211dc1b6d6ba525/LATEST/en-US/Deletable_Objects.pdf)).

**Comment by d023604** [comment]
IAXU ->ITS - XML Templates for HTML Templates
Transport relevant tables are IACXU, IACXUT and IACXU_C1 . 
CL_W3_API_OBJECT might provide some insights. 
Note IACXU_C1 stores the contents of the templates as raw strings

**Comment by larshp** [comment]
@CASAG-MariusRaht are you looking into / working on this issue ? https://github.com/CASAG-MariusRaht/abapGit/tree/fix_2889

**Comment by CASAG-MariusRaht** [comment]
@larshp Currently not, I'll try to come back to this issue next week.

**Comment by larshp** [comment]
no problem, just trying to make sure nobody does double work

**Comment by mariusraht2** [comment]
Solved.
