### ISSUE TITLE
The data object "LS_ENDPOINT" has no component called "ENDPOINTNAME"

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#289]
Latest version does not compile :(

lcl_object_webi->handle_endpoint

![image](https://cloud.githubusercontent.com/assets/15635498/16707811/c317e442-45e4-11e6-8bab-cac64f8755cd.png)

**Comment by larshp** [comment]
Just comment it out as a temporary fix, will look into it on monday

Wrote the code on 750, so that version is not affected

**Comment by sbcgua** [comment]
OK, another issues is in handle_soap method:

"A logical expression may not consist of just a method call."

```abap
    IF mi_vi->has_soap_extension_virtinfc( sews_c_vif_version-active ).
      RETURN.
    ENDIF.
```
