### ISSUE TITLE
abapGit install via oData supported?

### ISSUE THREAD

**Issue by chungseunghwan** [larshp/abapGit#2901]
Thought it'd be great if we run abapGit installation through an oData URI call, instead of going through the gui program.

Is abapGit install functionality via oData supported? or any plans?

**Comment by larshp** [comment]
install of abapGit itself, or using abapGit to install a repo?

**Comment by chungseunghwan** [comment]
using abapGit to install a repo

**Comment by sbcgua** [comment]
Not sure if this helps, but I made a node.js script which installs AG remotely via adt (abap-adt-api libarary)
Maybe helpful: https://github.com/sbcgua/sap-nw-abap-vagrant/tree/master/abapdeploy.js

**Comment by sbcgua** [comment]
Ah you mean not the abapgit itself but the repo inside abapgit. Sorry, please skip the comment then

**Comment by larshp** [comment]
Currently not supported, however:
a: the API for pull is described at https://docs.abapgit.org/development/api.html
b: Long term I'd like to provide a REST interface, currently zero lines of code = https://github.com/abapGit/REST
c: https://github.com/abapGit/ADT_Backend will at some point in time support pull, its a REST interface but might require some investigation on what to call

**Comment by larshp** [comment]
some abapGit operations might be quite time consuming, so websockets might be a better fit than HTTP

**Comment by chungseunghwan** [comment]
> some abapGit operations might be quite time consuming, so websockets might be a better fit than HTTP

Got it. Thanks a lot.
