### ISSUE TITLE
Import zip doesn´t work

### ISSUE THREAD

**Issue by j-kopp** [larshp/abapGit#2903]
Hi, 

I´m trying to import a zip from Opensap. When I choose the zip-file, the result is displayed very fast, but the code is not imported. On the result page I can´t see a menu entry or a button to save the displayed result or something similar. 

What am I doing wrong?

Regards
Joerg

**Comment by christianguenter2** [comment]
There should be "Pull" like this.
![image](https://user-images.githubusercontent.com/17437789/64130179-ee7b8c80-cdc0-11e9-87dc-5988c72732c3.png)

**Comment by j-kopp** [comment]
Hi Christian,

I´ve already tried the "Pull" link. But then the error "Current login language DE does not match master language EN. Run 'Advanced > open in master language' ". When I do that, the next error "Please install the abap git repository" appears.  When I try that on the tutorial page, the error "HTTPS ARGUMENT_NOT_FOUND | STRUST/SSL Setup correct?" appears.

I don´t want to setup an online connection, at least not at the moment. Is there no other way to install the code from a zip file?

Regards
Joerg

**Comment by larshp** [comment]
logon the system in english

**Comment by j-kopp** [comment]
Hi Lars,

that worked.

Thank you very much.

Regards
Joerg

**Comment by larshp** [comment]
closing
