### ISSUE TITLE
multiple reset => overwrites local changes

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#291]
First time a repository is "reset local", there is a popup asking if local changes should be overwritten or not.

However, the 2nd time the function is called, the local changes are overwritten without the program asking.

I guess there is a similar problem when doing pulls, however it is more difficult to reproduce.

**Comment by larshp** [comment]
method warning_overwrite should return skipped objects
method deserialize should return skipped objects
pass skipped objects to build_local_checksums

**Comment by EduardoCopat** [comment]
I couldn't reproduce your issue, maybe I did something different:

Steps:

1. Open abapGit and pull repo
2. In a new window, edit a class of the repo, activate
3. Reset local changes (overwritten pop-up is shown)
4. In another window, change class again
5. Reset local changes:
5.1 Overwritten pop-up is shown (as contrary to issue descriptions)
5.2 Receives "SEO_CLASS_CREATE_COMPLETE" error

**Comment by larshp** [comment]
steps to reproduce(havent tried in a while):

1. Open abapGit and pull repo
2. In a new window, edit a class of the repo, activate
3. Open abapGit again
4. Reset local changes, click no to resetting object
5. Reset local changes => no yes/no popup appears, so the changes made in 2 is overwritten

**Comment by EduardoCopat** [comment]
@larshp Following these steps, the error does not happen. If you click `cancel` on the second pop-up, it is really cancelling.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/2248490/22183248/b8736e88-e0b9-11e6-8850-1e0f7ef183bd.gif)

**Comment by larshp** [comment]
tried again, looks like this has been fixed 😄  one down

**Comment by EduardoCopat** [comment]
@larshp Still, if the user follows the steps below, she gets an error. Well, I think that's a minor thing and acceptable.

**Comment by larshp** [comment]
tried again, got the "SEO_CLASS_CREATE_COMPLETE" error, but it was due to myself locking the object in a different session
