### ISSUE TITLE
Misleading error message: "Repository XXX alreay contains YYY"

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2914]
Considering this package structure and Z_MM_RELEASE is managed by abapGit.

![image](https://user-images.githubusercontent.com/17437789/64769229-3336be80-d54b-11e9-810f-35169a3cbbc0.png)

I think we could improve this error message.

![image](https://user-images.githubusercontent.com/17437789/64769231-3467eb80-d54b-11e9-9a81-63769abb55e4.png)

**Comment by larshp** [comment]
@g-back please add a comment in this issue, then I can assign it to you

**Comment by g-back** [comment]
ok!
