### ISSUE TITLE
Release engineering improvements and cleanups, auto tags

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#2916]
ref: #960

Made some tests on auto tag pushing here: https://github.com/sbcgua/ci-abap-versioning-test
I propose to integrate it into AG

The ideas is: if `zif_abapgit_version=>gc_abap_version` changes - publish a new tag

Along with this I'd propose a couple of cleanups for the current ci scripts:
- move ci scripts (name travis.sh and the new tag deployer) to ci dir
- adjust package.json
  - remove `pretest`
  - `test` = `npm run eslint && npm run lint`
  - remove `posttest`, instead move to `merge` script (`abapmerge ...`) - it is not a test step
  - remove `_disabled_posttest` (or it's used ? then rename it to `lint-merged`)
- consequently tune the travis script
  - re-use `npm run merge`
- optionally replace GITHUB_API_KEY with deployment_key - which is an SSH key to the specific repo (build). Well, just a suggestion, GITHUB_API_KEY give access to the whole account so kind of less secure.

**Comment by larshp** [comment]
when github actions goes into GA(november?) I'd probably like to move to that instead of travis

guess the key is required anyhow for pushing to https://github.com/abapGit/build ?

**Comment by sbcgua** [comment]
I agree with GA, but I'd separate this step to reduce complexity. Actually I'll try to dive into GA too.

Key: this is up to you :) Have a look at the repo I mentioned above - it uses the ssh deploy key. So you can add a new key to `build` repo and use it in another environment e.g. this one. But anyway it is optional, let's keep it as a separate step and only if you prefer.

**Comment by sbcgua** [comment]
🎉 

![image](https://user-images.githubusercontent.com/15635498/66290472-11312180-e8e8-11e9-9386-1dff539a8335.png)

![image](https://user-images.githubusercontent.com/15635498/66290460-0a0a1380-e8e8-11e9-9b2d-6c418086619f.png)

**Comment by larshp** [comment]
anything else needed to close this issue?

**Comment by sbcgua** [comment]
imho let's close
migration to GA can be a separate one
And I'd wait for the release ... after some hands on with GA I just got convinced in feeling that it is quite beta ...

**Comment by larshp** [comment]
agree and agree
