### ISSUE TITLE
Hash in new branch --> no overview

### ISSUE THREAD

**Issue by MAMKOC** [larshp/abapGit#2917]
If the branch name contain a hash, the overview is initial.

![image](https://user-images.githubusercontent.com/55314922/64909274-5c517d80-d70a-11e9-8cbd-8a3adf9451d6.png)

![image](https://user-images.githubusercontent.com/55314922/64909256-109ed400-d70a-11e9-814b-6ff316737299.png)

After delete the branch with hash, the overview shows the graphic:
![image](https://user-images.githubusercontent.com/55314922/64909324-f87b8480-d70a-11e9-9e96-c2e1991d283f.png)

**Comment by christianguenter2** [comment]
@MAMKOC 
Bug is fixed. Can you please try again the latest build?
