### ISSUE TITLE
The ASSERT condition was violated

### ISSUE THREAD

**Issue by a13marquez** [larshp/abapGit#292]
When I run the report It crashes and shows the following error in row 25418
 - The ASSERT condition was violated

**Comment by nununo** [comment]
I am getting the same exact error. This happens at line 25418 because table ZABAPGIT is empty.

**Comment by larshp** [comment]
thanks, I'll have a look, will most likely fix it within an hour or two

**Comment by larshp** [comment]
@a13marquez @nununo can you try again, make sure to get the latest version from http://larshp.github.io/abapGit/build/zabapgit.txt

thanks for the bug report :+1:

**Comment by nununo** [comment]
Hi Lars,

Thanks for you quick action.
Unfortunately the problem remains in v1.16.2...

At line 25418:
    IF mv_show IS INITIAL.
      READ TABLE lt_repos INTO lo_repo INDEX 1.
>>>      ASSERT sy-subrc = 0.

**Comment by larshp** [comment]
yeah, will try again :) my user has the mv_show set, so I fixed the wrong case(but also a possible dump)

**Comment by a13marquez** [comment]
Hi @larshp an thanks for your help but the same that happens to  @nununo happens to me

**Comment by larshp** [comment]
try again, new Version released :smile:

**Comment by a13marquez** [comment]
It works for me @larshp. Thanks a lot

**Comment by larshp** [comment]
cool, feel free to open a new issue if you find more bugs, or have any questions/comments/suggestions

closing issue

**Comment by nununo** [comment]
Perfect. It works now for me also. Thanks @larshp !
