### ISSUE TITLE
unknown file during commit if PROG contains "="

### ISSUE THREAD

**Issue by AndreasSchaller-STELACON** [larshp/abapGit#2923]
Hi Lars,

I try up commit a PROG (created from SAP Code Inspector in order to transport a check variant) containing a lot of "=". This character is converted to %3D.

in
ZCL_ABAPGIT_GUI_PAGE_STAGE->PROCESS_STAGE_LIST 
READ TABLE ms_files-local 
fails because names aren't matching.

**Comment by AndreasSchaller-STELACON** [comment]
Hi Lars,

after inserting cl_http_utility=>unescape_url it seems to work proper.

_zcl_abapgit_path=>split_file_location(
        EXPORTING
          iv_fullpath = <ls_item>-name
        IMPORTING
          ev_path     = ls_file-path
          ev_filename = ls_file-filename )._

      **ls_file-filename = cl_http_utility=>unescape_url(
                           escaped = ls_file-filename ).**

      _CASE <ls_item>-value.
        WHEN zcl_abapgit_stage=>c_method-add.
          READ TABLE ms_files-local ASSIGNING <ls_file>
            WITH KEY file-path     = ls_file-path
                     file-filename = ls_file-filename._

**Comment by larshp** [comment]
thanks for the bug report

also see https://blogs.sap.com/2015/08/02/upload-and-download-code-inspector-variants-via-xml/ it allows you to have readable files instead of the PROG variant

**Comment by ibnbr** [comment]
I made some tests. On ZCL_ABAPGIT_HTML_ACTION_UTILS-<GET_FIELD already have an workaround for this.
```abap
    IF iv_decode = abap_true.
* URL decode, not sure why some are decoded automatically
      REPLACE ALL OCCURRENCES OF '%3d' IN lv_value WITH '='.
    ENDIF.
```
I'll change this and zcl_abapgit_path=>split_file_location to use **cl_http_utility=>unescape_url** , and make more tests to send a PR.

**Comment by larshp** [comment]
@AndreasSchaller-STELACON can you help testing the change from https://github.com/larshp/abapGit/pull/2980 ?

**Comment by flaiker** [comment]
Somewhat related: #2448

**Comment by mbtools** [comment]
Fixed by https://github.com/larshp/abapGit/pull/3564.
