### ISSUE TITLE
Package Interfaces not yet supported?

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#293]
Hello,

Package Interfaces (PINF) objects are still not supported. 
When do you think this object type will be supported?

Thanks in advance,
Nuno

**Comment by larshp** [comment]
Not sure, it is a bit tricky. Packages corresopnd to folders in abapGit, the objects might be installed to a different package than the original.

Also the target system might not have the package checks activated.

So package interfaces might have to be handled in a special way, compared to other objects.

**Comment by nununo** [comment]
I see what you mean.

When you mean a special way... do you already have any ideas? Like adapting the existing object to whatever the new package name is?

Meanwhile, I'll keep copying them manually. Or do you suggest any other automated way?

Thanks

**Comment by larshp** [comment]
if the value of TADIR-DEVCLASS for the PINF is the same as the package. Eg. package name is "FOO", and the TADIR-DEVLCASS value for FOO package interface is "FOO". Then it might be possible to implement this as a normal object serialization with a few tricks. 

The filename should be fixed to eg. "package.pinf.xml", as the target package might not be the same as from the source system.

Also I guess if the package checks are not enabled in the target system, the object should not be imported. However it might also be possible to import it, as it might be ignored by the SAP code.

I'm quite busy with real work, so I dont know if/when I'll have time to look more into it.


few notes,
http://scn.sap.com/community/abap/blog/2012/07/22/abap-package-concept-part-4-how-to-perform-package-checks
SAP note 648898

**Comment by nununo** [comment]
Makes sense.

I think it would be a good addition. When you find the time of course. No stress.

Thanks!
Nuno

**Comment by larshp** [comment]
@nununo check the latest version

as this is new functionality there might be some bugs :smile: just open a new issue if you find bugs, also feel free to submit a pull request if you find a fix

**Comment by nununo** [comment]
Hi @larshp! Great! Thanks for such a quick action! I'll try it and will post an issue if I find it.
