### ISSUE TITLE
No log messages for local objects after pull

### ISSUE THREAD

**Issue by mfsap** [larshp/abapGit#2931]
In case a package contains objects that are are not part of the remote repository, the pull log contains messages like "Object <objname> (type <objtype>) only exists local; no import required". It is not necessary that messages for local object appears in the log. For pull requests, messages for the affected objects (objects to be imported) are sufficient.
Pull request in preparation...

**Comment by larshp** [comment]
guess this was fixed in https://github.com/larshp/abapGit/pull/2932 ?

**Comment by mfsap** [comment]
Yes, fixed with #2932. I'll close the issue...
