### ISSUE TITLE
Sapscript Form compare/blame difficult

### ISSUE THREAD

**Issue by openPhiL** [larshp/abapGit#2934]
Hi there. 
It is awesome that we can now track changes in SAPSCRIPT forms - this function does not exist in SAP Standard. But it is not perfect and I'd like to start a discussion how to improve that. 

So here is how a change somewhere in the Form looks like today: 
![image](https://user-images.githubusercontent.com/43743230/65862107-d1a98900-e36d-11e9-97e7-642c4a952ff0.png)

My biggest painpoint is the text is split into TDFORMAT and TDLINE. It is important for exact analysis and recovery, I don't want to change that. But how can we improve readability to easily know in what Section of what Window a text has been changed? 

My suggestion is to create a seperate "formatted" file besides the existing
-/src/ztestgitform.form.tdlines_en.xml
-/src/ztestgitform.form.xml
something like
-/src/ztestgitform.form.formatted_en.txt

where the form is displayed in human-readable-form. Maybe like that option here: 
![image](https://user-images.githubusercontent.com/43743230/65862314-47adf000-e36e-11e9-90c8-ff0a1b053e1e.png) 
![image](https://user-images.githubusercontent.com/43743230/65862837-5ea11200-e36f-11e9-8083-1f2f3ee58622.png)

or like the program RSTXSCRP is trying to do:
![image](https://user-images.githubusercontent.com/43743230/65862791-4b8e4200-e36f-11e9-81fa-6ff549ba7e68.png)

What would you think? 
best regards
PhiL

**Comment by larshp** [comment]
Yea, this is a problem, also for other object types

For "separate" file, we should make sure only to have the information once in git, no duplication or things might mess up.
We can change the file format to something a bit more readable, but it will still be an issue.

However, in the world of git there are a lot of possibilities, its possible to make a script that takes the raw XML and mirrors it into whatever format, and have that automatically committed to git via CI. Then the abapGit XML might be located under /src/ and readable under /readable/, and still show up in the pull requests.

I've also spent a bit of time on https://github.com/larshp/abap-transmogrify, which is intended to convert between the different formats, and provide readable/HTML output.
Another approach is loading the raw git into something like vscode, and have a custom editor(scoped for vscode september release) show it in readable format, and use it for reviewing.

**Comment by openPhiL** [comment]
> For "separate" file, we should make sure only to have the information once in git, no duplication or things might mess up.

That would mean either your existing logic has to be replaced to "look" nicer (which is a lot of work I assume) or to reuse your sapscript-extractor within the SAP system in a different "solution". I'm not a fan of both. 

> Then the abapGit XML might be located under /src/ and readable under /readable/, and still show up in the pull requests.

From "our" perspective, the idea with a new /readable tree sounds good - and is close to what I had in mind. I guess there are argument to have a readable version of an object close to the object and not in a separate root-tree though :D 

If I understand correctly, your transmogrify project is intended to run based on the existing extractor (xml) and is to be pipelined into our git-infrastructure? I personally would not "endorse" that, as it is another "solution" build on existing solutions that one has to maintain with knowledge that somebody must have here in the company. I would prefer to have that transmogrify-functionality within the ABAP-stack. (SAP even has some SAPSCRIPT2HTML function modules for example.  (haven't really tried ).

Do you not want that (as you stated with sentence 1 of your respone) or would you be open for an abap-based extractor even though that information from the object is duplicated in the /readable part. Maybe we can meet in the middle and write the transmogrify to be inputted with the RAW or XML and do not give it access to SAP itself?

**Comment by larshp** [comment]
closing, no progress
