### ISSUE TITLE
Inconsistency: repo buffer will not be invalidated after db fetch in advanced repository overview screen

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#2938]
Hi abapGit community,

I have faced an issue, which can be reproduced by the following steps:

1. Open two abapGit sessions (a) and (b)
Session a:
![image](https://user-images.githubusercontent.com/39330834/66027420-20d0f480-e4fb-11e9-9f89-5b66e34cf452.png)
Session b:
![image](https://user-images.githubusercontent.com/39330834/66027452-380fe200-e4fb-11e9-869a-bf82bb9f8ab1.png)

2. Link an new repository in session (a) 
Session a:
![image](https://user-images.githubusercontent.com/39330834/66028180-d5b7e100-e4fc-11e9-9ff4-4fd2c48ab34b.png)
Session b:
![image](https://user-images.githubusercontent.com/39330834/66027452-380fe200-e4fb-11e9-869a-bf82bb9f8ab1.png)

3. Click on Advanced --> Repository overview in session (b) -- an error with text "repo not found, get" occurs
![image](https://user-images.githubusercontent.com/39330834/66028313-229bb780-e4fd-11e9-8474-11393420001a.png)

Where does the exception is thrown?

````abap
 METHOD zif_abapgit_repo_srv~get.

    FIELD-SYMBOLS: <lo_list> LIKE LINE OF mt_list.

    IF mv_init = abap_false.
      refresh( ).
    ENDIF.

    LOOP AT mt_list ASSIGNING <lo_list>.
      IF <lo_list>->get_key( ) = iv_key.
        ro_repo = <lo_list>.
        RETURN.
      ENDIF.
    ENDLOOP.

    cx_abapgit_exception=>raise( 'repo not found, get' ).

  ENDMETHOD.
````

I would suggest the following solution to fix this upcoming issue:

1. Enhance the interface ZIF_ABAPGIT_REPO_SRV by a new method INVALIDATE_BUFFER. This method will set the instance attribute mv_init to abap_false.

````abap
METHOD ZIF_ABAPGIT_REPO_SRV~INVALIDATE_BUFFER.
    mv_init = abap_false.
ENDMETHOD.
````

2. Call this introduced method in method list of class  ZIF_ABAPGIT_PERSIST_REPO 

````abap
  METHOD zif_abapgit_persist_repo~list.

    DATA: lt_content TYPE zif_abapgit_persistence=>tt_content,
          ls_content LIKE LINE OF lt_content,
          ls_repo    LIKE LINE OF rt_repos.


    lt_content = mo_db->list_by_type( zcl_abapgit_persistence_db=>c_type_repo ).
    zcl_abapgit_repo_srv=>get_instance( )->invalidate_buffer( ).  

    LOOP AT lt_content INTO ls_content.
      MOVE-CORRESPONDING from_xml( ls_content-data_str ) TO ls_repo.
      IF ls_repo-local_settings-write_protected = abap_false AND
         zcl_abapgit_factory=>get_environment( )->is_repo_object_changes_allowed( ) = abap_false.
        ls_repo-local_settings-write_protected = abap_true.
      ENDIF.
      ls_repo-key = ls_content-value.
      INSERT ls_repo INTO TABLE rt_repos.
    ENDLOOP.

  ENDMETHOD.
````

Any other ideas? Or have I missed some side effects? 

Regards,
Thomas

**Comment by larshp** [comment]
Suggestion:
Keep the fix to ZCL_ABAPGIT_REPO_SRV, in GET if the repo is not found refresh( ) the data and try again

Background:
Currently ZCL_ABAPGIT_REPO_SRV calls the persistence layer, we want to keep the layering, ie. not have the persistence layer call the serivce layer. Also performance wise its difficult to say what the consequence of the current fix is, whereas possibility doing a refresh in GET in the error scenario is low impact

**Comment by larshp** [comment]
@ThomasPloski try again, latest version

**Comment by mbtools** [comment]
It works. Closing
