### ISSUE TITLE
Optimize Stage: Include removed objects?

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2944]
Some colleagues of mine find it confusing that the 'add all and commit' function doesn't include removed objects and therefore asking whether we can improve that. 

E.g.
a) include deletions
or
b) add a new function 'add and remove all and commit' (sounds a bit bulky, we can surely come up with a better description)

![image](https://user-images.githubusercontent.com/17437789/66266638-eda6a200-e827-11e9-8b79-41012657d4aa.png)

**Comment by larshp** [comment]
Perhaps "All changes and commit"

**Comment by sbcgua** [comment]
Imho it is not that straight forward. In the bottom section there are 2 kinds of files:
- those which were there before and deleted locally 
- and those which were missing before and added remotely

The latter are potential (and probable) "ignores". I think the code should analyse the status to differentiate both and auto commit just the 1st category

**Comment by flaiker** [comment]
Another approach would be to align the behavior with the commands in git, which people might be used to. So `git add -A` or `git commit -a` ? Interestingly `git commit -a` ignores new unstaged files while `git add -A` includes them.

And regarding the ignored files: that also is always very fiddly in CLI in my experience. I am not even sure what the behavior is (I recall having to explicitly stage files that were added to .gitignore to remove them from the repo).

Related: https://git-scm.com/docs/git-rm#_removing_files_that_have_disappeared_from_the_filesystem

Personally I just use the buttons in the column header to mass stage files and then review each diff to then unstage unrelated changes.

**Comment by sbcgua** [comment]
yeap, auto committing may be a bit fiddly here as well. because in cmd line you commit to the local repo and then sync it. So in case of newly added remote file you just cannot commit without checking out it first. And in abapgit you can ...

**Comment by FreHu** [comment]
Related: #2738
