### ISSUE TITLE
create branch -> change coding -> switch back to master -> error

### ISSUE THREAD

**Issue by rednose84** [larshp/abapGit#295]
When create a new branch and do a change in an Interface (additional optional paramter) ...activate all things fine... Push the code to remote repo 

Now switch back to master (without merge) the pull get an esxception that the package cannot created. I want to have the old inteface implementation ... Mayby i missunderstood something...

**Comment by larshp** [comment]
hi mr. Red,
can you paste a screenshot of the error here in the issue?

perhaps if you also can create a repository with the objects needed to reproduce the error? it sounds like just a dummy interface is needed.

**Comment by larshp** [comment]
@rednose84 can you help providing additional information?

**Comment by larshp** [comment]
closing issue, @rednose84 feel free to open a new issue with the same problem, please just provide more information(see above)
