### ISSUE TITLE
FUGR, consider clearing RSFDO-INDEX

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#2957]
see
https://github.com/larshp/abapGit/pull/2954/files#diff-f0757c1b6941d86ffda280b41b3add21

when adding a new parameter there is a large diff, guess the INDEX field can be cleared, as the sequence is in the file anyhow

**Comment by ibnbr** [comment]
Is it to always be cleared? or only clear it on comparison?

**Comment by larshp** [comment]
in progress by @ibnbr, https://github.com/larshp/abapGit/pull/2975

**Comment by larshp** [comment]
@ibnbr please add comment in this issue, then I can assign it to you

**Comment by ibnbr** [comment]
@larshp done.
