### ISSUE TITLE
MSAG Message Class - Not all languages are exported

### ISSUE THREAD

**Issue by TinSchu** [larshp/abapGit#2974]
In T100 table there are two entries EN and DE. EN is the main language.
ABAPGit exports the EN language only.

How all languages are exported?
Class: ZCL_ABAPGIT_OBJECT_MSAG in paket $ABAPGIT_OBJECTS
Thank you very much for support.

![T100A entry](https://user-images.githubusercontent.com/56536729/66739276-a7c58b80-ee70-11e9-8079-d7b71ae9b05e.png)
![T100 entries](https://user-images.githubusercontent.com/56536729/66739281-aa27e580-ee70-11e9-9a80-2c4c8f82f66d.png)
![XML export](https://user-images.githubusercontent.com/56536729/66739286-ac8a3f80-ee70-11e9-9716-a8090e5fbbc7.png)

**Comment by larshp** [comment]
currently not implemented, see https://github.com/larshp/abapGit/labels/translation regarding translations

**Comment by sbcgua** [comment]
MSAG does support translations
![image](https://user-images.githubusercontent.com/15635498/66893754-6f9c8500-eff7-11e9-997d-db7ec8e34edf.png)

The texts are serialized in `SERIALIZE_TEXTS` method. @TinSchu could you tell what is returned by this code ?
![image](https://user-images.githubusercontent.com/15635498/66893896-c6a25a00-eff7-11e9-94a8-81fbbe25da0b.png)

**Comment by TinSchu** [comment]
Thank you very much Alexander for feedback.
The  `SERIALIZE_TEXTS` method returns nothing. The reason is the select statements use the table **T100T**. But the texts in table **T100**.
See 
![Debugger-SERIALIZE_TEXTS_0](https://user-images.githubusercontent.com/56536729/66901368-dec9a780-effe-11e9-9a2c-b3d1b11506ca.png)

**Comment by sbcgua** [comment]
Ah, I see. So you don't have a translation for the name of the message class itlself. I think the quickest option here would be to add one. It will really solve the issue without change of code. 
Potentially we can `select distinct` from t100 ... but I have a feeling that it will have performance issues as such select will not use index and the table is quite large ... not sure if it will work properly

**Comment by TinSchu** [comment]
Hi Alex, thank you very much for your quick response.
That fix my issue!
After adding the 'DE' entry in table T100T all languages now exported.

![Table T100T after fix](https://user-images.githubusercontent.com/56536729/66985851-f61b9a00-f0bd-11e9-8cc3-5546fad063c5.png)
