### ISSUE TITLE
Not so easy installation

### ISSUE THREAD

**Issue by nomssi** [larshp/abapGit#2984]
Most SAP systems do not have a trusted connection to github, so the growing size of zabapgit.abap is a concern. The copy and paste process fails for 75K+ LOC in a Chrome browser window.

Can anyone describe a stable routine for this method to work well?
It might be useful to provide a zip-Version of zabapgit.abap.

**Comment by sbcgua** [comment]
I "save link as" the file and then open it is any viewer (notepad included). Works stably so far.

But yes, probably it worth mentioning directly in the readme as this is unobvious.

**Comment by larshp** [comment]
alternatively copy paste once, and install abapGit as offline using https://github.com/larshp/abapGit/archive/master.zip

**Comment by larshp** [comment]
@nomssi did the updated readme help? https://github.com/larshp/abapGit/blob/master/README.md

**Comment by nomssi** [comment]
yes, but let me nitpick: the browser problem is not in "displaying" but in "copy/paste".

**Comment by larshp** [comment]
@nomssi did the updated readme help? https://github.com/larshp/abapGit/blob/master/README.md

**Comment by nomssi** [comment]
As I said previously, it helped. But I would prefer a minor change:
_instead of_: browsers have issues displaying the file with 75k lines. 
_it should be_: browsers have issues to **copy/paste** a file with 75k lines.

**Comment by larshp** [comment]
PRs welcome 😄

**Comment by larshp** [comment]
no progress, closing
