### ISSUE TITLE
CL_WDR_CFG_ENHANCEMENT is not a BASIS object

### ISSUE THREAD

**Issue by sandraros** [larshp/abapGit#2989]
In issue #542 was added code in ZCL_ABAPGIT_OBJECT_ENHO which used the constant "cl_wdr_cfg_enhancement=>tooltype" but cl_wdr_cfg_enhancement belongs to SAP_UI component, not SAP_BASIS (#1826), so abapGit might not compile on Basis-only systems. 

```
      WHEN cl_wdr_cfg_enhancement=>tooltype.
        CREATE OBJECT ri_enho TYPE zcl_abapgit_object_enho_wdyc
          EXPORTING
            is_item  = ms_item
            io_files = mo_files.
```

Suggestion: no constant with value 'WDYCONF' found in SAP_BASIS, so just:

```
      WHEN 'WDYCONF'.
        CREATE OBJECT ri_enho TYPE zcl_abapgit_object_enho_wdyc
          ...
```

Note: as of today, all other objects used by abapGit belong to SAP_BASIS.
abapGit version: 1.90.0

XML version: v1.0.0

GUI version: 7500.2

LCL_TIME: 1571688223 +0200

SY time: 20191021 220343 3600

Supported objects: ACID, ASFC, AUTH, AVAS, CHAR, CLAS, CMPT, CUS0, CUS1, CUS2, DCLS, DDLS, DDLX, DEVC, DIAL, DOCT, DOCV, DOMA, DSYS, DTEL, ECAT, ECSD, ECSP, ECTC, ECTD, ECVO, ENHC, ENHO, ENHS, ENQU, ENSC, FORM, FUGR, G4BA, G4BS, IAMU, IARP, IASP, IATU, IDOC, IEXT, INTF, IWMO, IWOM, IWPR, IWSG, IWSV, JOBD, MSAG, NROB, PARA, PERS, PINF, PRAG, PROG, SAMC, SAPC, SCP1, SFBF, SFBS, SFPF, SFPI, SFSW, SHI3, SHI5, SHI8, SHLP, SHMA, SICF, SMIM, SMTG, SOTS, SPLO, SPRX, SQSC, SRFC, SSFO, SSST, STYL, SUCU, SUSC, SUSO, SXCI, TABL, TOBJ, TRAN, TTYP, TYPE, UCSA, UDMO, UENO, VCLS, VIEW, W3HT, W3MI, WAPA, WDYA, WDYN, WEBI, XINX, XSLT

Browser: Mozilla/5.0 (Windows NT 6.2; WOW64; Trident/7.0; managedpc; rv:11.0) like Gecko
Frontend time: Mon Oct 21 2019 22:03:56 GMT+0200 (Romance Daylight Time)

**Comment by larshp** [comment]
"might not compile", so is this an acutal problem on some of your systems?

**Comment by sandraros** [comment]
No issue at my side. It's just that following our discussion at #2987 to make abapGit SAP_BASIS-compatible, I have checked again, and found this potential issue.

**Comment by larshp** [comment]
I'm sure there are hundreds of potential issues in abapGit 😁

**Comment by sandraros** [comment]
"I propose you dispose"

**Comment by sandraros** [comment]
So, let's close it for now.
