### ISSUE TITLE
Short dump after clean install

### ISSUE THREAD

**Issue by senel** [larshp/abapGit#299]
After, clean install (no ABAP Git install before on this particular SAP), I'm getting short dump:

Error analysis
    An exception occurred that is explained in detail below.
    The exception, which is assigned to class 'CX_SY_DYNAMIC_OSQL_SEMANTICS', was
     not caught in
    procedure "READ" "(METHOD)", nor was it propagated by a RAISING clause.
    Since the caller of the procedure could not have anticipated that the
    exception would occur, the current program is terminated.
    The reason for the exception is:
    An Open SQL clause was specified dynamically. The contained field name
    "DATA_STR" does not exist in any of the database tables from the FROM clause.

Missing RAISING Clause in Interface
    Program                                 ZABAPGIT
    Include                                 ZABAPGIT
    Row                                     3.556
    Module type                             (METHOD)
    Module Name                             READ

Trigger Location of Exception
    Program                                 ZABAPGIT
    Include                                 ZABAPGIT
    Row                                     3.558
    Module type                             (METHOD)
    Module Name                             READ

Line  SourceCde

 3528
 3529     UPDATE (c_tabname) SET data_str = iv_data
 3530       WHERE type = iv_type
 3531       AND value = iv_value.
 3532     IF sy-subrc <> 0.
 3533       _raise 'DB update failed'.
 3534     ENDIF.
 3535
 3536   ENDMETHOD.
 3537
 3538   METHOD modify.
 3539
 3540     DATA: ls_content TYPE ty_content.
 3541
 3542     lock( iv_type  = iv_type
 3543           iv_value = iv_value ).
 3544
 3545     ls_content-type  = iv_type.
 3546     ls_content-value = iv_value.
 3547     ls_content-data_str = iv_data.
 3548
 3549     MODIFY (c_tabname) FROM ls_content.
 3550     IF sy-subrc <> 0.
 3551       _raise 'DB modify failed'.
 3552     ENDIF.
 3553
 3554   ENDMETHOD.
 3555
 3556   METHOD read.
 3557
>>>>>     SELECT SINGLE data_str FROM (c_tabname) INTO rv_data
 3559       WHERE type = iv_type
 3560       AND value = iv_value.                               "#EC CI_SUBRC
 3561     IF sy-subrc <> 0.
 3562       RAISE EXCEPTION TYPE lcx_not_found.
 3563     ENDIF.
 3564
 3565   ENDMETHOD.
 3566
 3567 ENDCLASS.
 3568
 3569 CLASS lcl_persistence_repo IMPLEMENTATION.
 3570
 3571   METHOD add.
 3572
 3573     DATA: ls_repo        TYPE ty_repo,
 3574           lv_repo_as_xml TYPE string.
 3575
 3576
 3577     ls_repo-url          = iv_url.

**Comment by larshp** [comment]
Hi,
For a short while the implementation had code that created a field 'DATA' in table ZABAPGIT, however field name 'DATA' is not allowed in older SAP versions.

Can you check in SE11 if you have a database table called ZABAPGIT and if it contains a field called 'DATA'. If so, rename the field 'DATA' to 'DATA_STR'

**Comment by senel** [comment]
Hi,

thanks for the fast response.

Yes, table ZABAPGIT is present in the system. So I renamed field as you wrote and got another short dump:

`Error analysis
    An exception occurred that is explained in detail below.
    The exception, which is assigned to class 'CX_XSLT_RUNTIME_ERROR', was not
     caught in
    procedure "FROM_XML" "(METHOD)", nor was it propagated by a RAISING clause.
    Since the caller of the procedure could not have anticipated that the
    exception would occur, the current program is terminated.
    The reason for the exception is:
    Either the source document contains invalid XML or it is handled
    incorrectly in the ABAP program that called the transformation.






Missing RAISING Clause in Interface
    Program                                 ZABAPGIT
    Include                                 ZABAPGIT
    Row                                     3.771
    Module type                             (METHOD)
    Module Name                             FROM_XML



Trigger Location of Exception
    Program                                 ZABAPGIT
    Include                                 ZABAPGIT
    Row                                     3.781
    Module type                             (METHOD)
    Module Name                             FROM_XML

Source Code Extract

Line  SourceCde

 3751
 3752   ENDMETHOD.
 3753
 3754   METHOD list.
 3755
 3756     DATA: lt_content TYPE lcl_persistence_db=>tt_content,
 3757           ls_content LIKE LINE OF lt_content,
 3758           ls_repo    LIKE LINE OF rt_repos.
 3759
 3760
 3761     lt_content = mo_db->list_by_type( c_type_repo ).
 3762
 3763     LOOP AT lt_content INTO ls_content.
 3764       MOVE-CORRESPONDING from_xml( ls_content-data_str ) TO ls_repo.
 3765       ls_repo-key = ls_content-value.
 3766       INSERT ls_repo INTO TABLE rt_repos.
 3767     ENDLOOP.
 3768
 3769   ENDMETHOD.
 3770
 3771   METHOD from_xml.
 3772
 3773     DATA: lv_xml TYPE string.
 3774
 3775     lv_xml = iv_repo_xml_string.
 3776
 3777 * fix downward compatibility
 3778     REPLACE ALL OCCURRENCES OF '<_--28C_TYPE_REPO_--29>' IN lv_xml WITH '<REPO>'.
 3779     REPLACE ALL OCCURRENCES OF '</_--28C_TYPE_REPO_--29>' IN lv_xml WITH '</REPO>'.
 3780
>>>>>     CALL TRANSFORMATION id
 3782       OPTIONS value_handling = 'accept_data_loss'
 3783       SOURCE XML lv_xml
 3784       RESULT repo = rs_repo ##NO_TEXT.
 3785
 3786     IF rs_repo IS INITIAL.
 3787       _raise 'Inconsistent repo metadata'.
 3788     ENDIF.
 3789
 3790 * field master_language is new, so default it for old repositories
 3791     IF rs_repo-master_language IS INITIAL.
 3792       rs_repo-master_language = sy-langu.
 3793     ENDIF.
 3794   ENDMETHOD.
 3795
 3796   METHOD to_xml.
 3797
 3798     DATA: ls_xml TYPE ty_repo_xml.
 3799
 3800
`

**Comment by senel** [comment]
Cool, that worked! Thanks!
