### ISSUE TITLE
HTTPIO_PLG_CANCELED while adding online repository

### ISSUE THREAD

**Issue by Suncatcher** [larshp/abapGit#2990]
What to check?

**Comment by christianguenter2** [comment]
Can you provide a bit more info?

**Comment by Suncatcher** [comment]
I suppose I am missing HTTP service. Yes? Should I add it via RZ10?

![image](https://user-images.githubusercontent.com/6388034/67334638-7c861080-f4f0-11e9-9efe-b624d3a06081.png)

**Comment by mariusraht2** [comment]
Please check that there's a HTTPS Service created: RZ10 → Go To → Services. If not you have to define it in RZ10 > Extended Maintenance of the current version of the system-related Profile (not Default!) by changing/adding the parameter "icm/server_port_x" whereas x stands for an available server port (e.g. 1 or 2):
![grafik](https://user-images.githubusercontent.com/45243391/68196310-b0fdd000-ffb8-11e9-8e88-c960e64dada3.png)
You can figure out what port is available from the list of services in SMICM > Go To > Parameters > Display. In this case (s. image above) there's already a HTTPS service on server port 2.

After that the ICM Server is to be restarted: SMICM > "Administration" -> "ICM" -> "Exit Soft" > "Global". Please make sure there are no running processes that are depending on the ICM Server! They will be canceled!

Also make sure that you have none or a valid Proxy maintained: SICF → F8 → Client → Proxy Settings → HTTPS Protocol → Emptying or maintaining Hostname and Port with valid values.

Please also check you SAPCRYPTOLIB version: SA38 > SSF02 > Execute (F8) > Execute (F8). You must have at least CommonCryptoLib 8.4.38; SAP recommends 8.4.49 ([SAP Note 510007](https://launchpad.support.sap.com/#/notes/510007)). If you not meet this criteria you have to update the libary (s. [SAP Note 2450794](https://launchpad.support.sap.com/#/notes/0002450794)).

**Comment by mariusraht2** [comment]
@Suncatcher Did you solve this issue?

**Comment by Suncatcher** [comment]
Not yet. I will report when I solve

**Comment by larshp** [comment]
any luck? I dont think this issue is a bug in abapGit, most likely a system/network issue

**Comment by Suncatcher** [comment]
I am closing this for now as it is my SSL/TLS problems
