### ISSUE TITLE
Object type request: CPRO

### ISSUE THREAD

**Issue by RyabovAlex** [larshp/abapGit#2999]
Hello, working with ABAP classes in GUI often requires to overwrite the changes.
For example, implementing the gateway service requires to generate th runtime artifacts and then do redifinition of the methods (Get, Update, etc).
If implementing these redefinitions over ABAPGIT, currently some methods get overwritten and afterwards even dissapear.
The structure of redifinitions is located in CPRO object type (main class).
In order to make it be properly visible, it is required everytime after GIT import, edit and activate the main class text (CPRO).
Please kindly add this object type to proper processing.
THank you.

**Comment by larshp** [comment]
Can the issue be reproduced?

**Comment by RyabovAlex** [comment]
Hello, larshp.
Yes, certainly.
Everytime I redeploy the method redifinitions, the main class code is rewritten.
The issue to take it back is to open for edit and reactivate.
If I don't to that, all redifinitions become invisible for SE80.
the code still works, but RCA get much harder.
After 2-3 PULLs, the code gets unreadable :(

Can send screenshots if needed.

**Comment by larshp** [comment]
yea, can you help adding more information?

**Comment by larshp** [comment]
this was probably fixed in https://github.com/larshp/abapGit/issues/3053

and no reply, closing
