### ISSUE TITLE
Slow performance on serialization process

### ISSUE THREAD

**Issue by jeovax** [larshp/abapGit#3005]
I'm trying to use abap git just for code review purpose and my project has about 3000 ddic and the serialization process takes to long to be done. Is there a way to ignore does ddic objects and only serialize the code objects ?

**Comment by larshp** [comment]
move the ddic objects to a different package?

**Comment by jeovax** [comment]
Move the object is my last option, because move the objects would take a lot of work.

**Comment by larshp** [comment]
or use user exit https://docs.abapgit.org/ref-exits.html#change_tadir to make the objects disappear

**Comment by larshp** [comment]
are you running the long report or the dev version? The dev version includes multi-threaded serialization

**Comment by jeovax** [comment]
I'm running the long report. OK, I will try those two approach and see which one is the best.

**Comment by larshp** [comment]
for questions feel free to join the slack channel, https://abapgit-slackinviter.herokuapp.com
