### ISSUE TITLE
exception class text objects does not work?

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#302]
@grahamrobbo ?

Works for message based exception classes, saved as constants in eg. https://github.com/larshp/abapGitServer/blob/master/src/backend/zcx_ags_error.clas.abap

However I guess it doesnt work for non-message based exception classes

LIMU - CPUB

transaction SOTR_EDIT

tables SOTR_HEAD, SOTR_TEXT, SOTR_USE, SOTR_USEU

function modules:
* SOTR_GET_TEXTS_WITH_KEYS
* SOTR_GET_CONCEPT
* SOTR_DELETE_CONCEPT
* SOTR_OBJECT_GET_OBJECTS
* SOTR_CREATE_CONCEPT
* OTR_TOOLS_GET_TEXT_VIA_ALIAS
* BTFR_INSERT
* BTFR_USAGE_OF_CONCEPT

most likely something similar to https://github.com/larshp/abapOpenReview/blob/d7b7a7660f452c5276c47b1cdfe1d0c853805f3e/zcl_aor_review.clas.abap#L241 can be used to find the LIMU CPUB for the R3TR CLAS

**Comment by grahamrobbo** [comment]
Hadn't thought of testing with message-based exception classes - sorry about that. Starting to wonder if a solution would be bigger than the problem. ;)

**Comment by larshp** [comment]
I think it will be quite simple to implement, I'll probably have time to look into it this week.

However I recommend using message based exception classes, as it IMHO is easier to do where used from the message class to the code that raises the message.

**Comment by mrsimpson** [comment]
When not using se91 messages in exception classes, I simply pass a string to the constructor and then redefine get_text() to return it

**Comment by larshp** [comment]
done, see branch https://github.com/larshp/abapGit/tree/issue302

will probably push to master tomorrow

**Comment by larshp** [comment]
@grahamrobbo try again(latest abapGit version), the SOTR texts should now be part of the XML file. Feel free to open a new issue if it doesnt work
