### ISSUE TITLE
When patching files, state boxes are empty on the commit page

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#3022]
When using just the stage screen, the boxes work correctly. But when I go through the patch screen, they always look like this:
![SapGuiServer_a80mfwEvb1](https://user-images.githubusercontent.com/5097067/68015265-0e7cde80-fc92-11e9-8158-1ec49b475e87.png)

#3007

**Comment by larshp** [comment]
see comments in https://github.com/larshp/abapGit/pull/3003
