### ISSUE TITLE
TABL: SAPGUI data preview doesn't work when opened from abapGit

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#3029]
If I navigate to a transparent table (SE11) from abapGit and then go to 'Contents' (SE16) nothing happens and the window closes.

![image](https://user-images.githubusercontent.com/17437789/68067591-9d98fd80-fd49-11e9-9c2c-88cb237034b3.png)

![image](https://user-images.githubusercontent.com/17437789/68067596-a984bf80-fd49-11e9-924b-eb63471cc43a.png)

**Comment by mariusraht2** [comment]
Seems only to happen for tables for which its selection screen weren't called once after their creation: I created a new table and navigated from abapGit to the transparent table and tried to call the selection like you did and the window just closes itself. Found out that after `COMMIT WORK ` in form "ausgeben" the report just exits:
```
  insert report repname from report.
  update progdir set rstat = 'S'
                   unam  = 'SAP*'
                   cnam  = 'SAP*'
                   edtx  = 'X'
                   rload = sy-langu
                   occurs = '1'
                   subc  = '1' where name = repname and state = 'A'.
  commit work. 
```

After that I called SE11 manually, clicked the "content" button and from that moment on the selection screen opened via abapGit without error.

**Comment by mariusraht2** [comment]
Will apply a fix very soon: Figured out that calling RS_TOOL_ACCESS instead of ABAP4_CALL_TRANSACTION for SE11 fixes the bug.
