### ISSUE TITLE
UI: Login dialog usability

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#303]
Addressing usability of login dialog - noname unidentified login somewhere. ;)

![2016-08-28_20h57_04](https://cloud.githubusercontent.com/assets/15635498/18035901/f5bf16ae-6d67-11e6-86da-2f46ec636991.png)

- Better visibility as to which repo/server the user is logging into
- Possibility to default username in the login popup

**Comment by sbcgua** [comment]
@larshp Have a look at the commits above ? I don't know the transport code well (yet at least :) maybe I overlooked some logic.

![image](https://cloud.githubusercontent.com/assets/15635498/18036600/96fbb13a-6d77-11e6-87d8-e5e6d2f7b6e3.png)

Doubts:

1. In this way password is not hidden. This is the main concern. Also it is shown in history (on spacebar). I don't know how to make the field masked ('***'). Maybe there are some std dialog with user and masked pass fields ? Or maybe dive deep into `generate dynpro` internal call ? Or maybe implement in html (not sure how to keep it light)? Or maybe look into OAuth and authorization directly at host site (limits compatibility though)? ...

2. [paranoia ON] keeping passwords in variables even temporary is insecure [paranoia OFF]. Imho not critical here.

Small cosmetic change at lcl_git_transport=>class_constructor by the way. Added '-' before version if you don't mind ("git/abapGitv1.17.3" didn't look well).

P.S Further improvement: add login name per user per repo to config and defaulting the username in the dialog.

P.P.S. Include order needs some refactoring ... one observation: many classes depends on persistence->ty_value (key) definition. I think it can be move to global types. Also lcl_git_transport=>ty_branch_list. Could not move password_popup to lcl_popups because of this stuff.

P.P.P.S ... another option is to find how to change "Resource" field in the standard dialog, but I didn;'t find any hints on that.

**Comment by larshp** [comment]
I'm quite paranoid :) I think it would be easier to move it to html instead of masking the password in a ABAP popup.

I think the "Resource" field is taken from some HTTP headers, which we cannot change.

Anyhow, what are we trying to solve? I guess the following:
* Possibility to default username in the login popup
* Better visibility as to which repo/server the user is logging into

**Comment by sbcgua** [comment]
Yeap, the goal is correct (added to the issue head).
After a day passed I don't like the code anymore. Insecure indeed ... I'll do some more experiments.

**Comment by sbcgua** [comment]
![image](https://cloud.githubusercontent.com/assets/15635498/18158551/a2e7844e-702c-11e6-9816-bbdb0459148c.png)

**Comment by sbcgua** [comment]
Finally ! On the halfway I started to regret that I initiated the subject ...

The initial solution was insecure.
I struggled some time with `cl_gui_dialogbox_container` but it is amodal and after some time I gave up on it. 
The I started hopelessly to dig into `generate dynpro`
And then my collegue @sshlapak advised a solution - another selection screen :) Thanks !
So now it seems fine to me. 

If OK I can MR. And then would take a look into defaulting username.

OFFTOPIC:  would you mind if I merge all zabapgit_object* into one include (I mean 2nd level include that includes zabapgit_object*) - as I understand abapmerge supports it already :)

**Comment by larshp** [comment]
My thoughts:
Looks like P_PASS can be cleared in method popup after passing the value to CV_PASS?

How does it work with private repositories?

Includes: no, seems like a good idea. Do not remember if it works in abapmerge, but it can be tested via the web thing, http://larshp.github.io/abapmerge/

**Comment by sbcgua** [comment]
Ah yes, and yet I've found FMs:
`POPUP_GET_USER_PASSWORD` and `POPUP_GET_PASSWRD_AND_REGISTRY`
But they are from 731

**Comment by sbcgua** [comment]
>Looks like P_PASS can be cleared in method popup after passing the value to CV_PASS?

Indeed, will fix in a moment

> How does it work with private repositories?

Yes

Includes: mmm, sorry "no" or "seems like a good idea" ? =)

**Comment by larshp** [comment]
Includes: I do not mind => it seems like a good idea

**Comment by sbcgua** [comment]
abapmerge supports, I checked. ;)
However, I'd replace the regex there:
`/^\s?INCLUDE\s+(z\w+)\s*.\s*$/i` to `/^\s*INCLUDE\s+(z\w+)\s*.\s*$/i` (any whitespace before include keyword)

**Comment by larshp** [comment]
abapmerge: yes, looks good, feel free to submit it as a PR(you can just edit the code via the github web interface, since it is a small change)

Please keep the password and the reorganizing of includes in 2 separate PRs if possible, so we dont mix too much in one PR

**Comment by sbcgua** [comment]
> Please keep the password and the reorganizing of includes in 2 separate PRs

OK, I'll do it a bit later anyway and create a separate task. It seems it will be a bit more complecated than I thought initially. Just a short question: how does `ZABAPGIT_OBJECTS` relate to **core** serialization. Except it defines the interface and then use it in the gateway ?

**Comment by larshp** [comment]
not sure, would have to look into the code. Include ZABAPGIT_OBJECTS is kind of a mess, from the initial break into multiple includes.

It was a lot of work splitting everything into includes, and some of the code does not have a nice home :smile:

**Comment by sbcgua** [comment]
... will keep this open for while just in case ...
