### ISSUE TITLE
The text contains characters which cannot be converted

### ISSUE THREAD

**Issue by ElNovi** [larshp/abapGit#3035]
I can't activate new version of ABAPGIT (previous activated was 1.90 ) due to error: **The text contains characters [ E2 86 B5 22 2C 20 22 43 6F 6D 6D 69 74 22 29 3B] which cannot be converted**

It doesn't specify which row is related to this issue :/ I'm on 7.31 non-unicode system.

**Comment by larshp** [comment]
hmm, try isolating the issue and find the statement which causes the error

**Comment by ElNovi** [comment]
Seems that this text is causing it `↵", "Commit");`

**Comment by ElNovi** [comment]
The fix works very well, thank you
