### ISSUE TITLE
Error author regex

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#3042]
For abapGit itself, trigger Tag -> Switch, gives following error

![image](https://user-images.githubusercontent.com/5888506/68203131-70f11a00-ffc5-11e9-8dfb-680b27e2ceaf.png)

**Comment by larshp** [comment]
still get the same error, we need to add unit tests too for the regex, reopen

**Comment by mariusraht2** [comment]
I don't get the error anymore so to see the value that causes it I added it to the error message.

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/69007671-151d7e00-0941-11ea-9d38-75c687ef3d43.png)

**Comment by mariusraht2** [comment]
Ah seems its because of äöüÄÖÜ ("Umlaute")

**Comment by mariusraht2** [comment]
I suggest we use this (.*) instead of ([\\\w\s\.\*\,\#@%\-_1-9\(\)\[\] ]+)

**Comment by larshp** [comment]
try it out, and please add unit tests, ABAP regex is greedy so not totally sure if it will work, but unit tests will show

**Comment by mariusraht2** [comment]
I figured out that zcl_abapgit_test_serialize=>check is no valid test method on my system (7.52). Test methods are to be marked with "for testing" and can't be class-methods (static).
