### ISSUE TITLE
Type "CL_W3_API_XML3" is unknown 	

### ISSUE THREAD

**Issue by stoamandl** [larshp/abapGit#3046]
Hi, 
if i want to activate from the latest full build 
[https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap](url)
i get the error "Type CL_W3_API_XML3 is unknown.
In one of the older full builds this problem do not exist.
My SAP_ABA and SAP_BASIS is 702 SP 0009.
I know.... its old.
But is there a way to solve this issue without to implement the note
[https://launchpad.support.sap.com/#/notes/1837409](url)
That seems to be the  pre publish implementation of the missing class.
But with a lot of manual work.

Thank you!

**Comment by christianguenter2** [comment]
Can you check whether the interface `if_w3_api_object` is available?

**Comment by stoamandl** [comment]
> Can you check whether the interface `if_w3_api_object` is available?

The interface is available!

**Comment by christianguenter2** [comment]
And the class `CL_W3_API_OBJECT`?

**Comment by stoamandl** [comment]
> ~And the class `CL_W3_API_OBJECT`?~
> Never mind, I prepared a fix.

Ok,
Let me know if I should test.

Thank you!

**Comment by larshp** [comment]
see changes in https://github.com/larshp/abapGit/pull/3047 for testing

**Comment by stoamandl** [comment]
> see changes in #3047 for testing

Ok, 
The fix solved this problem.
But i have to change in Class ZCL_ABAPGIT_OBJECTS Methode check_duplicates  
The Chaining Operator && with the Append to lt_duplicates.
Marked with #001.
I think my Abap Release does not support that feature.

    DATA: lt_files TYPE zif_abapgit_definitions=>ty_files_tt,
          lv_path TYPE string,
          lv_filename TYPE string,
          lt_duplicates TYPE stringtab,
          lv_duplicates TYPE string, "#001
          lv_all_duplicates TYPE string.

    FIELD-SYMBOLS:
      <lv_file> LIKE LINE OF it_files.

    lt_files = it_files.
    SORT lt_files BY path ASCENDING filename ASCENDING.

    LOOP AT lt_files ASSIGNING <lv_file>.
      IF lv_path = <lv_file>-path AND lv_filename = <lv_file>-filename.
        CONCATENATE <lv_file>-path <lv_file>-filename INTO lv_duplicates. "#001
        APPEND lv_duplicates TO lt_duplicates. "#001
        "APPEND <lv_file>-path && <lv_file>-filename TO lt_duplicates.  "#001
      ENDIF.
      lv_path = <lv_file>-path.
      lv_filename = <lv_file>-filename.
    ENDLOOP.

    IF lt_duplicates IS NOT INITIAL.
      CONCATENATE LINES OF lt_duplicates INTO lv_all_duplicates SEPARATED BY `, `.
      zcx_abapgit_exception=>raise( |Duplicates: { lv_all_duplicates }| ).
    ENDIF.

Also the cl_w3_api_template=>if_w3_api_template~create_new Methode do not have the Exception "user_error" 
I removed that.

After this changes everything runs like expected!

Thank You!
Great Project!

**Comment by christianguenter2** [comment]
fixed b7cfa44
