### ISSUE TITLE
Force Stage: JS Init error

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#3048]
![image](https://user-images.githubusercontent.com/17437789/68316845-6cf2f400-00ba-11ea-89dc-790d94d74649.png)

steps to reproduce

1) create package $test_ftgl with short description test feature toggle
![image](https://user-images.githubusercontent.com/17437789/68316991-a75c9100-00ba-11ea-8721-d4746369b838.png)

2) goto abapGit and create new online repo
https://github.com/abapGit-tests/FTGL
![image](https://user-images.githubusercontent.com/17437789/68317034-b93e3400-00ba-11ea-9fc6-b8f01c9cfe87.png)

3) goto advanced > force stage

**Comment by sbcgua** [comment]
just today got the same issue.
Most probably it is because of dynamic detection of columns, which is done on "local" section, but don't have time to check these days. maybe on the weekend

**Comment by larshp** [comment]
had the same problem earlier today
