### ISSUE TITLE
Hash character in imported ZIP repository

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapGit#3051]
Hi all,

I have a problem, I installed my repository in a system which is under firewall so I need to import changes with a zip file.

Problem is that compressed files in zip are always loaded with "#" characters, so always detect changes
![image](https://user-images.githubusercontent.com/56556686/68377380-8f345280-014a-11ea-917d-95c39dfc6d66.png)

Original file uncompressed hasn't character:
![image](https://user-images.githubusercontent.com/56556686/68377524-d884a200-014a-11ea-8ae7-6d76b299ec53.png)

Any idea about that?

Thank you.

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit/issues/799 and https://github.com/larshp/abapGit/issues/1044

**Comment by jrodriguez-rc** [comment]
Thank you, I'll check them

**Comment by BlackmanCC** [comment]
@jrodriguez-rc Please try out my changes in Pull request #3167
