### ISSUE TITLE
Issue on NW 7.31 system

### ISSUE THREAD

**Issue by os-neff** [larshp/abapGit#3054]
Hey Lars,

the following coding is causing issues on lower release version, like 7.02 and 7.31:

https://github.com/larshp/abapGit/blob/3776ac353a06dd944caa332da5a4b3d159cc3a6b/src/zcl_abapgit_objects.clas.abap#L315

One probably has to use an auxiliary varialbe like 
`        lv_path_file = <lv_file>-path && <lv_file>-filename.
        APPEND lv_path_file TO lt_duplicates.`

Best regards
Joachim

**Comment by larshp** [comment]
thanks, pull request welcome 😄

**Comment by christianguenter2** [comment]
Already fixed here b7cfa44
