### ISSUE TITLE
check repo URLs before creating a new online repo

### ISSUE THREAD

**Issue by filak-sap** [larshp/abapGit#3060]
I had to deal with a shortdump where the user added their package with the url https://github.com/. Then it was not possible start abapgit because zcl_abapgit_url=>name did not parse out rv_name and dumped on the assert.

**Comment by mariusraht2** [comment]
Also we have to make sure that the repo name is only the name between a "/" and ".git" or the end of the url, because something like this is also recognized as valid: "https://github.com/larshp/" or "https://github.com/larshp".

**Comment by mariusraht2** [comment]
Ok, something I just learned: git repo urls don't need to have the extension '.git'. So we don't need to edit the regex for repo urls.
