### ISSUE TITLE
Any possible way to convert CGM file to base64 using abap?

### ISSUE THREAD

**Issue by vikashkumar99** [larshp/abapGit#3065]
We tried to convert using below FM but image gets corrupt on HTML.

CALL FUNCTION 'SCMS_BINARY_TO_XSTRING'
  EXPORTING
    input_length = lw_length
  IMPORTING
    buffer       = lw_xstring
  TABLES
    binary_tab   = li_data
  EXCEPTIONS
    failed       = 1
    OTHERS       = 2.
IF sy-subrc <> 0.
  RETURN.
ENDIF.

* Conversion en Base64
CALL FUNCTION 'SCMS_BASE64_ENCODE_STR'
  EXPORTING
    input  = lw_xstring
  IMPORTING
    output = lw_string_base64.

**Comment by mariusraht2** [comment]
This is totally off-topic. You should ask those questions the [SAP Community](https://community.sap.com/) or on [StackOverflow](https://stackoverflow.com/).

**Comment by christianguenter2** [comment]
Closed as off topic.
