### ISSUE TITLE
Class text elements translation

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapGit#3066]
Translation for class element text are not in git repository.

I have some text elements with translation EN->ES:
![image](https://user-images.githubusercontent.com/56556686/68852470-37609300-06d8-11ea-8c8f-6010d84717ea.png)
![image](https://user-images.githubusercontent.com/56556686/68852512-4d6e5380-06d8-11ea-8ed0-65b2050e7d6a.png)

But in remote system there are no translations
![image](https://user-images.githubusercontent.com/56556686/68852543-6414aa80-06d8-11ea-873e-1995c09c1df9.png)

**Comment by christianguenter2** [comment]
Confirmed. Seems that only texts in the master language are currently serialized.
https://github.com/larshp/abapGit/blob/714fe7202dbd225433a42dfe08f66753e6f5005b/src/objects/zcl_abapgit_object_clas.clas.abap#L242-L246

See also #2539

**Comment by jrodriguez-rc** [comment]
It could be done same way that PROG types once classpool name is determined, languages can read from D010TINF and get all translations:
![image](https://user-images.githubusercontent.com/56556686/69039151-a6492f00-09eb-11ea-9a55-2efb9032eb91.png)
![image](https://user-images.githubusercontent.com/56556686/69039176-b3feb480-09eb-11ea-8567-693d33aeb30f.png)

**Comment by larshp** [comment]
Pull request https://github.com/larshp/abapGit/pull/3078
