### ISSUE TITLE
Though installation fails db entry isn't being deleted

### ISSUE THREAD

**Issue by mariusraht2** [larshp/abapGit#3068]
If the installation of abapGit fails, the related database entry isn't being deleted so it isn't possible for a common user to retry the installation because if you try it says that the repo is already referenced. In my case I had to delete the db entry via db utils and restart abapGit so it recognizes the removed db entry (maybe worth a 2nd issue^^).

**Comment by mariusraht2** [comment]
We should run the "removing repo"-routine if the installation failed.

**Comment by larshp** [comment]
did you check the "burger" icon to find the repo after it failed? It is typically there, just its not added as a favorite

**Comment by mariusraht2** [comment]
You're right - there it is:
![grafik](https://user-images.githubusercontent.com/45243391/69008072-7e53c000-0946-11ea-9000-fc3d371a0151.png)
So the user would have to pull the objects and "install" them thereby into $ABAPGIT.

**Comment by larshp** [comment]
it should be added as a favorite so its not hidden, but its a bit difficult

related: https://github.com/larshp/abapGit/issues/1678

**Comment by mariusraht2** [comment]
I added a exporting parameter for the repo_key to the new_online method so we would be able to add it to the favorites toolbar. If the exception appeared before or while the key generation we just throw the exception.

**Comment by mbtools** [comment]
We have a new repo overview and favorite design. Closing this one.
