### ISSUE TITLE
Add unit tests for author regex

### ISSUE THREAD

**Issue by mariusraht2** [larshp/abapGit#3069]
Maybe this is a good point to introduce unit tests for that regex?

_Originally posted by @christianguenter2 in https://github.com/larshp/abapGit/pull/3067#issuecomment-554070478_

**Comment by larshp** [comment]
@mariusraht2 I've invited you as a collaborator to abapGit, welcome 😄 

feel free to join the slack channel https://abapgit-slackinviter.herokuapp.com if you are not already there, everybody else also welcome on slack 🎈

**Comment by mariusraht2** [comment]
@christianguenter2 I didn't know if it's just sufficient to be able to give it a value and you get back the result or we should test some actual values within the unit test so I implemented both^^.

**Comment by mariusraht2** [comment]
I figured out that zcl_abapgit_test_serialize=>check is no valid test method on my system (7.52). Test methods are to be marked with "for testing" and can't be class-methods (static).

**Comment by mariusraht2** [comment]
How is it possible to invert assert-checks? I tried to execute assert_true based on the result of assert_text_matches which would return 'X' if assertion failed:
```
    " +00001 too long
    cl_abap_unit_assert=>assert_true(
      cl_abap_unit_assert=>assert_text_matches(
        EXPORTING
          pattern = zif_abapgit_definitions=>c_author_regex
          text    = 'pull[bot] <39814207+pull[bot]@users.noreply.github.com> 1573216988 +00001'
          quit    = if_aunit_constants=>no
          level   = if_aunit_constants=>tolerable ) ).
```

**Comment by larshp** [comment]
suggest adding a utility method that calls normal ABAP regex instead
