### ISSUE TITLE
abapGit didn't create a function module

### ISSUE THREAD

**Issue by valdirmendesgt** [larshp/abapGit#3084]
I had some problems with function module when i am getting abapGit clone in a client environment, according to the image below. This happened to my code as well when I tried to pull a new version of the function group in another environment. does anyone have this problem?

![image](https://user-images.githubusercontent.com/1057524/69341459-5d41e680-0c48-11ea-9c27-853135978c6f.png)

**Comment by larshp** [comment]
hmm, try checking authorizations and developer key?

**Comment by valdirmendesgt** [comment]
It's ok! I will test and debug this part to clarify the error and post again. thanks
