### ISSUE TITLE
HTTP 401, unauthorized 

### ISSUE THREAD

**Issue by gedhurst** [larshp/abapGit#3088]

**Comment by gedhurst** [comment]
I have set up SSL on a S4 HANA system and Report ZABAPGIT_TEST_SSL runs OK. However I get 'HTTP 401, unauthorized' when I try to clone an online repository via ZABAPGIT. Any ideas?

**Comment by larshp** [comment]
Is it a public or private repository? What git host are you using? Any 2FA setup on your user?

**Comment by gedhurst** [comment]
It's a private repository, no 2FA. My company has single sign-on with GitHub (SAML single sign-on). It looks like I need to create a personal access token for the command line. I'll close this issue and try that.
Thanks!

**Comment by larshp** [comment]
yea, see https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
