### ISSUE TITLE
Code selection "by column" on diff screen

### ISSUE THREAD

**Issue by sandraros** [larshp/abapGit#3089]
It can be useful to copy/paste the code while comparing branches (diff view) so that to copy easily some portions of code from branch to branch.

Unfortunately, in the diff screen of abapGit, whatever it's in the split or unified view, the selection of code selects the whole lines, including the row numbers and marks, and if it's in the split view, the code of the other side is also included.

As-is (want to copy code from the right side, but unfortunately the code from the left side is also selected):

![image](https://user-images.githubusercontent.com/34005250/69497971-086dcc80-0ee3-11ea-8484-368f1ff95194.png)

To-be:

![image](https://user-images.githubusercontent.com/34005250/69497287-88903400-0edb-11ea-8c27-5ddb3f7860b7.png)

For information, the principle how to select and copy code of an HTML table column is explained here: https://stackoverflow.com/questions/6619805/select-text-in-a-column-of-an-html-table.

I have prototyped the solution and it works well (for me). I will propose a pull request if you agree with this feature.

**Comment by larshp** [comment]
agree

**Comment by sbcgua** [comment]
interesting. There was an issue like this before, but it was not solvable by CSS in IE (though Chrome and any other modern browser worked fine - `user-select: none` if I remember correctly). But a combination with JS could be interesting.
