### ISSUE TITLE
UX: default username in the login popup

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#310]
Following #303
default user name per user per repo
- [X] save/restore config
- [x] fix in pass dialog call

**Comment by sbcgua** [comment]
Can be reviewed as well, but the goal was not achieved yet.

The obstacle is that `lcl_git_transport->bracnhes()` does not have access to repo key. Option is to pass repo reference instead of url as the parameter. Or ...

The call is used in `ZABAPGIT_PAGE_BRANCH_OVERVIEW` and `ZABAPGIT_PAGE_MERGE` which have repo instance. And in `ZABAPGIT_POPUPS` which does not ... Would it be OK to pass repo everywhere ? 

Another option is to find repo key by URL (add some method to persistence class), or maybe keep URL in user_repo_config, or making repo URL the key instead of repo-key (in user repo config) ... the last looks best for me but creates some discrepancy in detail levels. Need an opinion from your side :)

**Comment by larshp** [comment]
Lets try to disconnect it from the repo object, its starting to become too central :)

I like the idea with having the url as key in user persistence(fields username and email)

```abap
   METHODS set_repo_username
      IMPORTING iv_url TYPE string
                iv_username TYPE string
```

**Comment by sbcgua** [comment]
ok, agree. Looks like ready then.
