### ISSUE TITLE
Table Storage Type not exported/imported

### ISSUE THREAD

**Issue by mfsap** [larshp/abapGit#3101]
When a table is defined with storage type "Column Store" in source system, the attribute is not exported to the git repository. When this table is imported, the table is handled as "Row Store" table because DD09L-ROWORCOLST field is initial.
Error happens in serialization method of ZCL_ABAPGIT_OBJECT_TABL:
```
    ASSIGN COMPONENT 'ROWORCOLST' OF STRUCTURE ls_dd09l TO <lg_roworcolst>.
    IF sy-subrc = 0 AND <lg_roworcolst> = 'C'.
      CLEAR <lg_roworcolst>. "To avoid diff errors. This field doesn't exists in all releases
    ENDIF.
```
I would recommend to keep the field ROWORCOLST as it is and live with the diff. errors in old releases...

**Comment by larshp** [comment]
as far as I remember, importing without the field imports it as 'C' by default?

**Comment by mfsap** [comment]
Sorry, I have not checked in detail. The affected table was exported as RowStore table and by mistake I thought it was a ColumnStore table that has been exported with wrong attributes. And yes, 'C' is the default if ROWORCOLST is initial. I'll close this issue!
