### ISSUE TITLE
SAP BW component objects do not exist in SAP BASIS

### ISSUE THREAD

**Issue by sfkc** [larshp/abapGit#3105]
Newly added class zcl_abapgit_object_iobj has references to data elements and function modules with prefix RSD_*. These do not exist in SAP BASIS so you cannot use the zabapgit report there now without activating with errors.

**Comment by pawelwiejkut** [comment]
@larshp , @christianguenter2 , can I check installed modules by cvers , or there is a build in a mechanism for this? I think that we can check do you have SAP_BW component installed and call functions dynamically?

**Comment by larshp** [comment]
temporary workaround is commenting the class

can you help listing the syntax errors? The function modules should be okay, since these are resolved at runtime

**Comment by larshp** [comment]
relevant code is https://github.com/larshp/abapGit/pull/3058

@pawelwiejkut I guess `rsd_s_viobj`, `rsd_iobjnm`, `rsd_t_c30` can be changed to `TYPE C LENGTH something`, function modules are resolved at runtime so they should not cause syntax errors. But lets wait to see what the actual errors are before fixing it

**Comment by sfkc** [comment]
Yup sure. You are correct, the given data elements come as 
> Type "RSD_*" is unknown.
The report will activate with unknown FMs.
I agree with your fix, change the data elements to primitives. I can't do that locally as I don't even know what data types these are ;)

**Comment by sfkc** [comment]
> @larshp , @christianguenter2 , can I check installed modules by cvers , or there is a build in a mechanism for this? I think that we can check do you have SAP_BW component installed and call functions dynamically?

Are you sure these data elements are even available in SAP BW ?

**Comment by pawelwiejkut** [comment]
> > @larshp , @christianguenter2 , can I check installed modules by cvers , or there is a build in a mechanism for this? I think that we can check do you have SAP_BW component installed and call functions dynamically?
> 
> Are you sure these data elements are even available in SAP BW ?

Example:
<img width="1129" alt="Screenshot 2019-12-06 at 10 41 05" src="https://user-images.githubusercontent.com/11619019/70312971-fc540a00-1814-11ea-9b20-57392ea2e803.png">

@larshp , what is a correct approach to handle structures in this case? Can I create my own corresponding type locally?

**Comment by larshp** [comment]
`rsd_iobjnm` can be replaced with `TYPE c LENGTH 30`

**Comment by sfkc** [comment]
The objects I cannot find in a BASIS system...

_Structures_
rsd_s_viobj
bapi6108
bapi6108io

_Table types_
rsd_t_c30

_Data elements_
rsdiobjnm
rsd_iobjnm

_DB tables_
rsdiobj

_Functions_
RSDG_IOBJ_MULTI_DELETE
BAPI_IOBJ_CREATE
BAPI_IOBJ_ACTIVATE_MULTIPLE
BAPI_IOBJ_GETDETAIL
RSD_IOBJ_GET

**Comment by christianguenter2** [comment]
Is anyone working on this? If not I can provide a patch.

**Comment by pawelwiejkut** [comment]
> Is anybody working on this? If not I can provide a patch.

Yes, just give me a minute.

**Comment by larshp** [comment]
@sfkc try again, latest version

**Comment by sfkc** [comment]
Hello. The structures BAPI6108 and bapi6108io are still referred to in the latest code thus I cannot activate. Cheers

**Comment by larshp** [comment]
@sfkc try again, latest version

**Comment by sfkc** [comment]
Hi @larshp 

Tried again, rsdiobj DB table still doesn't exist. Do you want me to comment out the class zcl_abapgit_object_iobj still?

Cheers
