### ISSUE TITLE
Exclude some object types from serialization/deserialization

### ISSUE THREAD

**Issue by arial** [larshp/abapGit#3106]
Hello!

I need to exclude some object types (i.e. BSP applications) from serialization/deserialization. Is it possible? What I should do for it?

Regards, Lev

**Comment by larshp** [comment]
Try this user exit: https://docs.abapgit.org/ref-exits.html#change_tadir

**Comment by larshp** [comment]
@arial did above help?

**Comment by larshp** [comment]
closing, no reply
