### ISSUE TITLE
Can't transport Report Program Application Variant

### ISSUE THREAD

**Issue by jwigert** [larshp/abapGit#3107]
Hi,

I have a transport request containing a report variant (Program ID: LIMU, Object Type: VARX). When I try to select the transport request in order to transport to branch, an exception is raised in `ZCL_ABAPGIT_TRANSPORT->RESOLVE`. The call of function module `GET_R3TR_OBJECT_FROM_LIMU_OBJ` fails with "no_mapping" (`sy-subrc = 1`). 

Would it be ok to exclude Object Type: VARX from the call of the function module? Please let me know your thoughts, and I'll be happy to create a PR.

Kind regards,
Johan

**Comment by larshp** [comment]
yea

looks like VARX is a workaround that does not really belong to a R3TR object

**Comment by jwigert** [comment]
Thanks, you can assign the issue to me, and I'll create a PR to exclude VARX from the call.

**Comment by larshp** [comment]
done

**Comment by larshp** [comment]
PR merged, closing
