### ISSUE TITLE
UI: Branch switch UI tweaks

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#311]
![image](https://cloud.githubusercontent.com/assets/15635498/18161483/c1bb5c2a-703a-11e6-863b-e484dbb73ca6.png)

Idea is:
1. refs/heads/*** should become a link - activating will call switch (no changes in swicth itself)
2. get rid of "refs/heads/" part in view
3. non-master branches should be highligted with some color to emphasize that it is no master (somewhat arguable, master is not always the master ... but should be ok for 99%, maybe add the master branch name to config later if required)

@larshp one question to p.2 - do you know if it is always "refs/**heads**/" or there may be something else in git ? I'm not 100% sure

**Comment by larshp** [comment]
currently abapGit is defaulted to use 'refs/heads/master' however I think it is more correct to use 'HEAD'. There is also 'refs/pull/*' for each pull request(currently not shown in abapGit)
and 'refs/tags/*' for tags, eg https://github.com/larshp/abapGit/tree/v0.113.0

**Comment by sbcgua** [comment]
... info by the way:

Gitlab, private repo, 2 merge requests (1 is external ~ pull request), 1 (one!!) tag:

```
refs/heads/abranch
refs/heads/master
refs/keep-around/03b6f005841e685c7e4e1db68ee1deb20962f6be
refs/keep-around/caca5c8e7460465bce2da0fb9591f7c5c345153d
refs/keep-around/e106f781d263fa3e6208ea5970bd99cf3afd34f8
refs/merge-requests/1/head
refs/merge-requests/2/head
refs/tags/TheTag
refs/tags/TheTag^{}
refs/tmp/d9edd92395b8f0f57da7ed5aeda14419/head
```
seems like merge/pull request branch names is not a standard.
seems like there is some strange mirror name for tag (in gitlab at least)
seems like there are more technical branch names

BTW header record contains link between HEAD and the master branch - `symref=HEAD:refs/heads/master` - can be useful

**Comment by sbcgua** [comment]
![image](https://cloud.githubusercontent.com/assets/15635498/18225220/642c4d54-71f6-11e6-856e-8447dad30de5.png)

@larshp Have a look.

- most of branch logic separated to `lcl_git_branch_list`. It exposes some useful semantic methods
- branch types are global. Maybe they should be returned to `lcl_git_branch_list`. Not sure. I'd move important types to definitions include - would simplify includes order. What do you think ?
- branch object now identifies HEAD symref -> `mv_head_symref` - can be useful for what you mentioned above. Both HEAD and symref are marked as `is_head` in the branch list
- added interactive link to UI, however no color coding yet ... see below
- `ZABAPGIT_PAGE_BRANCH_OVERVIEW` should be probably refactored but I didn't study how it works and a bit lazy for that ;P ... e.g. `lv_name = <ls_branch>-name+11` => `<ls_branch>-display_name ???`

Now one issue. I actually wanted to make color coding for the branch link - to see more clearly if it is master or not (tags seem to be irrelevant for the moment because swicthing to tag is not supported as I undertood). But for this I need the fact that the branch is HEAD. And for this I need full info about the repo branches which is missing at the moment of UI rendering. I think it would be useful to keep the instance of `lcl_git_branch_list` in repo instance. What do you think ? If yes, what is the best point to add it?

non-master will probably look something like this
![image](https://cloud.githubusercontent.com/assets/15635498/18225420/910d8dee-71f9-11e6-8a67-269da36e290b.png)
Or maybe this ... 
![image](https://cloud.githubusercontent.com/assets/15635498/18225429/faba2bee-71f9-11e6-9062-a243433ba184.png)

still thinking ... a side opinion will help :) On the one hand I don't want to introduce more link colors (also link is blue so why it suddenly becomes orange) ob the other icon might not be visible enough. Background change would look ugly. On the other hand maybe always show background (with rounded squares): grey for master , orange for branch. Or maybe not orange ... and not grey ... I think I have to do a break :)

![image](https://cloud.githubusercontent.com/assets/15635498/18225466/11947d82-71fb-11e6-8bdc-2ea707898f16.png)

**Comment by larshp** [comment]
cool, will take a look tomorrow

**Comment by larshp** [comment]
refactorings look really good

branch types global: I think it is a good idea to keep types in the local classes if possible, so they are closely related with the logic. We can always move it to global if its needed. Also the branch types might only be needed after calling the lcl_git_branch_list methods.

branch list in repo instance: yes, I've also been thinking about it, though not sure how it will work out. Give it a try and see how it looks. Perhaps submit the current changes as a PR now, and do this as next step.

link colors: I like the background with rounded squares approach. Colouring texts blue for links and what happens when its visited might get too confusing.

private: can these 2 variables be changed to private?
```abap
DATA mt_branches    TYPE ty_git_branch_list_tt READ-ONLY.
DATA mv_head_symref TYPE string READ-ONLY.
```
 
constants: perhaps change the constant defintions to
```abap
CONSTANTS: BEGIN OF c_type,
  branch TYPE ty_git_branch_type VALUE 'HD',
  tag   TYPE ty_git_branch_type VALUE 'TG',
  other  TYPE ty_git_branch_type VALUE 'ZZ',
END OF c_type 
```
from
```abap
CONSTANTS TYPE_BRANCH TYPE ty_git_branch_type VALUE 'HD'.
CONSTANTS TYPE_TAG    TYPE ty_git_branch_type VALUE 'TG'.
CONSTANTS TYPE_OTHER  TYPE ty_git_branch_type VALUE 'ZZ'.
```
Its a trick I've recently started using, creating a structured constant for the constants with similar semantics

**Comment by sbcgua** [comment]
Generally all OK, I'll check/answer later today, have to go now.  :)

P.S. Why don't you like `read-only` feature? I find it so cool :) I'd say it is cleaner than getters (in abap at least). I'll fix, just to discuss.

**Comment by larshp** [comment]
read-only: I think its an old habit from when I worked with Java, it exposes internal class design.

In this case i guess method `get_head()` could be used instaed of `mv_head_symref`, and method `get_branches_only()` instead of `mt_branches`. 

In the current example it looks like `CLASS-METHODS create` can be changed to a `constructor` ?

**Comment by sbcgua** [comment]
1. constants: agree, I also liked this approach.
2. branch types global: ok, convinced.
3. `get_head`: I've adjusted it to search for symref first and then fallback to HEAD. Maybe it worth to make 2 methods - kind of `get_head` and `get_master` to avoid ambiguity. But anyway it is not used in the code for the moment.
4. `branch_list_popup` now calls `get_branches_only`. Which means it does not show tags anymore ... probably should be adjusted in future. I left there a commented block for tags just in case.

branch list in repo instance & colors: not that easy as it seemed...

Had to split includes because repo used porcelain and transport uses repo. I've put reading branches to refresh. Please have a look, I didn't check repo code much so I'm not sure this is 100% proper place and how to use it better in the class. And in particular refresh is not called before `page=>render_repo_top` ... I can add refresh somewhere at the beginning of main_page rendering. But actually now I'm also thinking about storing symref in repo persistence (just as a part of common repo info) - maybe it is better and always accessible. One worring thing - what if repo changes HEAD ref - at which moment the program should verify it and adjust repo record. 

PRing now.

**Comment by larshp** [comment]
HEAD switch: hmm, not sure, but I also guess this is something that will not happen very often

**Comment by sbcgua** [comment]
@larshp have a look at https://github.com/sbcgua/abapGit/commit/6230046d9b8480ec7a27fe310fb8844b2f269d21
what do you think ? (keeping head branch in repo persistence - checked and updated each refresh)

**Comment by larshp** [comment]
looks good to me

**Comment by sbcgua** [comment]
ok, will PR a bit later today

**Comment by sbcgua** [comment]
A question by the way: what do you think about replacing icons with svg or svg font ?
I'm playing with that background branch UI. Images have fixed color. And SVG can change it easily. 
Actually it is a question about not/keeping support for old IEs.

**Comment by larshp** [comment]
We can try changing the branch link to SVG, to see if it causes problems for anyone.

I'm not really comfortable with changing everything to SVG just yet, but we can try it on small scale first.

**Comment by sbcgua** [comment]
![image](https://cloud.githubusercontent.com/assets/15635498/18283707/2e8bf2a0-746f-11e6-83ec-efa32438b234.png)

![2016-09-06_20h18_12](https://cloud.githubusercontent.com/assets/15635498/18283709/31e3a470-746f-11e6-847e-d310aeaaf3b3.png)

OK, ready. If ok, I'll PR.
