### ISSUE TITLE
+Online instead of +Clone Button

### ISSUE THREAD

**Issue by frankahland** [larshp/abapGit#3112]
Hello,

the tutorial "Moving package into git" tells me to click the +Clone button. But i have a +Online button and it opens a different popup.
Please see screenshot. 
What can i do to move a package into git?
Thanks
Frank

![git](https://user-images.githubusercontent.com/54402030/70421974-30286d00-1a6b-11ea-8d34-c540143c20c5.PNG)

**Comment by mariusraht2** [comment]
You have to click the +Online button. Apply an url to an online git repo (e. g. https://github.com/larshp/abapgit.git) and a package like the tutorial states.

We should update it though.

**Comment by larshp** [comment]
pull requests welcome to file https://github.com/larshp/abapGit/blob/master/docs/guide-moving-package.md
