### ISSUE TITLE
Error Message "identical keys " after cloning

### ISSUE THREAD

**Issue by frankahland** [larshp/abapGit#3118]
Hello,

I clicked "+Online", 
entered the URL to our gitlab https://gitlab.isecnet.local/FA/m4s-main.git
entered the name of a package in the z namespace
left everything else as default (Branch = refs/heads/master   Folder logic = PREFIX)

After clicking OK i get the error messsage in the lower corner of the screen "identical keys", Message 00/0001,

Do you have an idea?

Thanks
Frank

**Comment by mariusraht2** [comment]
Could you make a screenshot from Advanced > Database util page please?

It seems there is a missing db entry for an existing repo during runtime. But it shouldn't reappear if you restart abapGit, because then it loads the repos by the db entries again. Exists the problem after a restart of abapGit?

**Comment by frankahland** [comment]
Restarting helped
