### ISSUE TITLE
Error: HTTP error 407 occured: ICM_HTTP_SSL_ERROR

### ISSUE THREAD

**Issue by srikanthnalluri8** [larshp/abapGit#3119]
Good morning
When i try to clone abap2xlsx, i been getting error ' Error: HTTP error 407 occured: ICM_HTTP_SSL_ERROR'. 

I have imported the certificates in STRUST and restarted the SMICM but still the problem persists. Please let me know if i need to do anything else.
![SMICM Error log](https://user-images.githubusercontent.com/43546145/70729479-eb9a0d00-1cc8-11ea-98b8-a54146ff40c8.PNG)

Thanks for the help

**Comment by larshp** [comment]
see https://docs.abapgit.org/guide-ssl-setup.html#note-about-github for solution

workaround is https://docs.abapgit.org/guide-import-zip.html

**Comment by srikanthnalluri8** [comment]
I shall reach out to my BASIS for further help, however the offline option solved my problem
Thank you
