### ISSUE TITLE
ATC Check - GEN_INCLUDE_NOT_EXEC dump

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapGit#3136]
I have a change document which generated not referenced includes.

When I try to upload changes to git some ATC checks are executed and those includes checks generates a dump
![image](https://user-images.githubusercontent.com/56556686/71582684-8c7f2980-2b0b-11ea-93c3-352a3fef7147.png)

Executing ATC checks from Eclipse or GUI it is performed without dump

**Comment by larshp** [comment]
Guessing, because the above does not contain all relevant information.

Method `create_objectset` in class `zcl_abapgit_code_inspector` must be changed to skip include programs.
