### ISSUE TITLE
Method exception content_data_error missing in 7.40 ehp 4 (IARP / IASP)

### ISSUE THREAD

**Issue by geert-janklaps** [larshp/abapGit#3139]
When importing the latest abapGit version in a system running SAP_BASIS 7.40 ehp 4, I run into an activation error related to method exception content_data_error that's not available in this release (interface if_w3_api_object).

This activation error occurs in:
- Class zcl_abapgit_object_iasp, method w3_api_set_changeable
- Class zcl_abapgit_object_iarp, method w3_api_set_changeable

Available method exceptions in 7.40 ehp 4:
![image](https://user-images.githubusercontent.com/2744548/71884830-56f4c480-3139-11ea-9272-fcd233907aa6.png)

Easy solution is to remove the method exception from the code, afterwards activation succeeds.
I can do the change if this approach is ok.

**Comment by christianguenter2** [comment]
Yes, please.

**Comment by geert-janklaps** [comment]
@christianguenter2 Pull request is available.

**Comment by christianguenter2** [comment]
@geert-janklaps Please try again
