### ISSUE TITLE
Create branch response is not processed correctly

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#314]
Tried to create invalid branch (with space) - `wrong branch`
it didn't work but abapGit didn't catch the mistake and switch to the new branch

Server response (**gitlab**):

```
000eunpack ok
002dng refs/heads/wrong branch funny refname
0000       
```

at **github** `ii_client->receive` fails with 'HTTP communication failure' (which is not descriptive) :(
http status 500, http body empty

**Comment by larshp** [comment]
it is still not parsed correctly, however a fix for above error was implemented in https://github.com/larshp/abapGit/commit/6b016bbb11b41b63fe6e2c259cdeb10022d3c097

**Comment by EduardoCopat** [comment]
I just tested this now and if you enter a branch name `invalid branch` (note the spaces), a new branch is created as `invalid-branch` with the `-`. 

Tested with Github

**Comment by larshp** [comment]
suggest changing the code so branch names with spaces are not allowed, as a check in abapGit before the request is sent to the server

**Comment by sbcgua** [comment]
Looks like there are some bugs

![image](https://cloud.githubusercontent.com/assets/15635498/22856083/5b77a20a-f093-11e6-9554-681f4e431c4e.png)

![image](https://cloud.githubusercontent.com/assets/15635498/22856089/62b50cec-f093-11e6-8430-c33d43f8b077.png)

**Comment by sbcgua** [comment]
t1_multi_file does not work as well :(
