### ISSUE TITLE
abapgit not supported in project <System name>

### ISSUE THREAD

**Issue by testabapdevops** [larshp/abapGit#3141]
When I tried to add new abap git repository, It is showing that abapgit repository is not supported for S4 Hana System 1709

Could you please let us know which system it supports or what we are doing wrong?

![image](https://user-images.githubusercontent.com/58258996/71892762-cedde180-316f-11ea-8106-92a9d6059871.png)

**Comment by christianguenter2** [comment]
You have to use SAPGui
https://docs.abapgit.org/guide-install.html

**Comment by himanshush13** [comment]
@christianguenter2 we are using the report only for abapgit. But in eclipse we installed abapgit repository, but the cloning green button is disable over there and the error message is that "abapgit is not supported in project <project name>.
we want to Clone Git repository into SAP Cloud Platform ABAP Environment with this process, 
as stated in this link-- https://developers.sap.com/tutorials/abap-environment-abapgit.html
but we can't.

**Comment by larshp** [comment]
step 7 in the tutorial is on the ABAP CP system, not the on-prem project(which I assume the above screenshot is from),
![image](https://user-images.githubusercontent.com/5888506/71901917-3e000980-3161-11ea-9be9-2ce2b8e52117.png)

**Comment by larshp** [comment]
@testabapdevops @himanshush13 did above help?

**Comment by testabapdevops** [comment]
Hi Larshp,

So I can conclude that abapgit plugin(eclipse) only supports cloud architecture (abap on cloud) not onpremise system.  So to checkin onpremise abap code we must use 'ZABAPGIT' program for git operations.

Thanks,
PV

**Comment by larshp** [comment]
yea

**Comment by blackfish5** [comment]
According to the Requirements [here](https://github.com/abapGit/ADT_Frontend) it seems that abapgit plugin IS supported in OnPremise system - but as the required repo is marked as deprecated/not working, this is not the case, right? So, SAP Cloud Platform ABAP Environment is still the only option, correct?
