### ISSUE TITLE
Deprecation of GitHub API password based authentication

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#3150]
> Hi @flaiker,
> 
> You recently used a password to access an endpoint through the GitHub API using SAP NetWeaver Application Server (1.0;752). We will deprecate basic authentication using password to this endpoint soon:
> 
> https://api.github.com/
> 
> We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.
> 
> Thanks,
> The GitHub Team

https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-passwords

https://developer.github.com/v3/auth/

This will break our current 2FA implementation for GitHub. Any ideas for a different approach where no private key is stored on a shared system?

**Comment by larshp** [comment]
well, we'd have to delete the 2FA implementation, as it wont work anymore

when users enter passwords(or personal access tokens) they are only kept in memory in the current session

**Comment by flaiker** [comment]
I guess the only reasonable thing to do is to lead users to generate an access token on the GitHub website and store it in a password manager so that it is entered in the normal http(s) authentication dialog. Which should just work. The current implementation is a bit of a workaround anyways, only to enable users to not need to remember the token and also not permanently store it somewhere unsafe.

- https://help.github.com/en/github/authenticating-to-github/accessing-github-using-two-factor-authentication#authenticating-on-the-command-line-using-https
- https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line

Not sure if this deprecation also affects on premise github enterprise installations and I also could not find a deadline as to when this will be changed.

**Comment by FreHu** [comment]
In SAP, passwords are going to be deprecated in favor of single sign on, see #3113.

**Comment by larshp** [comment]
deprecation date = July 1st, 2020

**Comment by jfilak** [comment]
Already deprecated in our GitHub enterprise and username + token authentication works but is extremely uncomfortable.

**Comment by larshp** [comment]
if its your private system you can hardcode the token in the user exit

alternatively see https://github.com/larshp/abapGit/pull/1262, Keepass can also be used to remember it on the frontend PC

**Comment by jfilak** [comment]
If ABAP code could access a web server on my workstation (i.e. http://localhost/) I could create a proxy server which would have access my Client Certificates.

**Comment by hf-kklein** [comment]
Just adding a similar but not same warning text from Github to make it searchable within Github Issues and search engines:

> On ... (UTC) you or an application you used recently accessed the deprecated Authorizations endpoint on the GitHub API with the useragent SAP NetWeaver Application Server (1.0;750).
>
> We will remove the Authorizations API endpoint on November 13, 2020. If you accessed the API via password authentication, then we recommend you use the web flow to authenticate. Please check that your app uses the web flow for authentication https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow
>
> You can learn more about these changes by visiting our developer blog https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/

**Comment by elsewhat** [comment]
Latest information from Gihub is that the endpoint will be removed November 13 2020. 
https://developer.github.com/v3/auth/#via-username-and-password

@larshp is there functionality today to supply Github personal access token directly in the UI ? 

As far as I can see, this is [the pull request](https://github.com/larshp/abapGit/pull/536) for the current functionality but after a quick glance didn't see any mention of inputing personal access tokens

**Comment by larshp** [comment]
yea, enter the token as the password in the login popup

**Comment by sbcgua** [comment]
just an idea: if (when) password dialog will be based on HTML, maybe it can be accessible by tools like 1password, lastpass and etc. Directly or via some JS

**Comment by larshp** [comment]
yea, just have to take care of the existing usages, https://github.com/larshp/abapGit/pull/1262

**Comment by pokrakam** [comment]
On a related note this also breaks the webby unit tests. There is no password prompt, it just goes straight to 401.
But since this only affects abapGit developers we can open a separate issue for it.

**Comment by abapChaoLiu** [comment]
I'd like to try to add support to [Web application flow](https://docs.github.com/en/developers/apps/identifying-and-authorizing-users-for-github-apps#web-application-flow). 

Any hint on where should I start?

The Web application flow is based on OAuth2.0.
Once the access to GitHub is granted, no user name or password is required anymore.
OAuth2.0 is only supported by  SAP_BASIS 7.31 SP5. (https://github.com/larshp/abapGit/pull/3302 and [OSS Note 1717249](https://launchpad.support.sap.com/#/notes/1717249)).

**Comment by larshp** [comment]
this topic is regarding the deprecation and removal of the API based password authentication

please create a new issue regarding oauth

**Comment by larshp** [comment]
I think just do it soon, instead of waiting
