### ISSUE TITLE
ZIP Package Download fails, if Package is in / Namespace

### ISSUE THREAD

**Issue by StevusPrimus** [larshp/abapGit#317]
Hi,

there is an error, when I try to download a zip package in / namespace. It occurs because the zip file name includes the /, which is obviously not a allowed character in a file name. I fixed it in the INCLUDE ZABAPGIT_ZIP:
  METHOD file_download.
...
LINE 112 ff:
```
lv_package  TYPE devclass.
  lv_package = iv_package.
   TRANSLATE lv_package using '/#'.
CONCATENATE  lv_package '_' sy-datlo '_' sy-timlo INTO lv_default.
```

Keep up the good work, it is really a great tool!!!!

**Comment by larshp** [comment]
cool, feel free to submit the change as a pull request
