### ISSUE TITLE
Missing Object TTYD

### ISSUE THREAD

**Issue by Fr4nc3sc0O** [larshp/abapGit#3214]
Hello,

I need to make a feasability test if it is possible for us to use abapgit in our systems. So
I have installed abapgit in our development system and tried to export everything to check if this would work. I found that we have several objects (29) in our system which are not supported from abapgit. For example we have the object type TTYD. 
I had a quick look into the code to check how to support the different objects. So I have seen that you made a class for each object in which you use the interface zif_abapgit_object and sometimes 
What else do I need to know if I want to code the support for all objects I need.

**Comment by larshp** [comment]
it looks like TTYD is a LIMU object type, abapGit works on R3TR level via objects from TADIR

![image](https://user-images.githubusercontent.com/5888506/74831544-bb4c9b80-5315-11ea-961a-cf5b16405509.png)

documentation for writing new serializers is at https://docs.abapgit.org/development/serializers.html, limited but there is a lot of examples in the code

**Comment by larshp** [comment]
@Fr4nc3sc0O see above

**Comment by larshp** [comment]
no reply, closing
