### ISSUE TITLE
Transaction, unknown CINFO

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapGit#3223]
I'm testing the import of some package in a Development system (NPL) and I can't import some transactions:
![image](https://user-images.githubusercontent.com/56556686/75702984-de346380-5cb6-11ea-906b-b4130796cd7b.png)

The problem is that field CINFO from TSTC can contain multiple values: Type + Authority Check + Enqueue.

Here is the logic from subroutine save_tcode in function group SEUK:
![image](https://user-images.githubusercontent.com/56556686/75703194-43885480-5cb7-11ea-8b32-ee0a7e3bc4c3.png)

**Comment by jrodriguez-rc** [comment]
I made a change for this but found that Authorization Objects are not supported
![image](https://user-images.githubusercontent.com/56556686/75764255-e2f02a80-5d3d-11ea-86b6-819f11d5fe86.png)

Do I open a new issue or do it here?

**Comment by larshp** [comment]
if doing separate fixes at weeks apart suggest different issues, if you intend fixing it together and now, then just keep this one issue
