### ISSUE TITLE
Dump because of non-existant $TMP sub package

### ISSUE THREAD

**Issue by thedoginthewok** [larshp/abapGit#3224]
We upgraded an internal SAP System to a newer release (S4 1709 to S4 1909). After the upgrade all sub packages of $TMP were gone.

This caused a dump when trying to open the abapGit repo in abapGit. After recreating the package, it worked again. There is already logic there to print an error message, but it fails.

In class [zcl_abapgit_gui_view_repo](https://github.com/larshp/abapGit/blob/0dba9e5af32ee558d416b2e226a00ff475d6038b/src/ui/zcl_abapgit_gui_view_repo.clas.abap) Constructor, there is this line 
```abap
mv_are_changes_recorded_in_tr = zcl_abapgit_factory=>get_sap_package( lv_package
                                                  )->are_changes_recorded_in_tr_req( ).
```
It raises exception zcx_abapgit_exception. This is caught in zcl_abapgit_gui->handle_action( ) and the exception object is handed over to method zcl_abapgit_gui->handle_error( ). 

The rest of the stack is visible in this screenshot:
![grafik](https://user-images.githubusercontent.com/6908247/75724158-10a58700-5cde-11ea-80e3-6ef166138601.png)

mo_repo_content is not bound while trying to render the error message. When I skip over the line 
```abap
ro_html->add( mo_repo_content->render( ) ).
```
I see a reasonable error message:
![grafik](https://user-images.githubusercontent.com/6908247/75724432-a6411680-5cde-11ea-8006-f41409b0db5b.png)

I suggest adding an `IF mo_repo_content IS BOUND. ... ENDIF.` around that line.

I don't know how usual it is for packages in $TMP to disappear, can someone shed some light on this?

Dump info
![grafik](https://user-images.githubusercontent.com/6908247/75722815-3ed59780-5cdb-11ea-9c0f-5573154a1430.png)
[OBJECTS_OBJREF_NOT_ASSIGNED_20200302_231437.zip](https://github.com/larshp/abapGit/files/4278162/OBJECTS_OBJREF_NOT_ASSIGNED_20200302_231437.zip)

**Comment by larshp** [comment]
thanks, pull requests welcome

yea, upgrades sometimes delete $* packages, see https://abapgit.slack.com/archives/C4KRH6CAJ/p1582035760056600 and https://github.com/larshp/abapGit/issues/284
