### ISSUE TITLE
Remove SHI3 at uninstall repository

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapGit#3229]
When repository is uninstalled, IMG Structures (SHI3) are not removed, they still exist and can be removed from SIMGH transaction so you can remove the package

**Comment by larshp** [comment]
can the issue be reproduced with https://github.com/abapGit-tests/SHI3 ?

**Comment by jrodriguez-rc** [comment]
No, I just check it and this is removed correctly.

I will try to find the case.

**Comment by mbtools** [comment]
https://github.com/abapGit-tests/CUS0 contains SHI3. As far as I can tell, uninstall works fine.

**Comment by mbtools** [comment]
Reopen, if you find a test case
