### ISSUE TITLE
Dump when reading repository with object which was moved to a different package

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#323]
Hello,

I have a repository for package Z3F_FA_MAPPER and moved one of its objects to package Z3F_FA_CLR_IN.
Both of these packages are children of package Z3F_FA_FULL_FACTORING_ALL.

In class ZABAPGIT_SAP_PACKAGE->CHECK() there is a LOOP at it_results. I have 80 records in there and the program dumps on record 72 which is the object moved to a different package. The dump is in on line 78 of method CLASS_TO_PATH().

That's because in line 77 of that method you have this:

```
        lv_len = strlen( lv_parentcl ).
        lv_path = iv_package+lv_len.
        IF lv_path(1) = '_'.
```

but:
- but LV_PARENTCL = Z3F_FA_FULL_FACTORING_ALL
- so: LV_LEN = 25
- but: IV_PACKAGE = Z3F_FA_CLR_IN
- so IV_PACKAGE+LV_LEN doesn't make sense and will yield an empty string
- which will result in a dump in the next line.

Let me know if you need any more information. I'd like to help correcting it but I'm not familiar with the code...

**Comment by larshp** [comment]
abapGit currently assumes that subpackage names are prefixes of their parent

eg.
ZFOOBAR has subpackage ZFOOBAR_`something`

so in your example if Z3F_FA_MAPPER is the top package, then subpackages are assumed to be prefixed with name 'Z3F_FA_MAPPER', eg subpackage might be Z3F_FA_MAPPER_FA_CLN_IN which will result in 'fa_cln_in' as the folder name in the directory structure

**Comment by nununo** [comment]
Hum... I see... I was not aware of that.

Two questions?
- Why that limitation?
- If that is not possible what can I do?

I take the opportunity to vent my anger at the fact that SAP doesn't have proper namespaces :( grrrrrrrr We are always forced to keep a long chain of IDs in the name... :(

**Comment by larshp** [comment]
with the improper namespaces :angry: I think it makes most sense with the current approach, and I'd like not to force a specific package name.

However I also realize that not packages may follow this naming scheme. I've been thinking of adding this as a setting in the .abapgit.xml file, to override the default package naming scheme with something different.

Perhaps a naming scheme could be to just remove the Z/Y/namespace from the package name and use that for the folder names.

**Comment by nununo** [comment]
Couldn't the folder structure simply use the full name of each package? In my case it would be:

Z3F_FA_FULL_FACTORING_ALL
Z3F_FA_FULL_FACTORING_ALL\Z3F_FA_MAPPER
Z3F_FA_FULL_FACTORING_ALL\Z3F_FA_CLR_IN

Another question: the fact that the problem occurred with an object which was moved to a different package, and since a repository is supposed to be restricted to objects of a specific package (right?) how is that object supposed to be handled since it is now part of a different package? Maybe this is a lame question since I still didn't fully understand how your wonderful engine does its magic.

**Comment by larshp** [comment]
structure: yeah, but it would be a manual action in the future to override the default handling. The setting could be saved in the .abapgit.xml file

a repository is restricted to objects in the main repository package and its subpackages

I'm not sure exactly why the error occurs in your case, we might want to try reproducing it. However I guess we need the alternative folder structure to fix it properly.

**Comment by nununo** [comment]
> structure: yeah, but it would be a manual action in the future to override the default handling. The setting could be saved in the .abapgit.xml file

Seems like a good option for me. I also feel tempted to try to adapt to your prefix constraint.

> a repository is restricted to objects in the main repository package and its subpackages
Right.

So what is the behavior when an object which belonged to the main package ZA of repository A is moved to a the main package ZB of repository B? It will be detected and added to repository B, right? But shouldn't it be removed from repository A? 

But it should not be treated as if it was deleted, since it still exists in a different independent package/repository B.

**Comment by larshp** [comment]
when staging files for repository A, the files for the moved object should appear in the files list where it is possible to delete the files from the object in the repository

when staging files for repository B, the files for the moved object should appear in the list and it should be possible to add the files

**Comment by nununo** [comment]
Understood. Thanks!

**Comment by nununo** [comment]
> abapGit currently assumes that subpackage names are prefixes of their parent

Having converted our package structure to this naming convention I must say that it now makes more sense. I like the approach and will adopt it in the future regardless of it being a current abapGit limitation ;)

This said, the dump is still annoying and time consuming. I had to constantly go into debug to find out which objects were causing the dump. Since there are several weird behaviors around TADIR (mostly unrelated to abapGit)... I found several scenarios:

1. the object existed in a different package. Solution: either move it to our package or delete it;

2. the object no longer existed but was listed in TADIR with DELFLAG = X. Solution: manually remove the entry from TADIR (knowing that it was never transported to another system);

3. the object no longer existed but was listed in TADIR and DELFLAG was not set. This is the most weird situation and I think (not sure, will try to find a test case if this happens again) that these objects were deleted by abapGit (could it be?). Solution: manually remove the entry from TADIR (knowing that it was never transported to another system).

Ideally this dump (related to the package hierarchy not respecting your prefix assumption) should be replaced by some sort of error handling.

Thanks,
Nuno

**Comment by larshp** [comment]
For each object type(includes = ZABAPGIT_OBJECT_*)  a method `lif_object~exists` is implemented, its purpose is to check if the object actually exists, as TRDIR-DELFLAG is unreliable.

I'm not sure I understand exactly when the dump happens, can you add a step by step description of how it can be reproduced? Is it when moving an object to a subpackage which has a shorter name than the parent main package?

**Comment by nununo** [comment]
The dump happens when a object ZA which belonged to the repository of package Z1 is moved to a package which is completely independent, for example Z2. 

And it happens, it seems, because somehow the code still expects part of it's path to be common.

**Comment by larshp** [comment]
I've reproduced a dump with the following setup, $CLAS is the main repository package,

![image](https://cloud.githubusercontent.com/assets/5888506/18408625/0c696cb6-7735-11e6-9449-3a7785eff6bd.png)

Before the dump abapGit shows warning:
![image](https://cloud.githubusercontent.com/assets/5888506/18408630/2435162e-7735-11e6-8cab-e40673a18afd.png)

so I'm not completely sure this is the same scenario, fixing...

**Comment by larshp** [comment]
try again, abapGit should show an error message and not dump,

![image](https://cloud.githubusercontent.com/assets/5888506/18408666/0fea2898-7736-11e6-810c-34b172d3efe2.png)

**Comment by nununo** [comment]
Great! I does not explode anymore. Thanks!

The fact that it says "only remote" is not exactly accurate, though, because the object does exist in the system so maybe it should say something else like "In wrong package" or something? Or am I getting it wrong?

**Comment by larshp** [comment]
true, but it should also show the error message "Package and path does not match for object" above the file list?

**Comment by nununo** [comment]
I like that it shows it at the top also... it's alarming :)

**Comment by larshp** [comment]
this is the best we can do for now, the place where "Only Remote" is determined does not know of other packages. Alternatively the error handling will need to be refactored/reorganized

**Comment by nununo** [comment]
If that's the case it's perfectly fine ;)
