### ISSUE TITLE
Repository "Remove" vs. "Uninstall"

### ISSUE THREAD

**Issue by hf-kklein** [larshp/abapGit#3241]
The documentation explains that the "Uninstall" button in the repository context menu removes the associated ABAP package from the system. What does the Remove button do?
![grafik](https://user-images.githubusercontent.com/23094997/75957571-97af5680-5eba-11ea-8aeb-43050c24da44.png)

Some background on my problem:
I tried to add an existing package to git but instead of [following the guide](https://docs.abapgit.org/guide-moving-package.html) I accidentially created an "Offline" repo that contains my package. Is it safe to click remove? Will the ABAP package stay in my system and only the offline repo is removed?

**Comment by g-back** [comment]
Yes, "Remove" only removes the reference to the repo. When you click on it, you get the following popup:

![image](https://user-images.githubusercontent.com/27279305/75960317-1fe42a80-5ec0-11ea-9fc9-b48307d6ef96.png)

But I suppose this could be explained explicitly in the docs.

**Comment by larshp** [comment]
yes, its safe to click remove, first thing that happens after clicking it is a popup explaining what will happen

the contents in the package will stay, only the abapgit repo reference is removed

**Comment by hf-kklein** [comment]
Thanks, it worked. I submitted a pull request #3242 that adds one sentence to the documentation.
