### ISSUE TITLE
Handle customizing transports in "Transport to Branch"

### ISSUE THREAD

**Issue by goreraks** [larshp/abapGit#3244]
Whenever the customizing content need to be handled in abapGit, one has to follow the below manual steps.
1. Create a BC set for the customizing content
2. Push the created BC set to git repository
3. Pull the BC set from git in another system
4. Activate the BC set using SCPR20 transaction to deploy the content

**Which steps can be automated?**
Steps 1 and 2: Create a BC set from transport & push the BC set to repository
Steps 3 and 4: During pull, these BC sets are de-serialized and activated to deploy the content

**Comment by flaiker** [comment]
Can you explain your use case? I typically use BC-sets to save the "default customizing" of the repository so I can deliver it to external systems for the installation process. So basically the stuff SAP delivers using client 000 and client copies. Since this doesn't happen often I don't need to process to be automated. So I am curious what your use case is.

**Comment by larshp** [comment]
do you want to deliver customizing to SAP standard tables, or only tables part of a custom development?

**Comment by goreraks** [comment]
I don't have any use case but I saw some issues raised related to handle/support of customizing content in abapgit.
My ideas is to generate a BC set for each customizing object and update the same BC set whenever the content is changed in that customizing object.

**Comment by larshp** [comment]
this is not easy, unless the customizing transport always contains the full set of customizing? which it does not, in a typical scenario the customizing transport contains incremental changes

**Comment by goreraks** [comment]
Yes, to handle such incremental changes, I thought of creating single BC set for each object i.e. 1:1 relation.
The flow would be like:
1. Maintain the customizing entry in the object via SPRO/SM30/SM34 ..etc
2. Use 'Transport to Branch' or new option to stage it to git repository
     > Check BC set(specific type) exists for the customizing object
     > No, then create a new BC set with content recorded in the transport
3. Maintain the customizing entry again i.e. new entry/delete/change
4. Use 'Transport to Branch' or new option to stage it to git repository
    > Check BC set(specific type) exists for the customizing object
    > Yes, then update the existing BC set with additional content

P.S - I believe, it is also possible to use the BC set as virtual container(means no design time artifacts need to be created in the package). Just push the SCP1 XML to git with content.

**Comment by goreraks** [comment]
@larshp , I have implemented the handing of customizing content via BC sets. Please check https://github.com/goreraks/abapGit/tree/HandleCustomizing
I have not created a pull request, As I wanted to get some initial feedback.
Current solution is only compatible in release 754, as no BC set metadata is being persisted for recording/importing the content in system.

**Comment by goreraks** [comment]
Closing this issue, as support for customizing will be handled with new report.
