### ISSUE TITLE
Provide HTTP Destination Support

### ISSUE THREAD

**Issue by Jens-Schwendemann** [larshp/abapGit#3254]
Dear all,

would it be possible to support HTTP Destinations (SM59) for Git repository server alternatively to keying in the server itself?

I think in part this was brought up in issue #1841 where the solution was a user exit. I would however prefer a more plug-and-play-ish solution which is configurable via abapGit GUI.

### I could think of the following benefits
- Offloading configuration to a place that SAP sees fit
- Benefiting from features already available within HTTP destinations including proxy configuration, User Authentication, including current user, technical user (whereever this makes sense) and even client certificate based auth using maybe a dedicated PSE
- Feeding in an HTTP destination into an ABAP HTTP client should be quite straightforward, so implementation costs should not be too overwhelming
- More clearness on which (outbound) connections an AS ABAP has. Basis could look into SM59 and get a sense that there are say 4 connections to different Git servers. If they are only visible within abapGit, only the user that created the connection / uses ABAP Git knows.
- At least give the opportunity for segregation of duties between developers and basis

### I see the following downsides
- In situations where you want to consume a large quantity of repositories from **different** servers, you will end up with lots of HTTP destinations
- Segregation of duties could lead to decreased processing times, e.g. if requesting an HTTP destination at basis would be some bureaucratic process
- two options (direct entry as is and additionally HTTP destination) would result in at least an increased effort for development / testing for fututere abapGit releases

Cheers
Jens

**Comment by larshp** [comment]
see https://docs.abapgit.org/ref-exits.html and https://github.com/larshp/abapGit/issues/1841

with this you can choose to enforce/allow different setups as required by your organization

**Comment by larshp** [comment]
@Jens-Schwendemann did above help?

**Comment by larshp** [comment]
no reply, closing
