### ISSUE TITLE
Method zif_abapgit_object~serialize - components udate and utime not available

### ISSUE THREAD

**Issue by dominikasbgw** [larshp/abapGit#3255]
Hi all,

While trying to activate the current release in our ECC6 EHP8 system I got 4 syntax errors (see screenshot below).

![image](https://user-images.githubusercontent.com/62097449/76509421-4c63ed80-6450-11ea-8cdb-031fdc7009da.png)

There are no components "udate" and "utime" in the objects "<ls_objects>" and "<ls_objects_text>".
"ls_objects" is referencing database table "TCDOBS".
"ls_objects_text" is referencing database table "TDCOBTS".
Both database tables do not have columns called "udate" or "utime".
There are no date or time columns in those tables at all.

What are "udate" and "utime" supposed to be used for?
Should they reference the columns "datum" and "uzeit" of database table "TCDRPS" maybe?
Is there an older build available which doesn't have that issue?
Please assist.

Best regards
Dominik

**Comment by christianguenter2** [comment]
Interesting. No problem here with ECC6 EHP7 (NW 740 SP16). UTIME and UDATE are there.

![image](https://user-images.githubusercontent.com/17437789/76511934-27717980-6454-11ea-866a-653de1d74265.png)

![image](https://user-images.githubusercontent.com/17437789/76511933-26404c80-6454-11ea-8bbf-4a3290d3421f.png)

**Comment by christianguenter2** [comment]
I suggest that we clear the fields dynamically.

**Comment by dominikasbgw** [comment]
Strange.
I checked two IDES systems (ECC6 EHP4 / NW 7.01 and S/4HANA 1610 / NW 7.51) which we have here and those fields are in neither one available.
Wondering when they got added and removed again.

**Comment by jrodriguez-rc** [comment]
Very strange, I have those fields in ECC6 EHP8 and in NW 7.52

**Comment by mbtools** [comment]
If I see it right, the tcd*s tables are shadow tables and could be from other releases (depending on previous upgrades). Function 'CDNAMES_GET' returns tcdrp, tcdob, tcdobt (without S). ty_change_document is therefore incorrect as well as the insert and delete statements into the tables with tcd*s. 
tcdrps > tcdrp
tcdobs > tcdob
tcdobts > tcdobts 
Then you can adjust the cleared fields accordingly ie remove the udate, utime loops.

**Comment by jrodriguez-rc** [comment]
@mbtools yes, they're shadow tables used by the transport system and function AFTER_IMP_CHDO to generate all depending objects

**Comment by dominikasbgw** [comment]
I investigated the difference.
It looks like SNOTE #2324651 "CD: Enhancement of program RSSCD_CHECK_GEN" (or SAP_BASIS 750 support package SAPK-75006INSAPBASIS) are adding fields "udate" and "utime" to the shadow tables "tcdobs" and "tcdobts".
