### ISSUE TITLE
The data object "<LS_OBJECTS>" does not have a component called "UDATE".

### ISSUE THREAD

**Issue by agiguere** [larshp/abapGit#3257]
I got an activation error

line 74036
error  The data object "<LS_OBJECTS>" does not have a component called "UDATE".

SAP_ABA 740 012

thanks

**Comment by larshp** [comment]
duplicate of https://github.com/larshp/abapGit/issues/3255 ?

**Comment by larshp** [comment]
@agiguere try again, latest version, PR is merged

**Comment by agiguere** [comment]
thanks

**Comment by larshp** [comment]
asumming it works? closing

**Comment by agiguere** [comment]
wait, I am testing it, I download the program from here is it ok 
https://docs.abapgit.org/guide-install.html

**Comment by agiguere** [comment]
I confirm the program compile without error, yes you can close this incident, thanks
