### ISSUE TITLE
CALL SCREEN (not modal) in modal dialog box not allowed

### ISSUE THREAD

**Issue by GiantCrocodile** [larshp/abapGit#3259]
Hello,

when I add a new online project and fill in git clone URL, package and press `Select branch`, I get this error in the status bar:

![grafik](https://user-images.githubusercontent.com/6271057/76640260-e3fc3580-654f-11ea-9278-9c6e3d91ddac.png)

Afterwards I can click OK or cancel and abapGit will close itself.

This does happen on NW 740 with abapGit 1.92 and 1.93.

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit/issues/658

workaround is to select the default branch, then switch after the repo creation

**Comment by GiantCrocodile** [comment]
Hi @larshp! Weird; Github search didn't find that issue when I did search for parts of the error message. You wrote:

`Click "change remote", enter wrong url(something that does not exist), click "select branch" => results in error`

I want to clarify that this did happen with a valid Git repository URL to a private repository.

**Comment by larshp** [comment]
duplicate, closing
