### ISSUE TITLE
Block destructive changes

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#326]
@larshp  Would you mind if I add a config parameter to block pulls/branch change?
The idea is to block occasional pulls for the repos where not all code features are supported. For myself I clearly mean text translations for some of our products (if you remember we discussed it once)
Maybe the parameter should also block "uninstall".

**Comment by larshp** [comment]
no problem, would it be a global setting or per repository?

**Comment by sbcgua** [comment]
per repo. I think for the moment to add it just via DB-util so it will be a part of repo persistence structure.

**Comment by sbcgua** [comment]
![2016-09-07_22h22_09](https://cloud.githubusercontent.com/assets/15635498/18325412/d914f976-7549-11e6-8dcb-d2d9d9b84dfc.png)

Overview:

- repo config has now param called `write_protect`
- affected commands: pull, reset, uninstall, switch branch (the popup shown but not swicthed), create brach (it is actually created but not switched)
- repo has now method `is_write_protected()`
- on the low level repo throws errors in `deserialize` and `set_branch`, on the high level pull and reset throw errors from router (for more specific error texts)
- Design: added `add_anchor` option crossout
- removed older styles by tte way
- pull, reset, etc are still displayd but crossed -  to show errors why they are disabled (arguable)

**Comment by larshp** [comment]
cool
