### ISSUE TITLE
SHA1 for file zcl_abapgit_object_chdo.clas.abap

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapGit#3263]
SHA1 for file zcl_abapgit_object_chdo.clas.abap in Git is not the same that local generated
![image](https://user-images.githubusercontent.com/56556686/76683429-4151be80-6604-11ea-9816-240f076e3c24.png)

That causes a constant modification detected
![image](https://user-images.githubusercontent.com/56556686/76683442-61817d80-6604-11ea-9d74-1d46ad5e90de.png)

When there are no differences for file:
![image](https://user-images.githubusercontent.com/56556686/76683456-71995d00-6604-11ea-87f3-a5d039032eb3.png)

Does someone have the same problem?

I can upload a new file with different SHA1.

I have the same problem in NW7.5 and NW7.52

**Comment by larshp** [comment]
try opening a pull request with the changed file, its typically a newline or other whitespace changes that causes this
