### ISSUE TITLE
Redesign home page

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#3269]
Core idea: promote repository overview page to the home page.
- The list can be toggled to only show favorite packages (should be faster to load).
- With no favorite packages, the tutorial can still be shown above the list

![image](https://user-images.githubusercontent.com/5097067/76703176-03ba6780-66d0-11ea-9682-7a5b84132acd.png)

![image](https://user-images.githubusercontent.com/5097067/76703154-ce157e80-66cf-11ea-9f0b-d0b64a5458b5.png)

You can also have buttons in the grid for syntax check/code inspector. These don't require serializing the repo so you get a good place from which to quickly check all of your repositories.

Then in the repo page, this part can go away. If you have a lot of favorites, it will start eating up space. The hamburger menu is not very useful either if the system contains a large number of repositories.
![image](https://user-images.githubusercontent.com/5097067/76703184-159c0a80-66d0-11ea-8ebf-5897abb45a60.png)

The top abapgit button can go home instead of the abapgit website, which is already linked to in two other places (help and footer).
![image](https://user-images.githubusercontent.com/5097067/76703335-737d2200-66d1-11ea-911c-7ed061a46337.png)

**Comment by sbcgua** [comment]
So do you propose to get rid of favorites at all ? I think if the repolist page shows favorites first by default this should be a good alternative.

**Comment by FreHu** [comment]
Yes, I wanted to unclutter the repo page. You would switch repositories by going home first.

**Comment by sbcgua** [comment]
... or with F2 for quicker access. Well I agree, I think it is a very right idea. I'd check more opinions though - quite a big UI change. @christianguenter2 @larshp what do you think ?

**Comment by christianguenter2** [comment]
I just stopped using favorites, because it becomes soon very crowded and it gets hard to find anything. I usually navigate with F2, great feature btw, or repo overview. So I like the idea to use/integrate the repo overview page as start page.

**Comment by mbtools** [comment]
Overall, I like the proposed home page design. Maybe add a toggle filter on the first column to show favorites only (but keep the sort order).

Long term some folder structure to organize repos would be nice.

**Comment by sbcgua** [comment]
> Long term some folder structure to organize repos would be nice.

Tags, I think tags is a good option
