### ISSUE TITLE
Table objects showing differences in abapGit even though objects are similar

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#328]
Hello,

After an initial clone where everything seems to run smoothly I still end up with differences in some objects. There are some more issues with other object types but in this issue I'll focus on tables.

Two tables show the following difference:

![image](https://cloud.githubusercontent.com/assets/532049/18346310/7031d6a4-75b7-11e6-97d3-fbab9b770a29.png)

It says the log flag is different. Assuming this flag refers to the "log data changes" option, I can confirm that this flag is similarly set in both systems for both tables. So somehow the tables were correctly replicated but the repository files seem to not have this flag set.

![image](https://cloud.githubusercontent.com/assets/532049/18346384/c1ced034-75b7-11e6-8849-3fbee61a076c.png)

**Comment by larshp** [comment]
field LOGFLAG = "Indicator for writing change documents"

can you check the XML data above the screenshot, my guess is that this is a field which refers to a SAP standard data element? And for this data element the indicator has changed between versions/systems

**Comment by larshp** [comment]
try again, I've added code to clear the field, since it was inherited from the data element it is not needed at TABL level

note that you have to commit changes for the source object again

**Comment by nununo** [comment]
It seems to be working now. Thanks!
