### ISSUE TITLE
Re-orginize includes

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#329]

**Comment by sbcgua** [comment]
Some include reorg. (Better to agree on it before any new commits ;) I hope I integrated correctly with d4d8b338103c06320c25b611e982236da21f54e6 - maybe worth to double check )

So summary:
`ZABAPGIT_PERSISTENCE_OLD` for obsolete persistence classes
`ZABAPGIT_GUI_ROUTER` - separate router
`lcl_log` moved to `ZABAPGIT_UTILS` (as it is util)
`lcl_html_action_utils` went to own include (because it refers persistence and to be closer to pages code where it is used)
`page_diff` and `page_explore` got own includes
all page includes went to `zabapgit_gui_pages`
own includes for `lcl_object_prog, fugr, clas`
`zabapgit_object` renamed to `zabapgit_objects_impl` (and contains only object_impl now)
All serializations went to `zabapgit_object_serialization`
Moved deferred definitions to `zabapgit_app` (arguable, but it is where they are used first, and that's quite early level class so I think it should be ok)

Did touch `zabapgit_objects` and `zabapgit_git` but there is some space for improvement.

If ok, I'll PR

**Comment by sbcgua** [comment]
Ah yes ! Stage didn't work from 1 try - it is OK ? After 1st commit htere were still objects to stage, so I did it second time. Strange. Is it some new feature ? Or a bug ? I hope I didn't break anything ;)

**Comment by larshp** [comment]
will take a look later today, didnt have time yesterday

**Comment by sbcgua** [comment]
ok, no prob :)
