### ISSUE TITLE
ZCL_ABAPGIT_TIME: Unit tests fail on NW 752 SP04 dev

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#3294]
![image](https://user-images.githubusercontent.com/17437789/78472557-32a98380-773a-11ea-856c-dd96d99302ef.png)

**Comment by mariusraht2** [comment]
UTC difference is being determined by TZON_GET_OFFSET with same import parameters two times but with different results:
![image](https://user-images.githubusercontent.com/45243391/78564480-c8b5da80-781c-11ea-9581-773052a1c83e.png)![image](https://user-images.githubusercontent.com/45243391/78564492-cce1f800-781c-11ea-9ef7-2ab130d535dc.png)

**Comment by mariusraht2** [comment]
Oh...of course summer and winter time..
