### ISSUE TITLE
Local class zcl_abapgit_gui_component as public

### ISSUE THREAD

**Issue by marcelloganzaroli** [larshp/abapGit#3297]
Latest build local class zcl_abapgit_gui_component is declared as public, the source code is not compiling

`CLASS zcl_abapgit_gui_component DEFINITION ABSTRACT
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS constructor RAISING zcx_abapgit_exception.
  PROTECTED SECTION.
    DATA mi_gui_services TYPE REF TO zif_abapgit_gui_services.
  PRIVATE SECTION.
ENDCLASS.`

**Comment by larshp** [comment]
thanks, will have a look later today

**Comment by larshp** [comment]
@marcelloganzaroli thanks for the bug report, try again, latest version

thanks to @christianguenter2 for doing the fix

**Comment by sbcgua** [comment]
@christianguenter2 thanks for a fix ! :+1:

**Comment by marcelloganzaroli** [comment]
You're welcome guys.
It's fixed in my environment.

**Comment by larshp** [comment]
the issue should not occur again, fixed in https://github.com/larshp/abapmerge/issues/101
