### ISSUE TITLE
Package interface with diff but not being updated

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#330]
Hi,

Initial status: both systems are synced through an existing repository.

In the original system:
1. Updated a package interface adding some objects to it (a data element).
2. Committed changed to the repository

In the destination system:
3. Refreshed abapGit and can now see a diff in the modified package interface identifying that it was changed
4. Pulled changes... but nothing happens
5. Reset local... still nothing happens

I did some debugging through the package interface code and all seems normal (it identifies the components that need to be added and seems to ad them although then nothing is added) but unfortunately I still couldn't figure out where the problem happens. Sorry. I'm still not familiar with your code.

**Comment by larshp** [comment]
the package interface object is quite new, think it needs more code to handle this scenario

https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_pinf.prog.abap

**Comment by larshp** [comment]
try again, use latest abapGit version

**Comment by larshp** [comment]
@nununo did you try it out, did it work?

**Comment by larshp** [comment]
@nununo this should also be fixed

**Comment by nununo** [comment]
Indeed it seems to work fine now as my interfaces are now in sync ;)
Thanks!!

**Comment by nununo** [comment]
It hasn't happened in a while so I don't have a fresh test case. I'll close this one and open a new one in abapGit the next time this happens to me. Thanks!
