### ISSUE TITLE
Pressing "View  Diff" causes a DUMP

### ISSUE THREAD

**Issue by RyabovAlex** [larshp/abapGit#3303]
Hello colleagues, 
When I'm Importing the Objects (CLASS) into the repository, I see expected difference in the code line. When I click "View diff" I get a short dump:

Dynamic type conflict
 MOVE_CAST_ERROR
 CX_SY_MOVE_CAST_ERROR

The issue is caused in the beginning of the Constructor:
mo_repo              ?= zcl_abapgit_repo_srv=>get_instance( )->get( iv_key ).

P.S. I'm using 1.94.0 version

Thank you.

**Comment by larshp** [comment]
can you help adding a screenshot of the dump, or a reference to the line number / method

**Comment by RyabovAlex** [comment]
Sure!
here  they are
![image](https://user-images.githubusercontent.com/4346510/79240299-452e6600-7e7a-11ea-9e05-17df704ff1c0.png)

![image](https://user-images.githubusercontent.com/4346510/79240281-3e075800-7e7a-11ea-9dd2-0d06924be892.png)

**Comment by christianguenter2** [comment]
I guess that's an offline repo? It's most likely due to #3283. I'll have a look.
