### ISSUE TITLE
SYNTAX_ERROR while pulling APACK project, IF_APACK_MANIFEST doesn't exist

### ISSUE THREAD

**Issue by sandraros** [larshp/abapGit#3308]
**Steps to reproduce**:

1. Given you use a classic ABAP system (not Cloud - maybe the issue happens on on-premise systems too)
1. Run ZABAPGIT
1. +online project https://github.com/SAP-samples/abap-platform-jak or https://github.com/SAP-samples/abap-platform-yy
1. Pull
1. Short dump SYNTAX_ERROR

![image](https://user-images.githubusercontent.com/34005250/79671272-95cef780-81c9-11ea-922e-a93acd0d70d2.png)

It happens at statement `CREATE OBJECT lo_manifest_provider TYPE (ls_manifest_implementation-clsname)`, which is either in class `ZCL_ABAPGIT_APACK_HELPER` or in class `ZCL_ABAPGIT_APACK_READER`. The reason is that the indicated manifest class uses the interface `IF_APACK_MANIFEST` but it doesn't exist.

**Analysis**:

In non-Cloud SAP systems, abapGit doesn't need to work with `IF_APACK_MANIFEST` but it should not short dump if the pulled project is intended to be installed in Cloud system.

**Proposed solution**:

Don't analyze the manifest class if it has a syntax error.

**Comment by goreraks** [comment]
@larshp Please check, I think this issue can be closed.

**Comment by larshp** [comment]
@sandraros can you try again?

**Comment by sandraros** [comment]
Yes, thank you it works

(now, on my trial developer edition 7.52, while deserializing zcl_xx_apack_manifest, the line INTERFACES: if_apack_manifest. of the repository is turned into INTERFACES: zif_apack_manifest. so this line doesn't prevent from compiling anymore; not talking about ABAP_BOOLEAN which doesn't exist in 7.52 but that's another issue)
