### ISSUE TITLE
Dump CREATE_OBJECT_CLASS_NOT_FOUND

### ISSUE THREAD

**Issue by hardyp** [larshp/abapGit#3315]
I set up the option in abapGit to run a background job each night to get the latets version. Each night it dumps trying to create a class calledd PULL which obviously does not exist.
![image](https://user-images.githubusercontent.com/7078215/79969256-966ed300-84d4-11ea-90ff-27efb1e29d13.png)

Class ZCL_ABAPGIT_BACKGROUND method RUN.

It could be this is too problematic to ever work, in which case maybe the background option should be removed from the abapGit menu.

**Comment by larshp** [comment]
whats the value of `<ls_list>-method` ?

**Comment by hardyp** [comment]
It is PULL

**Comment by hardyp** [comment]
![image](https://user-images.githubusercontent.com/7078215/79971322-7bea2900-84d7-11ea-8d74-66c509a115b2.png)

**Comment by mbtools** [comment]
@hardyp the proper value for <ls_list>-method should be ZCL_ABAPGIT_BACKGROUND_PULL. So check how lt_list is being put together.

**Comment by hardyp** [comment]
First the contents of table ZABAPGIT is read with key BACKGROUND. It looks like it is getting an XML string with the user name (email) to use to connect with GitHub. It the fills this structure from the XML.
![image](https://user-images.githubusercontent.com/7078215/83504050-5c4b1500-a507-11ea-81f2-33e8b9b26385.png)

**Comment by hardyp** [comment]
The SETTINGS are a table of KEY/VALUE pairs. The class methods are both static so I will write a test program and debug it.

**Comment by hardyp** [comment]
![image](https://user-images.githubusercontent.com/7078215/83506305-56a2fe80-a50a-11ea-91e5-163a5c1c2706.png)

OK, let us see how this gets built up (or not)

**Comment by hardyp** [comment]
The XML contains the method name PULL, but the transformation does not extract the username, and the password is not even in the XML as far as I can see.

**Comment by hardyp** [comment]
So, instead of PULL the value should be ZCL_ABAPGIT_BACKGROUND_PULL, and the username and password has to be extracted from the XML string, and the password needs to be set in the XML string i.e. in the ZABAPGIT table.

**Comment by larshp** [comment]
I think this was changed in the code very long time ago, try modifying the XML via the db util, and set it up the background from scratch

![image](https://user-images.githubusercontent.com/5888506/83507837-63533280-a4c9-11ea-991e-a141ab1f76f4.png)

**Comment by hardyp** [comment]
OK I added the entries manually, and all was well.

I then set up a new background pull for the "code pal" and this time the correct XML entries were saved. Therefore this issue is closed. The root cause was me setting up the background pull a long time ago, before the code was fixed.

I would end by saying this is a FANTASTIC bit of functionality and I am so happy I have got it working at last.
