### ISSUE TITLE
Ignored subpackages are checked by code inspector

### ISSUE THREAD

**Issue by JSB-Vienna** [larshp/abapGit#3316]
Hi Lars,
I did the following REPO settings for my main package. The object list was correct, but the error list of the code inspector refers to objects that are part of the subpackages. Did I something wrong?
![grafik](https://user-images.githubusercontent.com/30773503/80119092-88c75500-8589-11ea-93ec-1a1b391295c6.png)
BR, Jens

**Comment by larshp** [comment]
The "Ignore subpackages" setting currently only effects which sub objects to be serialized, don't think it has any effect in the code inspector run from abapgit

could probably implement it 🤷

**Comment by JSB-Vienna** [comment]
Depends on you. The settings somehow suggest that only the quantity described here is checked. It is a lower prio in any case.
