### ISSUE TITLE
abapGit PlugIn for eclipse - API deprecation notice

### ISSUE THREAD

**Issue by nomssi** [larshp/abapGit#3317]
I received this information after using the abapGit Plugin for ABAP Cloud Platform (trial version):

On April 25th, 2020 at 05:27 (UTC) you or an application you used recently accessed the deprecated Authorizations endpoint on the GitHub API with the useragent SAP NetWeaver Application Server (1.0;779).

We will remove the Authorizations API endpoint on November 13, 2020. If you accessed the API via password authentication, then we recommend you use the web flow to authenticate. Please check that your app uses the web flow for authentication https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow

You can learn more about these changes by visiting our developer blog https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/

**Comment by flaiker** [comment]
Do you use 2FA? See #3150

**Comment by larshp** [comment]
ref https://github.com/larshp/abapGit/issues/3150

**Comment by larshp** [comment]
duplicate, closing
