### ISSUE TITLE
UI: DB page readability improvements

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#332]
Piece of xml in DB util list does not represent the essence of entry well, it is difficult to find what you search if there are many entries. So I decided to improve a bit. It should be something like this (not yet finished):

![image](https://cloud.githubusercontent.com/assets/15635498/18386194/f773f6ec-769d-11e6-877a-62aacb45ddbf.png)

Do you think some more information can be shown here (or differently) ?
Also I have doubt: To extract the data I actually parse (regex) the xml (I'll make a preliminary commit in a moment). I think this is safer because repo_svr caches the data if I understood well. Does it seems OK ?

**Comment by larshp** [comment]
looks good

for the WHEN OTHERS case, just fallback to rendering the xml?

**Comment by sbcgua** [comment]
> for the WHEN OTHERS case, just fallback to rendering the xml?

Good idea.

![image](https://cloud.githubusercontent.com/assets/15635498/18408541/25dce262-773b-11e6-9e15-677d241ed4ff.png)

(of course USER was just for simulation)

**Comment by sbcgua** [comment]
btw added a feature to gui/router: 
- there is now new `event_state-new_page_replacing` which does not store previous page as history. This is different from `bookmark`. Bookmark is an intentional event to skip some history which otherwise **can** be followed with `back` (like in stage). And replacing is actually a jump with preserving the same parent page. 
- `on_event` now receives `iv_prev_page` - class name of the currently displayed page - which can be used in routing (see db_display/edit in router)
