### ISSUE TITLE
Second 'pull' sends no object selection and overwrites objects

### ISSUE THREAD

**Issue by JSB-Vienna** [larshp/abapGit#3320]
Hello Lars,
I used the zip-import. As I am still not familiar with all functions, I tried the pull-action and got a popup to mark which objects should be overwritten. I cancelled this dialog to check first in the difference view. Then pulled again expecting to get the selection dialog again, BUT! it comes no dialog up and overwrites all objects without asking anything- not ideal :(.
Please have a look at it.
Thanks a lot.
Br, Jens

**Comment by larshp** [comment]
sorry about the delay, can you try again, this might have been fixed in the meanwhile

**Comment by JSB-Vienna** [comment]
Hi Lars, thanks for the update, but I don't when I can retry this. So I close this and open a new issue refering to this issue.
