### ISSUE TITLE
Texts,Labels, etc... are not taken into account, when IMPORTING a Web Dynpro component

### ISSUE THREAD

**Issue by KDS42** [larshp/abapGit#3324]
Problem:
When exporting and importing a Web Dynpro component, instead of the texts,labels,etc. only GUIDs are shown. 

Solution:
Web Dynpro texts are stored as SOTR objects - analogue to messages of the ABAP Exception classes.  The existing logic of the handling was partly reused for the WDA texts. Just compare the attached changes of the attached file to the current 1.94 version:
[ABAPGIT_WDA.txt](https://github.com/larshp/abapGit/files/4539338/ABAPGIT_WDA.txt)

**Comment by larshp** [comment]
Pull requests with changes are welcome 😄

**Comment by mbtools** [comment]
Closed by https://github.com/larshp/abapGit/pull/3681
