### ISSUE TITLE
 Error: HTTP error 421 occured: ICM_HTTP_SSL_PEER_CERT_UNTRUSTED 

### ISSUE THREAD

**Issue by kymcaris** [larshp/abapGit#3325]
Hello, I am encountering this error when trying to open the repo in abapGit. Can someone please advise?

<img width="960" alt="Screenshot_5" src="https://user-images.githubusercontent.com/63042009/80461109-5fcb0980-8967-11ea-91e2-dae4a8889307.png">

This is what I am following:
https://developers.sap.com/tutorials/abap-environment-abapgit-transfer.html

Thanks!

**Comment by flaiker** [comment]
Hi, please take a look at https://docs.abapgit.org/guide-ssl-setup.html

**Comment by kymcaris** [comment]
> Hi, please take a look at https://docs.abapgit.org/guide-ssl-setup.html

Thank you! Problem solved. :)
