### ISSUE TITLE
GitLab login with Personal Access Token

### ISSUE THREAD

**Issue by BlackmanCC** [larshp/abapGit#3328]
Hi,

I want to login to gitlab (private server) with a "personal access token" [https://docs.gitlab.com/ee/api/#personal-access-tokens](url)

I already read #2879 and tried out following:

  METHOD zif_abapgit_exit~http_client.

    IF iv_url CP 'https://gitlab...'.
      ii_client->request->set_header_field(
        name  = 'Private-Token'
        value = 'ahfalshsfljfsakljlkfj' ).   "Token 

   ENDIF.

  ENDMETHOD.

I also tried other ways using ii_client->request->set_header_field but gitlab still wants usernanem + password for login.

**Comment by larshp** [comment]
can it be reproduced on the public gitlab?

a while ago it worked just by typing username, and then the PAT as password, like on command line

**Comment by BlackmanCC** [comment]
If I use 

curl -k https://gitlab....../api/v4/projects?private_token=MV8cTcf8Dos*** 

I get the repo list as result without login. 

I just do not know how I pass the parameter in ABAPgit exit like shown.

**Comment by larshp** [comment]
can it be reproduced on the public gitlab?

**Comment by BlackmanCC** [comment]
sorry. no. I was not able to reproduce it because it shows all public repos even if I use the token.

**Comment by g-back** [comment]
have you tried this example, taken from the issue you referenced? it looks like you forgot the `authenticate` part, at least from what you wrote.
```abap
  METHOD zif_abapgit_exit~http_client
    IF iv_url CP 'https://enterprisegithub'.
      ii_client->request->set_header_field(
        name  = 'authorization'
        value = '' ).

      ii_client->authenticate(
        username = 'username'
        password = 'token' ).
    ENDIF.

  ENDMETHOD.
```

**Comment by BlackmanCC** [comment]
If I do it like this I get a 403 (forbidden). I also get a 403 with username+password with the code above.

**Comment by BlackmanCC** [comment]
Can't I add the private_token as parameter in abapgit user-exit like shown in the curl example above?

**Comment by flaiker** [comment]
> Can't I add the private_token as parameter in abapgit user-exit like shown in the curl example above?

Your curl example uses the GitLab specific REST API. abapGit uses the vendor agnostic Git over Http "API". These are two different protocols and the token based authentication is usually specific to the former. As Lars mentioned you can have luck that it just works as a password with basic http authentication.

Have you tried this approach? https://stackoverflow.com/questions/25409700/using-gitlab-token-to-clone-without-authentication/29570677#29570677

Using the username oauth2 and your token as a password in the dialog or using the exit?

**Comment by BlackmanCC** [comment]
It works now with following code:

       ii_client->request->set_header_field(
             EXPORTING
               name  = 'authorization'
               value = '' ).

       ii_client->authenticate(
         EXPORTING
           username             = 'dummyusername'
           password             = {token} ).

The username does not matter, but is obligatory, so I use a dummy.

I found the error in my gitlab. Thanks for the fast help.

**Comment by larshp** [comment]
"found the error in my gitlab", did you change something in gitlab? can you help sharing the solution for future reference?

**Comment by BlackmanCC** [comment]
the user i used did not have enough rights on the repo. I think making clear, that the username is not important can help others with similar problems.
