### ISSUE TITLE
Object deleted shows DIFF but it's not clear that it does not exist

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#334]
Hello,

1. I cloned abapOpenChecks even though I already had an older copy in the system;
2. I found that class ZCL_AOC_CATEGORY was showing a DIFF which consisted of a slight change in code spacing;
3. So I decided to deleting the class so that it would be pulled again;
4. But the class is now listed twice: once at the top and again as an object with DIFF;
5. When I press the DIFF it says "file not found locally".

![image](https://cloud.githubusercontent.com/assets/532049/18395072/c4257a4c-76b4-11e6-8f2c-611b5788fc45.png)

I believe this is not clear because it makes it hard to distinguish an objects which doesn't exist from an object which exists with differences.

I guess the file should only be shown once, at the top, right?

Thanks,
Nuno

**Comment by nununo** [comment]
Hum... after doing a RESET LOCAL I still get the same differences in the class. I guess it's probably due to differences in ABAP version:

![image](https://cloud.githubusercontent.com/assets/532049/18395176/4d9b77ae-76b5-11e6-802c-cf3a1b23ce02.png)

Anyway, regardless of this, the issue explained above still applies.

Cheers,
Nuno

**Comment by larshp** [comment]
I dont think this is something that can be fixed

in older SAP versions(eg. 731) class CL_OO_SOURCE is used for creating the class,
https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_clas.prog.abap#L886

and in newer ADT functionallity is used
https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_clas.prog.abap#L915

The old approach has issues with the whitespace. Above issue should not be a problem on 740 as abapGit will then use the ADT functinoallity

**Comment by nununo** [comment]
But do you refer to the spaces that cause the diff? That's not a big deal. My concern is with the fact that objects that don't exist locally show up in the list with a DIFF link. That's what's confusing and misleading. Is this intentional behavior?

**Comment by larshp** [comment]
spaces(I usually only read the screenshots :smile: )

but fixed, try again

![image](https://cloud.githubusercontent.com/assets/5888506/18408398/08950fce-772f-11e6-808c-177b451af09a.png)

**Comment by nununo** [comment]
Perfect now! Thanks! And great idea to show all the diffs at the top!

**Comment by larshp** [comment]
cool, @sbcgua fixed so that the diffs are at the top
