### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#3340]
@christianguenter2 

also IF_WB_OBJECT_OPERATOR does not seem to exist in 751

![image](https://user-images.githubusercontent.com/5888506/80941426-b2327d00-8de2-11ea-833c-9dc839f256e7.png)

**Comment by christianguenter2** [comment]
Damn, I'll have a look.

**Comment by larshp** [comment]
probably works on the versions that have the object types, so no panic
