### ISSUE TITLE
ZABAPGIT_FULL Installation Source Syntax Error for class CL_CLS_ATTRIBUTE

### ISSUE THREAD

**Issue by habrahams** [larshp/abapGit#3353]
Hello All,
I am installing AbapGit on a new system via the initial installation Program.
There is however a syntax error.
Method "IF_CLS_ATTRIBUTE~SET_HIDE_ICON" is not declared or inherited in class "CL_CLS_ATTRIBUTE". -
![image](https://user-images.githubusercontent.com/16045067/81392288-bd591600-911e-11ea-84da-1deed8461d22.png)

I did do a search to see if someone else has already raised this issue, but I could not find anything.
Regards,
Harry

**Comment by larshp** [comment]
thanks, might be caused by the recent merge, https://github.com/larshp/abapGit/pull/3338

I'll have a look

**Comment by larshp** [comment]
as a workaround, try gabbing the build from yesterday, https://github.com/abapGit/build/tree/f254f2427183a993a22b422037b0e2bfa9a49f37

**Comment by larshp** [comment]
or well, just comment the single line

reference is https://github.com/larshp/abapGit/pull/3346

**Comment by jfilak** [comment]
Yep, that's my fault. I would say that the method is present only in our systems.

How can I call it dynamically?

**Comment by habrahams** [comment]
Thanks for the prompt response Lars!
I'll grab the build from yesterday.

**Comment by larshp** [comment]
@habrahams just comment the line with syntax error in it, its just a single line

**Comment by larshp** [comment]
@habrahams fix merged, the build will automatically update in a bit, let us know if you find more issues

thanks for the bug report 👍
