### ISSUE TITLE
Update of abapGit does not restart abapGit

### ISSUE THREAD

**Issue by mbtools** [larshp/abapGit#3358]
When updating abapGit itself from Github, it remains in the current session. IMHO, this can easily lead to inconsistencies. 

Any update of itself should force a restart of abapGit.

**Comment by larshp** [comment]
true, any suggestions on how to solve this?

**Comment by jfilak** [comment]
My two cents: don't use abapgit to update abapgit, use sapcli or Marcello's tools from command line :)

**Comment by FreHu** [comment]
If you actually run into the updated code, abapgit will dump so I think you cannot actually screw anything up but it's not usable without a restart either.

**Comment by larshp** [comment]
typically it works, but yea, there are some examples where the full report must be installed to fix issues

perhaps add some documentation / helper tools to update from command line?

**Comment by mbtools** [comment]
I tried this and it seems to do the trick (at least for online updates from this repo or forks). 

ZCL_ABAPGIT_REPO->DESERIALIZE
...
   COMMIT WORK AND WAIT.

    " If abapGit was used to update itself, then restart
    IF ms_data-url CS '/abapGit.git'.
      MESSAGE i000(0h) WITH 'abapGit was updated and' 'will restart itself'.
      SUBMIT (sy-cprog).
    ENDIF.

  ENDMETHOD.

**Comment by jfilak** [comment]
@mbtools have you ever suffered  from a crash of abapgit while it was updating itself? It has happened to me serveral times. Because of that I have be working on sapcli's `checkin` feature - it already works for me, but I haven't released it yet because it is not fully covered by tests :(

Perhaps, Marcello can create another TypeScript thingy for offline abapGit updates too.

**Comment by larshp** [comment]
for worst case scenario I keep the compiled long report as ZABAPGIT_FULL so it can be run to fix a failed update
