### ISSUE TITLE
Hello! Updated my abapGit installation just now, and I'm having short dump when running tcode ZABAPGIT. I think it's caused by the removal of the cache_asset alias.

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#3361]
> Hello! Updated my abapGit installation just now, and I'm having short dump when running tcode ZABAPGIT. I think it's caused by the removal of the cache_asset alias.
> 
> ![image](https://user-images.githubusercontent.com/36019912/82017767-78048d80-96b6-11ea-91b2-819c301e3c77.png)

_Originally posted by @jinigirl in https://github.com/larshp/abapGit/pull/3355#issuecomment-629050785_

**Comment by larshp** [comment]
@jinigirl are you using the long report or the development version?

**Comment by jinigirl** [comment]
@larshp I'm using the development version (updated via abapGit itself)

**Comment by larshp** [comment]
try deleting the class manually and creating it manually, code is at https://github.com/larshp/abapGit/blob/master/src/ui/core/zcl_abapgit_gui.clas.abap

it it does not work, install the full report, https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap as report ZABAPGIT_FULL, and try updating again

**Comment by jinigirl** [comment]
the first workaround worked! Thanks @larshp!

**Comment by larshp** [comment]
👍 closing

**Comment by larshp** [comment]
sometimes the self update messes up, also see https://github.com/larshp/abapGit/issues/3358

**Comment by jinigirl** [comment]
oh I see! I wondered what could have caused the issue, when there are no differences with the code from self-update, and when I manually created it.

**Comment by nomssi** [comment]
I had the same issue and I used the same workaround (copy the current code for classes ZCL_ABAPGIT_GUI **and** ZCL_ABAPGIT_HTML).

**Comment by larshp** [comment]
hmm, wonder what might be special about those classes
