### ISSUE TITLE
Access private Bitbucket repository with SSH key

### ISSUE THREAD

**Issue by hendrikfreytag** [larshp/abapGit#3364]
Hi,
I have a bitbucket repository which can be accessed with SSH keys. Is it possible to enter a private key somewhere in abapGit to get access to this repository?
Cheers,
Hendrik

**Comment by larshp** [comment]
afraid not

abapGit supports only git over HTTP, ie. no SSH

**Comment by hendrikfreytag** [comment]
I found out I can generate app passwords to use http in Bitbucket. So everything works now. Thank you.

**Comment by larshp** [comment]
closing

**Comment by larshp** [comment]
@hendrikfreytag https://github.com/open-abap/open-abap-ssh
