### ISSUE TITLE
Purpose of Advanced -> Page playground

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#3368]
![](https://user-images.githubusercontent.com/5097067/82154524-d6746c00-986e-11ea-996f-ddce4a87a8b1.png)

Page playground asks for a page name, then instantiates and switches to that page. But if the page has constructor parameters, it will dump. Most pages can't be created because of this.

![](https://user-images.githubusercontent.com/5097067/82155249-c7dc8380-9873-11ea-8b5b-ceae8655850e.png)

The dump is easy to fix, but is this feature used? Maybe it could be removed entirely to simplify the menu.

@sbcgua  probably you know the most about it

**Comment by sbcgua** [comment]
yeah, that was it was a tool to test new pages. I made and used it a couple of times. But I don't anymore. And current architecture of UI allows to quickly create a side program to test one page. I think this feature can be removed. 
Would you do it ot you prefer me to do it ? (if latter - after #3362 merge)

**Comment by FreHu** [comment]
I can do it, deleting is fun.

**Comment by sbcgua** [comment]
sure, go forward :)
