### ISSUE TITLE
Data loss when switching branches

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#337]
Repeatable case
Branches: master, branchA - current is master
2+ objects in repo
1. program 1 changed in repo online
2. program 2 is changed locally
3. abapGit displays 2 diffs and just Pull (a bit misleading btw)
4. I switch branch to branchA (which does not have local change of p2)
5. Answer No on "It looks like object xxx has been modified locally, overwrite object?"
6. Branch switched, p2 preserved - good (although arguable logic by the way - p2 may differ between branchA and master also)
7. Now I switch back to master
8. the message about "modified locally" does not appear, p2 is silently overwritten
   remaining repo state - both p1 and p2 display diff button (both are empty) and Stage is displayed.

**Comment by larshp** [comment]
guess this is similar to https://github.com/larshp/abapGit/issues/291

**Comment by sbcgua** [comment]
Indeed, seems very similar. Shell I close ?
At the same time point 6 can become as a separate issue - to me it seems that switching without stashing is prone to issues. Of course stashing is quite difficult to implement here. Maybe just forbid switching from "dirty" local state ?

**Comment by larshp** [comment]
is this still relevant? Currently, it does not pull automatically when switching branches?

**Comment by sbcgua** [comment]
I guess let;s close, attach/detach implemented + new status. This issue, if still exists, should be then formulated differently anyway.

**Comment by larshp** [comment]
closing
