### ISSUE TITLE
abapGit does not serialize DSYS documents when the name contains a namespace-prefix

### ISSUE THREAD

**Issue by Elberet** [larshp/abapGit#3374]
When a documentation object (here: a `CHAP` via SE61) has a name that contains a namespace, e.g. `/FOO/DOCU`, abapGit fails to serialize the object.

**Reproduction:**
* Create a namespace, e.g. `/FOO/`.
* Create a development package and (offline) abapGit repository in that namespace.
* Create a CHAP document in that package and include the namespace as a prefix in the document name, e.g. `/FOO/DOCUMENT`.
* Export the package in abapGit.

**Analysis:**
The document created above will have a a TADIR entry of type `R3TR DSYS` with object name `<prefix> 'CHAP' <remainder of document name>`, e.g. `/FOO/CHAPDOCUMENT`. However, in the document storage system, including table DOKIL which is read in the exists-check in `ZCL_ABAPGIT_OBJECT_DSYS`, the document is referred to as `'CHAP' <full document name>`, e.g. `CHAP/FOO/DOCUMENT`. This mismatch causes the exists-check to fail, so abapGit will ignore the TADIR entry entirely.

1. Line 43 here is broken, instead of just removing the leading four chars the constructor must first remove the namespace prefix, if any: https://github.com/larshp/abapGit/blob/840d818b2d6bbb2c80062c3dc557a8e378400445/src/objects/zcl_abapgit_object_dsys.clas.abap#L37-L45

2. The use of `mv_object` in line 118 here is broken, because the TADIR object name is not the same as the object name in the document tables: https://github.com/larshp/abapGit/blob/840d818b2d6bbb2c80062c3dc557a8e378400445/src/objects/zcl_abapgit_object_dsys.clas.abap#L114-L122
   This problem is repeated in most other uses of `mv_object` throughout the class, where that value is passed into the docu system as the document's name.

I'm planning to work on a fix myself, but would be glad if someone with more experience with agapGit and the documentation system could verify these findings. 🙇

**Comment by flaiker** [comment]
I have the same behavior. (I didn't know these objects were supported until now because they never showed up)

**Comment by Elberet** [comment]
Yeah, when an object class claims that an existing TADIR entry doesn't actually exist as an object, abapGit should probably complain to the user... that situation should always be indicative of a broken system or bug in abapGit.
