### ISSUE TITLE
Purpose of explore page

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#3376]
The page points to https://dotabap.github.io/explore.html

The clone button just prefills the repo url so it's not that much help. You could just have a link to dotabap.org in the help section. 

![](https://user-images.githubusercontent.com/5097067/82472251-3023a300-9ac8-11ea-9492-3fae206f7e03.png)

**Comment by larshp** [comment]
yea, makes more sense, plus list is getting too long in the GUI

**Comment by sbcgua** [comment]
I was it sure it would be the next target :)))
