### ISSUE TITLE
Instalation ZABAPGIT_FULL

### ISSUE THREAD

**Issue by petrhos** [larshp/abapGit#3377]
Hi,

I'm getting the error when installing/running [ZABAPGIT_FULL](https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap):

> Direct access to components of the global class ZCL_ABAPGIT_STAGE is
> not possible. The statement CLASS ZCL_ABAPGIT_STAGE DEFINITION LOAD is
> missing.

Line 11129.

Thanks

**Comment by larshp** [comment]
thanks

as a temporary workaround, try the build from yesterday, https://github.com/abapGit/build/blob/a0aab39001246301c0207a65a6332b97d39fe9fd/zabapgit.abap

**Comment by larshp** [comment]
@petrhos thanks for the bug report

should be fixed in latest version, try again

**Comment by larshp** [comment]
closing
