### ISSUE TITLE
Docs inside abapgit

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#3379]
Could we render the docs directly instead of a separate tutorial, then rework the welcome page?

![](https://user-images.githubusercontent.com/5097067/82479077-2ef77380-9ad2-11ea-9245-e35f21fdc0c5.png)

**Comment by larshp** [comment]
just link the docs instead? it will be easy

**Comment by FreHu** [comment]
acutally yeah, in #3269 I want to put the repo overview as the main page anyway which would replace the tutorial.
