### ISSUE TITLE
Refactoring lcl_popups

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#338]
Decided not to mix with #319  :)

So I checked a bit the usage of `lcl_popups` methods. They are mostly used in one place now. I'm not sure it is needed to separate into a separate class - it just to move a couple of lines from popups to routes or main_page.

BTW 'install' event code is duplicated in router and main_page. Is it OK if I move main_page handling to router ?
      
      repo_popup
      	OK
      create_branch_popup
      	OK
      repo_package_zip
      	external calls: lcl_zip=>export( lo_repo ).
      	used in: router->packagezip
      repo_new_offline
      	ext: repo_srv calls
      	used in: PAGE_MAIN-on_event
      switch_branch
      	ext: repo->set_*** calls
      	used: PAGE_MAIN-on_event
      delete_branch
      	ext: git->delete_branch
      	used: PAGE_MAIN-on_event
      branch_list_popup
      	ext: branches calls - but maybe it is OK 
      	used: FORMS include, internally in class
      repo_clone
      	ext: repo calls
      	used: PAGE_MAIN-on_event and duplicated in router

**Comment by larshp** [comment]
both router and main_page classes are quite large, so if possible try to minimize the code in these classes

'install': I think the one in router is used from the explore page, so just make sure it also works

**Comment by sbcgua** [comment]
not that easy as I expected initially ... :( will need to think.

> both router and main_page classes are quite large, so if possible try to minimize the code in these classes

My thoughts:
- I think, concentrating all handling in one place and close to each other is very convenient (at least looking fopr event became quicker imho), I'd say handling in pages can be removed at all.
- However, router is indeed huge. Do you think splitting it into 2-3 classes would help ? E.g page routing, db-tools, repo commands, in-repo commands ... or someting like that. Maybe it also worth to refactor event names to add some prefix and route to those classes based on prefix (not sure)

**Comment by larshp** [comment]
all in one place: would require also the state to be all in one place, which can be seen as a set of global variables. I think the state belongs in the page classes, eg.:
https://github.com/larshp/abapGit/blob/master/src/zabapgit_page_db.prog.abap#L14

router: yes, I think it will help splitting it. It will also help if we need to move logic between the router and pages.

**Comment by sbcgua** [comment]
Some thoughts. Sorry for much text :))) 

1. There are global commands - services - and local page only commands - like one on branch overview page and stage.
2. Global command looks really better in router (well, in one place) so that there is a clear catalog of actions.
3. Local commands do not do any logic, just change the page a bit. 
4. Some pages have state. Actually the goodness of it is arguable. I guess lcl_app can handle some controller-like objects or 'current_repo' - there are not so many states (repo, stage and merge). But that would mean rewriting all pages logic because now the gui creates and exchanges pages (views, not models). So I guess it should stay as it is now.
5. Then the question is how to handle events, which are 'global' but require internal state ? If I understand this is one of the main contradictions.

Let's consider `PAGE_BRANCH_OVERVIEW`. All events are local expect `merge` which creates new page - this is global navigation action. But the new page requires internal state. How to pass it to router ?

**Option 1**: in this particular case I would actually suggest: add repo_key to postdata, then mo_repo can be obtained in router too
**Option 2**: give router access to curent page object, and add tech methods to extract needed attributes (get_repo) - simple but I don't like it because too much cross references and unnecessary methods in pages.
**Option 3**: a bit crazy but works (tested). Create secondary event handler. E.g. any page can raise some event (declared in the interface) and pass some payload on it. Then router catches it and calls the same handling `CASE-WHEN`. Kind of flux ;) Should work nicely and clearly. There is just one doubt. That event will be handled BEFORE the previous ends - it is syncronous. So raise event should be kind of the last action to do and return event_type should be no_action ... to many conditions - this is a potential pitfall. Do you know if there is a way in abap to fire event asyncronously ?
**Option 3.1**: Same, but queue the action to router instead of `raise` (or raise calls queue as an option). Router then must process the queue after finishing with current event. This will make it async. (best option imho)

```abap
  events action exporting 
      value(iv_action) type string
      value(payload1) type any 
      value(payload2) type any
      value(payload3) type any.
```      

Below is the list of actions and some questions to them. In brackets - proposed renaming. 'local' means staying in page. ->lcl_... means separating handling to separate service class so that the method can be re-used somewhere else. Handling `CASE-WHEN` then would typically look as 2 lines: call a method, assign event_type. All more than 2 lines should be wrapped in methods. Naming: all global actions should have specific prefic, all local - no prefix. Consequently router iteself will have just page navigation logic and a huge (but ordered and convenient ;) action list. 

## at router

**Page navigation**
  main (go_main)
  explore (go_explore)
  db (go_db)
  background_run (go_background_run)
  background (go_background)
  abapgithome (go_abapgithome)
  diff (go_diff)
	stage (go_stage)
	branch_overview (go_branch_overview)
  jump

**Abapgit**
  abapgit_installation -> lcl_services_abapgit (will also absorb `needs_installation` from main_page)

**DB**
	db_display - no change, page navigation (maybe rename to go_db_display)
	db_edit - same
	db_delete -> lcl_services_db
	db_save -> lcl_services_db

**REPO**
	uninstall (repo_uninstall) -> lcl_services_repo
	remove (repo_remove) -> lcl_services_repo
	refresh (repo_refresh) -> lcl_services_repo
	install (repo_clone) -> lcl_services_repo
	
**ZIP**	
	zipimport (zip_import)  -> lcl_services_zip
	zipexport (zip_export) -> lcl_services_zip
	packagezip (zip_package) -> lcl_services_zip
	transportzip (zip_transport) -> lcl_services_zip
	files_commit - **is this command needed ? Seems like it is some old code ... Maybe remove ?**

**GIT**
	pull (git_pull) -> lcl_services_git
	reset (git_reset) -> lcl_services_git
	create_branch (git_branch_create) -> lcl_services_git

## at page_background
save (bg_update) -> lcl_services_background, move handling to router

## at page_branch_overview
uncompress - local
compress - local
refresh - local
merge - local, fire secondary event (git_branch_merge) to router or add key to postdata, and there to lcl_services_git

## at page_commit
commit_post (post) - local , fire secondary event (git_commit) to router and there to lcl_services_git
commit_cancel (cancel)

## at page_main
newoffline (repo_newoffline) - move to router, -> lcl_services_repo
delete_branch (git_branch_delete) - move to router, -> lcl_services_git
switch_branch (git_branch_switch) - move to router, -> lcl_services_git
install (repo_clone) - move to router - it is the same as in router in fact, just add show logic there
show (repo_show) - move to router, -> lcl_services_repo

## at page_stage
stage_* remain local except that `commit` and `all` should fire secondary event (go_commit)

**Comment by larshp** [comment]
hmm

4: I'm afraid that lcl_app will become a object containing global variables, and it then has to be read in the context of the page to figure out which variables are populated. Currently it serves singleton objects. It is very easy to pass state to a page via CREATE OBJECT, and the information is close to where it is needed.
However it does raise issues with regards to making the router reusable.

Looking at "page_main" actions: newoffline + delete_branch + switch_branch + install + show, I think these are only used in the main page. Moving to logic to lcl_services_repo + lcl_services_git would be a good idea, as it then is possible to reuse it from there if needed.


I think it all comes down to adding more structure and layers in the overall design, it would be nice with a package structure or package interfaces but this is not something we can easily add. It would also be nice to have dynamically generated diagrams of the class dependencies, something I would like to include in abaplint at some point.

**Comment by sbcgua** [comment]
ok, then if you don't mind I'll try with:

- separate some function to `lcl_services_repo, git, abapgit and zip`
- I'll implement that secondary event layer to show what I mean
- would mind if I rename actions as described ?
- `files_commit` question - is this feature still needed ? Seems not very natural anymore as abapGit supports pretty much already
- `page_main` actions: I don't quite agree. branch actions would also look well on branch overview for example. Install is easily unified for Explore and Main - no need to have double code. Show - yes this is main only. newoffline ... not used anywhere else indeed, although it is a global action - it changes repo list. But you decide. 
- 4. well my point was that I agree with you on keeping state in pages :) btw what do you mean "making router reusable" ? For me it looks like a central controller logic.

> It would also be nice to have dynamically generated diagrams of the class dependencies, something I would like to include in abaplint at some point.

That would be an awesomest feature! I miss it so much too (in abapGit in particular). =)) There are some UML generation features in sap but it looks poor and also they are not about depencies.

**Comment by larshp** [comment]
separate functions: ok

rename as described: ok. In a few places there are constants for the actions, eg.:
https://github.com/larshp/abapGit/blob/094266e4f79402e29598747c8d4c59bccbf7986f/src/zabapgit_page_main.prog.abap#L16
this helps to jump from where the event is defined to where it is handled, via where-used list

files_commit: just remove it, then we'll figure out if someone is using it, I dont use it

page_main: lets try to separate the functions into lcl_service_* first, then I guess it will be easier to make a few examples and see what looks/works the best

4: I am currently thinking more of having the controller logic in the pages, and they then call the logic in the lcl_services_* classes, as the pages have the state. Transferring state to a central controller will require something that looks like global variables, or a factory/singleton class, as we can only transfer strings(POSTDATA/GETDATA) to the router. While it is easy to call from the page.

**Comment by sbcgua** [comment]
First commit. Gives some overview how it will look.
actions are defined as constants. I've put them to global defs. 

files_commit: +1 :)

**Comment by larshp** [comment]
for choose_rerender_or_noaction: is it possible to always rerender? If the user press cancel it will then rerender, but I think it will not happen very often, and the time to rerender is usally low. So better with less code?

**Comment by larshp** [comment]
alternatively perhaps rename rv_success to rv_cancel, and set it when the user cancels the popups. I usually think of methods executing successfully if no exceptions are thrown

**Comment by sbcgua** [comment]
Does this look better ?
Cancel: well, yes, it is rare action. But still nothing changed ! So why re_render (and mainly resync). Well, that annoyed me while testing - that's why I did it in fact :)

Indeed the macro does not look ideally clean. But the handling does look better - avoiding clutter with IF cancel ... Maybe as a better option we can create some more types of exceptions ? In particular something like `lcx_cancel` - there are a lot of places to use it. And then it can be handled as a cancel action and potentially cleaner then now.

**Comment by larshp** [comment]
Good idea with a lcx_cancel

**Comment by sbcgua** [comment]
Some more code. `lcx_cancel` in particular. Some doubts if it should be moved directly to popups. 

zip_services actions seems to be handled with one call each. Except package export - I moved it to `lcl_zip`. So `lcl_services_zip` seems to be covered with `lcl_zip` and `lcl_transport` well.

**Comment by sbcgua** [comment]
Some more new code 
and a new feature

![image](https://cloud.githubusercontent.com/assets/15635498/18586345/e6ef2a76-7c24-11e6-945f-29a7c62ebdb5.png)

Switch action now shows directly branch selection dialog, displays current branch by default and allows creating new branch directly from there.

**Comment by sbcgua** [comment]
Maybe PR ? Much code already ... and I'd like to finish 319 =)

**Comment by larshp** [comment]
yeah, small PRs are good :smile:

**Comment by sbcgua** [comment]
PRing then :) Not so small one, sorry :(
Remaining:
- background services,
- adjust navigation action names
- try implementing secondary event

**Comment by sbcgua** [comment]
I think I can close this one. 
For the only this I want to try yet I opened 348.
