### ISSUE TITLE
UI: sort repo objects starting from those with diff

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#339]

**Comment by sbcgua** [comment]
![image](https://cloud.githubusercontent.com/assets/15635498/18450440/b918caf8-793b-11e6-8d4f-7db4e3f24804.png)

**Comment by sbcgua** [comment]
First go no-type objects, then new, then modified, then rest.
New and modified are highlighted

**Comment by sbcgua** [comment]
Maybe this can be done customizable

**Comment by larshp** [comment]
I think it adds value to have these interesting objects at the top. That way users would not have to scroll all the time :)

So I think do not make it customizable, we can look into it if somebody opens an issue for it.
