### ISSUE TITLE
POPUP_GET_VALUES_USER_BUTTONS claims ZABAPIGT-VALUE does not exist

### ISSUE THREAD

**Issue by jfilak** [larshp/abapGit#3390]
Dear abapGit gurus,

for some strange reasons some users on some of our systems started getting a strange error when trying to clone a new repo into the systems. Upon changing the value of Folder logic, they get a new error popup with the message:
`Filed ZABAPGIT-VALUE is not in ABAP Dictionary`.

Do you happen to have any idea why could be wrong?

**Comment by larshp** [comment]
ZABAPGIT is the auto generated database table, check if it exists,

![image](https://user-images.githubusercontent.com/5888506/82658813-f669ae00-9c27-11ea-9bf0-88d56b9d0431.png)

**Comment by jfilak** [comment]
Oh, sorry, forgot to mention that we opened it in se11 and saw no problems.

**Comment by jfilak** [comment]
Would it be possible to use a DDIC object from BASIS instead of ZABAPGIT?

**Comment by larshp** [comment]
perhaps, where is the error raised from, which ABAP code?

**Comment by jfilak** [comment]
POPUP_GET_VALUES_USER_BUTTONS

**Comment by larshp** [comment]
yea, any will do, try with following, as it is already in use

```
      add_field( EXPORTING iv_tabname    = 'TEXTL'
                           iv_fieldname  = 'LINE'
```

**Comment by jfilak** [comment]
Already tried, it's not possible to use 1 filed more times :) But thanks for the confirmation, that we can use whatever table and field.

**Comment by jfilak** [comment]
Changed to TADIR-AUTHOR. Caused by the function module RS_DS_INT_FIELD_INFO (hopefully, the version causing the issue will not be released). Thank you!
