### ISSUE TITLE
Refactoring, UI: Remove page redirect code 

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#3404]
zcl_page contains code to do redirects (namely `redirect` method)

![2020-05-23_18h21_40](https://user-images.githubusercontent.com/15635498/82736037-41bab400-9d2f-11ea-8faa-3740e23da87d.png)

But it is not used anyhow ... maybe remove ? It kind of does not make much sense to open web pages in IE11 in sap gui these days ...

@larshp @FreHu

**Comment by larshp** [comment]
yea, remove if possible

**Comment by sbcgua** [comment]
... screenshot is abapscan for `redirect_url` usage - the attribute that triggers redirect ... never assigned ...

**Comment by sbcgua** [comment]
added on top of #3403

**Comment by larshp** [comment]
hmm, that PR was big enough as is

**Comment by sbcgua** [comment]
I can separate if you ask. Just not to forget about it ... also that PR is well splitted into commits. But no prob, just let me know.

**Comment by sbcgua** [comment]
done in #3403
