### ISSUE TITLE
Message not being deleted in message c lass

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#341]
Hi there,

I think this is a bug in the message object:

1. I have deleted two messages from a message class in system A
2. I submitted the changes to the repository
3. I pulled them into system B
4. The two deleted messages are still there:

![image](https://cloud.githubusercontent.com/assets/532049/18579589/e798a070-7bf6-11e6-884a-abdc12f5a475.png)

**Comment by larshp** [comment]
thanks, will take a look sometime during the weekend

**Comment by nununo** [comment]
Hum... strange... this goes beyond the message class. I just added a simple change to a method already existing in the target system and this change is not being applied there. Not with PULL nor with RESET LOCAL:

![image](https://cloud.githubusercontent.com/assets/532049/18580103/dab1140c-7bf9-11e6-96dc-16b9d0d747df.png)

Any ideas why?

**Comment by nununo** [comment]
Sure! Thanks!

**Comment by larshp** [comment]
the code only does MODIFY, but does not keep track of what to DELETE,

https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_msag.prog.abap#L78

**Comment by larshp** [comment]
@nununo try again, use latest version, you can trigger a pull via 'Advanced' -> 'Reset Local'

**Comment by nununo** [comment]
Perfect! It's working now! Thanks!
