### ISSUE TITLE
Edit "master language" and "ignore files" in repo setting

### ISSUE THREAD

**Issue by mbtools** [larshp/abapGit#3413]
Is there a particular reason why that's no possible or something that just missing? 

https://docs.abapgit.org/ref-dot-abapgit.html

![image](https://user-images.githubusercontent.com/59966492/82755531-674dc900-9dd4-11ea-9dd4-988e925861be.png)

**Comment by larshp** [comment]
ignore files can be added via the staging page, but currently no edit functionality. Except for changing the file manually in git

if someone changes the master language I think it can cause a lot of problems for the user

**Comment by mbtools** [comment]
how about ML in read-only and a textarea for the ignored files?

![image](https://user-images.githubusercontent.com/59966492/82757039-36729180-9dde-11ea-828b-34dafb0a62d2.png)

**Comment by larshp** [comment]
sure
