### ISSUE TITLE
Unable to clone gitrepository

### ISSUE THREAD

**Issue by sangita-p** [larshp/abapGit#3420]
Hi ,

We are following this blog : https://developers.sap.com/tutorials/abap-environment-abapgit.html . At sub-step 6 of Step 3: Push ABAP source from on-premise to Git repository, when we give the package name and the GIT repository URL and then click on Ok, we are getting the below-mentioned error: ' While creating HTTP Client '.

![image](https://user-images.githubusercontent.com/57656604/82809181-1fe53c80-9ea9-11ea-9f65-6cdd974127eb.png)

Am I missing any pre-configuration step on the on-premise system in order to avoid this error?

Regards,
Sangita

**Comment by larshp** [comment]
try checking if connection from the SAP system to host works, try with https://docs.abapgit.org/other-test-ssl.html

**Comment by sangita-p** [comment]
Hello ,
I executed the above report program for testing the SSL connection to github.com. However I am getting an exception of 'PSE_NOT_FOUND' . 

![image](https://user-images.githubusercontent.com/57656604/82811101-9dab4700-9ead-11ea-8f0e-026f7d599e90.png)

Regards,
Sangita

**Comment by larshp** [comment]
then it looks the SSL setup is missing, https://docs.abapgit.org/guide-ssl-setup.html

**Comment by sangita-p** [comment]
Hello ,

We imported the certificates from github.com and uploaded them to the SSL client SSL client(anonymous) folder, under STRUST t code. 
After successfully adding the certificates to the list, I ran the report program 'ZABAPGIT_TEST_SSL' to check the SSL handshake. However, we are getting this error:

![image](https://user-images.githubusercontent.com/57656604/82868456-4dce8d80-9f4a-11ea-9d08-92e73820cd07.png)

Regards,
Sangita

**Comment by larshp** [comment]
connection refused, the system must have access to connect to the target system

**Comment by sangita-p** [comment]
Hello ,

How can we ensure that 'the system must have access to connect to the target system. Are there some other configuration steps required?
We have already uploaded the 3 certificates of github.com to STRUST t-code.

Regards,
Sangita

**Comment by larshp** [comment]
what is your networking setup? try logging on to the SAP server and check you can do `curl` to github.com

**Comment by sangita-p** [comment]
Hello ,
We did some changes in the network settings of the back- end system. Now when we run the report' ZABAPGIT_TEST_SSL' we are getting the below-mentioned error:

![image](https://user-images.githubusercontent.com/57656604/82890645-25568b80-9f6a-11ea-9889-422293829efe.png)

Regards,
Sangita

**Comment by larshp** [comment]
certificate untrusted, then it looks the SSL setup is missing, https://docs.abapgit.org/guide-ssl-setup.html

**Comment by sangita-p** [comment]
Hello,

The SSL certificates have already been downloaded and imported from github.com to STRUST as stated in the above document shared by you.
Sharing the screenshot of STRUST T-code.

![image](https://user-images.githubusercontent.com/57656604/82891367-3c49ad80-9f6b-11ea-88b9-f3024653a8e7.png)

Regards,
Sangita

**Comment by larshp** [comment]
github certificates are signedby DigiCert, whichis not in the list, it looks the SSL setup is missing, https://docs.abapgit.org/guide-ssl-setup.html

**Comment by larshp** [comment]
did it work out? please add a note so its possible to know if the issue can be closed

https://github.com/sangita-p/abapgitrepo1

**Comment by larshp** [comment]
closing, no reply
