### ISSUE TITLE
Syntax error in program "ZCL_ABAPGIT_APACK_READER======CP        ".

### ISSUE THREAD

**Issue by stubbini** [larshp/abapGit#3429]
Hi 

I'm trying to update from v 1.92 and after selecting pull from the repo, I have hiit the below error.

![image](https://user-images.githubusercontent.com/32145310/83016458-df590080-a019-11ea-88ea-2df0a3d18007.png)

Any repo I now access, causes the dump.

**Comment by larshp** [comment]
try taking the latest build https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap and install as ZABAPGIT_FULL and use it to update the abapGit classes

**Comment by stubbini** [comment]
All good. Thanks Lars!

**Comment by larshp** [comment]
sometimes the self update fails, using the compiled report is the easiest way to get it running again
