### ISSUE TITLE
DDLS (de)serialization

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapGit#3442]
I created some CDS in a 750 system and pass them into another system NPL 752.

It seems that DDLS objects are getting some difference in the last sentence (maybe like BOM character):
![image](https://user-images.githubusercontent.com/56556686/83490000-840e8e80-a4af-11ea-86ea-0154ba370e9c.png)
![image](https://user-images.githubusercontent.com/56556686/83490025-8d97f680-a4af-11ea-8102-0d43d295b9d2.png)

**Comment by larshp** [comment]
try checking what happens on activation in the two different systems, see https://github.com/larshp/abapGit/issues/1879

**Comment by jrodriguez-rc** [comment]
Ok, I'll close this one and follow the issue in the other
