### ISSUE TITLE
Unreadable overwritten warning when using Quarz Dark Theme in SAP GUI 7.70

### ISSUE THREAD

**Issue by gregorwolf** [larshp/abapGit#3447]
When using the "Quarz Dark Theme" In SAP GUI 7.70 Beta 2 this warning message about a class being overwritten can't be read:

![Screenshot 2020-06-03 at 12 46 27](https://user-images.githubusercontent.com/2639535/83630116-90701580-a59b-11ea-92a1-6db74e49e709.png)

Only when the text is highlighted the message is readable:

![Screenshot 2020-06-03 at 12 46 18](https://user-images.githubusercontent.com/2639535/83630121-9239d900-a59b-11ea-93fc-e7eefeda20c1.png)

Is that a standard control?

**Comment by christianguenter2** [comment]
Yes. That's CL_SALV_FORM_TEXT.
https://github.com/larshp/abapGit/blob/40b45f6221268b925ab5a8dcfc9573be0adb24c1/src/ui/zcl_abapgit_popups.clas.abap#L920

**Comment by gregorwolf** [comment]
This issue can be replicated also in the SAP Standard report SU2X_CHECK_CONSISTENCY.

**Comment by gregorwolf** [comment]
Filed the incident 366743 / 2020 via the SAP Service Marketplace regarding this issue.

**Comment by gregorwolf** [comment]
SAP Note [2938245 - Dynamic Documents : the GUI foreground and background colours inconsistent](https://launchpad.support.sap.com/#/notes/2938245) should fix this issue. Hope someone can try this in their own backend,

**Comment by flaiker** [comment]
The note worked! And thankfully it seems to be backported to even 700.

![image](https://user-images.githubusercontent.com/5270359/94047098-e5959880-fdd1-11ea-9ada-0fbb8c84ef92.png)

**Comment by flaiker** [comment]
Main note: 2930005 - Quartz Dark: Text in HTML Control is displayed with black font on dark gray background

For reference I just implemented these in the current AS ABAP Developer Edition:

0002530968 SBWP: Tips & tricks not readable
0002894053 get_foreground_color caching issue
0002938245 Dynamic Documents : the GUI foreground and background colours inconsistent
0002948774 return correct color in get_dynpro_colors for high contrast themes
0002950674 SBWP content not visible in Quartz Dark Theme
