### ISSUE TITLE
User exit: After deserialization perform additional steps

### ISSUE THREAD

**Issue by goreraks** [larshp/abapGit#3459]
After deserialization, I would like to perform some additional checks/operations on some type of objects.
My scenario: If some abapGit based project has created BC Sets for customizing content then those BC Sets must be unpacked after deserialization(no manual step of activation via SCPR20).

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit/blob/master/src/zcl_abapgit_exit.clas.abap and the where used-class for how user exists currently works
