### ISSUE TITLE
UI: Main page, hide file list, adjust diff

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#347]
Following #346 

That will be something like this:

![2016-09-18 21h09_18](https://cloud.githubusercontent.com/assets/15635498/18617927/88eaf5ec-7de4-11e6-99aa-b50632a2eb9a.gif)

in collapsed mode diff link will have number of changes in brackets. Pressing it will open diff page which will then support multifile display (semms to be easy to do).

**Comment by sbcgua** [comment]
Final look

![2016-09-20_13h40_04](https://cloud.githubusercontent.com/assets/15635498/18667221/516c1308-7f38-11e6-8c73-543ca651c4e3.png)

![2016-09-20_13h40_15](https://cloud.githubusercontent.com/assets/15635498/18667226/58eaafc2-7f38-11e6-841b-8ee5195c969f.png)

And diff suports multifiles

![2016-09-20_13h39_27](https://cloud.githubusercontent.com/assets/15635498/18667234/610a839e-7f38-11e6-82ce-94c7c6248b53.png)

meta files (.abapgit, etc) are always visible

P.S. On wide screens there are too much of whitespace (actually both with or without files), maybe we should force width ? Like github e.g. ?

**Comment by sbcgua** [comment]
Finetuning :)

![image](https://cloud.githubusercontent.com/assets/15635498/18667579/d89c56ca-7f39-11e6-829c-3d95c82ebca6.png)

**Comment by larshp** [comment]
cool, perhaps add a list of files in the top of the diff, with links to jump down to the file? (only if there are multiple files)

**Comment by larshp** [comment]
test case: create a class, commit and push it. Change class and add test class include, this will result in a diff and a "Only Local" file, how will this look in the new setup?

**Comment by sbcgua** [comment]
list of files: I would wait with it and see how it is used. There will not be many files actually and they are shortened - so not so much to scroll. So it does not add much in term of convenience imho but adds some clutter at the top. But definitely it is really easy to add. 

test case: tricky case. :) It does not work - shows new local object as diff which cannot be found on click. But that does not work with file view as well. That's because local only is triggered by `IF lines( is_item-files ) = 0.`. So the question is how to process it properly - the simplest is showing in as diff when collapse and adjust expanded view to show as "Only local". Or maybe mark as `diff (x) + new` (not my favourite). 

Page width: and what do you think about page width question above ?

**Comment by larshp** [comment]
files list: ok

test case: hmm

page width: would it force the width to be eg. 300px for each column, or force the table to be 100% Either way, lets just try it.

**Comment by sbcgua** [comment]
have to refactor diff logic a bit, I changed `remote_only` field to `new` which may take L or R (local or remote). Will commit soon. 
Btw would you mind if I rename "Local only" & "Remote only" to `new @local` and `new @remote` - it seems more clear to me.

**Comment by sbcgua** [comment]
Done. But it was tricky. I guess it still can be finetuned both internally and from UX but have to be tested in live a bit first - improvements are not clear to me for the moment. One thing definitely - in diff with one side only the table alignment becomes ugly - but I'll fix it later in some other issue.

PRing. Please don't squize commits - reforking is too radical - i did it and lost all history and references - it was a headache :( I'll try to compress commits before PR so that there are fewer of them or 1.
