### ISSUE TITLE
Reposition repo filters

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#3478]
Step 1: The columns will no longer be toggleable. This is because the space they occupy will always be needed.

![](https://user-images.githubusercontent.com/5097067/84252501-f108d080-ab0e-11ea-9d7f-45ca37522f4b.png)

Step 2: the diffs first option will become the new dropdown. Diffs first becomes one of the options in the dropdown.

![](https://user-images.githubusercontent.com/5097067/84252978-9de34d80-ab0f-11ea-9026-9e39ed73082d.png)

Step 3: The gear icon is now freed up and can go to the settings. Remove settings from advanced menu.

This should help users find the filtering options as well as settings more easily.

**Comment by FreHu** [comment]
Acutally, maybe even have all the options in the column list instead of a dropdown. Get rid of the word "show" to make space.

**Comment by mbtools** [comment]
Proposal for combining items in a "View" menu:
![image](https://user-images.githubusercontent.com/59966492/84398273-0c073d80-ac00-11ea-8e1d-30e1862d6b24.png)
("Refresh" wasn't worth a menu anyway)

**Comment by sbcgua** [comment]
I would't remove "show" ... it makes the items less clear. Also I wouldn't put refresh into a submenu - this is one of most popular actions - does not make sense to add an extra click.

Menu vs  header of table. This is also a bit controversial. This is not a repository setting. It is global setting. So it should be other in the main menu ... or on the table (to emphasize it is about representation, not the repo)
