### ISSUE TITLE
UI router refactoring, secondary event experiments

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#348]
Following from #338

**Comment by sbcgua** [comment]
This is what I mean for secondiry event. 
Benefits: pages do not know anything about each other (just about actions) and navigation can be done at upper level. 
There is a space for improvement - maybe don't pass objects with event, instead page should expose some kind of `get_state` which will be called from router (to `sender` of event).

**Comment by sbcgua** [comment]
@larshp  if this code does not look to crazy I'll fix page_merge in the similar way and PR.

**Comment by larshp** [comment]
hmm, IMHO, following

```abap
    mo_repo->push( is_comment = ls_comment
                   io_stage   = mo_stage ).
```
is easier to maintain, as it uses typed objects to call a method

```abap
        RAISE EVENT lif_gui_page~queue
          EXPORTING
            action = gc_action-git_commit
            obj1   = mo_repo
            obj2   = mo_stage
            tab1   = it_postdata.
```
accepts everything as it imports objects. So to trigger the action I would have to look up the code to see what it does, compared to calling a method with typed objects.

Can you explain about the benefits you see with this setup?

**Comment by larshp** [comment]
off cause it makes gc_action-git_commit reusable across pages, but is it needed?

From my point of view the method commit(lcl_services_git) is already reusable across pages?
```abap
CLASS-METHODS commit
      IMPORTING io_repo     TYPE REF TO lcl_repo_online
                is_postdata TYPE ty_commit_fields
                io_stage    TYPE REF TO lcl_stage
      RAISING   lcx_exception lcx_cancel.
```
(can we rename is_postdata to is_commit in the above)

**Comment by sbcgua** [comment]
Perhaps you're right. I wanted to achieve the state when pages don't know about each other and about how "global" actions are performed (some kind of flux concept). But since the state is inside the page it is not that natural. Unnamed params do not look good, I agree. I can change it so that payload is a structure with named params. But still the sending page should know about the structure for the receiving page which fails my goal. Perhaps this is the router who should extract the state ... which means ideally that the state should be outside of a page. Maybe that's the way to go ... somewhen.

So I think for now I'll remove that 2ndary event code and just keep `services-commit` and then PR.

**Comment by larshp** [comment]
yeah, its difficult stuff. I'm afraid that if having the state outside of the page will result in having a set of semi-global variables

**Comment by sbcgua** [comment]
ok, create a PR with commit improvements only.

One side question: why `lcl_stage` does not have a reference to it's repo ? Can it exist without repo context ?

> "! keep the list of staged files, independent of repository and branch

**Comment by larshp** [comment]
not sure :smile: 

this code smells like it could just accept io_repo in its constructor
```abap
    CREATE OBJECT mo_stage
      EXPORTING
        iv_branch_name = io_repo->get_branch_name( )
        iv_branch_sha1 = io_repo->get_sha1_remote( ).
```

looks like it would also make it easier to call the commit page, just passing `mo_stage` (assuming it has a reference to the repo)
```abap
    CREATE OBJECT ei_page TYPE lcl_gui_page_commit
      EXPORTING
        io_repo  = mo_repo
        io_stage = mo_stage.
```

**Comment by sbcgua** [comment]
Yeap, that's what I had in mind :)

P.S. Closing this issue now
