### ISSUE TITLE
Incorrect validation of URLs

### ISSUE THREAD

**Issue by mbtools** [larshp/abapGit#3484]
Change repo using protocol "XYZ":

![image](https://user-images.githubusercontent.com/59966492/84488555-ab7c0d00-aca0-11ea-9988-947626b99aa9.png)

It actually works without errors!

![image](https://user-images.githubusercontent.com/59966492/84488608-c058a080-aca0-11ea-8287-eef60d80cebc.png)

Can we change ZCL_ABAPGIT_URL=>REGEX to limit URLs to http and https?

Instead of
```
    FIND REGEX '(.*://[^/]*)(.*/)([^\.]*)[\.git]?' IN iv_url
      SUBMATCHES ev_host ev_path ev_name.
```
use
 ```
   FIND REGEX '(https?://[^/]*)(.*/)([^\.]*)[\.git]?' IN iv_url
      SUBMATCHES ev_host ev_path ev_name.
```

**Comment by larshp** [comment]
yea

**Comment by g-back** [comment]
working on it, unless you've already done it @mbtools ?

**Comment by mbtools** [comment]
I’m doing it. There’s a bit more to catch cases if malformed URLs already exist in persistency

Best,
Marc
