### ISSUE TITLE
Tutorial link not working - sapevent:go_tutorial broken

### ISSUE THREAD

**Issue by GiantCrocodile** [larshp/abapGit#3485]
Hello,

clicking on the linked word 'tutorial' in string 'No favorites so far. For more info please check tutorial' does nothing. The link refers to `sapevent:go_tutorial`.

This happens on latest SAP Logon for Windows 760.

Best Regards,

**Comment by mbtools** [comment]
I have GU 760 patch 4 and the link seems to be working fine. If you are already showing the "Tutorial" page, then the link doesn't do anything.

**Comment by GiantCrocodile** [comment]
You are right @mbtools. The tutorial is already shown; I never realized it's the tutorial. Is there a page that isn't the 'Home' page and where this text is shown? I clicked around but found no page where this string is visible.

**Comment by mbtools** [comment]
You will see it when viewing a repo (but only when you have no favorites, obviously)
