### ISSUE TITLE
Question regarding offline / local changes 

### ISSUE THREAD

**Issue by Sirius-A** [larshp/abapGit#349]
Hey
I installed abapGit in our dev system and created an offline project from an existing package. 

If I change and activate a class within the package, the change is not listed as changed. Is that the intended behavior?
Is there a way to add (think `git add`) and commit the files offline? 

Thanks and best regards
Fabio

**Comment by larshp** [comment]
in the offline scenario abapGit does not keep track of which files/objects are changed

However, you can download the files as zip, and then use a normal git client to commit files from the frontend pc. This will also show which files are changed

**Comment by Sirius-A** [comment]
Ah I see.  If I convert the project to an online one, will I be be able to track, commit and push the changes done on the system?

Thank you for your help :smile:

**Comment by larshp** [comment]
yes, then you can commit/push directly from the abap system, and the abap system will show if files does not match the remote repository

see https://github.com/larshp/abapGit/wiki/Installing-abapGit for setting up SSL/STRUST

**Comment by Sirius-A** [comment]
Thank you for the fast help and for the awesome project in general :+1:
