### ISSUE TITLE
ABAPGit won't install in 7.31 after #3445

### ISSUE THREAD

**Issue by esjewett** [larshp/abapGit#3494]
I believe this broke compilation in 7.31 and below. :(

![image](https://user-images.githubusercontent.com/4822/84536352-4aaa0000-acb3-11ea-9d47-97b73f06502e.png)

![image](https://user-images.githubusercontent.com/4822/84536412-68776500-acb3-11ea-8f28-dd9e3d0a0eb2.png)

_Originally posted by @esjewett in https://github.com/larshp/abapGit/pull/3445#issuecomment-643431043_

**Comment by esjewett** [comment]
The release version of that system. I have no idea what this "4.0" message is. 
![image](https://user-images.githubusercontent.com/4822/84536654-ed627e80-acb3-11ea-97b4-56c4bce56946.png)

**Comment by larshp** [comment]
@esjewett try again, latest version

**Comment by esjewett** [comment]
Looking good. Thanks for the VERY quick fix.
