### ISSUE TITLE
XML_FORMAT_ERROR after editing XML file.

### ISSUE THREAD

**Issue by whereistejas** [larshp/abapGit#3496]
Hi,
I have installed abapGit, however I edited the XML file (and, messed it up). Now, everytime I run the program I get the above mentioned error. I found the other issue where it was suggested that we can edit the XML file during debugging. However, I couldn't manage to do it. I even tried deleting the program and all its includes but all in vain. 

Is there any way for me to just delete the XML file or reset it physically? For reference:
```abap
CLASS ZCL_ABAPGIT_PERSISTENCE_USER IMPLEMENTATION.
  METHOD constructor.
    mv_user = iv_user.
  ENDMETHOD.
  METHOD from_xml.

    DATA: lv_xml TYPE string.

    lv_xml = iv_xml.

* fix downward compatibility
    REPLACE ALL OCCURRENCES OF '<_--28C_TYPE_USER_--29>' IN lv_xml WITH '<USER>'.
    REPLACE ALL OCCURRENCES OF '</_--28C_TYPE_USER_--29>' IN lv_xml WITH '</USER>'.
    
    CALL TRANSFORMATION id                  " <--- THIS IS WHERE I GET THE ERROR
      OPTIONS value_handling = 'accept_data_loss'
      SOURCE XML lv_xml
      RESULT user = rs_user ##NO_TEXT.
  ENDMETHOD.
  METHOD get_instance.

    IF iv_user = sy-uname ##USER_OK.
      IF gi_current_user IS NOT BOUND.
        CREATE OBJECT gi_current_user TYPE zcl_abapgit_persistence_user.
      ENDIF.
      ri_user = gi_current_user.
    ELSE.
      CREATE OBJECT ri_user TYPE zcl_abapgit_persistence_user
        EXPORTING
          iv_user = iv_user.
    ENDIF.
```

**Comment by larshp** [comment]
the easiest workaround is deleting the contents of database table ZABAPGIT via SE14, but you will lose your settings

**Comment by larshp** [comment]
would like to make a standalone version of the db tool for scenarios like this, but have not had time

**Comment by whereistejas** [comment]
and now it wont start because the db table is missing :(

**Comment by whereistejas** [comment]
It's working, now. Thanks @larshp :)
