### ISSUE TITLE
GUI page playground

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#350]
Hi @larshp 
I have one dev feature in mind. The idea is to have button in Utils menu - you press it - the dialog pops up asking the program and class name and then it launches that class as a page (via interface) and renders it. It will give a possibility to experiment on page changes outside of abapGit package wihtout including the code and messing up the commits while it is not ready  (e.g. for diff page code highlighting).  What do you think ? I planned actually to do it locally (copy part of program and etc.) but then I thought that maybe it is a feature to include to the core which does not seem too difficult. What do you think ?

**Comment by larshp** [comment]
:+1: 

perhaps we can add a
```abap
INCLUDE zabapgit_user_exit IF FOUND.
```
in the main include

where stuff like this can be included

**Comment by sbcgua** [comment]
Good idea!
But still some util is needed to call it. Although this will be a local class which simplifies a lot. I'll do some examples and commit.

**Comment by sbcgua** [comment]
Done. The feature is quite straight forward. `IF FOUND` really simplifies things, thanks ! :)
Will PR after 'hide files' feature merged (or I can add to PR now)

**Comment by sbcgua** [comment]
UPD: BTW generic user_exit include will not work because of depencies so I called this one `gui_userexit`. More can be added when needed.

**Comment by larshp** [comment]
PR: One feature at a time, it makes it more easy to look through, I will take a look this afternoon

**Comment by sbcgua** [comment]
How it work (for history and doc)

Advanced util menu now have `Page playground` item

![image](https://cloud.githubusercontent.com/assets/15635498/18721872/1883eec2-803b-11e6-9c4e-7cd637f3684c.png)

Which popups the dialog with class name

![image](https://cloud.githubusercontent.com/assets/15635498/18721878/2960155e-803b-11e6-90cb-76b3d39496ae.png)

If confirmed, it tries to create it as `lif_gui_page` and render it. Supposed that there is no params to constructor. Although it can be easily adjusted to accept e.g. repo_key (as additional dialog params) or another optional string params.
