### ISSUE TITLE
Cannot create offline repos anymore

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#3507]
![image](https://user-images.githubusercontent.com/17437789/84648372-3f4e1300-af05-11ea-85d2-4c6928dc75bf.png)

![image](https://user-images.githubusercontent.com/17437789/84648382-42490380-af05-11ea-8b42-1d4a3533f90b.png)

![image](https://user-images.githubusercontent.com/17437789/84648384-42e19a00-af05-11ea-9377-9c81c7246c9c.png)

Introduced by #3486 
https://github.com/larshp/abapGit/blob/ea21a7cfd1e3d84af4a5ea1fce548791d2254c0f/src/utils/zcl_abapgit_url.clas.abap#L80

I think we don't need the validation for offline repos. However using url field as name for offline repos looks fishy anyway. Some refactoring needed I guess.

**Comment by christianguenter2** [comment]
@mbtools

**Comment by mbtools** [comment]
Thx, Christian. Of course. This is what happens if one can enter something into a field called "URL" that isn't a URL. The popups just aren't going to do it in the long run (no F4, etc) and need some work... https://github.com/larshp/abapGit/issues/3417
