### ISSUE TITLE
Repo with 'Display name' shows diff for non-code file

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#3510]
Before setting display name
![image](https://user-images.githubusercontent.com/17437789/84650591-de283e80-af08-11ea-8dd1-aa800fd072b9.png)

![image](https://user-images.githubusercontent.com/17437789/84650626-f009e180-af08-11ea-92d9-e23ff5fea289.png)

After
![image](https://user-images.githubusercontent.com/17437789/84650686-0a43bf80-af09-11ea-8fb0-377cd632c5b5.png)

Restarting abapGit solves the issue

**Comment by mbtools** [comment]
https://github.com/larshp/abapGit/pull/3506

**Comment by mbtools** [comment]
should work now
