### ISSUE TITLE
Remove Default for 'Default for Comment'

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#3511]
Recently the feature for default commit message was added. That's ok, but I vote against prepopulation. Because nobody changes the default commit message in my shop :-)

Opinions?

![image](https://user-images.githubusercontent.com/17437789/84651822-d5d10300-af0a-11ea-8c8f-87727e19ff62.png)

https://github.com/larshp/abapGit/blob/58fb961a19a4b38e85a24bd0824790768b8f43d0/src/zcl_abapgit_settings.clas.abap#L319

**Comment by g-back** [comment]
Agreed, one could also argue that
- the variables are anti-patterns (theres no need to specify which objects/files have been changed, that is what git is for)
- the default commit message should be moved to repo settings (e.g. for JIRA keys that are repo specific)

**Comment by mbtools** [comment]
The behaviour was modeled after Github and I find it very convenient. Sure we can remove the default.  Should length and size of body also be repo settings?
