### ISSUE TITLE
Allow pull/stage although nothing changed remotely/locally

### ISSUE THREAD

**Issue by mbtools** [larshp/abapGit#3519]
There are cases where you want these options but they are not shown in the menu (https://github.com/larshp/abapGit/issues/2563). Happens when you sync changes between branches for example. Or when you want to "reset remote" although nothing changed locally. 

```
ZCL_ABAPGIT_GUI_VIEW_REPO->BUILD_MAIN_TOOLBAR

      IF iv_rstate IS NOT INITIAL. " Something new at remote
        ro_toolbar->add( iv_txt = 'Pull'
                         iv_act = |{ zif_abapgit_definitions=>c_action-git_pull }?{ mv_key }|
                         iv_opt = iv_pull_opt ).
      ENDIF.
      IF iv_lstate IS NOT INITIAL. " Something new at local
        ro_toolbar->add( iv_txt = 'Stage'
                         iv_act = |{ zif_abapgit_definitions=>c_action-go_stage }?{ mv_key }|
                         iv_opt = zif_abapgit_html=>c_html_opt-strong ).
      ENDIF.

```

Should we add a setting to allow pull/stage even if nothing is new?

**Comment by larshp** [comment]
There is a Advanced -> Force Stage, and Advanced -> Reset Local, stage and pull

**Comment by mbtools** [comment]
Apparently too advanced for me. :-) Thx!
