### ISSUE TITLE
UI stage js improvements

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#353]
following #346

More responsive add/reset on JS

Key issue - how to generate post request with JS for sapevent - [this solution works](http://stackoverflow.com/questions/133925/javascript-post-request-like-a-form-submit)

**Comment by larshp** [comment]
cool, only add to the staging page for now, then we will figure out if it works for all users, and then perhaps we can add it more places if needed

**Comment by sbcgua** [comment]
sure, actually I don't see where else to use it for the moment :)

**Comment by sbcgua** [comment]
ok, done. Interesting experience :)
Maybe will play a bit with representation UX of commands - dont like that "command <-> reset" toggling. But generally can PR.

**Comment by sbcgua** [comment]
"command <-> reset" toggling improvement - i meant this:

![image](https://cloud.githubusercontent.com/assets/15635498/18761859/50f50078-810f-11e6-985e-e2e3da4017fc.png)


Arguable ... maybe not that better (the idea is actually not showing reset as an action)
