### ISSUE TITLE
XML classes, remove ALIASES

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#3531]
see https://github.com/larshp/abapGit/pull/3514

**Comment by larshp** [comment]
- ZCL_ABAPGIT_XML_INPUT
- ZCL_ABAPGIT_XML_OUTPUT

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/91040296-43d22e80-e60e-11ea-95f9-7fc3b377a524.png)

![image](https://user-images.githubusercontent.com/5888506/91040359-6106fd00-e60e-11ea-921a-31d25368e5ae.png)

**Comment by g-back** [comment]
Todos before `zif_abapgit_object` can be changed:
- [ ] CLAS
- [ ] DOMA
- [ ] DSYS
- [ ] DTEL
- [ ] FUGR
- [ ] INTF
- [ ] MSAG
- [ ] PROG
- [ ] SPRX
- [ ] TABL
