### ISSUE TITLE
Remove no_text pragmas

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#3555]
I think these are useless because

*   abapgit does not use messages, so you have to put it all around the place
*   all this prevents is an info message in an atc check nobody looks at
*   actually if you ever wanted to translate abapgit, it would make more sense to _not_ have pragmas because then you could just go over all the info messages

There are 624 instances of either `##NO_TEXT` or `##EC_NOTEXT` in the codebase. I propose to remove them for readability.

**Comment by larshp** [comment]
I think some of them in class headers(public, protected, private sections) are automatically added by SE24. 

So suggest starting with the method bodies

**Comment by FreHu** [comment]
I forget that because of you we still support se24 :D

**Comment by mbtools** [comment]
You could change the CLAS/PROG serializer temporarily to remove the unwanted pragmas.

**Comment by larshp** [comment]
well, if we want to enforce this it needs to be part of CI

ie. implement a rule in abaplint, and then have a quickfix for it => it all can be fixed by one command line command

**Comment by larshp** [comment]
`"#EC NOTEXT`

**Comment by larshp** [comment]
I'm starting this now

**Comment by larshp** [comment]
ready, configuration =

```json
    "forbidden_pseduo_and_pragma": {
      "ignoreGlobalClassDefinition": true,
      "ignoreGlobalInterface": true,
      "pragmas": ["##NO_TEXT"],
      "pseudo": ["#EC NOTEXT"]
    },
```

**Comment by larshp** [comment]
done, closing
