### ISSUE TITLE
"Cannot find .abapgit.xml" error for new online repo

### ISSUE THREAD

**Issue by mbtools** [larshp/abapGit#3563]
I think https://github.com/larshp/abapGit/pull/3512 is too restrictive... For example, our documented process produces an error:
https://docs.abapgit.org/guide-first-project.html

1. Create a new repo in Github
2. Do +Online in abapGit

![image](https://user-images.githubusercontent.com/59966492/86053497-e334d400-ba58-11ea-8de0-0af8a595aef4.png)

Maybe raise the error only if a certain number of files exist?

**Comment by christianguenter2** [comment]
yeah, makes sense. Feel free to fix. I don't have time currently.
