### ISSUE TITLE
Document Database Util to remove already deleted repositories from database

### ISSUE THREAD

**Issue by GiantCrocodile** [larshp/abapGit#3579]
Hello,

I'm getting an `Error from CL_PACKAGE_FACTORY=>LOAD_PACKAGE 1` error from abapGit 1.97.0 on NW 740 when I click on the name of a repository in the Repository list/overview. The package that belongs to this repository has been deleted and I would like to uninstall/remove the repository from abapGit as it's not needed anymore. Clicking on the ABAP package name of the repository in the overview does throw a proper `Object DEVC <package name> doesn't exist` error.

Of course I can recreate an empty package with the same name and uninstall/remove it then but I think this should work without that too. I read the documentation at https://docs.abapgit.org/guide-online-uninstall.html to see if there's another way to remove a repository but doesn't seem so.

Callstack:
![grafik](https://user-images.githubusercontent.com/6271057/86454450-8585dd80-bd1f-11ea-9c14-1cba9d1726b8.png)

**Comment by mbtools** [comment]
On the repo list in AG, try Advanced > Database Util

**Comment by GiantCrocodile** [comment]
@mbtools Deleting it there did work. I found no information about the Database Util so I wasn't sure if I should delete it via that. After deleting, it disappeared properly from the abapGit Repository Overview. Do we have docs for the Database Util? If not, I might write a short mention of the tool in the Uninstall/remove docs part and explain on a separate doc page how it helps if you are stuck with regular deleting of a repository. I would do this the next 3 or 4 days.

**Comment by larshp** [comment]
I dont think there is any mention of it, its kind of a power tool ✊ 

feel free to open a PR adding it to the documentation

**Comment by GiantCrocodile** [comment]
Okay, I will do that @larshp and reference this issue so when it gets merged, this issue is closed/fixed too.

**Comment by GiantCrocodile** [comment]
I still have this in my mind. My current workload just changed a bit so this is delayed but I will keep it in mind and try to deliver a PR soon.
