### ISSUE TITLE
ENHO: Enhancement code not updated

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#359]
Hi,

I have an enhancement which is not being updated. It is just a couple of spaces but nonetheless a change. And it stays there showing DIFF after pulls and reset locals:

![image](https://cloud.githubusercontent.com/assets/532049/18875271/fbc7b404-84bc-11e6-9a4b-bc35eed238ad.png)

Being such a simple change I am going to change it manually. But I wanted to report it anyway because it seems to be an issue.

Cheers,
Nuno

**Comment by larshp** [comment]
looks like this is related to normalizing of the XML tag values, it removes the spaces when the value is read/written.

Same problem occurred in dynpro flow logic, a new xml tag counting the number of spaces was introduced, see https://github.com/larshp/abapGit/blob/d4d8b338103c06320c25b611e982236da21f54e6/src/zabapgit_objects.prog.abap#L790

**Comment by nununo** [comment]
So I guess that means you already found a way to solve it! Great!

**Comment by larshp** [comment]
yeah, it just needs to be implemented. I dont think I'll have time to look into it anytime this week.

**Comment by nununo** [comment]
This one is not urgent at all! ;)

**Comment by larshp** [comment]
try again

update to latest abapGit and push from source system again, update to latest abapGit in client system and pull again

**Comment by nununo** [comment]
Hi Lars,
Great! Thanks! I now don't have any test scenario for this unfortunately but if you did find a reason for this behavior and corrected I'll happily close it! :)

Thanks,
Nuno
