### ISSUE TITLE
Delete Brach -> No Branch selected

### ISSUE THREAD

**Issue by ed-holland** [larshp/abapGit#3595]
When using the menu Branch -> Delete there is no popup for selection of the branch.

the Error message appears immediately: No Branch Selected

**Comment by g-back** [comment]
Works for me. You can't delete a branch you are currently in - you also can't delete the master branch, so it's not shown in the list.
Try switching to master and then try deleting?

**Comment by ed-holland** [comment]
> Works for me. You can't delete a branch you are currently in - you also can't delete the master branch, so it's not shown in the list.
> Try switching to master and then try deleting?

You are correct, the popup comes up if one is not in the branch it self. 

I propose the message to be improved to make it clear.

**Comment by ed-holland** [comment]
Created PR [#3605](https://github.com/larshp/abapGit/pull/3605)

**Comment by ed-holland** [comment]
Verified
