### ISSUE TITLE
No +Clone option

### ISSUE THREAD

**Issue by SergioMorente** [larshp/abapGit#3599]
Hello!

When I run ZABAPGIT_FULL and try to clone a repository I find that the +Clone option does not appear.
Any other way to do it?
![image](https://user-images.githubusercontent.com/67968644/86805818-281bc480-c070-11ea-8ebc-acb4469c44ba.png)

Thanks!

**Comment by larshp** [comment]
click the "+ Online",

![image](https://user-images.githubusercontent.com/5888506/86806516-3b7f5d80-c079-11ea-8365-4f7adc9f2e07.png)

**Comment by SergioMorente** [comment]
Tried that too.
It asks for a package which I supose is the package where the new code will be generated? 

When I try to open the line it creates it spends a lot of time "Serializing" all the elements of that package so It seems wrong, but anyways at some point I get this error and nothing else happens:
![image](https://user-images.githubusercontent.com/67968644/86807390-bba1c500-c071-11ea-9628-1fa8c26210d7.png)

Thanks!

**Comment by larshp** [comment]
can you help posting a screenshot of the dump where it mentions the code surrounding the ASSERT?

**Comment by SergioMorente** [comment]
This should be the TRY:
![image](https://user-images.githubusercontent.com/67968644/86808362-b002ce00-c072-11ea-9e37-72e683dae37e.png)

**Comment by larshp** [comment]
suggest changing the code to catch the exception to check the error message, also check the values of `is_item`

**Comment by SergioMorente** [comment]
The values of is_item are:
![image](https://user-images.githubusercontent.com/67968644/86810317-b09c6400-c074-11ea-9017-663f43de9094.png)
Also:
![image](https://user-images.githubusercontent.com/67968644/86810342-b5f9ae80-c074-11ea-94ae-7429081290f6.png)

**Comment by SergioMorente** [comment]
Also, if it serves any help, the repository im trying to clone is:
https://github.com/fidley/json2abaptype

**Comment by SergioMorente** [comment]
Ok, tried to clone it on another package. Which is smaller and it seems to work now. 
Thanks for your time and help!

**Comment by larshp** [comment]
clone all open source to a dedicated new empty package, so you can keep track of what belongs where

**Comment by larshp** [comment]
closing
