### ISSUE TITLE
serializer does not use package for path

### ISSUE THREAD

**Issue by ed-holland** [larshp/abapGit#3603]
In the AbapLint Backend, the serializer is called to generate dependency code.
![image](https://user-images.githubusercontent.com/53995991/86953213-668aaf80-c154-11ea-83bd-e00c193b77dd.png)
The package is filled
![image](https://user-images.githubusercontent.com/53995991/86953319-8e7a1300-c154-11ea-8ca3-c9ef91203e98.png)
The resulting path does not contain it.
![image](https://user-images.githubusercontent.com/53995991/86953405-b1a4c280-c154-11ea-9c47-343aca6e70e4.png)

Is that meant to be this way?

**Comment by larshp** [comment]
thanks, I think this is something that should be solved in https://github.com/abaplint/abaplint-abap-backend

can you help closing it here, and opening in https://github.com/abaplint/abaplint-abap-backend ? 

its not possible to transfer issues between organizations...

**Comment by ed-holland** [comment]
I thought the serializer is part of abapgit. That is why i opened it here.

Created is as #69 in backend.
