### ISSUE TITLE
Possible to export/import WDYV (OTR) texts

### ISSUE THREAD

**Issue by mfallen** [larshp/abapGit#3606]
Hi,

for my WebDynpro, I save my text as OTR text (in SOTR_EDIT), using object type WDYV.

Now I want to do some tests and exported my package via abapgit/reimported into my sandbox.
Unfortunatelly, the text is not included?

Not possible or mistake by myself?

Thanks
Michael

**Comment by mbtools** [comment]
There seems to be a bug in reading the texts. How many records do you have in table sotr_use for LIMU,WDYV,<your webd dynpro>* ? If it's more than 1, it doesn't work properly

**Comment by mbtools** [comment]
In addition to the bug above, the import does not update SOTR_USE. I'm working on a fix

**Comment by mbtools** [comment]
The change also impacts ENHS objects. We will have to wait until https://github.com/larshp/abapGit/pull/3629 is merged to avoid conflicts.

**Comment by mbtools** [comment]
Closed by https://github.com/larshp/abapGit/pull/3681. If you find any problems with it, pls open a new issue,
