### ISSUE TITLE
docs: describe code inspector functionality

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#3616]
describe code inspector functionality

![image](https://user-images.githubusercontent.com/5888506/87241689-e69b6880-c425-11ea-855e-8c6ff187b19a.png)

**Comment by GiantCrocodile** [comment]
@larshp What kind of information do you lack regarding CI/ATC? Maybe I can enhance that information as I did for other stuff about this topic.

**Comment by larshp** [comment]
when the check variant is set, code inspector is run sometime before stage or commit

missing a description of this feature somewhere on docs.abapgit.org

**Comment by GiantCrocodile** [comment]
I will try to see if/how I can enhance that here https://docs.abapgit.org/ref-dot-abapgit.html#code-inspector.

**Comment by larshp** [comment]
ahh, okay I did not read through it, as it is local configuration and the page describes the .abapgit.xml file

**Comment by GiantCrocodile** [comment]
I agree that it's not that clear that you find those information on that page. On the other hand the other pages doesn't fit too and I don't think that more and more pages are actually improving the finding of information. Maybe we should just remove the bracket part of the page title and thus clarify that this page is about repository settings and the `.abapgit.xml` file in general.

**Comment by GiantCrocodile** [comment]
@larshp Do you think the current documentation for Code Inspector and ATC is sufficient so we can close this issue or shall I think about enhancing it somehow?

**Comment by larshp** [comment]
its okay, closing
