### ISSUE TITLE
ZCL_ABAPGIT_STAGE refactoring (repo relation)

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#365]
Following discussion in #348 

> why lcl_stage does not have a reference to it's repo ? Can it exist without repo context ?
> this code smells like it could just accept io_repo in its constructor

```
CREATE OBJECT mo_stage
  EXPORTING
    iv_branch_name = io_repo->get_branch_name( )
    iv_branch_sha1 = io_repo->get_sha1_remote( ).
```

> looks like it would also make it easier to call the commit page, just passing mo_stage (assuming it has a reference to the repo)

```
CREATE OBJECT ei_page TYPE lcl_gui_page_commit
  EXPORTING
    io_repo  = mo_repo
    io_stage = mo_stage.
```

**Comment by sbcgua** [comment]
appears that lcl_repo_online uses stage in `push`.
What do you think about moving `push` to stage ? On the one hand push is repo logic. On the other - currently push is only possible after staging.

**Comment by sbcgua** [comment]
`push`, in its turn, uses `set` and `build_local_checksums` :(

**Comment by larshp** [comment]
yea, perhaps we need to move some methods
