### ISSUE TITLE
Local serialization performance tweaks

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#366]
I wonder what if add some method `has_changed()` to `lif_object`. The method should check actual date of last change of the object (and compare it to given param). This method can be called then in `get_files_local` loop - unchanged objects will be just skipped without reserializing. 
This would make page switching faster and also might help #280 (folder view)

**Comment by sbcgua** [comment]
I don't know if all objects has easily accessible changed date **and time** in particular.

**Comment by larshp** [comment]
dont think all objects have changed date and time

I think we should try to do a performance trace, to see where most of the time is spent, that way we can decide where to focus

**Comment by sbcgua** [comment]
Optimizing most common ones would work well as well, I guess. I'm a bit worried about CLAS - it has many components to check.

Performance: well, here is one. I think it's quite representative :) (top lines are page global methods so I scrolled them down)

![image](https://cloud.githubusercontent.com/assets/15635498/18988091/ae9459d2-870d-11e6-80b3-46a47f8c2e42.png)

**Comment by larshp** [comment]
perhaps we should make a small test program that just calls the serialization, so eg. the time of HTTP_READ_SC is not included.

But as far as I remember, the most of the time is typically spent in READ REPORT functions inside the CLAS serialization. So perhaps we can just build a buffering mechanism inside the CLAS and PROG classes?

**Comment by sbcgua** [comment]
I think I can implement some caching for basic dictionary object and prog, maybe clas too. fugr maybe ... seems like it takes a lot of time in my case. It will be in a separate branch so we can check how it works then.

small test program can be useful for some tests. But I think it is quite clear from the log that lcl_objects=>serialize takes a lot. 45% of execution. http takes 33%. Well, for smaller programs it will be opposite I guess. Serialization has linear growth. HTTP has high initial bias. 

Here is the log for abapGit serialization

![image](https://cloud.githubusercontent.com/assets/15635498/18993579/8c53ba60-872c-11e6-9162-b0faea21c11c.png)

**Comment by sbcgua** [comment]
Draft. Needs some critical review ...

Also I've found that it is not actually `repo->get_files_local` which delays page switching but `file_status->status`. So will think on it too. 

P.S. imho. `refresh` refreshes only remote part and "requests" local update on next `get_files_local` call via `super->refresh`. That was really confusing logic for me. Although it is unified for on and off line repos this took some time to understand. Maybe it worth calling local serialization directly in online refresh for clarity.

**Comment by sbcgua** [comment]
added status results cache - no unnesessary re-status each page switch. I hope I didn't break anything :)

**Comment by larshp** [comment]
we need to take care it works with time zones, wondering what time zone the date and time stored in `dd04l` uses

**Comment by sbcgua** [comment]
good point. `get time stamp` produces UTC. dd04l seems to keep local time. However `cl_abap_tstmp=>systemtstmp_syst2utc` converts it to UTC also. So at the end the comparison is correct. At least it seems so. 

![image](https://cloud.githubusercontent.com/assets/15635498/19014593/a8fab7d6-87f9-11e6-9410-407a8556246d.png)

**Comment by sbcgua** [comment]
Test prog (yeap that was a good idea indeed)

https://github.com/sbcgua/ZGITHUB_TEST/blob/master/zabapgit_perf_test.prog.abap

Current stats

![image](https://cloud.githubusercontent.com/assets/15635498/19016207/3c4f281a-881c-11e6-9f76-aa570972a2d2.png)

**Comment by sbcgua** [comment]
test order was wring - here is more proper result

![image](https://cloud.githubusercontent.com/assets/15635498/19016333/259a41ba-881f-11e6-8803-8a4b0471ef6c.png)

**Comment by sbcgua** [comment]
For basic objects:

```
get_files_local()                      5,665213
get_files_local() cached               4,487249
```

```
DOMA  24
DTEL 110
ENQU   1
SHLP  11
TTYP  26
TABL  44 ??? (probably bug, it is 14)
VIEW   4
```

**Comment by sbcgua** [comment]
```
get_files_local()                      5,575876
get_files_local() cached               1,803491
```
Not completely confident in PROG and FUGR checks though.

**Comment by sbcgua** [comment]
```
get_files_local()                      5,232372
get_files_local() cached               1,721740

PROG  72
FUGR  21
CLAS  33
```

For CLAS also not too confident.

**Comment by larshp** [comment]
any thoughts on the non-PROG objects in a CLAS? eg. it also contains a textpool

**Comment by sbcgua** [comment]
texts ... I'm not sure about the table. Is it `REPOTEXT` ? Looks like the one.

**Comment by larshp** [comment]
`READ TEXTPOOL`, https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_clas.prog.abap#L578

I think it is not easily accessible via a database table

**Comment by sbcgua** [comment]
Well, seems like it is `REPOTEXT` :) Time and content is changed there when texts are updated and SQL trace also suggest some inserts. So I guess I'll add this table check

**Comment by sbcgua** [comment]
So ... shell I PR this ? I'd add a couple of more objects ... but maybe later - these are the most frequent and long to serialize.

**Comment by larshp** [comment]
yea, please do, small PRs are good

**Comment by larshp** [comment]
some of the DDIC object XML files include information for other DDIC objects, I've tried clearing some extra fields, see todays commits

**Comment by larshp** [comment]
@sbcgua can we close this one?

**Comment by sbcgua** [comment]
I think yes. Most heavy types are cached. There is still that text issue to fix and to stabilize what is done. If required a new ticket can be opened.

**Comment by larshp** [comment]
closing, text issue = https://github.com/larshp/abapGit/issues/404
