### ISSUE TITLE
OTR texts for classes is not saved in XML

### ISSUE THREAD

**Issue by pokrakam** [larshp/abapGit#3664]
Once upon a time exception classes with OTR texts saved the texts in the class XML
See https://github.com/pokrakam/SAPlink-Git/blob/master/src/zcx_saplink.clas.xml line 52 onwards

However this no longer works, abapGit now wants to commit a "change" removing the texts. 

Reproduced using https://github.com/pokrakam/SOTRtest 
Created exception class in SE24 with texts 
![image](https://user-images.githubusercontent.com/25539927/88375334-4d5c4280-cd93-11ea-91eb-36feb0fa92ec.png)

Resulting XML only contains one text, see https://github.com/pokrakam/SOTRtest/blob/master/src/zcx_exception_with_sotr.clas.xml

Considering this as low priority as OTR is not the main component or usage of exception classes so I won't look into this further at the moment. But maybe someone might be aware of the change, or maybe there's a wider issue.

**Comment by mbtools** [comment]
I already have a branch going to fix it. Just waiting for the change on ENHS to get merged to avoid conflicts.

**Comment by mbtools** [comment]
Fixed by https://github.com/larshp/abapGit/pull/3681. After getting the fix, you have to update your repo with the additional SOTR_USE section in the XML (once).

**Comment by pokrakam** [comment]
Seems to work now, thanks!
