### ISSUE TITLE
Transport Request IDs as Tags in Commits

### ISSUE THREAD

**Issue by mkaesemann** [larshp/abapGit#3668]
I noticed that for quite some time now abapGit lists the transport requests in which files are locked and tag support has also been added to abapGit for a while.
For our current development scenario it would be useful if abapGit was able to add the transport request IDs commited objects are locked in to the commits as tags. Because that way it would be much easier to create a link between commits transport requests (or tasks), commits and our JIRA isues (which are automatically linked by denoting the JIRA issue ID in the commit).
I believe that all the functionality required is already there, I just need some pointers where I have to look for a good "after commit"   spot I could use for an extension.
Any hints would be appreciated.

**Comment by mbtools** [comment]
This could work only with limitations. For example, parts of a function group or class could end up in different transports (as LIMU) which abapGit currently does not recognize: https://github.com/larshp/abapGit/issues/2961

Not sure if you want to have so many tags in your repo. Maybe it's sufficient to add the transport IDs to the body text of the commit. https://github.com/larshp/abapGit/blob/master/src/ui/zcl_abapgit_gui_page_commit.clas.abap#L311 (fill lv_body with a default similar to the commit comment)

**Comment by larshp** [comment]
Can you explain a bit more about the process?

ABAP developers typically make multiple changes to objects in a transport before it is released, commits can happen multiple times during those changes, bit by bit. The transport/change would implement a full "feature", ie. branches can be seen as equal to a transport(again depending on process).

You could also have chosen only to commit to git at release, having the ABAP developers use git less. In this case you can automate it completely, find released transports commit to git.

**Comment by mkaesemann** [comment]
I am aware of the limitations and the wide variety in which the CTS can be used, so I'm not even sure if the functionality would be of any use to anyone but my team and me. That's why I am merely asking for advice on what a good place would be to implement it in my own fork.
But let me explain where the idea comes from:
My team and I are working on a big add-on with lots of inherited code artifact from previous versions that are not that well designed or adhering to SoC principals. We use Bitbucket for the repository and JIRA for issue tracking. 
We work based on JIRA tickets, for which we try to have a single transport task per ticket (if possible), because this way we almost have a 1:1 relationship between transport tasks and git commits and the mention of the JIRA ticket in the commit automatically links the commits to the JIRA issues.
Due to the limitations of the locking mechanism in SAP CTS, all developers work in one transport request (otherwise their artifacts may be split amongst transports if another developer has already touched the same object) and we only release the transports at certain intervals (often the end of a sprint). This way we are decently certain that all changes relevant for a new function or bugfix are grouped in one transport.
The downside is that there are lots of objects in the transport request in the end - which is where the transport tasks are supposed to help to figure out which objects were actually related to a change and can be referenced in a transport of copies if we need to move it to another version or system (multiple versions and systems in our landscape; complex setup; don't ask ;-))
At the moment we try to add the transport task links to the JIRA issues manually, which, as you can imagine, is quite error prone.

Naturally the ideal solution would be developing in branches, but as long as SAP does not implement my suggestion to have a user-based temporary view of the system (theoretically possible as a transparent additional layer, but probably a huge amount of work...), branches are not an option.

So the next best thing for us would be to introduce hunks in abapGit (so developers can select only those changes in an object that actually belong to their change if multiple developers have touched an object) and automatically referencing the transport task/request.
At first, I wanted to automatically add the request/task ID to the commit message, but that is tedious to search. Tags would be much easier to see, as they are visible in most git clients and web interfaces right away and in our case the number tags would be limited due to the way we work and release.

I don't have time to look into implementing hunks at the moment, so I wanted to start with something small for which all functionality is basically already available.
And that's where my question comes from :-)

**Comment by larshp** [comment]
I think a git tag can only refer to one commit, and the tag would be the transport number? I guess you want to make the tag when the transport is released, and only one tag? And the assumption for making this tag is that everything from the transport is in git?

even though branching is not supported in ABAP, you can still choose to have branches in git, this would enable you to do code reviews via pull requests. I assume that in the above you have one master branch?

we can quite easily add more user exits in abapGit if needed, https://docs.abapgit.org/ref-exits.html

git patch(hunks) is implemented in abapGit:
![patch](https://user-images.githubusercontent.com/5888506/88645749-c70e6c00-d0c4-11ea-97b8-cb5d24dc2e01.gif)

**Comment by mkaesemann** [comment]
First off all you are absolutely correct and I'm an idiot. I completely ignored the fact that a tag is limited to one commit and the same task or transport might occur multiple times. I guess that brings me back to my original idea and @mbtools proposal to just add the tasks/requests to the commit message.
I guess I just confused the git tags with the JIRA labels...

Secondly, thanks for pointing out the hunk/patch functionality. I actually never associated the term 'patch' with hunks and have literally never clicked on Patch. This will definitely change from now on and make live so much easier :-)

And last but not least: Yes, we could do branches in git, but the developers would still be working on the code in the SAP system, so they would need to switch the branch in abapGit. Or did I get you wrong? I don't see an easy (safe) way for two developers to work on two different features in two branches without running into possible issues.
But then again: The first two points show that I am far from infallible ;-)

**Comment by larshp** [comment]
yea, multiple developers and switching branches would be a problem, but we could implement a feature in abapGit, having the system set to one branch, but allowing to commit to other branches than the one choosen

**Comment by mkaesemann** [comment]
That would actually be an interesting option. My initial idea was to have branch defined per repo and a branch defined per user, so abapGit could detect the changes against the branch of the developer and commit them into said branch (as long as the developer takes proper care of his hunks), while at the same time everybody who is not using a separate branch can stay on the repo branch, which is the "system state".
At least as a rough idea.
Maybe I'll look into this option a little closer when all my release dates have come and passed for this year - which will not be prior to the S/4HANA 2020 release in October *sigh*
Thanks for the answers regarding the transport request/task link. I'll start by looking into those...

**Comment by larshp** [comment]
and you can run abaplint in for each branch to ensure consistency
