### ISSUE TITLE
Staging: add link does not seem to work

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#367]
Clicking the "add" button, nothing happens, but "diff" works
![image](https://cloud.githubusercontent.com/assets/5888506/18991522/55fed110-8719-11e6-9278-09fc9870b16d.png)

![image](https://cloud.githubusercontent.com/assets/5888506/18991518/4ed391d2-8719-11e6-9b76-588426a1b0ff.png)

**Comment by larshp** [comment]
@sbcgua any tricks to debug the javascript code inside the SAP GUI? It seems that nothing happens when I try `alert`

**Comment by sbcgua** [comment]
alert definitely works (I used it for debug).
Yeap, `const` is a later feature. Bug from my side.
I think I have somewhere virtuabox with winXP and SAPGUI 730 - I'll try to check how it works there.

**Comment by larshp** [comment]
it works for me now, replaced `const` with `var`

**Comment by sbcgua** [comment]
Installed some IE8 clutches. Now works even on this (and theoretically down to IE6 ???):

![image](https://cloud.githubusercontent.com/assets/15635498/19015859/333ab1ec-8815-11e6-9853-7dff89025854.png)

Pushed directly.
