### ISSUE TITLE
Question regarding branch switching where table structure changes have been made

### ISSUE THREAD

**Issue by habrahams** [larshp/abapGit#3670]
Hi all,
I have a question regarding what happens to table data(entries) in a table whose structure has changed( removal of field/column or Data element change) when switching branches.

What happens to the data or DB entries in the table? 
I would assume that when switching branches that the data could potentially be corrupt and would have to be re-populated after each branch switch? Is this the case currently?
 
Thanks for you time.
Regards.

**Comment by larshp** [comment]
The https://github.com/larshp/abapGit/blob/master/src/objects/zcl_abapgit_object_tabl_compar.clas.abap code should run and show a warning to the user.

but recommend trying it out with some dummy objects first

**Comment by habrahams** [comment]
Thanks Lars ,
Will definitely have a look at it, just wanted to confirm my assumption.
