### ISSUE TITLE
Abap short dump in ZCL_ABAPGIT_HTML after pulling latest changes

### ISSUE THREAD

**Issue by habrahams** [larshp/abapGit#3677]
After pulling latest repo changes I got an Abap dump when trying to run abapGit.
![image](https://user-images.githubusercontent.com/16045067/88795797-e24ea980-d1a0-11ea-9042-e0720014d3c0.png)\

Thus I tried the full report source code to see if I could reset the local objects, the full report source code(ZABAPGIT_FULL) does not trigger a short dump , but the ZCL_ABAPGIT_HTML does not reset when selecting "Reset Local"

Regards,

**Comment by mbtools** [comment]
RENDER was moved to an interface. First, activate ZIF_ABAPGIT_HTML, then ZCL_ABAPGIT_HTML.

**Comment by habrahams** [comment]
Thanks, the issue is resolved, I think a certain sequence of events caused this.
