### ISSUE TITLE
Remove workaround for leading spaces in PROG, FUGR, and ENHO

### ISSUE THREAD

**Issue by mbtools** [larshp/abapGit#3680]
I did some tests and the workaround to persist the number of leading spaces in the XML for PROG & FUGR (dynpro flow) and ENHO (for hook implementation) is not necessary anymore.

References: https://github.com/larshp/abapGit/pull/2597, https://github.com/larshp/abapGit/issues/2643, https://github.com/larshp/abapGit/issues/2655

Removing `<SPACES>` section from the XML would impact all repos with dynpros or enhancement implementation including the following test repos:
https://github.com/abapGit-tests/CLAS_with_ENHO
https://github.com/abapGit-tests/ENHC
https://github.com/abapGit-tests/ENHO
https://github.com/abapGit-tests/FUGR_maintenance_view
https://github.com/abapGit-tests/FUGR_maintenance_view_variant
https://github.com/abapGit-tests/IARP_IASP_IATU
https://github.com/abapGit-tests/IAXU
https://github.com/abapGit-tests/PROG
https://github.com/abapGit-tests/PROG_dynpro_foreign_key
https://github.com/abapGit-tests/PROG_dynpro_modi
https://github.com/abapGit-tests/PROG_dynpro_resize
https://github.com/abapGit-tests/SCP1_TOBJ

Depending on the repo, there might be many diffs for users (which are easily fixed by staging the updated serialization). 

Example of what it would look like: New leading spaces and no more `<SPACES>` on local side
![image](https://user-images.githubusercontent.com/59966492/88817840-018f0c00-d18c-11ea-9ad4-6135a76bfc50.png)

Do we want to proceed and remove the workaround?

**Comment by larshp** [comment]
yea, just make it backwards compatible, so if SPACES exists it is used at import, but serializes without SPACES
