### ISSUE TITLE
On missing branch, not possible to enter a repo

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#3701]
If branch was deleted online, then entering the repo from overview page is blocked by `branch not found` error. No workaround except DB editor

**Comment by mbtools** [comment]
Not perfect, but #3749 takes care of this

**Comment by mbtools** [comment]
I reworked it and removed the methods that I had added to repo :-)
https://github.com/larshp/abapGit/pull/3831

**Comment by larshp** [comment]
I think this is solved?

**Comment by sbcgua** [comment]
yeap
