### ISSUE TITLE
package sync with 2 repo

### ISSUE THREAD

**Issue by agiguere** [larshp/abapGit#3703]
is it possible to have a package sync with 2 different repo

let say I have developped something that is sync on a GitHub Enterprise repository, then I would like to expose it publicly on GitHub

I would need to create a new repo (on GitHub) then in ABAPGIT click Online + Pull (but I don't want that the empty GitHub repo erase my local one)

thanks

**Comment by mbtools** [comment]
Yes, using the same repo but different URLs. Are you sure putting code into the public would adhere to company security policies? 

After the first repo is in sync, go to "Advanced > Change Remote" and enter the URL of the other repo. Then use "Advanced > Force Stage" to update the second repo. Then switch back to the original URL so you don't get confused ;-).

**Comment by agiguere** [comment]
ok thanks, in short I have to change the remote, there is no way to have a second online repo and push the package content there ?

If I want my code to be accessible by others users of ABAPgit, it needs to be public?

my code is pure SAP not related to the company policies

thanks

**Comment by larshp** [comment]
you could do git mirroring, however it will be difficult if you want to accept PRs in both repositories.

So consider having the real version on github, where everyone can contribute, and then mirroring that to the local GHE

**Comment by larshp** [comment]
but also, IMHO it will be easier if the code is just in one place, ie. public github

**Comment by agiguere** [comment]
thanks, I agree with you going on with mirroring would be difficult, I decided to change the remote like @mbtools mention, it is now pointing to my public GitHub acccount, I would need to blog about it, what it takes to be listed in the projects under explore, mine is called SCPmsPushNotificationREST_API but I can't see it

**Comment by larshp** [comment]
Explore shows the projects from https://dotabap.org, click the upper right "+ Add Project" link 😄

**Comment by larshp** [comment]
add a license to your repository, https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository and add it in https://github.com/dotabap/dotabap-list/blob/master/list.json via a pull request

**Comment by agiguere** [comment]
thanks, I just added an MIT license, the add project bring me to the GitHub repo dotabap-list,

I will rework my readme file this weekend with good documentation then I will sent your a PR on list.json

thanks
