### ISSUE TITLE
Overview page - show files/objects per folder

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#371]
see https://github.com/larshp/abapGit/issues/280

![54099416-8b52-11e6-9b55-b49dbb53ecc7](https://cloud.githubusercontent.com/assets/5888506/19142715/e20505be-8b9f-11e6-8c14-8b8fb4e666f8.gif)

**Comment by larshp** [comment]
Currently there are 2 different views implemented:

With files,

![image](https://cloud.githubusercontent.com/assets/5888506/19142727/015c953a-8ba0-11e6-9c8f-565f3d47b5ce.png)

And hiding files,

![image](https://cloud.githubusercontent.com/assets/5888506/19142735/0a36a1a0-8ba0-11e6-919a-9ec9f9499a28.png)

Do we need another way of showing the same information? I'm afraid that having 3 different ways to do the same thing makes it more difficult to maintain, as some of the features are used less than other.

Alternatively if having 3 different implementations we can consider hiding the logic behind an interface.

**Comment by sbcgua** [comment]
For me they are not 3 different ways - they are complementary. Hiding files has nothing to do with folders. I want either compact view or all the data and so I choose my option. In the code it is also implemented in different places. 

Folders:

Let's start from subpackages - imho it is really straight forward. Currently it is implemented on repo level. And I can see it as a part of path. But that is inconvenient for large repos. So we need folder. It is just representation if you checked the code - I didn't change backend part. 

Forders by type: this is not that clear. I see 2 usecases:

1. I don't care about repo level, but I want to group my current view in SAP. So I switch on the grouping and types are shown as folder. Or maybe as collapsing groups (implemented in JS). Dynamically. No changes to actual file structure. In term of settings it is user preference like hiding files. 

2. I want my files in the repo to be located per type. This is different feature in fact. I need some way to convert existing file structure. After which the regular code (subpackages code) will work to show me that in folders. This option should be noted in `.abapgit` for proper (de)serializing also. **Conversion** - I see it as one step action. Gradual conversion one by one when something is commited is trickier. 

For the options above I personally think that 1st is more nice to have than the 2nd one. However it is easier to implement and more flexible so I aimed to implement it first. 2nd rises more question. About convertion ... and maybe back converion ...

**Comment by larshp** [comment]
Do we need a folder view? 

It is possible to go to SE80 and see the objects in the package, and the objects are grouped by object type. For a browseable folder structure the git repository can be downloaded, or browsed on github, if needed. Information about filenames is also currently implemented by 'show files'.

I see the overview as `git status`, so if it shows folders, it does not have the important information on what is changed.

**Comment by sbcgua** [comment]
OK, the following opinion is from my as side as from user: yes, I need it :) 

Here is the screenshot of that 400-object project: https://github.com/sbcgua/ZGITHUB_TEST/blob/master/2016-10-06_13h21_06.png

It is too long to manage. abapGit is very convenient for review of my team work. Any kind of downloads would make it less conveninent. SE80 does not show changes. abapGit is the best place. And I need some feature for narrowing review scope quickly and efficiently. 

That's why I vote for fast and convenient UI, sintax highlight etc. Moreover I'd like to have some tailored diff views e.g. for tables/structures - to see more quickly which fields added/changed. Not in XML. This is what github/files/se80 will not give anyway. Maybe I'll code that too some days (if you don't mind :). 

P.S. `git status` ... mmm ... but that more stage page ? Status shows changes. That was great idea to add there diff links by the way. 
P.P.S Just one opinion but from the real tasks. :) Sorry if insisting too much :)

**Comment by larshp** [comment]
heh, cool screenshot :smile: 

The changed files are shown at the top of the long list, perhaps we can hide the rest of the list and just show text "398 objects unchanged"? This would make the overview very fast and only show the relevant information? (and easy to implement)

tailored diff for tables and structures, good idea -> new issue

**Comment by sbcgua** [comment]
Mmmm ... maybe good idea ... if it is switchable also ... 
OK. then if you don't mind - I'll finish that subpkg folder code without by-type for the moment - it is still good and also code structure is better. Then I'll check this "Show changes only" feature (indeed easy to implement). And then it will be more clear.

P.S. Added tailored diff to #346 list

**Comment by larshp** [comment]
lets just try it :smile:

**Comment by sbcgua** [comment]
Ok, something like this for the moment. What do you think ?

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/15635498/19364620/945638b2-9197-11e6-941a-019728d40b8d.gif)

To do yet:
1) Save those settings to user config (maybe not needed for grouping by folder)
2) I think to make diff capable of showing all changes (in particular some top difflink to show all diffs like at github)

**Comment by sbcgua** [comment]
while it is not merged anywhere - do you have any preference on naming ?
Currently include is called `ZABAPGIT_VIEW_REPO` and class `lcl_gui_view_repo_content`. It is not a page, it is a component. But component is too long. But view is not quite clear. Hmmm.

**Comment by larshp** [comment]
no naming preference, naming is difficult

**Comment by sbcgua** [comment]
Closing. Looks fine for the moment imho
