### ISSUE TITLE
The option Ignore Subpackages no longer works when adding new Online

### ISSUE THREAD

**Issue by jfilak** [larshp/abapGit#3712]
The following change introduced a user regression:
https://github.com/larshp/abapGit/commit/09120cb80d7f7ac3fee5378d30449c850c32b7b1#diff-a387b940e84b85067646dfdc3dc0e29bL447

Old behavior:
- it raised exception only if the package was already added as a repo

Current behavior:
- the exception is raised if the package is versioned as a sub-package too

Can you please take a look, @mbtools  @FreHu 

Thanks to Antonio Yanez Santamaria <antonio.yanez.santamaria@sap.com>!

**Comment by antonioyanez** [comment]
Hello all, 

as finder and person who needs a fix, I would gladly take this issue.

**Comment by mbtools** [comment]
Looks like we just need to pass iv_ign_subpck to the new get_repo_from_package.
https://github.com/larshp/abapGit/commit/09120cb80d7f7ac3fee5378d30449c850c32b7b1#diff-63a6c4399151ad3e2f86898107920ee9R192

 ```
   zcl_abapgit_repo_srv=>get_instance( )->get_repo_from_package(
      EXPORTING
        iv_package = ls_popup-package
       iv_ign_subpkg = ls_popup-ign_subpkg   "<<<ins
      IMPORTING
        eo_repo    = lo_repo
        ev_reason  = lv_reason ).
```
