### ISSUE TITLE
Question on packages in abapGit

### ISSUE THREAD

**Issue by jinigirl** [larshp/abapGit#3713]
Hello.. This is a question on how packages work in abapGit. I came across issue [1237](https://github.com/larshp/abapGit/issues/1237) , and it is recommended to use a superpackage if you want to have multiple packages that you want to add in the same repo. 

We explored this in abapGit and tried to connect the repo we have to 2 different packages, and it seems it created two separate projects in abapGit (we tested and contents of both packages can be committed to github, just not at the same commit). Is this an expected functionality? I'm thinking one way we would be using 2 packages is if it's already existing in our system and we wanted to commit this in the same repository in Github.

![package 1](https://user-images.githubusercontent.com/36019912/89503449-1e18ed00-d7f9-11ea-9b2e-65adc8efdd92.JPG)
![package 2](https://user-images.githubusercontent.com/36019912/89503463-22dda100-d7f9-11ea-8bff-6ddda80bf5d5.JPG)

**Comment by larshp** [comment]
Create one top package,

ZTOP
-> ZTOP_SUB1
-> ZTOP_SUB2

Put the ZTOP package into a repository, and all changes below that can be pushed and pulled to git

**Comment by larshp** [comment]
@jinigirl did above help?

**Comment by jinigirl** [comment]
@larshp yes it was helpful. so we just made the first package as the superpackage for the second one. Thank you!
