### ISSUE TITLE
Patch for Stages Files only

### ISSUE THREAD

**Issue by mkaesemann** [larshp/abapGit#3716]
We are working on a huge repository with hundreds or thousands of changed objects sometimes and multiple developers working on the same objects in certain cases.
I now know that abapGit already has hunk functionality in form of the 'Patch' functionality on the staging screen; howvere, I noticed that pressing Patch on the stage screen always lists all changed objects on the following patch screen, which is not only unwieldy and convoluted, but also takes a longtime to prepare, which takes a lot of waiting time (e.g. having abapGit render diffs for 500 changes objects even though I know I have only changed 1 is rather annoying)
I've checked the coding and have seen that the ZCL_ABAPGIT_GUI_PAGE_PATCH could probably easily be adapted to support another case (currently only single file, single object or whole repo are supported) and render patches for a given set of objects and the ZCL_ABAPGIT_GUI_PAGE_STAGE would be able to supply this set of objects based on the staged state of the objects.
However, while pressing "Commit selected" si supplied with the POST data from which the selected objects can be determined, pressing Patch on the same page does not receive any POST data.
Could you provide me with some hints, where I would have to look to get the POST data of the selected objects when Patch is chosen?
![2020-08-06_12h02_10](https://user-images.githubusercontent.com/32765685/89519473-b654a900-d7dc-11ea-9c80-725b367d2d66.png)

**Comment by mbtools** [comment]
The logic to call the patch page is in ZCL_ABAPGIT_GUI_PAGE_STAGE->ZIF_ABAPGIT_GUI_EVENT_HANDLER~ON_EVENT.

```
      WHEN zif_abapgit_definitions=>c_action-go_patch.                         " Go Patch page

        lo_stage = stage_selected( it_postdata ).  "<<< INSERT this and pass it to get_page_patch and from there to ZCL_ABAPGIT_GUI_PAGE_PATCH

        ei_page  = get_page_patch( iv_getdata ).
        ev_state = zcl_abapgit_gui=>c_event_state-new_page.
```

**Comment by larshp** [comment]
I'm wondering if we can change the overall logic, so that it always respects the selection

I don't use patch very much, will post a heads up in slack 🗣️

**Comment by christianguenter2** [comment]
Yeah, idea to respect the selection sounds really useful to me. 
If nothing is selected should the logic behave the same as now? I vote for yes.

**Comment by FreHu** [comment]
> If nothing is selected should the logic behave the same as now?

This part has to stay the same as now because you can also patch from the list page where you can't select files.

**Comment by sbcgua** [comment]
long term speaking: I would remove the stage page at all and move the selection of files to commit to the repo view (or some mode of it). So then:
- view page -> `select needed` -> `commit` -> commit page
- view page -> `select needed` -> `patch` -> patch page -> `select lines` -> commit page
- view page -> `select needed` -> `pull` -> pull selected (this is the deployment mode I posted an issue recently for)

Just an idea

**Comment by mkaesemann** [comment]
@mbtools: The problem with the proposed insert is that there is no post data in the event GO_PATCH. That was my initial question: Where can I trigger that it_postdata is supplied?

**Comment by mbtools** [comment]
@sbcgua that's the best productivity idea for a while. On repo view, add a checkbox col to select objects (or files) and then have all actions work on the selected objects only (we should have a typical select/deselect all and maybe other selectors - like "my objects", too).

@mkaesemann Sorry, to suggest it was that easy. the file selection is done in JS (smw0 > bin > ZABAPGIT_JS_COMMON, object StageHelper). The idea with checkboxes will probably be easier to implement than adapting the JS.

**Comment by mkaesemann** [comment]
@mbtools Too bad. I was hoping for something I missed, that would enable the Patch to behave like the COmmit Selected and receive the Post Data. I didn't see anything off the bat, but I'm rarely looking at the UI stuff in abapGit currently, so I was hoping I had missed something.
