### ISSUE TITLE
cached objects - does not take package change into account

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#372]
Steps to reproduce:

1: open abapGit
2: change package of eg. a TABL object(this will change where it should place the files in the git folder structure)
3: click refresh in abapGit -> nothing to stage

If abapGit is restarted, it allows for staging the files in the correct folder

**Comment by sbcgua** [comment]
Will have a look. (add package check to `has_changed()` )

**Comment by larshp** [comment]
it also might work by copying line https://github.com/larshp/abapGit/blob/d289abaffdeca8c1f0a33b00464172661204eac9/src/zabapgit_repo_impl.prog.abap#L444

to inside the loop
https://github.com/larshp/abapGit/blob/d289abaffdeca8c1f0a33b00464172661204eac9/src/zabapgit_repo_impl.prog.abap#L426

if TADIR does not have a timestamp/or not updates on package change

**Comment by sbcgua** [comment]
Seems like we need `DEVCLASS` cached in ty_file_item. What do you think ? Quite used and critical structure - not sure about all consequences. Or keeping some structure just with package references nearby.

If I understand the issue happen only if switching package between subpackages, right ?

**Comment by larshp** [comment]
yes, looks like we need to store the DEVCLASS somewhere to figure out if it has changed, looks like there is no timestamp in TADIR

switching between subpackages: yes

Example:
$foo = main repository, with following subpackages:
$foo_ddic
$foo_backend

moving an object from $foo_backend to $foo_ddic, and it does not show up as a diff. After restart of ZABAPGIT it shows up

**Comment by sbcgua** [comment]
ok. so ... do you think it is ok to add it to ty_file_item? What can it break ?
I think I'll add it to the the end of the structure - i rememeber there was some sorting somether ... or `at new`

**Comment by larshp** [comment]
just try, we'll see what happens, I usually do not use `at new`, think its okay

**Comment by sbcgua** [comment]
OK, looks like this works. But not 100% sure. Could you pls have a look?

One more thing. When I change table pkg (from sub to main package in the example) then: 

1) Path in the overview is old

![image](https://cloud.githubusercontent.com/assets/15635498/19219653/bdf53c82-8e21-11e6-9e3a-d57fa6e4bb6d.png)

2) Diff shows only remote part

3) there is a log entry "Package and path does not match for object, TABL ZGITHUB_TABL" at the top - is it OK ? 

4) User have to both add new file and remote the old one in the stage page. 

Is it OK ? 
If yes then it is still confusing :)

**Comment by larshp** [comment]
1 + 2 + 3: same behavior as earlier, not perfect, something we might want to look into

4: yes, same behavior as normal command line `git`

**Comment by sbcgua** [comment]
OK ... so , I PR then ?

**Comment by larshp** [comment]
yes :+1:
