### ISSUE TITLE
Object TRAN: No package information in XML causing differences

### ISSUE THREAD

**Issue by ed-holland** [larshp/abapGit#3729]
We have several transactions in the package.
These are now showing differences on the remote side. The XML does not contain the package information (checked also on file system).

![image](https://user-images.githubusercontent.com/53995991/89918290-222e7b80-dbfa-11ea-95e5-b4a6d4300b29.png)

A pull / reset local would overwrite the current objects.

Am i correct in assuming that the TRAN xml should contain the package information it belongs too?

**Comment by abapChaoLiu** [comment]
No, no client based information (package, user name, time stamp and etc...) should be contained in XML.
Since the package name in system A doesn't have any meaning in neither system B or in git repository.
![image](https://user-images.githubusercontent.com/48561271/90034821-b6debb00-dc86-11ea-8c34-cc075f2b63f9.png)

**Comment by ed-holland** [comment]
I would not say that the package is system specific. It is part of the path of the xml. The source of the problem is that AG is showing differences for TRAN objects. I've updated the title of this issue accordingly

![image](https://user-images.githubusercontent.com/53995991/90103193-6b89e280-dd42-11ea-8edc-9785dd2635ca.png)

The Transaction exists of course (although AG thinks it is not)
![image](https://user-images.githubusercontent.com/53995991/90103252-80667600-dd42-11ea-9fbb-fc9748ce852e.png)

The base package is /JCS/FCA.
When one tries to pull the changes, AG thinks that the objects have been moved package.
![image](https://user-images.githubusercontent.com/53995991/90103645-25814e80-dd43-11ea-9e61-eee49e7bea49.png)

As from the screenshot above, the package has not been changed.
Is the move packages change having problems with namespaces?

**Comment by larshp** [comment]
in the local system the package is translated to folder as `ecc/`, but in remote git it is `nw/`

either you want the object in the `ecc` or `nw` folder, when pulling abapGit will try to move the object from `ecc` to `nw`

![image](https://user-images.githubusercontent.com/5888506/90103934-a6d8e100-dd43-11ea-89bf-44da7b007169.png)

**Comment by ed-holland** [comment]
Ok, understand now what it is trying to do. Can it be that the new move-package functionality now notices it and it was not noticed  before (the move was done more than a month ago).

**Comment by larshp** [comment]
yea, there have been some changes in this area not so long time ago

**Comment by ed-holland** [comment]
The pull does not seem to be able to move it.
Also a reset local does not help.
![image](https://user-images.githubusercontent.com/53995991/90106873-5021d600-dd48-11ea-84fe-dd2bdc4190f4.png)

would moving them on filesystem be a valid sollution?

**Comment by larshp** [comment]
I think above errors are for the function group

its always an option to change the package manually in the system, or move the files in git, depending on where you want to have the objects

**Comment by ed-holland** [comment]
The real issue is that the objects existed in both places. It seems they where not removed when the objects were moved to the new package structure.
