### ISSUE TITLE
staging page - state is lost

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#373]
Steps to reproduce:

1: click add for a file
2: click diff for a file
3: go back -> the information about adding file from step 1 is lost

**Comment by sbcgua** [comment]
Hmmm ... that's probably because JS state is not stored when page is rerendered. I'll have a look. But can be a problem ...

**Comment by larshp** [comment]
I'm thinking that the "diff" link can submit, like the commit link, then store state in page, and return state to page when re-rendered. Looks like a lot of work for a small issue

**Comment by sbcgua** [comment]
That would fail the whole idea of managing the stage state in js. And also diff will behave differently in different case. Ufff :(((( That ruins the concept :( Maybe the initial though to make it in ALV was better :) Or some kind of cookies/local-storage ... have look at it with a fresh head :)

**Comment by sbcgua** [comment]
:+1: for which thought ? ;)

btw looking into localStorage thing. This seems to work embeded in abap, also on 731 + IE8

```
    function myFunc() {
      var obj = {a: 1, b: "abc"};
      var data = window.sessionStorage.getItem("key");
      if (!data) {
        window.sessionStorage.setItem("key", JSON.stringify(obj));
        data = window.sessionStorage.getItem("key");
      } else { data = "!! " + data; }
      alert(data);
    }
```

**Comment by sbcgua** [comment]
So that's my current solution idea

**Comment by sbcgua** [comment]
The above also keeps data if page is switched. Which is good but also needs some measure to distingush 2 different stages in the same abapGit session ... most probably some random id generated by page_stage

**Comment by larshp** [comment]
I think it will be easier to keep the fix in ABAP, typical users of abapGit are ABAP'ers only few of these know javascript. Plus its easier to debug the ABAP part.

but anyhow, any solution that fixes the problem is good

**Comment by sbcgua** [comment]
Seems like really tricky to make it in abap :( Just spent 2 hours trying. I cannot manage to fire 2 events - 1st to preserve state, 2nd for diff page. One on them doesn't fire. It seems that SAP does not queue them properly. I tries alredy onclick+href, ondeforeunload and some other stuff :(
I'll check one more option with iframes ... if not, I'll go for sessionStorage

**Comment by larshp** [comment]
hmm, the "commit" link knows the state when its clicked, so the state is transferred to ABAP? Just do the same with diff, or does this not work since you want to only store the state in JS?

**Comment by sbcgua** [comment]
commit triggers js, which dynamically creates form and submit it. 
diff must submit the same and **after** trigger `diff?` event. Which is with own params btw. This does not work. Or I'm looking in a wrong place.

P.S. iframes also don't work :(

**Comment by sbcgua** [comment]
iframes - i meant [this](http://stackoverflow.com/questions/12483016/executing-javascript-after-a-form-finishes-submitting) if interesting - a workaround to catch the fact that form submit has been finished.

**Comment by sbcgua** [comment]
The only way I see now is some mixed action of diff and stage_preserve but this looks really ugly for me.

**Comment by sbcgua** [comment]
well ... and sessionStorage (js only)

**Comment by larshp** [comment]
I can take a look tomorrow to see if I can come up with any ideas?

**Comment by sbcgua** [comment]
OK. But if no ideas - the above commit just works (js solution). (I had to write something that works after 2.5 hours of failures to restore my morale :)

**Comment by larshp** [comment]
then lets just go with above, there is a lot of other stuff that also needs attention...

**Comment by sbcgua** [comment]
OK, I'll push directly if you don't mind.

**Comment by larshp** [comment]
go for it :ship:

**Comment by sbcgua** [comment]
done. Closing.

**Comment by larshp** [comment]
tested ok
