### ISSUE TITLE
UI asset caching

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#374]
Hope this is not too crazy. Stop me if it is.  ;)

Goal and reason: handle assets data outside of abap code. It is not convenient to code it in abap. It adds clutter. It is not flexible. Difficult to integrate big objects like images/fonts.

What I mean by assets: CSS, images (or, better font - which would give more variety of images and options to style/color them), js code. Maybe HTML templates (???). CSS might be ours or external (github primer)

Potential locations of assets: in-abap, cdn, github (abapGit or not!). The connection to CDN is assumed on client side. The connection to github is supposed on server side (however may not be the case if installed manually just for local use !)

General idea: cache assets into MIME storage in SAP and supply it from there with some backups, namely CDN and in-abap assets (for single copy-paste installation only).

To take into account: keep easy to install approach. So manual MIME installs is not OK. It must be transparrent for a user. 

Let's assume for example that there is (1) CSS in abapGit repo and (2) a webfont available both at CDN and octicons github repo. Important: CSS is mandatory to run. Webfont is not actually (no images, well ... can survive). 

What if abapmerge understand some special hints and can integrate CSS (and JS) into the build. The first installation then works as it is w/o issues. 
- Upon start abapGit check if there is webfont cahced. 
- If not - adds a link to CDN to html
- Additionally it starts background execution of another abapGit with params to update cache (background - to avoid UI delays in the main task) - this background task tries to connect to github repos for CSS and webfont. So that the next run will work with cached assets.
- any abapgit pull can also update CSS. 
- the background job may also be smart enough to extract CSS from the abap code of initial install (easy but not sure if needed in reality)

So as the result - no impact on user, better code structure for developers, more options for UI (images, webfonts, more js)

**Comment by larshp** [comment]
hmm, yea, could be nice to separate the ABAP and js/css.

Perhaps store the external dependencies ZABAPGIT database table. As if they go into the same package as    ZABAPGIT it will show in the staging list, making it non-external.

**Comment by sbcgua** [comment]
**Some history from [here](https://github.com/larshp/abapmerge/pull/12)**

----

There will some class, let's say `resource_crawler`
And let's say there will be some method `resource_crawler->get_resource(id)` - set of id's is in fact known and limited.

So it will do something like (pseudo code)

```abap
method get_resource.
...
  if (id = 'css').
   lv_result =  css_in_code().
   if lv_result is initial.
    lv_result = get_resource_somewhere_else()
   endif.
endmethod.

method css_in_code.
  data tab type table of string. 
  "@@abapmerge include style.css > APPEND '$$' TO tab.
  rv_result = concat_lines_of( table = tab, sep =  `\n` ).
endmethod.
```

----

general idea is that css/js will be a part of repo (assets folder or similar). So it will be non-code file which in fact is processed by abapGit. So css/js should not be just skipped but stored to DB instead. Thus it will be in line with current branch. Maybe it should be mentioned in `.abapGit` for that. Or maybe not, as actually assets for abapGit are known and can be hardcoded.

----

idea: store the css/js as mime objects in the SAP system, these can then be part of the git repository, and abapmerge can include them.

eg. like [this](https://github.com/larshp/abapGitServer/blob/master/src/frontend/02c1f55747191ed58ab0401507578067.smim.index.html) is a SMIM object, part of the git repository and stored as an object in the SAP system

----

W3MI vs SMIM: not sure, might be better with W3MI, as I do not like the keys/names of the SMIM files

----

Current thoughts:
- SMIM looks better because it stores actual text in repo. W3MI is base64ed.
- maybe ... serailization can be changed for W3MI ... as an idea ... not sure if it will work for all non-abapGit cases
- naming in SMIM - is it GUID ? Is it possible to change naming in serialization somehow ? (also not sure)
- there is still always a way to specially handle abapGit non-code files.

**Comment by sbcgua** [comment]
@larshp one related question. I was thinking on that SMIM vs W3MI choise. 
I think W3MI looks like a better choice, in particular due to naming, mention by you.
But !
W3MI is base64ed. So css/js will not be visible in repo which spoils the whole idea.
I'm thinking about changing of W3MI serialization: xml should contain it's attributes and the file should be separate. 
W3MI was written by me and my colleague, addressing our own need, so ... maybe ... it was not much used by anyone else. So I guess how safe it is to change serialization. Potentially old deserialization code can stay for a while to support both approaches. What do you think ?

**Comment by larshp** [comment]
it would be okay to change, the serializer version is part of the XML, eg. `serializer="LCL_OBJECT_PROG" serializer_version="v1.0.0"` 

so the new code can automatically fall back to old logic or show error/warning

**Comment by sbcgua** [comment]
Mmmm, and where to change it ? And what should be the new version - 1.1 ?

**Comment by larshp** [comment]
override method `get_metadata` inherited from `lcl_objects_super`, new version would be v2.0.0, as this is breaking changes/new API

I try to follow http://semver.org/

**Comment by sbcgua** [comment]
> new version would be v2.0.0
version or serializer_version ? if serializer_version, then what to do with version ?

**Comment by sbcgua** [comment]
UPD: seem like it assigned it to serializer_version automatically ... so should be ok... but confusing :)

**Comment by larshp** [comment]
yeah, we should probably move it to each serializer instead of having it in the superclass

**Comment by sbcgua** [comment]
@larshp could you have a look at commit pls ? Seems like work fine, but I'm a bit confused with that versioning stuff. Also if it looks proper from "version concept" perspective.

P.S. I've added `get_filename_from_syspath` method to `lcl_path` and covered with UT but then I decided not to use it :)) It finds the file name from Unix or Win path. Shall I keep for future or remove (because it is not used anyhow now) ?

**Comment by sbcgua** [comment]
For history: result example (files)

![image](https://cloud.githubusercontent.com/assets/15635498/20490125/8a0ea460-b015-11e6-9183-72fa9b6e59c1.png)

**Comment by sbcgua** [comment]
Closing. Becoming too long. Actually main goal achieved. Although the final solution differs from initial description (W3MI caching was a good idea). CSS refactoring and other finetunings can be done as separate PRs/issues. As well as usage of webfonts instead of inline image data.
