### ISSUE TITLE
clone - everything shows with diff

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#375]
After a clone, seems like everything shows with diff:
![image](https://cloud.githubusercontent.com/assets/5888506/19211734/18d44d70-8d44-11e6-884b-914c873495ef.png)

Click refresh, and the diff links are gone:
![image](https://cloud.githubusercontent.com/assets/5888506/19211738/22ae82c0-8d44-11e6-8117-1c1b256dac40.png)

can be reproduced with repository: https://github.com/larshp/CLAS.git

**Comment by larshp** [comment]
for "show files" mode shows "@new remote", but all okay after refreshing

![image](https://cloud.githubusercontent.com/assets/5888506/19214356/776d7c7a-8d81-11e6-93a6-95da7bcaff1c.png)

**Comment by sbcgua** [comment]
should work now. Added clear status in online deserialize. Pushed to master directly.

**Comment by larshp** [comment]
tested, works :+1:
