### ISSUE TITLE
Performance: Deserialize is calling check twice

### ISSUE THREAD

**Issue by mbtools** [larshp/abapGit#3757]
Reproduce: 
1. Put break-point in `ZCL_ABAPGIT_OBJECTS->DESERIALIZE_CHECKS`
2. Perform a pull 
3. Break-point will be reached twice

It seems the following call is superfluous since the check results are passed to the method by a parameter already:

```
ZCL_ABAPGIT_REPO->DESERIALIZE

    deserialize_checks( ).
```

Can this simply be removed?

**Comment by larshp** [comment]
the idea behind this is to have it work in REST setup(think ADT)

the user clicks pull, call the backend returns user decisions, user chooses in the UI, the UI sends the decisions back(these should be validated, ie. second call)

**Comment by larshp** [comment]
yes, its by design in order to decouple GUI and backend, for setups with REST(think ADT)

The user clicks a button, backend `deserialize_checks` is called, the results are presented to the user to decide what to happen

Next the user decisions is sent to the backend, these must be validated as a lot of things could happen or the input be inconsistent(no control of the REST client)

**Comment by larshp** [comment]
but maybe we can do some caching somewhere, so it will be faster if its done within the same session

**Comment by mbtools** [comment]
that's not what the code is doing.

```
ZCL_ABAPGIT_REPO->DESERIALIZE

    deserialize_checks( ).

    IF is_checks-requirements-met = zif_abapgit_definitions=>gc_no AND is_checks-requirements-decision IS INITIAL.
```

the user decision is passed to deserialize as is_check. then deserialize does it's own check without evaluating the results (no return parameter). and then deserialize simply checks what was in is_check. 

To check things again should be:

```
ZCL_ABAPGIT_REPO->DESERIALIZE

    ls_check = deserialize_checks( ).

    IF ls_checks-requirements-met = zif_abapgit_definitions=>gc_no AND ls_checks-requirements-decision IS INITIAL.
```

... and we should remove the is_check parameter.

**Comment by mbtools** [comment]
on the other hand, in the background example, it's close to impossible that "things change" in the few milliseconds between the checks. if we trust the caller completing the check, we should trust what's in is_check and not check again.

**Comment by larshp** [comment]
yea, okay, the reason its called without using the return value is the exceptions, if this part is refactored somewhere else then some calculations can be avoided

![image](https://user-images.githubusercontent.com/5888506/91967691-da3fd780-ed13-11ea-8199-7dadd9ae12c1.png)
