### ISSUE TITLE
Community Call, September 2020, call for topics

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#3763]
In September we'll try to have the first online community call/meeting, to chat, to coordinate, to ask questions, to define direction etc.

Agenda:
* Deprecating 2FA, https://github.com/larshp/abapGit/issues/3150
* Major new features
* Refactoring topics
* Testing
* Moving abapGit to the abapGit organization
* ?

Feel free to add suggestions for agenda below.

More information about how/when to be added later

**Comment by FreHu** [comment]
My suggestions:

*   table data serialization concept
*   add last change date to object api, don't reserialize unchanged objects
*   combining repo and stage to single page

**Comment by sbcgua** [comment]
- roadmap (or at least long term development goals)
- refactoring of repo :) (not sure it is a topic for discussion, I guess everyone kind of agree that it is needed ... it is more a question of prototyping and pre-design)
- deployment mode (possibility to pull selected items - correlates a lot with repo refactoring and repo+stage single page above)

**Comment by pokrakam** [comment]
End-to-end integration testing with ABAP Unit, as per #3776

**Comment by christianguenter2** [comment]
Harmonization of object serializers in ABAP in the Cloud and abapGit. #3349

**Comment by bigld** [comment]
- local setup to meet abapGit's abaplint criterion
- PR discussion vs Issue discussion 
- idea for layer separation

**Comment by mariusraht2** [comment]
- Multithreading (especially (de-)serialization - not sure where we could use this too, but it should reduce the overall runtime of AG a lot)

**Comment by larshp** [comment]
summed to:


**Minor**

- 	Deprecating 2FA, #3150
- 	Moving abapGit to the abapGit organization
- 	Harmonization of object serializers in ABAP in the Cloud and abapGit. #3349
- 	Local setup to meet abapGit's abaplint criterion
- 	PR discussion vs Issue discussion, contribution guidelines

**Major new features**

- 	table data serialization concept
- 	add last change date to object api, don't reserialize unchanged objects
- 	combining repo and stage to single page
- 	deployment mode #3705, possibility to pull selected items
- 	Multithreading/multitasking, especially (de-)serialization

**Refactoring**

- 	idea for layer separation

**Testing**
`	End-to-end integration testing with ABAP Unit, as per #3776`

**Roadmap**

**Comment by larshp** [comment]
I'd like to keep the call scheduled to an hour, and keep a semi-realistic schedule, so we cannot cover everything this time around

**Comment by larshp** [comment]
closing this issue and moving to https://github.com/larshp/abapGit/issues/3834

**Comment by sbcgua** [comment]
Roadmap thoughts:
- what is abapGit ? is it just for serialization abap to git ? Then focus is supporting all possible object types
- or is it for CI/devops, blah blah automation and assistance ? E.g. running compulsory CI before commit looks very interesting, integration with abaplint ... maybe these function should grow ?
- or should it be a possibility to run ci tasks remotely via rest api ?
- if REST api then what is about UI? should be completely decoupled and developed separately (and merged with abapmerge)
- and what is UI then ? html in abap ? focus on eclipse ? focus on normal editors like vscode ? external independent PWA (progressive web app - running mostly offline) hiding into the tray (wouldn't it be cool?) ?
- or abapGit is a tool for abap open source popularization ? Then package management would be a good focus

**Comment by larshp** [comment]
* git dependencies feature

**Comment by sbcgua** [comment]
To mention: multitasking #3008
