### ISSUE TITLE
Add support to Web application flow (OAuth2.0)

### ISSUE THREAD

**Issue by abapChaoLiu** [larshp/abapGit#3766]
Hi all,

Since GitHub API password based authentication will be deprecated in near future (https://github.com/larshp/abapGit/issues/3150), I'd like to try to add support to Web application flow.

The Web application flow is based on OAuth2.0.
Once the access to GitHub is granted in SAP, no user name or password is required anymore.
OAuth2.0 is only supported by SAP_BASIS 7.31 SP5. (#3302 and OSS Note 1717249).

Any hint on where should I start?

**Comment by mbtools** [comment]
Hi Chao,

the core login logic is here: https://github.com/larshp/abapGit/blob/master/src/http/zcl_abapgit_http.clas.abap#L126
There are a couple of exits that you might be able to use https://docs.abapgit.org/ref-exits.html. Ultimately, the method has to return an instance of the HTTP client that is authorized to exchange data with the server. 

Or try to replace the complete method with the OAuth logic. When it works, we can figure out how to integrate it with the existing code.

**Comment by abapChaoLiu** [comment]
Hi Marc,

Thank you for your help. I'll start to work on this soon.

Regards,

Chao

-------------------------------------------------- 

Chao Liu 

Platinum DB, Inc. 

Email: [ mailto:chao.liu@ss-us.com | cliu@platinumdb.com ] 


Cell: 224-432-3522 

: [ https://www.linkedin.com/in/chaoliu4BPC | Chao Liu ]

----- Original Message -----

**Comment by abapChaoLiu** [comment]
New issue: **ALL** HTTP calls have to go through API endpoint https://api.github.com/.

It's noticed that some HTTP calls are trying to access GitHub repo URLs in the format of https://github.com/{username}/{repo}/.
But endpoint https://github.com/ is **NOT** available if the HTTP client is authorized via Web Application Flow (OAuth2). 

To utilize Web Application Flow (OAuth2), we have to point HTTP calls to endpoint https://api.github.com/ and re-implement them using APIs under https://api.github.com/. Is this possible and do we really want to do it? :)

**Comment by abapChaoLiu** [comment]
I'm going to close this issue because under Web application flow (OAuth2.0), git transfer protocols, both dumb and smart, are not available for abapGit.
1. For abapGit, only endpoint https://api.github.com/ is available under Web application flow (OAuth2.0) by design.
2. Git transfer protocols require access to endpoint https://github.com/ which won't be available.
3. Technically, we can [use git over Web application flow](https://github.blog/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/). But the Access Token is not accessible in ABAP layer since it's managed and protected by kernel ( see method CL_ICF_PLUGIN_SESSION_RT=>_SET_OA2C_INFO() ). Also there's certainy security risks in this approach, like Clone is not recommended.

**Comment by larshp** [comment]
abapGit uses the smart git transfer protocol via https via access to the endpoint https://github.com

**Comment by abapChaoLiu** [comment]
Find something interesting. 
Git access is possible for both GitHub App via JWT token and OAuth App via deploy key.
Will try the deploy key approach first. If it works, I may reopen this issue.
![image](https://user-images.githubusercontent.com/48561271/93351057-dd9c8e00-f7fe-11ea-9fae-0cb2216a29c5.png)
