### ISSUE TITLE
database content under version control 

### ISSUE THREAD

**Issue by cpoliwoda** [larshp/abapGit#3772]
Hello,

Is it possible in abapgit to put the content of a database under version control?

I have done some tests with different branches, adding and deleting columns and changing the values of the rows. 
But switching from a branch with more columns to a branch with fewer columns causes value loss in the additional column in my tests when I commit some changes to the table and return to the branch with more columns.

Is there a way to handle the change of the table structure and table values to the corresponding structure?

Regards,
cpoliwoda

**Comment by FreHu** [comment]
Only development objects are currently serialized, but this would be a very useful addition and has been discussed before. See

#3441, #3763

**Comment by cpoliwoda** [comment]
Hello, FreHu,

Thanks for the answer with the links. I did not find the issues when I searched for the topic. 
I am curious if the feature will make it on the implementation list.

Regards,
cpoliwoda
