### ISSUE TITLE
Double scroll-bar

### ISSUE THREAD

**Issue by mbtools** [larshp/abapGit#3773]
Is it just me getting double scroll-bars on the right after some navigating?

Start AG:

![image](https://user-images.githubusercontent.com/59966492/90683945-5a0a7400-e235-11ea-89f6-bde2f6335d1f.png)

One nav step:

![image](https://user-images.githubusercontent.com/59966492/90684168-bf5e6500-e235-11ea-8b12-bc47fb909735.png)

**Comment by larshp** [comment]
only if I resize the window after a page was rendered

**Comment by mbtools** [comment]
the issue disappeared after update to sapgui 7.6 patch 8
