### ISSUE TITLE
Multiple syntax error on latest build of standalone report 

### ISSUE THREAD

**Issue by eljoaco** [larshp/abapGit#3775]
Hi,

When compiling de latest build of the standalone report I'm getting muliple syntax errors.
	
![image](https://user-images.githubusercontent.com/29739737/90790278-2b110280-e308-11ea-908a-57a360dd19d9.png)

Please, check attached screenshot.

Thanks!

**Comment by larshp** [comment]
thanks what is your SAP_BASIS version?

I'm guessing its all inside class https://github.com/larshp/abapGit/blob/master/src/objects/zcl_abapgit_object_wdcc.clas.abap in the report, can you help checking?

**Comment by eljoaco** [comment]
Hi,

we are running 702 release version of SAP_BASIS.

And yes, you guessed right... all syntax error are in the class zcl_abapgit_object_wdcc in the implementation methods of the interface zif_abapgit_object (~delete, ~serialize, and ~deserialize)

After commenting the local class the report has activated correctly,

Many thanks for your help!

**Comment by larshp** [comment]
@eljoaco try again, latest version, if there is still problems feel free to reopen this issue

**Comment by eljoaco** [comment]
Thanks @larshp , latest versión worked perfectly fine 👍

**Comment by larshp** [comment]
and thanks to @mbtools that actually fixed it 💪
