### ISSUE TITLE
Password / credential storage [Discussion]

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#3798]
It may be a nice feature to have password/token storage. Copying token from a text file is inconvenient and not quite secure. Here are some ideas and thoughts. Input is welcomed

## Internal to SAP

- store passwords/token in `zabapgit` table, in user specific entry. Just for the sake of discussion - it's totally insecure (though may fit systems like NPL)
- use SAP internal features to store user specific encrypted (based on user password) data. This would be the best. I have no I idea if there is such a feature? **Does anyone aware if such functionality exists ?**
- store credentials in `zabapgit` table but encrypted. AES + salt, based on master password from user. So kind of pass manager - more convenient than copy-paste tokens. But essentially comparable level of security to open text ... any mid-skilled developer will hijack it in a common dev env. 

Frankly speaking, seems that **ANY** solution would be prone to hijacking by another dev ... so maybe there is no completely secure option.

## external to SAP:

- text file from the user pc (in a typical place, to read it automatically). Mmm. Kind of better than in SAP, but ...
- same plus encryption
- a COM component, accessible via OLE. Could seem complicated, but in fact modern windows does contain C# compiler, so it should be possible to transparently deliver and compile such a component to the user machine on-the-fly. But yeah, it is relatively complicated. And maintainability is poor. So for the sake of discussion.
- JS based local storage. AFAIK Chrome does control that local storage is accessible by the same page that used to write it ... but is it the same for IE ? Could be insecure. Maybe a combination of local storage and encryption ?
- JS based solution to access some local facilities like Windows Credential Manager (not the most secure stuff but ...)

Any more ideas/thoughts ?

**Comment by larshp** [comment]
I'd like not to get into the password storage business, at least not part of the core setup, but maybe link to some solutions in the documentation

If its a single user system, the user can add the passwords via user exit https://docs.abapgit.org/ref-exits.html

External, some people use keepass, see https://github.com/larshp/abapGit/pull/1262

**Comment by flaiker** [comment]
> use SAP internal features to store user specific encrypted (based on user password) data. This would be the best. I have no I idea if there is such a feature? Does anyone aware if such functionality exists ?

Sure, there is the secure storage used by for example SM59 to maintain user data for RFC destinations. If I recall correctly there is no way to retrieve the unencrypted password from the ABAP side though. You can already use an RFC destination with the exit but then everyone else on your shared system can as well. You could restrict the authorizations for the destination but then again you can circumvent that check in the debugger.

I just use keepassxc with autofill for the authorization popup (please don't replace it with a JS form whose window title is not unique...).

**Comment by larshp** [comment]
https://help.sap.com/viewer/280f016edb8049e998237fcbd80558e7/7.5.9/en-US/4eeb2dce10f2398de10000000a42189b.html

> For legal reasons, only SAP applications may use the secure storage. We therefore use technical measures to prevent the secure storage being used in customer developments.

**Comment by mbtools** [comment]
Agree with Lars. No storing of passwords in AG (or other personal info). It would open up a big can of worms.

A uniquely identifiable username/password popup plus external password manager is the way to go.

**Comment by sbcgua** [comment]
Hmmm. Yeah. Well, the professor of [coursera cryptography course](https://www.coursera.org/learn/crypto) also suggested to never invent encryption tools ... at least we now have a discussion about this subject :) 

BTW I think a template code for the user exit in doc - is a good idea. 

@flaiker could you please tell how you managed keypass to auto fill abap popup ? I didn't manage to do it :(

**Comment by sbcgua** [comment]
I let it hang here for a while if you don't mind. To collect more ideas. Then maybe ok to close. 

P.S. @larshp by the way a good example for github discussion feature

**Comment by flaiker** [comment]
> @flaiker could you please tell how you managed keypass to auto fill abap popup ? I didn't manage to do it :(

Just have the login window open and select it in the auto type settings of the keepass entry. Should be something like

`NPL(*)/001 Login: github.com`

You might want to change it to the star in the brackets as the external mode identifier may of course change.

The focus depends on wether abapGit already has your username saved for the url. Unfortunately KeepassXC does not support the Shift+Tab sequence (+{TAB}) which normal Keepass does so I just tab forward until the username is focused again using `{TAB}{TAB}{TAB}{USERNAME}{TAB}{PASSWORD}{ENTER}`. When the popup opens I just press Ctrl+Alt+A to fill it.

Also works really well for me on the SAP logon screen and the ADT login popup, even with multiple users and clients on the same system. Then there is a selection popup.

**Comment by larshp** [comment]
would someone using Keepass like to add how to set it up to the documentation? https://docs.abapgit.org ?

otherwise I suggest closing the issue

**Comment by sbcgua** [comment]
ok to close from my side. imho well discussed, useful as a knowledge base, but no next steps

**Comment by cawoodmonads** [comment]
It's a real pain to have to constantly type in long PATs as a password in abapGit - even with a password manager.

If abapGit would just use SM59 Destinations for all HTTP(S) calls the issue would be solved since the credentials can be securely saved in SAP.

**Comment by larshp** [comment]
feel free to open new issues with questions, we dont want to keep adding history to closed issues

SM59: this is possible as is

**Comment by mbtools** [comment]
See https://docs.abapgit.org/user-guide/reference/exits.html#create-http-client
