### ISSUE TITLE
Error in Nightly Batch Job Update of abapGit

### ISSUE THREAD

**Issue by hardyp** [larshp/abapGit#3800]
Often I get the following error message:-

![image](https://user-images.githubusercontent.com/7078215/91294224-86e1fc80-e7dc-11ea-8ae6-1d710fddde24.png)

The exact class name changes over time, but the message is the same,

If I manually "pull" the latest version the error goes away for a few days, then starts again....

**Comment by larshp** [comment]
@hardyp try this, https://github.com/larshp/abapGit/pull/3802

**Comment by larshp** [comment]
@hardyp try again, latest version

**Comment by hardyp** [comment]
I downloaded the latest version, saw that the code had changed, and the job has stopped crashing, so all is well.
