### ISSUE TITLE
Reset Local (Force Pull) not resetting/overwriting Objects if language pack is installed recently

### ISSUE THREAD

**Issue by habrahams** [larshp/abapGit#3819]
When I do a force pull / reset local, I am unable to reset the below objects to original, after a Language Pack was installed.

Abapgit 1.99.0
![image](https://user-images.githubusercontent.com/16045067/91704237-9fa33700-eb7b-11ea-8858-f444f7f4998a.png)
![image](https://user-images.githubusercontent.com/16045067/91704260-aaf66280-eb7b-11ea-986c-351c07a4a854.png)
![image](https://user-images.githubusercontent.com/16045067/91704294-b77abb00-eb7b-11ea-895f-c67d4963f7ae.png)

**Comment by larshp** [comment]
try going to settings for the repository, and check "Serialize Master Language Only"

![image](https://user-images.githubusercontent.com/5888506/91704727-4ab3f080-eb7c-11ea-9348-85bf295390bb.png)

**Comment by larshp** [comment]
its a workaround, but 🤷‍♂️
