### ISSUE TITLE
Error while using ABAPGIT

### ISSUE THREAD

**Issue by sangita-p** [larshp/abapGit#3821]
Hi,

We are following this blog : https://developers.sap.com/tutorials/abap-environment-abapgit.html to establish the connection with ABAPGIT and clone a GIT repository. A couple of months back we were able to establish the connection successfully by performing all the necessary configurations like SSL Setup, running the program ZABAPGIT_TEST_SSL to test the connection. We were successfully able to git clone from the repository "https://github.com/sangita-p/abapgitrepo2"

But now when we try to access the same repository by running the ABAPGIT program, we get the error as "Error: HTTP error 411 occured: Direct connect to github.com:443 failed: NIECONN_REFUSED(-10)". Sceenshot below:
![image](https://user-images.githubusercontent.com/57656604/91724066-5b835700-ebba-11ea-9848-25c0aaab84cb.png)

Also please find the SSL certification which has been configured in the STRUST. 
![image](https://user-images.githubusercontent.com/57656604/91724037-4d353b00-ebba-11ea-950b-b0e72714470e.png)

Also when we run the program ZABAPGIT_TEST_SSL, we get the error given in the screenshots below:
![image](https://user-images.githubusercontent.com/57656604/91724203-95ecf400-ebba-11ea-8426-b4f762f1ce08.png)

![image](https://user-images.githubusercontent.com/57656604/91724266-aac98780-ebba-11ea-9978-f32762cc7e42.png)

Can you please help us know what would have changed that the same setup is not working any more?

Regards,
Sangita

**Comment by larshp** [comment]
NIECONN_REFUSED is typically a connection refused error, suggest trying to login to the application server and verify that it is possible to connect to github.com

Is the server behind a firewall? Is it behind a proxy?

**Comment by g-back** [comment]
Looks like the github certificates are missing (they recently expired in May)? 
See docs here: https://docs.abapgit.org/guide-ssl-setup.html
Also: https://docs.abapgit.org/guide-ssl-setup.html#note-on-actions-that-require-authentication

Certificate List should include these two:
![image](https://user-images.githubusercontent.com/27279305/91725448-0ab23500-eb9f-11ea-8495-65c86daa9b4d.png)

**Comment by sbcgua** [comment]
Could be also due to missing profile settings (see the same doc - https://docs.abapgit.org/guide-ssl-setup.html#note-about-github)
```
ssl/client_ciphersuites = 150:PFS:HIGH::EC_P256:EC_HIGH
ssl/ciphersuites = 135:PFS:HIGH::EC_P256:EC_HIGH
icm/HTTPS/client_sni_enabled = TRUE
```

**Comment by larshp** [comment]
@sangita-p  did above help?

**Comment by sangita-p** [comment]
Still trying to resolve the issue. Will keep you informed on the findings

**Comment by sangita-p** [comment]
I have imported the new certificates from github.com into STRUST.
![image](https://user-images.githubusercontent.com/57656604/92083635-f1e69100-ede3-11ea-9813-b0ba0727d1d3.png)

But when I run the ABAP Program ZABAPGIT_TEST_SSL, I am still getting the same error:
![image](https://user-images.githubusercontent.com/57656604/92083750-13477d00-ede4-11ea-8733-3095a0a3adc0.png)

When I goto smicm > Goto > Trace File > Display End, I see the below error:
![image](https://user-images.githubusercontent.com/57656604/92083841-3540ff80-ede4-11ea-8b8d-b33010e58570.png)

The system where we have imported the certificates in an on-premise system.

Regards,
Sangita

**Comment by flaiker** [comment]
Your first screenshot still only shows the root and intermediate certificate and not the server certificate of GitHub?

In some configurations you need the full certificate chain and in others you only need the root certificate (no idea when which scenario is relevant).

**Comment by flaiker** [comment]
I just noticed the docs seem to have been updated and say that you only need the root certificate now instead of all three of the chain? I don't think that works on all releases.

**Comment by flaiker** [comment]
It still show DigiCert for me o0

![image](https://user-images.githubusercontent.com/5270359/92105133-ab446700-ede2-11ea-90cb-3258625c7aaa.png)

**Comment by sangita-p** [comment]
Yes (Digicert and with 2 levels of certification). This is what I downloaded and uploaded yesterday into the on-premise system. And I uploaded both the certificates. This is the correct one right?

**Comment by sangita-p** [comment]
A couple of months back, the same Digicert certificates with 2 levels were imported into the same and the connection with abapGIT was working perfectly fine. I re-imported these certificates which was downloaded again yesterday, into our system as someone in the above chain mentioned that the certificates expired in May.

**Comment by larshp** [comment]
note the peer ip address which is Vodaphone india
![image](https://user-images.githubusercontent.com/5888506/92109751-de3e2900-ede9-11ea-91a4-c0201832d867.png)

> NIECONN_REFUSED is typically a connection refused error, suggest trying to login to the application server and verify that it is possible to connect to github.com
> 
> Is the server behind a firewall? Is it behind a proxy?

**Comment by mbtools** [comment]
you need all 3 levels. you are missing the github.com cert.

![image](https://user-images.githubusercontent.com/59966492/92166990-a04ffd80-ee07-11ea-9c1c-502df94b8280.png)

If you want to update private repos, you will also need the *.github.com which you can get from https://api.github.com/.

**Comment by sangita-p** [comment]
> note the peer ip address which is Vodaphone india
> ![image](https://user-images.githubusercontent.com/5888506/92109751-de3e2900-ede9-11ea-91a4-c0201832d867.png)
> 
> > NIECONN_REFUSED is typically a connection refused error, suggest trying to login to the application server and verify that it is possible to connect to github.com
> > Is the server behind a firewall? Is it behind a proxy?

We imported all the 3 certificates now, but still getting the same error when we goto smicm> Goto > Trace File > Display End
![image](https://user-images.githubusercontent.com/57656604/92223695-76a5dd80-eebe-11ea-9b6a-a97be29bc016.png)

Yes the ABAP sever(N1D) that we are using is behind a firewall. Can you please elaborate what do you mean by "uggest trying to login to the application server and verify that it is possible to connect to github.com"? How do we check this?

**Comment by larshp** [comment]
if its linux, `ssh` into it and verify with `curl` or `wget`, if its windows then open via `rdp` and check the browser can access https://github.com

**Comment by sangita-p** [comment]
Thanks for the help. It was a networking issue. We are successfully able to connect to abapGIT with github

**Comment by larshp** [comment]
👍 closing

**Comment by jayesh-mudaliar** [comment]
Hello all,
I am getting the same issue as above, I tried everything as explained above still not able to connect to Online Repository.

Only breakthrough  i got is in prog ZABAPGIT_TEST_SSL, I entered the P_PROXY and Port and it succeeded.
<img width="323" alt="Capture" src="https://user-images.githubusercontent.com/77326578/106896567-c1e74500-6717-11eb-8620-89e9df44676d.PNG">

But when I tried to execute and connect to https://github.com/abapGit/abapGit/ . It has given me the same error as aobe one.
![image](https://user-images.githubusercontent.com/77326578/106897137-88630980-6718-11eb-9ba2-720da8a1d58a.png)

Can anybody suggest where I am lagging? Where do i need to update the Proxy parameter?
Is it in here?
![image](https://user-images.githubusercontent.com/77326578/106897532-0cb58c80-6719-11eb-8a9c-c908a306bf16.png)

**Comment by larshp** [comment]
@jayesh-mudaliar please open new issues for new/additional issues

anyhow, setup the proxy settings under https://docs.abapgit.org/guide-settings-global.html

**Comment by jayesh-mudaliar** [comment]
> @jayesh-mudaliar please open new issues for new/additional issues
> 
> anyhow, setup the proxy settings, see https://docs.abapgit.org/guide-settings-global.html

Thanks@larshp You are genius!! It worked!! I can blame myself for not reading the whole document and jumping into the action!!
