### ISSUE TITLE
Multiple login dialogs on cancel from repo list

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#3826]
- Click on a repo that requires authentication in repo list
- The login popup appears
- You want to cancel and click cancel in the dialog
- The message "Falling back to master branch" appears
- The login popup appears 3 more times before the operation is cancelled

I don't remember it being this way before. I guess somewhere zcx_abapgit_cancel needs to be handled separately in a catch block.

**Comment by flaiker** [comment]
Also after you are finally back in the repo list and you click on some other repository that does not require authentication the login popup for the previous repo appears again ?! You need to cancell that one 2 times then and restart abapGit completely to open any other repo.

**Comment by mbtools** [comment]
Adding the commit hash to the header causes an earlier logon than before. Canceling (or any HTTP error) will lead to the above behaviour. I'm working on a fix.
