### ISSUE TITLE
Unify naming of standalone version

### ISSUE THREAD

**Issue by g-back** [larshp/abapGit#3829]
Currently it's still `REPORT ZABAPGIT_FULL` in the merged/built version  -> change to `ZABAPGIT_STANDALONE` as it is called in the [docs ](https://docs.abapgit.org/guide-install.html#install-standalone-version)?

**Comment by larshp** [comment]
yea, think ZABAPGIT_STANDALONE is the best name for it

**Comment by larshp** [comment]
try changing https://github.com/larshp/abapGit/blob/master/package.json#L5-L6
