### ISSUE TITLE
CL_OO_CLASSNAME_SERVICE=>GET_ALL_CLASS_INCLUDES not available

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#383]
I'm trying to install abapGit in another system (which I though had the same version as the one I'm already using it on but after all...) I'm getting compilation errors:

![image](https://cloud.githubusercontent.com/assets/532049/19239799/9ff487fe-8eff-11e6-8ddf-72d8185c899f.png)

The first problem listed is related to class CL_OO_CLASSNAME_SERVICE which appears to be in an older version than what's needed:

![image](https://cloud.githubusercontent.com/assets/532049/19239720/4a2fbf82-8eff-11e6-81b7-ce403188ce06.png)

Can the method be replaced by something else available earlier?

Here are the versions on my problematic system:
SAP ECC 6.0
SAP_BASIS	702	0014	 SAPKB70214	SAP Basis Component
SAP_ABA	702	0014	 SAPKA70214	Cross-Application Component

And here are the versions on my ok system:
EHP6 FOR SAP ERP 6.0
SAP_BASIS	731	0005	SAPKB73105	SAP Basis Component
SAP_ABA	731	0005	 SAPKA73105	Cross-Application Component

Thanks,
Nuno

**Comment by larshp** [comment]
For CONTROLLER_EXCEPTIONS: comment out the 4 lines with errors. This is related to exceptions in web dynpro applications, so you might run into trouble if you use web dynpro


CL_OO_CLASSNAME_SERVICE=>get_all_class_includes: this is quite new functionallity, in method
```
CLASS lcl_object_clas IMPLEMENTATION.

  METHOD lif_object~has_changed_since.
```
replace all the code in the method with `rv_changed = abap_true.`, this method is for optimizing performance

**Comment by larshp** [comment]
class stuff fixed, following 4 lines has to be commented on 702, related to WDYN exceptions:

```
    ls_obj_old-wdyc-excp  = is_controller-controller_exceptions.
    ls_obj_old-wdyc-excpt = is_controller-controller_exception_texts.
```

and

```
        controller_exceptions        = rs_controller-controller_exceptions
        controller_exception_texts   = rs_controller-controller_exception_texts
```

**Comment by larshp** [comment]
closing issue, I've added a note about 702 in the installation guide: https://github.com/larshp/abapGit/wiki/Installing-abapGit
