### ISSUE TITLE
Autostart without popup

### ISSUE THREAD

**Issue by mariusraht2** [larshp/abapGit#3838]
It'd be cool if there would be an option in global settings to be able to suppress the autostart popup after update.

**Comment by mbtools** [comment]
are you refering to https://github.com/larshp/abapGit/pull/3804? without the popup there's no way to notify the user of what happens. but maybe that's not necessary in this case. 

Remove https://github.com/larshp/abapGit/blob/093f0d6ca0286de0db085bd5e23d34290c213d58/src/zcl_abapgit_repo.clas.abap#L260 or change it to "S" which might show for a sec in the status bar and see how you like it.

**Comment by mariusraht2** [comment]
Yes, which is a really great feature by the way - thanks for the implementation!

Should we add an option for that or just remove the message at all?

**Comment by mbtools** [comment]
if a user has "Show Last Opened Repository" turned on, autostart will take them right back where they are. we could skip the popup in this case.

**Comment by mariusraht2** [comment]
I'll implement it that way but find it a little awkward to bind it to that property: One who don't want to open the last opened repo on start-up can't suppress the popup. But we can change again it if needed later - it's not critical for the user experience.

**Comment by mariusraht2** [comment]
I'm not happy with this solution: lars is right: It's not consistent plus in my opinion not comprehensible why it's bound to this option. I'd like to show the message always for 1 second and then start the autostart by itself without confirming.
