### ISSUE TITLE
CLAS: Looks like class "locals_imp" is not deleted at pull

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#384]
Steps to reproduce:
1: Create class with local class implementations, ie. file `zcl_name.locals_imp.abap` should exist
2: install repo in system 2
3: delete locals implementation and commit+push
4: pull in system 2 => locals_imp is not removed

note: I have not tested above steps yet
note: above steps can probably also be performed using branches

**Comment by EduardoCopat** [comment]
Tested using two different systems. Bug happens.

System 2 treats the local classes as if they were added, not removed:

![image](https://cloud.githubusercontent.com/assets/2248490/22507225/e944e1a4-e884-11e6-847f-7ab41b74c1f2.png)

But it was removed:
https://github.com/EduardoCopat/abap-sandbox/commit/84fc1778d9ac7ee73fb97e51a7809687874cf8e2

**Comment by EduardoCopat** [comment]
Actually seems like the problem is deeper. I removed a "DOMA" domain object from repo in system 1, and when refresing in system 2, it also wants to add, instead of delete.

![image](https://cloud.githubusercontent.com/assets/2248490/22507970/3a6f89aa-e888-11e6-9495-36a328df5aed.png)

**Comment by larshp** [comment]
Status: deleted remote or added locally, yes, this is confusing, however I guess the correct status cannot be determined without looking at the history.

Anyhow, the local class implementation should be deleted when during pull

**Comment by EduardoCopat** [comment]
@larshp 
What if we mark the objects as deleted? an extra tag in XML to mark it to delete... 
It may add more "xml metadata", but removes the confusion.

This would also solve the "local class" pull problem.

**Comment by larshp** [comment]
Then if deleting 10 objects, there would be 10 extra xml files forever in the repository?

**Comment by EduardoCopat** [comment]
It is indeed too much overhead...

Just for brainstorming: What if this information is kept in .abapgit.xml (<deleted_items>).

**Comment by larshp** [comment]
hmm, guess it will still not be straight forward

if file is in <deleted_items>, and user adds it in the system again, it should show as added instead of deleted?

**Comment by EduardoCopat** [comment]
Yeah, I also thought of this case. If user adds again, then it should be removed from "deleted items".

**Comment by EduardoCopat** [comment]
@larshp I've been debugging this issue for quite a long time. I can't find a way to solve this... 

We would need to know if a file was deleted in the repository. Is that even possible to do with that crazy git protocol that is used in the `git_porcelain` class?

**Comment by larshp** [comment]
but the CLAS deserialization is called? it should be responsible for removing/updating the include

**Comment by EduardoCopat** [comment]
Yes, it is called. But then, should I somehow set a flag in the CLAS deserialize that for this particular deserialization it should not deserialize locals? 

If so, how do I know when I should set this flag? Every time a pull is done?

**Comment by larshp** [comment]
but the local does not exist, so after deserialization of the class the local should not exist in the system

**Comment by EduardoCopat** [comment]
@larshp OK......... Let me investigate further...

**Comment by larshp** [comment]
my guess is that SEO_CLASS_GENERATE_LOCALS does not delete the include when `it_local_definitions` is empty

```abap
    CALL FUNCTION 'SEO_CLASS_GENERATE_LOCALS'
      EXPORTING
        clskey                 = is_key
        force                  = iv_force
        locals_def             = it_local_definitions
        locals_imp             = it_local_implementations
        locals_mac             = it_local_macros
        locals_testclasses     = it_local_test_classes
```

**Comment by larshp** [comment]
looks like the behavior is the same as when a PROG is deleted, abapGit does not do the deletion

perhaps we should just leave this as is

**Comment by larshp** [comment]
leaving as is
