### ISSUE TITLE
Repo-specific title of login popup

### ISSUE THREAD

**Issue by mariusraht2** [larshp/abapGit#3845]
I think it would be useful if the login screen would have a repo-specific title to be able to use external tools like Keypass via shortcuts. Maybe we should just set the title to the repo name?

**Comment by mariusraht2** [comment]
ZABAPGIT_PASSWORD_DIALOG=>lcl_password_dialog->popup

**Comment by mbtools** [comment]
not it shows the domain and one login to a domain is sufficient for all repos on that domain. no?

**Comment by mariusraht2** [comment]
Yea, missed that - will close.
