### ISSUE TITLE
Background mode ->error No transport request was supplied

### ISSUE THREAD

**Issue by anagarcigm** [larshp/abapGit#3857]
Hi, I don´t know what is the problem.
When I execute in background mode with a job(sm37), in the log appears "No transport request was supplied".

If I execute zabapgit and enter in the option background mode and execute the option "Run Background logic", in he log appears the same message.

I have tested with two different repo:

- Repo with objects created with pull manually. When  I pull appears the message "Order xxx is set as standard request".  After I introduce a change in one object and execute the option "Run Background logic".  In the log appears the error message but objects are blocked in the transport order.
- Repo with only a package. I use the option to create a repo online. (Create the repo and the package)
When I pull all the new objects of the repository with the option "Run Background logic", I receive the same error message.

![TransportOrder](https://user-images.githubusercontent.com/56394203/92478371-5dfd3680-f1e2-11ea-864f-270506c50ee6.PNG)

![abapgit_background](https://user-images.githubusercontent.com/56394203/92478332-4cb42a00-f1e2-11ea-9b6e-19ed2e95f5b9.PNG)

I have this git to test it. https://github.com/anagarcigm/TEST_DEMO.git

**Comment by anagarcigm** [comment]
Good Morning,

I have been debugging and I have found the error message.
The error message is in the class ZCL_ABAPGIT_REPORT, method DESERIALIZE.  
The problem is that is_checks-transport-transport isn´t being filled (line 16).
I have seen that this structure is filled in class zcl_abapgit_objects, method DESERIALIZE_CHECKS, fields like   rs_checks-transport-required or   rs_checks-transport-type is filled.

I have found a class zcl_abapgit_default_transport with a method set but it is not called in this methods but it appears in zcl_abapgit_objects=>deserialize.

If i put in the line 20 of method deserialize_checks "rs_checks-transport-transport = zcl_abapgit_default_transport=>get_instance( )->get( )-ordernum." the problem is solved.
I don´t know if this error is due to reorganization/fusion (deserialize, deserialize_checks) of objects and this sentences now is not used.

Best regards.
Ana

**Comment by larshp** [comment]
so, there is no way to supply a transport number to a background task

only possibility is to implement the logic for transport determination, implement interface `ZIF_ABAPGIT_BACKGROUND` and it should show up in the list

**Comment by anagarcigm** [comment]
Hi larshp,

So then if you want to do a pull in background mode, you can do only with local package.
I have tested the process of background mode many times doing pull, and if i had a transport order set as a standard request the process worked.
I don´t know if it is a recently change but this process works pulling objects.

**Comment by larshp** [comment]
currently, yes

you can implement interface `ZIF_ABAPGIT_BACKGROUND` and add logic to determine/create the transport number

**Comment by anagarcigm** [comment]
Good Morning,

I would like to know if this logic will be incluyed in a future. 
I don´t know if you can tell me this information.

Thanks in advance,
Best regards.

**Comment by larshp** [comment]
creating/determining transport numbers are very process dependent, 

must transports be created manually by a user? Or automatically by the system? Or automatically by CHARM? If creating the transport, what should the description be? If the transport is deleted or released, what should happen? What if tasks are released in the transport?

**Comment by anagarcigm** [comment]
Hi larshp,

We have created a service that create a transport request, a package and set the order as a standard. After create an online repo y complete the data of user and password. After create a job to run zabapgit.This last step doesn´t work.
At your first question -> automatically.
The order will be released manually once you check that the pull of all objects have been done well.
The transport order will be in which package is blocked.

Thanks in advance.

**Comment by larshp** [comment]
What is your overall goal, and what design decisions have you already made?

I'm guessing it would be easier for you to call the pull API, https://docs.abapgit.org/development/api.html

**Comment by anagarcigm** [comment]
Hi larshp,

Good idea. I have used the pull api and pass the transport order and it works well.
