### ISSUE TITLE
exception METHOD_NOT_EXISTING at ZCL_ABAPGIT_GUI_PAGE_CODI_BASE->RENDER_RESULT_LINE not caught

### ISSUE THREAD

**Issue by gardian12** [larshp/abapGit#3863]
class: ZCL_ABAPGIT_GUI_PAGE_CODI_BASE
method: RENDER_RESULT_LINE
at line: 36

...
ls_mtdkey = cl_oo_classname_service=>get_method_by_include( is_result-sobjname ).
...

calling get_method_by_include( is_result-sobjname ) must be covered by try...catch block otherwise these exceptions are not handled:

- CLASS_NOT_EXISTING

- METHOD_NOT_EXISTING

This actually happen while calling the code inspector.

**Comment by mbtools** [comment]
I will add the try catch, of course. Thx

However this points to another issue. How did SCI find a problem in a class or method that doesn’t actually exist?

**Comment by FreHu** [comment]
#3649 is possibly related

**Comment by gardian12** [comment]
Regarding your question: I figured out that the root cause was an exception much deeper in the call stack (single SCI check rule failed). But SCI doesn't catch exceptions correctly either. That's how it happens.

**Comment by FreHu** [comment]
Also feel free to open an incident on SCI if you feel this is really a SAP issue.

**Comment by mbtools** [comment]
@gardian12 you are running an older version. the call has been changed already and is handling exceptions properly:
https://github.com/larshp/abapGit/blob/master/src/ui/zcl_abapgit_gui_page_codi_base.clas.abap#L231

**Comment by larshp** [comment]
@gardian12 try again, latest version

**Comment by larshp** [comment]
closing, no reply

**Comment by gardian12** [comment]
Sorry for late respond. Got problems to update abapGit.
Problem solved.
