### ISSUE TITLE
Failure pulling object SHI3 - object still in use

### ISSUE THREAD

**Issue by habrahams** [larshp/abapGit#3869]
When pulling a object of type SHI3, I get the following error:
![image](https://user-images.githubusercontent.com/16045067/92908584-a73dc800-f426-11ea-9471-b79ea40d0327.png)

**Comment by mbtools** [comment]
bug in delete method

**Comment by larshp** [comment]
@habrahams try again, latest version

**Comment by habrahams** [comment]
@larshp I'm still experiencing this issue for some or other reason, and I'm still getting the same error. I updated Abapgit, checked that there are no differences between the source system and the repo, pulled on target system and the result is the same(Target system's Abapgit is also up to date). I also made sure that the "original system" and transport locking is not causing this issue. Are there any specific steps you followed when testing to confirm that the issue is resolved?

**Comment by larshp** [comment]
@mbtools , https://github.com/larshp/abapGit/pull/3873

**Comment by mbtools** [comment]
With https://github.com/larshp/abapGit/pull/3901 it will delete the object first before saving it with the new settings. If you still get an error, then we need a public repo to reproduce it, pls.

**Comment by larshp** [comment]
@habrahams try again, latest version

**Comment by habrahams** [comment]
@larshp , tried to quickly test, but I ran into another AG short-dump issue with the latest version. I created issue #3916. I will retest as soon as I'm able to resolve this.

**Comment by habrahams** [comment]
@larshp , I pulled the object again and I didn't get an error this time, but there are still differences between the local and remote object.
![image](https://user-images.githubusercontent.com/16045067/93764738-ec76ac80-fc13-11ea-8a51-d837a7b606cf.png)

**Comment by mbtools** [comment]
https://github.com/larshp/abapGit/pull/3923

**Comment by larshp** [comment]
@habrahams try again, change by @mbtools https://github.com/larshp/abapGit/pull/3923 merged

**Comment by habrahams** [comment]
Issues resolved, thank you very much @mbtools , @larshp!
