### ISSUE TITLE
Parsing forms, ZCL_ABAPGIT_HTML_FORM

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#3881]
@sbcgua one idea,

instead of having to write PARSE_FORM for each form,
https://github.com/larshp/abapGit/blob/af5b898a37d1508a6d0acb0fcdbac1ef75badc16/src/ui/zcl_abapgit_gui_page_addonline.clas.abap#L91

then have it as a method on the form itself? So in the ON_EVENT, instantiate the form(without rendering it), and then call parse()

**Comment by sbcgua** [comment]
Potentially. But this methods do 2 things. 1) pre-validate unexpected fields (probably can be solved) 2) pre-processing of values (like in the example) - may not be that easy to unify (probably not possible at all, and we will need an extra pre-process method in each form). But yes, make sense too look closer into it. I would also correlate it with event processing refactoring (cannot find the issue number - but idea was to have a dedicated class for post_data parsing and etc)

**Comment by mbtools** [comment]
https://github.com/larshp/abapGit/issues/3602

**Comment by larshp** [comment]
see #3602 instead, closing
