### ISSUE TITLE
Object to files - add option to export dependent objects

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#3889]
For abaplint dependencies, it would be useful if you could export for example a structure with all related domains/data elements.

**Comment by larshp** [comment]
see https://github.com/abaplint/abaplint-sci-client

https://github.com/abaplint/abaplint-sci-client/blob/master/src/zabaplint_dependencies.prog.abap can commit everything to git
https://github.com/abaplint/abaplint-sci-client/blob/master/src/zabaplint_list_deps.prog.abap lists dependencies by name
https://github.com/abaplint/abaplint-sci-client/blob/master/src/zabaplint_debug.prog.abap can download a full zip for a object which can be run through abaplint
