### ISSUE TITLE
Syntax errors in 702

### ISSUE THREAD

**Issue by mbtools** [larshp/abapGit#3897]
- [ ] @larshp https://github.com/larshp/abapGit/pull/3828 Unfortunately, exception `cx_oo_clif_scan_error_detail` does not exist in 702:
https://github.com/larshp/abapGit/blob/4dde63360eb928eebb600dce546374cd113b95fa/src/objects/zcl_abapgit_oo_class.clas.abap#L199-L201

- [ ] @flaiker https://github.com/larshp/abapGit/pull/3847 "Unexpected word "IMPORTING" in functional method call" in `zcl_abapgit_services_basis->run_performance_test`. Needs temp variable for `zif_abapgit_popups`.
zcl_abapgit_ui_factory=>get_popups( )->popup_perf_test_parameters(
https://github.com/larshp/abapGit/blob/dc5725b49c8e64c8dd17f012d6af28e0ad468c3b/src/ui/zcl_abapgit_services_basis.clas.abap#L96-L103

**Comment by flaiker** [comment]
Homework, huh?
