### ISSUE TITLE
UX improve pull/stage button logic

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#391]
UX of the buttons is unclear - they are both always displayed. This was done for attach/detach but for the remaining time the source of last changes is unclear.
Thought: Local + remote changes may still happen at the same time so status should be displayed more clearly, maybe track branch flow (if changes are coming from remote from newer branch). Maybe store branch history locally as a 1st step to #357

**Comment by larshp** [comment]
suggestion: do not show "Stage" button if no local objects are changed, we already have the information about changed objects in the online repo

**Comment by sbcgua** [comment]
But then attach/detach will not work - the issue with a/d is that abapGit doesn't know which changes are preferable. But maybe you're right and the solution is very simple. I'll have a look. This is more a reminder for me not to forget. :)

**Comment by larshp** [comment]
attach(offline to online repo?): delete the checksums for the local objects, then stage should appear

detach(online to offline?): does not matter, offline is handled manually

**Comment by sbcgua** [comment]
I'd say should be OK for me after 419. If will be OK for you too, let's close.

**Comment by sbcgua** [comment]
I think I'd close for now. 
This - "Maybe store branch history locally" - feature actually implemented in #407. So should be OK now. If not can be reopened with more specific requirement.
