### ISSUE TITLE
Refactoring: Use boolc instead of IF

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#3911]
Following,
https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#use-xsdbool-to-set-boolean-variables
but note that abapGit targets 702, which does not have `xsdbool`, so use `boolc` instead,

```
/src/apack/zcl_abapgit_apack_migration.clas.abap[210, 7]     - Use boolc instead of IF (use_bool_expression) [E]
/src/objects/zcl_abapgit_object_ddls.clas.abap[264, 11]      - Use boolc instead of IF (use_bool_expression) [E]
/src/objects/zcl_abapgit_object_oa2p.clas.abap[240, 7]       - Use boolc instead of IF (use_bool_expression) [E]
/src/objects/zcl_abapgit_object_sprx.clas.abap[300, 7]       - Use boolc instead of IF (use_bool_expression) [E]
/src/objects/zcl_abapgit_object_vcls.clas.abap[177, 7]       - Use boolc instead of IF (use_bool_expression) [E]
/src/objects/zcl_abapgit_object_wdcc.clas.abap[305, 7]       - Use boolc instead of IF (use_bool_expression) [E]
/src/objects/zcl_abapgit_object_xslt.clas.abap[159, 7]       - Use boolc instead of IF (use_bool_expression) [E]
/src/objects/zcl_abapgit_objects_program.clas.abap[434, 7]   - Use boolc instead of IF (use_bool_expression) [E]
/src/syntax/zcl_abapgit_syntax_highlighter.clas.abap[212, 7] - Use boolc instead of IF (use_bool_expression) [E]
/src/ui/zcl_abapgit_popups.clas.abap[940, 7]                 - Use boolc instead of IF (use_bool_expression) [E]
/src/utils/zcl_abapgit_adt_link.clas.abap[194, 11]           - Use boolc instead of IF (use_bool_expression) [E]
/src/zcl_abapgit_merge.clas.abap[379, 7]                     - Use boolc instead of IF (use_bool_expression) [E]
```

**Comment by pokrakam** [comment]
I'm not convinced this is such a great idea. IMHO `boolc` is an abomination and should NEVER be used. SAP made a big mistake that `boolc` returns a string when `abap_bool` is a char. 

Thus mistakes can easily slip in, especially with the false sense of security that comes with such a seemingly simple refactor. According to the following, pigs can fly:
``` 
    DATA(foo) = 'Blah'.
    IF boolc( foo IS INITIAL ) = abap_false.
      WRITE / foo.
    ELSE.
      WRITE / 'Pigs can fly'.
    ENDIF.
```
With xsdbool, pigs stay firmly on the ground. So I'd rather use the traditional IF for versions < 7.4 (I think ?) and only use the functional style if xsdbool is available. SAP also recommend xsdbool in the doc.

**Comment by larshp** [comment]
in all the above examples, the result of `boolc` is assigned directly to a variable, which will make the conversion happen

**Comment by pokrakam** [comment]
Agree, and if the abapLint catches bad type comparisons that would be good. I also think that`boolc` will be OK most of the time as best practice is to formulate conditions as positive. But when refactoring, someone may just refactor it to the problematic `= abap_false` to fit in with an existing code block.

Also, not everything gets linted, and I still think it's way too easy to get into a habit of using `boolc` and would rather discourage anyone from using it for conditions. It's just my opinion of course.

**Comment by larshp** [comment]
yea, `boolc` has some problems, but so far there is 96 usages of it, https://github.com/larshp/abapGit/search?q=boolc&unscoped_q=boolc, and I don't remember we have hit the conversion problem

In the ideal world we could use `xsdbool`, but we wont get there until the automatic downport is running. And I think its safe to automagically upport boolc to xsdbool, assuming there are no bad usages of boolc

So for now I think its more important to reduce the amount(lines) of code.

**Comment by pokrakam** [comment]
Idea: Since a comparison to 'abap_false' is the most problematic one, might it be worth the linter checking for this? 
`IF(.+)boolc\((.+)= abap_false\.`

**Comment by larshp** [comment]
I was thinking more of when it would make sense to use `boolc` or `xsdbool` in an IF condition?

`IF boolc( foo IS INITIAL ) = abap_false.` should be `IF foo IS NOT INITIAL.`

**Comment by pokrakam** [comment]
I also agree that a comparison to abap_true/false is kindof redundant, perhaps my example isn't the best. 

If I generate the following `pig_can_fly` method definition via quick fix then ADT defines `result` as a string and if I'm a hasty dev who doesn't check their code or I get interrupted by someone bringing cake into the office then we end up with flying pigs: 
```
  METHOD pigs_can_fly.
    result = boolc( 1 = 0 ).
  ENDMETHOD.

  METHOD run.
    IF pigs_can_fly( ) = abap_false.
      WRITE / 'Correct result'.
    ELSE.
      WRITE / 'Pigs can fly'.
    ENDIF.
  ENDMETHOD.
```
Of course this is a simple example, and abapGit is generally made up of pretty decent code. But it's just the type of thing that can creep in when refactoring.

**Comment by pokrakam** [comment]
PS. All of this is a good case for strong typing :-)

**Comment by flaiker** [comment]
I am not using the quick fixes for magic variable declarations again after getting burned by too short PACKED types and date constants being generated as decfloat16.

In my opinion just disallow boolc completely in conditions should be enough.

**Comment by pokrakam** [comment]
Yes, always check those quick fixes. They are right 80% of the time but I find they still save a bit of time when they're not. Ctrl-F1, F3 to jump to the result.
