### ISSUE TITLE
Shortdump/syntax issue with latest AG Build

### ISSUE THREAD

**Issue by habrahams** [larshp/abapGit#3916]
Hi,
I am running into a short-dump after pulling the latest version of AG.
After pulling and restarting AG:
![image](https://user-images.githubusercontent.com/16045067/93762694-60af5100-fc10-11ea-9bd3-fe90c288ada0.png)

Running AG via the ABAPGIT_FULL report and pulling again does not reset my class, I would imagine it is due to the syntax issue:
![image](https://user-images.githubusercontent.com/16045067/93762668-53926200-fc10-11ea-8192-468a545d35c6.png)

**Comment by larshp** [comment]
try deleting the class manually and pull or copy pasting it into the system

**Comment by habrahams** [comment]
Deleting the class and pulling it again resolved the issue.
Would you like me to close this issue?

**Comment by larshp** [comment]
yea, closing
