### ISSUE TITLE
Shortdump when sorting by Created At in repo overview

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#3918]
![image](https://user-images.githubusercontent.com/5270359/93780889-02db3300-fc29-11ea-9326-b4d730291b44.png)

![image](https://user-images.githubusercontent.com/5270359/93780920-0bcc0480-fc29-11ea-8485-98e70ad809e0.png)

**Comment by mbtools** [comment]
makes me wonder how many string literals representing technical names are misspelled. could be an interesting lint check.

**Comment by mbtools** [comment]
https://github.com/abaplint/abaplint/issues/1361
