### ISSUE TITLE
After Authentication To ABAP GIT private account, a Runtime Error is Raised

### ISSUE THREAD

**Issue by NailSpahija** [larshp/abapGit#3930]
With the latest Update (21.09.2020) , 

After submitting the credentials of a Personal Github account, the dumb is being raised :

![image](https://user-images.githubusercontent.com/24881973/93874033-04f9cc00-fcd3-11ea-980f-21fdc46a2b32.png)

 An exception has occurred in a class constructor. This exception is
 assigned to class 'CX_SY_CREATE_OBJECT_ERROR'.
 Since the exception was not caught in the constructor, processing was
 terminated. The reason for the exception is:
 An attempt was made to assign an object reference (class
  "ZCL_ABAPGIT_2FA_GITHUB_AUTH", view "global")
 to an interface reference (interface "ZIF_ABAPGIT_2FA_AUTHENTICATOR", view
  "ZABAPGIT_FULL"). Class "ZCL_ABAPGIT_2FA_GITHUB_AUTH" does not
 support interface "ZIF_ABAPGIT_2FA_AUTHENTICATOR" however.

**Comment by larshp** [comment]
does a global class `zcl_abapgit_2fa_github_auth` exist in your system? if so it must be deleted

the 2FA implementation will soon be deprecated by github, so its been removed from abapGit, https://github.com/larshp/abapGit/pull/3839

**Comment by NailSpahija** [comment]
I just deleted `zcl_abapgit_2fa_github_auth` and it is working well. 
Thank you!
