### ISSUE TITLE
ZCL_ABAPGIT_OBJECT has attribute MV_TEXT but constructor has parameter IV_TEXT

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#397]
```
      raise exception type zcx_abapgit_object
        exporting
          iv_text = lv_exception_text.
```

This works fine if you don't mess with the ZCX_ABAPGIT_OBJECT class. But I'm having a hard time installing abapGit in an older version and it regenerated the constructor (which cannot be manually adjusted) and now I'm stuck with an syntax error saying IV_TEXT is not a parameter of ZCX_ABAPGIT_OBJECT.

**Comment by larshp** [comment]
Hi Nuno,
Class ZCX_ABAPGIT_OBJECT is part of https://github.com/larshp/abapGit-Plugins, which provides extra serialization functionallity. The plugins are not required to run default abapGit functionality.

The "Get abapGit" link installs both abapGit and abapGit-Plugins. Just install abapGit from https://github.com/larshp/abapGit.git, or alternatively just copy http://larshp.github.io/abapGit/build/zabapgit.txt into your system, and you should be good to go with the default functionality :smile:

**Comment by larshp** [comment]
but I guess we should change the ZCX_ABAPGIT_OBJECT exception so it uses the default parameter name instead

**Comment by nununo** [comment]
Yes, I'd do that. You know how picky SAP Workbench is with exception
classes. It doesn't even allow you to edit the CONSTRUCTOR. We might as
well play by its rules :)

**Comment by larshp** [comment]
I think with ABAP in Eclipse, it is possible to change the constructor. But anyhow, lets just stick to the standard scenario in this casel

**Comment by nununo** [comment]
Don't make me envy. I can't use Eclipse in my current client. Yet!

But yes, I'd stick to the standard scenario given that this already showed that it can cause problems. Thanks!

**Comment by EduardoCopat** [comment]
> I think with ABAP in Eclipse, it is possible to change the constructor. But anyhow, lets just stick to the standard scenario in this case

You can change, but I extremely not recommend to. It can cause some bugs.

**Comment by nununo** [comment]
I agree.

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapGit-Plugins/commit/1064be90d4842b7641fa3ff89a44ae1a7226c5d2 try again

**Comment by larshp** [comment]
closing, see above
