### ISSUE TITLE
main view: current_dir

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#400]
in the main view it shows the current_dir: 

![image](https://cloud.githubusercontent.com/assets/5888506/19693046/74edc494-9ada-11e6-8e80-06ed09208482.png)

@sbcgua can we show this only when the files are browsed in folder view? what do you think?

`<td class="current_dir">/</td>`

**Comment by sbcgua** [comment]
Yeap, sounds logical. Will have a look

**Comment by sbcgua** [comment]
minor fix so pushed directly :)

**Comment by larshp** [comment]
LGTM :+1:
