### ISSUE TITLE
Repositories should be user-specific

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#401]
Hello,

Suggestion: Repositories should be user-specific.

**Reason 1: Someone else can misuse my repositories**
I am currently the only developer using abapGit in my system.
I have setup several repositories related to specific projects I'm working on.
I realized that If someone decides to run ZABAPGIT and for some reason PULLs one of my repositories... something can go broken on my code.

**Reason 2: Overcrowded**
If several people start using abapGit for their specific projects... very soon abapGit will be overcrowded with dozens of repositories. Here's another reason repositories should be customized at user-level.

If all members of a team need to use the same repository, each user should need have to configure that repository.

**Comment by larshp** [comment]
Hi Nuno,
Also had the same thoughts a while back,

**Reason 1:**
Yes, misuse is possible, but this is a consequence of SAP being a multi-user system. 
If working on a class ZCL_FOOBAR, any developer can change this class.

There is a feature to disallow pulling code, see https://github.com/larshp/abapGit/wiki/Write-protected-repository. This will make sure code can only go out of the SAP system to Git, and not from Git to SAP, perhaps this can help?

Otherwise I recommend pushing changes often to the git repository, perhaps in a branch if the development is not ready for master branch.

**Reason 2:**
Yes, the "Table of contents" list gets a bit crowded, perhaps we can change the user interface, eg. a dropdown list might work.

There must be some kind of reuse of the repositories between users, if a repository is installed to $FOOBAR, then all users will have to use the same package, as multiple object instances are not possible.

**Comment by sbcgua** [comment]
Hi All,
A comment on **reason 2**. I think the UI change is not that obvious here. 
Dropdown list itself is an inconvenient control - current "map" is more usable imho unless it is crowded indeed. In my system I have 3 lines of repos now. It's feasible though. 
Maybe option is some kind of "favorites". Favorites are displayed as now. But all repos are available in some larger list (or even dropdown).

**Comment by sbcgua** [comment]
OK, guys. Here is the preliminary concept (don't look to styling too much, they are not final).

![ezgif com-video-to-gif2](https://cloud.githubusercontent.com/assets/15635498/20458156/b679b038-aea5-11e6-8ddf-59c37451b332.gif)

1. No online/offline bars. Just favourites. Icon is available when switch to repo and maybe (!opinion needed - it looks a bit ugly for me - I'd remove) in the complete list.
2. So fav bar is initially empty. Some place holder text can be there like "Blah blah, press all to choose favs"
3. To the right there is "all" link. Maybe it will be some icon instead. Hovering will open droplist with ALL repos (fav and not favs)
4. From there you can choose any repo and switch to it. If switched to non-fav repo - fav bar displays the same (alternatively - can temporarily add displayed non-fav after all favs - not sure)
5. In drop list - click the star to toggle fav state.
6. And of course this is user specific
7. repos in the droplist are ordered acsending by name (I guess it is the best)

Potential further improvement: starring can also propose to add a tag (like in gmail). Each tag will then be a separate fav bar. This is for big number of repos which needs more structure. But I'm lazy to do that now and also I think it is not that useful for the moment. ;)

What do you think ? All opinions and suggestions are welcomed :)

**Comment by larshp** [comment]
a: if a user clones/installs a repo it should automatically be added to the favorites list

b: perhaps move the star in the dropdown to the right, so it is closer to where the dropdown is triggered

:+1:

**Comment by sbcgua** [comment]
a) good point, agree. 
b) I though about it. The droplist is actually not about favs but about complete list of repos. So the selection of repo I guess will be more frequent feature there than actual fav toggle. In one of first attempts the online icon was rightmost and it was inconvenient to choose repos. So I'd better leave repo name rightmost.
c) similar consideration: the drop list is about "all". "all" itself however does not look clear thus I was actually thinking about some "burger" icon (like in mobile apps menu) + some tooltip. This is also more compact. 
d) "Show everything": mmm. so you mean for a new user or for a user who don't care about favs it will be more convenient to have the full list ? And then switching any fav will hide all but favs ? Yeah, maybe this is better than my point 2 (with placeholder), have to simulate a bit.
"new, visible to everyone": I guess not. 1) easily accessed from "all", 2) actually it should then go through all users and add a fav - complecated

**Comment by larshp** [comment]
d: the logic could be to just store the list of which repositories to hide. This will make sure all users are notified when new repositories are installed, and then they can choose to unfavorite/hide it

**Comment by nununo** [comment]
a) agreed;

b) I don't think the star should be interactive in the "all" drop-down list. I would go there, choose a repository, and then have an enabled/disabled star next to the big repository name. Much like Google Docs does. There I'd be able to decide if that already chosen repository is a favorite.

c) I'd keep it that burger thing, I'd sort it alphabetically and I'd still show the fav stars in the list just as an extra information. This would make the dropdown list simpler to use.

d) showing everything by default is overwhelming and inconsistent with the concept of favs. I'd show it empty and maybe saying something like "favorites list still empty" and maybe with a tooltip saying "please pick a repository from the full list on the right". I much prefer the logic of favs to the logic of hidden. If abapGit is an ambitious project... soon some systems will have dozens of repositories and that would force each user to painstakingly remove all the dozens which don't concern him. I'd say most times a particular user will be focused on very few repositories.

**Comment by larshp** [comment]
d: good idea with tooltip. I'm afraid that users will try to clone already installed repositories, as the repository list is hidden under "all"/"favorites". But agree, it might be too overwhelming if it shows all repositories installed by default, if there are eg. 20 repositories

**Comment by nununo** [comment]
d: but isn't it simple to avoid duplicate clones? You simply check the git url and don't allow for duplicates.

**Comment by larshp** [comment]
d: I think it already does that, and also check on package level

another thought: if there are 20+ repositories installed, then the dropdown might become very long, perhaps create a new page for editing favorites? it would also make it searchable via CTRL+F

**Comment by sbcgua** [comment]
d) @larshp "Hide repo" logic. Mmm. So someone adds his test repo and it pops up in my pressious finetuned fav list ? Imho would be annoying :). If I want to tell someone about a new repo I'll do it directly. :) I'd keep to explicit "fav" logic.

"duplicate clones", yeah, I guess it should be clone check too. And indeed I think it there already - I stimbled upon it a couple of times.

b)  @nununo "Remove interactive stars from drop list". That's look like a very good idea to me. Simpler to implement, less clutter in UI :+1:

c) @nununo "still show the fav stars". In perspective of (b) why is it needed then ? If you have favs you immediately see them in favbar. I'd remove and keep just on/offline marker (which would then look better then in the first screenshot above ;).

>@larshp another thought: if there are 20+ repositories installed, then the dropdown might become very long, perhaps create a new page for editing favorites? it would also make it searchable via CTRL+F

:+1: Can be a [search field at the top of dd](https://silviomoreto.github.io/bootstrap-select/examples/#live-search). You type and it filters automatically. Pure JS though so I'd better do it after #374 if you don't mind :)

OK, a couple of finetuned screenshots based on discussions (colors might probably change):

Placeholder text, unstarred repo (star is grey)

![image](https://cloud.githubusercontent.com/assets/15635498/20463000/a019444c-af32-11e6-912d-5538508a4a5a.png)

Some favs + Repo list (no stars version)

![image](https://cloud.githubusercontent.com/assets/15635498/20463019/f274c450-af32-11e6-8f13-75838d971ab8.png)

What do you think ?

P.S. BTW what do you think about that on/offline icon in front of repo name (in main repo header) ? I have a feeling that it is not that useful there.

**Comment by larshp** [comment]
d: ok, yeah, real communication is better :smile: 

new page: later is okay, currently it will not be a problem

**Comment by sbcgua** [comment]
... Probably better list version. Since there is a name sorting it better be left aligned. ... Also a new icon for offline - from octicons. That HDD is not a standard one.

![image](https://cloud.githubusercontent.com/assets/15635498/20463137/f1584c92-af35-11e6-832c-f00f470cfaff.png)

**Comment by nununo** [comment]
c) @nununo "still show the fav stars". In perspective of (b) why is it needed then ? If you have favs you immediately see them in favbar. I'd remove and keep just on/offline marker (which would then look better then in the first screenshot above ;).

You’re right. No need for the fav stars there.

**Comment by sbcgua** [comment]
:rocket:

**Comment by sbcgua** [comment]
@nununo pls check the feature :) If OK, can be closed

**Comment by nununo** [comment]
OK is an understatement! It's great!! Thanks!!

**Comment by sbcgua** [comment]
Always welcome :) Thank for a nice idea :)

P.S. Closing then
