### ISSUE TITLE
visualstudio.com - Error: Compressed data doesnt match 

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#403]
Have a private repository on visualstudio.com, abapGit shows error "Error: Compressed data doesnt match "

Has anyone faced a similar issue? Will try to reproduce in public repository, plus try to find workaround.

**Comment by larshp** [comment]
decompression via `lcl_zlib` works => workaround

**Comment by larshp** [comment]
closing, will probably not look into this anytime soon, plus there is a workaround. 

Please raise a new issue or leave a comment if you experience anything similar

**Comment by tiefox** [comment]
Got same error in TFS 2017 onpremise.. not sure what the workaround is around lcl_zlib

**Comment by tiefox** [comment]
Ok, got the workaround work, will work a pull request to fix this. Can you reopen the issue ?
