### ISSUE TITLE
PROG - Caching problems

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#404]
Clicking "Refresh" after a program is updated, then abapGit does not show it as updated.

Will investigate and try to reproduce, I think it only happens on one of the SAP systems I have access to. Perhaps different system setup, or bug in SAP standard, or something else.

**Comment by larshp** [comment]
looks like this is due to bad time zone settings on the system.

However, it works for CLAS objects, as classes without `repotext` are always considered as changed, I guess this is a bug which we should fix? @sbcgua

**Comment by sbcgua** [comment]
Mmmm ... not quite sure I've understood the issue :) How to reproduce it ?

**Comment by larshp** [comment]
a: create new empty repo
b: add simple class to repo
c: set breakpoint at `SELECT SINGLE udat utime FROM repotext` in ZABAPGIT_OBJECTS
d: click "Refresh"

Nothing is found in REPOTEXT, so macro `_object_check_timestamp` always returns `rv_changed = abap_true.`

**Comment by sbcgua** [comment]
mmmm ... does not seem easy from the first glance. It just happens with text and there is no information if it was there before. What if it is deleted and thus changed ... have to think. But a bit loaded at work at the moment. 

P.S. I'm starting to be a bit pessimistic about this caching stuff. As they say the most complex problems in programming are invalidation of cache and naming of variables. ;)

**Comment by larshp** [comment]
I think it would be okay to ignore the deletion of all texts in the caching algorithm, it would not happen very often, and probably at the same time as the ABAP code is changed.

Alternatively reconsider the approach, and regenerate the XML file every time and cache the ABAP files for CLAS.

**Comment by sbcgua** [comment]
OK, did like you suggested. Indeed this logic would fail in rare cases.

> Alternatively reconsider the approach ...

If you mean that `serialize` should take care about what should or should not be serialized - I think it is a better in general. But I think it will not be easy. That means that serialize should have an access to some common cache (or own static attribute?). So serialize will also take timestamp as an input (or generate it internally) and decide which files to reserialize. Something like that. What do you think ? And also how needed is this ?

BTW another question: currently texts are serialized into main xml. Would it be a good idea to separate the texts file ? For PROG/CLAS and also for MSAG (maybe something else ) ? Potentially could be better readability from repo side. Just as an idea.

**Comment by larshp** [comment]
separate text files: I dont think so, everything should go into the main xml. 

Eg. a PROG XML consists of dynpros + text symbols + selection texts + list headings + header metadata + CUA + title texts, I dont think we should start splitting some of these into individual files.

**Comment by sbcgua** [comment]
ok, just asked. 
What do you think about caching questions ?

**Comment by larshp** [comment]
I think https://github.com/sbcgua/abapGit/commit/16ba35664cb69ad20144bcd9b0322f336fa5f492 is okay for now, redesigning caching will require some hard work

**Comment by sbcgua** [comment]
Closing then :)
