### ISSUE TITLE
SAP TechEd Barcelona 2016, November 8 to 10

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#408]
Hi All,
If you are at SAP TechEd Barcelona next week, be sure to check out my session about abapGit: 

https://sessioncatalog.sapevents.com/go/agendabuilder.sessions/?l=133&sid=37856_464065&locale=en_US

I will add a link to the slides after the session.

**Comment by sbcgua** [comment]
:+1:
Good luck with the speech ! Abap needs some fresh breeze ! :)

**Comment by larshp** [comment]
Slides: https://larshp.github.com/teched-2016-emea/

**Comment by sbcgua** [comment]
How did it go ? =)

**Comment by larshp** [comment]
very good, lots of photos on twitter

**Comment by gregorwolf** [comment]
Check out the Twitter timeline: https://twitter.com/search?f=tweets&vertical=default&q=%23abapGit&src=typd
