### ISSUE TITLE
Refactor commit author regex 

### ISSUE THREAD

**Issue by Sirius-A** [larshp/abapGit#410]
PR #368 fixed an issue in the branch overview screen, which caused the program to crash, if there is an e-mail address as author in the commit history.

I found another occurrence of the regex, wich causes the crash. 
My suggestion is to unify the two and move it to the [definitions](https://github.com/larshp/abapGit/blob/master/src/zabapgit_definitions.prog.abap) include.

Here are the two occurrences:
https://github.com/larshp/abapGit/blob/master/src/zabapgit_page_branch_overview.prog.abap#L196
https://github.com/larshp/abapGit/blob/master/src/zabapgit_page_merge.prog.abap#L286

I'll create a PR when I get the time (prob this week).

Best regards
Fabio

**Comment by larshp** [comment]
:+1: sounds good to me :smile:
