### ISSUE TITLE
Updated Installing abap-git page

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#411]
Hello,

Since it is not possible to fork a repository wiki and I do not have wiki permissions here. Could you please take into consideration this possible update I wrote to the [Installing-abapGit](https://github.com/larshp/abapGit/wiki/Installing-abapGit) page?

I wrote them while installing the project. I added a chrome step-by-step and more detailed STRUST instructions.

First changes, then source:

## ABAP Report ##
Copy the [ABAP code](http://larshp.github.io/abapGit/build/zabapgit.txt) into new report via SE38 or SE80. To update abapGit to a newer version, replace the code in the report with the most recent.

In case of activation errors on 702 see https://github.com/larshp/abapGit/wiki/702-Manual-Changes

To use the online feature, SSL must be setup. Offline projects will work behind firewalls and without SSL.

##### Option A - Chrome #####

1. On chrome, go to https://github.com
2. Click on the locker near the address bar, then click on "Details"
3. The developer tools will open at the Security tab. Click on "View certificate"
4. Go to the "Details" tab and click on "Copy to file..." to export to a .CER file
5. Open the "Certification path" tab and navigate to the parent node at the tree, do this until the root

##### Option B - Firefox #####
1. Use Firefox to go to https://github.com
2. Click on the lock icon and then "More Information ..." and there "View Certificate"
3. Switch to the Details Tab and choose the first certificate of the tree and click Export
4. Do the same for the next certificate in the tree

##### Option C #####
1. Goto github, find the certificate that it is using
2. Download certificate from https://www.digicert.com/digicert-root-certificates.htm

##### Then continue here #####
1. Install the certificates in STRUST transaction under "SSL System Client SSL Client (Anonymous)"
* Click on the Change button
* In the third box, Certificate, click on the bottom-left button "Import certificate" and upload all the downloaded certificates
2. If NetWeaver Release 7.01 or lower
* Restart ICM using transaction SMICM

Report [ZABAPGIT_TEST_SSL](https://github.com/larshp/abapGit/wiki/ZABAPGIT_TEST_SSL) can be used to verify that the connection works.

Also see blogs
* http://scn.sap.com/people/jens.gleichmann/blog/2008/10/31/calling-webservices-from-abap-via-httpsssl-with-pfx-certificates
* http://scn.sap.com/people/thomas.jung/blog/2004/11/17/bsp-a-developers-journal-part-xiv--consuming-webservices-with-abap

The certificate list should end up looking something like this:
![STRUST!](img/strust.png)

## Done ##
Run report

Source:
```

## ABAP Report ##
Copy the [ABAP code](http://larshp.github.io/abapGit/build/zabapgit.txt) into new report via SE38 or SE80. To update abapGit to a newer version, replace the code in the report with the most recent.

In case of activation errors on 702 see https://github.com/larshp/abapGit/wiki/702-Manual-Changes

To use the online feature, SSL must be setup. Offline projects will work behind firewalls and without SSL.

## STRUST/SSL setup(online projects only) ##

##### Option A - Chrome #####

1. On chrome, go to https://github.com
2. Click on the locker near the address bar, then click on "Details"
3. The developer tools will open at the Security tab. Click on "View certificate"
4. Go to the "Details" tab and click on "Copy to file..." to export to a .CER file
5. Open the "Certification path" tab and navigate to the parent node at the tree, do this until the root


##### Option B - Firefox #####
1. Use Firefox to go to https://github.com
2. Click on the lock icon and then "More Information ..." and there "View Certificate"
3. Switch to the Details Tab and choose the first certificate of the tree and click Export
4. Do the same for the next certificate in the tree

##### Option C #####
1. Goto github, find the certificate that it is using
2. Download certificate from https://www.digicert.com/digicert-root-certificates.htm

##### Then continue here #####
1. Install the certificates in STRUST transaction under "SSL System Client SSL Client (Anonymous)"
* Click on the Change button
* In the third box, Certificate, click on the bottom-left button "Import certificate" and upload all the downloaded certificates
2. If NetWeaver Release 7.01 or lower
* Restart ICM using transaction SMICM

Report [ZABAPGIT_TEST_SSL](https://github.com/larshp/abapGit/wiki/ZABAPGIT_TEST_SSL) can be used to verify that the connection works.

Also see blogs
* http://scn.sap.com/people/jens.gleichmann/blog/2008/10/31/calling-webservices-from-abap-via-httpsssl-with-pfx-certificates
* http://scn.sap.com/people/thomas.jung/blog/2004/11/17/bsp-a-developers-journal-part-xiv--consuming-webservices-with-abap

The certificate list should end up looking something like this:
![STRUST!](img/strust.png)

## Done ##
Run report
```

**Comment by larshp** [comment]
:+1: thanks, I've updated the wiki page
