### ISSUE TITLE
HTTP failure on systems using a Proxy

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#412]
Hello,

When running the program `ZABAPGIT_TEST_SSL` to test my connection, I was receiving a HTTP Communication Failure. My SAP system/network has a proxy.

Checking the `cl_http_client`, I noticed it takes as an optional parameter the proxy URL and Proxy Port. I added it and it worked:

```abap
  cl_http_client=>create_by_url(
    EXPORTING
      url           = lv_url
      ssl_id        = 'ANONYM'
      proxy_host    = 'proxy' "proxy URL
      proxy_service = '8080'  "proxy port
    IMPORTING
      client        = li_client ).
```

Being so, I also needed to modify this in the ZABAP_GIT. Specifically at the `lcl_git_transport=>branch_list` method.

I believe we could provide this values as a setting/configuration, similar to what is offered with the Name and Email when commiting (i.e., save in the persistence). What do you think?

**Comment by larshp** [comment]
Agree, good idea

**Comment by larshp** [comment]
closing issue, above PR merged to master
