### ISSUE TITLE
Local checksums strategy

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#416]
follows from #407. Decided to open a separate discussion because the topic is controversial.

To summarize: 
- I added per-file checksums to local DB cache. 
- So abapGit can compare checksum to remote sha1 and local sha1 independently and see what was changed and where. 
- Now checksums contain both per-file sha1 and whole object sha1
- push/pull can be partial ! so checksumming all local files on update does not work. Only actually pushed/pulled files must be updated

Questions ( @larshp ):
1) Do we need whole object checksums at all ? What value do they bring ? This is tricky to update them in case of partial push (actually no possible). I'd suggest dropping them
2) How this change should be delivered to current users? What I mean. Let's say a user have a repo in a dirty state. Force calculating checksums will save actual current state so the local changes will be ignored in status display and can lead to confusion. I'm a bit out of ideas here. Somehow the checksum update must happen first just for clean repo.

**Comment by larshp** [comment]
1: no, I do not think so, just drop it :smile: 

2: hmm, I think we should avoid making a lot of code to handle this upgrade, and just take the risk that some users might run into some issues. I'd say we prioritize moving ahead to a better solution, over fixing every scenario for all users.

**Comment by sbcgua** [comment]
1: 👍 
2: Generally agree. I'll think how to mitigate the issues in minimem of code ... maybe some warning message ...

BTW: I think i could be a good idea to publish some release notes/ changelog ... maybe to announce issues like this, definitely to announce new features, another option is to actually open this change log on the first run of abapGit. E.g. store "last shown announcement" version and if current abapGit is higher the download change log and show it to user. Just thoughts ...

**Comment by larshp** [comment]
release notes: probably a good idea, but it is just more work, which means less code :wink: it should be first run after upgrade, per user?

**Comment by sbcgua** [comment]
But more clear for users ! Which is good ! :) UX is important :P
Well, I'll write some release notes just as MD file then. Automatic display of changes ... maybe ... somewhen later (for sure after external assets idea).

For the local check some refresh I've put the warning below. And maybe some autorun if no file checksums found for repo. I guess the logic (read below) should be OK - unsynced repo with remote and local updates at the same time should be rare enough.
```
'This will rebuild and overwrite local file checksums.'
' The logic: if local and remote file differs then:'
' if remote branch is ahead then assume changes are remote,'
' else (branches are equal) assume changes are local.'
' This will lead to incorrect state for files changed on both sides.'
' Please make sure you don't have ones like that.'
```

**Comment by sbcgua** [comment]
Closing. changes wil be commited as a part of 407
