### ISSUE TITLE
ZABAPGIT_TEST_SSL update version

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#417]
Hi, 

I updated the ZABAPGIT_TEST_SSL so that you can test with a proxy. I also updated it to have a more detail error description. Could you please update it in the wiki? (Or, maybe, being greedy, give me access :-) ).

```abap
REPORT zabapgit_test_ssl.

* See https://github.com/larshp/abapGit/

PARAMETERS: p_url    TYPE swc_value DEFAULT 'https://github.com',
            p_proxy  TYPE string,
            p_pxport TYPE string.

START-OF-SELECTION.
  PERFORM run.

FORM run.

  DATA: lv_code          TYPE i,
        lv_url           TYPE string,
        li_client        TYPE REF TO if_http_client,
        lv_error_message TYPE string.

  lv_url = p_url.
  cl_http_client=>create_by_url(
    EXPORTING
      url           = lv_url
      ssl_id        = 'ANONYM'
      proxy_host    = p_proxy
      proxy_service = p_pxport
    IMPORTING
      client        = li_client ).

  li_client->send( ).
  li_client->receive(
    EXCEPTIONS
      http_communication_failure = 1
      http_invalid_state         = 2
      http_processing_failed     = 3
      OTHERS                     = 4
  ).

  IF sy-subrc <> 0.
    WRITE: / 'Error Number', sy-subrc.
    MESSAGE ID sy-msgid TYPE sy-msgty NUMBER sy-msgno WITH sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4.
    li_client->get_last_error(
      IMPORTING
        message        = lv_error_message
    ).
    WRITE: / `Error message: ` && lv_error_message.
    WRITE: / 'Also check transaction SMICM -> Goto -> Trace File -> Display End'.
    RETURN.
  ENDIF.

  li_client->response->get_status(
      IMPORTING
        code = lv_code ).
  IF lv_code = 200.
    WRITE: / 'Success, it works'.
  ELSE.
    WRITE: / 'Error', lv_code.
  ENDIF.

ENDFORM.
```

**Comment by larshp** [comment]
hi, I've added you as a collaborator, welcome to the abapGit project :smile: 

you can now also commit directly to master, but please try to make pull requests, also see https://github.com/larshp/abapGit/blob/master/CONTRIBUTING.md

thanks

**Comment by sbcgua** [comment]
BTW wiki is accessible as a separate repository - https://github.com/larshp/abapGit.wiki.git
I'm not sure if it is pull-requestable - never tried - but I guess it should be

**Comment by larshp** [comment]
the wiki does not allow for pull requests and editing is limited to collaborators

**Comment by larshp** [comment]
:+1: 

https://github.com/larshp/abapGit/wiki/ZABAPGIT_TEST_SSL/_compare/cb321b5%5E...cb321b5

**Comment by EduardoCopat** [comment]
Hi, @larshp, thanks! Sure, I will keep the github pull request flow.

And yes, @sbcgua , unfortunately you can't create pull requests for wiki repositories.

**Comment by sbcgua** [comment]
>  pull requests for wiki repositories.

Yeap, well, good to know anyway :)
