### ISSUE TITLE
Compile warnings (minor)

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#418]
@larshp 
Just a minor question
The compiler always show 4 warnings

![image](https://cloud.githubusercontent.com/assets/15635498/20236680/a3397d3c-a8c4-11e6-843f-b161619fc06b.png)

Is it OK to remove those ##warn_ok and ##enh_ok ? And suppress the first one ? Or is it just happening on my system ?

**Comment by larshp** [comment]
on higher versions the ##WARN_OK pragma is known, and the statement will create a warning in code inspector, I added the pragma to get rid of the error in code inspector

so, yeah, hmm

**Comment by sbcgua** [comment]
OK, no prob. Can live with it. Closing then.
