### ISSUE TITLE
diff page - color changes 

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#420]
Old version:
![old](https://cloud.githubusercontent.com/assets/5888506/20296373/c6a33b4e-ab0a-11e6-8992-19786352d203.png)

New version:
![new](https://cloud.githubusercontent.com/assets/5888506/20296380/ca6940f2-ab0a-11e6-891e-17a50ef41e96.png)

UPD: from #419

**Comment by sbcgua** [comment]
Studying this one. 

Just by the way: What do you think about unified view ?

I mean twosided 

![image](https://cloud.githubusercontent.com/assets/15635498/20442290/ce416f42-add0-11e6-8513-d3172207b09b.png)

vs (unified)

![image](https://cloud.githubusercontent.com/assets/15635498/20442274/c1732166-add0-11e6-9393-0056d08953de.png)

For me personally it looks better. Also solves the issue of table width. Just an opinion

**Comment by larshp** [comment]
I like the twosided, but it is a matter of taste, the perfect solution would be to implement both(like Github)

![image](https://cloud.githubusercontent.com/assets/5888506/20442687/ede67a38-adc9-11e6-8146-27f700b25c9d.png)

and store the selection as user setting.

Table width: if the code is max 72 characters the twosided table width is okay :smiling_imp:

**Comment by sbcgua** [comment]
Mmmm. Is there as issue ? Just did 2 tests. Add/deleted/changed line locally, check how it looks in AG, commit, check hot it looks in github. Then vice versa (which is potentially incorrect)

![image](https://cloud.githubusercontent.com/assets/15635498/20442693/54ea0300-add2-11e6-86de-74016464a75e.png)

Looks similar (suprizingly for me, I was sure github diffs a bit differently).

As mentioned in #419 now color logic is to reversed is change comes from remote ... which I guess logical. Seems like there is some space for improvement but I cannot clearly see it for the moment. :)

**Comment by sbcgua** [comment]
> the perfect solution would be to implement both(like Github)

Hmmm ... I also thought about this option ... maybe I'll do.

> Table width: if the code is max 72 characters the twosided table width is okay :smiling_imp:

I knew you'd say it ;)

**Comment by larshp** [comment]
what triggered this issue was the green "+2" and then it showed the 2 deleted lines with red. I would expect it to correspond, if the top says 2 green, then I expect 2 green lines in the diff,

![image](https://cloud.githubusercontent.com/assets/5888506/20442859/a73f22be-adca-11e6-83f6-0569c5123217.png)

**Comment by sbcgua** [comment]
Ah ! Hmm ! Good point. That should be inversed either ... I'll fix

**Comment by sbcgua** [comment]
Just in case. In case of MM (changes from both sides), does all yellow seems logical ? (currently it is the logic, as the most unambguous, but I don't like it a lot)

**Comment by larshp** [comment]
MM: yeah, lets try it

**Comment by sbcgua** [comment]
OK, seems like OK now, PRing
There are 2 commits, first is changing the names in lcl_diff - I though that more abstract "new/old" were better terms there instead of "local/remote" - less confusing. Especially for the "unified" mode.

Regarding the unified mode - I'll create a new issue, will do somewhen in future.

**Comment by sbcgua** [comment]
Closing this one then
