### ISSUE TITLE
Support for Core Data Services

### ISSUE THREAD

**Issue by simontb** [larshp/abapGit#425]
It would be great if CDS (I currently would need Data Definitions, but maybe Access Control could be useful, too) will be supported by abapGit in the future.

Currently I get the following error:
`Object type ignored, not supported: DDLS - ZST_CDS_FLIGHTS`
`Object type ignored, not supported: STOB - ZST_CDS_FLIGHTS`

**Comment by larshp** [comment]
Hi,
I've added DDLS and STOB in the overview page: https://github.com/larshp/abapGit/wiki/Supported-object-types so it is easy to find this issue.

I guess it will be supported sometime in the future, just need to find the API to read and save the objects :smile:

**Comment by larshp** [comment]
as always, pull requests welcome :smile:

**Comment by larshp** [comment]
reports RUTDDLSSHOW + RUTDDLSSHOW2

**Comment by simontb** [comment]
The `lo_dd_ddl_handler` can also be used to write a CDS source into the system.

`lo_ddl_handler->if_wb_ddl_handler~save`
`lo_ddl_handler->if_wb_ddl_handler~write_tadir`
`lo_ddl_handler->if_wb_ddl_handler~activate`

**Comment by larshp** [comment]
feature branch created: https://github.com/larshp/abapGit/tree/issue_425

**Comment by larshp** [comment]
okay, the feature can now be tested via the code in branch https://github.com/larshp/abapGit/tree/issue_425

file extension is `asddls`, the same as used by ABAP in Eclipse

todo: downport, the code should be possible to activate on 702, so the method calls needs to be replaced with dynamic calls

**Comment by larshp** [comment]
@simontb merged, try again

**Comment by simontb** [comment]
Just installed the latest version on my system and it works. I was able to commit CDS views to a git repository.

**Comment by larshp** [comment]
cool, closing issue, just open a new if you run into problems or have any questions
