### ISSUE TITLE
Import package from ZIP dumps

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#427]
Import ZIP does not generate SHA1 and so dumps in `status_calculate` on assertion.
Not sure if the assert should be removed or import shoud generate sha1 normally

**Comment by larshp** [comment]
try generating SHA1 normally, I think we can use it in the future for offline projects

**Comment by larshp** [comment]
I've added the calculation of SHA1, so it does not dump anymore, however there are more issues see #432 

closing this issue
