### ISSUE TITLE
staging screen - show changed by

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#429]
in the staging screen is it possible to show the user who last changed the object?

changed by is implemented in many serialization classes via method `METHOD lif_object~changed_by.`

perhaps also show when the object was changed

**Comment by EduardoCopat** [comment]
Would add this have an impact on performance? I ask because every `changed_by` call would be a hit on the database.

@sbcgua Thoughts on this 😄 ?

**Comment by larshp** [comment]
performance impact: yes, hmm

**Comment by sbcgua** [comment]
I didn't look much into the topic, but I guess it can be cached. 'local_status' collects this info anyway into`mt_cache`. :)
