### ISSUE TITLE
Problem with function group: function already exists

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#430]
Hello,

I started getting a strange error when transporting simple function groups (not maintenance views):

![image](https://cloud.githubusercontent.com/assets/532049/20343957/f39d8a8c-abf0-11e6-9eb1-38bccaf7bd59.png)

And when I click the "Display" button it takes me to an include which I had never seen before:

![image](https://cloud.githubusercontent.com/assets/532049/20343984/0fea1282-abf1-11e6-9693-625ee5f663a8.png)

This happens even if I first delete the function group and make sure the offending function module doesn't exit when I do the pull.

Any ideas?

Thanks,
Nuno

**Comment by larshp** [comment]
can you help reproducing the issue with a public repository? and please provide steps to reproduce.

**Comment by larshp** [comment]
@nununo can you try again, I think I found the bug

Some function module files did not contain the correct source code for the function module.
Eg. file for function module ZABC, contained the code for function module ZQWERTY

**Comment by nununo** [comment]
Perfect! ;)

I deleted the function group which I had had to create manually, did a RESET LOCAL and now everything was created smoothly.

Thanks!

**Comment by larshp** [comment]
:+1: one down
