### ISSUE TITLE
Method descriptions not being copied

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#431]
Hello,

I just realized that the method descriptions are not being copied.

Here's the original system:
![image](https://cloud.githubusercontent.com/assets/532049/20350452/4bc1923a-ac0f-11e6-985d-3446e27e82a8.png)

And here's the target system:
![image](https://cloud.githubusercontent.com/assets/532049/20350474/5e838f5e-ac0f-11e6-8a44-d3ef4a3ff2e4.png)

Any idea why?

The surprising thing is that it took me so long to notice this!!

Cheers,
Nuno

**Comment by larshp** [comment]
heh, yeah, I have reproduced the error

need to implement it sometime

**Comment by nununo** [comment]
Ah! For a moment I thought I was crazy. Glad you get it too :)

**Comment by larshp** [comment]
I do not use the method descriptions, so I've also never noticed :smile:

**Comment by EduardoCopat** [comment]
@nununo Can you please retest this? Fixed with #480

**Comment by nununo** [comment]
Hello, @EduardoCopat, I finally managed to test it and it is now working fine. Thanks!!
