### ISSUE TITLE
Reimporting from ZIP doesn't work

### ISSUE THREAD

**Issue by corinzio** [larshp/abapGit#432]
I've generated manually the SHA1 from zip as for bug #427.
The first ZIP import works fine but if i made a change in a report and i try to reset the modification made by reimporting the ZIP the report ask for overwrite local object but it doesn't do really nothing.

The same thing happen if i locally delete a report and the i try to reimport it from exported ZIP

**Comment by larshp** [comment]
Hi,
Thanks for the bug report :smile: Yes, we currently have some trouble with the SHA1/zip setup, will look into it when time allows.

If it is something that you need to work right now, I recommend installing one of the older builds:
https://github.com/larshp/abapGit/tree/gh-pages/build

eg.
https://github.com/larshp/abapGit/blob/gh-pages/build/zabapgit2016-11-02-08-51-40.txt
should work

**Comment by sbcgua** [comment]
Seems like a lot of bugs after the change :((
I'll try to have a look tomorrow, currently in a business trip.

**Comment by larshp** [comment]
it was a big change, so large risk. I have some time today, so I'll see if I can fix a few more :smile:

**Comment by corinzio** [comment]
To fix the problem #427 i've made this modification:
[zabapgit.txt](https://github.com/larshp/abapGit/files/594865/zabapgit.txt)

with this in BUILD_EXISTING method of lcl_file_status 
IS_REMOTE-SHA1 and LS_FILE_SIG-SHA1 are equals for unchanged files IS_LOCAL-FILE-SHA1 is different.

Hope it can help.

**Comment by larshp** [comment]
@corinzio can you try again with latest abapGit version? I've fixed the dump, and tested both scenarios, seems like it works now

**Comment by corinzio** [comment]
Yes, the first tests i have made are successful. It seems to work fine now

**Comment by larshp** [comment]
just open a new issue if you find anything strange/interesting/or have any questions :smile:
