### ISSUE TITLE
Unit tests rely on confirming a pop-up

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#433]
Hi, 

## Problem

whenever you run unit tests, you need to confirm that you are not on a customer-production system:

```abap
CLASS ltcl_dangerous IMPLEMENTATION.

  METHOD class_setup.

    DATA: lv_text   TYPE c LENGTH 100,
          lv_answer TYPE c LENGTH 1.


    lv_text = 'Objects will be created and deleted, do not run in customer system!'.

    CALL FUNCTION 'POPUP_TO_CONFIRM'
      EXPORTING
        titlebar              = 'Warning'
        text_question         = lv_text
        text_button_1         = 'Run'
        text_button_2         = 'Cancel'
        default_button        = '2'
        display_cancel_button = abap_false
      IMPORTING
        answer                = lv_answer.
```

Everytime I run them, I need to confirm. If I'm developing using Abap in Eclipse, it takes longer because I receive a "Screen output without connection to user" dump.

## Suggestion (which I can create the pull request):

Add a "abapGit Developer Mode" checkbox in the new "Settings" page. When flagged on, this confirmation is not needed anymore.

**Comment by larshp** [comment]
:+1: 

I typically do not have the `RISK LEVEL CRITICAL` tests enabled, so I haven't tried these tests in a while.

But it sounds like a good idea, perhaps rename "abapGit Developer Mode" to "Enable critical unit tests (LTCL_DANGEROUS)". And then I think we can remove the popup all together, and only run this test class if the checkbox is flagged

**Comment by EduardoCopat** [comment]
The final user could confuse the abapGit unit tests with their programs unit tests.

How about a settings area, something like this:

## abapGit Development Internals settings

- [ ] Enable critical unit tests (see LTCL_DANGEROUS )

**Comment by larshp** [comment]
looks good

**Comment by EduardoCopat** [comment]
Pull request #463
