### ISSUE TITLE
supported obj types @debugpage

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#436]
@larshp  Does it look reasonable to display supported obj types at debug page ? (and also serialize_text feature support) ?

**Comment by larshp** [comment]
feel free to add the object types on the debug page

however I do not think we should add serialize_text support, the unsupported texts can be seen as bugs, and I dont think we should add a list of bugs in the debug page. 

However, if needed for building serialize_text, you can add a page and show it via the "page playground"? In a separate include that is not part of the abapGit repository, eg `INCLUDE zabapgit_gui_pages_userexit IF FOUND.`

**Comment by sbcgua** [comment]
> I dont think we should add a list of bugs in the debug page

That's why it called debug page ! :) But not insisting anyway. I actually though it can be useful to update wiki page.

**Comment by larshp** [comment]
anyhow `serialize_text` is not part of the `lif_object`, so it is a private/protected method, so it cannot be determined if it is implemented from code.

Feel free to create a new wiki page or update the existing

**Comment by sbcgua** [comment]
One issue: if plugins installed then all objects are supported.
I call `lcl_objects=>is_supported( )`, it cannot create local class and then falls back to bridge. Bridge has `gt_objtype_map` which actually contains 1200 object types. Is it correct ? Looks like a bug.

Besides: if it ok if I add an optional param to `is_supported` to force skip plugins ?

**Comment by larshp** [comment]
1200 might be correct, there are a lot of object types, and I also think these are supported(or partially supported) by plugins

just add a is_supported, or alternatively uninstall the plugins in your systems

(OFF TOPIC: been thinking of moving the "get abapgit" option to "Advanced", and perhaps add a checkbox if user wants plugins?)

**Comment by sbcgua** [comment]
> just add a is_supported

Hmm, the idea was to list those which are natively supported, now the list is quite unreadable ...

![image](https://cloud.githubusercontent.com/assets/15635498/20438585/e2ee5258-adc0-11e6-8581-0f9f18d47afa.png)

Get AG to Advanced: Yes, why not. Actually I'm not sure I understand the logic of this button. I have AG in $ABAPGIT package and still the button is displayed. What it suppose to get ? :) However, installing plugins from main interface is good idea.

**Comment by larshp** [comment]
the "get abapgit" button only disappears if the plugins are also installed

just add a is_supported: to force skip plugins

**Comment by sbcgua** [comment]
Closing
