### ISSUE TITLE
Block pull if any of deserialized object is opened by a user

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#437]
Probably not the most important feature but it is quite annoying when some of updated objects is locked for editing and so deserialization stops at some undefined state (not clear what has been updated and activated). Would be nice to throw an error message about that before actual deserialization.

**Comment by larshp** [comment]
could be a new method `is_locked` in `lif_objects` interface

**Comment by christianguenter2** [comment]
I created a first protoype for this feature.
https://github.com/christianguenter2/abapGit/tree/issue_437

![image](https://user-images.githubusercontent.com/17437789/41477146-b7a7e06a-70c3-11e8-87a8-47cf07bb5967.png)

I added a IS_LOCKED method to the interface ZIF_ABAPGIT_OBJECT PUBLIC
https://github.com/christianguenter2/abapGit/blob/6958a63e2b0e250186b9f04f658107dff628286c/src/objects/zif_abapgit_object.intf.abap#L16-L17

```
    is_locked
      RETURNING VALUE(rv_is_locked) type abap_bool,
```

and a check method in ZCL_ABAPGIT_OBJECTS->DESERIALIZE
https://github.com/christianguenter2/abapGit/blob/6958a63e2b0e250186b9f04f658107dff628286c/src/zcl_abapgit_objects.clas.abap#L475-L476

```
    check_objects_locked( iv_language = io_repo->get_dot_abapgit( )->get_master_language( )
                          it_results  = lt_results ).
```

https://github.com/christianguenter2/abapGit/blob/6958a63e2b0e250186b9f04f658107dff628286c/src/zcl_abapgit_objects.clas.abap#L253-L273

```
METHOD check_objects_locked.

    DATA: li_obj  TYPE REF TO zif_abapgit_object,
          ls_item TYPE zif_abapgit_definitions=>ty_item.
    FIELD-SYMBOLS: <ls_result> TYPE zif_abapgit_definitions=>ty_result.

    LOOP AT it_results ASSIGNING <ls_result>.

      MOVE-CORRESPONDING <ls_result> TO ls_item.

      li_obj = create_object( is_item     = ls_item
                              iv_language = iv_language ).

      IF li_obj->is_locked( ) = abap_true.
        zcx_abapgit_exception=>raise( |Object { ls_item-obj_type } { ls_item-obj_name } |
                                   && |is locked. Deserialization not possible.| ).
      ENDIF.

    ENDLOOP.

  ENDMETHOD.
```

This is a sample implementation of IS_LOCKED for CLAS.
https://github.com/christianguenter2/abapGit/blob/6958a63e2b0e250186b9f04f658107dff628286c/src/objects/zcl_abapgit_object_clas_old.clas.abap#L412-L433

```
  METHOD zif_abapgit_object~is_locked.

    DATA: lv_clsname TYPE seoclsenq-clsname.

    lv_clsname = ms_item-obj_name.
    OVERLAY lv_clsname WITH '=============================='.

    CALL FUNCTION 'ENQUEUE_ESEOCLASS'
      EXPORTING
        clsname        = lv_clsname
      EXCEPTIONS
        foreign_lock   = 1
        system_failure = 2
        OTHERS         = 3.

    rv_is_locked = boolc( sy-subrc <> 0 ).

    CALL FUNCTION 'DEQUEUE_ESEOCLASS'
      EXPORTING
        clsname = lv_clsname.

  ENDMETHOD.
```

Other objects have dummy implementation. Which someday have to be implemented.

```
  METHOD zif_abapgit_object~is_locked.

    rv_is_locked = abap_false.

  ENDMETHOD.
```

**Comment by larshp** [comment]
looks good

consider using funciton module ENQUEUE_READ, never used it before, but this is the right scenario to use it

**Comment by christianguenter2** [comment]
Todo: implement is_locked for other objects.

https://github.com/larshp/abapGit/blob/b6894a5e67e6a6f635e9201f4198d020e460aecf/src/objects/zcl_abapgit_object_auth.clas.abap#L131-L135

**Comment by larshp** [comment]
I think we should close this issue, the basics have been implemented, just some object serializers missing the check, but it will always be work in progress

**Comment by christianguenter2** [comment]
Agree.
