### ISSUE TITLE
UI syntax highlighting at page diff

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#443]
Following point 4 at #346 
Another my collegue decided to take part :)

**Comment by larshp** [comment]
please add a brief description of the proposed solution here in this issue, will you try to work towards a ABAP only solution?

**Comment by sbcgua** [comment]
Yes, it will be abap solution. A class that will be called somewhere in `diff->render_line` per line. Will wrap major keywords, comments and text (all kinds: ',`,|,{} ) in color styles spans. Seems like quite fast but it is not finished yet.
That's the starting point. Probably we'll do for XML too later.

**Comment by sbcgua** [comment]
Some interesting info about abap regex performance. 

Seems like compilation of multiword regex ( `\b(word1|word2|...)\b` ) takes some time in abap. I did a small study. Here are the results: `Init` - is compilation of regex, `process` - match complete abapGit code (~37k lines). Time in seconds.

```
Keywords  init       process     total   
900       1,941251   1,003925    2,945176
800       1,539561   0,912489    2,452050
700       1,156716   0,782476    1,939192
600       0,826139   0,658053    1,484192
500       0,559143   0,579103    1,138246
400       0,346399   0,428340    0,774739
300       0,190116   0,332266    0,522382
200       0,079722   0,275598    0,355320
100       0,018217   0,235597    0,253814
```
![image](https://cloud.githubusercontent.com/assets/15635498/20828564/d61509c6-b880-11e6-85bc-0b0f14a95107.png)

Seems like non linear dependence. 500 words take 4 times less to init.

Some comparison.

- hash table. Match all words with `\b\w+\b` and read hashed table with keywords. **0,631974** - not bad by the way and linearly grows with code size. Initialization time is neglectable.
- `SCAN ABAP-SOURCE` - scan for tokens. No processing though so not directly comparable. Also probably cannot be applied as abapGit shows parts of code which might begin in improper place. Envious **0,033317**
- and finally ... the initial task (900 keywords) performed with JS: Init = **0.0009**, process = **0.037**. (0.9 and 37 **milliseconds** respectively). Mmm ... 😱

**Comment by sbcgua** [comment]
Closing :)
