### ISSUE TITLE
Click package to open SE80

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#450]
Hi,
It could be nice if it was possible to click the package in abapGit:

($AES in this case)
![image](https://cloud.githubusercontent.com/assets/5888506/20488807/a9c93124-b008-11e6-8d94-2729fb9d1b5d.png)

And then it would open a new window with SE80 for that package.

**Comment by sbcgua** [comment]
if 'Hi' was to me, I can do :)

**Comment by larshp** [comment]
feel free, I guess it is a small change(as always)

**Comment by sbcgua** [comment]
Commiting. But it is not 100% working how intended. 
I'm using the below code to open the package. But if I give `IN_NEW_WINDOW` then `WITH_OBJECTLIST` is ignored somehow ... don't know how to fix. Feel free to adjust.

```abap
    CALL FUNCTION 'RS_TOOL_ACCESS'
      EXPORTING
         OPERATION       = 'SHOW'
         IN_NEW_WINDOW   = 'X'
         OBJECT_NAME     = iv_package
         OBJECT_TYPE     = 'DEVC'
         WITH_OBJECTLIST = 'X'.
```

**Comment by larshp** [comment]
ok, thanks
