### ISSUE TITLE
Pull and Reset local try to overwrite local files not in the repository and fail (regression?)

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#452]
Hello,

I removed a couple of objects from system A. When I try to sync to system B these two objects show as "Local: Added new" which is ok (although the text doesn't really reflect the reality as these are not new objects but old objects which have since then been deleted from the remote system).

But when I try to pull or do a reset local I get this:
![image](https://cloud.githubusercontent.com/assets/532049/20530530/961189b0-b0cb-11e6-835d-8c94ec73333b.png)

Which is strange since, not existing in the repository, these objects should not be touched. But then it gets worse. If I say yes I get this "file not found" error:
![image](https://cloud.githubusercontent.com/assets/532049/20530696/17f7a220-b0cc-11e6-913f-88f44b94b1e6.png)

Regards,
Nuno

**Comment by larshp** [comment]
first part is similar to https://github.com/larshp/abapGit/issues/445

**Comment by larshp** [comment]
@nununo try again

**Comment by nununo** [comment]
Works fine again. And wow the new favourites is great!! Thanks guys!!

**Comment by larshp** [comment]
closing
