### ISSUE TITLE
Favorites - Icon size/mouse move

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#453]
As mentioned in the pull request, moving the mouse along the red line:

![image](https://cloud.githubusercontent.com/assets/5888506/20531582/7def6210-b0d7-11e6-9b0b-0a3d122934a9.png)

will make the dropdown disappear. The icon horizontal width is quite small, can we extend the element with blank space or do something so moving the mouse along the red line will not make the dropdown disappear?

**Comment by sbcgua** [comment]
follows #401 

Yeap, I'll fix with an invisible CSS element most probably. 
http://www.positioniseverything.net/css-dropdowns-red.html

**Comment by sbcgua** [comment]
![image](https://cloud.githubusercontent.com/assets/15635498/20561858/58c34904-b189-11e6-9c71-7de4cb366586.png)

OK, added some extension zone and some "forgiving shadow" zone. Should be fine now.
CSS is in a mess a bit, but I plan a serious refactoring after implementation of "external resources".

**Comment by sbcgua** [comment]
Closing then. :)
