### ISSUE TITLE
Change "Create package" button

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#459]
Today, the create package button is an envelope:

![image](https://cloud.githubusercontent.com/assets/2248490/20568087/88beff9c-b19b-11e6-8a41-7c6e971cc6c9.png)

Couldn't we use the folder icon?

![image](https://cloud.githubusercontent.com/assets/2248490/20568135/b92845da-b19b-11e6-9a67-1fcd2e21b2fa.png)

**Comment by larshp** [comment]
feel free, just change it :smile:
