### ISSUE TITLE
ABAP Version Requirement?

### ISSUE THREAD

**Issue by jhyland** [larshp/abapGit#46]
Hi larshp,
 
 I like the intention of abapGit although this could be explained more thoroughly in the read me ( stated goals, examples, support, etc). While attempting to test abapGit by uploading the ABAP source into a targeted development system (Software Component = 'SAP_ABA', Release = '700',  Level = '0021') I have come across many problems. The first is that type "ABAP_BOOL" is not recognized. Rather I would need to utilize type "SAP_BOOL". Also, I can not access statements which are chained. For example, "li_struct->find_from_name( depth = 0 name = lv_name )->get_value( )." statement gives the following error in the editor:  "=" expected after ")->GET_VALUE(". I can work around this by supplying helper variables but have not gone through this trouble yet. Before proceeding any further, is there a version requirement for abapGit and if so would it be worth the effort to make this backwards compatible?

 Anyways, once again, I want to point out that I am interested in the idea of abapGit as I do think there is great potential for ABAP developers to be able to share repositories for business solutions rather than re-writing a solution for each system or copying and pasting code. Thank you for the effort and work on this.

Regards,

James

**Comment by larshp** [comment]
I've tested it on 740+730, plus it compiles on 702.

There is currently no version requirement, I'd like it to work with as many versions as possible, however I don't have access to a 700 system, thats mainly the reason why it doesnt work.

If you have the time, feel free to submit a pull request with the necessary changes.

Thanks for the feedback.

**Comment by larshp** [comment]
started backporting to 701

**Comment by larshp** [comment]
looks like this wont work out due to the stuff needed from class CL_OO_SOURCE
