### ISSUE TITLE
File show/hide dropdown broken

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#460]
I think with commit https://github.com/larshp/abapGit/commit/e4b3f7343ae27faf049fcc7a1bb0927253ab7c48
the dropdown for show/hide files is broken.

Moving the mouse into the red zone hides the dropdown,

![image](https://cloud.githubusercontent.com/assets/5888506/20568320/6f8c4eb6-b19c-11e6-9a31-dde474274280.png)

**Comment by sbcgua** [comment]
Ah yes, I forgot to check this dd. 
I even know what's the reason - I added "top: 1em" css style to the dropdown. I'll have a look a bit later.
