### ISSUE TITLE
Add label to "Repositories" menu?

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#465]
Should we add a label next to the repositories menu? From an user perspective, I find it confusing that the "hamburger" icon contains the repositories.

![image](https://cloud.githubusercontent.com/assets/2248490/20630727/016c6df6-b333-11e6-8954-a0dc7c1db81d.png)

**Comment by sbcgua** [comment]
Label would be too long and take too much place. The idea is that you add favourites which you use most - you can add all repos as favs :) E.g. I have 3 lines of repos which is inconvenient so favs make a difference. 
Maybe the button can be done a bit larger e.g. like this:

![image](https://cloud.githubusercontent.com/assets/15635498/20634328/528a9e86-b358-11e6-88f6-bc88a313a246.png)

But is it really needed ? Doubts. @nununo @larshp : what do you think ?

**Comment by sbcgua** [comment]
Or like this 

![image](https://cloud.githubusercontent.com/assets/15635498/20634372/d3cd1884-b358-11e6-83af-cdbd0febb742.png)

**Comment by EduardoCopat** [comment]
@sbcgua Indeed, it could take too much space. I liked your idea to make it a small button, specially the second one. Easy of use is important!

**Comment by nununo** [comment]
I actually like the simplicity of the Hamburger. It may not be obvious... but, you open the drop-down list by default for a user who runs abapGit for the first time and still doesn't have any favorite. This way it would become obvious where to start.

**Comment by larshp** [comment]
alternatively, if the user does not have any favorites, show a "tutorial" screen showing how to use the hamburger?

**Comment by sbcgua** [comment]
Mmm. seems like no single opinion ... Ok what about a more clear text/tutorial indeed ?

![image](https://cloud.githubusercontent.com/assets/15635498/20639603/e444097a-b3d0-11e6-8aa7-c6d291082f23.png)

**Comment by larshp** [comment]
how about moving the tutorial down to the main area, and show it there, instead of a random repository? It will force the user to use the burger, instead of thinking there is only one repo installed

**Comment by sbcgua** [comment]
OK let's discuss.

1) I'm a new user, I run AG, there is not show_repo_id so AG know that it runs for the first time

- Fav bar displays a shorter text (then now) e.g. "No favs so far. Check the tutorial to find more", where "tutorial" is a link
- instead of repo - there is some long text with some tutorial on how to work with AG. Potentially downloaded from wiki (or maybe hardcoded). Of course with some JS animation and a link to youtube (joking, actually I think some introduction text is a very good idea :)

2) I switch to my first repo and work work work. If I delete current repo (or clear show_repo_id anyhow) then I get to the same (1) page. Right ?

3) What if I want to re-read the tutorial ? Where should I find the link  ? option: the "?" or "help" or "tutorial" item in the top menu (plus a link from the empty fav bar )

**Comment by larshp** [comment]
1: yes
2: yes
3: hmm, perhaps we should actually add a "Help" link in the top area, which opens the wiki in a new browser window,
![image](https://cloud.githubusercontent.com/assets/5888506/20639833/6cb17e30-b3ce-11e6-9a78-0768c3a2c8ff.png)

**Comment by sbcgua** [comment]
3) Hmm ... what about "Help" item with "Tutorial" and "Wiki" subitems ? T opens inline tutorial, W opens Wiki page externally as you suggested

**Comment by larshp** [comment]
sounds good to me

**Comment by nununo** [comment]
Sounds good to me also!

**Comment by sbcgua** [comment]
OK, will fix it then a bit later. At least the tech part - the tutorial text I don't promise ;P

**Comment by EduardoCopat** [comment]
👍 

I liked the idea of having this text in the beginning:

![image](https://cloud.githubusercontent.com/assets/2248490/20642168/2319e9d0-b408-11e6-92b7-6fb7f26b82c8.png)

I have the impression that if the User is using abapGit for the first time, it may be confusing/unnatural that you clone a repository and "nothing happens" (i.e., you need to search for your repository in the Hamburger)

**Comment by nununo** [comment]
But when you clone a repository it becomes your favorite, right? If not, I think it would make sense to be like this. You can easily remove it from your favorites later. This solves that problem.

**Comment by sbcgua** [comment]
> But when you clone a repository it becomes your favorite, right?

Yeap, it does :)

**Comment by EduardoCopat** [comment]
>> But when you clone a repository it becomes your favorite, right?

>Yeap, it does :)
>Also for new offline repo

If that is true, we can ignore this issue then. I opened because this was not happening, maybe I was doing something wrong.

**Comment by larshp** [comment]
earlier, if the cloing/activation failed, the favorite was not added. I have moved the "add" so it happens earlier,

https://github.com/larshp/abapGit/commit/968a186a85d418a8b2a0f58071df993cd0bc48d0

**Comment by sbcgua** [comment]
> earlier, if the cloing/activation failed

Strange, worked for me, I was checking that. Something has to be done to commits probably.

P.S. So ... but should we do that tutorial stuff ? :)

**Comment by larshp** [comment]
I think it could be nice to have the tutorial stuff
