### ISSUE TITLE
UI: Tutorial

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#469]
Following #454 , #465

History:
----

1) I'm a new user, I run AG, there is not show_repo_id so AG know that it runs for the first time

- Fav bar displays a shorter text (then now) e.g. "No favs so far. Check the tutorial to find more", where "tutorial" is a link
- instead of repo - there is some long text with some tutorial on how to work with AG. Potentially downloaded from wiki (or maybe hardcoded). Of course with some JS animation and a link to youtube (joking, actually I think some introduction text is a very good idea :)

2) I switch to my first repo and work work work. If I delete current repo (or clear show_repo_id anyhow) then I get to the same (1) page. Right ?

3) What if I want to re-read the tutorial ? Where should I find the link  ? option: the "?" or "help" or "tutorial" item in the top menu (plus a link from the empty fav bar ) 

... perhaps we should actually add a "Help" link in the top area, which opens the wiki in a new browser window 

... what about "Help" item with "Tutorial" and "Wiki" subitems ? T opens inline tutorial, W opens Wiki page externally as you suggested

**Comment by sbcgua** [comment]
Something like this for the moment.

![image](https://cloud.githubusercontent.com/assets/15635498/20667286/2c8365fe-b571-11e6-8dda-6cda70f97673.png)

![image](https://cloud.githubusercontent.com/assets/15635498/20667305/3c3ce47a-b571-11e6-94f2-8a542d585508.png)

**Comment by EduardoCopat** [comment]
Hi, @sbcgua, the tutorial looks cool. May I make some suggestions? Just some brainstorming:

Currently we have:

```
Repository list and favorites
•To choose a repo press  at the favorite bar.
•To add a repo as favorite click  icon at repo toolbar.

Adding and cloning repos
•To clone a remote repo (e.g. from github) click + Clone from the top menu. This will copy a remote repo to your system.
•To add a local package as a repo click + Offline from the top menu. This will track a repo which already exist in the system with abapGit. You'll be able to attach it to remote origin or just serialize as a zip file
```

Could we first present how to `add and clone repositories`? I think this is the first thing that users may do.

Also, could we rename from `To add a repo as favorite click * icon at repo toolbar` to `To favorite a repo click *  icon at repo toolbar`

**Comment by sbcgua** [comment]
@EduardoCopat fair ideas. Fixed :) will arrive with #496 
P.S. Feel free to adjust tutorial text. There is much space for improvement, I'm just too lazy to write user guides :)

**Comment by EduardoCopat** [comment]
@sbcgua I was going to do that, but first I wanted to discuss :)

**Comment by larshp** [comment]
can this issue be closed?

**Comment by sbcgua** [comment]
From my side yes, unless @EduardoCopat wants to add something to the tutorial. :) I don't plan additions for the moment.

**Comment by larshp** [comment]
closing then 😄  feel free to open an issue or PR for additional information/functionality
