### ISSUE TITLE
UI: render sequence refactoring

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#472]
Hi @larshp,

I've got one though about current rendering architecture.  Almost all pages have wrapping - header and footer. And this is repeated in each render.  Recent settings page does not call footer and so html is actually ends incorrectly. 

No blaming, I've fixed actually, just thinking how to make it more automatic. I think it would be a good idea to call header and footer implicitly. This would mean e.g. that **only** `page_super` will implement render which will call header/footer and + some common method (render_page?) which will be specific and redefined for each page. 

At the same time some pages have redirect, some have menu, some don't, etc ... So that render_page method should actually return a number of instructions that will control main renderer (show/hide menu, include script, actual html output ...). 

Or there should be some separate class - page_renderer - which will care about header/footer/mainmenu and html consistency ...

What do you think about it ? The above approaches still don't look like a lean solution for me, maybe you have better ideas ?

**Comment by larshp** [comment]
*shrug* the gui is not perfect, but we also do not create a lot of new pages

feel free to come up with a suggestion

**Comment by sbcgua** [comment]
doing some refactorings in html stuff and pages current. I'd be greatfull if there are no changes to them for a while to avoid code conflicts :))

**Comment by sbcgua** [comment]
closing then.
