### ISSUE TITLE
Error: Could not acquire lock USER [username]

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#474]
Hello,

Suddenly I started getting this error every time I tried to set a repository as favorite or switch to another repository using the burger icon:

![image](https://cloud.githubusercontent.com/assets/532049/20706654/3dcdd48e-b620-11e6-8977-090d32c16942.png)

But then it stopped happening again and now everything is working fine...

Weird.

Cheers,
Nuno

**Comment by EduardoCopat** [comment]
I also received this error a few days ago. I had a lock on the ZABAPGIT table. I went to SM12 and killed all sessions and then everything was working fine again.

**Comment by sbcgua** [comment]
seems that something is still wrong with those commits

**Comment by EduardoCopat** [comment]
May also happen when two ZABAPGITs are running concurrently

**Comment by EduardoCopat** [comment]
@nununo Have you received this error again? I couldn't reproduce it again using two abapgits session concurrently. Should we close this issue?

**Comment by larshp** [comment]
I think lets close it, open a new if the error occurs again, and provide steps to reproduce

**Comment by nununo** [comment]
Never again ;)
