### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#475]
Some unit tests are failing:

![image](https://cloud.githubusercontent.com/assets/2248490/20713561/08ff3454-b649-11e6-8b98-fb957736d682.png)

I just installed abapGit in a new system to check if things were working or not.

Also, these tests are not fully automated as they require to click on some pop-ups (i.e. create/delete/activate. I don't know if there is a background way to do this).

**Comment by larshp** [comment]
The popups are from SAP standard code, would like to deactivate them, but so far I've not figured out how to

**Comment by sbcgua** [comment]
Is `calculate_status` still has the mistake ? It passes in my copy at the moment ...

**Comment by EduardoCopat** [comment]
@larshp I will try to fix the unit tests. If that's possible, I'll look into how to deactivate this.

@sbcgua I pulled the last version and they are still breaking. Maybe I'm doing something wrong. Do you have access to other SAP system where you could install abapGit and run them?

![image](https://cloud.githubusercontent.com/assets/2248490/20829747/b56e7b88-b87d-11e6-858f-042585d684e8.png)

**Comment by larshp** [comment]
For the dangerous tests, I think the latest code/XML format has to be pushed to the test repository

**Comment by sbcgua** [comment]
@EduardoCopat no, (well, I do but cannot install it there :). Actually there were some changes to status indeed, so I'm more surprised that tests pass on my system. I'll check. Maybe I'll ask some more screenshots from your side. :)

**Comment by larshp** [comment]
fixed some of the errors in https://github.com/larshp/abapGit-Unit-Test/commit/a338940a5c9d068270e7da76ac1b094f36888c17

however it is difficult to do proper testing across versions, think we need to implement #478

**Comment by sbcgua** [comment]
@EduardoCopat OK, a closer look to the screenshot revealed that ZCLASS2 in your case have a package ZPACKAGE ... which mean they it does exist in your system. I think I'll rename the object names in UT to be more rare

**Comment by sbcgua** [comment]
@EduardoCopat pls check. Shoud be fine now

P.S. Why `ltcl_persistence_settings` is dangerous ? Can it save the current state in `class_setup` and restore in `class_teardown` ?

**Comment by EduardoCopat** [comment]
@sbcgua File status tests are working now.

It is dangerous because it creates objects in the system. Someone could run the unit test in a customer system and replace customer objects with abap unit ones. 

However, normally, customer systems are not configured by default to allow unit test running.

**Comment by sbcgua** [comment]
`class_teardown` can handle that imho :) Just as an opinion though, nothing critical.
Glad that tests worked. :)

**Comment by EduardoCopat** [comment]
Progress so far:

![image](https://cloud.githubusercontent.com/assets/2248490/20970365/8e121b12-bc8d-11e6-8bb1-c66937ea7a59.png)

SHI3 test is not working.

Also, somehow there is a bug on my system where I can't delete the Authorization SUSC ZAGT. (thinking into cleaning the TADIR directly).

P.S.: Some tests were failing to me because I accidentaly created some objects at $TMP instead of $ABAPGIT_UNIT_TEST (wrong button click...)

**Comment by larshp** [comment]
SHI3: see https://github.com/larshp/abapGit/issues/483

SUSC: not all code in abapGit handles the TADIR deletion properly, so it might be a bug in abapGit

**Comment by EduardoCopat** [comment]
SUSC:

We could use brute force to delete from TADIR, but that is not elegant. Changeing https://github.com/larshp/abapGit/blob/master/src/zabapgit_unit_test.prog.abap#L187

to
```abap
    LOOP AT lt_tadir ASSIGNING <ls_tadir>.
      "If it was not deleted correclty, use brute force
      DELETE tadir FROM <ls_tadir>.
      IF sy-subrc <> 0.
        cl_abap_unit_assert=>fail(
          msg = | 'Failed to delete { <ls_tadir>-object } { <ls_tadir>-obj_name }. Work Rollbacked' |
          quit = if_aunit_constants=>no ).
      ENDIF.
    ENDLOOP.

```

**Comment by larshp** [comment]
the SUSC serialization code should handle the deletion properly. If field `delete_tadir` is set in the serialization code, then TADIR deletion is triggered in include ZABAPGIT_OBJECTS_IMPL,

`IF li_obj->get_metadata( )-delete_tadir = abap_true.`

**Comment by EduardoCopat** [comment]
If we add the following around this line: 
https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_susc.prog.abap#L34

It is deleted:


```
  METHOD lif_object~get_metadata.
    rs_metadata = get_metadata( ).
    rs_metadata-delete_tadir = abap_true.
  ENDMETHOD.                    "lif_object~get_metadata
```

**Comment by larshp** [comment]
yes, lets do that 👍

**Comment by EduardoCopat** [comment]
Anyway, in my environment,  the tests pass if I update the abapGit-unit-test repository with 7.5 stuff.

This "dangerous->run" tests just seem to test if you can deserialize all objects in the abapGit-unit-test package... Seems like some system-level/integration-level tests, which are inherently brittle/flaky

**Comment by larshp** [comment]
yes, I misuse the unit testing framework for writing integration tests 😄 I typically find integration tests more important than unit tests, but it is another story

**Comment by EduardoCopat** [comment]
@larshp The difficult part with integration tests is that when one fails, it is hard to detect where the failure is.

It's being hard to fix them :confused:

**Comment by EduardoCopat** [comment]
Most of tests are passing. Also, dangerous tests are now cancelled, rather than fail, if they are not allowed to run. Closing this issue for now.
