### ISSUE TITLE
XML: omit INITIAL fields

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#478]
**Problem 1:** would like to decrease the file sizes

**Problem 2**: Diffs shows up in abapGit between AS versions, eg.:

![image](https://cloud.githubusercontent.com/assets/5888506/20841296/96b83acc-b8b3-11e6-8755-dba73764a38d.png)

**Solution:** in LCL_XML_OUTOUT method add, create a structure dynamically without the fields that are initial, and move the contents to this structure, after this the `CALL TRANSFORMATION id` should still work. Note that this will also be backward compatible

**Comment by larshp** [comment]
RTTS should work in 702, http://help.sap.com/abapdocu_702/en/abenrtti.htm

**Comment by nununo** [comment]
RTTS works fine in 702.

It would be great to omit the fields with default values. That's a great idea which can have the automatic consequence of removing all those irrelevant diffs appearing between different versions. I hope it works!

**Comment by larshp** [comment]
yep, fewer diffs and lower file size 😄 

Did some testing, see: https://gist.github.com/larshp/205f3be705167451113ae06f97f52c14 it works with RTTS.

However the feature is already built into CALL TRANSFORMATION, so something like the following will do the trick,

```abap
  CALL TRANSFORMATION id
    OPTIONS initial_components = 'suppress'
    SOURCE data = ls_usr02
    RESULT XML lv_xml.
```

**Comment by nununo** [comment]
Ah that's cool I didn't know that.
Looking forward to see it happening.

**Comment by larshp** [comment]
code change committed in branch https://github.com/larshp/abapGit/tree/issue478

to be used for testing purposes before creating pull request, there might be some unforeseen issues
