### ISSUE TITLE
syntax highlighting - colours

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#484]
Strings are highlighted in green, added lines are also green

suggest changing it to eg. purple(or something that is not one of red/yellow/green),

![image](https://cloud.githubusercontent.com/assets/5888506/20858852/bbc788ae-b94e-11e6-973a-d171af2922d4.png)

**Comment by sbcgua** [comment]
I'll have a look.

**Comment by larshp** [comment]
dont change the code just yet, would like to merge PR https://github.com/larshp/abapGit/pull/481 first, so we avoid a possible conflict

**Comment by sbcgua** [comment]
OK, there are also some small fixes from our side too. Will commit a bit later then.

**Comment by sbcgua** [comment]
pushed a fix to 475. But should be no conflicts with highlighter stuff

**Comment by sbcgua** [comment]
OK, got to this one ...

Well, if you don't mind I can just follow github style. It looks quite balanced

![image](https://cloud.githubusercontent.com/assets/15635498/21240357/a97cab38-c313-11e6-90ed-535f87ed114c.png)

**Comment by larshp** [comment]
closing, does not seem to be a problem anymore
