### ISSUE TITLE
CLAS + INTF: remove redundant information from XML

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#488]
Many of the fields in the XML are redundant, since it is also specified in the ABAP code.

Fields like: EXPOSURE + STATE + CLSABSTRCT + CLSFINAL

Not sure how to implement it, guess it would require parsing the ABAP code before calling function module `SEO_CLASS_CREATE_COMPLETE`

**Comment by larshp** [comment]
after https://github.com/larshp/abapGit/issues/21

**Comment by jfilak** [comment]
Why do you believe we need to parse the ABAP code?
Do you believe that a class can have the flag CLSABSTRCT but not the keyword abstract?

**Comment by larshp** [comment]
it is the serialization process, as far as I remember, the values from the XML are stored in database before the ABAP, not sure if saving the ABAP also updates the metadata in the database.

Anything is possible in SAP 😈 we just need to try it out and test it

**Comment by larshp** [comment]
closing, use #1458 instead
