### ISSUE TITLE
"Overwrite all" button

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#490]
Sometimes, when pulling a big project, I need to manually click to overwrite objects, such as the following:

![image](https://cloud.githubusercontent.com/assets/2248490/20894093/6c562542-bb14-11e6-8e05-bfc3517e8275.png)

Is there an optimal way or should we add a "override all" button?

**Comment by larshp** [comment]
What package is configured for the abapGit repository? Is it different from $ABAPGIT6?

**Comment by EduardoCopat** [comment]
So, I had my branch on $ABAPGIT6. Clicked on "Get abapGit" to replace it, using another package, $ABAPGIT7.

**Comment by larshp** [comment]
We should change it, however overwriting object in different package should not happen very often. 

In this case if you had uninstalled $ABAPGIT6 before cloning the same programs to $ABAPGIT7 it will not show the warning.

**Comment by EduardoCopat** [comment]
Yes, but that's a problem when you uninstalling abapGit itself...

**Comment by larshp** [comment]
Uninstalling abapGit works, it just dumps after having deleted itself.

Anyhow, perhaps you need to use the "Advanced" -> "Change remote" feature, it lets you change the git repository without uninstalling it

**Comment by larshp** [comment]
see #515 which might implement a solution to a similar issue

**Comment by EduardoCopat** [comment]
Fixed in #934
