### ISSUE TITLE
W3MI: remove filesize from XML

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#495]
the filesize information is redundant, as it can be derived from the file. Suggest removing/clearing the filesize, so the XML is not changed when the file(CSS in this case) is changed

see:
https://github.com/larshp/abapGit/pull/493/files#diff-4068d95236149d26803bd411091e1c68

![image](https://cloud.githubusercontent.com/assets/5888506/21078833/cbad23b6-bf7d-11e6-9bc7-9690869f2885.png)

**Comment by sbcgua** [comment]
Looks like a good idea, I'll have a look
