### ISSUE TITLE
Importing zip into offline-repo: Multiple transport pop-ups

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#497]
when importing into a zip-file a new system, the package selection popup is being displayed for each object.

**Comment by larshp** [comment]
yea, I think it depends on the object type how the transport is handled, but this is definitely something we should look into

**Comment by mrsimpson** [comment]
Might also depend on included packages. Just imported the abapgit-plugins and didn't experience the behaviour

**Comment by christian1020-94** [comment]
How can I reproduce this bug?

**Comment by mrsimpson** [comment]
Try this zip: https://github.com/mrsimpson/p2p-help-abap-client/archive/master.zip

**Comment by christian1020-94** [comment]
I'm getting an Object type AVAS not supported, because of the .avas files. I guess I should just delete them?

**Comment by mrsimpson** [comment]
Deleting them might make a difference, but I don't know. Give it a try and see whether it occurs. If not, install the abapGit plugins

**Comment by larshp** [comment]
The package selection popups are object type dependent, so the same issue should occur with online repositories.

Perhaps calling TR_TADIR_INTERFACE before the object type API call will help

**Comment by larshp** [comment]
@mrsimpson try this https://github.com/larshp/abapGit/pull/632

**Comment by larshp** [comment]
try again, implemented in https://github.com/larshp/abapGit/issues/1042

closing, please open new issue in case of bugs/questions
