### ISSUE TITLE
Unreleased transport: TADIR entry remains after uninstalling

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#498]
Once objects have been added to a transport request (non-$TMP), the transport request (particularly the transport lock) needs to be removed before the uninstallation can be performed.
Repsonse from TRINT_TADIR_DELETE:

```
Object directory entry cannot be deleted, since the object is locked
Message No. TR022

Diagnosis
The object directory entry for R3TR DTEL Z... cannot be deleted, since this object is still locked in request XXXKXXXXXX.

```

**Comment by larshp** [comment]
As far as I remember, the TADIR entry(in this case: non $TMP) is deleted when the transport is released. So need to do some testing, and replicate the logic of the standard system

**Comment by mrsimpson** [comment]
Steps to reproduce:
Create package zmessaging, clone `https://github.com/mrsimpson/sample-bopf-application.git`, branch 0_ddic
> Uninstall
=> TADIR remains

**Comment by larshp** [comment]
I think this is working as expected, try creating eg. a domain in SE11 in a transportable package and delete it again, the TADIR remains until the transport is released

**Comment by mrsimpson** [comment]
Hmmmm - too true. 
Not a bug, but a feature
