### ISSUE TITLE
folders

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#5]

**Comment by larshp** [comment]
idea:

repository contains eg. 2 folders
backend/
gui/
each folder contains abapGit serialized objects

the repository is cloned into package $FOOBAR, then abapGit will create subpackages $FOOBAR_BACKEND and $FOOBAR_GUI with superpackage $FOOBAR, transport layer and software component should be inherited from the superpackage

this will require some work to better automatically assign packages to objects, and some code to handle the folders

**Comment by larshp** [comment]
Package maintenance:
function group PB_PACKAGE
class CL_PACKAGE_FACTORY

**Comment by larshp** [comment]
Object types missing automatic package assignment:
- [ ] DOMA
- [ ] DTEL

**Comment by mrsimpson** [comment]
If there are packages and paths being used, all objects have to be supported. Also, a reuse-method should be provided to plugins.

**Comment by larshp** [comment]
Development Scribblings:

add package back to overview?

from front page: "pull" or/and "stage"

new staging page

	only show unknown or changed files/(objects?)

	new objects, changed objects
		add/stage remove/unstage

@LOCAL
add
reset

@REMOTE
ignore
rm


commit and push -> new commit page, possible to enter body text

**Comment by larshp** [comment]
todo: more work on putting objects in the correct packages when doing pull

**Comment by sbcgua** [comment]
Sorry, maybe a wrong issuet o post, but I'd say it would be nice to have an option to set a root folder for all objects in general.
E.g. /src
a) This would be useful in case of more irrelevant files in repo (docs, tests, ...) - now this would live all together in the root
b) will coexist well with release concept (abapmerge)

**Comment by larshp** [comment]
yes, I agree. Got a note in #125 regarding it, the general folder support implemented earlier today is first step on the way :smirk: 

the idea is to have the configuration in a ".abapgit.xml" file in the root directory, it could contain something like "<root_folder>src</root_folder>" which will tell ZABAPGIT to only mess with files in that folder

also planning to list files for abapGit to ignore in the .abapgit.xml file

and add master language in .abapgit.xml

and most likely a new page to edit the contents of the .abapgit.xml file

a lot of work, will probably create a new roadmap issue soon, as much of the stuff in #186 is done

**Comment by larshp** [comment]
todo: set objects to correct package when deserializing
