### ISSUE TITLE
Package- / Folder-structure deeper than one level: Content ignored on import (of zip)

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#500]
Imported the attached zip file.
Expected to find a package ZP2PH_EXPERT_FINDER_UI within ZP2PH_EXPERT_FINDER (such as in the original system). Folder structure in ZIP looks fine, but on import, it looks as follows:)
![2016-12-13 19_35_49](https://cloud.githubusercontent.com/assets/17176678/21153579/692d6d00-c16b-11e6-8f7a-0af049e511da.png)

- no third level
- third-level-to-be-package empty

[ZP2P_20161213_141403_without_view_maintenance_fugr.zip](https://github.com/larshp/abapGit/files/649791/ZP2P_20161213_141403_without_view_maintenance_fugr.zip

**Comment by larshp** [comment]
yes, I also expect it to create a third level in this case

**Comment by larshp** [comment]
issue reproduced in https://github.com/larshp/FUGR2

**Comment by mrsimpson** [comment]
retested successfully on separate branch :+1:

**Comment by larshp** [comment]
ok, will merge the PR then 😄
