### ISSUE TITLE
702 Manual changes... yet another change needed

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#502]
I just found that the latest version has more references to those things which are not available in 702. So an extra pair of lines must be commented. I think we should update the "702 Manual changes" wiki page to reflect them:

![image](https://cloud.githubusercontent.com/assets/532049/21185056/157a1720-c207-11e6-8de5-147817ea5075.png)

Thanks,
Nuno

**Comment by larshp** [comment]
yes, I think you have access to change the wiki page?

https://github.com/larshp/abapGit/wiki/702-Manual-Changes

**Comment by nununo** [comment]
Actually I was gonna doing myself but couldn't find out how to edit it :(

**Comment by nununo** [comment]
This is what I see:

![image](https://cloud.githubusercontent.com/assets/532049/21185535/f515937c-c208-11e6-911d-aefdcddd2422.png)

**Comment by larshp** [comment]
updated, I'll add you as a contributor, then you should be able to update it in the future

**Comment by nununo** [comment]
Ah! Ok thanks for the upgrade! :) Next time I can do it myself, cool!

**Comment by EduardoCopat** [comment]
Can't we have an IF statement for this type of thing? IF version > 702...

**Comment by nununo** [comment]
An IF will not be enough as these attributes don't exist in that version.
What would work is to have these lines done dynamically.
Those lines will become uglier... but they'll work in 702 without any need to adapt the code :)
Let me know if you think it's a good idea and I'll gladly do it.

**Comment by larshp** [comment]
I would like to just have one ABAP file as the distribution, not multiple.

But it is possible to do some dynamic ABAP using RTTS, feel free to submit a PR 😄

**Comment by nununo** [comment]
I wasn't suggesting multiple files. More like dynamic calls... like RTTS or dynamically assigning a structure field to a field-symbol.

I'll submit a PR soon.

**Comment by larshp** [comment]
Multiple files: I was thinking of Eduardo's suggestion, guess it involves adding a feature in abapmerge, and then it could generate 2 different files.

I'm all for doing dynamic assigns/RTTS/dynamic function module call/dynamic sort, I just dont have access to any 702 systems

**Comment by nununo** [comment]
Don't worry, I'll do it. Unfortunately I have access to a 702 system :)

**Comment by nununo** [comment]
The current version has methods mixing CHANGING and RETURNING, which is not allowed. I reviewed them and converted the RETURNING into a CHANGING
Pull request: #504

**Comment by nununo** [comment]
I guess we can close this now.
