### ISSUE TITLE
Package to zip fails with "Unsupported ENHO type CLASENH"

### ISSUE THREAD

**Issue by mydoghasworms** [larshp/abapGit#507]
When using the function to export a package to a zip file, it stops with the error message "Unsupported ENHO type CLASENH". (For other unsupported objects, you get a message that the object type is not supported).

This seems to be caused by an enhancement implementation of the type "Class Enhancement", but instead of just giving a warning and ignoring the object, the whole function fails.

**Comment by mydoghasworms** [comment]
@larshp I have made a fix to the program on our system which is based on the program from here: http://larshp.github.io/abapGit/build/zabapgit.txt
What is the correct way to submit a pull request to your project? How do you build the above program from the sources?

**Comment by larshp** [comment]
yes, it is automatically built from source, there is a bit more information in https://github.com/larshp/abapGit/blob/master/CONTRIBUTING.md

**Comment by mydoghasworms** [comment]
Just a question on your development guidelines: Is there any reason for defining many classes as FINAL? Also, you have a few separate exceptions defined, but do not define an inheritance hierarchy for exceptions. (In my fix, I removed the FINAL addition from LCX_EXCEPTION and inherited from it to introduce an exception class called LCX_UNSUPPORTED_OBJECT that inherits from it. Does this deviate from your overall strategy?)

**Comment by larshp** [comment]
FINAL: no

inheritance for exceptions: good idea

**Comment by VishnAndr** [comment]
@mydoghasworms there is a difference in messages because ENHO object type has different, let's say, subtypes. And not all of them are implemented yet. "Class enhancement" is amongst those "yet-missed" subtypes of ENHO object type.

**Comment by larshp** [comment]
I've implemented some of the class enhancement tool, see https://github.com/larshp/abapGit/pull/512

There is still room for improvement, but this is better than nothing

**Comment by larshp** [comment]
@mydoghasworms try again

**Comment by larshp** [comment]
closing, feel free to create a new issue if you still experience the same problem, or find a new
