### ISSUE TITLE
CL_ABAP_UNIT_ASSERT=>ASSERT_TRUE() and ASSERT_FALSE() don't exist in 702

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#509]
Hi there,

We have new incompatibility issues with 702. I just commented all the ASSERT_TRUE and ASSERT_FALSE lines since they're just unit tests.

But it would be great to adapt it to become a unified version again. I enjoyed it while it lasted LOL.

Cheers,
Nuno

**Comment by larshp** [comment]
our trusted 702 tester 😄 

guess 

`cl_abap_unit_assert=>assert_true( mo_spy_oo_object->mv_overwrite ).`

can be replaced with

```abap
    cl_abap_unit_assert=>assert_equals( act = mo_spy_oo_object->mv_overwrite
                                        exp = abap_true ).
```

**Comment by nununo** [comment]
I bet it can! I bet it can! I'm very busy today but I'll try to do it
tomorrow ;)

**Comment by EduardoCopat** [comment]
Sad :(, I will use assert_equals from now on then.

@larshp Idea: Is there a way to add a rule to abaplint to send a warning if assert_true/false was used? (e.g. if your project needs 7.02 compatibility)

**Comment by larshp** [comment]
abaplint: there is some functionality on ABAP keyword level, but not on API/method level, yet 😄
