### ISSUE TITLE
Deserialization - DDIC before everything else

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#511]
See issues:
https://github.com/larshp/abapGit/issues/501
https://github.com/larshp/abapGit/issues/354

Suggestion:
Deserialize all DDIC objects and activate before everything else. 
It is possible for a DDIC object to reference a class, however that does also not work currently.

Solution:
Add a way to identify that an object type is a DDIC object. Add to metadata or as new method

**Comment by nununo** [comment]
But aren't DDIC objects being activated already before everything else?

**Comment by larshp** [comment]
current setup:
1: deserialize everything
2: call ddic activation popup
3: call activation of other objects

proposao:
1: deserialize ddic
2: call ddic activation popup
3: deserialize other objects
4: call activation of other objects

**Comment by nununo** [comment]
got it.

**Comment by larshp** [comment]
closing this
