### ISSUE TITLE
Staging button not shown after moving report between dirs/packages

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#514]
After moving report ZMOVE from /foo/ to /foo/bar/ the staging button is not shown:

![image](https://cloud.githubusercontent.com/assets/5888506/21561805/17899500-ce72-11e6-8536-d848bc7f555e.png)

The old files could have been deleted while adding the new, but in this case I did not, so now it is in a inconsistent state which I would like to fix by removing the old files in a new commit.

**Comment by sbcgua** [comment]
It seems there are a pack of issues here. I've started some tests and occasionally resulted in the state when online repo contain object BOTH in package and subpackage and AG does not see it ... might have a look at it but not sure when yet.

**Comment by sbcgua** [comment]
OK, played a bit with this issue. Below are my considerations. Sorry for many letters :)

**THE CASE**
- Moved DTEL from sub to sub/more package
- Now DTEL has 2 files local (1) and remote (2) (both in status A - added)
- Push -> pushes new file (1) to remote, but other one (2) remains and Pull is active
- Then Pull actually moves the object back to sub (!!!) and leaves the file (1) in repo too.
- 'no changes' state achieved

Now, I can see 2 issues actually:

1) Identify the change of location. And push/pull **both** changes properly.

Technically can be done somewhere around `lcl_sap_package=>check`.  
Location is changed **locally** if: (branches sha1 are equal) and (for a given object there are 2 files, one of which has the same path as actual package in the system right now)  
Location is change **remotely** if: kind of opposite condition BUT ! non equal branches does not unambiguously mean that the remote is newer ! **That rises the need of keeping the commit sequence**.  
Also ! There is no mechanism for the moment to manage 'sets' of files together (like add and remove 2 files with one user click)  
So this seem to be complex task for the time being.

2) Independently: Let's say I somehow got to the wrong state. There must be a way to delete/ignore files from 'no changes' state. Ideas:  
let's say there is a button in 'Advanced' - remove files - which actually opens stage page with all existing files - you can ignore/delete them and push it.  
The button is enabled **only** for 'no-change' state. What about limiting file to a certain set ? Two options:
- don't care - we are in git, history is preserved, made mistake? => reverse the commit = no problem. Not very user friedly though
- show only files from lines with mistakes. I think it is complecated. All possible 'mistakes' are not known in fact.
So I'd say just go for the option 1. Maybe add some inplace filtering in stage page later, maybe improve indication of problematic lines both at main page and in stage page 

Ufff... I hope some one read this till the end and not bored to death :)

**Comment by sbcgua** [comment]
Smth like this (above commit, beware older ag version in that branch)

**Comment by larshp** [comment]
this is solved
