### ISSUE TITLE
dot abapgit: subpackage/folder naming strategy

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#521]
currently a main package FOO has to have subpackge named as FOO_BAR to have a folder /sub/

however in some projects FOO has subpackage BAR, which breaks the serialization

would like to have a setting in .abapgit.xml to have folder names map 1:1 to package names

Options:
- ignore subpackages
- name folders 1:1
- subpackage prefix - subpackage contains prefix of super package

IGNORE
FULL
PREFIX

**Comment by EduardoCopat** [comment]
The option "Name folders 1:1" seems to be the best option

**Comment by nununo** [comment]
And I'd definitely add a deep/shallow option (per repository) to decide whether to ignore subpackages. 
It would be of great use for my current scenarios.

**Comment by sbcgua** [comment]
Great idea + I agree with both @nununo and @EduardoCopat :)
"Name folders 1:1" seems to be a sufficient option - it alone looks enough and can be applied always.
And deep/shallow option feels then like a separate setting (IGNORE_SUBPACKAGES = yes/no), independent from naming strategy in fact.

One issue though: how to fall back to the old strategy for existing repos. I guess maybe it should be strictly defined by serializer version which can be stored in .abapgit by the way (as a root repo object).

**Comment by larshp** [comment]
Idea is to implement all 3 options(but ignore subpackages might be a different setting)

If the setting is not found in the .abapgit.xml it should fall back to the current strategy = PREFIX

Example:
ZPROJECT -> ZPROJECT_LOGIC -> ZPROJECT_LOGIC_DISCOUNT (this is the way I prefer to name subpackages)

in this case FULL(1:1) would give the following folder structure:
/zproject_logic/zproject_logic_discount

and PREFIX(current logic):
/logic/discount

But anyhow, both strategies are needed, because the PREFIX might not be possible in all cases, it will be configurable via the .abapgit.xml file

**Comment by larshp** [comment]
one concern using the FULL logic: if the user installs the repository into eg. $PROJECT, and the subpacages are eg. ZPROJECT_LOGIC as in the example above, then the subpackage should have "$" prefixed.

also for FULL when serializing the preceding "$" should be removed?

**Comment by larshp** [comment]
IGNORE would also not be needed in the .abapgit.xml file, only needed locally

**Comment by EduardoCopat** [comment]
The problem with the PREFIX approach is that it forces your program to follow the abapGit package naming. 

I tried to upload existing packages to abapGit and I couldn't because of naming.

**Comment by larshp** [comment]
yea, we need both PREFIX and FULL 😄

**Comment by smb** [comment]
I know it's generally considered bad practice - but do you have an ETA on the "FULL" implementation? (or at least an roadmap - short term / mid term / long term, I guess other things are just more important)

**Comment by larshp** [comment]
I hope to look into it this week, perhaps today, but wont promise anything.

**Comment by larshp** [comment]
Test results(to be updated):

![image](https://cloud.githubusercontent.com/assets/5888506/22943818/26e89478-f2ef-11e6-8c85-d686896fd6c9.png)

**Comment by smb** [comment]
Thats great! Thank you - will test tomorrow

**Comment by smb** [comment]
Seems to work perfectly for Z* packages - i was able to create an offline repository, export to zip and create a local repository from that zip without any issues. 

It (FULL) breaks (somehow) for slash-prefixes:
Creating an offline repository for /TEST/123 (name "TEST_123") results in a ZIP file #TEST#123_date.zip

that contains too many backslackes: \\test\test_base\\ so you can't see that level in the zip file because its shown as empty folder.

**Comment by larshp** [comment]
slash-prefixes: what is the exact setup, a package named "/TEST/123" with an object called "TEST_123"? can you add a screenshot of the objects in SE80?

**Comment by smb** [comment]
Can't access the system at the moment for screenshots

But whats interesting: when I open the file in WinRAR there is a "\test" folder - 7zip shows it as "empty" with a nested structure.

and i see - my backslashes were stripped from my previous comment, it's actually:

`\\test\test_base\\`

**Comment by larshp** [comment]
Alternatively you can describe the scenario here.

What is the package used in the repository, which subpackages does it have and which objects?

**Comment by smb** [comment]
Package is "/TEST/TOOLS" Git Repo Name is "TEST".

There are subpackages /TEST/T1 and /TEST/T2.

The resulting zip contains a "\TEST" in Root and "T2" on the second level.

When opening with 7zip its displayed as (ROOT): "" (empty folder) + ".abapgit" --> "TEST" --> "T1"
WinRAR: (ROOT): "\TEST" + ".abapgit" --> "T1"
Windows Explorer: only .abapgit - no additional folder visible.

So the \ in the folder name seems to cause issues here.

**Comment by larshp** [comment]
@smb try again, use latest code from https://github.com/larshp/abapGit/pull/624, I've added logic to handle the namespaces

**Comment by larshp** [comment]
I've merged the PR, feel free to test more, and create an issue if you run into problems

https://github.com/larshp/abapGit/pull/624

**Comment by EduardoCopat** [comment]
Should the FULL prefix logic be the default now?

**Comment by larshp** [comment]
no, PREFIX is default, as it was default in previous versions. Change to FULL by editing .abapgit.xml manually on remote, like this https://github.com/larshp/PROG/commit/77bfc69075caf79e0515d0a58c250a7fa029a354
