### ISSUE TITLE
ENHO: New methods/changes via interface enhancement

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#522]
see https://github.com/larshp/abapGit/pull/512

Create a pre-method and one regular additional method. The latter one was not serialized and thus was lost.

todo: enhancement types from interface enhancement, but I guess the method enhancements are most common

**Comment by larshp** [comment]
WIP, see branch https://github.com/larshp/abapGit/tree/issue522

**Comment by larshp** [comment]
implemented most of it, but still some things missing

**Comment by christianguenter2** [comment]
Is this still an issue? What's missing?

**Comment by larshp** [comment]
closing
