### ISSUE TITLE
Function module "exception classes" flag not being set

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#523]
Hello,

Some FM which use class exceptions were transported without the exception classes flag set. As a consequence I got syntax errors and hat to manually set the flag in each FM.

This seems to be a bug.

Regards,
Nuno

**Comment by larshp** [comment]
looks like the information is stored in ENLFDIR-EXTEN3, have not been able to find any function module to update the table, so perhaps just update it directly

**Comment by larshp** [comment]
if someone wants to do a PR I guess this would be an easy task to get started:

changes to be done in https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_fugr.prog.abap

In the serialization:
select the relevant data from ENLFDIR, add it to the XML via `io_xml->add(`

In deserialization
read the xml via `io_xml->read(` and update the database table ENLFDIR

and perform test, then open PR

**Comment by nununo** [comment]
I'd like to do it. But I think I will only be able to look into it in February. That's the go-live of the project I've been working on since last Summer and things are getting hotter and hotter even though it's now Winter :)

It would be a great way for me to start contributing with code.

Can it wait?

**Comment by larshp** [comment]
Currently I dont need it, so for me it can wait. 

But I think if someone "out there" has the time and needs the feature, still feel free to open a PR before Feburary

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit/pull/558

**Comment by larshp** [comment]
tested ok, closing
