### ISSUE TITLE
UI webfonts instead of inline base64 images

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#525]
following #346 

First tests: https://github.com/sbcgua/abapGit/commit/55e4a4051da7ab77d09c3e81043ade5c8bf72331
Seems to work quite well, even in eclipse

**Comment by larshp** [comment]
nice, hope it will be easier to make cool stuff work with the `<meta http-equiv="X-UA-Compatible" content="IE=11,10,9,8" />` trick

**Comment by sbcgua** [comment]
Works nicely. Appeared to be easy task (specially after `lcl_html=>icon` stuff)
Will PR after #526 

## How to use properly

```abap
lcl_html=>icon( iv_name  = 'alert/red' " Octicon name + CSS class for color (COLOR PALETTE section)
                iv_class = 'pad-sides' " Additional css class if needed (usually paddings)
                iv_hint  = 'OMG it is error' ) ). " Icon tooltip (title attribute)
```

PS: `iv_class` should be avoided. I'll probably remove it later - layout stuff should preferably be handled out of icon

**Comment by sbcgua** [comment]
Ah yes, the source. The octicons are taken from https://cdnjs.com/libraries/octicons/4.4.0
Should be quite reliable. If not, maybe we can do some caching to server W3MI but that has some complexities

**Comment by larshp** [comment]
👍 would like not to duplicate any external files inside the abapGit repository
