### ISSUE TITLE
Dump on Clone or Explore

### ISSUE THREAD

**Issue by sergiu230** [larshp/abapGit#53]
I get a dump when I try to clone or explore any of the projects.

I am running SAP on an old windows server virtual machine. I've installed firefox on the virtual machine and exported the certificates after I logged in on github on the virtual machine.

![image](https://cloud.githubusercontent.com/assets/3950633/6425528/edf1e9cc-bf2d-11e4-92fc-e9e2394a45c4.png)

![image](https://cloud.githubusercontent.com/assets/3950633/6425534/147bc928-bf2e-11e4-8bfc-63d713053b7d.png)

![image](https://cloud.githubusercontent.com/assets/3950633/6425536/26de284a-bf2e-11e4-8340-cd838104b0e8.png)
![image](https://cloud.githubusercontent.com/assets/3950633/6425544/429070f2-bf2e-11e4-81c0-ba7d0982233d.png)
![image](https://cloud.githubusercontent.com/assets/3950633/6425546/54a93cba-bf2e-11e4-9ce8-fef9b8fa5005.png)

**Comment by larshp** [comment]
Hi, whats the value of sy-subrc? The PSE files contain the SSL certificates, so this might be related to the SSL setup, make sure to double check STRUST SETUP

**Comment by sergiu230** [comment]
sy-subrc = 2

Am I missing something here? I never inputted my git username and password anywhere.

Also do I need to install OAuth2 and Sap cryptographic library?

Here is a screenshot of my STRUST
![image](https://cloud.githubusercontent.com/assets/3950633/6426137/7e7cfc04-bf4a-11e4-91df-75757235b4ce.png)

**Comment by larshp** [comment]
I guess Oauth is not needed, but the cryptographic stuff is.

See these links
http://help.sap.com/saphelp_nw70ehp2/helpdata/en/49/23501ebf5a1902e10000000a42189c/frameset.htm
https://service.sap.com/sap/support/notes/510007
http://scn.sap.com/community/netweaver-as/blog/2005/10/11/setup-https-ssl-for-the-sneak-preview-sap-netweaver-04-abap-edition-on-windows

If HTTPS service is running in transaction SMICM, I think the ABAP part can also handle SSL

**Comment by gregorwolf** [comment]
I think you have not yet the SAP crypro library installed. In STRUST there must be a node for SSL Client. As you are on windows my Blog: http://scn.sap.com/community/netweaver-as/blog/2005/10/11/setup-https-ssl-for-the-sneak-preview-sap-netweaver-04-abap-edition-on-windows can help you.

**Comment by larshp** [comment]
Hi Sergiu,
Any luck? Can I close the issue?

**Comment by sergiu230** [comment]
Not yet, I tried following gregorwolfs blog post. However I could not make it work. Once I edited the following file "C:usrsapNSPSYSprofile NSP_DVEBMGS00_hostname". I could no longer log in with BCUSER because it would error as invalid license.

**Comment by sergiu230** [comment]
This version of SAP doesn't let me use cryptographic stuff. I have closed the issue.
