### ISSUE TITLE
HEAD in select branch dialog (minor tweak)

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#531]
Do we need separate "HEAD" in the selection list ?
Maybe just output `(HEAD)` suffix for the head branch like: refs/heads/master (HEAD) ?

![image](https://cloud.githubusercontent.com/assets/15635498/21826690/25e45608-d791-11e6-8387-0d2c9705d8ce.png)

**Comment by larshp** [comment]
yeah, good idea

**Comment by sbcgua** [comment]
Like this now, also removed `refs/heads`

![image](https://cloud.githubusercontent.com/assets/15635498/21894298/564bc5f4-d8e7-11e6-9028-9a2517a9ace6.png)
