### ISSUE TITLE
bug (regression): when an object is deleted it is now showing as in sync. This is dangerous!

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#532]
Hello,

I had a diff in a table. Even when doing a "Reset local" it was still showing a diff. So I decided to delete it and pull so that it would be created afresh. Much to my surprise, after I deleted it, it was not showing in the list of objects with diff. Instead, it was now down there together with all the other objects which are supposed to be sync'd:

![image](https://cloud.githubusercontent.com/assets/532049/21854529/56721938-d81b-11e6-819b-cda20817f5fa.png)

But it does NOT exist in the system! And if I click on it it will give an error:

![image](https://cloud.githubusercontent.com/assets/532049/21854617/b2c062a8-d81b-11e6-9615-5ae338e30ef7.png)

This is very dangerous!

I was lucky that I noticed this otherwise I'd have a missing object which would not be reported by abapGit. The workaround: to remove the repository and clone it again.

The exact same problem happened with a data element so it was not an isolated case. I had never seen this before.

Thanks,
Nuno

**Comment by sbcgua** [comment]
Tried to repeat this one - partially succeded. 

> Even when doing a "Reset local" it was still showing a diff  

Mmm, what kind of change was that ? I tried a very simple change (table description), then "reset" and the description was overwritten and status was displayed correctly.

> after I deleted it, it was not showing in the list of objects with diff

This one confirmed. But not sure how to solve. During status calculation second loop of `calculate_status` tries to find the object in the system via `lcl_tadir=>get_object_package` which actually check the tadir. However until the transport is released there is a record in tadir (and `delflag` is empty for table for some reason - I'm not that deep in the low level stuff). 
So the package of the deleted object is found and object is treated as existing one. So there should be some more reliable way to check the object was deleted. @larshp do you have any ideas ? I can only think of calling "lcl_object->exists" for all entries ...

**Comment by sbcgua** [comment]
one more thought: `repo->get_files_local` calls `lcl_tadir=>read` which calls `check_exists` which actually checks `lcl_object->exists` for all entries **and removes deleted**. What if it will return local_files with deleted ones (marked with some flag) ? then it can be reused in `calculate_status`.
This looks like a surgery however ... I wonder how many bug this might create :)

**Comment by sbcgua** [comment]
found a bit different idea
@nununo could you pls check - does it solves your case ? if yes, I'll merge to master

**Comment by nununo** [comment]
Hi,

Unfortunately I have a go-live on February 1st, the devs should be frozen by now but, as expected, besides the bugs they find, the designers are still putting their imagination to good use. So I'm already multiplexing a lot with no time left for anything else.

I'll hopefully resurface in February when things cool down. And then I'll test, ok?

Sorry for not being of much help until then :(

**Comment by sbcgua** [comment]
@nununo OK, no problem :) Well, what I'll do, I'll actually PR it, because the commit certainly fixes at least one bug. Then, when you have time, just confirm (or not confirm :) that it solved the original issue.

Good luck with the go-live !

**Comment by sbcgua** [comment]
@nununo did you have a chance to double check it ? Can it be closed ? =)

**Comment by nununo** [comment]
Hi @sbcgua sorry for the late reply. Due to a project policy change I haven't been able to use abapGit for some time now but while I was still using it I never saw it happening again. 

I suggest we close it and reopen it if it happens again.
