### ISSUE TITLE
Moved an object out of the package... and still... no PULL nor STAGE available

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#533]
Hello,

I moved a function group to another package. Now I get a list of red warnings saying:

> Package and path does not match for object, FUGR .....

I'd expect I'd be able to somehow edit the repository and remove the object from there. But in order to be able to do it I had to make an insignificant change to a data element description to make the STAGE button show up.

**Comment by larshp** [comment]
guess this issue is related: https://github.com/larshp/abapGit/issues/514 lets keep both open in case it is not the same code fix

**Comment by larshp** [comment]
I think this is solved with https://github.com/larshp/abapGit/issues/1378
