### ISSUE TITLE
Separate committer / author name from username

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#535]
While doing a rebase using git command line I noticed on GitHub that committer and author name had diverged. When that happens you get this effect on GitHub:
![image](https://cloud.githubusercontent.com/assets/5270359/21957392/4199d61e-da95-11e6-92aa-90bd92bf8882.png)
![image](https://cloud.githubusercontent.com/assets/5270359/21957395/4c056a5a-da95-11e6-98fd-09744b3ae946.png)
The commit looks like this:
![image](https://cloud.githubusercontent.com/assets/5270359/21957420/fde291d0-da95-11e6-9efb-5ac230940ea5.png)

I personally like to have my full name as the committer and author name of my commits. In command line git I have a .gitconfig that looks like this:
```
[user]
  name = Full Name
  email = my.email@host.com
```
And my username is not relevant because of SSH authentication. It would be over https but that authentication is completely separated.

In abapGit currently you can specify committer and author name in the commit dialog. It is however prefilled with the username associated to the current repository (in the example above I of course forgot to change it). So for me I have to change it every time I do a commit and then also change it again in the upcoming login dialog, because there my full name then appears which of course needs to be the username for authentication.

I would like a similar option to `git config --global user.name "name"` in the settings page where you can optionally specify a global name for your SAP account there and if it is filled it will be used in the commit dialog but not in the authentication dialog.
Or is there an option already that I did not find?  

- https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/
- https://help.github.com/articles/setting-your-username-in-git/

**Comment by larshp** [comment]
good idea, do not think it is currently possible, perhaps it should default the username, but if overwritten then save this as the new default

**Comment by sbcgua** [comment]
@larshp why not possible ? If I understand correctly - can be fixed in `lcl_git_porcelain->receive_pack`. Well not only ... a new user setting fields and etc ... author name can be separate field to username (or maybe rename it to `login`).  We can also make separate author and commiter fields (I needed it a couple of time although not critical). I can have a look. What do you think ? Or there are some obstacles I don't see ?

**Comment by larshp** [comment]
we can implement it

**Comment by sbcgua** [comment]
Does this look fine ? @flaiker @larshp 

![image](https://cloud.githubusercontent.com/assets/15635498/23224010/60013db8-f935-11e6-9435-e6c8ce99ceb4.png)

![image](https://cloud.githubusercontent.com/assets/15635498/23224054/8829fe38-f935-11e6-815f-f977d22eeb1a.png)

Code to test is [here](https://github.com/sbcgua/abapGit/tree/t535-commiter-author). If OK, I'll PR

**Comment by larshp** [comment]
looks okay to me

**Comment by flaiker** [comment]
👍

**Comment by sbcgua** [comment]
@flaiker could you pls check the latest AG version ? If this is OK, I guess the issue can be closed :)

**Comment by larshp** [comment]
it is not merged yet, I will merge tomorrow. But you can try the branch

**Comment by sbcgua** [comment]
ah, ok, sorry :)

**Comment by flaiker** [comment]
@sbcgua Seems to work fine for me, thanks :)

**Comment by sbcgua** [comment]
closing then
