### ISSUE TITLE
Not being able to save XML user configuration.

### ISSUE THREAD

**Issue by christian1020-94** [larshp/abapGit#539]
I get an ASSERTION_FAILED dump when trying to save the XML user configuration. As far as I've looked, the data is being cleared in the ELSE of the following method. There is also a " Hmmm ??? " commentary, so I think there is something weird happening here.

    METHOD dbcontent_decode.
 
      DATA: lt_fields TYPE tihttpnvp,
            lv_string TYPE string.

      CONCATENATE LINES OF it_postdata INTO lv_string.
      rs_content = dbkey_decode( lv_string ).
  
      lt_fields  = cl_http_utility=>if_http_utility~string_to_fields( lv_string ).
      field_keys_to_upper( CHANGING ct_fields = lt_fields ).
  
      get_field( EXPORTING name = 'XMLDATA' it = lt_fields CHANGING cv = rs_content-data_str ).
      IF rs_content-data_str(1) <> '<' AND rs_content-data_str+1(1) = '<'. " Hmmm ???
        rs_content-data_str = rs_content-data_str+1.
      ELSE.
        CLEAR rs_content-data_str.
      ENDIF.

    ENDMETHOD.                    "dbcontent_decode

**Comment by larshp** [comment]
can you add the first few characters from variable `rs_content-data_str`?

plus which assertion is it that fails? i.e. which line causes the dump

**Comment by christian1020-94** [comment]
`rs_content-data_str` starts with `<?xml version="1.0" encoding="iso-8859-1"?>` .

And the assertion that fails is:

    METHOD print.

      DATA: li_ixml           TYPE REF TO if_ixml,
            li_xml_doc        TYPE REF TO if_ixml_document,
            li_stream_factory TYPE REF TO if_ixml_stream_factory,
            li_istream        TYPE REF TO if_ixml_istream,
            li_parser         TYPE REF TO if_ixml_parser,
            li_ostream        TYPE REF TO if_ixml_ostream,
            li_renderer       TYPE REF TO if_ixml_renderer.


      ASSERT NOT iv_xml IS INITIAL.
      ...
    ENDMETHOD.

**Comment by larshp** [comment]
hmm, I dont think I can reproduce it with above information, can you try on eg. another system, and/or switch on the debugger to see where it fails?

**Comment by christian1020-94** [comment]
What I found is that the:

    ELSE.
      CLEAR rs_content-data_str.

is clearing the XML, so when it reaches the ASSERT, it fails.

**Comment by larshp** [comment]
okay, try commenting the 2 lines

```abap
ELSE.
  CLEAR rs_content-data_str.
```

and see if it works?

What ABAP backend version(SAP_BASIS) are you using?

**Comment by christian1020-94** [comment]
SAP_BASIS 740 SP 08.

I tried that change before and works.

**Comment by larshp** [comment]
cool, I have changed the code in https://github.com/larshp/abapGit/commit/68c51626a3d33e88c8f38a240791a9fbad68aca2

I think there is something broken somewhere regarding code pages, but hope it works how 😄
