### ISSUE TITLE
Changes not detected in offline repository

### ISSUE THREAD

**Issue by christian1020-94** [larshp/abapGit#541]
I created an offline repo, made a change in a program from the repository's package, but when I  run the ZABAPGIT, there is no commit link. As far as I've seen in the code, there is nothing that detects if there was a change in the object for offline repositories. Is there something I'm missing?

**Comment by larshp** [comment]
For offline repositories it does not keep track of changes, as all files are exported via the "Export zip" option

**Comment by christian1020-94** [comment]
Sorry if this sounds like a dumb question, but  what can I use "offline repo" for?

**Comment by larshp** [comment]
just importing zip and exporting zip

https://github.com/larshp/abapGit/wiki/Installing-a-repository-offline
https://github.com/larshp/abapGit/wiki/Exporting-offline-project-to-repository

I can add more explanation in the wiki if you have any suggestions?

Offline is mainly just a workaround when there is no connection to a git repository. Depending on what you plan to use abapGit for you might want to look into https://github.com/larshp/abapGitServer (note it is also work in progress) as it can be installed on the ABAP application server.

**Comment by christian1020-94** [comment]
What happens is that I cannot do the SSL configuration. In this step from the "Installing abapGit guide":

> 3. Open "SSL System Client SSL Client (Anonymous)" folder

I don't find a folder but a "X". I tried to create it and everything but it seems I'm missing something in that folder configuration (I don't know so much about this SSL topic).

So, I thought that I could use an offline repository to locally track the changes I made in programs.

**Comment by larshp** [comment]
STRUST: goto change mode and right click the line with the "X" -> Create 

![image](https://cloud.githubusercontent.com/assets/5888506/22037211/92775260-dcf6-11e6-8ec4-df0656a2e9f9.png)

with offline repos you can still track changes, just some manual work to export the zip file and then use another git client for finding the changed files and commit + pushing

**Comment by christian1020-94** [comment]
Mmmm, couldn't this be automated by executing bash scripts in the local machine?

**Comment by larshp** [comment]
yes, however the main focus so far have been online repositories

did it work creating the folder in STRUST?

**Comment by christian1020-94** [comment]
I tried that multiple times. Create the folder, add certs, run the ZABAPGIT_TEST_SSL and get an error.

**Comment by larshp** [comment]
what is the error? perhaps I can help

**Comment by christian1020-94** [comment]
In the `receive` method I'm gettting this error:
> 110
> HTTPIO_PLG_CANCELED

As exception from the call I get `http_communication_failure`. It seems it's a problem with PSE.

**Comment by larshp** [comment]
Hmm, have not seen this error before.

Try checking the log in transaction SMICM -> Goto -> Trace File -> Display End, it might help

**Comment by christian1020-94** [comment]
I'm getting this error:

> [Thr 140221997504256] *** ERROR => IcmConnConnect: No service for protocol HTTPS started [icxxconn.c   2755]
> [Thr 140221997504256] IcmConnConnect: Connect failed for session GUI T5_U31793_M1, 200, BCEXTSF11, Christian-PC, time=02:39:23, W14,

**Comment by christian1020-94** [comment]
Mmm, it's not even configured there. Only HTTP and STMP are configured. Do you know if I can configure it myself or is basis stuff?

**Comment by larshp** [comment]
in SMICM -> Goto -> Services

then Service -> Create

If you have some basis guys I recommend contacting them, as they might get annoyed if you create it 😄
