### ISSUE TITLE
Restrict certain objects in "Export ZIP"

### ISSUE THREAD

**Issue by christian1020-94** [larshp/abapGit#544]
Maybe it should be possible an advanced option to filter the objects/types that will be exported. This could be useful in large projects where you are not touching every object.

**Comment by larshp** [comment]
In the top "Advanced" menu it is possible to cherry pick objects, or download by transport

![image](https://cloud.githubusercontent.com/assets/5888506/22074213/e6bf47cc-dda7-11e6-8754-294fa2fe2a2c.png)

It is not possible to filter, but perhaps you can create a transport with the objects, or alternatively split your development into more packages.

In the future I hope to implement a feature where it is possible to download an object along with its dependencies. I.e. when downloading PROG ZFOOBAR it automatically downloads all classes, dictionary objects etc, that are required to run ZFOOBAR.

**Comment by christian1020-94** [comment]
Yeah, Transport to zip will work for me.

About the dependencies feature, is there an issue # about that?

**Comment by larshp** [comment]
dependencies feature: no issue, just something I have been thinking of

**Comment by christian1020-94** [comment]
I'm trying "Transport to zip", but as I see, it serializes all the package objects. Is this necessary or can be improved?

**Comment by larshp** [comment]
it can be improved, however some refactoring is required

**Comment by christian1020-94** [comment]
I'll be working on this improvement, but is it necessary to create another issue?  Because it's not related to the this #544 issue.

**Comment by larshp** [comment]
We have a lot of texts/comments in this issue, so it will be easier and faster to understand if we close this issue and create a new one. Containing a description of the problem and perhaps a description of the proposed solution.

Note that if the transport contains 2 objects one in the top package and one in a child package, I expect this to be reflected in the folder structure, like when exporting the entire package to zip.

**Comment by christian1020-94** [comment]
Created issue #553.
