### ISSUE TITLE
No english description

### ISSUE THREAD

**Issue by christian1020-94** [larshp/abapGit#545]
Is it really mandatory to have a description in English for every object? I'm getting the 'TOBCT no english description' error for some objects.

    METHOD lif_object~serialize.
      ....
      SELECT SINGLE * FROM tobct INTO ls_tobct
        WHERE oclss = ms_item-obj_name
        AND langu = mv_language.
      IF sy-subrc <> 0.
        lcx_exception=>raise( 'TOBCT no english description' ).
      ENDIF.

      io_xml->add( iv_name = 'TOBC'
                   ig_data = ls_tobc ).
      io_xml->add( iv_name = 'TOBCT'
                   ig_data = ls_tobct ).
    ENDMETHOD.                    "serialize

**Comment by larshp** [comment]
nope, I have recently removed a few of this kind of errors from the code. Feel free to submit a pull request, if you like?

**Comment by christian1020-94** [comment]
Already working in this change (I'm new to git so I hope I get all right).
