### ISSUE TITLE
Deletion pop-up when deleting table

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#548]
Whenever a TABL is deleted, I receive the following example pop-up:

![image](https://cloud.githubusercontent.com/assets/2248490/22104281/bca24812-de3e-11e6-9662-0c317462241f.png)

Is this on purpose so that the user does not accidentally delete a table and lose data?

Other objects such as domain, dtel, have a 'no_ask' set as true when calling 'RS_DD_DELETE_OBJ'

**Comment by larshp** [comment]
I would like to get rid of as many popups as possible, just haven't had time to look into it

**Comment by nununo** [comment]
Hum... interesting... abapGit never tried to delete objects. Whenever I sync a repository in which objects have been deleted I just see them in the target system as only existing there and have to delete them manually. 

How do you get abapGit to delete stuff?
I don't dislike the popup. If you think about removing it it would be nice if that could be customizable.

**Comment by larshp** [comment]
Advanced -> Uninstall, it deletes all objects in the package

When doing pull it does not delete objects

Problem with the popup is that if you have a repository with 200 objects, then there might be 50 popups for deleting different kind of objects.

**Comment by EduardoCopat** [comment]
>How do you get abapGit to delete stuff?

Repo -> Advanced -> Uninstall

>I don't dislike the popup. If you think about removing it it would be nice if that could be customizable.

That was my idea also, I will create a new setting then. What about?

- [X] Hide table deletion pop-ups (default is true)

**Comment by nununo** [comment]
Ah... You mean when uninstalling. Then I agree. 
I thought you meant when syncing.

**Comment by EduardoCopat** [comment]
By that, do you also think the "settings" is needed?

**Comment by larshp** [comment]
When uninstalling there is a initial popup showing a warning, this one we should keep. 

But all the subsequent popups are annoying 😄 I do not think a setting is needed in this case

**Comment by nununo** [comment]
I'd say the first warning popup is enough for uninstalling
