### ISSUE TITLE
"Transport to zip": don't serialize objects that are not in the transport request

### ISSUE THREAD

**Issue by christian-94** [larshp/abapGit#553]
In large. packages this can improve the performance considerably. 
**Actual situation**: first all the package objects are serialized and then, the filter (from the transport request objects) is applied.

**Proposed solution:** Read all the package objects. Apply the filter. Serialize.

Actually working in this solution. What I've noted so far and need to clarify before creating a PR is that in the _actual situation_, a ".abapgit.xml" is not being generated (because it is deleted when filter is applied). With the _proposed solution_ the ".abapgit.xml" is being generated and not deleted. So, what I'm not sure of, is that if that file is necessary to add to the zip file.

**Comment by christian1020-94** [comment]
I have all the changes in this branch: [issue553](https://github.com/christian1020-94/abapGit/tree/issue553).

**Comment by christian1020-94** [comment]
@larshp I tested the case you mentioned in #544 and it works as expected:

> Note that if the transport contains 2 objects one in the top package and one in a child package, I expect this to be reflected in the folder structure, like when exporting the entire package to zip.

I need to do more tests, specifically online repository tests. I've been working just with offline repositories because of connection problem.
