### ISSUE TITLE
UI page_db_display, indentation and highlighting

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#556]
Space for improvement

![image](https://cloud.githubusercontent.com/assets/15635498/22156694/20631d78-df3d-11e6-8a84-3611dc36a40a.png)

`page_db_display` would benefit from indentation and highlighting.

Current plan: implement indentation in `lcl_xml_pretty=>print` and then attach highlighter in `page_db_display->render_content`. @TheWirtschaftsmann volunteered to do it :)

**Comment by larshp** [comment]
Also when clicking edit the XML is not pretty printed...

**Comment by sbcgua** [comment]
yeap, good point. However, this one should pretty-print before edit and then unpretty-print before save, right ?

**Comment by larshp** [comment]
yeah, that would be perfect

**Comment by larshp** [comment]
hi, perhaps the indentation problem is due to the automatic formatting of the html, it should keep indentation as is for content in `<pre>` tags

![image](https://cloud.githubusercontent.com/assets/5888506/22175887/b9c835c2-dffe-11e6-9e13-f7a9acafa892.png)

**Comment by TheWirtschaftsmann** [comment]
Hi @larshp ,

New feature arrived:) 

XML-highlighting will look as follows:

![image](https://cloud.githubusercontent.com/assets/6059582/22326141/3096e4fa-e3ba-11e6-97f4-00f6875fa700.png)

Besides, I've also added small fine-tuning to the display of DB table:

![2017-01-26_11h26_49](https://cloud.githubusercontent.com/assets/6059582/22326183/54ad7bce-e3ba-11e6-9856-2f79588f9456.jpg)

I've created PR #582 to merge these changes.

**Comment by sbcgua** [comment]
BTW indentation was a bug of lcl_html. The new version renders it correctly.
Regarding saving XML without indentation: I'll have a look on it but later. If **anyone** would like to take the lead - it's welcomed - I'm not an expert in XML classes :) I shortly tried to change `set_normalize( false )` in `lcl_pretty=>print` - it removes newlines but does not remove spaces between tags. So seems a bit more complicated. Maybe ID transformation can remove it ... or regex substitution (should be quite safe - `>\s+<` to `><`)

**Comment by sbcgua** [comment]
@larshp Solved the unprettify thing. Seems to work. Could you have a look ? https://github.com/sbcgua/abapGit/commit/15249221a66ec714a1b3ce902508ef402444d92f
But I'm not sure if it is the best solution. Maybe as short term ... but in general I think it would be better to actually de-serialize XML to be saved with appropriate class (and thus **validate** it) and serialize it again. What do you think ?

**Comment by larshp** [comment]
cool, can you open a PR for it, then I'll remember to look at it
