### ISSUE TITLE
How to add existing ABAP package to a new git repo?

### ISSUE THREAD

**Issue by njames** [larshp/abapGit#56]
It seems like all your doco is about getting from git->abap what about from abap->git initially?

**Comment by larshp** [comment]
Hi,
It should work the same as described in the wiki.

1: create git(hub) repository
2: clone the repository into abapGit(make sure the repository is not emtpy, add eg. README file), and select your package while doing this
3: the objects from the package should should show up in the list with _add_ options

**Comment by larshp** [comment]
See the following,
https://github.com/larshp/abapGit/wiki/Moving-existing-package-contents-into-git

**Comment by larshp** [comment]
Hi Nigel,
Any luck? Can I close the issue?

**Comment by njames** [comment]
Yes Thanks for that.
