### ISSUE TITLE
Problem with CUAD

### ISSUE THREAD

**Issue by fidley** [larshp/abapGit#562]
Hi Lars, 
I've just updated abapGit to latest build and I tried pulled the FALV but as in SAPLink I'm having problems with CUAD. I have to manually change variable l_nok to be empty while debugging to be able to install CUAD.

![2017-01-22_16h51_51](https://cloud.githubusercontent.com/assets/7912195/22183651/31c3fec0-e0c3-11e6-9463-b234f6c98b99.png)

Additionally after installing I still see difference between local and remote version. Which should not be I think.
![2017-01-22_16h51_34](https://cloud.githubusercontent.com/assets/7912195/22183654/3a6c214c-e0c3-11e6-87c0-83cefcdbf91f.png)

Cheers
Łukasz

**Comment by larshp** [comment]
what version(SAP_BASIS) are you using?

**Comment by fidley** [comment]
750 SP2

**Comment by larshp** [comment]
thanks, 

no problems on 740 SP10

note 2159455 introduces the CHECK_ADM form, I've earlier done an evil hack to get it working, see:
https://github.com/larshp/abapGit/blob/d093c2b6045db26a7d48905a7b929b62ccbf32a9/src/zabapgit_objects.prog.abap#L1446

After applying the latest version of note 2159455 I have reproduced the issue on my test system

**Comment by larshp** [comment]
hmm, it works if a dummy text is inserted in the ADM variable, however I do not know the consequences of this

perhaps just skip RS_CUA_INTERNAL_WRITE, and insert the data in the relevant places instead

**Comment by fidley** [comment]
I'd leave it adding this dummy text, I've checked on the code and if it's empty then this function always return l_nok = 'X', but if it's not then it does some additional checks. So for me it's sounds better to set dummy text instead of doing all manipulations directly

**Comment by larshp** [comment]
yeah, but filling setting `ADM-ACTCODE ='TEST'.` might be bad, and have some unforeseen consequences

**Comment by larshp** [comment]
Did some more testing, creating CUA saving to abapGit and reinstalling works., as ADM data is written, see https://github.com/larshp/PROG/blob/master/zfoobar.prog.xml#L72

Looking at the code for SAPLINK and the description in SAP note 2159455, I would regard this CUA as corrupt, as SAPLINK deletes the ADM fields.

You can:
1. Edit the XML manually and add some values in the ADM fields, however I do not know what the correct values should be(caution, I do not recommend this approach). Perhaps you can debug the standard code to find the correct logic.

2. Recreate the CUAs manually, I tried deleting the objects in the function group and recreating, but it seems that this does not initialize the ADM data. So perhaps the entire function group has to be deleted and recreated(most objects can be copied)

Tried deleting the function group and recreated a CUA manually, ADM values are written to the XML:
![image](https://cloud.githubusercontent.com/assets/5888506/22207675/3d2a8d7a-e180-11e6-8f68-db35151e064a.png)

**Comment by fidley** [comment]
No risk no fun, I've debug a bit and for me the numbers which are stored in ADM are the latest ID used in STATUSes and TITLEs, so I've manually entered proper entries to XML and now everything works like a charm. I know it's ok, because before when I was trying to edit the GUI status I was receiving an error that this status is inconsistent so I can only view it. Now I can edit it without problems.
![image](https://cloud.githubusercontent.com/assets/7912195/22216653/38027856-e1a0-11e6-88b8-05b70a5fd331.png)

Thanks a lot.
