### ISSUE TITLE
New entry in Explore

### ISSUE THREAD

**Issue by fidley** [larshp/abapGit#564]
Lars

can you add https://github.com/fidley/falv as new abapgit repository under Explore button? After some tests I moved everything to my main FALV repository.

Thanks
Łukasz

**Comment by larshp** [comment]
done, https://github.com/larshp/abapGit/commit/2abcc772c6c99e9dbd206d3fc23321de8837ff75

it might be a few minutes before the caches clear, both server and client side

note that the explore page is always randomly ordered
