### ISSUE TITLE
"Create package" button when adding +Offline project

### ISSUE THREAD

**Issue by christian1020-94** [larshp/abapGit#567]
It would be useful to have a [Create package] button in the "+Offline" popup, just as "+Clone" has. From my own experience, I've had to do this manually like 4 times, so it's kind of annoying. It would look like this:

![image](https://cloud.githubusercontent.com/assets/16184648/22187209/40a3f35c-e0d0-11e6-98ad-2c9f4b6392be.png)

Tomorrow I can start implementing this if you guys think is useful.

**Comment by larshp** [comment]
I think it is useful

**Comment by EduardoCopat** [comment]
Functionality from the `+Clone` package creation can be reused

**Comment by christian1020-94** [comment]
Great, I will look at this then :smirk:
