### ISSUE TITLE
v1.26.0 - Tutorial doesn't work

### ISSUE THREAD

**Issue by grahamrobbo** [larshp/abapGit#568]
When clicking the "tutorial" links nothing happens.
![image](https://cloud.githubusercontent.com/assets/1305633/22192372/9c0e2c82-e187-11e6-8059-db1c0f3b3c45.png)
![image](https://cloud.githubusercontent.com/assets/1305633/22192395/d66f54a0-e187-11e6-99dc-f8c2a9b95d11.png)

**Comment by christian1020-94** [comment]
Mmm, it is working for me. Maybe it has something to do with not having any project yet?

**Comment by larshp** [comment]
issue replicated, uninstall everything(https://github.com/larshp/abapGit/wiki/Uninstalling-abapGit) and install again

**Comment by larshp** [comment]
@grahamrobbo try again
