### ISSUE TITLE
v1.26.0 - Branch Overview no longer working

### ISSUE THREAD

**Issue by grahamrobbo** [larshp/abapGit#569]
Only showing master branch. Also "Compress Graph" button doing strange things.

![image](https://cloud.githubusercontent.com/assets/1305633/22193019/e27f9b6a-e18c-11e6-9cc0-80447a7d3708.png)

![image](https://cloud.githubusercontent.com/assets/1305633/22193037/02cf1a94-e18d-11e6-955f-87fb9793f1cc.png)

**Comment by grahamrobbo** [comment]
More details on this. It seems like abapGit is not picking up the entire commit history. I still only shows the first three commit points for this repo. BTW this repo is public if you want to test using it in case it is something repo-specific.

![image](https://cloud.githubusercontent.com/assets/1305633/22198536/11af93f4-e1ab-11e6-9dca-5282df86d13a.png)

**Comment by larshp** [comment]
Compress button fixed: note that it only does compression if there are 10 or more subsequent commits in a branch, so in your case it will not do anything

will look into the missing commits next, there are 11 commits in the internal table however only 3 are rendered

**Comment by larshp** [comment]
Something is wrong with the times, after sorting commits by time(which might be a bad strategy) it gives the following result:

![image](https://cloud.githubusercontent.com/assets/5888506/22206112/2d1dbb74-e17a-11e6-870d-13c268c12123.png)

Also the history in GitHub looks strange:

![image](https://cloud.githubusercontent.com/assets/5888506/22206134/499326a4-e17a-11e6-834c-aa0ef0fc6dae.png)

Can you check that the time/zone settings are correct in the SAP system?

**Comment by grahamrobbo** [comment]
I did have timezone issues with that server in the middle of doing those commits so that makes some sense.

But GitHub itself seems to be able to figure it out
![image](https://cloud.githubusercontent.com/assets/1305633/22232167/e1fcb952-e23b-11e6-928f-e194274cd35a.png)

**Comment by larshp** [comment]
yeah, "sorting commits by time(which might be a bad strategy)", should change the logic to look at the parent commits instead, but this is hard work 😄

**Comment by grahamrobbo** [comment]
Well I'm all for less hard work :)

**Comment by larshp** [comment]
added https://github.com/larshp/abapGit/issues/577 perhaps someone will look into it some day

**Comment by prashantagl** [comment]
Hi Graham, currrently we have exploring different options in abapgit for multilandscape scenarios.

 I am based out of Melbourne. Would like to discuss with you, hows your exprience in using abapgit and github.

Br,
Prash
