### ISSUE TITLE
GitHub Auth. fail if PW contains special chars

### ISSUE THREAD

**Issue by LeTysker** [larshp/abapGit#57]
Reproduce by changing GitHub pw to something containing the "!" character and try to clone a repository via abapGit.

**Comment by larshp** [comment]
Thanks I'll look into the issue, the code uses standard SAP for generating the password stuff, so it might work on a different SAP release, if not I'll implement the basic auth from scratch

**Comment by larshp** [comment]
no additional error reports, closing

plus this uses standard functionality to encode the password
