### ISSUE TITLE
v1.26.0 abapGit & plugins have disappeared from "Explore" page

### ISSUE THREAD

**Issue by grahamrobbo** [larshp/abapGit#570]
This was a really easy way to setup cloning of abapGit & pugins repos. Can I have it back please?

**Comment by larshp** [comment]
it is part of the tutorial page now(which does not work for you, https://github.com/larshp/abapGit/issues/568), 

![image](https://cloud.githubusercontent.com/assets/5888506/22193235/3d3d4564-e13a-11e6-8481-73a4f906dec0.png)

**Comment by grahamrobbo** [comment]
So the tutorial is back...but when I try and install abapGit repo I get "Seems like abapGit package is already installed. No changes to be done".

![image](https://cloud.githubusercontent.com/assets/1305633/22198043/d5572e8c-e1a8-11e6-9a6c-84050f95b06e.png)

**Comment by larshp** [comment]
Check the "burger" icon to see if it is already there,

![image](https://cloud.githubusercontent.com/assets/5888506/22198184/af72e902-e155-11e6-904a-f95be10e044b.png)

**Comment by grahamrobbo** [comment]
Before thinking to check burger icon I used db utility to remove an invalid reference to that repo. Restarted program and then it worked. 👍
