### ISSUE TITLE
Branch Overview - Truncated details 

### ISSUE THREAD

**Issue by grahamrobbo** [larshp/abapGit#571]
Just noticed another thing that bothers me - the branch details only seem to use about a third of the page width and then truncate.

![image](https://cloud.githubusercontent.com/assets/1305633/22193325/a5b2536a-e18e-11e6-9a33-12499b715188.png)

**Comment by larshp** [comment]
did a short test, cannot reproduce the issue

try right clicking -> view source, and save it as html, and do a few adjustments, it is the Canvas element that contains the graph
