### ISSUE TITLE
Tutorial - Hide "install abapGit" + plugin links if already installed

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#573]
Tutorial - Hide "install abapGit" + plugin links if already installed

**Comment by sbcgua** [comment]
I'd say not "hide" but indicate that they are installed. Looking at communication in #570 seems that it is not that clear on how to find this.

**Comment by larshp** [comment]
good idea

**Comment by larshp** [comment]
PR: https://github.com/larshp/abapGit/pull/586
