### ISSUE TITLE
Transport to zip. Select multiples transport requests

### ISSUE THREAD

**Issue by christian1020-94** [larshp/abapGit#578]
I was thinking it would be useful to allow selecting multiple TR in the Transport to zip option. Is this viable?

**Comment by larshp** [comment]
yeah, feel free to open a PR. I guess easiest is one zip per transport, but 1 zip for all transports would also be nice

**Comment by larshp** [comment]
@christian1020-94 can we close this issue?

**Comment by christian1020-94** [comment]
Sure, I've been looking for a function to show the selected requests but I'm getting some screen issues. If not able to solve it I will be posting it.
