### ISSUE TITLE
Problems when importing from git

### ISSUE THREAD

**Issue by kaysap** [larshp/abapGit#58]
I did not succeed in importing an ABAP report from the remote repo. Erroneous line feeds confused the compiler and made activation impossible. 
Backend is 7.40 SP7.

You can test with the example at github.com/kaysap/abapgit.git.

Please note that my first test was against a gitlab repo, maybe that's the catch?

**Comment by larshp** [comment]
Hi,
Can you paste a screenshot of the compiler error? I've tested in 730 SP5 and it seems to work.

Also please try to import https://github.com/larshp/Foobar.git into your system to see if it gives the same error

**Comment by kaysap** [comment]
Importing Foobar.git from github worked. 
Local subpackages ($FOO under $TMP) cause trouble, but let's ignore this for now.
I will mirror this repo to gitlab and continue testing.

My SAP system is running on Windows, but since no filesystem is directly involved, this should not pose any problems, right?

**Comment by kaysap** [comment]
Importing from gitlab worked ok, but the package assignment seemed odd... 
ZTEST
|--> ZFOOBAR

I imported into ZTEST, but the DDIC elements were put into ZFOOBAR instead. 
The class was created in ZTEST and activated correctly.

abapGit showed the DEVC ZTEST in the overview as a new object. Now I can't uninstall the repo, because DEVC is not supported.

After a restart the DEVC entry is still there (not shown as new), but uninstall still fails. (Error from SEO_CLASS_DELETE_COMPLETE)

**Comment by larshp** [comment]
yes, there are some trouble with package assignments, the package selected in the clone popup is not always automatically used for the reports, in this case you have to enter it manually.

Uninstalling: You can goto transaction SO10 and delete text name = ZABAPGIT, this will make it forget about the repository. And then manually delete all objects in the package.

I havent tested very much with "real" packages, can you try cloning it into a temporary package, you can create a new named eg. $FOOBAR

**Comment by kaysap** [comment]
Uninstalling the repo was helping a lot.

Ok, so my latest test worked.
I created package $ZFOO (not a subpackage of $TMP), created an empty repo in gitlab and cloned it.
Then I wrote a simple test report and committed to the repo. After that, I deleted the repo link in SO10 and deleted the ABAP program and cloned the repo again. As a last step I refreshed the contents of $ZFOO.

Now everything looks ok! Yay! :-)

I think that the basic functionality is working correctly, but abapGit needs some more work to support the workflow better. 

My first suggestions at this point would be to  
* make the user aware of conflicts while cloning. Overwriting existing stuff without notice makes no friends.
* While working with real (non-local) packages, either add full package support or let the user exclude the package object from the repository.

Great work, I am really looking forward on seeing this grow!!

**Comment by larshp** [comment]
:+1: 

Overwriting: When pulling the latest code from a repository it will overwrite the original code. However adding a warning on the initial clone of a project, if it overwrites something in the system is a good idea.

Packages: one package equals one repository, I see packages as something the users manage, package names are currently not stored in abapGit xml objects. So the quick fix is to just exclude DEVC from the list of contents in the package. Having abapGit to track package names might also make sense, but it requires globally unique package names for developments, but this is the same for domains, data elements, reports etc. hmm

**Comment by kaysap** [comment]
Yeah, sounds reasonable. I will try more objects and get back to you if something else is odd.
