### ISSUE TITLE
Dump while running abapGit after fresh installation by copying code

### ISSUE THREAD

**Issue by fidley** [larshp/abapGit#583]
After succesfull install on one of the systems, I'm receiving dumps while running the prograc because table ZABAPGIT is not available in the system. There should be some check of existance before dynamic select call or just exception catching ;)

Version 1.26.3 

![image](https://cloud.githubusercontent.com/assets/7912195/22327990/3f432d1a-e3ba-11e6-8c68-2fa8be652192.png)

**Comment by larshp** [comment]
abapGit automatically creates the ZABAPGIT database table at startup, try going to SE11 and check how it looks.

If an old version was previously installed, it might be due to field DATA having been renamed to DATA_STR, if so rename field DATA to DATA_STR.

If everything fails, try deleting database table ZABAPGIT and run abapGit, it should automatically create the table again. Note that abapGit configuration is lost

**Comment by nununo** [comment]
@larshp, I always wondered. In which package do you keep table ZABAPGIT?

At some point I kept it the $ABAPGIT package but then it would show as a DIFF which obviously doesn't make sense.

I ended up up creating package $ABAPGIT_DATA just for it.

**Comment by larshp** [comment]
table ZABAPGIT automatically goes to package $TMP, it also works if you move it to somewhere else after creation. Just keep it out of the same package as report ZABAPGIT, or it will show up as a diff, as you mention.

see https://github.com/larshp/abapGit/blob/39b285cb9d24b4f5e24334db11208f4f9a1e3e59/src/zabapgit_persistence.prog.abap#L1413

**Comment by fidley** [comment]
the table is not activated as I don't have correct authorizations here...  haven't you thought about using INDX table instead ? :)

**Comment by larshp** [comment]
also need the enqueue object, plus it is nice to be able to see the data in SE16

**Comment by larshp** [comment]
I have implemented extra checks, and tried disabling the auth check for table activation, see https://github.com/larshp/abapGit/commit/0f653bf15f11ebb3d2c077ba9db9499931534498

so we might avoid this happening for other people in the future

can we close the issue?

**Comment by fidley** [comment]
Yes, we can close it. Thanks!
