### ISSUE TITLE
Show selected transport requests in "Transport to zip" problem

### ISSUE THREAD

**Issue by christian102094** [larshp/abapGit#592]
Following #578 . I've been trying to implement this, but when I call the function to show some transport requests (the same that SE10 uses), I'm getting the screen like this:

![image](https://cloud.githubusercontent.com/assets/16184648/22481497/7e808fce-e7c3-11e6-8943-cd767ecd4d2e.png)

As you can see, the status is from the function, but the content is not. I have the code in [this branch](https://github.com/christian1020-94/abapGit/tree/show_selected_tr). Any clue?

**Comment by larshp** [comment]
normal dynpro screens does not work very well due to the abapgit screen setup. I would like to implement a page feature, see https://github.com/larshp/abapGit/issues/515, where a abapGit page can be called

**Comment by larshp** [comment]
is this still an issue after https://github.com/larshp/abapGit/issues/685 ?

**Comment by larshp** [comment]
closing
