### ISSUE TITLE
Import Transport from ZIP

### ISSUE THREAD

**Issue by corinzio** [larshp/abapGit#596]
How may I import a transport from a ZIP file in case it has objects belonging to different packages?
Thanks,
Luca

**Comment by larshp** [comment]
Assumption is that all objects in the transport share a common super package,
https://github.com/larshp/abapGit/blob/master/src/zabapgit_transport.prog.abap#L70

However if this is not the case, then you manually need to change the zip file, or adjust the packages after importing the zip.

**Comment by larshp** [comment]
@corinzio did above help?

**Comment by corinzio** [comment]
yes thanks, i forgot to close the issue.
