### ISSUE TITLE
Commits in offline project

### ISSUE THREAD

**Issue by christian1020-94** [larshp/abapGit#600]
Is it possible to make commits in an ABAP program from an offline project?

**Comment by larshp** [comment]
not sure what you mean, but the zip file can be downloaded, and then use something like eg. https://desktop.github.com/ to commit+push the files to a git repository

**Comment by christian1020-94** [comment]
Mmmm, I know, but do you think it could be possible to implement something like this but in the SAP GUI?

**Comment by larshp** [comment]
depending on your scenario, I would recommend using online projects or install https://github.com/larshp/abapGitServer

**Comment by christian1020-94** [comment]
Does abapGitServer need the SSL configuration as well?

**Comment by larshp** [comment]
most likely not, but it depends on your SICF setup

It can run on the same server as abapGit, i.e. the client and server is installed on the same ABAP application server

**Comment by christian1020-94** [comment]
I will take a look at it. Thanks for the idea!

**Comment by larshp** [comment]
@christian1020-94 can we close this issue?

**Comment by christian1020-94** [comment]
I haven't have the time to look at it, so I guess I will reopen later.
