### ISSUE TITLE
READ TABLE mo_repo->get_files_local( ) not valid in v702

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#601]
Hello,

I'm getting a syntax error in the latest version due to this line in include ZABAPGIT_PAGE_STAGE.

READ TABLE mo_repo->get_files_local( ) INTO ls_local_file WITH KEY file = is_file.

I will adapt it to be compatible with 702 and make a PR as soon as I can.

Nuno

**Comment by nununo** [comment]
I just submitted a PR #602. Please review my proposal

**Comment by EduardoCopat** [comment]
Is there any program which checks for ABAP retrocompatibility inside SE80 tools?

**Comment by larshp** [comment]
it is possible to do a remote syntax check via code inspector, but it requires a 702 system inside your landscape
