### ISSUE TITLE
2FA error while creating a branch

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#604]
Cannot create a branch anymore, getting this: 

![image](https://cloud.githubusercontent.com/assets/15635498/22784388/827dfece-eed8-11e6-9355-e700860fc7fe.png)

:(

**Comment by flaiker** [comment]
I got that too about an hour ago. I switched from only having the github.com and *.github.com certificates in STRUST to adding the root certificates and it worked again. Maybe there was some certificate swap on github's end.
What is your STRUST setup?

**Comment by sbcgua** [comment]
Hmmm ... seems like I've got github and all parent ones ...  
Also just rolled back to the version before 2FA and created a branched as usual on the same system.

**Comment by larshp** [comment]
try https://github.com/larshp/abapGit/wiki/ZABAPGIT_TEST_SSL with github.com and api.github.com

**Comment by sbcgua** [comment]
This one works

![image](https://cloud.githubusercontent.com/assets/15635498/22785336/8ac3f5ee-eedc-11e6-8e08-e1df8f019044.png)

**Comment by larshp** [comment]
hmm, try looking in transaction SMICM -> Goto -> Trace File -> Display End

**Comment by flaiker** [comment]
I just reread and saw you get the error when creating a new branch. That has never worked for me (not even with entering the access token as the password directly). I do however get a different error:
![image](https://cloud.githubusercontent.com/assets/5270359/22786115/846776ee-eed7-11e6-8753-55dd99b9158f.png)
![image](https://cloud.githubusercontent.com/assets/5270359/22786153/a7010db4-eed7-11e6-8b99-d1b71bf21a59.png)
Creating the branch via command line and switching to it in abapGit works fine though.

**Comment by sbcgua** [comment]
![image](https://cloud.githubusercontent.com/assets/15635498/22785995/5c77f138-eedf-11e6-9b47-d2f448ef5eb1.png)

Added *.github.com certificate to STRUST and it worked. I didn't realize that they differ (default github cert). Guess it worth adding to WIKI

Thanks for the tip !

**Comment by larshp** [comment]
@flaiker the "premature EOS" error is this for github.com?

**Comment by sbcgua** [comment]
Hmmm, so now it requires github cert, *.github cert and parents...  

Just for curiosity: but why ? Did the api calls changed after 2FA changes ? I thought it is kind of optional feature (very cool though :) ... I confess I didn't read the 2FA PR well :(

**Comment by larshp** [comment]
I only have the root certificate in my test system, i.e. only 1 certificate, and it works

I did some testing and it seemed like it worked fine with the certificates that I had installed previously. Changes is that now https://api.github.com is called

**Comment by flaiker** [comment]
@sbcgua The call to api.github.com is just made to check if two factor authentication is required for the account (because only on api.github.com you can get a specific response header if 2FA is needed).

@larshp The EOS error is exactly at lcl_http_client->send_receive right after mi_client->send( ) is called. On the receive call right after that http_commmunication_failure is raised. Callstack:
![image](https://cloud.githubusercontent.com/assets/5270359/22786635/a52f3c48-eed9-11e6-98c0-c7d017228850.png)

**Comment by sbcgua** [comment]
@larshp removed BOTH github and *.github and it worked too (just with 2 parents: root & sha2...).  
Seems to be resolved for me :) Thanks !

**Comment by larshp** [comment]
@flaiker for the EOS, can you open a separate issue for this, I have not seen this kind of error before, and not sure how to reproduce

**Comment by flaiker** [comment]
@larshp I will once I can reproduce it again. Just retried now and it works fine :/

**Comment by sbcgua** [comment]
I think this one can be closed
