### ISSUE TITLE
TOBJ don't show user at stage page

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#605]
Stumbled upon a minor strange bug. 

The sequence is quite unusual:
1) Cloned my test repo to a new system (https://github.com/sbcgua/ZGITHUB_TEST.git)
2) That repo was created by an older abapGit with old XML so it offered some changes to push immediately (so the last change to the object was done by AG itself!)
3) Pressed Stage

![image](https://cloud.githubusercontent.com/assets/15635498/22785220/19deee06-eedc-11e6-982f-dd693c2de524.png)

All the objects showed that they were changed by current user except `TOBJ`

A the same time user seems to be there if opened in GUI

![image](https://cloud.githubusercontent.com/assets/15635498/22785284/5aa89de2-eedc-11e6-8179-197d5ea94783.png)

Seems like user lost somewhere by the way but just for a specific object type ...

**Comment by larshp** [comment]
yeah, `changed_by` is not implemented for all the object types yet, see

https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_tobj.prog.abap#L29

this is also why I wanted to add it on the staging page, more visibility => more testing, and hopefully more fixes

**Comment by sbcgua** [comment]
thanks, that clarifies :)

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapGit/commit/9cfd9ea0ed312ee00e4221163f304ba82666e541

closing
