### ISSUE TITLE
Table types with classes as a line not working

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#606]
If you have a table type referencing a class, abapGit can't activate it properly.

Example in branch https://github.com/EduardoCopat/abap-sandbox/tree/ttyp-of-classes

How to reproduce:

1. Declare class FOO.
2. Create a Table type TT_FOO, referencing FOO as a line.
4. Declare class BAR.
5. Create a method qux inside bar and declare the table type `DATA: foos type tt_foo`

Commit and push.
Delete the repo and pull again.

You will receive an error like the following:
`Type TT_FOO is unknown`

![image](https://cloud.githubusercontent.com/assets/2248490/22792186/37008e94-eeec-11e6-993a-1f7b9000d7d6.png)

**Comment by EduardoCopat** [comment]
I think that now abapGit first activates the dictionary entities, and then later the classes. The problem with this particular TTYP seems like an egg and chicken problem 😕

**Comment by larshp** [comment]
yeap, chicken and egg problem

workaround is to define the type in the class instead of ddic

**Comment by EduardoCopat** [comment]
Another possible, although inelegant solution, if a table type has a class as a line type, then this table type should be activated together with the classes, in the second activation phase.

> cyclic dependencies which cannot(?) be solved

I can't think of other scenarios, for now.

**Comment by larshp** [comment]
the activation function module handles ddic = 'X' or ddic = '', so I'm not sure it is possible to activate DDIC and class at the same time.

scenarios, if eg.
Structure with REF TO class
is used by
the class
which uses
the structure

will be a cyclic dependency

**Comment by EduardoCopat** [comment]
Yeah, seems to be too complex and not worth it.

The easier workaround is what you mentioned, declare the type locally in your class:

```
CLASS cl_foo DEFINITION.
TYPES:
  tt_foo type table of ref to cl_foo
ENDCLASS.
```
