### ISSUE TITLE
how to create folder and then clone the folder into abapgit

### ISSUE THREAD

**Issue by prashantagl** [larshp/abapGit#609]
We have created repositories and within that we have created folders, but when we try to add objects from existing package in abapgit and clone it then how do we make sure files get created into respective folders within repositories?

Once files are commited in the repository then i moved the files into folders inside repository and when I check in abapgit I get error saying files are not in correct folder and there are duplicate files.

Below are screenshots from Gihub and abapgit

![image](https://cloud.githubusercontent.com/assets/25575475/22805621/8c53f8aa-ef72-11e6-9123-2235d80de075.png)

![image](https://cloud.githubusercontent.com/assets/25575475/22805604/74a51cc0-ef72-11e6-85fd-68658cc853aa.png)

Kindly advice

**Comment by larshp** [comment]
click the "Stage" button, it lets you add the 2 files inside the directory, and remove the 2 old files

**Comment by prashantagl** [comment]
Hi,

I see Add button against the files which I want to delete, the files which I want to add against that I see ignore or remove button. Please see below screen shot

**Comment by larshp** [comment]
It should look something like this:
![image](https://cloud.githubusercontent.com/assets/5888506/22817203/3361f3a2-ef66-11e6-90ae-9c6e37a82c2a.png)

In stage:
![image](https://cloud.githubusercontent.com/assets/5888506/22817206/375442ee-ef66-11e6-8343-904b0d887466.png)

The files can be added or removed:
![image](https://cloud.githubusercontent.com/assets/5888506/22817213/401de420-ef66-11e6-89bf-b053e07cb8ac.png)

**Comment by prashantagl** [comment]
For me its looking like below.  I see Add button against the files which I want to delete, the files which I want to add against that I see ignore or remove button. Please see below screen shot

![sc2](https://cloud.githubusercontent.com/assets/25575475/22817260/43c82974-efba-11e6-85cd-f63074d839e7.JPG)

**Comment by larshp** [comment]
ahh, I got the scenario wrong, you want to move ZGITHUBTEST to the "prash" folder

abapGit uses the package structure to derive the folders, so in your ABAP system if you create a new package "ZABAPGIT_PRASH" as subpacage of "ZABAPGIT" and move ZGITHUBTEST  to the new package

**Comment by prashantagl** [comment]
thats correct. But the thing is that we can not have so many packages created as our landscape is shared across multiple projects so one object may be shared by different project. So I think moving objects in multiple packages will create lot of confusion.

Is there any alternate way for this?

**Comment by larshp** [comment]
alternatively a starting folder can be defined in `.abapgit.xml`, eg. `<STARTING_FOLDER>/src/</STARTING_FOLDER>`
if you want to have all the objects inside the "src" folder

in abapGit there is a 1:1 relation between top packages in SAP and git repository. So if you want to store all the code across the landscape in 1 git repository, all objects must share a common toplevel superpackage.

**Comment by larshp** [comment]
if you have packages:
ZGIT_FOO
ZGIT_BAR
And want contents of both packages in a git repository, then a superpackage can be introduced
ZGIT superpackage to ZGIT_FOO and ZGIT_BAR.

also see https://github.com/larshp/abapGit/issues/521 for folder naming strategy, as currently there are requirements for how the packages are named

**Comment by prashantagl** [comment]
In case of new packages we can take care of package naming conventions but as our system is very old so it is very high risk to rename the packages.

Currently we have 3 Development Landscapes(one for BAU and others for projects), and in one landscape multiple projects running. There is possibility that multiple people will be working on same abap object in different landscape. So do you think these kind of model will be supported by ABAPGIT from code backup point of view?

Only couple of days back I started exploring this tool, so need some inputs from your side.

**Comment by larshp** [comment]
I'd recommend testing abapGit with 1 package, just to see how it fits into your organization. If it works then wait for https://github.com/larshp/abapGit/issues/521 to be implemented, and then introduce a super package(see "FULL" logic description).

You can choose to have 1 repository per system, or 1 branch per system, both having pros and cons.

**Comment by prashantagl** [comment]
I have tested with one package -> one repository -> one dev system. It all works fine.

But we can not use one package -> 2 repository -> one dev system. It says package is already in use which is logical. we can not have same objects in 2 different repositories for same dev system.

**One more question:** 
Out of 100 objects in one package, we select 4 objects to be committed in GitHub, is there any way to hide other objects in abapgit which we havent committed to GitHub?

**Comment by larshp** [comment]
2 repositories: hmm, why have the same code in 2 different repositories? 

hide other objects: no, if the 4 objects are logically part of the same development I'd suggest moving these to a separate package

**Comment by prashantagl** [comment]
Exactly which plugin shall we use to enable abapgit for the gateway services?

**Comment by larshp** [comment]
gateway services: https://github.com/larshp/abapGit-Plugins

**Comment by prashantagl** [comment]
Do we need to install all objects from abapGit-Plugins? Or is there any specific you want to hilight?

![image](https://cloud.githubusercontent.com/assets/25575475/22997364/2b1a1976-f426-11e6-8a46-3e2d1f4c83f3.png)

**Comment by larshp** [comment]
install all, just clone the objects into the system using abapGit

**Comment by prashantagl** [comment]
Thanks it worked well
