### ISSUE TITLE
Stage page UX improvements, filtering

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#610]
A couple of UX improvements to the stage pare are on the way. So I publish it for discussion. Comments and constructive suggestion are more than welcomed :) Everybody is invited. 

## User perspective

1) The main thing is filtering and add/reset selected. Now you can add part of file name to the search box, hit enter and only matching items will remain on screen, The filter pattern is highlighted. Filtered items can be add or reset massively respecting the current filter. (Actual commit cares about actual item status not the filter !!!)

![image](https://cloud.githubusercontent.com/assets/15635498/22852780/a0335c96-f04c-11e6-834d-93dc508606e8.png)

2) To supress the potential confusion with Filter vs Status, the counter was added to Commit action - to see number of files selected.

3) "All diffs" action moved to upper menu - it is a better place because it is a page-scope command.
4) Diff per item removed - instead you can click the file name with the same result.
5) Some css improvement, in particular to last-changed user
6) A more global stuff - now errors JS initialization would be more visible, not only in the "JS: OK" debug output (if anyone saw it at all :)

![image](https://cloud.githubusercontent.com/assets/15635498/22852781/a611e100-f04c-11e6-8b66-2dd94efc2ae1.png)

## Internals

Some internal decisions to JS code: mainly driven by the idea that if JS fails to init then UI should not show JS related controls:
7) handlers are initialized in JS
8) commands add/reset in items are rendered in JS

One point here: Initial "Add all and commit" is not JS - just a pure sapevent button. So if all JS init fails you're still able to commit something. This was kept intentinally.

## Doubts and questions

9) is filtering by last-change-user needed ? I'm a bit reluctant (lazy to implement) but could be a nice feature
10) stupid IE in SAP GUI hides "cross" in search typed field. Not sure what to do with it. Select all + hit Backspace work just fine but still a bit less conveninent. Do we need an explicit button to clear the filter ?

![image](https://cloud.githubusercontent.com/assets/15635498/22852784/acc7e418-f04c-11e6-9df7-35bc68215650.png)

11) The whole table looks a bit confusing to me in case there are ignore/remove section. "Add all" button concerns "add" section ONLY. I have a feeling of incomleteness. Not sure what to do, creativity exhaused :) Maybe it is a good idea to separate these tables ...

![image](https://cloud.githubusercontent.com/assets/15635498/22852823/817fd094-f04d-11e6-9bc5-a3475dd30ca0.png)

12) would be nice to add object type as an additional column ? It is not easy readable from file name.
13) filter field is not well placed imho. The best look would be to put it on the action (commit) line but align right so it matches the right table edge. But it seems to be quite difficult: the below table size is dynamic - so the action line would shift filter to the very right side of the PAGE. Also out of ideas here for the moment. 

The code to test is here: https://github.com/sbcgua/abapGit/tree/ux-experiments

P.S. Some improvement to Diff page are also planned ;)

**Comment by larshp** [comment]
so much text 😄 will look into it tomorrow or early next week, working on some code today

**Comment by sbcgua** [comment]
Yeah, I guess this can be called a "long-read" :) This is why I put some illustrations.   
No prob anyway, no rush with this one :)

**Comment by larshp** [comment]
Implementing support for DDLS was easier than expected(#425),

9: no, changed by does not work for all objects yet, we can always add it later

10: it is better than what we have now, we can add it later if needed/find a solution in a separate issue

11: add a "ignore all" and "remove all" for the remote files? note that the remote unrecognized files might also be abap files
![image](https://cloud.githubusercontent.com/assets/5888506/22853346/6873dcba-f054-11e6-939b-9aa2be0ad698.png)

12: one step at a time, we can add it later

13: hmm

**Comment by sbcgua** [comment]
9: sounds convincing.

11:. Sorry, it was an outdated screnshot (from browser). Here is the real from AG:

![image](https://cloud.githubusercontent.com/assets/15635498/22853605/f71a8c8e-f063-11e6-9922-6569ee11781d.png)

So title is OK I guess. Commands: yeah, this is logical to have also mass ignore and remove (now just reset there). I'm just worried that it will look too long and bulky. Would "ign/rem/reset" be fine ? Or maybe make some I/R/X with some wider click area around ??

Anyway the main question (11) remains: "Add all" button is confusing. (although i don't have any better ideas)

12: Ah, it is really easy. 1-2% of what's done ... Just tell if it looks useful :)

**Comment by sbcgua** [comment]
mass ignore/remove added, 12 added. Also rearranged columns so that Action and Status are near. I think this is more convenint as no need to run eyes left-right. 

![image](https://cloud.githubusercontent.com/assets/15635498/22882130/54386ba4-f1f2-11e6-9505-8a45c6461fe9.png)

Check a bit on 10, but seem to be not that easy to find an elegant and light solution. So will do somewhat later.

**Comment by sbcgua** [comment]
:tada:

Now waiting for feedbacks ...

Remaining points from my side:
- [ ] Click on cell should also perform the command (links are small and incovenient)
- [ ] Performance - on 500+ files search is notably slow (just tried on our 400 object project). Some room for improvement. 99% is that it is because of keeping values in DOM (not sure what to do with this for the moment). Below 100 object though it is fast and clean, surely faster than re-rendering
- [ ] Implement cancel cross button in search field (maybe, if prove to be inconveninent)
- [ ] Reconsider search field position (see above PR for detailsed discussion) (maybe)

**Comment by larshp** [comment]
Performance: how long does it take? I guess it is still faster than clicking "add" 400 times manually?

**Comment by sbcgua** [comment]
2 sec. per search/cancel. UX Scientists claim that user perceive >0,5 sec. reaction and non fluent interface ... just kidding. I guess it is OK. I occasionally faced the performance issue because I just synced our 400obj project to the new XML format. There were 750 files and slow reaction was unexpected. It is even not about the speed of search but about the fact that nothing happen on screen during 2 sec. This is not the typical case however. Still might be an interesting exercise when I find some time for that.

**Comment by larshp** [comment]
perhaps add a progress indicator in javascript for the javascript, not sure if this is easy or difficult

**Comment by sbcgua** [comment]
I was also about some spinner. Well, probably will have a look on it on the weekend.

**Comment by sbcgua** [comment]
BTW does the new layout fill convenient ? (I caught myself thinking that I got used to the old one and the newer feels unusual)

**Comment by larshp** [comment]
its okay, as anything else it takes a bit to getting used to

**Comment by sbcgua** [comment]
![image](https://cloud.githubusercontent.com/assets/15635498/23095747/c109323a-f617-11e6-87a0-f87c7ea25205.png)

So:
- now you can click on the whole cmd cell (if the command is single there). No need to aim small links
- mass commands a bit more accurate
- filter field moved to the right, table size fixed (this might have rare downsides)
- a bit improved JS-fail-banner text (for the case of long rendering) and potentially fixed JS issue mentioned in #629 (not sure, just stumbled upon a bug and fixed it - commitAll button was hidden in no-local-files case and so there was no element with appropriate ID on the page)
- and finally the filter performance rised ~10x. Spinner is not needed (and also not that easy to do for this case)

**Comment by sbcgua** [comment]
I guess can be closed for now.
