### ISSUE TITLE
Dump: Function module "POPUP_GET_STRING" not found

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#615]
include ZABAPGIT_2FA

**Comment by flaiker** [comment]
Hmm, is there any way to see which release a function module was released on?

**Comment by larshp** [comment]
was thinking to change it to POPUP_GET_VALUES, we use this FM in an other places in abapGit

**Comment by flaiker** [comment]
Sure no problem. POPUP_GET_STRING is in some weird package anyways that does not seem to be intended for reuse, I just noticed.

**Comment by larshp** [comment]
fixed in PR https://github.com/larshp/abapGit/issues/626
