### ISSUE TITLE
Translation for object TRAN

### ISSUE THREAD

**Issue by TheWirtschaftsmann** [larshp/abapGit#616]
Changes to serialize/deserialize translations for transaction code names (object TRAN) are not yet supported, but they are on the way.

Before the implementation is completed, I would like to clarify the naming conventions. As for previously implemented objects, two methods will be added serialize_texts( ) / deserialize_texts( ). Would it be ok, if I use name lt_tpool_i18n for internal table with translations (existing approach) or should I use something like lt_tstct (referencing actual table that stores translations)?

**Comment by larshp** [comment]
naming is difficult, so I do not have any strong opinions on this. Names for internal variables are easy to change in the future.
