### ISSUE TITLE
"add all" feature

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#62]

**Comment by larshp** [comment]
or click add for those to add, and then commit after this

it will most likely require refactoring, and creating the repository object/class

**Comment by se38** [comment]
or: select objects (checkbox) and press "Add selected"

**Comment by larshp** [comment]
yeah

The repository object has recently been refactored. Thinking to do it much like command line git, click "add" multiple times to stage the files, then click commit when files have been selected

**Comment by se38** [comment]
I've just created a new git repository with 83 objects. I would prefer checkboxes (with a button "select all" which just triggers all other checkboxes, nothing else).
Reason: abapGIT has another "glitch" -> it also selects already deleted objects. The TADIR entry (the source of the list) will only be deleted if the transport order is released. I had around 90 entries in my list, where I wanted only 85 to be added to the new repository.

**Comment by larshp** [comment]
I've created issue #135 for fixing the glitch

**Comment by larshp** [comment]
new staging screen fixes this issue, click "add all and commit", or files can be selected individually.
Screen design might change
closing issue, feel free to reopen or create a new issue

![image](https://cloud.githubusercontent.com/assets/5888506/15273556/8dab0e82-1a9d-11e6-8293-6db8bd522326.png)
