### ISSUE TITLE
"Force Stage" not possible

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#623]
test repository: https://github.com/larshp/Empty

![image](https://cloud.githubusercontent.com/assets/5888506/22943654/a357509a-f2ee-11e6-876a-3c4d982c2273.png)

**Comment by sbcgua** [comment]
Force stage is possible only in synced state for the moment
https://github.com/larshp/abapGit/blob/master/src/zabapgit_view_repo.prog.abap#L298

`IF iv_rstate IS INITIAL AND iv_lstate IS INITIAL.`

Easy to fix, but what's the idea behind ?

**Comment by larshp** [comment]
in this case there are changes to the local `.abapgit.xml` and a file `foobar.txt` which is not ignored

I want to be able to ignore `foobar.txt`, and commit the changes to `.abapgit.xml`

**Comment by larshp** [comment]
tested ok, 

![image](https://cloud.githubusercontent.com/assets/5888506/23013092/85b0f88e-f429-11e6-8785-a7c203bcff87.png)
