### ISSUE TITLE
Branch Overview Short Dump

### ISSUE THREAD

**Issue by prashantagl** [larshp/abapGit#627]
Hi,

Recently we have installed abapgit, one of its feature Branch Overview when we select this option then we are getting below shortdump.

![image](https://cloud.githubusercontent.com/assets/25575475/23003854/76de778c-f447-11e6-8041-751832445ee9.png)

![image](https://cloud.githubusercontent.com/assets/25575475/23003882/981dbe94-f447-11e6-8660-87e1a1dec11e.png)

**Comment by larshp** [comment]
can you provide the value of variable `ls_raw-author` ?

**Comment by prashantagl** [comment]
Valie is  "prashantagl <PChaudhari3@agl.com.au> 1487204566 +1100"


![image](https://cloud.githubusercontent.com/assets/25575475/23011233/f01bae9a-f473-11e6-821f-1fd3d4661028.png)

**Comment by larshp** [comment]
hmm, regex seems to be okay, https://regex101.com/r/Bj3ghQ/1

try copying the regex to a small test report to see what is happening, there might be some special characters in the string?

**Comment by Sirius-A** [comment]
Looks fine in program `DEMO_REGEX_TOY` as well.

![image](https://cloud.githubusercontent.com/assets/11653812/23019958/ffe25466-f444-11e6-8d60-d695d3e77dbc.png)

**Comment by prashantagl** [comment]
Dont know whats wrong, there are no special characters in the name

**Comment by larshp** [comment]
hmm, can you try reproducing the issue in a public repository? just add some dummy objects to a new public repository on github

**Comment by prashantagl** [comment]
Hi Lars.

I have reproduced same error, uploaded some dummy program into prashantagl/Demo public repository. When I go to ABAPGIT and select branch overview i get same shortdump



![image](https://cloud.githubusercontent.com/assets/25575475/23153130/de4815c4-f85a-11e6-9dc0-cd4f4ea5a32b.png)

**Comment by larshp** [comment]
works for me, see below. Can you try updating abapGit to the latest version? Looking at the objects it looks like the version you have is at least a month old, however I am not sure it will fix the problem.

![image](https://cloud.githubusercontent.com/assets/5888506/23153311/16c9b7a2-f808-11e6-9863-a08fd0456671.png)

**Comment by prashantagl** [comment]
last week I updated code with latest one, but I was getting short dump in the staging option...I will try again today and let you know

**Comment by prashantagl** [comment]
Hi Larshp - I have one more question.

Scenario is I have created branch 1 from master branch. I make all my changes in Branch 1 and create transport to save those changes. When I release the transport  and check my program in se38 I can see my branch 1 changes there. Is it expected behavior.

However if I navigate thro ABAPGIT for master and Branch 1 changes, in master branch I dont see my Branch 1 changes, I can only see my changes in Branch 1 which is correct.

Can you please clear my understanding here how master and branches will behave when we release transport in which captured the branch 1 changes.

Cheers!!!

Prashant

**Comment by larshp** [comment]
abapGit does not integrate with the SAP transport system, so nothing will when a transport is released

(have been thinking of some features regarding this, but need to do more thinking)

**Comment by prashantagl** [comment]
Is it expected that when we create branch and make our changes in branch. and when we check the program via separate SE38 transaction(instead of navigating from abapgit), we should see changes from Branch or we just see master branch code there?

**Comment by larshp** [comment]
in SAP there is always only 1 version of each program active

If you want to work with branches, you decide how to use it, abapGit does not decide/help how to do branching(except for implementing the git protocol).

From my point of view each git branch can be a separate SAP system, this is they way SAP handles branching.

**Comment by Sirius-A** [comment]
Issue regarding multiple active versions: #382 
Please note the **crazy** label :blush:

**Comment by prashantagl** [comment]
thanks this helps
