### ISSUE TITLE
Add support for git flow 

### ISSUE THREAD

**Issue by Sirius-A** [larshp/abapGit#628]
Hello 

[Git flow](https://github.com/nvie/gitflow) is a collection of git extensions to streamline working in a[ multi branch workflow](http://nvie.com/posts/a-successful-git-branching-model/). It is already adopted in a lot of git clients. 

I think that supporting git flow in abapGit would benefit it as well. What do you think? 

I'm aware that this is a rather big change/ feature request. Maybe it could also be serverd as a plugin.

If you need more information on git flow or how it could be integrated within abapGit free to ask :smile:.

BR
Fabio

**Comment by larshp** [comment]
Yeah, can you explain more on what you have in mind? Can you create a description of the atomic operations that are needed?

I have not used `git-flow`, but a function like `feature start <your feature>`, I guess corresponds to creating a branch? And `publish` corresponds to merging the branch?

abapGit implements most of the basic git operations, so perhaps git-`flow` can be built on top of this?

**Comment by Sirius-A** [comment]
Sure.
I will add some screenshots from [GitKraken](https://www.gitkraken.com/features) to make it easier see what I'm talking about.

Git flow is designed to make it easier to work with `feature-, hotfix-` and `release branches`.

Git flow works on a per repo basis. 
When you start using git flow in a repo, you define how your branches should be named:

![image](https://cloud.githubusercontent.com/assets/11653812/23026630/25d01ec0-f462-11e6-81ed-403aec4fd69e.png)

After that, instead of creating and merging branches manually, git flow offers you to do that via `feature start <your feature>` and  `feature finish <your feature>`. 
![image](https://cloud.githubusercontent.com/assets/11653812/23025058/d86587e2-f45c-11e6-8818-997bf119ff88.png)
![image](https://cloud.githubusercontent.com/assets/11653812/23026097/7c234506-f460-11e6-8401-4fdf3c94dc55.png)


Here is a list off the git flow operations:

- **Init**: Define branch naming scheme
- **feature start:** create new branch named feature/XYZ  (usually starting form `develop` branch)
- **feature finish:** merge branch feature/XYZ into develop branch
- **release start:** create new branch named release/v1.5.1 (usually starting form `develop `branch)
- **release finish:** merge branch release/v1.5.1 into `master `branch and create a tag for the new version number
- **hotfix start:** create new branch named hotfix/ABC (usually starting form `master` branch)
- **hotfix finish:** merge branch hotfix/ABC into `master `branch and create a tag for the new version number

[This article](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/) should make it easier to understand each command.

**Comment by larshp** [comment]
cool, thanks

The following basic operations are currently not implemented in abapGit:
* conflict handling while merging
* tagging

I'd suggest starting with these 2 things, once they are implemented then adding the flow operations should be easy 😄

**Comment by Sirius-A** [comment]
Sweet!
I'll create separate issues when I find time to work on one of the two.

>[..] then adding the flow operations should be easy :smile:

Oh the amount of times I said something like that only to regret it later :blush:

**Comment by larshp** [comment]
merge is currently possible under the "Branch Overview" page, see https://github.com/larshp/abapGit/blob/master/src/zabapgit_page_merge.prog.abap

nothing is implemented with regards to tagging

**Comment by larshp** [comment]
tags, https://github.com/git/git/blob/master/Documentation/technical/protocol-capabilities.txt#L216

**Comment by larshp** [comment]
the basic actions are implemented: tagging, switching branches, merging

anything else missing?

**Comment by Sirius-A** [comment]
Great! Yup all the functionalities are part of abapGit now :tada:

**Comment by larshp** [comment]
closing
