### ISSUE TITLE
Switch to Branch with long Name results in shortdump 

### ISSUE THREAD

**Issue by rednose84** [larshp/abapGit#631]
HI,

if a branchname is to long, then it is not possible to switch to this branch. Shortdump :-/ Because the Name fromthe Popup doesn't match the name in the internal table.

![image](https://cloud.githubusercontent.com/assets/5937077/23091751/6ad052ea-f5bd-11e6-8ac1-ef2bfbd9ff1d.png)

regards Micha

**Comment by rednose84** [comment]
quick & dirty fix

```
 "READ TABLE lt_branches WITH KEY display_name = <ls_sel>-varoption ASSIGNING <ls_branch>.
  Loop at  lt_branches assigning <ls_branch> where display_name cp '*' && <ls_sel>-varoption && '*'.

  endloop.
```

**Comment by larshp** [comment]
thanks, feel free to submit a pull request

just make sure the CP kicks in only with long branch names, eg. if there are 2 branches:
* foobar
* foo
and "foo" is selected, then it should not choose "foobar"

**Comment by larshp** [comment]
@rednose84 try this: https://github.com/larshp/abapGit/pull/637

**Comment by larshp** [comment]
now merged into master, can we close the issue?

**Comment by rednose84** [comment]
Yeah sure ;)

Thx a lot

Am 22.02.2017 um 17:18 schrieb Lars Hvam <notifications@github.com<mailto:notifications@github.com>>:


now merged into master, can we close the issue?
