### ISSUE TITLE
Eclipse/ADT support

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#636]
This question comes up every now and then, so lets add an issue for it and discuss here.

Pull requests welcome 😄 

The abapGit code can currently be hooked into like this:
```abap
  CREATE OBJECT lo_repo TYPE ('\PROGRAM=ZABAPGIT\CLASS=LCL_REPO_OFFLINE')
    EXPORTING
      is_data = ls_data.
```
but I guess this approach is not very nice if a lot of integration is to be made.

**Comment by flaiker** [comment]
Here are some ressources for the ADT SDK:
- https://archive.sap.com/documents/docs/DOC-40668
- https://blogs.sap.com/2014/08/27/creating-a-abap-in-eclipse-plug-in-using-the-adt-sdk/
- https://blogs.sap.com/2014/08/31/creating-a-abap-in-eclipse-plug-in-using-the-adt-sdk-part-2/

**Comment by larshp** [comment]
also see https://github.com/larshp/abapGit/issues/773

**Comment by larshp** [comment]
follow https://github.com/abapGit/ADT_Backend and https://github.com/abapGit/ADT_Frontend
