### ISSUE TITLE
Authorisations in abapGit

### ISSUE THREAD

**Issue by prashantagl** [larshp/abapGit#640]
Hi,
We are planning to add some security authorizations to different actions in ABAPGIT.

For example, only development should be able to create the branches etc.

Any idea how to proceed with that? or we can add it at user-command of create branch action?

Let know if you come across something similar.

Br,
Prashant

**Comment by sbcgua** [comment]
Just an opinion: auth for git action should be not controlled at git client but at git server. I can create branches from else where - no need for AG. 
Also controlling auth for a developer in development system in a custom tool ... if developer wants to overcome it, no one will ever find out. Does not make much sense. Just imho.

**Comment by sbcgua** [comment]
Also: does the auth check should check user or user+repo ? (imho it is probably the latter)

**Comment by prashantagl** [comment]
Currently there are no SAP standard authorisation objects used for any of the functions in ABAPGIT as its an open source code, we would like to add authorisations to limit the access to below functionalities:
01.	Authorisation to limit the Branch creation/deletion in abapgit
02.	Authorisation to limit the Advanced functions(Reset local/Change remote/Update local checksum/Remove/Uninstall etc.) from abapgit

We have multiple development landscapes which will share the common repositories. We have created one repository for one SAP package.

So we want to avoid scenarios like, developer from one landscape deletes the branch of other development landscape etc. or they just delete the branch created for another landscape.

**Comment by larshp** [comment]
I'm worried that if authorization checks are added directly in abapGit it might break functionality for users that now has access to everything. Authorizations are also very dependent on the processes that you want to implement in your landscape. And I would like not to generate additional objects when installing abapGit, as I think reusing standard auth objects in this case is difficult.

So, I'll suggest adding some "user-exits" for these kind of checks. Eg. in abapGit branch deletion add something like:
```abap
PERFORM branch_delete IN PROGRAM zabapgit_exits IF FOUND USING lv_branch_name CHANGING lv_abort.
```
that way you can add authorization checks in eg. BRANCH_DELETE, and also use custom authorization objects if needed. And it can also be used for other things.

**Comment by prashantagl** [comment]
yes, this is what we are planning. To use the custom authorization objects and thanks for pointing out the use of user exits. I will certainly give it a try and let you know how it goes ;-)

**Comment by larshp** [comment]
it is not implemented yet, it is just a suggestion on how to proceed

**Comment by prashantagl** [comment]
I understood that, I meant we will implement it :-)

**Comment by sbcgua** [comment]
Arch suggestion to minimize impact on the core code and stay incline with current runtime style:

- Adding `INCLUDE zabapgit_global_userexit IF FOUND` to main prog.
- Adding some `class lcl_auth create private` to utils with one method: `check( iv_auth, iv_params OPTIONAL )` which returns boolean
- Adding `lif_auth_check` (interface) with similar method
- `lcl_app` should create an instance of `lcl_auth` and expose as static `auth()` method, `lcl_auth` constructor should `PERFORM create_auth_validator IF FOUND.` - a function which would stay in `zabapgit_global_userexit` and return an instance of `lif_auth_check`. Thus `lcl_auth->check` should do 

```abap
IF mi_auth IS BOUND AND mi_auth->check(...) = abap_false.
  raise |Auth failed: { iv_auth }|.
ENDIF. 
rv_result = abap_true.

```

Thus there will be minimal additional conditions in code to apply checks. E.g. to check auth for branch switching you would add just one line somewhere in services:

```abap
lcl_app=>auth()->check( 'AUTH_BRANCH_SWITCH' ).
```

P.S. `iv_params` in `check()` is for some potential complications of specific auth rule, a reserve for future.

**Comment by larshp** [comment]
Having a class based setup is a good idea

But I would like not to limit this to authorizations, ie. the naming can be done without "auth" but just the event name "branch_switch" or "switch_branch". I think the user exit approach can be used in a lot of different places for a lot of different reasons.

something like:
lcl_app=>exits()->branch_switch( lv_branch_name ).
which can throw an exception. Note that in this case there are no constants, so where-used can be used when maintaining the program.

one concern:
if eg. lif_exits is implemented in zabapgit_global_userexit, and another method is added in lif_exits, then I guess there will be a syntax error when pulling the latest abapGit?

**Comment by sbcgua** [comment]
Imho, i would not mix all user exits. We don't know how many auth check there will be and how many other exits. Keeping them together might lead to a very messy and packed interface with time. 
 Building a universal user exit interface can face many complexities and refactorings in future :) Also auth is quite distinct feature to separate (imho).

`branch_switch` vs `check( 'BRANCH_SWITCH' )` - well this is arguable, both approaches has pros/cons. Separate methods can consume more specific params instead of faceless `iv_param` string (if this needed at all though!). And `check` is more universal and leaves all internals to user exit. If there will be a bunch of auth methods and we will want to refactor them - it may bring activation errors indeed. You decide :) Even in SAP though, auth_check FM is unified.

**Comment by larshp** [comment]
hmm 😄 

let just start out with something, we can always refactor when we know more about the problem. @prashantagl feel free to submit a PR take the key points from above that you find useful, code counts 🚢

**Comment by prashantagl** [comment]
Hi,

Can you suggest how do I hide the Uninstall Option from Advanced menu in ABAPGIT.
I find this function very dangerous. I just want to hide this or I dont want anything to happen in case developer mistakenly use this function.

Regards,
Prash

**Comment by larshp** [comment]
Hi,
There is a possibility to write protect a repository, https://github.com/larshp/abapGit/wiki/Write-protected-repository
This way code can only go out of the system

**Comment by prashantagl** [comment]
What I meant is that, I am looking for different options to restrict the different functions depending on the role. For ex. Only dev lead should be able to see option to branch creation. Developers should not have authorization to create/delete branch. Developer should able to only view Branch overview and branch switch option. Like this I am planning to control the authorizations using custom authorization objects.

**Comment by larshp** [comment]
okay, then we need to implement the authorization approach as discussed earlier in this thread

**Comment by larshp** [comment]
@prashantagl can you take a look, it has been merged to master now

**Comment by larshp** [comment]
closing, please raise a new issue if/when authorization exits are needed in more places
