### ISSUE TITLE
Does program ZABAPGIT modify/update/delete any SAP standard objects

### ISSUE THREAD

**Issue by prashantagl** [larshp/abapGit#642]
Hi Larshp,

Want to check with you, in anyway the code from ZABAPGIT modify/update/delete any SAP standard objects?

Br,
Prashant

**Comment by larshp** [comment]
no, ZABAPGIT is 100% custom code

There is a guide here: https://github.com/larshp/abapGit/wiki/Uninstalling-abapGit which describes how to uninstall abapGit, it lists all the objects that abapGit uses

**Comment by prashantagl** [comment]
Thanks for confirmation
