### ISSUE TITLE
Freez userid/email id field in staging option

### ISSUE THREAD

**Issue by prashantagl** [larshp/abapGit#645]
any existing plugin to pre populate and freez the userid and email id field at the time of staging?

These are editable fields, any one can put anyother developers name at the time of staging.

Might be new feature if not existing

**Comment by larshp** [comment]
no, no feature for this. There is no default authentication methods in git, in a normal git scenario on eg windows, anyone can put anything in `.gitconfig`. If it is developers that are using abapGit they can probably also easy manipulate the variables to a different username, just like it is possible when editing SAP standard objects.

Easiest solution is to trust your developers 😄 

Or alternatively wait for https://github.com/larshp/abapGit/issues/358 to be implemented
