### ISSUE TITLE
Connection issue with proxy authentication

### ISSUE THREAD

**Issue by prashantagl** [larshp/abapGit#646]
Hi,

We are trying to clone a repository from ABAPGit program but our SAP server allows internet connection via proxy only with user ID/password based authentication.

Getting the error as per attached screenshot.

Could you please assist in this regard.

Cheers.
![image](https://cloud.githubusercontent.com/assets/25575475/23289936/5125f7bc-faa1-11e6-801b-dd641ae878e8.png)

**Comment by larshp** [comment]
in your case, is there a general username + password that can be used by everyone to access the proxy, or is it per user?

**Comment by prashantagl** [comment]
Hi, 

Thanks for your response.

It is per user.

Regards.

**Comment by larshp** [comment]
okay, solution proposal:
Add a checkmark in the proxy settings if proxy authorization should be used, and when making the HTTP call show a popup for username and password. Store username and password in memory only, not in database.

**Comment by prashantagl** [comment]
Do you mean we need to change the code or is there any checkmark to enable username and password?

**Comment by larshp** [comment]
above is just a proposal, not implemented in the code, feel free to submit a PR. It is difficult to test as it requires a proxy with user authentication

**Comment by prashantagl** [comment]
can you help in which part of the code it is making the HTTP call? It looks like I have to add the proxy authentication

**Comment by larshp** [comment]
try adding the headers somewhere around https://github.com/larshp/abapGit/blob/master/src/zabapgit_http.prog.abap#L395

**Comment by liamgp23** [comment]
we tried coding option but didn't work, spent lot of time. Finally we have to open the port and make it work ;-). Keep it simple

**Comment by prashantagl** [comment]
Hi Guys,

I managed to add user id/password fields on selection screen and then used them to authenticate the proxy.

How do I share the code with you?

Regards,

**Comment by larshp** [comment]
cool, see

https://help.github.com/articles/fork-a-repo/
and
https://help.github.com/articles/about-pull-requests/

**Comment by SaschaWaechter** [comment]
This would be very helpful, we also need Proxy Authentification.

Any Idea when everyone can use the Feature?

**Comment by larshp** [comment]
@prashantagl can you share your solution? Just put the code somewhere on github or submit a pull request if you like

**Comment by prashantagl** [comment]
was this useful?

I created new selection screen where in developer will enter their LAN credentials then I use it to authenticate proxy.

Another way could be you can get generic credentials to authenticate proxy from your infrastructure team and then you can add user id and password fields in the proxy details section and then use them to authenticate the proxy.

**Comment by larshp** [comment]
@prashantagl thanks, I hope someone will pick it up and submit a PR. I guess we should add a tickmark in Advanced -> Settings if proxy authorization should be enabled or not.

**Comment by larshp** [comment]
@SaschaWaechter @prashantagl you can test the feature in PR https://github.com/larshp/abapGit/issues/700

**Comment by larshp** [comment]
did you have time to try it out? it has been merged to master now

**Comment by prashantagl** [comment]
Sorry didnt tried it. Will try it today and let you

**Comment by larshp** [comment]
closing, create new issue in case of problems
