### ISSUE TITLE
Folder logic / sub-package naming

### ISSUE THREAD

**Issue by pfaller** [larshp/abapGit#647]
Hi Lars, 

I ran into the "unexpected package naming" error, since we have now subpackages where the name is not prefixed with the parent package's name. I know this is currently the intended behavoir (I've seen your comment at https://github.com/larshp/abapGit/blob/master/src/zabapgit_folder_logic.prog.abap#L98) - but would this be difficult to change? 

Background why we don't want to use prefixes: We've now moved our code from Z to our new /CQSE/ namespace. We'd like to have one top-level package what is synchronized with abapGit. 
Before we had a top-level package ZCQSE which worked well es prefix for the sub-packages. Since package name /CQSE/ ist not possible, we'd use something like /CQSE/ALL or /CQSE/ABAP_DEV instead for our repository root package ... but obviously we wouldn't like to use this name again in every package name.  

If the modification wouldn't be too elementary I could also try out it on our fork of abapGit. But maybe you could give me a few hints what must be changed for that. 

Cheers,
Christian

**Comment by larshp** [comment]
Hi,
FULL folder/package naming is supported in abapGit, implemented 7 days ago, https://github.com/larshp/abapGit/pull/624. This will translate the package names 1:1 to folders.

See example in repository https://github.com/larshp/PROG

Currently there is no easy way to change this(https://github.com/larshp/abapGit/issues/630 planned), so you have to set the logic to FULL in the remote repository not using abapGit. Like this: https://github.com/larshp/PROG/commit/77bfc69075caf79e0515d0a58c250a7fa029a354

**Comment by larshp** [comment]
I do not know your exact setup, but looking at this from the outside it might make sense to have 1 git repository per solution/product, eg.(just found some product names on your homepage, not sure if they are ABAP related):

- /CQSE/TEAMSCALE
with subpackages /CQSE/TEAMSCALE_UI and /CQSE/TEAMSCALE_LOGIC
- /CQSE/CONQAT
etc.
- /CQSE/SIMULINK
etc.

But there might also be reasons to have
- /CQSE/ALL
with subpackages  /CQSE/TEAMSCALE + /CQSE/CONQAT + /CQSE/SIMULINK, and these subpackages follow the PREFIX format

The folder logic is implemented in https://github.com/larshp/abapGit/blob/master/src/zabapgit_folder_logic.prog.abap, it might make sense to add a new FOLDER_LOGIC option for the 2nd case

**Comment by pfaller** [comment]
Hi Lars, 

perfect, setting  FULL in .abapgit.xml worked! Many thanks!

About our packages structure: basically all our ABAP code is related to Teamscale (ConQAT uses just a subset) - the differentiation is more between what to be included in the main transport, and some further things which should under source control, too. We even placed two Z packages inside ... one if for Code Inspector Variants (which cannot be named in /../ namespace) and the other is for legacy proxies for earlier Teamscale version which expect e.g. RFC functions in Z namespace. But as everything belongs to Teamscale we'd prefer to have it in one Git repository. 

Thanks again, 
Christian
