### ISSUE TITLE
Increase length of commit message

### ISSUE THREAD

**Issue by Sirius-A** [larshp/abapGit#648]
Hello 

I like to use the [(Angular) conventional commit message format](https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md) and/or [emojis](https://gitmoji.carloscuesta.me/) for my commit messages. :blush: This means that they often get longer than 50 characters. :cry: 

Any concerns with increasing the commit message length to 100? 
(100 is the recommended commit length by angular --> [source](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format))

Thanks and best regards
Fabio

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit/blob/master/src/zabapgit_page_commit.prog.abap#L163

Guidelines https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project say 50 characters :o)

suggest adding this as a configuration option in Advanced -> Settings (https://github.com/larshp/abapGit/blob/master/src/zabapgit_page_settings.prog.abap)

**Comment by bigld** [comment]
Suggestion - two new setting parameters:
Commit Message
-max Comment Length (default 50 max 100)
-max Body Line Size (default 72 max 100)

**Comment by larshp** [comment]
sounds good to me

**Comment by larshp** [comment]
closing, merged in https://github.com/larshp/abapGit/issues/735
