### ISSUE TITLE
Warnings in yellow not red color

### ISSUE THREAD

**Issue by RainerWinkler** [larshp/abapGit#650]
When I change the package structure in a project where the folder logic is "FULL", I receive warnings in red color. I am used to the convention that errors are red and warnings yellows. This is common on SAP systems. Normally I would not have proceeded, as I assumed it to be an error.

Can the color be changed to yellow?

Cheers,
Rainer

**Comment by larshp** [comment]
sounds good to me

@sbcgua what do you think? You are our UI export 😄

**Comment by sbcgua** [comment]
@RainerWinkler could you pls post a screenshot ? Not clearly sure which error do you mean :)
Generally, yes, I even reserved yellow warning style in CSS. I just have some doubt about specific errors: imho package inconsistency **is** error. Or do I miss something ?

**Comment by larshp** [comment]
![image](https://cloud.githubusercontent.com/assets/5888506/23586486/e5356a00-0195-11e7-8437-1ab0773e5142.png)

I'd say errors(red) are usually when the user cannot continue. In this case the user can still work with the repository *shrug*

**Comment by sbcgua** [comment]
Looks like a simple fix. I'd just add `type` param to `lcl_log->add` and then change rendering a bit. Can do.
There are just 5 calls to log add at the moment - could you pls have a look which are warnings/which are error ? (or we can do it eventually when issue raised).

P.S. Interestingly now all are warnings in fact :))
```abap
METHOD add.
    FIELD-SYMBOLS: <ls_log> LIKE LINE OF mt_log.
    APPEND INITIAL LINE TO mt_log ASSIGNING <ls_log>.
    <ls_log>-msgty  = 'W'. " <<<<<<<<<
    <ls_log>-msgid  = '00'.
```

**Comment by larshp** [comment]
Can we change it to something like
```abap
IMPORTING
iv_text TYPE csequence
iv_type TYPE msgty OPTIONAL DEFAULT 'W'
iv_key TYPE msgid OPTIONAL,
```

`key` can be used for the unit tests, method `show` would have to be rewritten

note https://github.com/larshp/abapGit/pull/649 has to be merged first, guess there will be conflicts with file zabapgit_unit_test

**Comment by sbcgua** [comment]
Preview - mix of warnings and errors (ignore text, just see the color). Does it look OK ?

![image](https://cloud.githubusercontent.com/assets/15635498/23587320/36693f3e-01b2-11e7-9ded-88b8948a994a.png)

**Comment by sbcgua** [comment]
For the moment just added `iv_msgty default 'E'` so should be no conflicts.

P.S. E vs W - mmm, imho if not specified it is more an error ...

**Comment by larshp** [comment]
ok, can we change one of the icons so they are not identical, eg https://octicons.github.com/icon/flame/

**Comment by sbcgua** [comment]
Hmm good idea :+1:

![image](https://cloud.githubusercontent.com/assets/15635498/23587402/ccb64508-01b3-11e7-8349-5a79ca8014ae.png)

So if OK, I'll PR. Should I change just this message to warning or all ?

**Comment by larshp** [comment]
ok, just set all to warnings

**Comment by sbcgua** [comment]
I'll this one as error probably:

` ZABAPGIT_OBJECTS_IMPL              484         io_log->add( iv_msgv1 = 'Object type ignored, not supported:'`

PRing in a minute ...

**Comment by RainerWinkler** [comment]
Thank you for the fast response. The good point is, I was able to to change the package. And to solve my problems very fast by searching in the issues on github. And made a lot of successful pushes with ABAPGit this weekend :-)

**Comment by larshp** [comment]
@RainerWinkler try again, latest version

**Comment by RainerWinkler** [comment]
@sbcgua @larshp I just tried it. Looks fine :-) Thank you for the fast response. 
Having different icons is a good idea, so it is not only the color that makes the difference.
Shall I close the issue now?

**Comment by larshp** [comment]
yeah, lets close
