### ISSUE TITLE
UI: lcl_toolbar refactoring

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#656]
connected to #655 (as prepreq) and ready.

Mainly inspired by this: https://codepen.io/philhoyt/pen/ujHzd
So implemented, html and CSS is cleaner now + a couple of new features/sideeffects available

1) Dropdowns look like this now

![image](https://cloud.githubusercontent.com/assets/15635498/23812293/96d630a0-05e2-11e7-855a-f37bd6d3a33e.png)

2) Theoreticaly they support 3 levels menu. I didn't try. Might be usefull for future.

3) Items can have separator type (e.g. Filter menu in Diff + may be useful in future).

![image](https://cloud.githubusercontent.com/assets/15635498/23812333/ccf97d36-05e2-11e7-96cb-3e8425c4a2c3.png)

4) Lists may be "check box" lists. In fact just list with predefined icons but with cleaner API. E.g.

```
      ro_toolbar->add(  " Show/Hide files
        iv_txt = 'Show files'
        iv_chk = boolc( NOT mv_hide_files = abap_true )
        iv_act = c_actions-toggle_hide_files ).
```

Check box list can work with sapevents (grid options at main page) or with JS (filter at diff page). For the latter case there is a wrapper in common.js - `CheckListWrapper` - which simplifies hooks and action handling.

5) Repo grid menu move to repo toolbar (indeed looks cleaner)

![image](https://cloud.githubusercontent.com/assets/15635498/23812489/6c39aba0-05e3-11e7-9f1e-29610ee355fb.png)

6) minor tweaks around (save at DB edit page move upwards, css tweaks, etc, etc )

**Comment by sbcgua** [comment]
Let it hang here for a while. Unless there are bug and wishes I'll close in a couple of days.

**Comment by EduardoCopat** [comment]
This new UI style looks great 🥇 .

**Comment by sbcgua** [comment]
@EduardoCopat Thanks :)

**Comment by sbcgua** [comment]
I guess can be closed
