### ISSUE TITLE
select branch -> CALL SCREEN error

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#658]
Click "change remote", enter wrong url(something that does not exist), click "select branch" => results in error 
"CALL SCREEN (not modal) in modal dialog box not allowed"

![image](https://cloud.githubusercontent.com/assets/5888506/23821346/c893b39a-062f-11e7-8d28-46d16c7aa2f2.png)

**Comment by larshp** [comment]
hmm, this is actually not very easy to fix, when clicking "select branch" it tries to show the login+password dialog box, as github.com looks to see if the repo is private.

This error also affects all private repos, where the change remote -> select branch option triggers the same error

**Comment by mbtools** [comment]
The CALL SCREEN error does not appear anymore. If the URL is not correct, we return "HTTP 404, not found"

**Comment by mbtools** [comment]
@cawoodmonads send feedback to the contacts mentioned below 😉 

![image](https://github.com/abapGit/abapGit/assets/59966492/a9ba635f-db29-4331-8374-1a144fd47def)
