### ISSUE TITLE
UI: groups in repo list (burger button)

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#660]
I have a lot of repos and repo list looks crowded. I wonder if it is an issue for other users ? The idea is to make groups in "burger" button - like hobby, work, tests ... I think it was partially discussed somewhere (maybe here #401 with @nununo )

Unclear questions at the time being:

- how to assign a group to a repo? Having that groups should also be freely definable. Options in my mind: some button at individual repo toolbar (much like branches), some separate settings page (ugly imho), ??? (ideas depleted)
- how it should look like ? Options:

Separators like in filter on diff page

![image](https://cloud.githubusercontent.com/assets/15635498/23822249/09a83654-0652-11e7-8288-60ae046dc0c0.png)

... Maybe in several columns (though I'm not sure it is possible with CSS and I'd like to keep it pure formatting, without changes in html)

![image](https://cloud.githubusercontent.com/assets/15635498/23822277/ac3d2c4e-0652-11e7-8f75-374c910d1c26.png)

Or maybe 3-level repo list (but htne the whole list is not observed at a time)

![image](https://cloud.githubusercontent.com/assets/15635498/23822303/39caf3b6-0653-11e7-9b72-54feea0786de.png)

Or maybe make it customizable ... (???)

- One more question should the repo list grouping be per user or global

Opinions needed and appreciated ! :)

**Comment by nununo** [comment]
I definitely think this would be a nice feature if we believe that abapGit will be used more and more. Even more so when other open source projects start using it. I wish projects like abap2xlsx would adopt it.

**Comment by larshp** [comment]
I think we also need to consider the favorites approach vs. the burger icon. I rarely use the burger icon as I have the important repositories marked as favorites.

Another idea: have a page instead of the dropdown from the burger icon, this will make it scrollable

**Comment by sbcgua** [comment]
Hmm... I use both quite intensively. I keep favs list short but change it depending on current focus. And thus burger is also used a lot. This is why I miss some grouping. Separate page would be less usable imho - more click o reach the goal :)

Maybe: think towards keyboard shortcuts (like g-d in guthub) and show some bigger menu at the screen center ... or some search (like ctrl+shift+p in Atom or packagecontrol.io) ... Maybe some coloring instead of named groups ...

**Comment by larshp** [comment]
closing
