### ISSUE TITLE
CSS favorites list, BG mode repo not aligned

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#661]
![image](https://cloud.githubusercontent.com/assets/5888506/23845842/add8cdaa-07ca-11e7-83a9-fa7a821fe2f9.png)

**Comment by sbcgua** [comment]
Hmm strange issue imho. Anyway fixed (PRing)

For history:
http://stackoverflow.com/questions/1530685/html-sup-tag-affecting-line-height-how-to-make-it-consistent
http://stackoverflow.com/questions/27475542/correcting-sup-sub-line-height
https://css-tricks.com/snippets/css/prevent-superscripts-and-subscripts-from-affecting-line-height/

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapGit/issues/662
