### ISSUE TITLE
Slack ?

### ISSUE THREAD

**Issue by tiefox** [larshp/abapGit#664]
Should the project have its own slack so we can better chat about it ?

**Comment by sbcgua** [comment]
:+1:

**Comment by larshp** [comment]
feel free to create one, lets see how it works

however I'm a bit worried that we might loose some history here in the issues, but on the other hand we might remove some of the discussion and have solutions described instead

**Comment by tiefox** [comment]
Created! 
Invite link
https://abapgit.slack.com/shared_invite/MTU1MjI0NjUyMjYwLTE0ODk2NDkwNTctNGU2OTBiNzZjNw
We can setup http://partyline.rocks and even manage github issues from there.

**Comment by larshp** [comment]
badge added via https://github.com/larshp/abapGit/pull/671

I guess this can be closed now
