### ISSUE TITLE
ABAPGIT for Eclipse

### ISSUE THREAD

**Issue by prashantagl** [larshp/abapGit#665]
Do we have any plugins for Eclipse? or can we use existing ZABAPGIT program in Eclipse?

**Comment by larshp** [comment]
no Eclipse/ADT support currently, pull request welcome, also see https://github.com/larshp/abapGit/issues/636

the ZABAPGIT report can be run inside Eclipse like any other report

closing, for questions/comments please use https://github.com/larshp/abapGit/issues/636
