### ISSUE TITLE
ECATT scripts pull request

### ISSUE THREAD

**Issue by prashantagl** [larshp/abapGit#666]
When I backup ECATT script on the GitHub using ABAPGIT client. Post deletion of ECATT script from SAP when I refresh in ABAPGIT I see D against the D(Local Deleted) but I don't get the pull request to pull back the ECATT script which is deleted evenif the ECATT script is present in the GitHub repository.

![image](https://cloud.githubusercontent.com/assets/25575475/24029158/6ffed5ae-0b28-11e7-9a32-409072dbb489.png)

![image](https://cloud.githubusercontent.com/assets/25575475/24029171/898eb93a-0b28-11e7-82c4-ef33288f05f1.png)

**Comment by larshp** [comment]
how did you generate the ECATT xml? via transaction SECATT?

ECATT objects are not supported by default in abapGit, see https://github.com/larshp/abapGit/wiki/Supported-object-types

also see https://github.com/larshp/abapGit/issues/163

**Comment by prashantagl** [comment]
Out tester created ECATT scripts and saved them in ZTEST1 package. When I clone the repository, it gives shown me the ECATT scripts objects as well to stage to GitHub repository.
I thought if abagit doesnt support any object it will not appear in the abapgit to transfer to GitHub repository :-)

**Comment by prashantagl** [comment]
you can try it at your end as well, create some ECAT scripts via SECATT capture them in any Z package and try to clone that package via abapgit, it automatically creates xml file of ECAT object

**Comment by larshp** [comment]
yes, ECATT scripts are currently not supported by abapGit

abapGit lists all files in the repository, so it is possible to ignore the file

**Comment by prashantagl** [comment]
I committed .xml files from one Dev environment and tried importing to another Dev environment it successfully imported them, I can send you my test case document if you are interested to see :-)

However in your issue #163 you mentioned below which I did:
try using https://github.com/larshp/abapGit-Plugins it might support eCATT objects

**Comment by larshp** [comment]
okay, plugins, can you add a step by step guide on how to reproduce the issue?

**Comment by prashantagl** [comment]
Follow below steps:

01. Create any ECATT test object and capture it in any package
02. Clone that package to any repository using ABAPGIT
03. Stage and commit the ECATT test objects using ABAPGIT
04. Delete the ECATT test object from SE80
05. Run the ABAPGIT again, we will see D against the local system
06. As we have deleted the object from local system but it still present on GitHub/Remote system when I refresh I was expecting the pull option enabled in ABAPGIT which I don't see in ABAPGIT

Kindly advise

**Comment by larshp** [comment]
Hi,
If you like to remove the object from the remote repo, then click "Stage", this follows the same approach/logic as command line `git`.

If you like to have the object created again from remote then click "Advanced" -> "Reset local", again same logic as command line

**Comment by prashantagl** [comment]
I tried above option, it works for other supported objects except ECATT objects :-)

in case of ECATT it doesn't do anything.

**Comment by larshp** [comment]
oh, okay, might be a bug in abapGit-Plugins, will take a look

**Comment by larshp** [comment]
@prashantagl fixed, try again, latest abapGit and abapGit-Plugins versions

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapGit-Plugins/commit/4b6f611a22d1b309fa307ab1aa290e27eb7e2c67

**Comment by prashantagl** [comment]
Thanks!
Will update the code and update you

**Comment by prashantagl** [comment]
Tested with updated code, still no pull request but reset local option worked to restore the deleted ECATT scripts.

Pull option could have been better, as reset to local will be dangerous in scenarios where there is mismatch between local and remote code as it will reset all local objects.

**Comment by larshp** [comment]
pull and reset local actually triggers the same code, and there are(should work) warnings if mismatches exist

**Comment by larshp** [comment]
In case of command line git, the git pull does not restore deleted files, see below, will close this issue

![image](https://cloud.githubusercontent.com/assets/5888506/24249531/e10bd4a4-0fd3-11e7-8ba5-06e7d2776c67.png)
