### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by jeremycoppey** [larshp/abapGit#667]
I made an offline repository because I had some connection issues. (download zip --> import) but now I got it working(rights for STRUST) and was able to connect and ready for a commit.
The only issue was that I imported the project when I was logged in as sy-langu Dutch in stead of the master language of the github code English.

When doing a commit or a pull i receive the fowling issue.
![image](https://cloud.githubusercontent.com/assets/13691266/24036541/29753c00-0afa-11e7-9405-db7e9250aa83.png)

**Comment by larshp** [comment]
if you want to change the master language, goto Advanced -> Database Util

![image](https://cloud.githubusercontent.com/assets/5888506/24036988/5df5c13c-0afc-11e7-94ff-9455179c6a9a.png)

Find your project, click Edit, change the MASTER_LANGUAGE

![image](https://cloud.githubusercontent.com/assets/5888506/24037004/6d4f9112-0afc-11e7-8f52-5d15240c43e4.png)

click save and restart abapGit


Note that this might have some unforseen consequences, but if it is a new project it should not matter.

Alternatively click Advanced -> Remove to remove the project and create it again with the correct master language

**Comment by larshp** [comment]
closing
