### ISSUE TITLE
dot abapgit for offline repo - DB values not used

### ISSUE THREAD

**Issue by erdenber** [larshp/abapGit#668]
I tried to change an offline Repo to FULL folder logic (cf. #624 and #630). The problem is that during rendering, a default dot abapgit is created for offline repos instead of using the one from the DB. This happens in
LCL_REPO_CONTENT_BROWSER->BUILD_REPO_ITEMS_OFFLINE() and subsequently reaches PACKAGE_TO_PATH() where the "Unexpected package naming" error is thrown.

**Comment by larshp** [comment]
try again, it should be solved in https://github.com/larshp/abapGit/commit/62a8099b63f4c3e42ec14d5dababa11368c5a758

**Comment by erdenber** [comment]
Now I'm getting a dump, probably the types are not matching?
![render_repo](https://cloud.githubusercontent.com/assets/5205158/24055744/94a6f8fa-0b41-11e7-9699-e4edd0106c04.png)

Sorry I gotta go, so I can't have a deeper look right now...

**Comment by larshp** [comment]
I tried reproducing the dump, but no luck. Created offline repo with FULL folder logic and subpackages plus objects, no dump 😢

**Comment by erdenber** [comment]
Okay, not the worst thing... Probably I messed something up. I will have another look but won't be able to make it next week. Hope you don't mind leaving the issue open till then.

**Comment by larshp** [comment]
no problem 😄

**Comment by larshp** [comment]
@erdenber did you have time to test it?

**Comment by erdenber** [comment]
@larshp Yeah, finally got to it. I definitely get a dump on 1.32.1, but with 1.33.3 everything is sweet! So I am closing this issue. Thanks!
