### ISSUE TITLE
REPEAT Method Not Found - Need Alternative

### ISSUE THREAD

**Issue by thesourav123** [larshp/abapGit#672]
Hi,
I am trying to install ABAPGit to access ABAP-Swagger.
But, in the program located at http://larshp.github.io/abapGit/build/zabapgit.txt , 
under the method **indent_line**, the code at 
    ` lv_x_str = repeat( val = ` ` occ = ( cs_context-indent - 1 ) * c_indent_size ).`

Here, REPEAT method is UNKNOWN. I am using NetWeaver 7.0 SPS31. I have been able to replace a lot of things to make it compatible with 7.0 but, i dont know what REPEAT method does so that i can adjust. Kindly, help me out.

**Comment by larshp** [comment]
Minimum version for abapGit is mentioned in the READAME.md: "ABAP Version: 702 or higher"
also see https://github.com/larshp/abapGit/issues/635

[ABAP-Swagger](https://github.com/larshp/ABAP-Swagger) requires at least "Releases 7.02 and 7.03/7.31 (Kernelpatch 116)" in order to do JSON processing(https://blogs.sap.com/2013/01/07/abap-and-json/)

So basically it is not supported on 7.0, but feel free to give it a go.

**Comment by thesourav123** [comment]
Hi Lars, 
Thank You very much for the prompt reply. I have handled the JSON Processing part in 7.0. I am only unable to find any documentation on REPEAT method. What does it do. 

I know i am being optimistic for it to work. But, i want to try before i give up due to lower NW Version.

**Comment by larshp** [comment]
repeat is a built-in string function introduced in 7.02

Some german documentation, I havent had any luck finding the correct documentation
http://www.cadaxo.com/high-class-development/abap-7-02-new-features-neue-stringfunktionen/

translating the line to something like the following should work:
```abap
lv_times = ( cs_context-indent - 1 ) * c_indent_size.
do lv_times.
concatenate lv_x_str space into lv_x_str respecting blanks.
enddo.
```

**Comment by thesourav123** [comment]
Thanks a lot @larshp . Though, there are a lot of changes, i am hopeful 💃.
Can you provide a replacement for XSTRLEN. Seems like it is also not available.

Method :  adler32 Class: lcl_hash

    ` do xstrlen( iv_xstring ) times.`

**Comment by larshp** [comment]
something like
```abap
describe field iv_xstring length lv_length in byte mode.
do lv_length times.
```

also feel free to join the Slack channel, https://abapgit-slackinviter.herokuapp.com/

**Comment by larshp** [comment]
@thesourav123 I'll close the isssue, feel free to open a new
