### ISSUE TITLE
HTTP error code:502

### ISSUE THREAD

**Issue by prashantagl** [larshp/abapGit#673]
Hi,

At the time of creation of branch from master branch I am getting below error. This error is intermittent, after retrying 3-4 times it works and again after 3-4 hour get same error message. Any idea?
 
![image](https://cloud.githubusercontent.com/assets/25575475/24131930/b917b47a-0e45-11e7-9495-8d36a7a38a7d.png)

**Comment by larshp** [comment]
do you get the error after the branch creation popup?

![image](https://cloud.githubusercontent.com/assets/5888506/24134205/fe4ee218-0e02-11e7-9e9b-4ae10f3e5d58.png)

try adding a `WAIT UP TO 10 SECONDS.` in the code after branch creation, GitHub might need some time to create the branch

**Comment by prashantagl** [comment]
Yes, after branch creation pop-up. Exactly which place/method in the code I need to add wait upto 10 seconds?

**Comment by larshp** [comment]
try at the end of method `lcl_git_porcelain=>create_branch(`

**Comment by prashantagl** [comment]
Debugged and found that lcl_git_transport=>receive_pack( this method it throwing back an exception

**Comment by larshp** [comment]
what is the error text, value of `lv_string` in method `receive_pack` ?

**Comment by prashantagl** [comment]
Currently not getting this error as its intermittent, once I get same error again will share it with you

cheers!!!
