### ISSUE TITLE
How to deal with "Could not aquire lock REPO"

### ISSUE THREAD

**Issue by jfilak** [larshp/abapGit#678]
Hello, the function ENQUEUE_EZABAPGIT started exiting with `sy-subrc EQ 2` and I cannot find any reason for it.

Could you please advise me how to find out why I cannot acquire the lock?

**Comment by larshp** [comment]
Can you reproduce the issue? What are the steps?

**Comment by jfilak** [comment]
Sure I can reproduce it. I wanted to debug it on my own but I got stuck on `CALL 'C_ENQUEUE' ...`. The symptoms are the following:
- impossibility to checkout a branch
- impossibility to reset local changes
- impossibility to pull
- impossibility to commit & push

Thanks!

**Comment by larshp** [comment]
first exit all programs in all open sessions, then make sure there are no locks in SM12 for your username

If there is an entry, then you have a dead session that needs to be killed via SM04 or similar

**Comment by jfilak** [comment]
Thank you very much indeed! The application server was restarted and everything works as expected now.
