### ISSUE TITLE
Transport to Branch, objects from different packages

### ISSUE THREAD

**Issue by giovannidegani** [larshp/abapGit#682]
Following my understanding, when using the Transport to Branch functionality, any object that is not part of the repo package would cause an error. It would be useful for this to be handle differently and just pushing to the repo this objects as "new"

**Comment by Srinu3366** [comment]
When trying Transport to Branch can we move objects from the package/sub packages of this git repo only and display a message with objects not in the package of the Git Repo. Objects from different package can be created as separate branch in the respective repo.

**Comment by larshp** [comment]
I'll go ahead and close this, no progress

custom handlers can be implemented via interface ZIF_ABAPGIT_BACKGROUND
