### ISSUE TITLE
"IT_REQUIREMENTS" is not a structure or internal table with header line.

### ISSUE THREAD

**Issue by ibewugb** [larshp/abapGit#683]
Hi, I copied all the code to my $TMP package as a new report "ZABAPGIT". Then I get the following error:

```
Program ZABAPGIT	6.877	@0A\QError@
"IT_REQUIREMENTS" is not a structure or internal table with header		
line.		
```

Release: SAP_BASIS	731	0005

**Comment by larshp** [comment]
thanks, will do the downport

**Comment by larshp** [comment]
@ibewugb fixed, try again, latest version 😄

**Comment by ibewugb** [comment]
@larshp thank you for this crazy fast fix :) working now
