### ISSUE TITLE
Error: Branch Not found after installing Gitlab 9.

### ISSUE THREAD

**Issue by p-h-i-l** [larshp/abapGit#690]
**Problem:** 

abapGit can't find branches (master, any other branch)  anymore after update to [Gitlab 9.](https://about.gitlab.com/2017/03/22/gitlab-9-0-released/) All projects are visible and can be selected in abapGit but branches cannot be found.

Contrary to the Gitlab branches all abapGit repositories can still be found and their branches are visible. 

**Assumption:**

Obviously Gitlab does sth. differently, not sure what though, because everything worked fine before updating... Also all branches and projects are visible in Gitlab. 

**Other stuff:** 
Using the newest version of abapGit and Gitlab.

**Comment by larshp** [comment]
a: can the issue be reproduced in a gitlab.com public repository?

b: try setting a breakpoint at the following code, and see what the contents of variable `lv_data` is

```abap
  METHOD branch_list.

    DATA: lv_data TYPE string.

    eo_client = lcl_http=>create_by_url(
      iv_url     = iv_url
      iv_service = iv_service ).

    lv_data = eo_client->get_cdata( ).
```

**Comment by rednose84** [comment]
lv_data is empty... i guess it is something related to the URL *.git/info/refs which is invoked by zabapgit...

**Comment by p-h-i-l** [comment]
*.git/info/refs also throws an `access denied` error message. 

Permissions and user-groups look fine to me.

**Comment by rednose84** [comment]
this: 

https://github.com/larshp/abapGit.git//info/refs?service=git-upload-pack works 


but the same request to gitlab (ce internal installation) returns an empty file...  


with gitlab.con it seems to be working... :-(  Nay idea?

**Comment by larshp** [comment]
I assume you have tested with a normal git client to make sure it works generally. Are you running the community edition, or checked if the error is reproducible in the community edition?

Try setting a breakpoint at the following, to check value of `rv_scheme`

```abap
    rv_scheme = ii_client->response->get_header_field( 'www-authenticate' ).
    FIND REGEX '^(\w+)' IN rv_scheme SUBMATCHES rv_scheme.

    CASE rv_scheme.
      WHEN gc_scheme-digest.
```

**Comment by p-h-i-l** [comment]
`rv_scheme` has the Value `Basic` and seems to work properly. 

In the meanwhile i tried pulling / fetching / pushing from a non ABAP Gitlab Repository. 
Fetching from remote resulted in a `ref not found` and pushing in `fatal: git-http-push failed`. 

After consideration, this looks less like a bug with ABAPGIT but with the Community Edition of Gitlab. Even though we can't be sure yet, what exactly is causing the issue.

In the meanwhile i updated my local git and can tell, that this is not the issue. 👍

**Comment by larshp** [comment]
maybe this is related: https://gitlab.com/gitlab-org/gitlab-ce/issues/29923 try restarting your gitlab instance

**Comment by p-h-i-l** [comment]
Yap, that solved the issue for us as well - as far as i can tell. I hope from here on it's a smooth ride with ABAPGIT + GITLAB 😀 

Thanks for your fast response and support! 🍺
