### ISSUE TITLE
Shortdump - after code update of ZABAPGIT

### ISSUE THREAD

**Issue by prashantagl** [larshp/abapGit#693]
Hi,

Today I tried updating ZABAPGIT code by just deleting existing code and copy paste new code.

When I execute after entering github  credentials I am getting below pop-up and after pressing enter I get the shortdump. Any idea?

But when I remove all repositories which are cloned in ABAPGIT then follow above process then it works fine. So my question is everytime when we have to update the ZABAPGIT code do we need to remove all cloned repositories from ABAPGIT then update the ZABAPGIT code?

![image](https://cloud.githubusercontent.com/assets/25575475/24273520/ec841f8c-1076-11e7-9d15-ae70da1bf6fa.png)

![image](https://cloud.githubusercontent.com/assets/25575475/24275623/e878595e-1084-11e7-8472-5948f058b210.png)

**Comment by larshp** [comment]
everytime abapGit is updated, remove all repos: no, but sometime we'll introduce new features that require migration, and in this case some problems might occur.

can you paste the call stack from the dump? did all the repos work previously to upgrading abapGit?

**Comment by prashantagl** [comment]
before updating code it was working perfectly fine. Below is screenshot of calls from ST22

![image](https://cloud.githubusercontent.com/assets/25575475/24282693/403116ec-10b5-11e7-9b02-ce075b2ea935.png)

**Comment by larshp** [comment]
try again, latest version

thanks for the bug report 😄

**Comment by prashantagl** [comment]
updated code resolved the issue.

Cheers!!!

Closing this issue
