### ISSUE TITLE
Ignore files that are outside of STARTING_FOLDER

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#696]
If you specify `STARTING_FOLDER` in .abapgit.xml all source code and metadata files serialized by abapGit will be inside that folder. Everything outside of it _should_ be irrelevant for abapGit (except .abapgit.xml) so it might be reasonable to add new behavior so that these files are automatically ignored (possibly triggered by a new flag for compatibility).

**Comment by larshp** [comment]
merged, try latest version

**Comment by larshp** [comment]
closing merged in https://github.com/larshp/abapGit/issues/697, please raise new issue in case of problems
