### ISSUE TITLE
Log issue.

### ISSUE THREAD

**Issue by VishnAndr** [larshp/abapGit#703]
There is an issue in lcl_log->show
It shows 4 lines of the same content:
```
    READ TABLE mt_log INDEX 1 INTO ls_log1.
    READ TABLE mt_log INDEX 1 INTO ls_log2.
    READ TABLE mt_log INDEX 1 INTO ls_log3.
    READ TABLE mt_log INDEX 1 INTO ls_log4.
```

The result looks like this:
![image](https://cloud.githubusercontent.com/assets/4543139/24683900/a02544a4-19e5-11e7-9e69-d41c4bfefc85.png)

I'm not sure how this comment may apply:

```
* only supports showing 4 errors, but I guess this is okay
* alternatively refactor to use method TO_HTML instead
```

Seems that (to_html) is already done for online repos. But not yet for offline.

**Comment by larshp** [comment]
```abap
READ TABLE mt_log INDEX 1 INTO ls_log1.
    READ TABLE mt_log INDEX 1 INTO ls_log2.
    READ TABLE mt_log INDEX 1 INTO ls_log3.
    READ TABLE mt_log INDEX 1 INTO ls_log4.
```

should be changed to 

```abap
READ TABLE mt_log INDEX 1 INTO ls_log1.
    READ TABLE mt_log INDEX 2 INTO ls_log2.
    READ TABLE mt_log INDEX 3 INTO ls_log3.
    READ TABLE mt_log INDEX 4 INTO ls_log4.
```

trouble is that the same code can be triggered via Advanced -> Export package to zip, where it is difficult to show the html list

**Comment by larshp** [comment]
I have changed the READ TABLEs, however this does not completely solve the problem

**Comment by christianguenter2** [comment]
should we close this?

**Comment by larshp** [comment]
yeah
