### ISSUE TITLE
Offline repos. Many questions to overwrite objects

### ISSUE THREAD

**Issue by VishnAndr** [larshp/abapGit#704]
In case we're importing zip-file with many objects which already exist in the system then there is annoying popup for each object saying:
"It looks like object <object_type> <object_name> has been modified
locally, overwrite object? "

Could we have like "Yes for all" button? I can contribute if you agree with the idea.

**Comment by larshp** [comment]
also see https://github.com/larshp/abapGit/issues/515

idea with "yes for all" is good, it would be quite easy to implement. But ultimately I would like it to display a list with the objects, where it is possible to choose for each object

**Comment by VishnAndr** [comment]
Agree with one page to review them all. Better do it once than step by step (e.g. object by object).

**Comment by larshp** [comment]
but it will take some time to implement the new page, implementing a "Yes for all" can perhaps be done quite quickly and help users until the big solution is implemented

**Comment by apex8** [comment]
Something like this could be implemented quite easily using a salv table with some checkboxes in the first column. I did this before, it´s not much code. If you want I can adopt this for this.

**Comment by christianguenter2** [comment]
As it's implemented I think we can close this one?

**Comment by larshp** [comment]
yeah 👍
