### ISSUE TITLE
SICF double entries

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#705]
workaround, add last 2 lines of abap in include ZABAPGIT_TADIR

```abap
    LOOP AT rt_tadir ASSIGNING <ls_tadir>.
      <ls_tadir>-path = lv_path.

      CASE <ls_tadir>-object.
        WHEN 'SICF'.
          <ls_tadir>-obj_name = <ls_tadir>-obj_name(15).
      ENDCASE.
    ENDLOOP.
* SICF doublets workaround, need better solution
    SORT rt_tadir BY object ASCENDING obj_name ASCENDING.
    DELETE ADJACENT DUPLICATES FROM rt_tadir COMPARING object obj_name.
```

**Comment by jorgt** [comment]
Still an issue in 1.37.6. 

![image](https://user-images.githubusercontent.com/2444503/28650200-51471ffc-72bd-11e7-853e-bf07d86b1398.png)

Don't have a great solution yet either.

**Comment by jorgt** [comment]
If you're using the merged / built version of abapGit, the code above is on line 14029 and still works. I agree it's not very neat.

**Comment by larshp** [comment]
The SICF nodes are stored with the name + hash value in TADIR, abapGit removes the hash value to get a nice filename,

```abap
    LOOP AT rt_tadir ASSIGNING <ls_tadir>.
      <ls_tadir>-path = lv_path.

      CASE <ls_tadir>-object.
        WHEN 'SICF'.
          <ls_tadir>-obj_name = <ls_tadir>-obj_name(15).
      ENDCASE.
    ENDLOOP.
```

ideally the has should be part of the filename, however this requires being able to create the SICF entry again with the same TADIR key. Which did not work out for me when I tried a few years back, however I did not spend a lot of time looking into it, so it might be possible

**Comment by jorgt** [comment]
Hi @larshp, I tried commenting out that particular bit of code but searching for `'SICF'` showed me that it was used in a few more places. ICF nodes in particular are a bit finicky but I can have a go on a system I have proper access to.

**Comment by larshp** [comment]
yeah, easy short term fix is to show a warning and ignore the 2nd SICF node

**Comment by larshp** [comment]
**As-is:**
SICF TADIR object names consists of the node name + the guid of the parent node, which differs from system to system.

**Solution proposal:**
Instead of the guid, then store a hash for the URL(folder path) of the service. This will be the same across systems.

think this can be done and still be backwards compatible, as the hash is not needed for deserializing the object

**Comment by larshp** [comment]
@jorgt try this https://github.com/larshp/abapGit/pull/867

**Comment by jorgt** [comment]
I'll test this

**Comment by larshp** [comment]
I tested it a bit, see comments in https://github.com/larshp/abapGit/pull/867
