### ISSUE TITLE
Full folder logic does not work with package nesting depth > 1 in custom /../ namespace

### ISSUE THREAD

**Issue by pfaller** [larshp/abapGit#710]
I just restructure our package structure, it looks now like follows 

![image](https://cloud.githubusercontent.com/assets/7314541/24896709/6f848f2a-1e96-11e7-8e5e-366038d4f55f.png)

/CQSE/ABAP_DEV is the root package used for sync with abapGit. Everything worked fine with full folder logic before adding the three marked packages. But with the additional level of nesting in the package structure, the contents of the three new packages do not get pushed to the git repository. 

I did a few tests with some dummy packages and it seems that the problems are related to the /../ custom namespace. It seems to work fine with packages in Z namespace

Here the result of such a package structure in Z namespace: https://github.com/pfaller/abapgit-test/tree/nested-packages  - everything looks as expected

And here the same for /CQSE/ namespace: https://github.com/pfaller/abapgit-test/tree/nested-pacakges-2 after staging / pushing the following objects:

![image](https://cloud.githubusercontent.com/assets/7314541/24897051/b53011e2-1e97-11e7-9426-880e753a6663.png)

The marked programs are missing in the git repository. 

That's how it looks like in abapGit after staging / pushing the changes: 

![image](https://cloud.githubusercontent.com/assets/7314541/24897118/f1091042-1e97-11e7-820b-b55024ca6a94.png)

The programs in question still appear as if these would be new. 

I also tried to create the package structure manually in the git but didn't help. Also I did a little bit debugging, but couldn't locate the bug. 

Here the debug info of abapGit:
```
abapGit version: v1.33.4

XML version: v1.0.0

GUI version: 7400.1

LCL_TIME: 1491895543 +0200

SY time: 20170411 092543 3600

Supported objects: ACID, AUTH, CLAS, DDLS, DOCT, DOCV, DOMA, DTEL, ENHO, ENHS, ENQU, ENSC, FUGR, IARP, IASP, IATU, INTF, MSAG, NROB, PARA, PINF, PROG, SFBF, SFBS, SFPF, SFPI, SFSW, SHI3, SHLP, SICF, SMIM, SPLO, SSFO, SSST, SUSC, SUSO, TABL, TOBJ, TRAN, TTYP, TYPE, VCLS, VIEW, W3HT, W3MI, WDYA, WDYN, WEBI, XSLT

Browser: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.2; WOW64; Trident/7.0)
Frontend time: Tue Apr 11 2017 09:25:41 GMT+0200 (Mitteleuropäische Sommerzeit)
```

**Comment by larshp** [comment]
thanks for the bug report

how does the staging page look? try pressing stage in the above example

**Comment by pfaller** [comment]
looks quite normal to me: 
![image](https://cloud.githubusercontent.com/assets/7314541/24998740/7853568a-203b-11e7-9d07-dce34a1ea066.png)

Also behaves like staging would work normal, the objects can be added and commited but in the end these are sill missing in the Git.

**Comment by larshp** [comment]
I think I have reproduced the issue, will try to fix

```abap
  METHOD namespaces.

    FIELD-SYMBOLS: <ls_tree> LIKE LINE OF mt_trees.

    append( iv_path = '/src/#foo#a/#foo#a1/'
            iv_name = 'a1.txt' ).

    append( iv_path = '/src/#foo#a/#foo#a2/'
            iv_name = 'a2.txt' ).

    mt_trees = lcl_git_porcelain=>build_trees( mt_expanded ).

    cl_abap_unit_assert=>assert_equals(
      act = lines( mt_trees )
      exp = 5 ).

    LOOP AT mt_trees ASSIGNING <ls_tree>.
      cl_abap_unit_assert=>assert_not_initial( <ls_tree>-data ).
    ENDLOOP.

  ENDMETHOD.
```

**Comment by larshp** [comment]
@pfaller try this, https://github.com/larshp/abapGit/pull/712

**Comment by pfaller** [comment]
Sorry for the late reply .. #712 did work! Many thanks for your great support and for providing this awesome tool!
