### ISSUE TITLE
changelog/news doesnt seem to work

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#714]
gc_abap_version is 1.34.0

```abap
          CREATE OBJECT ro_instance EXPORTING
            iv_rawdata = <file>-data
            iv_version = gc_abap_version.
```

when it compares the versions and it finds 1.34.0, EXIT is performed,
```abap
      "Skip everything below current version
      IF lv_version IS NOT INITIAL
         AND lcl_news=>compare_versions( iv_a = lv_version iv_b = lv_current_version ) < 1.
        EXIT.
      ENDIF.
```

**Comment by sbcgua** [comment]
This is intended. The current idea is to show **unsynced** changes. So you check them BEFORE pull. 
I merged latest changes to my branch - here is waht I see in AG

![image](https://cloud.githubusercontent.com/assets/15635498/25063408/464f74e0-21ec-11e7-96dc-f2bb7db1b7b2.png)

But after pull there is no changelog. 

However, maybe the idea is wrong, what do you think ? Maybe the last version should be always visible ?

**Comment by larshp** [comment]
ahh, okay

**Comment by larshp** [comment]
perhaps move the icon to next to the pull link?

**Comment by sbcgua** [comment]
Hmmm. If you intuitively expected different thing, then maybe UX can be improved. 
Thinking about this in connection to user settings param. What if:

1. Let's say we have user param telling that the user have seen new for version 1.1.1
2. And the current version is 2.2.2
3. So if saved version is lower than actual the user must see the changelog and so changelog is forcefully displayed at start. At the same time 2.2.2 is saved to settings as the user "has seen" the news.
4. If the saved version = actual -> news div are hidden by default
5. The news button is always shown. And would display **at least** current version news (this is actually the subject of this issue).
6. Now AG takes changelog from repo. If there is a version higher than **current** (lets say 3.3.3) then the new button is highlighted (orange probably).
7. Maybe even the last seen repo version should be also saved. So then if last seen < lastest changelog version (e.g. 4.4.4) then news div is shown by default.

Examples to reconcile:

settings = 1.1.1, current = 1.1.1, repo = 1.1.1 => blue button, hidden div, news range - 1.1.1
settings = 1.1.1, current = 2.2.2, repo = 2.2.2 => blue button, force div display, save 2.2.2 to settings, news range 1.1.1 - 2.2.2
settings = 2.2.2, current = 2.2.2, repo = 3.3.3 => orange button, force div display, save 3.3.3 to settings, news range 2.2.2 - 3.3.3
settings = 3.3.3, current = 2.2.2, repo = 3.3.3 => orange button, hidden div, news range 2.2.2 - 3.3.3
settings = 3.3.3, current = 2.2.2, repo = 4.4.4 => orange button, force div display, save 4.4.4 to settings, news range 2.2.2 - 4.4.4

> perhaps move the icon to next to the pull link?

Do you mean the action toolbar ? News is not a command. I think it is not a good place ... Why don't you like the current place ? Maybe to move it right after repo URL ? Potentially - maybe to change the icon ?
![image](https://cloud.githubusercontent.com/assets/15635498/25063565/50972e26-21f0-11e7-9a76-0375671934dd.png)

**Comment by sbcgua** [comment]
Some drafting on the way ...
![image](https://cloud.githubusercontent.com/assets/15635498/25066478/3a382e3e-222f-11e7-8464-4e8b356ea7bb.png)

**Comment by sbcgua** [comment]
#565

**Comment by sbcgua** [comment]
OK looks like ready ... PRing

final look - has updates
![image](https://cloud.githubusercontent.com/assets/15635498/25248733/0551ab04-2618-11e7-9a50-51faf6570020.png)

no updates (5 last versions displayed)
![image](https://cloud.githubusercontent.com/assets/15635498/25248784/3083fd9a-2618-11e7-9c84-4e3e576268e9.png)

Latest version saved to user setting, and on first appearence of a yet newer version - log is forced to display (hopefully it will not be annoying :)

P.S. Desided to leave design as regular tags - those bullets in above message look a bit messy
