### ISSUE TITLE
WAPA (BSP application) some page attributes are missing

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#717]
When serializing a BSP application some attributes are missing. E.g. "IS_START_PAGE", "LAYOUTLANGU" and "DEVCLASS".

![image](https://cloud.githubusercontent.com/assets/17437789/25089922/c7233e72-2380-11e7-85eb-f62a024a71e0.png)

![image](https://cloud.githubusercontent.com/assets/17437789/25089997/332c20b6-2381-11e7-81d7-ca8b6b7dcd80.png)

I think we should use lo_page->get_attrs instead of is_page

![image](https://cloud.githubusercontent.com/assets/17437789/25090524/055f496c-2384-11e7-8626-f36deaf078f2.png)

**Comment by larshp** [comment]
yeah, feel free to submit a PR

the CHANGETIME and DEVCLASS are/should be cleared on purpose, as the content can vary from system to system

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapGit/pull/719
