### ISSUE TITLE
DCLS (ABAP Data Control Language Sources) missing

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#726]
https://help.sap.com/viewer/f2e545608079437ab165c105649b89db/7.5.5/en-US/707332186bf41014b5040bee4e204223.html

**Comment by larshp** [comment]
merged in https://github.com/larshp/abapGit/pull/731

**Comment by larshp** [comment]
@christianguenter2 @bigId I've invited both of you to be collaborators, so you can assign yourself in the task 🎈
