### ISSUE TITLE
Screens are not exported

### ISSUE THREAD

**Issue by pacroy** [larshp/abapGit#729]
When export a program with a dialog screen in offline mode and try importing in another system. The program fails because the screen does not exist.

Haven't tried the online mode yet but suspect the same symthom.

**Comment by larshp** [comment]
hi, thanks for the bug report, can you add a bit more information?

is the dynpro part of report/module pool/function group etc?

**Comment by pacroy** [comment]
Yes, it is dynpro part of a program. Not sure about Function Group or Module Pool. Will try and let you know.

**Comment by larshp** [comment]
seems to work for me, https://github.com/larshp/CLAS/commit/e80e73e9a15f4beefc8130ccf5e08e7fe34ca714

try setting a breakpoint at function module RS_SCREEN_LIST,
https://github.com/larshp/abapGit/blob/master/src/zabapgit_objects.prog.abap#L1273

**Comment by pacroy** [comment]
So far, I found 2 cases:

1. Program with selection screens (I tried with ZSAPLINK) - screen 0110 and 0120 properly exported but not 1000 and got a shortdump as default 1000 selscreen does not exists. Could be fixed using RSDBGENA to regenerated selection screens.

2. Module pool program with screens - this happens when the program is in local package ($TMP) and you tries to reassign to a different package. abapGit does not export any screens or GUI elements. Could not find a solution yet. I plan to use SAPlink to re-import and try again.

**Comment by larshp** [comment]
1. selection screens are not exported to XML, as they are already part of the ABAP code, example: https://github.com/larshp/abapOpenChecks/blob/master/src/utils/zaoc_clearance.prog.abap

can you add steps to reproduce the issue?

2. can you check if the screens are found by function module RS_SCREEN_LIST ?

**Comment by larshp** [comment]
2. try again, latest version, https://github.com/larshp/abapGit/commit/38da837ea3a8c2a3bd15b68aa80e941741fd59d8

**Comment by pacroy** [comment]
Works great now. Thank you!

**Comment by larshp** [comment]
cool, closing issue, just raise a new if you run into other problems 😄
