### ISSUE TITLE
Jump to ADT for all objects

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#734]
For hardcore ADT users like me it would be great if all objects were opened in ADT. Therefore I'd suggest a new settings parameter with which you can enable generic jump to ADT.

**Comment by christianguenter2** [comment]
First prototype.
I created a parameter "Enable jump to ADT first". Which tries to open the object in ADT and fallback to the current implementation if it fails. If the parameter is not set, the current implementation is called.

![image](https://cloud.githubusercontent.com/assets/17437789/25316612/a3c0615a-286a-11e7-89c6-7183eb1cd777.png)

**Comment by EduardoCopat** [comment]
Cool 👍 

It seems that in the future we will need to arrange better the settings page

**Comment by christianguenter2** [comment]
Did some more testing and it works really well for me. Submitted a PR.

I'm not quite sure if lcl_objects_super is the right place for the jump_adt method. Better suggestions are welcome.
