### ISSUE TITLE
Versioning of packages owned by SAP user

### ISSUE THREAD

**Issue by jfilak** [larshp/abapGit#738]
I assume it is not possible to clone repositories for packages where the responsible person is SAP user because regular SAP users should not touch system source code:
https://github.com/larshp/abapGit/blob/master/src/zabapgit_repo_impl.prog.abap#L887

Is there any other reason for preventing users from versioning of such packages? If does not, I would like to make this feature configurable as I want to play with SAP system source code.

**Comment by larshp** [comment]
can be added as a global setting

I'm not sure if SAP would like it if the requirement is removed, but that would be the easiest.

**Comment by larshp** [comment]
implemented as user exit, see https://github.com/larshp/abapGit/issues/850, try again

**Comment by larshp** [comment]
closing
