### ISSUE TITLE
Keep getting HTTP Communication Failure

### ISSUE THREAD

**Issue by pacroy** [larshp/abapGit#743]
I've just installed the SSL certificate and tested it by making an existing repository online (by clicking Make online). Once I entered the correct URL, it showed errors "HTTP Communication Failure" (Seem my certificate is not good).

I exited and re-enter ZABAPGIT but keep getting [this screen](https://s3-ap-southeast-1.amazonaws.com/pacroy/2017-04-27_16-59-13.png) even I re-logon.

**Comment by larshp** [comment]
try running via this program:
https://github.com/larshp/abapGit/wiki/ZABAPGIT_TEST_SSL
it isolates the http communication, so it might be easier to debug

**Comment by nwenig** [comment]
did you install ALL certificates of the certificate chain up to the root certificate in the STRUST certification store? I had the same error, but after I installed the certificates (in my case to a git-http-backend on my private Synology NAS with Lets-Encrypt certificates) it worked.
But this issue I had:
despite of this error or if you enter a wrong credentials a record was inserted into table ZABAPGIT and after resolving the certificate issue I was not able to clone the same respository again until I deleted the record for this repository manually with SE16. Is this another (known) issue?

**Comment by larshp** [comment]
@nwenig hmm, can it be reproduced? If so feel free to create it as a separate issue

**Comment by pacroy** [comment]
I have solved my certificate problem. Seem the ca-bundle is not working so I did install individual certificates instead.

Thanks Lars for reminding me about ZABAPGIT_TEST_SSL. Should this useful program be included right in the repository?

**Comment by larshp** [comment]
the ssl program is mentioned in the wiki under certificate installation. The program is not part of the core, only for testing, so it is not in the git repository
