### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#749]
The wiki documentation should be rearranged to look more like a real manual.

There is a lot missing in the documentation:
* description of .abapgit.xml file
* description of folder logic
* F2A feature description
* favorites/burger menu
* changelog/news announcements
* background mode
* write protection
* proxy setup
* authorizations
* package to folder relation
* plus alot of other stuff

**Comment by EduardoCopat** [comment]
- description of .abapgit.xml file
- description of folder logic

Created: https://github.com/larshp/abapGit/wiki/.abapgit.xml-description

**Comment by larshp** [comment]
Cool

Perhaps we should consider the overall structure of the documentation, guess something like the following split:

- manual/features
walkthrough of each single feature, all buttons and what they do. Like https://github.com/larshp/abapGit/wiki/.abapgit.xml-description

- use cases
what can abapGit be used for at a more general level

- howto/guides
how to, eg. "how to clone a project" etc.

**Comment by larshp** [comment]
hi, any opinion on moving away from the wiki and adding the documentation to a new /docs/ folder?

it will allow us to use PRs for updating the documentation, and we can control the layout better. We can setup Travis CI to copy the documentation to gh-pages after each merge.

**Comment by tiefox** [comment]
Makes sense to me!

**Comment by sbcgua** [comment]
:+1:

**Comment by larshp** [comment]
I have created the /docs folder which uses Jekyll

Moved the builds to new "build" branch, only keeps the latest build, havent had any use for the old versions, and they were around 500 MB uncompressed.

Deleted "gh-pages" branch

**Comment by larshp** [comment]
todo: 
* add sidebar something like this https://github.com/facebook/react/blob/master/docs/_includes/nav_docs.html
* CSS and theming

**Comment by EduardoCopat** [comment]
I never used Jekyll... As long you can edit the documentation using a WYSIWGT, it's fine to me. It needs to be easy to document :)

**Comment by larshp** [comment]
Editing will be done via normal MD, example:
https://github.com/facebook/react/blob/master/docs/docs/introducing-jsx.md
and Jekyll will then put it into a HTML context, example:
https://facebook.github.io/react/docs/introducing-jsx.html

**Comment by larshp** [comment]
did some work on a navigation bar, see http://larshp.github.io/abapGit/

maintained in https://github.com/larshp/abapGit/blob/master/docs/_data/navigation.yml which then links to seperate MD files

**Comment by larshp** [comment]
all documents have been moved from the wiki to /docs, will close this issue and create a few new
