### ISSUE TITLE
IWPR	Gateway Business Suite Enablement - Service Builder Project

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#75]
gateway serialization

**Comment by larshp** [comment]
/IWBEP/CL_SB_GEN_GENERATOR
/IWBEP/CL_SBDM_MANAGER

http://scn.sap.com/docs/DOC-63661
http://help.sap.com/saphelp_nw74/helpdata/en/f7/dc22512c312314e10000000a44176d/content.htm

**Comment by larshp** [comment]
package /IWBEP/SB_DM_BASE

class
/IWBEP/CL_SBDM_FILE_IMPORT_REQ

interface
/IWBEP/IF_SBDM_FILE_HANDLER
methods
CREATE_IMPORT_REQUEST
CREATE_EXPORT_REQUEST


/iwbep/if_sbod_schema_context


package
/IWBEP/SB_EXPFILE empty
/IWBEP/SB_FILEIMP

project copy:
/IWBEP/CL_SBUI_PR_CMD_COPY
/IWBEP/CL_SBDM_COPY_CONTEXT


/n/IWBEP/REG_MODEL

**Comment by larshp** [comment]
testing,

```abap
REPORT zgatewaytest.

START-OF-SELECTION.
  PERFORM run.


*  DATA g_field TYPE REF TO data.
*  CREATE DATA g_field TYPE ('/IWBEP/I_SBO_PR').

FORM display USING pt_nodes TYPE /iwbep/t_sbdm_nodes
                   pv_level TYPE i.

  DATA: li_prop TYPE REF TO /iwbep/if_sbod_property.


  LOOP AT pt_nodes ASSIGNING FIELD-SYMBOL(<li_node>).
    DO pv_level TIMES.
      WRITE space.
    ENDDO.
    WRITE: <li_node>->get_name( ), <li_node>->ms_node_type-node_type.

    IF <li_node>->ms_node_type-node_type = 'PROP'.
      li_prop ?= <li_node>.
      WRITE: / li_prop->get_maxlength( ).
    ENDIF.

* class /IWBEP/CL_SBOD_PROPERTY_PS
* table /IWBEP/I_SBO_PR
    WRITE /.

    DATA(lt_nodes) = <li_node>->get_children( ).
    DATA(lv_level) = pv_level + 1.
    PERFORM display USING lt_nodes lv_level.
  ENDLOOP.

ENDFORM.

FORM run.

  DATA ls_sel_project TYPE LINE OF /iwbep/if_sbdm_manager=>ty_t_range_prjct_name.
  DATA lt_sel_project TYPE /iwbep/if_sbdm_manager=>ty_t_range_prjct_name.
  DATA lo_manager TYPE REF TO /iwbep/if_sbdm_manager.
  DATA lt_projects TYPE /iwbep/t_sbdm_projects.


  ls_sel_project-sign = 'I'.
  ls_sel_project-option = 'EQ'.
  ls_sel_project-low = 'ZS'.
  INSERT ls_sel_project INTO TABLE lt_sel_project.

  lo_manager = /iwbep/cl_sbdm=>get_manager( ).
  lt_projects = lo_manager->find_projects( lt_sel_project ).

  LOOP AT lt_projects ASSIGNING FIELD-SYMBOL(<lo_project>).
    DATA(lt_nodes) = <lo_project>->get_children( ).
    PERFORM display USING lt_nodes 0.
  ENDLOOP.

ENDFORM.
```

**Comment by js1972** [comment]
Just wondering where things are at with the GW support (SEGW)? I'd like to help if its not quite there.?

**Comment by larshp** [comment]
Hi,
Tried some stuff in https://github.com/larshp/abapGit-Gateway, but ended up concluding that it was a lot of work.

In the meantime https://github.com/larshp/abapGit-Plugins has been developed by @mrsimpson, it uses a generic approach for serializing objects. Install by clicking the "Install" link in the upper right corner when running ZABAPGIT. The plugin might work for SEGW projects, but I have not tested it

**Comment by larshp** [comment]
Update: I've fixed the dumps in the plugin 

The plugin now serializes the project to XML file.

But it fails when trying to import the data in
https://github.com/larshp/abapGit-Plugins/blob/0ad7d91dc4e99f1f7b638b1cbe4854e090d48611/zcl_abapgit_object_by_sobj.clas.locals_imp.abap#L796
when trying to process the packed number. I'll not look more into this today, but feel free to investigate if you have time. Or alternatively look into "native" abapGit serialization for IWPR

**Comment by larshp** [comment]
Update: dumps are fixed, so it works a bit better now, make sure to use latest version of abapGit and [abapGit-plugins](https://github.com/larshp/abapGit-Plugins)

I have only done limited testing

**Comment by filak-sap** [comment]
How can I help? It would super awesome to have SEGW projects versioned in git.

**Comment by larshp** [comment]
actually SEGW should work when using https://github.com/larshp/abapGit-Plugins, there is an example at https://github.com/grahamrobbo/teched16_example

but as always, there might be bugs, and more testing would be nice

**Comment by EduardoCopat** [comment]
My small 5 cents: Shouldn't SEGW be part of the "core" abapGit? Since on S4/HANA the Fiori front-ends are delivered through Gateway services...

**Comment by larshp** [comment]
I would, at some point, like to merge the functionality from the plugins into abapGit "core".

Need to consider the following:
* testing, would like to make sure that the objects types supported are tested before added, ie. a positive list of what is working
* clearing of fields like author/change/created date
* transports and TADIR, there might be some issues

all of this can be worked out

**Comment by larshp** [comment]
Once IWPR is supported, we need to decide if IWMO and IWSV should be supported or automatically generated on deserialization of IWPR

**Comment by jfilak** [comment]
I am not sure how to deal with `/IWBEP/I_SBD_AT` which contains attachments like SADL XML. The value is of the type raw bytestring (I tried to decode it on my linux box with base64 but the result complete disaster), so it is not readable when serialized.

IWPR probably needs to produce more files.

An excerpt of own IWPR XML:
```
<_-IWBEP_-I_SBD_AT>
    <PROJECT>RANDOM_NAME</PROJECT>
    <NODE_UUID>AkKsEQACHumRzvafLoQinw==</NODE_UUID>
    <NODE_UUID_PA>AkKsEQACHumOwe3vP8VBmA==</NODE_UUID_PA>
    <PLUGIN_PA>/IWBEP/CORE</PLUGIN_PA>
    <NODE_TYPE_PA>PROJ</NODE_TYPE_PA>
    <NAME>SADL</NAME>
    <TYPE>4</TYPE>
    <MIME_TYPE>XML</MIME_TYPE>
    <VALUE>/wYCAQICg...</VALUE>
<_-IWBEP_-I_SBD_AT>
```

I did some CDS renaming [1] and after pulling the changes my SEGW project went off.


1: https://github.com/jfilak/snippets/blob/master/abap_rename/rename.sh

**Comment by larshp** [comment]
hmm, guess this was also a problem with the old abapGit Plugins based IWPR serialization?

**Comment by jfilak** [comment]
Yep, absolutely. I am happy to create a patch. Any hints are more than welcome.

1.a. Should we add generic support?
- File name schema : <segw project name>.iwpr.atch.<node_uuid>.xml?

1.b. Or should we add support for particular attachments like SADL? (there is one much bigger named GENERATED_METHODS_RDS which is XML as well)
- File name schema : <segw project name>.iwpr.<node_type>.<name>.xml?

1.c. Or something completely else?

2. I would just leave the `/IWBEP/I_SBD_AT` element as it is and move only the child elment `value` to the new file. OK?

**Comment by larshp** [comment]
it depends a lot on the details, but suggest not to create too many new files, which 1.a. might do

**Comment by jfilak** [comment]
I hope we can use this: `<project>.iwpr.sadl.xml`

**Comment by larshp** [comment]
use something like the following to add more files from a serializer
```
    zif_abapgit_object~mo_files->add_xml( iv_extra = 'sadl'
                                  io_xml = dsfsd ).
```

**Comment by filak-sap** [comment]
The corresponding object types `IWMO` (model) and `IWSV` (service) were not added to transport after pulling them together with a new IWPR object. I had to add them manually in SE01 by coping their data from `TADIR` to the corresponding task. I believe these object types are still handled by abapGit-plugins.

IWMO tables:
- /IWBEP/I_MGW_OHD
- /IWBEP/I_MGW_OHT

IWSV tables:
- /IWBEP/I_MGW_SRG
- /IWBEP/I_MGW_SRH
- /IWBEP/I_MGW_SRT

**Comment by larshp** [comment]
suggest adding native support for these also, same approach as in https://github.com/larshp/abapGit/pull/2444

**Comment by larshp** [comment]
solved in https://github.com/larshp/abapGit/pull/2771, closing
