### ISSUE TITLE
HTTP communication error during cloning a new repository

### ISSUE THREAD

**Issue by nwenig** [larshp/abapGit#752]
Error description:
When an HTTP communication error occurs during cloning a new respository (e. g. missing certificate or wrong credentials) a record is added to table ZABAPGIT but the existing objects of the repository were not copied. Staying on the same screen and e. g. providing correct credentials the errormessage _Package already in use_ occurs. After re-entering abapGit with correct certificates/ credentials you see the repositoy and you have to pull the changes which were not cloned at the first try.
Solution proposal:
when a repository is cloned the record in ZABAPGIT shall only be inserted if no error occurs.
Test procedure:
- delete DigiCert certificates needed for github in STRUST and restart ICM
- start abapgit and clone https://github.com/nwenig/abapGit_eval4 -> communication error
- insert DigiCert certificates and restart ICM
- refresh/ restart abapGit 
- you see the differences and can pull them again manually
Rating:
From my point of view not critical because you can resolve it with the pull; but it might be more clear for the user if nothing happens when this error occurs.

**Comment by larshp** [comment]
@nwenig can you try again? https://github.com/larshp/abapGit/pull/787 was merged a while ago

**Comment by nwenig** [comment]
sorry for late close, was busy with other topiics and lost focus on abapgit for a while
