### ISSUE TITLE
Revert to last commit

### ISSUE THREAD

**Issue by herumartinussalim** [larshp/abapGit#753]
I'm looking for a feature to revert some specific objects to the last committed version, similar to re-checkout a new workspace in java development.
Unfortunately I could not find this feature anywhere.

**Comment by larshp** [comment]
Hi,
Under Advanced -> Reset local, it will get the latest commit and reset all local objects to this. Currently there is no feature to reset only a few objects,

![image](https://cloud.githubusercontent.com/assets/5888506/25746612/9c81bb1c-31a4-11e7-855e-7db82b464dde.png)

**Comment by herumartinussalim** [comment]
Hi Lars,
thanks a lot for your answer. It really helps.
Anyway, as of your current answer, I assume, it is also not possible to take a specific branch as a productive code. Am I right? Or can I achieve this by selecting the branch, and then "reset local"?

Thanks and best regards,
Heru

**Comment by larshp** [comment]
You can switch between branches, and abapGit will then take the code from that branch and activate when doing the pull from the branch.

It is possible to have your production code in a branch, and then develop in a different. However make sure you have a good overview when doing this, it might not be clear to all users that sometimes the productive code is active, and sometimes the dev code.

**Comment by herumartinussalim** [comment]
Ok, thanks again for the detailed explanation.
