### ISSUE TITLE
Error inserting Type-Pool ZZAOC

### ISSUE THREAD

**Issue by ewx** [larshp/abapGit#754]
Hi Lars,

I tried to install ABAP Open Checks and get the following error when inserting the type-group ZZAOC:

> error from RS_DD_TYGR_INSERT_SOURCES

I think this is an ABAPgit issue, not AOC.

Type-group ZZAOC is displayed in list of inactive objects.
When clicking on the type-group SAP says:
> %_CZZAOC does not have any inactive version

I also get a lot of meesages like
> Files for object CLAS ZCL_AOC_CATEGORY are not placed in the same folder 

Is this a follow-up issue of not completely installed AOC?

Any ideas how to solve this issue?

triple-Thanks (for ABAPgit, for ABAP Open Checks and for solving this issue... ;)

Regards
Enno

**Comment by larshp** [comment]
are you upgrading from a previous old version? 
Try uninstalling abapOpenChecks completely, and then reinstall it

**Comment by ewx** [comment]
No. fresh install.
I tried to uninstall everything and cloned again.
What remained inactive is "Type-Group ZZAOC".
I deleted type-group ZZAOC and again uninstalled.

New clone:
activation goes wrong:
> Runtime Errors         DBSQL_ARGUMENT_ERROR
> Except.                CX_SY_OPEN_SQL_DB
> SEU_DELETE_INACTIVE_ENTRIES

Can't figure out which of the 1277 objects causes the error... ;)
![image](https://cloud.githubusercontent.com/assets/800007/25894597/b902fefa-357c-11e7-834a-0d08a682a5e6.png)

Seems to be some kind of database issue...

I created type-group manually.
