### ISSUE TITLE
Text in source code based editor is reorganized on activation

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#756]
This is not directly an abapGit problem, but something that you stumble upon using abapGit and it kind of ruins `git diff`: When you activate a global class in eclipse or in SE24 using the source code-based editor ~20% of the time the source code will get completely reorganized. This includes:
- Method implementations are reordered alphabetically (which is very annoying if you wrote them in order of visibility and static/instance-bound)
- Method implementations are separated by exactly two empty lines (this includes two lines before the first method)
- The class name in the implementation part is suddenly in all uppercase

I assume this is a remainder of the form based editor and splitting a class in X includes. Currently I have this problem for every file in a project, because I exported the whole package and imported it on another system which I assume triggered a _fresh_ ABAP load generation (which otherwise is only done sometimes).

Any idea how to prevent this other than copying the whole class just in case it gets reorganized?

![image](https://cloud.githubusercontent.com/assets/5270359/26007608/8f4c0338-3741-11e7-9c90-143c7b3f7b6b.png)

**Comment by flaiker** [comment]
Regarding the method order: This seems to have something to do with `CL_OO_CLIF_SOURCE\LCL_PERSISTENCE_META_DATA->IF_OO_CLIF_PERSIST_META_DATA~KEEP_METHOD_ORDER` which you _could_ enhance to return `abap_true` instead of `abap_false` if you really wanted to.

**Comment by larshp** [comment]
yeah, I also had the same issue a few times

The idea with `METHOD serialize_abap_new.` was to use the same function as ADT to save the source code, where it must be possible to save the source without modifications. Try figuring out how ADT does it, it might help solving this issue

**Comment by larshp** [comment]
what SAP BASIS version is the source and target systems, is ADT supported?

**Comment by flaiker** [comment]
I've experienced this issue on 7.40 SP5 and 7.50 SP2, both support ADT.

Regarding source / target: I exported a whole package hierarchy using transport of copies to a virtual target. I took the cofile / datafiles from the filesystem and imported them using STMS on another system (new installation). Both of these were AS ABAP 7.50 SP2 developer edition systems.
The main problem in that case was, that I still had uncommitted changes in abapGit. Otherwise I would have been able to just revert to HEAD.

**Comment by EduardoCopat** [comment]
If you only use ADT, you shouldn't face this problem. I did several tests and debugs: abapGit correctly deserializes the method order, it is only when you open the Class with SE80, that it reorders everything.

There one thing we can do from the abapGit side to stop it, but it is dangerous: we can manually update the `TMDIR` table with the corrected indexes.

Example: I inverted C_METHOD and A_FIRST_METHOD index order manually, and it worked.

![image](https://user-images.githubusercontent.com/2248490/27752271-84500dc6-5db6-11e7-90d0-7c413fc1fbc9.png)

**Comment by flaiker** [comment]
> If you only use ADT, you shouldn't face this problem.

I agree you shouldn't, however I do. See here: https://streamable.com/ee369

**Comment by larshp** [comment]
found database table SEO_SRC_POS_IND, perhaps it can be used for something

**Comment by larshp** [comment]
Another piece of standard code to investigate,
![image](https://user-images.githubusercontent.com/5888506/29994300-ce3e66e2-8fcc-11e7-9aaa-f620644ca18b.png)

**Comment by flaiker** [comment]
Yup, that's the one I found initially :P
![image](https://user-images.githubusercontent.com/5270359/29994392-f2dd49a8-8fce-11e7-9032-0dec7bbccefb.png)

I enhanced it to return `abap_true` at some point but that didn't help much I don't think.
