### ISSUE TITLE
docs: write documentation

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#761]
There is a lot missing in the documentation:

- [ ] F2A feature description
- [ ] favorites/burger menu
- [x] changelog/news announcements
- [ ] background mode
- [X] proxy setup
- [x] authorizations
- [ ] branch overview
- [ ] keyboard shortcuts
- [ ] merging branches
- [ ] requirements feature, for eg. SAP_BASIS versions

**Comment by JohannesKonings** [comment]
Are the entries of menu "Advanced" somewhere documented? If not, should we create a new topic below "Reference"?

![image](https://user-images.githubusercontent.com/14806640/44046687-857f37a4-9f2c-11e8-9a07-5ef099ecc2c6.png)

**Comment by larshp** [comment]
closing, some of this is done, open new issues if something is missing
