### ISSUE TITLE
docs: favicon

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#764]
... having a mood for drawing :) nothing really creative but maybe better than nothing :)

![path16](https://cloud.githubusercontent.com/assets/15635498/26256009/3705d6bc-3cc4-11e7-945f-13ffd0f86d91.png)

Look at this one ^^^^ , the below one is to see that maybe can be reused in another place. 
I like: 
2.2 is actually not terrible despite blurry
3.1 not bad
5.3, 5.4
6.2, 6.4

![path32](https://cloud.githubusercontent.com/assets/15635498/26256062/62736850-3cc4-11e7-949f-b86fc1bcf9c4.png)

**Comment by larshp** [comment]
can you try these, but with upper case "G":
![image](https://cloud.githubusercontent.com/assets/5888506/26256350/f2c597a0-3cbc-11e7-8eee-111fe2d16484.png)

**Comment by sbcgua** [comment]
![path16-2](https://cloud.githubusercontent.com/assets/15635498/26256722/892fb6f4-3cc6-11e7-93bf-08e0fe04eaee.png)

Square one (2) is not bad ... but imho too asymetric

**Comment by larshp** [comment]
agree, like it better with just 2 lower case letters

**Comment by sbcgua** [comment]
potential chrome look
![image](https://cloud.githubusercontent.com/assets/15635498/26257310/cf828396-3cc8-11e7-8c2d-ef046305f83e.png)

**Comment by larshp** [comment]
I like these:
![image](https://cloud.githubusercontent.com/assets/5888506/26257351/96690c9a-3cc0-11e7-8439-30b9f6a06b63.png)

**Comment by sbcgua** [comment]
agree. 
I faved for bare one (4) but on a tab it does not look good. 
from these 2 ... circle looks github-like and more accurate but a bit too dense.
I'll try to make font smaller a bit ... 1 min

**Comment by sbcgua** [comment]
![image](https://cloud.githubusercontent.com/assets/15635498/26257654/2d30f274-3cca-11e7-89c1-345838507e14.png)
No, small font is too unreadable.

Ok, we can wait for some more opinions.
Imho I prefer round one - more accurate, github-like. A bit dense ... well, favicons are dense.

**Comment by sbcgua** [comment]
If PR is OK, let's close then. favicon.png is in docs now. Can also attach SVG if needed.

**Comment by larshp** [comment]
add the SVG under /docs/img? then it should be easy to find, if its needed in the future

**Comment by sbcgua** [comment]
SVG favicon
[ag-favicon-final.zip](https://github.com/larshp/abapGit/files/1017231/ag-favicon-final.zip)

**Comment by sbcgua** [comment]
> add the SVG under /docs/img

added :) good place. agree.
