### ISSUE TITLE
docs: welcome page

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#768]
the welcome page looks stupid, 2 sets of the same links, lets try something else, any thoughts?

![image](https://cloud.githubusercontent.com/assets/5888506/26286419/7b2760c0-3e65-11e7-88ab-4136aa157227.png)

**Comment by sbcgua** [comment]
I'd say it should describe the project itself. Started on ... goal of the tool ... blah blah ... NW7.02 ... roadmap ... to contribute do this ... blah blah ... start from installing this way ...

**Comment by sbcgua** [comment]
Any sense to install google analytics to the docs ? Or github gives enought details ? (Or maybe they are not needed at all ? :)) )

**Comment by larshp** [comment]
google analytics: been thinking about it, it could be fun, however it might be too evil for a open source project. 

Information from github is very limited and only goes back 14 days, so I have setup an Azure function that runs daily and downloads the information via the [traffic api](https://developer.github.com/v3/repos/traffic/)

**Comment by sbcgua** [comment]
Ah, cool :)
