### ISSUE TITLE
ssh communication with gerrit

### ISSUE THREAD

**Issue by njames** [larshp/abapGit#769]
I see in http://larshp.github.io/abapGit/guide-online-install.html that the repo is commicated with via https. Our gerrit server requires ssh. Is there any scope for abapGit to support ssh?

**Comment by larshp** [comment]
no

we are lucky that CL_HTTP_CLIENT supports https, however I dont konw any way for ABAP to communicate using SSH. Perhaps it is possible with the new TCP/IP sockets, however it would require implementing the ssh protocol from scratch

**Comment by larshp** [comment]
closing, feel free to reopen

**Comment by larshp** [comment]
@njames https://github.com/open-abap/open-abap-ssh
