### ISSUE TITLE
global classes for dev version of abapGit

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#773]
something we have been discussing in the slack channel

it would make it easier to do integration to Eclipse/ADT and other tools

Still want to have a single automatic generated report for copy/paste install

this will require some steps and a lot of trial and error,

1: get rid of global and cross class macros, macros inside methods are ok
2: get rid of global types(move to interface? ZABAPGIT_DEFINITIONS)
3: get rid of global constants(move to interface? ZABAPGIT_DEFINITIONS)
4: tool https://github.com/larshp/local-to-global for help converting

**Comment by larshp** [comment]
constants, todo:
_object_check_timestamp - difficult due to the RETURN
_reduce_state - new method?
_add_dialog_fld - many fields
_add_rule - move constants into code and call a method with table parameter to initialize rules?



related to unit tests:

_generate_parse
_generate_order
_generate_extend
_append_local
_append_remote
_append_state
_append_result
_new
_old
_expected

**Comment by larshp** [comment]
first PR merged, more to follow

**Comment by flaiker** [comment]
Wow you are actually going through with this 👍 

So the general idea would be to have some (loosely coupled) functionality depend on the existence of the "global class installation" and that installation can be done using the local copy paste abapGit installation? And abapGit development itself would then be done using the local or global classes?

**Comment by larshp** [comment]
installation: via copy pasting 1 report with local classes

development: global classes

And still having [abapmerge](https://github.com/larshp/abapmerge) building the copy-paste report, there is a lot of issues that needs to be handles, currently just trying out some stuff

**Comment by EduardoCopat** [comment]
woudl abapmerge convert Global classes to local classes?

**Comment by larshp** [comment]
yeah, its the plan, lets see if it works out

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit-global for WIP

**Comment by larshp** [comment]
todo: macros from above and rename the local class of the following so the name fits into 30 chars,

rename: zcx_abapgit_2fa_token_gen_failed
rename: zcx_abapgit_2fa_token_del_failed
rename: zcx_abapgit_2fa_communication_error
rename: zcl_abapgit_2fa_authenticator_base
rename: zcl_abapgit_2fa_github_authenticator
rename: zcl_abapgit_2fa_authenticator_registry
rename: zcl_abapgit_proxy_authentication
rename: zcl_abapgit_object_oriented_class
rename: zcl_abapgit_object_enho_wdyconf
rename: zcl_abapgit_object_enho_interface
rename: zcl_abapgit_object_oriented_interface
rename: zcl_abapgit_object_oriented_factory
rename: zif_abapgit_object_oriented_object_fnc
rename: zcl_abapgit_oo_object_serializer
rename: zcl_abapgit_object_oriented_base
rename: zcl_abapgit_object_tabl_validation
rename: zcl_abapgit_tabl_validation_dialog
rename: zif_abapgit_object_comparison_result
rename: zcl_abapgit_null_comparison_result
rename: zcl_abapgit_gui_page_background_run
rename: zcl_abapgit_gui_page_background
rename: zcl_abapgit_gui_page_branch_overview
rename: zcl_abapgit_gui_page_db_display
rename: zcl_abapgit_gui_page_repo_settings
rename: zcl_abapgit_persistence_migrate
rename: zcl_abapgit_persistence_background
rename: zcl_abapgit_persistence_settings
rename: zcl_abapgit_repo_content_browser
rename: zcl_abapgit_services_background
rename: zcl_abapgit_transport_to_branch
rename: zcl_abapgit_gui_view_repo_content

**Comment by flaiker** [comment]
Just fyi, do you know about this in SE24?
![image](https://user-images.githubusercontent.com/5270359/26917017-d253f7ee-4c2c-11e7-8e6f-bc57adb8d043.png)
![image](https://user-images.githubusercontent.com/5270359/26917037-e2ea2498-4c2c-11e7-8ea1-ae813c9492be.png)

I have personally never used it but seems like the exact use case (initial local to global conversion).

**Comment by larshp** [comment]
nope, didnt know, cool feature

https://github.com/larshp/local-to-global will work with very little manual work

**Comment by larshp** [comment]
dynamic references, pages and objects?

**Comment by larshp** [comment]
[ ] move 'GC_ABAP_VESION' to somewhere else
[ ] fix/test FORM callbacks for popups, see zabapgit_forms.prog.abap
[ ] macro _REDUCE_STATE, new method?
[ ] macro _ADD_RULE, move constants into code and call a method with table parameter to initialize rules?
[ ] macro _OBJECT_CHECK_TIMESTAMP - difficult due to the RETURN
[ ] macro _ADD_DIALOG_FLD refactoring, current approach does not work for global classes
[ ] selection screen password popup, ZCL_ABAPGIT_PASSWORD_DIALOG
[ ] rename method 'serialize_abap_czif_abapgit_source', longer than 30 chars

**Comment by larshp** [comment]
It is difficult to refactor all the code in one go, so perhaps a new plan is needed.

Instead of moving everything in 1 commit, then move to global classes over time.

A good starting point could be moving https://github.com/larshp/abapGit/blob/master/src/zabapgit_zlib.prog.abap to a global class, as it does not have any requirements to LCL_ classes.

This would get it started, and the infrastructure needed for the refactoring would be built, after this it would just be a lot of hard work 😄

**Comment by larshp** [comment]
https://github.com/larshp/abapGit-global updated

**Comment by larshp** [comment]
Another plan, have abapmerge create the merged file in the following order:

A: all DEFINITIONs DEFERRED
B: all DEFINITIONs
C: all IMPLEMENTATIONs
D: all testclasses, note that local test class names might collide
E: concatenated PROG

Assumptions: 
* no macros in global classes
* no local classes in global classes
* no calls from global classes to local classes

--------------------------------------------------------------------

Example:

```abap
CLASS lcl_bar DEFINITION DEFERRED.
CLASS lcl_foo DEFINITION DEFERRED.

CLASS lcl_foo DEFINITION.
  PUBLIC SECTION.
    METHODS: foo IMPORTING bar TYPE REF TO lcl_bar.
ENDCLASS.

CLASS lcl_bar DEFINITION.
  PUBLIC SECTION.
    METHODS: bar IMPORTING foo TYPE REF TO lcl_foo.
ENDCLASS.

CLASS lcl_foo IMPLEMENTATION.
  METHOD foo.
    NEW lcl_bar( ).
    RETURN.
  ENDMETHOD.
ENDCLASS.

CLASS lcl_bar IMPLEMENTATION.
  METHOD bar.
    NEW lcl_foo( ).
    RETURN.
  ENDMETHOD.
ENDCLASS.
```

**Comment by larshp** [comment]
note that additional classes will not be made global until #904 is solved

**Comment by christianguenter2** [comment]
I think for further globalization e.g. #964 we should also make the local interface lif_defs (ZABAPGIT_DEFINITIONS) global. I'm not quite sure whether abapmerge handles this correctly.

[This](https://github.com/christianguenter2/abapGit/tree/Interface_global) would be a first try.

**Comment by larshp** [comment]
try opening a PR for it, then I'll try running `abapmerge` on it

alternatively just `npm install abapmerge` and run it locally

**Comment by christianguenter2** [comment]
I'll submit the PR tomorrow. If I run abapmerge locally I get this error.

![image](https://user-images.githubusercontent.com/17437789/31321237-eafbaf24-ac82-11e7-9134-c68b989ae234.png)

Any idea?

**Comment by larshp** [comment]
something went wrong in the regex, https://github.com/larshp/abapmerge/blob/master/src/class_list.ts#L19, would have to start the debugger, but perhaps some Windows specific stuff

**Comment by christianguenter2** [comment]
yep, it's a windows thing. Line breaks are \r\n not just \n. This regex would work.
`/^((.|\r\n)*ENDCLASS\.)\s*(CLASS(.|\r\n)*)$/i`
Anyhow how do I call abapmerge correctly? I'm now quite sure which arguments I have to supply.

**Comment by larshp** [comment]
Correctly: yes, see https://github.com/larshp/abapGit/blob/master/travis.sh#L2 it just pipes the output to file

**Comment by christianguenter2** [comment]
As you already guessed global interfaces don't work.
![image](https://user-images.githubusercontent.com/17437789/31328364-f5475954-acd4-11e7-82cb-d77733ccdd9c.png)

**Comment by larshp** [comment]
Next steps:
* `lcl_gui_asset_manager` to global, note that this might require changes in abapmerge, due to the following abapmerge commands
```abap
        " @@abapmerge include zabapgit_css_common.w3mi.data.css > _inline '$$'.
      WHEN 'JS_COMMON'.
        " @@abapmerge include zabapgit_js_common.w3mi.data.js > _inline '$$'.
```

* Plus we have to move `lcl_object_*` classes to global, this will have to be done in one step. Be sure to check performance when installing this many classes, the new CLAS deserialization should make it possible, but who knows

**Comment by larshp** [comment]
Current core dependencies:

lcl_objects <-> lcl_repo*
lcl_repo -> lcl_tadir -> lcl_objects

lcl_repo also uses lcl_exit, need some kind of new solution for the exits setup

**Comment by larshp** [comment]
Done! closing ✨
