### ISSUE TITLE
Transport from Development to Productive System

### ISSUE THREAD

**Issue by tfey** [larshp/abapGit#788]
Hi,

a simple question about transporting abapGit from SYSTEM-Layer to PRODUCTIVE-Layer...

Do I have to install abapGit in each system, or how does it works? When I transport it within STMS there occur errors...

Maybe a idiotic question, but there is no documentation about it...

Thanks in advance.

Thorsten.

**Comment by larshp** [comment]
Transporting abapGit itself with STMS should work, what is the error message?

**Comment by tfey** [comment]
we have imported with abapGit. After that we would transport it via STMS.
But he cannot find some classes etc. because many were all under $TMP.
 And not within the created package. The return code after trying to
transport to Quality or productiv layer is 8.

To transport abapGit into the development layer is not the problem. The
problem is the transport from the developer layer to the quality and
productive layer.
therfore the question: Should I "install" abapGit in each layer or is there
a way to transport it within the layers development, quality and
productive...???




*Best regards,*

*Thorsten Fey*

**Comment by larshp** [comment]
Do you want to transport abapGit itself, or a objects that have been installed using abapGit?

In general; if the objects are in the development system, then it should be possible to use STMS for transporting if the objects are not in a local package.

If objects are in a local package, then move the objects to a transportable package.

**Comment by tfey** [comment]
both. First the objects using my program that it works...

Okay, I think that is the problem. While installing abapGit on the
development system it installed automatically some classes... under $tmp.
I will looking for the classes that have been installed under $tmp to get
it work... Not all are under $tmp.
I don´t know where was my error while installing. Everything should be
under my created package...

Thank you very much. I will try your solution next days...

**Comment by larshp** [comment]
abapGit itself automatically creates EZABAPGIT enqueue object and ZABAPGIT transparent table in $TMP when the program is started. However these are not referenced statically, so it should not cause any problems when transporting the report.

abapGit itself does not use any classes, only code is the ZABAPGIT report, or if using the development version, then the includes are listed under https://github.com/larshp/abapGit/tree/master/src

**Comment by larshp** [comment]
Install objects using abapGit into your development system and then use STMS for transporting to quality and production. Do not import objects to quality or production using abapGit.

You can use abapGit for exporting objects from quality or production, this will be okay.

(however there might be special cases/landscapes where you need to do something special)

**Comment by tfey** [comment]
Thank you very much...

a last question: is it the same for abap2xlsx via abapGit? There I have the
problem, that he haven't found some classes. A Program I have created has
not found methods like 'set_title', 'ZCL_EXCEL=====================CP,
Include ZCL_EXCEL=====================CM003' etc...

In the development environment it works very well and I am impressed about
abap2xlsx. But while transporting it to the quality layer it returns with
the error code 8.

**Comment by larshp** [comment]
yes, it is the same

abap2xlsx via abapGit: if you have a online project abapGit will show warnings if the classes are placed in a unexpected package. For offline projects the warning is not shown.

If you had an old version of abap2xlsx installed with saplink, and later moved to abapGit it might have caused some problems.

**Comment by tfey** [comment]
Okay, thank you very much.

What is the best practice for that? Should I deinstall and then reinstall?

**Comment by larshp** [comment]
Yes, try uninstalling abap2xlsx and installing it again, it should be safe to uninstall abap2xlsx as it does not store any data in the database.

If it does not work then you need to go through all the objects and make sure they are in the correct package, also make sure all objects are active.

**Comment by larshp** [comment]
closing
