### ISSUE TITLE
Support for ABAP 702

### ISSUE THREAD

**Issue by christianp86** [larshp/abapGit#789]
Hi Lars,

we would like to use your awesome Git Client within our product development department.
We are currently on ABAP 702 SP06 as we have to be at a low ABAP level to support a lot of clients.

At first I thought I only had to adjust some method calls, but in the end a lot of SAP standard classes are missing.

Do you know which exact release we would require?

Thank you.
Christian

**Comment by larshp** [comment]
"ABAP Version: 702 or higher" is the target version for abapGit, but it is sometimes difficult to test as only few have access to a 702 system.

Just post the syntax errors/dumps here, and we can take a look on how to make it run on your system 😄

**Comment by christianp86** [comment]
I started fixing syntax errors until I realized that we seem to be missing quite a few SAP ABAP classes such as:
CL_APC_APPLICATION_OBJ_PERS
CL_AMC_APPLICATION_OBJ_PERS

I guess without those classes I don't have to work on the syntax errors. Am I Correct?
Second questions would be how we can figure out with which ABAP version these classes have been released.

The package SAMC_DESIGN_TIME is part of SAP_BASIS. I can see check in another system that the package has been created on 21.11.2011.

![image](https://user-images.githubusercontent.com/29406789/27092655-624fd530-5064-11e7-8173-643d583e89ec.png)

So I guess it must come with one of those SPs.

**Comment by larshp** [comment]
ABAP push channels is a new feature not available on 702, so the references to the classes are dynamic in abapGit,

```abap
CREATE OBJECT mo_persistence TYPE ('CL_APC_APPLICATION_OBJ_PERS').
```

So it in this case should compile on 702, and the code never called since APC does not exist in 702. If trying to install a APC object on 702 abapGit will give an error.

Do you get any syntax errors regarding class CL_APC_APPLICATION_OBJ_PERS? Can you paste the list of the actual syntax errors when activating ZABAPGIT? Then we might be able to fix these one by one.

**Comment by christianp86** [comment]
Most of the syntax errors are related to chaining method calls...
![image](https://user-images.githubusercontent.com/29406789/27093204-219e2c06-5066-11e7-9db8-6a41e88a2191.png)

I simply unchain them to something like. (different methods called in both screenshots)
![image](https://user-images.githubusercontent.com/29406789/27093178-07bf9900-5066-11e7-8af4-7c52e16fb21a.png)

**Comment by christianp86** [comment]
sorry forgot the syntax error:
![image](https://user-images.githubusercontent.com/29406789/27093308-7b8493d6-5066-11e7-887b-918d81542878.png)

**Comment by larshp** [comment]
unchaining: feel free to submit the changes in a pull request(https://guides.github.com/introduction/flow/) so others using 702 can use the same changes, this will also help you when upgrading abapGit. Alternatively if you provide the list of places to unchain then I'll do the changes and add to abapGit master.

syntax error: what the exact line number? and are you running the latest version?

**Comment by larshp** [comment]
syntax error: can you add a screenshot of the ABAP code, if you've done a lot of unchaining the line number will not match the line number in the latest abapGit release

**Comment by christianp86** [comment]
Ok I will submit the changes in a pull request once I can confirm everything works as expected.
Thank you for your quick replies. Highly appreciated!
Sorry I already did all the changes. I could activate the report now
All syntax error (4 in total) were releated to the following two code lines:

```
get_persistence( )->lock(
get_persistence( )->get( 
```

**Comment by larshp** [comment]
cool 👍

**Comment by masterrx** [comment]
@christianp86  nice to see you here 👍 The code for SAMC and SAPC serialization was written by me, so it was my fault. I tested it only against our 7.31 system as I thought it's quite similar to a 7.02 one. Isn't there an option to check whether code is compatible in another NW release? I think I heard something about that but I'm not quite sure. Any hints or other suggestions how to prevent this error in the future?

**Comment by christianguenter2** [comment]
@christianp86  nice to see you here 👍 The code for SAMC and SAPC serialization was written by me, so it was my fault. I tested it only against our 7.31 system as I thought it's quite similar to a 7.02 one. Isn't there an option to check whether code is compatible in another NW release? I think I heard something about that but I'm not quite sure. Any hints or other suggestions how to prevent this error in the future?

**Comment by larshp** [comment]
prevent error in future: I'll add some more stuff to abaplint(https://github.com/larshp/abaplint/issues/139)

anyhow, most of the code is valid for 702, so usually it is low effort to downport it and submit a PR

**Comment by larshp** [comment]
@christianp86 are you planning to submit a PR for this issue?

**Comment by christianp86** [comment]
Yes I do. Hopefully this monday.

Mit freundlichen Grüßen

Christian Pfisterer

**Comment by larshp** [comment]
closing issue, fix merged in https://github.com/larshp/abapGit/issues/796

**Comment by larshp** [comment]
nope, 701 is not supported
