### ISSUE TITLE
SOTS: All Concepts (OTR) of a Package - Long Texts

### ISSUE THREAD

**Issue by nlsltz** [larshp/abapGit#792]
abapGit tells me these objects are unsupported.

as for now i don't know how to code the serialization of abap objects so i can't implement it by myself.

**Comment by larshp** [comment]
create a include ZABAPGIT_OBJECT_SOTS

see eg. https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_styl.prog.abap for an example on how it works.

There are 2 important methods: deserialize and serialize.

Serialize: Builds the files based on the object in the system, for SOTS I guess we only need 1 XML file, use io_xml->add( to add contents to the XML file

Deserialize: Takes the files and creates the object in the system. Use io_xml->read( to read the XML and then call some functionality to create the SOTS object

**Comment by larshp** [comment]
@nlsltz can you try the latest version

plus, do you know how to create a SOTS object?

**Comment by nlsltz** [comment]
@larshp tried with latest version, but error still exist.

unfortunately i do not have time to dig deeper into this at the moment :(

**Comment by christianguenter2** [comment]
@nlsltz can you try the latest build?
