### ISSUE TITLE
Add support for BSP applications with pages of type so2_controller

### ISSUE THREAD

**Issue by christianp86** [larshp/abapGit#793]
During the initial clone of our main package the client has troubles with BSP pages which are of type so2_controller (o2pagtyp value 'C')

In abapGit class lcl_object_wapa the method read_page is trying to read event_handlers, parameters, ... .
For BSP pages of type so2_controller all methods called from class cl_o2_api_pages throw expection invallid_call.

On monday I will continue working on this issue and try to resolve it.

**Comment by larshp** [comment]
@christianp86 did or will you have time to look into this? Just trying to make sure there are not multiple people looking into it at the same time

**Comment by christianp86** [comment]
Hey,

I was working on it but got new projects on my desk. Hope to fix it soon.
Sorry about the delay.

Christian

**Comment by christianguenter2** [comment]
@christianp86 Could you please test?

**Comment by christianguenter2** [comment]
I'll close...
