### ISSUE TITLE
"Commit: Committer email empty" when german umlaut 'ö' or 'ü' is in committer name

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#795]
I get the error message "Commit: Committer email empty" when I try to use the german writing of my name (with umlaut 'ü') in the committer name. I tried some other variants with german umlauts. With 'ö' I'm also not able to commit. But with 'ä' I can commit.

![image 2017-06-25-002](https://user-images.githubusercontent.com/17437789/27519367-6679bbd4-59f2-11e7-85b1-f0b752d7fe42.jpg)

The whole parsing of the commit request is done in method PARSE_COMMIT_REQUEST of class LCL_HTML_ACTION_UTILS. If I debug it with committer name 'Christian Günter' I can see the following in the debugger.
![image 2017-06-25-003](https://user-images.githubusercontent.com/17437789/27519383-32e59b52-59f3-11e7-9a47-01f460afa112.jpg)

It seems that somehow the query string isn't parsed properly. The parse_fields method delegates the work to cl_http_utility=>if_http_utility~string_to_fields which does a system call. So I'm not quite sure what the problem is. 

What's really strange for me is, when I use a committer name with german 'ä' like in this example at least the commit works. But there are some encoding issues.

![image 2017-06-26-003](https://user-images.githubusercontent.com/17437789/27537260-6007e45c-5a73-11e7-9424-223a4136a97c.jpg)

![image 2017-06-25-006](https://user-images.githubusercontent.com/17437789/27519412-ef325188-59f3-11e7-8880-2353e046c39e.jpg)

So the whole thing looks a bit strange to me. Maybe it's just on my machine? 

In general are special characters in the committer allowed? Or aren't they?

**Comment by larshp** [comment]
encoding, argh

in general: I think it should work with special characters

**Comment by larshp** [comment]
same issue on my machine, 

![image](https://user-images.githubusercontent.com/5888506/27840343-5c223f46-60f8-11e7-85f2-40e7e0703d08.png)

**Comment by larshp** [comment]
I see two possible solutions:
a: find a different standard class/function module that works
b: code the functionality from scratch(should be quite easy 😓 )

**Comment by christianguenter2** [comment]
Ok, thanks. I'll look for possible solutions.

**Comment by christianguenter2** [comment]
Ok, thanks. I'll try possible solutions.

**Comment by christianguenter2** [comment]
#820
