### ISSUE TITLE
Branch Overview Dump

### ISSUE THREAD

**Issue by DKAC** [larshp/abapGit#798]
Hi,

I had a Dump when trying to view the Branch Overview. I tracked the problem to METHOD parse_commits where the regular expression gc_author_regex did not match the ls_raw-author, which in my case contained a backslash. I added an extra \\ to the regular expression after ^([ and that fixed the problem:

gc_author_regex TYPE string VALUE '^([\\\w\s\.@\-_1-9]+) <(.*)> (\d{10})\s?.\d{4}$' ##NO_TEXT.

There was still a cosmetic issue on the view, where the backslash is not shown.

Regards, Daniel

**Comment by larshp** [comment]
what was the value of ls_raw-author? The regex has also caused some problems in the past, would like to add some unit tests for it

**Comment by DKAC** [comment]
Hi,

It was something like

DOMAIN\User <user@domain.com>...

Regards, Daniel



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Lars Hvam <notifications@github.com>
Datum: 28.06.17 18:16 (GMT+01:00)
An: larshp/abapGit <abapGit@noreply.github.com>
Cc: "Klink, Daniel" <klink@informatik.rwth-aachen.de>, Author <author@noreply.github.com>
Betreff: Re: [larshp/abapGit] Branch Overview Dump (#798)


what was the value of ls_raw-author? The regex has also caused some problems in the past, would like to add some unit tests for it

-

**Comment by larshp** [comment]
try again, latest version

**Comment by DKAC** [comment]
Works on my machine ;)

btw. thanks for the good work with abapGit!
