### ISSUE TITLE
XML byte order mark

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#799]
also see https://github.com/larshp/abapGit/issues/629

diffs show up, perhaps ignore the byte order mark when comparing files, hmm

![image](https://user-images.githubusercontent.com/5888506/27673351-7b5d3aca-5ca0-11e7-970a-1734b57e9673.png)

**Comment by insidy** [comment]
Is this still happening? Any example repository or steps on how to reproduce the issue?

By the way, not sure if ignoring UTF-8 BOM in diff is a good approach. If BOM was removed then the file did changed. 

Maybe the best is not adding/removing the BOM at all if it is already there, or ensure that xml rendering always follow the same BOM/no-BOM approach (explicitly set the enconding and BOM usage in the iXML stream).

**Comment by larshp** [comment]
not sure, have not seen it in a while

**Comment by insidy** [comment]
For future reference (if this issue appears again):

In ZABAPGIT_XML we have methods `parse` and `to_xml`, both instantiating ixml streams.

In output streams (the one used in `to_xml`) you can set an encoding, enforcing for example UTF-8 with BOM, with something like:

```abap
(...)
    li_istream = li_stream_factory->create_istream_string( iv_xml ).
    
"No BOM
    li_encoding = mi_ixml->create_encoding(  character_set = 'UTF-8' 
                                             byte_order = if_ixml_encoding=>co_none ). 
    li_istream->set_encoding( li_enconding ).
```
And from input streams you can retrieve if the stream is using BOM or not by using `get_encoding`.

Ideas on how to solve the issue:
1. Store the original encoding parameters when parsing so the same can be applied when converting to XML
2. Enforcing no BOM or little endian or big endian in `to_xml`.

**Comment by mbtools** [comment]
I considered this fix since https://github.com/larshp/abapGit/pull/3167

**Comment by larshp** [comment]
yea, closing
