### ISSUE TITLE
Support of customizing

### ISSUE THREAD

**Issue by JK185** [larshp/abapGit#800]
Hello,

is it possible to support not only workbench objects but also customizing, so basically table content?

Thank you

**Comment by larshp** [comment]
currently it is not possible to put table contents into the git repository using abapGit, but it would be a nice feature to have

**Comment by flaiker** [comment]
For initial installation purposes a workaround is to write an installation report which fills your customizing tables with the initial entries and then call `TR_REQUEST_CHOICE` or something alike to create the customizing transport request.

**Comment by bigld** [comment]
I really like the idea of "simple customizing content"! 
But I think this shouldn`t be used for application/business data - But how to find suitable restrictions...

**Comment by larshp** [comment]
closing, duplicate, see #1004 instead
