### ISSUE TITLE
Function groups with namespaces - not implemented

### ISSUE THREAD

**Issue by Gekke-Jakke** [larshp/abapGit#824]
When importing a function group which is in a namespace, importing in another system is not working. The function modules are not imported correctly. (Source code and includes are imported correctly but can't be activated)

![2017-07-12_10-56-07](https://user-images.githubusercontent.com/2744548/28109892-efb39586-66f0-11e7-8fbc-c2d329c82194.png)

It seems that using namespaces is still a todo in the function group logic

![2017-07-12_10-59-50](https://user-images.githubusercontent.com/2744548/28110052-6779aa10-66f1-11e7-9d24-af23d17ea4c5.png)

**Comment by larshp** [comment]
@Gekke-Jakke can this issue be closed?

**Comment by Gekke-Jakke** [comment]
@larshp Yes it can! Everything is working fine now!
