### ISSUE TITLE
Transport Custom Tcodes

### ISSUE THREAD

**Issue by devkeshav** [larshp/abapGit#826]
I am new to ABAPGIT, just configured it on sandbox. I am curious to know how can I leverage abapgit as a SAP security consultant. Can I use it to transport custom tcodes from one system to another. What are the risks involved.

**Comment by larshp** [comment]
Yes you can download the ABAP objects from one system and upload to another, note that abapGit works on package level.

Risks:
Always make sure you know or have read the code you upload. And you have a license for the code.

abapGit just makes it easier to upload and download, something that has always been possible to do manually.

**Comment by devkeshav** [comment]
Thanks larshp for the quick response. Can we use it to transport single and composite roles as well ?
For eg, maintaining the latest version of role from production system in development system before modifying the role?
Will it automatically highlight the changes that will take place and related concerns?

**Comment by larshp** [comment]
PFCG roles are currently not supported 😢 https://github.com/larshp/abapGit/issues/827

abapGit shows the changes in XML files via diffs, it is up to the user to determine related concerns

**Comment by devkeshav** [comment]
Thanks again larshp. Will now try to transport tcodes using abapgit, if not much trouble could you please direct me to a useful resource and tutorial for this ?

**Comment by larshp** [comment]
see eg. http://larshp.github.io/abapGit/guide-moving-package.html for how to move existing objects into git, and http://larshp.github.io/abapGit/guide-online-install.html on how to install

Also note if you do not have access to a git repository, then "offline" projects can be used to upload/download zip files instead, also see http://larshp.github.io/abapGit/

**Comment by larshp** [comment]
also see https://blogs.sap.com/2017/06/21/abapgit-so-easy/

**Comment by devkeshav** [comment]
Sure, Thanks 👍

**Comment by larshp** [comment]
closing
