### ISSUE TITLE
Dump when adding huge package to abapgit

### ISSUE THREAD

**Issue by ElNovi** [larshp/abapGit#830]
Hi, 

i tried to get to our biggest package to ABAPGIT ( around 2000+ programs and other objects ). It took a while and then it ended with this dump (there is todo comment in the code). But it nearly finished :) 

![image](https://user-images.githubusercontent.com/14199592/28258387-4a2df040-6ad1-11e7-906e-2b91967f2c87.png)
![image](https://user-images.githubusercontent.com/14199592/28258436-7c124e12-6ad1-11e7-8b2b-8a5ae508f4f3.png)
![image](https://user-images.githubusercontent.com/14199592/28258456-8b952b98-6ad1-11e7-8c88-6213b5a4c719.png)

**Comment by larshp** [comment]
hi, can you check the contents of variable `is_item`?

**Comment by ElNovi** [comment]
To be honest im quite afraid to try it again. As we have recently lost our backup files for SAP developer system :D

**Comment by larshp** [comment]
huh? lost the files? due to the bug above?

**Comment by ElNovi** [comment]
I don't think so. Corrupted backup files on the HP-UX.

**Comment by larshp** [comment]
ahh, phew 😓 

Anyhow, the export of a package only reads objects. Is the ST22 dump still in your system, as it might contain the values of IS_ITEM.

**Comment by ElNovi** [comment]
That's nice to hear that it only reads :)

Here is the content of IS_ITEM:
![image](https://user-images.githubusercontent.com/14199592/28362557-17450c56-6c7d-11e7-9efd-85d1df21b3af.png)

**Comment by larshp** [comment]
dump should now be fixed, https://github.com/larshp/abapGit/commit/a54d5779e92886117a34e1772d1a4c2cee5b65c3

**Comment by ElNovi** [comment]
Thanks a lot :)
