### ISSUE TITLE
RS_CUA_INTERNAL_WRITE error

### ISSUE THREAD

**Issue by SimoneCattozzi** [larshp/abapGit#831]
Error is raised in CHECK_INTCODE subroutin when CUA CODE contais only numeric values.

  clear p_is_index.
  if p_code+6(14) is initial and p_code(6) co '0123456789'. 
    p_is_index = 'X'.
  endif.

The exception is raised (in my case) when is_cua-adm IS INITIAL and the check_intcode is performed

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit/issues/562 if the code was previously installed with SAPlink the adm fields are destroyed

suggest manually fixing the data outside of abapGit
