### ISSUE TITLE
possibility to clone without pull

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#832]
in a backup scenario, it could be nice to be able to clone without deserializing any objects/files

**Comment by jfilak** [comment]
Any idea how to implement this feature? If you give me some tips & hints it might help me to find time to implement it.

**Comment by larshp** [comment]
I think the best way is to change the clone feature to a create online project feature. And then let the user use the normal functions to pull or push

**Comment by larshp** [comment]
I'll open a PR for this, hopefully later today
