### ISSUE TITLE
"Branch not found" error when remote branch is deleted

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#834]
If a certain branch is active in ABAPGit and you delete this branch in the remote origin e.g. github, the next time you start ABAPGit the error "Branch not found" is shown and there's no regular way to proceed.

![image](https://user-images.githubusercontent.com/17437789/28287363-ac2237a6-6b3b-11e7-983e-b4ee0f41b4fc.png)

In my opinion there are at least two sensible ways to fix it.
a) Open ABAPGit empty without a repository open
b) Say to the user that the branch doesn't exist anymore and ask for another branch to open

Any opinions or other suggestions?

**Comment by larshp** [comment]
also see https://github.com/larshp/abapGit/issues/747

**Comment by larshp** [comment]
yeah, in case you are inside ZABAPGIT, but if you restart abapGit then it shows an error

**Comment by bigld** [comment]
This was after a restart

**Comment by christianguenter2** [comment]
error occurs only for abapGit ;-)

![image](https://user-images.githubusercontent.com/17437789/28500044-78cbaa5a-6fc2-11e7-8c1a-3e48a9098a47.png)
