### ISSUE TITLE
Moved classes cause problems with the PREFIX folder logic

### ISSUE THREAD

**Issue by jfilak** [larshp/abapGit#837]
Example:
1. Create a class CL_FOO in a package BAR
2. Commit the class and push the commit to a remote
3. Move the class to a package BAZ
4. Refresh the repo and see the error "Error: PREFIX: Unexpected package naming(BAZ)"

I wanted to mark such classes as deleted but I am afraid of the consequences:
https://github.com/larshp/abapGit/blob/master/src/zabapgit_definitions.prog.abap#L158
https://github.com/larshp/abapGit/blob/master/src/zabapgit_file_status.prog.abap#L375

What is a good fix for this issue?
I would like to post a patch for it.

**Comment by larshp** [comment]
What is the relation between packages BAR and BAZ? Should CL_FOO be removed from the repository?

**Comment by jfilak** [comment]
> What is the relation between packages BAR and BAZ?

These are two separate packages and there is no other relation.

> Should CL_FOO be removed from the repository?

Yes, it should be removed from the repository for the package BAR. That means we need a new commit to update the remote repository.

**Comment by jfilak** [comment]
This commit causes that I can see the list of the moved objects, so I can remove the objects in  the command line git:
https://github.com/filak-sap/abapGit/commit/a9542acb4dfc668aa275116409b7fb8ce4c073d9

**Comment by larshp** [comment]
do you use online or offline projects? typically I remove the files during staging in abapGit, however staging only works for online projects

**Comment by jfilak** [comment]
Perhaps, this got resolved by #1393. I have to try it out.

**Comment by jfilak** [comment]
Ah, no, I guess this is a dupe of #1378.

**Comment by EduardoCopat** [comment]
Closing because #1378 is closed.
