### ISSUE TITLE
How to recover from online repository

### ISSUE THREAD

**Issue by devkeshav** [larshp/abapGit#839]
I cloned online repository into $DEMO5 package. I was able to successfully upload a tcode to online repository. Then I went ahead and deleted the tcode using SE93. Now how should I recover that particular tcode from my  online repository.

Error : error, expected parent package, $DEMO5
![l_6146 tmp](https://user-images.githubusercontent.com/4771036/28354629-42a61830-6c7e-11e7-82e6-f582cdd8dffc.PNG)

**Comment by larshp** [comment]
What is the package structure of $DEMO3 and $DEMO5 ? What is the folder structure of the git repository?

In case you have a folder named "demo5" in your git repository, try deleting it in git using tools outside of abapgGit

**Comment by devkeshav** [comment]
Okay, so if I committed the tcode using $DEMO5, I'll be only able to restore it back in $DEMO5 package ?
How to change the parent package once I have already cloned my repository.

**Comment by larshp** [comment]
My guess:
1: you created $DEMO3
2: add transaction to $DEMO3
3: push this to github
4: changed the transaction to $DEMO5
and the error occurs, if this is the full story then

a: change transaction back to $DEMO3 and the error should be gone

now if you want to restore it back into $DEMO5, then first uninstall $DEMO3 and clone back into $DEMO5

**Comment by larshp** [comment]
@devkeshav see recommendations above, will close the issue later in case of no reply

**Comment by larshp** [comment]
closing
