### ISSUE TITLE
Not able to connect to a local git server

### ISSUE THREAD

**Issue by devkeshav** [larshp/abapGit#840]
I installed GitStack on my system. I uploaded the server.crt file in STRUST. When I try to clone my local repository into shared SAP system, and link to my repository as https://"MY IP ADDRESS"/samplerepo1.git
I get the following error:-
HTTP communication failure.
Could you please help ?

**Comment by larshp** [comment]
try the SSL test program, http://larshp.github.io/abapGit/other-test-ssl.html

also check log in transaction SMICM -> Goto -> Trace File -> Display End

**Comment by devkeshav** [comment]
The tcode to call SSL test program does not exists.

**Comment by larshp** [comment]
just copy-paste the code into your system

**Comment by larshp** [comment]
@devkeshav please make sure to follow up in when you open issues

**Comment by larshp** [comment]
closing
