### ISSUE TITLE
Moving objects does not work, when switching branches

### ISSUE THREAD

**Issue by WurstMitDurst** [larshp/abapGit#842]
When the package assignment of an object has been changed, a branch switch does not work anymore.

Example with current version 1.37.5:

Preparation:
- Create package `zassign`
- Create package `zassign_one` (sub package of `zassign`)
- Create package `zassign_two` (sub package of `zassign`)
- Create Data Element `zassign_element` in package `zassign_one`

In abapGit do:
- Commit the package `zassign` to a git repo with abapGit (branch `master`)
- Create and checkout a new branch named `reassignment`

Now, do the following
- In SE80 right click `zassign_element` -> 'Other Functions' -> 'Change Package Assignment'
- Set `zassign_two` as new package
- Commit this change to branch `reassignment` (It will remove `zassign_element` from `zassign_one` and add it to `zassign_two` in the repository)

Now the weird stuff happens (at least for my understanding):
- Switch branch from `reassignment` to the original `master` branch. This will show you a popup, that `zassign_element` will be replaced. Click `OK`.
- Check SE80 and you will see, that `zassign_element` has been moved back from `zassign_two` to `zassign_one`

The other way round does not work anymore:
- Switch branch from `master` back to `reassignment`
- Instead of automatically "move" `zassign_element` from `zassign_one` to `zassign_two` it stays in `zassign_one` and abapGit interprets this as a local change compared to the repository.

Is this considered a bug or is there something I do not understand?
Best regards,
Tobias

**Comment by larshp** [comment]
automatic moving between packages during pull is not implemented yet 😢

**Comment by larshp** [comment]
workaround is to move the objects manually, or uninstall and install all objects again

**Comment by WurstMitDurst** [comment]
I have already feared, that this is a missing feature. Yes I definitely need to do something manually, here. Unfortunately in one of our projects, there is a big refactoring pending, which includes moving many objects from some packages to others. And refactoring in abap is always a pain :-D

**Comment by larshp** [comment]
tip: you can use transaction SE03 to do mass changes for objects, https://blogs.sap.com/2013/09/25/mass-tadir-changes-using-se03/

hope this will be implemented in abapGit sometime in the future, pull requests welcome

**Comment by larshp** [comment]
alternatively as a quick fix, perhaps make a small utility program outside of abapGit, which calls some of the abapGit functionality, that can be used to fix the package assignments

**Comment by WurstMitDurst** [comment]
Wow thanks alot for the SE03 magic. I have already used this transaction to change the origin of some objects, but didn't know, that is offers an option for mass changes

**Comment by larshp** [comment]
Closing, use #1483 

Workaround: Advanced -> Reset local
