### ISSUE TITLE
background mode, repo disappears

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#843]
if the git server returns an error, the repository disappears. 

steps to reproduce:
1: setup auto backup to abapGitServer
2: add syntax error in abapGitServer

guess the repo is deleted via the code introduced in
https://github.com/larshp/abapGit/pull/787

**Comment by apex8** [comment]
I can also confirm this behavior if the server returns some http error code

**Comment by larshp** [comment]
Also had this happen yesterday in the GUI, due to GitHub SSL issues.

Deletion happens in method DELETE_INITIAL_ONLINE_REPO, class ZCL_ABAPGIT_REPO_ONLINE
