### ISSUE TITLE
Support of object type PRAG

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#854]
This is quite an exotic one. Actually I wonder whether anybody has ever created a custom pragma.

**Comment by flaiker** [comment]
I did create one once looking through `New` context menus in SE80. But then I was clueless as how to do anything with it. I don't think pragmas even use namespaces, do they? So really difficult to do customer development with them.

I assume the main use case would be to disable custom CI checks or maybe as annotations for preprocessors / code generation.

**Comment by christianguenter2** [comment]
##TODO pragma, I somehow really like that idea 👍
