### ISSUE TITLE
SPRX	Proxy Object

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#87]

**Comment by larshp** [comment]
Looks like this just has to delegate to other serializers, object names eg. "TABLZFOOBAR", and then somehow lock the object so it cannot be edited, "You have entered a type name that is a generated proxy type. These types are not processed in the ABAP Dictionary, but using the transaction SPROXY."

**Comment by larshp** [comment]
```abap
  CALL METHOD cl_proxy_data=>delete_single_proxy
    EXPORTING
      object   = tb_fat-object
      obj_name = tb_fat-obj_name.
```

**Comment by JohannesKonings** [comment]
We want to use proxy objects with abapGit in the future. I can try to create a serialization for it.

**Comment by JohannesKonings** [comment]
CL_PXN_DB is not on NW 7.31
cl_proxy_db and cl_proxy_data can be used

**Comment by JohannesKonings** [comment]
for selection of proxy data: CL_PROXY_QUERY
