### ISSUE TITLE
Not able to clone through ABAPGIT through Gitstack

### ISSUE THREAD

**Issue by Rachanasuresh1994** [larshp/abapGit#875]
The problem I am facing is i can clone from Github, but i am using gitstack to clone as i wanted a free private repository. When i clone it through Gitstack repository( which is actually in localhost i.e a system folder), i get 'HTTP communication failure' error.

can you please tell me how to resolve this issue

**Comment by larshp** [comment]
make sure the systems are connected, use http://larshp.github.io/abapGit/other-test-ssl.html for testing

note that abapGit communicates from the SAP server to the git server, so if you use localhost then the SAP server must also be installed on localhost

**Comment by Rachanasuresh1994** [comment]
I tested it using ZABAPGIT_TEST_SSL, it gave me the following error:

Cannot connect to localhost:443 failed:NTECONN_REFUSED(-10)

Can you please tell me how to resolve this error?

**Comment by larshp** [comment]
is the SAP system also running on localhost?

**Comment by Rachanasuresh1994** [comment]
No, Its not running on localhost, and there is firewall.

Should i try with my system's IP address?

**Comment by larshp** [comment]
yes, there has to be a connection between the SAP server and the git server

Alternatively consider installing https://github.com/larshp/abapGitServer in the SAP server, note that not all normal git features works in abapGitServer, but most of the features needed for abapGit is implemented

**Comment by larshp** [comment]
closing, related https://github.com/larshp/abapGitServer/issues/78
