### ISSUE TITLE
Error: PREFIX: Unexpected package naming (/NMSPC/MAPPING)

### ISSUE THREAD

**Issue by apex8** [larshp/abapGit#877]
Hi,

I created an offline repository and added a main package of a project to it. The main package is named somewhat like /NMSPC/MAIN. It has an embedded package named like /NMSPC/MAPPING. 

Now I always get the error Error: PREFIX: Unexpected package naming (/NMSPC/MAPPING).
In the code (line 6894, version 1.3.3.7) where this issue is raised I found some comment:
* if abapGit project is installed in package ZZZ, all subpackages should be named
* ZZZ_something. This will define the folder name in the zip file to be "something",
* similarily with online projects. Alternatively change to FULL folder logic

So I´m asking what is the purpose of enforcing this? ABAP itself doesn´t have any problem with the name of those two related packages? Is it a bug?

Regards

**Comment by larshp** [comment]
it is actually a feature 😄 

the PREFIX and FULL logic is described in http://larshp.github.io/abapGit/ref-dot-abapgit.html

You can change the setting to FULL in "Advanced" -> "Repo Settings"

**Comment by apex8** [comment]
Ah I see, Thanks!
I see the point in the PREFIX logic. However personally I have my trouble with the PREFIX logic, because
* registered Namespaces can be long
* the length of package names is limited
* whenever possible I try to prevent using abbreviations in names, because of possible misunderstandings

Anyway its good to know that there is an alternative. Is there any further technical drawback using FULL except for longer shorter folder names?

**Comment by larshp** [comment]
nope, no known drawbacks

See https://github.com/SAP2Moose/SAP2Moose for an example where FULL folder logic is used

**Comment by larshp** [comment]
@apex8 can we close the issue?

**Comment by larshp** [comment]
closing
