### ISSUE TITLE
abapgit v1.37.7 Syntax errors with SAP_ABA 702

### ISSUE THREAD

**Issue by apex8** [larshp/abapGit#878]
Hi,
minimum requirement for abap git is 702. I´m working on such a system and there are two syntax errors in the program along with component version 702.

1. class lcl_http, method is_local_system: invalid line 
  lcl_exit=>get_instance( )->change_local_host( changing ct_hosts = lt_list ).
  changed to:
  data instance type ref to lif_exit.
  instance = lcl_exit=>get_instance( ).
  instance->change_local_host( changing ct_hosts = lt_list ).
2. class ltcl_html_action_utils, method _hex_to_char: invalid line
  cl_abap_conv_in_ce=>create( )->convert( EXPORTING input = i_x IMPORTING data = r_s ).
  changed to:
  data instance type ref to cl_abap_conv_in_ce.
  instance = cl_abap_conv_in_ce=>create( ).
  instance->convert( exporting input = i_x importing data  = r_s ).
 
Sorry for not providing a patch for this. I´m still having issues setting this up.

Regards

**Comment by larshp** [comment]
thanks, only a few of us have access to 702 systems, so sometimes downporting is needed

**Comment by larshp** [comment]
try again, latest version

**Comment by larshp** [comment]
closing
