### ISSUE TITLE
DIAL	Dialog Module

### ISSUE THREAD

**Issue by djoanadan** [larshp/abapGit#879]
When I try to export development package, this message occurs "Object type ignored, not supported: DIAL-RP_9298".
This object is not allowed. 
I create an infotype and it needs an object RP_9298 Dialog.
Someone know How do I put this in my project?

Thanks.

**Comment by larshp** [comment]
Hi,
DIAL objects are currently not supported in abapGit, http://larshp.github.io/abapGit/ref-supported.html

**Comment by christianguenter2** [comment]
I did a first try to implement DIAL. Feedback appreciated.

**Comment by larshp** [comment]
@christianguenter2 code looks good, feel free to submit it as a PR, I have some time to test it tomorrow...

**Comment by larshp** [comment]
@djoanadan try again, latest version

**Comment by larshp** [comment]
closing
