### ISSUE TITLE
Error table Maintenance Dialogue Generation

### ISSUE THREAD

**Issue by djoanadan** [larshp/abapGit#880]
I just hauled my development package to the environment and the following problem appears.
The maintenance dialog (function group )  from tables is not recognized to the table.
I need to modify the table and in the menu "Utilities" select the "Table Maintenance Generator" option and recreate the objects.
Exists another way to do this?

Thanks!

**Comment by larshp** [comment]
is not recognized to the table? what is the exact error? can you provide the steps to reproduce? Is it possible to create a dummy example and put it in a public repository on Github?

**Comment by djoanadan** [comment]
I sent you a step by step doc and the created project.
[ZTESTEHUB_20170803_140033.zip](https://github.com/larshp/abapGit/files/1198035/ZTESTEHUB_20170803_140033.zip)

[Error abapgit.docx](https://github.com/larshp/abapGit/files/1198028/Error.abapgit.docx)

**Comment by larshp** [comment]
hmm, I recommend creating a repository on github, see https://help.github.com/articles/create-a-repo/
and adding the steps here in the issue, see https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

I try not to open attached files in emails, and use the same approach on github

**Comment by larshp** [comment]
entries in TDDAT, TVDIR, and TVIMF are missing, the entries are part of TOBJ as described in SAP note 1435408

**Comment by larshp** [comment]
@djoanadan try again, latest version
