### ISSUE TITLE
runtime error OBJECTS_OBJREF_NOT_ASSIGNED_NO when pulling xml mime object

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#886]
This runtime error occurs when we try to pull a xml mime object which was changed in the remote.
![image](https://user-images.githubusercontent.com/17437789/29006921-7d6434dc-7af9-11e7-852c-b0ba566e129f.png)

![image](https://user-images.githubusercontent.com/17437789/29006922-7ee961ec-7af9-11e7-9bf9-522b9ac0993b.png)

Steps to reproduce:
1) upload a xml file into the mime repo
2) stage and commit with abapGit
3) change the file in the remote (e.g. add an empty line)
4) try pull the changed file in abapGit -> dump occurs

**Comment by larshp** [comment]
can you help creating a public repository here on github that reproduces the error?

**Comment by christianguenter2** [comment]
Sure, 
https://github.com/christianguenter2/ISSUE_886
You need to clone the repository and then change the test.xml file on github

**Comment by larshp** [comment]
Call stack:
![image](https://user-images.githubusercontent.com/5888506/29035915-9592ddc0-7b9d-11e7-8579-8a9b7b18facf.png)

**Comment by larshp** [comment]
@christianguenter2 try again, latest version

happy golfing

**Comment by christianguenter2** [comment]
Great, thank you.

Feel free to join the golf club ;-)
