### ISSUE TITLE
702 downport

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#890]
see https://github.com/larshp/abapGit/commit/af93a489db35f480e2bcd70a0356e49e96d3d29c#commitcomment-23580513

**Comment by tjankow2** [comment]
hi, the problem is ony with this line now:
lcl_exit=>get_instance( )->change_local_host( CHANGING ct_hosts = lt_list ).

**Comment by larshp** [comment]
@tjankow2 try again, latest version

**Comment by tjankow2** [comment]
It's fine now, thanks.

**Comment by larshp** [comment]
👍 closing
