### ISSUE TITLE
Programs and classes are not imported on DDIC activation failure

### ISSUE THREAD

**Issue by tjankow2** [larshp/abapGit#891]
Hi,
I'm doing zip import of offline repository as I want to move some development between systems.
abapGit deserializes objects in groups: DDIC, Objects, Late
when DDIC fails during activation, further objects are not imported at all. Is is expected behavior?

RS_WORKING_OBJECTS_ACTIVATE gives up and returns error
Message 062(DT) Correct the faulty objects,
it's propagated to abapGit as exception.

I would like to fix the issue later after importing everything. Currently I just commented out activation part ;) can we make abapGit to ignore activation errors? (e.g. some setting?).

**Comment by larshp** [comment]
hmm, guess this is special for DDIC, for programs there is usually an option to "Activate anyway"

to clarify, it fails in the following function module call, and then the exception is raised which prevents the activation of the rest of the objects? what is the value of `sy-subrc`?

```abap
      CALL FUNCTION 'RS_WORKING_OBJECTS_ACTIVATE'
        EXPORTING
          activate_ddic_objects  = iv_ddic
          with_popup             = abap_true
        TABLES
          objects                = gt_objects
        EXCEPTIONS
          excecution_error       = 1
          cancelled              = 2
          insert_into_corr_error = 3
          OTHERS                 = 4.
      IF sy-subrc <> 0.
        lcx_exception=>raise( 'error from RS_WORKING_OBJECTS_ACTIVATE' ).
      ENDIF.
```

**Comment by tjankow2** [comment]
sy-subrc is set 4, system variable message is set to DT 062.
there is no option to activate objects anyway (inside of FM on activation failure).

I'll be struggling with importing of program and classes that will fail for sure, so I can compare behavior of RS_WORKING_OBJECTS_ACTIVATE between DDIC and prgograms/clases. I'll let you know.

**Comment by tjankow2** [comment]
You're completely right. On failure in activation of ABAP classes I get pop-up.

Errors or problems discovered during check
What do you want to do?
Activate Anyway, Display Errors, Cancel

**Comment by larshp** [comment]
Which kind of DDIC object triggered the DT062 error?

**Comment by tjankow2** [comment]
Hi, this error is raised by FM RS_DD_WORKLIST_ACTIVATE no matter if I test it on 702 or 750.
BUT - on 702 this message returned by RS_WORKING_OBJECTS_ACTIVATE but on 750 is overwritten with some other (strange) message :)

However in both cases I don't get pop-up allowing me to activate objects with errors.

You can try to test RS_WORKING_OBJECTS_ACTIVATE with two TABL entries (structures). E.g. define structure with some field without data type assigned. then try to activate both via this FM. Error occurs in RS_DD_WORKLIST_ACTIVATE around line 180 and no further pop-up is raised by SAP.

**Comment by mbtools** [comment]
DDIC activation has been replaced by DD_MASS_ACT_C3 with proper logging. We also made other improvements like https://github.com/larshp/abapGit/pull/3545. Please open a new issue if you still have issues with DDIC activation.
