### ISSUE TITLE
Unsupported ENHO type prevent exporting

### ISSUE THREAD

**Issue by pacroy** [larshp/abapGit#894]
I'm working in offline mode and tried to export ZIP but got the error message "Unsupported ENHO type WDYENH". Can abapGit continue to export supported items and skip unsupported ones?

**Comment by larshp** [comment]
ENHO is a bit special, since abapGit supports some of the ENHO types, it is not ignored. As a temporary workaround you can change the abapGit code to skip the troublesome object

**Comment by larshp** [comment]
@pacroy try again, latest version

**Comment by pacroy** [comment]
Work great. Good job! @christianguenter2
