### ISSUE TITLE
source_new, access permission exception

### ISSUE THREAD

**Issue by Gekke-Jakke** [larshp/abapGit#900]
When importing a new class / interface with a namespace the import fails with exception source_new, access permission exception.

![image](https://user-images.githubusercontent.com/2744548/29654377-4b6910e4-88ad-11e7-9fa1-9ddc0ead8ef2.png)

When I skip this section in the importing logic (with go to statement in debugging) everything imports fine
![image](https://user-images.githubusercontent.com/2744548/29654434-7f3ca9d0-88ad-11e7-826e-9be6f99ad088.png)

**Comment by larshp** [comment]
is the namespace registered and all? Does it work creating the class manually in AIE?

**Comment by Gekke-Jakke** [comment]
The namespace is correctly registered in SE03 and the namespace is flagged as modifiable.
Creating a new class manually didn't give any error. (And if I skipped above code block everything worked fine)

Side information, I imported a project in an S/4 system.

**Comment by larshp** [comment]
In my test system, the settings are initialized in CL_OO_FACTORY, and it looks like it is not dependent on namespace. Does it work without the namespace?

Plus try tracking where the modification_allowed variable in settings is initialized

**Comment by larshp** [comment]
I dont have access to do namespaced development, so I cannot help testing/debugging this issue

**Comment by larshp** [comment]
@Gekke-Jakke can you try again, this might have been fixed as part of https://github.com/larshp/abapGit/issues/968

**Comment by Gekke-Jakke** [comment]
@larshp seems to be solved! Did an import in a brand new S4 system and didn’t run into this same issue!
