### ISSUE TITLE
'reset local' should remove locally added files

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#902]
Recently @flaiker started a discussion in slack about 'reset local' not deleting any objects. And therefore after switching branches and 'reset local' the existing objects from previous branches are marked as new.
I think it would be quite useful if 'reset local' deletes the superfluous objects.

Some questions regarding implementation. Should we ask the user before the objects are deleted? For every object? Any opinions?

**Comment by christianguenter2** [comment]
I did a first try to implement this feature.

https://github.com/christianguenter2/abapGit/blob/1de786ef7dbc2084c1fe64cdce1544af015bf4f5/src/zabapgit_services_git.prog.abap#L84-L112

Should we extract the logic to a separate method? Where is the right place for the method?
Feedback is appreciated.

**Comment by larshp** [comment]
ask user: yes. I dont have an opinion on the level, just having the user knowing what is happening is good

please add it as a separate method

it could be nice to have the method somewhere different than in `lcl_services_git` as it is not core git functionality, perhaps `lcl_repo_online`, however that class is getting large, hmm

**Comment by christianguenter2** [comment]
I extracted the method to lcl_repo_online and introduced a popup to ask the user. 

https://github.com/christianguenter2/abapGit/blob/fea262fb323497ec65fded9a515619baba0c97c7/src/zabapgit_services_git.prog.abap#L73-L85
https://github.com/christianguenter2/abapGit/blob/fea262fb323497ec65fded9a515619baba0c97c7/src/zabapgit_repo_impl.prog.abap#L324-L368

![image](https://user-images.githubusercontent.com/17437789/29785705-db34181c-8c28-11e7-8ba9-72430f2c7774.png)

I did also some further testing. For my purposes it's sufficient. Should I make a pull request?

**Comment by larshp** [comment]
cool, can you add the number of objects that will be deleted, as information in the popup?

**Comment by christianguenter2** [comment]
Good idea.

![image](https://user-images.githubusercontent.com/17437789/29787869-d566ba54-8c30-11e7-96b6-db3bb07eac8d.png)

And the popup is now only shown if there are any unnecessary objects.
