### ISSUE TITLE
CLAS deserialization performance

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#904]
Installing
https://github.com/larshp/abapGit-global/tree/master/src
seems to take forever on my laptop(750SP2, ASE database). (Note that the repository might contain syntax errors)

relevant for #773 

Seems to be mainly due to
`        FROM dwinactiv AS dw LEFT OUTER JOIN sabap_inactive AS dwa`
which is performed in method _GET_ALL in local implementation of class `CL_WB_WORKING_AREA`

**Comment by larshp** [comment]
forever = more than an hour

abapGit calls fm `SEO_CLASS_CREATE_COMPLETE` which will always try to insert into the working area, will try to check if there is any ADT functionality that can be used instead(on new versions)

**Comment by larshp** [comment]
ADT uses the same function module, CL_OO_ADT_RES_CLASS->CREATE_MAIN_CLASS

hmm

**Comment by larshp** [comment]
https://github.com/larshp/ABAP_Mass updated, supports mass creation of classes

**Comment by larshp** [comment]
Creating the raw class is now quite fast, but there is a similar problem with `CL_OO_CLIF_SOURCE`

**Comment by larshp** [comment]
some testing done in https://github.com/larshp/CLAS_rewrite

looks like the kernel performance for INSERT REPORT is bad for the first method, found an evil hack to fix this

**Comment by larshp** [comment]
PR opened, functionality can be enabled via the experimental switch.

Installing abapOpenChecks, ~80 classes:
old code: 4m25s
new code: 2m06s

**Comment by christianguenter2** [comment]
I did some testing and didn't spot any issues so far.

**Comment by larshp** [comment]
closing
