### ISSUE TITLE
QUESTION: How to Trigger Clone/Pull from Remote via HTTP Call

### ISSUE THREAD

**Issue by manuack** [larshp/abapGit#906]
Hi,

On short notice I have to automate some tasks (CI). Therefor I have to trigger the Clone and Pull command via an HTTP call.

What's your advice to achieve that?

From my point of view I could start with https://github.com/larshp/abapGit-global and create an HTTP endpoint (if_http_extension).
In that endpoint (class) I could do somethign like ...
`      DATA: lo_repo TYPE REF TO zcl_abapgit_repo_online.

        lo_repo = zcl_abapgit_app=>repo_srv( )->new_online(
           iv_url         = gitrepositoryurl
           iv_branch_name = gitrepositorybranch
           iv_package     = abappackage
        ).

        DATA: iv_key TYPE zcl_abapgit_persistence_repo=>ty_repo-key.
        iv_key = lo_repo->get_key( ).
        zcl_abapgit_app=>user( )->set_repo_show( iv_key ).
        COMMIT WORK.
`
... to add the remote gir repo to ABAPGit.

Then I need to do the **lo_repo->deserialize( )** stuff right?

Thanks,
Manuel

**Comment by larshp** [comment]
Hi,
The abapGit-global does not work yet, it is work in progress.

However, I recommend setting up background mode for your repository, and then triggering a background job from the http hook. See https://github.com/larshp/abapGit/issues/244

Note that background mode will run for all repos setup for background mode

**Comment by larshp** [comment]
@manuack did this work out for you? If you need to control multiple repositories we need #773 solved first

**Comment by manuack** [comment]
Yes, it is working. 
I wrote some lines to create the repo clone first.
After that I use the mentioned backround mode to pull the repo automatically.

Thanks,
Manuel
