### ISSUE TITLE
DEVC Package / "development class" (missing parts)

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#909]
For the package concept to work fully also in regards to package interfaces and package checks there are still some parts missing. Currently packages are created on clone utilizing the folder strategy defined in .abapgit.xml . Package attributes are not included in the abapGit repository. This includes:
- Package type (main package, structure package, development package)
- Package encapsulation flag
- Short description
- Application component
- Package interface usages and error severity

To version these attributes DEVC must be included in serialization and deserialization. Some stuff that might complicate things:
- The "local" packages where a repository is installed in can be named differently than the DEVC objects in the repo. A mapping must be used.
- The package concept has been changed a number of times within the release range that abapGit supports (like client/server checks, semantic interfaces, ...).
- Package hierarchies have restrictions. I. e. a main package cannot contain development objects other than subpackages and package interfaces.

In a second step package interfaces might be used as a _weak_ package / dependency management concept across abapGit repositories.

More thoughts can be found in today's slack discussion.

**Comment by flaiker** [comment]
Progress over here: https://github.com/flaiker/abapGit/tree/packages

**Comment by flaiker** [comment]
Another thing: the package interface needs to exist to be able to define it in the usage declaration of a package. Unless you use this internal switch.... (DEVELOPER is my username)

![image](https://user-images.githubusercontent.com/5270359/30005007-8c4f975c-90d9-11e7-99df-4f95fe5b1bd3.png)
The package then gets anonymized in the usage declaration:

![image](https://user-images.githubusercontent.com/5270359/30005013-b95b1212-90d9-11e7-9a98-f51fc3386253.png)
Would probably be better to deserialize package interfaces usages after the package interfaces themselves, instead of relying on some undocumented internal system switch.

**Comment by larshp** [comment]
the sequence of object types is managed in `METHOD prioritize_deser.`

**Comment by flaiker** [comment]
Changing the priority worked
