### ISSUE TITLE
Error deserializing EHNS

### ISSUE THREAD

**Issue by apex8** [larshp/abapGit#913]
I have an enhancement spot definition with a single BAdI definition in my project and deserializing it results in an error message followed by an abort of the pull.
error message: "Error occured while deserializing EHNS: Activity cancelled"
Specifically the call of cl_enh_factory=>create_enhancement_spot() in class lcl_object_enhs method deserialize fails.

I dived a bit deeper and the error is thrown because no task (transport) can be determined. Specific error message is "No task for editing objects can be determined", but isn´t handed over to the caller.

The other objects that are created during the pull are asking for the transport request, so I guess the problem here is using the *dark = abap_true* parameter of cl_enh_factory=>create_enhancement_spot().

I set the parameter dark to abap_false which appears to solve the problem - no more abort.

I try to create a pull request for that.

**Comment by apex8** [comment]
Although the ssl test worked for me, I cannot create a branch and/or push to the github repository. So for now, here is what I changed:

@@    68 @@ CLASS lcl_object_enhs IMPLEMENTATION =>   METHOD lif_object~deserialize
--
  |   |  
  |   | lv_package = iv_package.
  |   |  
  |   | TRY.
  |   | cl_enh_factory=>create_enhancement_spot(
  |   | EXPORTING
  |   | spot_name      = lv_spot_name
  |   | tooltype       = cl_enh_tool_badi_def=>tooltype

  |   | -            dark           = abap_true
  |   | +            dark           = abap_false
  |   | compositename  = lv_parent
  |   | IMPORTING
  |   | spot           = li_spot_ref
  |   | CHANGING
  |   | devclass       = lv_package ).
  |   |  
  |   | lo_badidef_tool ?= li_spot_ref.

**Comment by apex8** [comment]
created pull request #915

**Comment by larshp** [comment]
@apex8 can we close this issue?

**Comment by apex8** [comment]
Of course!
