### ISSUE TITLE
export to ZIP:   ASSERTION_FAILED on WAPA object

### ISSUE THREAD

**Issue by zloylom** [larshp/abapGit#916]
Hi!
Get dump on assert after line 
33619 lo_page->get_event_handlers( 
with type=WAPA.

Is there a way to avoid  it?

Dump is attached.
[dump1.txt](https://github.com/larshp/abapGit/files/1276826/dump1.txt)

**Comment by larshp** [comment]
from the dump it looks like `sy-subrc = 2`, and the standard code throws INVALID_CALL if it is a so2_controller? So I guess these have to be skipped

![image](https://user-images.githubusercontent.com/5888506/30055849-faf49380-9230-11e7-834b-fa51acce5c64.png)

**Comment by christianguenter2** [comment]
@zloylom Could you please try again with latest build?

**Comment by christianguenter2** [comment]
I'll close...

**Comment by zloylom** [comment]
Works fine now
Thanks a lot!
