### ISSUE TITLE
Getting message "nothing to merge"

### ISSUE THREAD

**Issue by suynwa** [larshp/abapGit#917]
Using abapGit v1.41.0 with abapGitServer (Backend Basis 750 Sp6)

1. Trying to merge branch into the master
![image](https://user-images.githubusercontent.com/31508041/30104770-e258b2d6-92f6-11e7-9983-8f4a77d25424.png)
![image](https://user-images.githubusercontent.com/31508041/30104940-621271ec-92f7-11e7-972a-ee4ab2d6031b.png)

2. Clicking on "Merge" gives the error message --> "nothing to merge" 

aGS Repo looks like this:
**Master**:
![image](https://user-images.githubusercontent.com/31508041/30105140-f80b470a-92f7-11e7-9589-1c36edc111f8.png)

**Branch**:
![image](https://user-images.githubusercontent.com/31508041/30105195-25abdc88-92f8-11e7-80a4-5a2c680d1797.png)

What might be the reason? Am i doing something wrong?

**Comment by larshp** [comment]
Hi,
You are not doing anything wrong, it is just the merge functionality in abapGit that is not very good

https://twitter.com/LarsHvam/status/898500463900884992

Keep the issue open, hope to fix it sometime

**Comment by larshp** [comment]
possible workaround: try a different git client than abapGit and use it to do the merge

**Comment by larshp** [comment]
@suynwa try latest version, https://github.com/larshp/abapGit/pull/1407 has been merged

**Comment by larshp** [comment]
closing
