### ISSUE TITLE
Serialization/Deserialization of FUGR

### ISSUE THREAD

**Issue by grahamrobbo** [larshp/abapGit#918]
This may be related to #914 

Just installed abapGit v1.41.1 on a new NW 7.51 SP2 install and pulled down one of my repos with a function group in it. abapGit reports include is missing on local repo when in fact it is there.

![image](https://user-images.githubusercontent.com/1305633/30144087-73415408-93cc-11e7-8d00-854dc0fa354b.png)

![image](https://user-images.githubusercontent.com/1305633/30144100-7e97924a-93cc-11e7-916e-3bf3678db4c6.png)

This worked fine with v1.41.0 a few days ago. Use repo https://github.com/Yelcho/sapui5-deployer to see the exact example.

**Comment by grahamrobbo** [comment]
FYI - I just updated to v1.41.1 from 1.41.0 on my NW 750 system uninstalled and reinstalled my repo and I see the same issue.

**Comment by larshp** [comment]
hmm, okay, thanks

**Comment by larshp** [comment]
note that in the first screenshot it is only the Textpool (TPOOL) entry that is missing, not the include itself?

**Comment by grahamrobbo** [comment]
Of course it is 
![image](https://user-images.githubusercontent.com/1305633/30149800-6262f388-93ec-11e7-9184-2647eba6d44b.png)

**Comment by larshp** [comment]
The local version contains a description for the include, while it does not exist in the remote.

Suggest pushing the description to remote, as the code is better than before?

**Comment by grahamrobbo** [comment]
Done that - all looks good.
