### ISSUE TITLE
DDLS error uninstalling

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#920]
Error while uninstalling https://github.com/jasper07/Teched17

Guess this is due to dependencies, however did not debug it

![image](https://user-images.githubusercontent.com/5888506/30240783-faf14a74-9576-11e7-9c22-dd0404e96d79.png)

**Comment by christianguenter2** [comment]
Yep, CDS view Zi_Te_Flight is used by other views. The same error occurs when I try to delete it in eclipse.
![image](https://user-images.githubusercontent.com/17437789/30916658-397ad1b2-a39a-11e7-8da9-3f98f1fbc89c.png)

**Comment by larshp** [comment]
hi,
in https://github.com/larshp/abapGit/blob/e81748abdfdb3ba8b19ce0ed52b0ce2f1503f608/src/zabapgit_objects_impl.prog.abap#L280 there is special code to handle the deletion sequence of objects, if we can find the dependencies for the DDLS, then we can make sure these are deleted first

**Comment by christianguenter2** [comment]
sounds like a good idea. I'll try it.

**Comment by larshp** [comment]
closing, now the repo can be uninstalled
