### ISSUE TITLE
DDLS skip generated SADL classes

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#921]
In https://github.com/jasper07/Teched17 2 clases are automatically generated by SADL, the generated classes should be skipped by abapGit

Example: ZCL_ZC_TE_FLIGHT

![image](https://user-images.githubusercontent.com/5888506/30240789-271356d8-9577-11e7-84c6-7aacda5432f6.png)

**Comment by EduardoCopat** [comment]
I couldn't find anything on the `VSEOCLASS` view (class metadata) that indicates that a class was generated. One option is to check if the class inherits from CL_SADL_GTK_EXPOSURE_MPC and skip it.

Any other options?

**Comment by larshp** [comment]
my guess is that there some where deep down in the SADL code is a table containing the names of the generated classes, ie. when changing the CDS I guess it has to regenerate the class

**Comment by EduardoCopat** [comment]
Yes. You are probably right :)

In method `CL_SADL_GTK_MPC_GEN=>_generate_class` if you go to `cl_sadl_transport_adapter=>get_instance( )->set_gen_flag`, it marks a gen_flag in the TADIR

**Comment by larshp** [comment]
Something like this, skip if
* Exists DDLS with name ZCL_{ ddls_name }
* Class has TADIR-GENFLAG = abap_true
* and inherits from CL_SADL_GTK_EXPOSURE_MPC
will it work?
