### ISSUE TITLE
Syntax error in 1.41.2

### ISSUE THREAD

**Issue by ElNovi** [larshp/abapGit#926]
I get this syntax error when i try to copy and paste new version. Previous version was 1.41.1

![image](https://user-images.githubusercontent.com/14199592/30430339-3535a0e4-995b-11e7-8f47-a87e608e9ecc.png)

**Comment by larshp** [comment]
ahh, thanks, sorry

Temporary workaround is just to comment out the code, LCL_OO_CLASS_NEW is only used if you enable the experimental features.

will fix

**Comment by larshp** [comment]
@ElNovi try again, latest version

**Comment by ElNovi** [comment]
Thanks a lot, it works now :)
