### ISSUE TITLE
GitLab Enterprise Account Support

### ISSUE THREAD

**Issue by Sdfraga** [larshp/abapGit#929]
Hello,

My company has a private account in GitLab and I am trying to connect abapGit to it.

I have installed the needed certificates but when I ran ZABAPGIT_TEST_SSL with the link https://git.teamwork.net/ I have an http error.

It seems it is an authentication error because this URL immediatly asks for user and password.

Am I missing something or there is no support for this type of private accounts in abapGit?

Thanks for you help
Sérgio Fraga

**Comment by larshp** [comment]
it should work with authentication, if you get to the user and password then I guess the SSL is set up correctly

try in ZABAPGIT and see what happens 😄

**Comment by Sdfraga** [comment]
Hi Lars, 

thanks for your prompt reply.

The thing is that I can't access from my SAP system to the private GitLab account.

The program to test the SSL returns me an error and if I try to clone a repository with abapGit I get an HTTP connection error.

I have asked my Basis team for help but I did not have any luck. 
They tell me the SAP system can't reach the site due to the credentials missing..

**Comment by larshp** [comment]
what is the http error code? shown in the test program via `WRITE: / 'Error', lv_code.`

**Comment by Sdfraga** [comment]
Error message: Connect to git.teamwork.net:443 failed: NIECONN_REFUSED(-10)

**Comment by larshp** [comment]
okay, this error happens if there is no connection between the SAP system or SSL is not set up correctly, can you check SMICM -> Goto -> Trace File -> Display End, it shows additional information in case SSL is not setup correctly

also make sure there is a network connection between the SAP system and the git server, you can try to ping the server via transaction SM69, there might be a firewall depending on your setup

**Comment by Sdfraga** [comment]
The connection between SAP and the web is OK since I can use abapGit with success with gitHub or even if I test the public gitLab your SSL test program ends with success.

I have tried to analyze it but it's honestly I am lost with this log.
[SMICM.pdf](https://github.com/larshp/abapGit/files/1325190/SMICM.pdf)

Thanks a lot for your help

**Comment by larshp** [comment]
hmm, the log looks okay, did you try pinging the server from SM69?

To me this looks like a basis problem, hmm

**Comment by Sdfraga** [comment]
I feel the same but it will be a difficult task.. The last response from the basis was that SAP cannot send the credentials to the server....

Regarding SM69 I never used it but I will give it a try.

**Comment by larshp** [comment]
looks like git.teamwork.net is not configured to respond to ping requests, hmm

**Comment by Sdfraga** [comment]
How can I use SM69?
I should know the IP address of git.teamwork.net right?
This is managed by a different team in the company

**Comment by larshp** [comment]
SM69: ping is not configured on git.teamwork.net so this test will not work

I recommend consulting with your basis/network/server people, the log looks okay, hmm

**Comment by Sdfraga** [comment]
I will try to contact the git dedicated team and check if they can help since from the basis I am not that confident.

By the way, do you know why abapGit does not work via Eclipse?
I just get an empty screen.
Apparently, the HTML you are generating with abapGit does not render in the GUI if it's a session is opened via Eclipse.

**Comment by larshp** [comment]
It is always difficult with the SAP basis team 😄 

I do not use Eclipse, and so far there have not been any issues reported that it does not work, or are you running SAP GUI on Java, or a non Windows setup?

**Comment by Sdfraga** [comment]
Yes true, especially if you arrive with topics like Git on SAP world...

I am using SAP GUI on Java. Check the result
<img width="1680" alt="abapgit on eclipse with sap java gui" src="https://user-images.githubusercontent.com/16186872/30756885-ae39ca34-9fcc-11e7-9701-f3af139f34b2.png">

**Comment by larshp** [comment]
hmm, does it work if you start ZABAPGIT in SAP GUI Java outside of Eclipse? 

There have been some issues with SAP GUI Java over the years, see https://github.com/larshp/abapGit/issues/110

Also which version of SAP and SAP GUI Java are you running?

**Comment by Sdfraga** [comment]
It works if I executed it via the SAP GUI Java directly.

SAP Version: 751

SAP GUI for Java 7.40
(Version ID 074000040000)
2014-12-03 06:00:42 +0100
ldm049, 740_REL, 1541807
Java VM: Oracle Corporation Version 1.8.0_131
OS: Mac OS X(x86_64) Version 10.12.6

I will have a look to Issue #110

**Comment by Sdfraga** [comment]
The demo programs that you refer in #110 works fine via Eclipse so it seems is just abapGit that is not being rendered

**Comment by larshp** [comment]
okay, can you open a separate issue for the Java GUI in eclipse?

regarding the connection problems, feel free to join the slack channel, https://abapgit-slackinviter.herokuapp.com/ it might be easier

**Comment by Sdfraga** [comment]
Deal

**Comment by Sdfraga** [comment]
I have tested the same scenario but with a different SAP machine and everything worked fine.
It's a system configuration that is not correctly defined and I will have to solve it with my Basis team.
