### ISSUE TITLE
Pull: Overwrite all local objects

### ISSUE THREAD

**Issue by apex8** [larshp/abapGit#932]
Hi,

when pulling there are always a lot of objects identified that were adjusted locally. Even without touching the objects after deserialization and generation there are differences when the objects will be serialized. At least for me those differences don´t make any difference and I would just ignore them. So in the end depending of the number of objects it´s a bit annoying to confirm a lot of confirm popups.

That´s why I would like to ast if some 'overwrite all' dialog option would be some improvement for the project.
As an additional configurable button won´t work for the FM popup_to_confirm and a custom built dialog would mean a couple of new global objects I would propose another approach:
When going through the objects and display the dialog for each one, count up to five when the user always presses 'yes'. On the 6th element some other popup_to_confirm dialog is displayed asking the user if he want´s to overwrite all. If so, then this will happen; If not the per-object-dialog query will be continued as it is now - no further counting for the current pull transaction

What do you think?

**Comment by larshp** [comment]
yeah, it is annoying, both the popup and the fact that the check does not work as intended

also see https://github.com/larshp/abapGit/issues/704

**Comment by apex8** [comment]
@larshp Something like this could be implemented quite easily using a salv table with some checkboxes in the first column. I did this before, it´s not much code. If you want I can adopt this for here.

**Comment by larshp** [comment]
feel free to submit a pull request 😄 

however there is a risk this might be refactored in the future, I would like to have a reuseable selection list using HTML like the rest of the abapGit gui, plus we need this part refactored to work in a RESTful manner ie. via API calls.
These are all ideas, and will take some time to implement, and users will benefit having an ALV in the meanwhile

**Comment by apex8** [comment]
@larshp see PR #934

**Comment by larshp** [comment]
PR merged, can the issue be closed?

**Comment by apex8** [comment]
yeah, sure
