### ISSUE TITLE
Support for ABAP 702

### ISSUE THREAD

**Issue by gfroggy** [larshp/abapGit#933]
Hi Lars,
thanks for this awesome tool, which I would love to use on a ABAP 702/SP11 system. Unfortunately the report cannot be activated because class "cl_oo_class_section_source" constructor is expected to have the following parameters, which it does not have in our release:
```
source
suppress_constrctr_generation
```
The activation error thus happens in the method `update_meta`

I believe it should have been working on our release a little while ago, at least if I refer to #789 , which was an SP06 system.
Any chance to get it working or am I just out of luck?

Thanks for looking into this,
Arno

**Comment by larshp** [comment]
hi, just comment out the contents of the method `update_meta`, it is part of some in-progress code #904 

can you paste the parameters for the constructor?

**Comment by gfroggy** [comment]
Hi,
wow, thanks for the fast answer. It does activate now and at a first glance seems to be working fine. Thank you!

These are the parameters for the constructor:
```
CLSKEY          TYPE SEOCLSKEY
EXPOSURE	TYPE SEOEXPOSE
STATE	        TYPE C
```
All are mandatory and "pass value".
Please let me know if you need any more info.
BR,
Arno

**Comment by gfroggy** [comment]
Oops, I just closed it. Please just reopen it if you need it to keep track of this....

**Comment by larshp** [comment]
@gfroggy try again, latest version

**Comment by gfroggy** [comment]
sorry for the late reply, didn't have access to that system for a couple of days. Unfortunately it is not compiling:
Error 
> Formal parameter "IM_ALSO_LOCAL_PACKAGES" does not exist.

in the following method call:
```
    cl_pak_package_queries=>get_all_subpackages(
      EXPORTING
        im_package             = iv_package
        im_also_local_packages = abap_true
      IMPORTING
        et_subpackages         = lt_packages ).
```

**Comment by larshp** [comment]
thanks, above code was added recently

**Comment by larshp** [comment]
@gfroggy try again, latest version

**Comment by larshp** [comment]
closing, feel free to open a new issue
