### ISSUE TITLE
Textpools should be read using maintenance language

### ISSUE THREAD

**Issue by thomas-erdoesi** [larshp/abapGit#935]
Textpools are not handled correctly when maintenance language does not match current logon language. In this case empty textpools for current language are compared with textpools for maintenance language and all programs are considered to be locally modified.

How to reproduce:
- Log on using a language different from EN
- Run abapGit and navigate to the abapGit repository

**Comment by thomas-erdoesi** [comment]
Issue could be fixed as follows:

`
METHOD serialize_program.

    DATA: ls_progdir      TYPE ty_progdir,
          lv_program_name TYPE programm,
          lt_dynpros      TYPE ty_dynpro_tt,
          ls_cua          TYPE ty_cua,
          lt_source       TYPE TABLE OF abaptxt255,
          lt_tpool        TYPE textpool_table,
          ls_tpool        LIKE LINE OF lt_tpool,
          lo_xml          TYPE REF TO lcl_xml_output,
          lv_subrc        LIKE sy-subrc,
          lv_curr_lang    TYPE langu,
          lv_dummy        TYPE string ##needed.

    IF iv_program IS INITIAL.
      lv_program_name = is_item-obj_name.
    ELSE.
      lv_program_name = iv_program.
    ENDIF.

    GET LOCALE LANGUAGE lv_curr_lang COUNTRY lv_dummy MODIFIER lv_dummy.
    SET LOCALE LANGUAGE mv_language.

    CALL FUNCTION 'RPY_PROGRAM_READ'
      EXPORTING
        program_name     = lv_program_name
        with_lowercase   = abap_true
      TABLES
        source_extended  = lt_source
        textelements     = lt_tpool
      EXCEPTIONS
        cancelled        = 1
        not_found        = 2
        permission_error = 3
        OTHERS           = 4.

    lv_subrc = sy-subrc.

    SET LOCALE LANGUAGE lv_curr_lang.

    IF lv_subrc = 2.
      RETURN.
    ELSEIF lv_subrc <> 0.
      lcx_exception=>raise( 'Error reading program' ).
    ENDIF.

    ...
`

`
METHOD deserialize_program.

    DATA: lv_exists      TYPE sap_bool,
          lv_progname    TYPE reposrc-progname,
          ls_tpool       LIKE LINE OF it_tpool,
          lv_title       TYPE rglif-title,
          ls_progdir_new TYPE progdir,
          lv_subrc       LIKE sy-subrc,
          lv_curr_lang   TYPE langu,
          lv_dummy       TYPE string ##needed.

    FIELD-SYMBOLS: <lg_any> TYPE any.

    ...

    SELECT SINGLE progname FROM reposrc INTO lv_progname
      WHERE progname = is_progdir-name
      AND r3state = 'A'.
    IF sy-subrc = 0.
      lv_exists = abap_true.
    ELSE.
      lv_exists = abap_false.
    ENDIF.

    IF lv_exists = abap_true.
      GET LOCALE LANGUAGE lv_curr_lang COUNTRY lv_dummy MODIFIER lv_dummy.
      SET LOCALE LANGUAGE mv_language.

      CALL FUNCTION 'RPY_PROGRAM_UPDATE'
        EXPORTING
          program_name     = is_progdir-name
          title_string     = lv_title
          save_inactive    = 'I'
        TABLES
          source_extended  = it_source
        EXCEPTIONS
          cancelled        = 1
          permission_error = 2
          not_found        = 3
          OTHERS           = 4.

      lv_subrc = sy-subrc.

      SET LOCALE LANGUAGE lv_curr_lang.

      IF lv_subrc <> 0.
        IF sy-msgid = 'EU' AND sy-msgno = '510'.
          lcx_exception=>raise( 'User is currently editing program' ).
        ELSE.
          lcx_exception=>raise( 'PROG, error updating' ).
        ENDIF.
      ENDIF.
    ELSE.
      ...
      IF strlen( is_progdir-name ) > 30.
        ...
      ENDIF.

    ENDIF.

    IF NOT it_tpool[] IS INITIAL.
      INSERT TEXTPOOL is_progdir-name
        FROM it_tpool
        LANGUAGE mv_language
        STATE 'I'.
      IF sy-subrc <> 0.
        lcx_exception=>raise( 'error from INSERT TEXTPOOL' ).
      ENDIF.
    ENDIF.
    ...
`

**Comment by larshp** [comment]
thanks, can you elaborate a bit more about the scenario? what is the master language of the git repository, vs master language in the report, vs maintained language, vs logon language?

**Comment by thomas-erdoesi** [comment]
Hi Lars,

Thanks for the quick response. All repository objects have a master language / original language / maintenance language (all terms are used for the same thing) which is stored in the file '.abapgit.xml'. I'm not sure if this is the right place because every program could have it's own master language, but this is not an issue for me right now, so I did not have a deeper look into the logic behind it.

During serialization the function RPY_PROGRAM_READ is called and this function module assumes that  SY-LANGU contains the master language. On our systems there is an optional parameter named LANGUAGE, but I'm not sure if it is present in all SAP releases. Therefore the language should either be passed to this function or SY-LANGU should be set to the master language before calling the function, otherwise the text pool will be read using the wrong language. This leads to a difference when comparing programs while logged on with a different language than the master language. The version from GIT has a title, the local version seems to be modified, because the title is empty. In fact, the title is there on the local version as well, but the wrong language was used when reading the text pool.

The same thing happens during deserialization of new versions for existing programs. Function RPY_PROGRAM_UPDATE updates the text pool for the current language (SY-LANGU) instead of the master language. Therefore updated program descriptions pulled from GIT will be stored using the current language instead of the master language. Furthermore, in this case only the program description gets updated because the INSERT TEXTPOOL is processed for new objects only. I guess this block should be moved behind the ENDIF to also update text pools for existing programs.

I hope my description is somewhat clear, otherwise feel free to ask... :-)

**Comment by EduardoCopat** [comment]
Pull requests are welcome 🤗

**Comment by thomas-erdoesi** [comment]
I don't think I'm authorized to create a branch and a pull request.

**Comment by larshp** [comment]
Fork the project, see https://help.github.com/articles/fork-a-repo/, also more information here https://guides.github.com/introduction/flow/

No authorization is needed to submit a pull request, it is open to everyone 😄

**Comment by thomas-erdoesi** [comment]
Thanks, got it. I'm doing some more testing, then I'll create the pull request.

**Comment by larshp** [comment]
Cool.

In abapGit, all objects in a repo is assumed to have the same master language, http://larshp.github.io/abapGit/ref-dot-abapgit.html

**Comment by larshp** [comment]
hmm, the code
https://github.com/larshp/abapGit/blob/e75fab654ddc2633af1fb61f3bd134b9e54f2a6f/src/zabapgit_repo_impl.prog.abap#L569
is there to make sure the sy-langu and the master language of the repo always matches. Did you first log in with one language, and then another one to export the objects?

**Comment by thomas-erdoesi** [comment]
I'm trying to reproduce the steps that lead to the issue. I'll let you know about the results.

**Comment by thomas-erdoesi** [comment]
Looks like this check is only performed when cloning to a repository or changing the current branch. 

I can reproduce the issues as follows:
1. Log in using the master language of a repository (EN) and clone the repository
2. Log in using another language (DE) and run abapGit
-> No exception, but all programs (R3TR PROG) are considered to be locally modified.

This is only a problem in connection with programs (R3TR PROG) because classes (R3TR CLAS) are aware of their master language which is written to the xml file. When the suggested code changes are applied, the master language specified for the repository will be used during serialization/deserialization of programs and the issue disappears.

Be aware that forcing users to log in using a specific language might be an issue in many corporate environments. Most users do not know their passwords because other means of authentication are used (e.g. smart cards), therefore, users cannot use the "classic" log in screen.

**Comment by larshp** [comment]
hmm, yeah, good point

merging PR, thanks 😄

**Comment by larshp** [comment]
merged, https://github.com/larshp/abapGit/pull/937 

try again

**Comment by thomas-erdoesi** [comment]
Works fine now.
