### ISSUE TITLE
Activation issues

### ISSUE THREAD

**Issue by dycsi-gabrielbaca** [larshp/abapGit#938]
When trying to install the program using SE38, I get several syntax errors, such as:

52500: Program ZABAPGIT
The statement SELECTION-SCREEN is not allowed within FORM routines and function modules.

If I remove the SELECTION-SCREEN in that line, I get the following error:

52504: Program ZABAPGIT
The statement CLASS ... DEFERRED cannot be used in a COMMON part, a FORM, a FUNCTION, a CLASS, or a GET event.

We have SAP_BASIS release 751, with SAP_ABA 75B. It is an S4HANA implementation.

**Comment by dycsi-gabrielbaca** [comment]
Please disregard, issue has been solved.

**Comment by larshp** [comment]
closing
