### ISSUE TITLE
Diff for ZCX_ABAPGIT_EXCEPTION due to ##ADT_SUPPRESS_GENERATION

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#948]
![image](https://user-images.githubusercontent.com/17437789/31053896-17f3b88c-a6a7-11e7-9240-1ff874c0e5c3.png)

I didn't anything with ADT. So I think the root cause of the diff are different netweaver versions. Can we savely add the pragma? I think so. I'll submit a PR.

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapGit/commit/87418cd125c4c6afed10c1ac045120670558476a
