### ISSUE TITLE
Locally untouched objects are not pulled if others are modified

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#949]
Seems to me like #934 introduced a regression. The popup only returns all checked locally modified objects that should be overwritten, but `ct_results` also included all other objects that need to be updated and were not modified.

In my case this prevents the update of a packages interface usages in #927 because the package interface itself is prevented from being pulled before the package is updated.

![image](https://user-images.githubusercontent.com/5270359/31056660-71bc176e-a6d5-11e7-98de-ef0a42079ab4.png)

**Comment by larshp** [comment]
yeah, anyone wants to fix this? Please add a comment here, or assign if you start looking into this
