### ISSUE TITLE
Mark all button on "Overwrite" objects pop-up

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#950]
Follow up on #934

> Yet another approach would be to use a modal dialogbox container popup. Then you can use the add_function method of cl_salv_table. Something like this.
> 
> ![image](https://user-images.githubusercontent.com/2248490/31078018-f0f4284c-a756-11e7-8880-0dcd8d2caa64.png)
> 
> 
> https://gitlab.com/christianguenter/ABAP_Demo_ALV_Popup/blob/1a1c5207158693d7260b9fd338224420b29eadd5/zcl_test_alv_popup.clas.abap

**Comment by flaiker** [comment]
Has anyone already started working on this? Reason I am asking is that fixing #949 will probably touch the same code and might cause conflict.

**Comment by larshp** [comment]
#949 is a bug, this one is just nice to have

**Comment by christianguenter2** [comment]
#954

**Comment by larshp** [comment]
keeping open until PR is merged
