### ISSUE TITLE
abapGit installer

### ISSUE THREAD

**Issue by ivanfemia** [larshp/abapGit#956]
Syntax error while activating the installer on SAP NetWeaver SAP_BASIS	731	0006

"A logical expression may not consist of just a method call." in class lcl_skip_objects

change

IF has_sadl_superclass( ls_tadir_class ).

in 

IF has_sadl_superclass( ls_tadir_class ) EQ abap_true.

Ivan

**Comment by larshp** [comment]
@ivanfemia try again, latest version, it might be a few minutes for the GitHub cache to refresh

**Comment by ivanfemia** [comment]
I see the code changed on the repo online, not yet on my local system.
Just a matter of time... We can close this issue
