### ISSUE TITLE
DEVC object out of sync

### ISSUE THREAD

**Issue by ivanfemia** [larshp/abapGit#957]
Once imported my local copy is always out of sync because I have the following tag XML added to DEVC objects

TRANSLATION_DEPTH
TRANSLATION_DEPTH_TEXT

in files
/src/package.devc.xml
/src/utils/package.devc.xml
/src/zlib/package.devc.xml 

Ivan

**Comment by larshp** [comment]
can you add a screenshot of the diff?

**Comment by ivanfemia** [comment]
Here it is
![screenshot 2017-10-05 12 32 24](https://user-images.githubusercontent.com/3193817/31241378-4ebf5568-a9c9-11e7-83b0-1477c988436b.png)

**Comment by larshp** [comment]
guess we should just clear these fields in the DEVC serialization, however I'm not sure what the fields are used for

**Comment by flaiker** [comment]
Just by chance: Is this on a customer system or SAP internal system? I saw a lot of switches regarding that distinction in the package check code. Like I cannot even set the translation depth value in the package builder.
![image](https://user-images.githubusercontent.com/5270359/31241745-2566f5a4-aa05-11e7-89a2-99562fe2d373.png)

**Comment by ivanfemia** [comment]
This is an IDES system

**Comment by flaiker** [comment]
I'll take that as a "yes" :)
@larshp Should I do a quick PR to just clear those two fields on serialization?

**Comment by ivanfemia** [comment]
I see also 

<LAYER_TEXT>Transport Layer for Local Developments (No Transport)</LAYER_TEXT>

**Comment by larshp** [comment]
@flaiker yeah, feel free, will merge tomorrow. No rush, everything works, diffs are just annoying

**Comment by larshp** [comment]
@ivanfemia try again, latest version
