### ISSUE TITLE
You may not delete or overwrite table "RT_PACKAGES" within a LOOP over itself. .

### ISSUE THREAD

**Issue by ElNovi** [larshp/abapGit#959]
I got this error when i try to do syntax check on the new verison (our version of ABAP is 731):

![image](https://user-images.githubusercontent.com/14199592/31267567-e98aec9c-aa78-11e7-8006-5147252b4846.png)

Maybe something like this as a workaround?
``` abap
   DATA: ls_package LIKE LINE OF rt_packages,
         lt_package LIKE rt_packages.

    SELECT SINGLE * FROM tdevc INTO ls_package WHERE devclass = iv_package.
    ASSERT sy-subrc = 0.
    APPEND ls_package TO rt_packages.

    LOOP AT rt_packages INTO ls_package.
      SELECT * FROM tdevc APPENDING TABLE lt_package
        WHERE parentcl = ls_package-devclass.
    ENDLOOP.
    
    APPEND LINES OF lt_package TO rt_packages.
```

**Comment by larshp** [comment]
thanks

above suggestion wont work, the code should fetch all subpackages, also children of children, hmm

**Comment by larshp** [comment]
as a workaround: just comment the LOOP, and avoid using the syntax check feature

**Comment by christianguenter2** [comment]
Maybe method GET_ALL_SUBPACKAGES of CL_PAK_PACKAGE_QUERIES does the job?

**Comment by larshp** [comment]
trying to avoid the standard code, see https://github.com/larshp/abapGit/issues/933

**Comment by larshp** [comment]
@ElNovi try again, latest version

**Comment by ElNovi** [comment]
It works, thanks a lot :)
