### ISSUE TITLE
Resolve dependencies: Refactor resolve_ddic + resolve_ddls

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#964]
Follow up on #936 

>  the RESOLVE_DDIC method builds a dependency graph and finds nodes with no inbound dependencies, these will be deleted first. We should refactor resolve_ddic + resolve_ddls out into a new class sometime in the future, this way we will also be able to write unit tests for it.

**Comment by larshp** [comment]
Hi Christian, 
This might be a candidate for refactoring into a global class, as I guess there are no dependencies to the local classes?

**Comment by christianguenter2** [comment]
Yep, I think so too. I'd first try to merge both methods and then move it to a global class.

**Comment by christianguenter2** [comment]
Regarding unit tests, class relevant types, local types and test classes seem not yet to be supported by abapmerge.  
![image](https://user-images.githubusercontent.com/17437789/31372730-79c7e672-ad97-11e7-9fb1-2a3769248bb5.png)

However what would be the overall strategy for these artifacts? I think sooner or later there will be name clashes etc.

**Comment by larshp** [comment]
class relevant types and local types:
will probably end up disallowing these, as it might cause name clashes

local test classes: 
I'm planning to ignore these in abapmerge, and only have them in the full abapGit development version
