### ISSUE TITLE
Automatic changes created during activation of exception classes are considered as local modifications

### ISSUE THREAD

**Issue by thomas-erdoesi** [larshp/abapGit#971]
When activating classes on SAP release 7.40 SP 8 or newer automatic changes may be applied to the source code. So far I noticed the following changes:
- Comments #EC NOTEXT are replaced by pragma ##NO_TEXT
- Pragma ##ADT_SUPPRESS_GENERATION is added to the constructor of many exception classes
- TYPE-POOLS declaration are removed from the section if there is nor explicit forward declaration

These code changes break compatibility with SAP releases prior to 7.31 and also create a difference in the source code that is always considered as a local modification of the class.

According to SAP note 2127087 these automatic code changes can be avoided by setting parameter SEO_SUPPRESS_PRAGMA to value 'X', so as a workaround users of SAP releases 7.40 SP 8 and newer can set this parameter when dealing with Git projects created on earlier SAP releases.
However, it might make sense to handle this issue by temporarily changing the value of this parameter during class generation based on some sort of compatibility flag stored in .abapgit.xml. Before proposing code changes I would be interested in other developers' opinions on this.

**Comment by larshp** [comment]
Yeah, it is pretty annoying

Have you tested the SEO_SUPPRESS_PRAGMA parameter?

**Comment by thomas-erdoesi** [comment]
We are using it on our development systems and it works fine in connection with SE80 and SE24. However, it does not seem have any effect in connection with the ADT methods used by abapGit. I'll try to come up with a better solution for this...

**Comment by larshp** [comment]
note that the class deserialization will use https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_clas_new.prog.abap sometime in the future

**Comment by larshp** [comment]
serialization code has been changed since 2017

@thomas-erdoesi can the issue be reproduced?

**Comment by thomas-erdoesi** [comment]
I'm going to test this with the latest version of abapgit and let you know about the results. This may take a couple of days because i have to wait until I can get two of our sandbox systems with different SAP releases for testing.

**Comment by thomas-erdoesi** [comment]
The issue still occurs in the class builder, but it no longer occurs when deserializing a class with abapGit. Therefore the issue is solved and can be closed.
