### ISSUE TITLE
Object type not supported  

### ISSUE THREAD

**Issue by vtebano13** [larshp/abapGit#977]
When I first create the repository all the objects will pull down but when I go to move them to another system I get the error Object type not supported for SRFC, AQSG, IWMO and a bunch of others.

**Comment by vtebano13** [comment]
It seems that if the object has already been created that it will push and pull the changes.  If it has to create the object then that is when it has issues.  Is this correct?

**Comment by vtebano13** [comment]
Updated to latest version and still get the error:
![image](https://user-images.githubusercontent.com/7851946/31355038-ae4734f2-ad06-11e7-9b9b-42572192ba70.png)

**Comment by christianguenter2** [comment]
@vtebano13 can you test SRFC serialization in your scenario?

**Comment by vtebano13** [comment]
Sorry been a little while.  I updated to the newest version and when I run the ZABAPGIT I get the error:
![image](https://user-images.githubusercontent.com/7851946/37043680-46638474-212f-11e8-9352-486f09ae56ed.png)

**Comment by larshp** [comment]
@vtebano13 see http://docs.abapgit.org/ref-supported.html

IWMO and IWSV is not natively supported by abapGit, but try installing https://github.com/larshp/abapGit-Plugins as noted in the bottom of the documentation

**Comment by jfilak** [comment]
@vtebano13 are you sure you want to version these objects? I do not version them because those objects are automagically generated from IWPR objects in our case (however, you need abapGit-plugins for IWPR anyways).

**Comment by larshp** [comment]
closing, see https://github.com/larshp/abapGit/issues/75 instead
