### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#991]
According to Github [community standards](https://github.com/larshp/abapGit/community), we should have a template for a new pull request.

What information could be present? An idea:

`
Fixes #
`

**Comment by afuscella** [comment]
Any updates on this ?

**Comment by larshp** [comment]
Pull requests are welcome, see https://github.com/larshp/abapGit/blob/master/CONTRIBUTING.md

**Comment by afuscella** [comment]
There's a github wiki that explains how to create a pull request template.

https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

Basically, just have to create a file called `pull_request_template.md`, and keep it on folder `docs` (public) or `.github/` (private) in the main branch.

I've create in my repo, and it should as it should.

E.g.:
https://github.com/afuscella/ABAP-Z-LAC-SHOP-MON
