### ISSUE TITLE
Fail to clone FULL folder logic

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#992]
See branch https://github.com/EduardoCopat/abap-full-sandbox/tree/failing-full-folder-logic

It has `<FOLDER_LOGIC>FULL</FOLDER_LOGIC>`

![image](https://user-images.githubusercontent.com/2248490/31443957-1ea22908-ae71-11e7-87cd-852c42cb0008.png)

**Comment by EduardoCopat** [comment]
It seems to be that the persisted dot_abapgit is `PREFIX` (from a previous pull), then I changed in the remote to `FULL`. abapGit is not accounting for this change.

Work around: Manually update the folder logic in the database.

**Comment by EduardoCopat** [comment]
It seems that abapGit has persisted this repository as `PREFIX`. I changed to `FULL` on the remote and the change was not accounted.

**Comment by larshp** [comment]
can you try again, this might've been related to https://github.com/larshp/abapGit/issues/994
