### ISSUE TITLE
Dump in LCL_FILE_STATUS=>CALCULATE_STATUS (ITAB_DUPLICATE_KEY) when trying to install ABAPGit as a repository

### ISSUE THREAD

**Issue by mkaesemann** [larshp/abapGit#994]
I wanted to try ABAPGit and downloaded ABAPGit (zabapgit.abap) to put it into the system.
According to the Wiki the way to do this would be to create a report in SE38, copy the zabapgit.abap into it, activate it, run it and click the "install abapGit" link in the main page.
At first I tried it by creating ZABAPGIT in package ZABAPGIT, but received a dump when clicking the install link. 
I thought this might be caused by me already having created the ZABAPGIT program and tried to delete everything again and recreate the "install" program as ZABAPGIT_INSTALL.
Unfortunately, the same dump occured.
So currently no matter what I do, I get the ITAB_DUPLICATE_KEY dump in the CALCULATE_STATUS method. (Full dump as HTML file: [ABAPGit Dump.zip](https://github.com/larshp/abapGit/files/1382204/ABAPGit.Dump.zip))

Since I'm completely new to ABAPGit, I have not yet tried to analyze the problem in-depth.
So far I have only figured out that neither the program name nor the development class seem to have any influence on the issue and deleteing  the entry for ABAPGit in the ZABAPGIT database table does not make any difference either.

Any pointers on what could be wrong or what I might have broken would be great. 

BTW: The certificates have been installed in the system and ZABAPGIT_TEST_SSL works. Also I'm working on a S/4HANA 1610. But I doubt either of these two things has anything to do with the dump.

**Comment by christianguenter2** [comment]
If you want to use abapGit without contributing to project itself, I guess this is what you want to do, you just have to copy zabapgit.abap into your ZABAPGIT report and you're fine. The further steps you only have  to do if you want to contribute to abapGit itself. I'd suggest to delete all objects in your package and try it again from scratch. You can also check database table ZABAPGIT for created repositories.

**Comment by mkaesemann** [comment]
Thanks for the fast response.
I wanted to connect to the repository for two reasons: 1. to easily stay up to date with ABAPGit and 2. to be able to contribute, once I get acquainted with the system and its capabilities.
Of course you are correct that I could start with a purely manually installed version, but my concern is that if I do and then have invested hours or even days to set up the repositories I either run into the dump again or am unable to connect to the ABAPGit repository without having to redo everything.
So I'd prefer it to have things running correctly from the start.
I already attempted to delete everything and redo the whole installation with the standard namesa and paths (ZABAPGIT, $ABAPGIT, $TMP) to no avail.
Is there anything that ZABAPGIT creates besides the database table ZABAPGIT and the report itself?

**Comment by antelio** [comment]
I think if fixed (or a work arround);
Change Line 14714:
` DELETE ADJACENT DUPLICATES FROM lt_items`
TO
` DELETE ADJACENT DUPLICATES FROM lt_items COMPARING      obj_type obj_name.`
CAUSE:
Two duppliocated lines for DEVC/$ABAPGIT

**Comment by larshp** [comment]
I also have the same problem 😄

**Comment by Sdfraga** [comment]
Same problem here.
Solved with @antelio correction/work around

**Comment by larshp** [comment]
there are some issues with the .abapgit.xml, will submit a PR in a bit

**Comment by larshp** [comment]
try again, latest version

**Comment by mkaesemann** [comment]
Now it works. Thanks a lot.

**Comment by nomssi** [comment]
Not sure if the fix is really included.

I had the dump triggered while doing "Advanced -> Reset Local" (ABAP-Ray Tracer project).
I use recent version of the code, but I missed @antelio work around. I repeated the process and it worked without dump.
