### ISSUE TITLE
Handling of includes without textpools

### ISSUE THREAD

**Issue by thomas-erdoesi** [larshp/abapGit#995]
Includes without a textpool (=include description) are created are either as includes with an empty description (first include) or using the description of the preceding textpool. This issue can be reproduced with function groups created on SAP releases older than 7.31.

**Comment by thomas-erdoesi** [comment]
Pull request #996 solves the issue for all my test cases.
Looks like abaplint does not support statement DELETE TEXTPOOL.

**Comment by larshp** [comment]
new abaplint released, and build restarted

Will look into the PR

**Comment by larshp** [comment]
merged
